### PR TITLE
Add wavesurfer.js@2.0.4 & update package.json

### PR DESCRIPTION
**Pull request by thijstriemstra**
Update author & license and add homepage info of wavesurfer.js and add wavesurfer.js@2.0.4 w/ npm auto-update.

Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/katspaugh/wavesurfer.js
 * Official website (optional, not the repository): https://wavesurfer-js.org
 * NPM package url (optional): https://www.npmjs.com/package/wavesurfer.js
 * License and its reference: BSD-3-Clause
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 137
   - Count of stars: 2707
   - Count of forks: 696
 * NPM download stats (optional):
   - Downloads in the last day: 715
   - Downloads in the last week: 3688
   - Downloads in the last month: 12,639

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [X] No already exist / duplicated issue and PR
 * [X] The lib has notable popularity
   * [X] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [X] More than 800 downloads stats per month on npm registry
 * [X] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [X] Has valid tags for each versions (for git auto-update)
 * [X] Auto-update setup
 * [X] Auto-update target/source is valid.
 * [X] Auto-update filemap is correct.

# Git commit checklist
 * [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X] The parent of the commit(s) in the PR is not old than 3 days.
 * [X] Pull request is sending from a non-master branch with meaningful name.
 * [X] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@PeterDaveHello is this PR ok? we'd like to get the website going again that relies on this CDN..

**Comment by PeterDaveHello** [comment]
@thijstriemstra oops, looks like there is a problem caused we have no review request on this PR, thanks for pinging me.
@extend1994 @sufuf3 would you please help review this PR? Thanks.

**Comment by thijstriemstra** [comment]
ping @extend1994

**Comment by thijstriemstra** [comment]
Thanks! Eagerly awaiting the merge..

**Comment by PeterDaveHello** [comment]
@sufuf3 @extend1994 next time please separate auto-update config transferring to another commit.

**Comment by sufuf3** [comment]
Got it.
I'll remember it.
Thanks

**Pull request merged**
