### PR TITLE
Add the license for depot

### PR DESCRIPTION
**Pull request by hades0322**
for #6324
ref : https://github.com/cdnjs/cdnjs/blob/master/README.md

### CODE REVIEW

**Comment by Amomo** [comment]
@hades0322 very close to a good PR.
Could you attach the reference of its license info? :smile:

**Comment by Amomo** [comment]
Hi @hades0322 It is very close to a good PR.
Would you come back to finish it?

**Comment by hades0322** [comment]
OK, update already.

2015-12-01 13:48 GMT+08:00 Amo Chen <notifications@github.com>:

**Comment by Amomo** [comment]
@hades0322 I mean that you should attach on where did you know this library use a "MIT" license.

**Comment by pvnr0082t** [comment]
@hades0322 Any update? Please add reference link in comment and solve the conflict.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by PeterDaveHello** [comment]
Sorry to close this PR due to no response for a long time, feel free to start any other contribution again, thank you.

**Pull request closed without merging**
