### PR TITLE
[author] [new] Add lightGallery.

### PR DESCRIPTION
**Pull request by sachinchoolur**

### CODE REVIEW

**Comment by sachinchoolur** [comment]
@PeterDaveHello,
Could you please tell me what is the error and what should i do?
I have run npm test but could not find any error..

Thanks.

**Comment by PeterDaveHello** [comment]
filename field

**Comment by drewfreyling** [comment]
Can you please add npm autoupdate support as per our readme?

**Comment by sachinchoolur** [comment]
Hi @drewfreyling ,
Sorry for the inconvenience caused. I was not aware of this.
Anyway I am going to change my directory structure completely according to jquery-boilerplate.
So it will be difficult to maintain directory structure
> If you are updating a library, please try to maintain consistency with the existing file and directory structure.
> There will be occasions, particularly with major version increments, where this is not practical.

So i think submitting a pull request after next version will be better. 
What do you think?.

**Comment by PeterDaveHello** [comment]
I think you can still add current version manually.

**Comment by sachinchoolur** [comment]
Hi @PeterDaveHello , @drewfreyling ,

Please let me know if there anything else I should do for manual submission? 
should i add npm autoupdate config into my `package.json` before next release?
``` javascript
"npmName": "lightgallery",
"npmFileMap": [{
    "basePath": "light-gallery",
    "files": [
      "js/*",
      "css/*",
      "fonts/*",
      "img/*"
    ]
}]
```

Thanks.

**Comment by PeterDaveHello** [comment]
You can add it now or not, up to you, but I'll respectfully ask you to squash these commits into only one commit, and because this PR is a little bit old, so you may need to rebase/update with our latest master branch, the easier way may be to close this PR and open a new one(you may need to delete your forked repo and fork our repo again), thank you.

**Pull request closed without merging**
