### PR TITLE
Add git autoupdate config in rxjs-dom

### PR DESCRIPTION
**Pull request by Piicksarn**
@LeaYeh would you please checking the commit for me?
here is the Git repository url: https://github.com/Reactive-Extensions/RxJS-DOM/tree/v6.0.0
and link of cdnjs website: https://cdnjs.com/libraries/rxjs-dom

### CODE REVIEW

**Comment by Piicksarn** [comment]
@maruilian11, I need your help for checking the pr, and i have it rebased to the master.
Thank you!

**Comment by LeaYeh** [comment]
i think add all files in /dist is fine, but that will make different file structure with previous (confused)..

**Comment by Piicksarn** [comment]
The version included in cdnjs is too old(the latest version in cdnjs is 2.0.7) and the old structure seems not suit for the new versions.
@PeterDaveHello, how do you think about it?

**Comment by PeterDaveHello** [comment]
I don't think you didn't fit the old structure, just have more files.

**Comment by Piicksarn** [comment]
@LeaYeh would you mind to check it again?
I have rebased the commit to master. 
Thank you!

**Comment by LeaYeh** [comment]
ok.

**Comment by Piicksarn** [comment]
@PeterDaveHello would you please take a look for the pr?
Thank you!

**Comment by PeterDaveHello** [comment]
Need rebase.

**Comment by Piicksarn** [comment]
@LeaYeh i have it rebase to master, and need you check it again~
Thank you!

**Comment by Piicksarn** [comment]
@LeaYeh i have it rebase to master, and need you check it again~
Thank you!

**Comment by Piicksarn** [comment]
@LeaYeh i have it rebase to master, and need you check it again~
Thank you!

**Comment by LeaYeh** [comment]
ok

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you please take a look on it?
Thank you!

**Pull request merged**
