### PR TITLE
add miniTip old versions and v1.5.3 bundled src files

### PR DESCRIPTION
**Pull request by maruilian11**
Pull request for issue: #8971
@Piicksarn @cdnjs/intern2 could you please help me review this PR? thank you!
the source of this commit is from git log msg which mention the version number, you can easily trace them https://github.com/goldfire/miniTip/commits/master
if you need all versions source list, feel free to let me know, thanks!

### CODE REVIEW

**Comment by pvnr0082t** [comment]
LGTM

**Comment by maruilian11** [comment]
@PeterDaveHello do I need to rebase this branch with the latest master branch and tag others to help me review again?

**Comment by PeterDaveHello** [comment]
ping @kennynaoh @x09326

**Comment by kennynaoh** [comment]
@maruilian11 Please rebase to the latest master branch, thanks!

**Comment by maruilian11** [comment]
@kennynaoh I rebased the branch with the lastest master branch. Thanks!

**Comment by PeterDaveHello** [comment]
Can we focus on other issues first? I thought my issues without `High Priority` label should have lower priority than the users' issues.

**Comment by maruilian11** [comment]
ok

**Pull request merged**
