### PR TITLE
[new] add canvas-nest.js @v1.0.0

### PR DESCRIPTION
**Pull request by hustcc**
Hi @Piicksarn

repo url: [https://github.com/aTool-org/canvas-nest.js](https://github.com/aTool-org/canvas-nest.js)
npm package url: [https://www.npmjs.com/package/canvas-nest.js](https://www.npmjs.com/package/canvas-nest.js)

` Watch 9 ` ` Star 149 ` ` Fork 62 `

Would you mind checking this PR for me? Thank you~ :-D

 - [x] Not found on cdnjs repo
 - [x] No already exist issue and PR
 - [x] Notable popularity : Watch 9, Star 149, Fork 62
 - [x] Project has public repository on famous online hosting platform (or been hosted on npm)
 - [x] Has valid tags for each versions (for git auto-update)
 - [x] Auto-update setup
 - [x] Auto-update target/source is valid.
 - [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
If there is a npm package, I will respectfully suggest you to use it instead of git auto-update, which is faster and more efficient.

**Comment by hustcc** [comment]
thanks for your suggestion, next version, I' will change to npm. the version of npm now is not very standard.

**Comment by hustcc** [comment]
excuse, how long can the cdn work ?

**Comment by PeterDaveHello** [comment]
Only few minutes, you can access it from https://cdnjs.cloudflare.com/ajax/libs/canvas-nest.js/1.0.0/canvas-nest.js / https://cdnjs.cloudflare.com/ajax/libs/canvas-nest.js/1.0.0/canvas-nest.min.js already. The lib page on our website needs much more time, about 30 mins, to reindex everything and clean up the cache.

**Pull request merged**
