### PR TITLE
add github-markdown-css@2.3.0 w/ npm auto-update

### LINKED ISSUE #8540: [Request] Add Loadie.js
**Library name:** Loadie.js
**Git repository url:_https://github.com/9elements/loadie.js_
**npm package url(optional):** 
**License(s):**
**Official homepage:_http://9elements.github.io/loadie.js/_
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/36115936-request-add-loadie-js?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #8544: [Request] Add github-markdown-css
**Library name:** github-markdown-css
**Git repository url:** https://github.com/sindresorhus/github-markdown-css
**npm package url(optional):** https://www.npmjs.com/package/github-markdown-css
**License(s):** [https://github.com/sindresorhus/github-markdown-css/blob/gh-pages/license](https://github.com/sindresorhus/github-markdown-css/blob/gh-pages/license)
**Official homepage:** [https://sindresorhus.com/github-markdown-css](https://sindresorhus.com/github-markdown-css/)
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #8544 
@pvnr0082t please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/sindresorhus/github-markdown-css
 * Official website (optional, not the repository): https://sindresorhus.com/github-markdown-css/
 * NPM package url (optional): https://www.npmjs.com/package/github-markdown-css
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 1265
   - Count of watchers: 40
   - Count of forks: 232
 * NPM download stats (optional):
   - Downloads in the last day: 183
   - Downloads in the last week: 1486
   - Downloads in the last month: 4938

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8544, cc @sindresorhus

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@kennynaoh You tagged wrong issue. Should be #8544

**Comment by kennynaoh** [comment]
@pvnr0082t 
I have fixed the issue number.
Please help me review it again.
Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh don't you need to update the comment?

**Comment by kennynaoh** [comment]
Sorry, I forgot.
I fixed it.

**Pull request merged**
