### PR TITLE
Added jQueryUI 1.8.24.

### PR DESCRIPTION
**Pull request by ghost**
Added the minified version of jQueryUI 1.8.24, obtained from

http://jquery-ui.googlecode.com/files/jquery-ui-1.8.24.zip

[Build Status](http://travis-ci.org/bmcustodio/cdnjs)

### CODE REVIEW

**Comment by glensc** [comment]
unfortunately the css files are not included...

https://cdnjs.com/libraries/jqueryui/1.8.24

**Comment by PeterDaveHello** [comment]
@glensc sorry about that and thanks for your report, would you like to open an issue to trace this problem? Thanks!

**Comment by glensc** [comment]
created!

**Comment by PeterDaveHello** [comment]
Thanks @glensc

**Pull request merged**
