### PR TITLE
add ng-device-detector@3.0.1 w/ npm auto-update

### LINKED ISSUE #9167: [Request] Add ng-device-detector
**Library name:** ng-device-detector
**Git repository url:https://github.com/srfrnk/ng-device-detector
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by nolsherry**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/srfrnk/ng-device-detector
- Official website (optional, not the repository): http://srfrnk.github.io/ng-device-detector
- NPM package url (optional): https://www.npmjs.com/package/ng-device-detector
- GitHub / Bitbucket popularity (required):
  - Count of stars: 205
  - Count of watchers: 17
  - Count of forks: 49
- NPM download stats (optional):
  - Downloads in the last day: 105
  - Downloads in the last week: 603
  - Downloads in the last month: 2645
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [X] This lib was not found on cdnjs repo
- [X] No already exist / duplicated issue and PR
- [X] The lib has notable popularity
  - [X] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [X] More than 500 downloads stats per month on npm registry
- [X] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [X] Has valid tags for each versions (for git auto-update)
- [X] Auto-update setup
- [X] Auto-update target/source is valid.
- [X] Auto-update filemap is correct.
# Git commit checklist
- [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [X] The parent of the commit(s) in the PR is not old than 3 days.
- [X] Pull request is sending from a non-master branch with meaningful name.
- [X] Separate unrelated changes into different commits.
- [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [X] Close corresponding issue in commit message
- [X] Mention related issue(s), people in commit message, comment.

close #9167, cc @srfrnk

### CODE REVIEW

**Comment by x09326** [comment]
@nolsherry 
There are so many versions in git repo but npm cannot get it.
Please manually add them.

**Comment by nolsherry** [comment]
@x09326 , I have manually added all old versions with git auto-update, please help me review this PR, thanks！

**Comment by x09326** [comment]
Multiple commits need multiple reviewer.
@kennynaoh 
Please review it together.

**Comment by x09326** [comment]
LGTM

**Comment by kennynaoh** [comment]
@nolsherry 
Because there exist duplicated version `0.0.1`, `v0.0.1` and `0.0.2`, `v0.0.2` on git repo.
Maybe you should confirm with author which version he want and ignore another in this case.
Thanks!
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@kennynaoh I don't think bothing the author directly at the beginning is a good idea, should figure out if the versions with and without v prefix are different first, if so, what's the difference?

**Comment by kennynaoh** [comment]
@PeterDaveHello 
What I mean is to confirm with author to figure out whether they are the same with and without `v`.
Is it necessary?
And I found that `ng-device-detector.js` is different between `0.1.0` and `v0.1.0`

**Comment by PeterDaveHello** [comment]
@kennynaoh What I mean is that you can confirm that by yourself first, right?

**Comment by kennynaoh** [comment]
@PeterDaveHello , sure.
And  `ng-device-detector.js` is different between `0.1.0` and `v0.1.0`
So should confirm with author?

**Comment by PeterDaveHello** [comment]
@kennynaoh Please give me a reference, I'll look into.

**Comment by kennynaoh** [comment]
`v1.0.0` -> https://github.com/srfrnk/ng-device-detector/blob/v1.0.0/ng-device-detector.js
`1.0.0` -> https://github.com/srfrnk/ng-device-detector/blob/1.0.0/ng-device-detector.js
And I also found that it shows `v1.1.0` in package.json in tag `v1.0.0` 
https://github.com/srfrnk/ng-device-detector/blob/v1.0.0/package.json#L3
Maybe it has typo.

**Comment by PeterDaveHello** [comment]
@kennynaoh okay, so let me confirm with you first, the difference is between ibetween 0.1.0 and v0.1.0 or v1.0.0 and v1.0.0? Confused by your inconsistency comments.

**Comment by kennynaoh** [comment]
Sorry for wrong versions.
It is different between `1.0.0` and `v1.0.0`.
Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh Okay, they are obviously different, let's ask its author, thanks.

**Comment by kennynaoh** [comment]
@nolsherry 
Please discuss with author about the versions with and without `v` which version is needed and ignore another.
Thanks!

**Comment by srfrnk** [comment]
Hi guys - version '1.0.0' was a type. I later started to add the 'v' as per convention.
Hope that helps.

**Comment by PeterDaveHello** [comment]
Thanks @srfrnk.

**Comment by nolsherry** [comment]
@srfrnk , thanks for your response, and I will ignore the versions which without `v`.

**Comment by nolsherry** [comment]
@pvnr0082t , I will ignore the versions (`1.0.0`, `2.0.0`) because there are formal versions `v0.0.1` and `v0.0.2`, please help me review this PR, thanks!

**Comment by kennynaoh** [comment]
@nolsherry 
The version you need to ignore are `1.0.0` and `2.0.0`, not `0.0.1` and `0.0.2`
By the way, I think the auto-update can't automatically add these two confused version on git repo because you use npm auto-update.
Maybe you don't need to update .gitignore to ignore it.
You could just add the correct version `v1.0.0` and `v2.0.0`, not `1.0.0` and `2.0.0`, manually.
Thanks!

cc @PeterDaveHello

**Comment by nolsherry** [comment]
@pvnr0082t, @kennynaoh, I have removed `ajax/libs//ng-device-detector/0.0.1` and  `ajax/libs//ng-device-detector/0.0.2` in `.gitignore` file, please help me review this PR, thanks!

**Comment by kennynaoh** [comment]
LGTM

**Comment by x09326** [comment]
@nolsherry 
Sorry for the late response.
Please rebase it with the latest branch.

**Comment by nolsherry** [comment]
@kennynaoh , @x09326 , I have rebased it with the latest branch. please help me review this PR, thanks!

**Comment by kennynaoh** [comment]
LGTM
ping @PeterDaveHello

**Pull request merged**
