### PR TITLE
Add sweetalert2 package

### PR DESCRIPTION
**Pull request by limonte**
# Profile of the lib
 * Git repository (required): https://github.com/sweetalert2/sweetalert2
 * Official website (optional, not the repository): https://sweetalert2.github.io/
 * NPM package url (optional): https://www.npmjs.com/package/sweetalert2
 * License and its reference: MIT https://github.com/sweetalert2/sweetalert2/blob/master/LICENSE
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 137
   - Count of stars: 4089
   - Count of forks: 659

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by limonte** [comment]
Couple of days ago we created the organization for sweetalert2, repo has been moved from https://github.com/limonte/sweetalert2 to https://github.com/sweetalert2/sweetalert2

Should I also delete [limonte-sweetalert2](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/limonte-sweetalert2)?

**Comment by PeterDaveHello** [comment]
@limonte Nope, I think web should just change the repo url of the original one.

**Comment by limonte** [comment]
> @limonte Nope, I think web should just change the repo url of the original one.

Done, https://github.com/cdnjs/cdnjs/pull/12416

**Comment by PeterDaveHello** [comment]
@limonte Thanks!

**Pull request closed without merging**
