### PR TITLE
add peity v3.2.0 

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/benpickles/peity
**Watch 117
  Star 3,298
 Fork 311**
@Piicksarn could you help me check out the PR for #6095 ? thank you~
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity 
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by Piicksarn** [comment]
It's fine~
@PeterDaveHello, would you please have a look at the pr?
thank you~

**Comment by benpickles** [comment]
I don't know if this helps but Peity is on NPM too - https://www.npmjs.com/package/peity

**Comment by PeterDaveHello** [comment]
Thanks a lot @benpickles!

@Piicksarn please send another PR to transfer to use npm auto-update if it's possible, npm auto-update process is much faster.

**Comment by maruilian11** [comment]
@PeterDaveHello ok.

**Comment by maruilian11** [comment]
@PeterDaveHello but `jquery.peity.min.js` and `jquery.peity.js` are put in version number folder in npm package so that i can't set `basepath` in npm auto-update, should i open an issue to ask author if they can change version number folder to dist folder?

**Comment by PeterDaveHello** [comment]
@benpickles is it possible to remove version number in folder name? I think version can be recognized by package.json

**Comment by benpickles** [comment]
Hmmm. I don't do anything with version numbers in file/folder names, it's just the main file and a minified version.

**Comment by PeterDaveHello** [comment]
@benpickles ok

**Comment by PeterDaveHello** [comment]
@maruilian11 as @benpickles says, I checked the structure, there is no version number in it's path, so not sure where does your problem come from.

**Pull request merged**
