### PR TITLE
[new] add Broadway.js@0.1.0 with git auto-update

### PR DESCRIPTION
**Pull request by LeaYeh**
Hi @maruilian11 

For #5706, I add Broadway.js at v0.1.0 and add git auto-update config in its package.json.
repo: https://github.com/mbebenita/Broadway/tree/0.1.0
and licence info: https://github.com/mbebenita/Broadway/blob/0.1.0/LICENSE#L16
Would you mind checking this PR for me? Thank you~ :-D
- [x] Not found on cdnjs repo
- [ ] No already exist issue and PR
- [x] Notable popularity : **Watch `63`, Star `1137`, Fork `143`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by maruilian11** [comment]
@LeaYeh i think every `js` and `css` added to cdnjs should have min file.

**Comment by LeaYeh** [comment]
@maruilian11 i minified each file in folder `Player`, could you check this pr again?

**Comment by maruilian11** [comment]
@LeaYeh you seem to forget `reqiredFiles`.

**Comment by PeterDaveHello** [comment]
Move to #7771

**Pull request closed without merging**
