### PR TITLE
add sugar@2.0.4 w/ git auto-update config

### LINKED ISSUE #9458: [Request] Add sugar 2.0.0
**Library name:sugar 2.0.0** 
**Git repository url:https://github.com/andrewplummer/Sugar**
**npm package url(optional):** https://www.npmjs.com/package/sugar
**License(s):MIT**
**Official homepage:https://sugarjs.com/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
Pull request for issue: #9458 
@kennynaoh @x09326 Please help me review this pull request, thank you.
- use git auto-update due to there are 36 releases on GitHub but 31 on NPM
- add latest version of sugar

close #9458

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@x09326 http://sugarjs.com/ will redirect to https://sugarjs.com/. I think we don't need to modify it.

**Comment by kennynaoh** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
This config only work with the last few releases.

**Pull request merged**
