### PR TITLE
AlaSQL

### PR DESCRIPTION
**Pull request by mathiasrw**
Hey - AlaSQL ( https://github.com/agershun/alasql ) would love to use cdnjs

### CODE REVIEW

**Comment by mathiasrw** [comment]
```
   alasql 
      ✗ alasql package.json is valid 
        » alasql didn't parse as any known format: 
  	  » NPM package.json 
  		Property is required (true): /properties/filename // valid-packages-test.js:82 
   
      ✗ alasql: filename from package.json exists 
        » ./ajax/libs/alasql/0.1.7/undefined does not exist but is referenced in package.json! // valid-packages-test.js:101 
  ✗ Broken » 6117 honored ∙ 2 broken (3.851s) 
  npm ERR! Test failed.  See above for more details.
```

Hmmm.... will check up on that...

**Comment by mathiasrw** [comment]
Wohoo !

**Comment by PeterDaveHello** [comment]
Please squash them into only one commit.

**Comment by PeterDaveHello** [comment]
#4699

**Pull request closed without merging**
