### PR TITLE
Add auto-update config on jquery-cookie, close #5861

### LINKED ISSUE #5861: auto-update config on jquery-cookie
https://github.com/carhartl/jquery-cookie
https://cdnjs.com/libraries/jquery-cookie

### PR DESCRIPTION
**Pull request by LeaYeh**
**`git repository : `** https://github.com/carhartl/jquery-cookie/tree/v1.4.0
**`Watch : 458 /  Star : 7473 /  Fork : 3236`**
related issue : #5861
@maruilian11, would you mind to have a look at the pr?

- [ ] Not found on cdnjs repo
- [ ] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.

### CODE REVIEW

**Comment by maruilian11** [comment]
@LeaYeh i think the pr is ok. can you rebase it? thank you~

**Comment by LeaYeh** [comment]
@maruilian11  ok, i already rebased it :)

**Comment by maruilian11** [comment]
sorry, i miss it, could you rebase it again? thank you

**Comment by LeaYeh** [comment]
@maruilian11 ok! rebased it.

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Pull request merged**
