### PR TITLE
Update bootstrap-combobox.js

### PR DESCRIPTION
**Pull request by ajaxboy**
Element ids include the word 'undefined' at the end of the id. Need to check type of variable instead of assume it to be a string saying 'undefined'  (could also be a constant, so removing the quotes will probably work as well)

If options.appendId is undefined then defined it, and if there is an id, pass the attribute.

Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:
   - Count of stars:
   - Count of forks:
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [x ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@ajaxboy Thanks for contribution.
But we don't touch the files from upstream.
Because CDNJS make sure every files are the same with upstream.

If you would help improve this lib, maybe you can send a PR to https://github.com/danielfarrell/bootstrap-combobox.
What do you think?

Thank you very much.

**Comment by sufuf3** [comment]
Because CDNJS host the files which related on git tag.
However, this lib's file is modified by contribution, this would affect many developers(users) who use CDNJS service.

If there is no any response in next 7 day, I suggest we can close this PR.

Many thanks

**Comment by extend1994** [comment]
Help close due to no response in 7 days, cc @sufuf3 @PeterDaveHello

**Comment by ajaxboy** [comment]
Apply changes

**Pull request closed without merging**
