### PR TITLE
Add git autoupdate config in xregexp.js.

### PR DESCRIPTION
**Pull request by Piicksarn**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
There is `min` folder as dist, maybe we should use it, or you can open an issue to discuss with the author, seems v3.0.0 is going to be released soon.

**Comment by Piicksarn** [comment]
have added the min folder!

**Comment by PeterDaveHello** [comment]
Seems the structure is complex, let's wait and see what we got in v3.0.0, it'll be better if you could open an issue there.

**Comment by PeterDaveHello** [comment]
Any updates?

**Comment by Piicksarn** [comment]
[Question for combining min folder and src folder ](https://github.com/slevithan/xregexp/issues/92)

**Pull request closed without merging**
