### PR TITLE
Add numbered@1.1.0 w/ npm auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
Pull request for issue: #10064 
@cdnjs/intern2  Please help me review this PR, thanks!

# Profile of the lib
 * Git repository (required): https://github.com/blakeembrey/node-numbered
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/numbered
 * License and its reference: MIT, https://github.com/blakeembrey/node-numbered/blob/7ce4ecb73df56f609d57ac5ca2d1c19922d1c139/Readme.md#license
 * GitHub / Bitbucket popularity (required):
   Watch 1
   Star 2
   Fork 1
 * NPM download stats (optional):
  123 downloads in the last day
  1,159 downloads in the last week
  3,523 downloads in the last month
# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by maruilian11** [comment]
@PeterDaveHello Just confirm this lib is compatible with browser and rebase this commit with the latest master branch.

**Comment by PeterDaveHello** [comment]
@kennynaoh please help review, thanks.

**Comment by PeterDaveHello** [comment]
@maruilian11 you didn't ... 

> but it was designed for a CommonJS bundler

**Comment by PeterDaveHello** [comment]
I don't think it's confirmed, waiting for https://github.com/blakeembrey/node-numbered/issues/1

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello There is no response from the upstream since 20 Jan. https://github.com/blakeembrey/node-numbered/issues/1#issuecomment-274043530
What can we do for this PR?
Still waiting for the upstream? Or close this PR?
Thanks.

**Comment by PeterDaveHello** [comment]
Just test if it works in browser?

**Comment by sufuf3** [comment]
No, I can't. 😞

**Comment by PeterDaveHello** [comment]
What do you mean I can't? You can't test it?

**Comment by sufuf3** [comment]
I can't use `index.js` in web front-end.
The lib seems to need to have a UMD wrapper as author said https://github.com/blakeembrey/node-numbered/issues/1#issuecomment-273863999

**Comment by PeterDaveHello** [comment]
Okay so let's say it more clear next time. As discussion here: https://github.com/blakeembrey/node-numbered/issues/1, I believe that we can wait a few more days, maybe one or two weeks to get this done.

**Comment by PeterDaveHello** [comment]
Seems to be done now: https://github.com/blakeembrey/node-numbered/issues/1

**Comment by maruilian11** [comment]
@cdnjs/library-reviewer @sufuf3 Please help me review this PR, thanks. This lib can work on browser start from v1.1.0. Thanks!
https://github.com/blakeembrey/node-numbered/pull/3#issuecomment-330755064

**Comment by sufuf3** [comment]
I think if we can separate two commits is better.
One is `Add numbered@1.1.0 w/ npm auto-update`, another is `update .gitignore`.
Or I think at lease the commit message needs to mention that you updated .gitignore, such as `Add numbered@1.1.0 w/ npm auto-update & update .gitignore`

What do you think?

**Comment by extend1994** [comment]
@sufuf3 I think she has mentioned that.
>And update .gitignore to ignore unpackaged
versions. close #10064, cc @blakeembrey

**Comment by sufuf3** [comment]
What I consider is: if  I use `git log --pretty=format:"%h %s" --graph` I don't know this commit including updating .gitignore.
I think separate it in two commits is helpful to trace git log. Especially, this repo is huge and maybe we can let it better, don't we?
Thanks.

**Comment by extend1994** [comment]
Well, they are both fine to me. We can see how maruilian11 and Peter decide.

**Comment by PeterDaveHello** [comment]
@sufuf3 There is no need to separate the commit, how you trace the commit history isn't the best way or the most common way in convention, it's super easy to use `git log` with `--stat` to recognize how many files are touched. In fact I prefer to combine them in a single commit as I also mention in the other comments before, so let's just do it like this. @sufuf3 please review the remaining parts.

**Pull request merged**
