### PR TITLE
Add Lazy 3.1.160913

### PR DESCRIPTION
**Pull request by keicheng**
https://github.com/keicheng/kule.lazy/tree/v3.1.160913

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@keicheng Please take a look at commit 866ca6e

**Comment by keicheng** [comment]
Sorry, I don`t know what happened

**Comment by PeterDaveHello** [comment]
The bot added the lib one hour earlier than you, so no need to send PR for this, but you'll be welcome to help solve other library request issues, thanks

**Comment by keicheng** [comment]
Thanks! magic bot

**Pull request closed without merging**
