### PR TITLE
[new] add pdf.js@1.3.22 with npm auto-update

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 

For #5020, I add pdf.js at v1.1.539 and add `npm` auto-update config in its package.json.
repo: https://github.com/mozilla/pdf.js
They put build files in another repo [pdfjs-dist](https://github.com/mozilla/pdfjs-dist)

I think we could add the whole repo because it is a distribution repository.
That's why I use `"**/*.+(js|css|svg|gif|png)"` in auto-update config.

Would you mind checking this PR for me? Thank you~ :-D

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `654`, Star `12,729`, Fork `2,964`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by maruilian11** [comment]
@Amomo why not use git auto-update?

**Comment by Amomo** [comment]
We could get this library from its distribute GitHub repo and also npm.
I found npm has the latest version, so I choose to add npm auto-update config. :-)

**Comment by maruilian11** [comment]
@Amomo thank you, could you rebase the PR?

**Comment by Amomo** [comment]
@maruilian11 I have updated my PR, pdf.js has v1.2.61 now.
Could you please check again? Thank you! :-D

**Comment by maruilian11** [comment]
@Amomo i think this pr is ok, could you rebase it to the master? thank you~

**Comment by Amomo** [comment]
@maruilian11 I have rebase this PR, could you check again? Thank you! :-D

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Comment by PeterDaveHello** [comment]
Do we really need the `build` folder? There is a `web` folder, I guess it's enough for cdn from its name.
cc @cdnjs/team-cdnjs @cdnjs/intern

**Comment by razorman8669** [comment]
Hi @Amomo, According to the code in pdf.js, it loads the worker.js file like this:
```
var pdfJsSrc = document.currentScript.src;
return pdfJsSrc && pdfJsSrc.replace(/\.js$/i, '.worker.js');
```
which means that if the minified pdf.js file is named `pdf.min.js` then the corresponding worker should be named `pdf.min.worker.js` and not `pdf.worker.min.js` like you have it

**Comment by Amomo** [comment]
@razorman8669  this advice is very important! Thank you very much! :-D

**Comment by maruilian11** [comment]
@Amomo as Peter said maybe the files under `web` are enough, could you check this with author?

**Comment by Amomo** [comment]
Hi @yurydelendik 
Would you please give us some advice if we wanna host this lib on the cdn?
Is it enough to host only `web/` folder? or we should host both `build/` and `web/`?
Thank you very much! :-)

**Comment by yurydelendik** [comment]
> Would you please give us some advice if we wanna host this lib on the cdn?

There is an issue that did not let us to do it first place: web workers cannot be loaded from the remote location. So people are using `PDFJS.disableWorker=true` to workaround the issue, however this just makes PDF.js performance really bad, locks UI and throws slow script warning.

See also https://github.com/mozilla/pdf.js/issues/5490. After https://github.com/mozilla/pdf.js/pull/6571 lands, I will try to create a "proxy" page that will host cdn worker as well.

>  Is it enough to host only web/ folder? or we should host both build/ and web/?

both, the web/ folder contains viewer parts, but PDF.js core library is located at build/

**Comment by PeterDaveHello** [comment]
@yurydelendik Thank you.  cc @cdnjs/team-cdnjs

**Comment by yurydelendik** [comment]
Suggested solution at:
- [ ] https://github.com/mozilla/pdf.js/pull/6753

**Comment by yurydelendik** [comment]
Is it possible to update pdf.js to use its newer version in the PR?

**Comment by PeterDaveHello** [comment]
> Is it possible to update pdf.js to use its newer version in the PR?

Yes, of course, maybe we can add them both.

**Pull request closed without merging**
