### PR TITLE
add auto-update config & minified files in musicmetadata

### PR DESCRIPTION
**Pull request by Amomo**
Hi @LeaYeh , From #5195, I have add minified files in musicmetadata and point filename field to `musicmetadata.min.js` in package.json.
repo : https://github.com/leetreveil/musicmetadata
Would you mind checking this PR for me? Thank you~ :-)

- [ ] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `13`, Star `302`, Fork `62`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by Amomo** [comment]
@LeaYeh I have rebased this PR to match the latest master branch.
Could you take a look? Thank you!

**Comment by Amomo** [comment]
@LeaYeh I have rebased this PR to match the latest master branch.
Could you take a look? Thank you!

**Comment by LeaYeh** [comment]
i think this pr is ok. i'm sorry for late reply, please rebase it again.

**Comment by Amomo** [comment]
@LeaYeh I have rebased it, could you check again? Thank you~

**Comment by LeaYeh** [comment]
@PeterDaveHello

**Comment by PeterDaveHello** [comment]
@Amomo You should not update PR even just rebase, we can not make sure it's reviewed.

**Comment by Amomo** [comment]
ok, I will keep it, if it has just been reviewed.

**Pull request merged**
