### PR TITLE
[new] add classnames@2.1.3 with git auto-update, close #5208

### LINKED ISSUE #5208: [Request] Add classnames
classnames
https://github.com/JedWatson/classnames
https://www.npmjs.com/package/classnames

### PR DESCRIPTION
**Pull request by Amomo**
Hi @LeaYeh , I add a new lib with git auto-update from the request #5208 
repo: https://github.com/JedWatson/classnames
Its main file named `index.js`, and It has a alternate version named `dedupe.js`.
I add them and their minified files.
Would you mind checking this PR for me? Thank you~ :-)

### CODE REVIEW

**Comment by LeaYeh** [comment]
i think add `dedupe*.js` and `index*.js` in filemap are better, because the basepath is not `dist` and we couldn't assume we need all `js` files.

**Comment by Amomo** [comment]
@LeaYeh Thanks for reminding~
I have revised it, could you come to check again? Thank you~

**Comment by LeaYeh** [comment]
sorry for late, plz rebase it again ><"

**Comment by Amomo** [comment]
@LeaYeh I have rebased it!
Could you come to check it again? Thank you! :-D

**Comment by LeaYeh** [comment]
ok @PeterDaveHello

**Comment by PeterDaveHello** [comment]
How can I know that I need dedupe.js?

**Comment by Amomo** [comment]
@PeterDaveHello According to its README.md, `dedupe.js` is a alternate version
It will correctly dedupe classes and ensures that falsely classes specified in later arguments will be excluded from the result set.
But, it will slower (about 10x) so it is offered as an opt-in.
Just an option, not very necessary.
Or, I should remove it?

**Pull request merged**
