### PR TITLE
add photoswipe v4.1.0 and update package.json, close #5356

### LINKED ISSUE #5356: [Request]PhotoSwipe new version
PhotoSwipe v4.1.0 is available

Repository: https://github.com/dimsemenov/PhotoSwipe/
CDN: https://cdnjs.com/libraries/photoswipe

Thanks for an update.

### PR DESCRIPTION
**Pull request by maruilian11**
@Piicksarn could u plz help me check this PR for #5356? thank you!
**git repo url :**  https://github.com/dimsemenov/PhotoSwipe/
**Warch 425
Star 8,967
 Fork 1,175**
* [ ] Not found on cdnjs repo
* [x] No already exist issue and PR
* [x] Notable popularity
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)
* [x] Has valid tags for each versions (for git auto-update)
* [x] Auto-update setup
* [x] Auto-update target/source is valid.
* [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by Piicksarn** [comment]
It's fine!
@PeterDaveHello, would you please take a look on this PR?

**Comment by PeterDaveHello** [comment]
Should explain your update in eb6b535. And why don't you separate auto-update config in another commit? I don't think it's kind of update.

**Comment by maruilian11** [comment]
@Piicksarn could u help me check it again? thank you very much!

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you please take a look on the PR?
thank you~

**Comment by PeterDaveHello** [comment]
Don't we need `default-skin` ... ？

**Comment by maruilian11** [comment]
@Piicksarn could u help me check it again? thank you very much!

**Comment by Piicksarn** [comment]
@maruilian11, sorry for my careless.
Author map additional items(such as external test or documentation framework) in a **`devDependencies`** object for installing.
In order  that we need to add it in the autoupdate filemap.

@PeterDaveHello, maruilian has it corrected, and need you to checkout the pr!
Thanks!

**Comment by maruilian11** [comment]
@Piicksarn thank you for your explaining!

**Pull request merged**
