### PR TITLE
Enrich entypo's package.json(field: license)

### PR DESCRIPTION
**Pull request by LeaYeh**
Hi @Piicksarn  , 
From #5500, I have added license info. http://www.entypo.com/
with licence `CC-BY-SA-4.0`
repo : https://github.com/danielbruce/entypo
Would you mind checking this PR for me? Thank you.

### CODE REVIEW

**Comment by Piicksarn** [comment]
@LeaYeh, it's fine, but need rebased to master! :smiley:

**Comment by LeaYeh** [comment]
@Piicksarn ok, i already did it

**Comment by Piicksarn** [comment]
It's fine!
@PeterDaveHello, would you mind to have a look at the pr?
Thank you!

**Comment by PeterDaveHello** [comment]
oh really?
https://github.com/danielbruce/entypo/commit/db716c7e70d5092ac781f545d197adf3892cea3a#diff-04c6e90faac2675aa89e2176d2eec7d8

**Pull request closed without merging**
