### PR TITLE
update autoupdate config of pileup

### LINKED ISSUE #8454: Update auto-update filemap of pileup
pileup v0.6.7 changed the structure and caused the auto-updater fetched something we can not use directly.

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8454 
@kennynaoh Please help me review this pull request, thank you.

close #8454

### CODE REVIEW

**Comment by kennynaoh** [comment]
@pvnr0082t 
Sorry for late review.
Please rebase to the latest master branch.
Thanks!

**Comment by pvnr0082t** [comment]
@kennynaoh I have rebased it. Please help me review again, thank you.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Comment by PeterDaveHello** [comment]
@pvnr0082t have you tried to confirm with the about this change?

**Comment by pvnr0082t** [comment]
@PeterDaveHello I don't get you. You mean I should confirm with the author about the structure changed and... confirm what?

**Comment by PeterDaveHello** [comment]
@pvnr0082t Confirm you arr on the right config, otherwise, will you think current config is perfect?

**Comment by PeterDaveHello** [comment]
The main reason is that we used to use a trivial solution on this lib but now change to a non-trivial solution, so we should better confirm that.

**Comment by pvnr0082t** [comment]
author said that the list of files they are interested in distributing:
-   dist/pileup.js
-    dist/pileup.js.map
-    dist/pileup.min.js
-    dist/pileup.min.js.map
-    dist/style/pileup.css

The auto-update config can fetch these files now but I don't know if there is better one. @kennynaoh Please help me review again, thank you.

**Comment by PeterDaveHello** [comment]
@pvnr0082t is `pileup.css` also under `dist`?

**Comment by pvnr0082t** [comment]
@PeterDaveHello No, the `pileup.css` is under `style` folder.

**Comment by PeterDaveHello** [comment]
Okay, so https://github.com/cdnjs/cdnjs/pull/8486#issuecomment-232860289 is wrong.

**Comment by PeterDaveHello** [comment]
@pvnr0082t let's rebase your branch and get this merged.

**Comment by pvnr0082t** [comment]
@PeterDaveHello Okay. I have rebase it. Please help me review again, thank you.

**Pull request merged**
