### PR TITLE
add angular-validation v1.4.1 with npm autoupdate config

### LINKED ISSUE #7505: [Request] Add angular-validation
**Library name:** angular-validation
**Git repository url:** https://github.com/huei90/angular-validation
**npm package url(optional):** https://www.npmjs.com/package/angular-validation
**License(s):** MIT
**Official homepage:** http://huei90.github.io/angular-validation/

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #7505 
@dannyxx001 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/huei90/angular-validation
 * Official website (optional, not the repository): http://huei90.github.io/angular-validation/
 * NPM package url (optional): https://www.npmjs.com/package/angular-validation
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 555
   - Count of watchers: 26
   - Count of forks: 144
 * NPM download stats (optional):
   - Downloads in the last day: 19
   - Downloads in the last week: 52
   - Downloads in the last month: 386

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

with npm autoupdate config, close #7505, cc @huei90

### CODE REVIEW

**Comment by dannyxx001** [comment]
I think it's OK. @PeterDaveHello Please make sure again, thanks.

**Comment by PeterDaveHello** [comment]
@pvnr0082t I wonder why your `package.json` is always in a strange order, the `package.json` from upstream doesn't looks like that:

```js
  "name": "angular-validation",
  "version": "1.4.1",
  "description": "Client-side Validation for AngularJS",
  "repository": {
    "type": "git",
    "url": "https://github.com/huei90/angular-validation"
  },
  "homepage": "http://huei90.github.io/angular-validation/",
  "scripts": {
    "test": "grunt karma",
    "build": "grunt build",
    "development": "grunt dev"
  },
  "author": {
    "name": "Huei Tan",
    "email": "huei90@gmail.com",
    "url": "https://github.com/huei90"
  },
  "license": "MIT",
  "keywords": [
    "angular",
    "angularjs",
    "validation",
    "angular validation",
    "validator",
    "client-side"
  ],
```

Please move the most important things the upper in `package.json`, at least put `"name"`, `"description"`, `"version"`, `"filename"` at top section.

**Comment by pvnr0082t** [comment]
@PeterDaveHello Because I referenced the ```package.json``` file after I did npm install. The order does not look like the same as upstream. Is that better to change order that you show us?

**Comment by PeterDaveHello** [comment]
@pvnr0082t I didn't get your point about *I referenced the 
package.json*, didn't you just copy the package.json but create a new one by yourself? Let's do it more usual.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I copied the ```package.json``` file  after I did npm install. The order looks like this.
```js
36   "author": {  
37     "email": "huei90@gmail.com",
38     "name": "Huei Tan",      
39     "url": "https://github.com/huei90"     
40   },
```
```js
87   "license": "MIT",                   
88   "main": "./dist/angular-validation.js",                             
89   "maintainers": [                   
90     {           
91       "email": "huei90@gmail.com",                       
92       "name": "huei90"                          
93     }                      
94   ],              
95   "name": "angular-validation",
```
I didn't change the order, so the order looks strange.

**Comment by PeterDaveHello** [comment]
@pvnr0082t Didn't get you, why did you do npm install after copied the package.json? npm install will give you the package.json with common order.

**Comment by pvnr0082t** [comment]
@PeterDaveHello Really!? npm install give me package.json file with alphabetical order. The key with underline always at top section. What's wrong with it?

**Comment by PeterDaveHello** [comment]
@pvnr0082t If the keys with leading underline are commonly seen, try to add them to tools/fixFormat.js and test/valid-packages-test.js, or jut manually delete them, at least, you won't use a strange order.

**Comment by PeterDaveHello** [comment]
@pvnr0082t and I have no the problem you said about npm, try to manually download and extract the tarball by yourself, the url format is like https://registry.npmjs.org/jquery/-/jquery-2.2.2.tgz

**Comment by pvnr0082t** [comment]
ping @dannyxx001

**Comment by dannyxx001** [comment]
If the format is accepted, then I think the PR is OK. @PeterDaveHello please review again, thanks.

**Pull request merged**
