### PR TITLE
update repo url in ng2-formly 2.0.0-alpha.5

### LINKED ISSUE #7568: [Request] Add ng2-formly
**Library name:** ng2-formly
**Git repository url:** https://github.com/formly-js/ng2-formly
**npm package url(optional):** https://www.npmjs.com/package/ng2-formly
**License(s):** MIT
**Official homepage:** http://formly-js.github.io/ng2-formly/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by nolsherry**
@kennynaoh, I have fixed the wrong repo url, please help me to review this pull request, thanks!
  
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/formly-js/ng2-formly
 * Official website (optional, not the repository): http://formly-js.github.io/ng2-formly/
 * NPM package url (optional): https://www.npmjs.com/package/ng2-formly
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 30
   - Count of watchers: 11
   - Count of forks: 7
 * NPM download stats (optional):
   - Downloads in the last day: 2
   - Downloads in the last week: 170
   - Downloads in the last month: 495

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [X] Has valid tags for each versions (for git auto-update)
 * [X] Auto-update setup
 * [X] Auto-update target/source is valid.
 * [X] Auto-update filemap is correct.

# Git commit checklist
 * [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X] The parent of the commit(s) in the PR is not old than 3 days.
 * [X] Pull request is sending from a non-master branch with meaningful name.
 * [X] Separate unrelated changes into different commits.
 * [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [X] Close corresponding issue in commit message
 * [X] Mention related issue(s), people in commit message, comment.

cc #7706, cc @mohammedzamakhan

### CODE REVIEW

**Comment by kennynaoh** [comment]
@nolsherry 
Please change the commit message.
Tell us what did you do.
Thanks!

**Comment by nolsherry** [comment]
@kennynaoh, I have updated commit messages, please help me to review this pull request, thanks!

**Comment by kennynaoh** [comment]
@nolsherry 
The repo url is still not correct.
Please confirm it again.
Thanks!

**Comment by nolsherry** [comment]
@kennynaoh, I fixed the repo url error, please help me to review this pull request, thanks!

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Comment by PeterDaveHello** [comment]
You don't need to mention author and lib version next time.

**Pull request merged**
