### PR TITLE
Update framework7 auto-update config

### PR DESCRIPTION
**Pull request by sufuf3**
Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/nolimits4web/Framework7
 * Official website (optional, not the repository): http://framework7.io
 * NPM package url (optional):
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 632
   - Count of stars: 10467
   - Count of forks: 2253
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
Memo: To exclude `framework7.module.js`@v2.0.0-beta.1

**Comment by PeterDaveHello** [comment]
@sufuf3 confirmed that the file is not needed?

**Comment by sufuf3** [comment]
Since v2.0.0-beta.1 the [README](https://github.com/nolimits4web/Framework7/tree/v2.0.0-beta.1#build) says they use `rollup`, as this line https://github.com/nolimits4web/Framework7/blob/v2.0.0-beta.1/scripts/build-js.js#L44 to generate the `framework7.module.js` .
In web front-end needs to use `<script type="module" />`
But in this case, the file need to import some relative modules which depend on the developer who knows these modules to import. 
Because CDNJS is a web front-end service, I think CDNJS doesn't need the file.

**Comment by sufuf3** [comment]
@cdnjs/active-contributor @cdnjs/intern3 Please help me review this PR, thank you.
This lib pattern as same with https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/whitestorm.js/package.json#L30

**Comment by sufuf3** [comment]
@cdnjs/active-contributor @cdnjs/intern3 Please help me review this PR, thank you.

**Comment by extend1994** [comment]
@sufuf3 Can I know how did you know we need `<script type="module" />` to use framework7.module.js?

**Comment by sufuf3** [comment]
CDNJS is good to support ES5 and not sure is good to support ES6.

Because the repo [README](https://github.com/nolimits4web/Framework7/tree/v2.0.0-beta.1#build) said it builds with rollup, and rollup wiki said it bundle for ES6: https://github.com/rollup/rollup/wiki/ES6-modules

the `framework7.module.js` is ES6 and work to add something like `<script type=module>` to HTML as this link said: https://hacks.mozilla.org/2015/08/es6-in-depth-modules/


What I learned <script> element is from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script.

Thanks

**Comment by PeterDaveHello** [comment]
ES5, ES6, both not related with CDNJS ... the problem is if they are minified, can work on CDN hosting.

**Comment by PeterDaveHello** [comment]
`js/framework7.modular.js` in v2.0.0-beta.3 still be fetched, can you guys check it again?

**Pull request merged**
