### PR TITLE
Add react-router-dom@4.1.1 w/ npm auto-update

### LINKED ISSUE #10977: [Request] Add react-router-dom
**Library name:** react-router-dom
**Git repository url:** https://github.com/ReactTraining/react-router/tree/master/packages/react-router-dom
**npm package name or url** (if there is one): https://www.npmjs.com/package/react-router-dom
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/ReactTraining/react-router/tree/master/packages/react-router-dom
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
close #10977

@maruilian11 @cdnjs/intern2 Please help me review this pull request, thank you.

Pull request for issue: #10977 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/ReactTraining/react-router/tree/master/packages/react-router-dom
 * NPM package url (optional): https://www.npmjs.com/package/react-router-dom
 * License and its reference: MIT, https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/package.json#L6
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 732
   - Count of stars: 21858
   - Count of forks: 5124
 * NPM download stats (optional):
   - Downloads in the last day: 13532
   - Downloads in the last week: 66205
   - Downloads in the last month: 248965

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@pvnr0082t oops, I believe that we should not mention its author anymore, let's remove the syntax ...

**Comment by pvnr0082t** [comment]
@PeterDaveHello We don't need to mention the author anymore?

**Comment by PeterDaveHello** [comment]
@pvnr0082t in this case.

**Comment by pvnr0082t** [comment]
@PeterDaveHello Okay, I'll fix it soon.

**Comment by PeterDaveHello** [comment]
@pvnr0082t and all of his libs.

**Comment by pvnr0082t** [comment]
@maruilian11 @cdnjs/intern2 I've removed author I mentioned in the commit message. Please help me review this pull request, thank you.

**Comment by PeterDaveHello** [comment]
Let's give @extend1994 a try.

**Comment by maruilian11** [comment]
Why don't we cc the author in this case??

**Comment by pvnr0082t** [comment]
@maruilian11 @extend1994 I don't think we should set https://github.com/ReactTraining/react-router/tree/master/packages/react-router-dom#react-router-dom as `homepage` because it's the same as repository url.

**Comment by pvnr0082t** [comment]
>Why don't we cc the author in this case??

Actually, I don't know the reason. cc @PeterDaveHello

**Comment by maruilian11** [comment]
@pvnr0082t The link I mention is a reference I want you to click and take a look. 
The homepage link I want you to add is: https://reacttraining.com/react-router/

**Comment by pvnr0082t** [comment]
@extend1994 @maruilian11 I've added https://reacttraining.com/react-router/ as homepage. Please help me review it again. Thank you.

**Pull request merged**
