### PR TITLE
Add Iframe-Auto-Height-Jquery-Plugin@1.2.5

### PR DESCRIPTION
**Pull request by lcd78706**
Pull request for issue: #10773 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/Sly777/Iframe-Height-Jquery-Plugin
 * Official website (optional, not the repository): http://ilkerguller.com
 * NPM package url (optional):
 * License and its reference: MIT [ref](https://github.com/Sly777/Iframe-Height-Jquery-Plugin/blob/master/Src/License.txt#L1)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 9
   - Count of stars: 164
   - Count of forks: 52
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by lcd78706** [comment]
@x09326  Please help me review this PR. Thanks!
And is my commit message ok?

**Comment by lcd78706** [comment]
@x09326 
I have modified the commit message. Please review it again. Thanks!

**Comment by PeterDaveHello** [comment]
@extend1994 I don't think that you need to take this PR, this PR looks lake of review, not modification, also, you better leave comment before you take it.

**Comment by PeterDaveHello** [comment]
@lcd78706 would you like to finish this PR? The license info is missing GPL-3.0, also the library name should be `Iframe-Height-Jquery-Plugin`.

**Comment by extend1994** [comment]
Get it.

**Pull request closed without merging**
