### PR TITLE
add numjs w/ git auto-update

### PR DESCRIPTION
**Pull request by kennynaoh**
Pull request for issue: #8917 
Related issue(s): # #
@pvnr0082t , @x09326 Please help me review this PR, thanks!
Manually add old versions because the file structure is changed and manually change the file name in some of old versions.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/nicolaspanel/numjs
 * Official website (optional, not the repository): https://nicolaspanel.github.io/numjs/
 * NPM package url (optional): https://www.npmjs.com/package/numjs
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 120
   - Count of watchers: 12
   - Count of forks: 8
 * NPM download stats (optional):
   - Downloads in the last day: 23
   - Downloads in the last week: 75
   - Downloads in the last month: 244

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@kennynaoh You can just commit the versions that need to be manually added. In this case, you can just commit the versions before v0.7.0 which should be adjust. It will make review easier.

**Comment by kennynaoh** [comment]
ping @x09326

**Comment by x09326** [comment]
@kennynaoh 
Sorry for the late response, please rebase to the latest master branch.

**Comment by kennynaoh** [comment]
@pvnr0082t @x09326 I have rebased to the latest master branch. Please help me review it again, thanks!

**Comment by x09326** [comment]
LGTM

**Pull request merged**
