### PR TITLE
add Dropify@0.2.1 w/ auto update

### PR DESCRIPTION
**Pull request by onlineth**
https://github.com/cdnjs/cdnjs/issues/8349
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars:
   - Count of watchers:
   - Count of forks:
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hi @onlineth, thanks for the PR, however, we should set `dist` as base path, so that we won't need to have it in the path, btw, we prefer to use npm auto-update, if it possible to use it here? Thanks.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern2 please help review this PR as your practice.

**Comment by onlineth** [comment]
@PeterDaveHello Alright, I'll make the changes to the `dist` path, as far as the autoupdate, if I can use npm as an autoupdate, should I not include the `autoupdate {}`section and use `npmName: ` & `npmFileMap[{}]` instead or should I have both in there?

**Comment by PeterDaveHello** [comment]
@onlineth Remove the current one please, thanks.

**Comment by onlineth** [comment]
@PeterDaveHello Did, how does this one look?
https://github.com/cdnjs/cdnjs/pull/8382

**Pull request closed without merging**
