### PR TITLE
add canvid@1.6.0 w/ npm auto-update

### LINKED ISSUE #9379: [Request] Add canvid
**Library name:** canvid
**Git repository url:** https://github.com/gka/canvid
**npm package url(optional):** https://www.npmjs.com/package/canvid
**License(s):**
**Official homepage:** https://gka.github.io/canvid/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by kennynaoh**
Pull request for issue: #9379
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.
@pvnr0082t Please help me review this PR, thanks!
Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/gka/canvid
 * Official website (optional, not the repository): https://gka.github.io/canvid/
 * NPM package url (optional): https://www.npmjs.com/package/canvid
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 811
   - Count of watchers: 28
   - Count of forks: 54
 * NPM download stats (optional):
   - Downloads in the last day: 1
   - Downloads in the last week: 91
   - Downloads in the last month: 287

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9379, cc @gka

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Is the npm package official?

**Comment by kennynaoh** [comment]
This npm package is published from the person on git repo which is one of contributors, so I think it is. Is this information enough or not? Thanks!

**Comment by PeterDaveHello** [comment]
that's funny, so will you treat every contributor as the guy officially manage the project?

**Comment by gka** [comment]
Hi, I am one of the two co-authors of canvid (@moklick is the other one), and I can confirm this [npm package](https://www.npmjs.com/package/canvid) is official.

**Comment by PeterDaveHello** [comment]
@gka thanks!

**Pull request merged**
