### PR TITLE
Manually add missing files of jquery-validate@1.16.0

### LINKED ISSUE #11550: Missing jquery-validation localization for version 1.16.0
As per issue #9491, localization was added for jquery-validation. But in version 1.16.0 it is missing, it is present only in previous versions.

### PR DESCRIPTION
**Pull request by sufuf3**
close #11550

Pull request for issue: #11550
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/jquery-validation/jquery-validation
 * Official website (optional, not the repository): https://jqueryvalidation.org/
 * NPM package url (optional): 
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 472
   - Count of stars: 7842
   - Count of forks: 2352
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@dakshshah96 @cdnjs/intern3 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
It's because of file permissions problem.
The origin file with an octal value is not 664.

**Comment by extend1994** [comment]
Then let's mention the reason in the commit message?

**Comment by sufuf3** [comment]
@extend1994 I modified the commit message
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
origin permission is 775
That's why I `change messages_hr.js permissions from 775 to 664` let CDNJS can host.

It's a little bit hard for me that I should said `change messages_hr.js permissions from 775 to 664 because origin permissions is 775`? Isn't redundant about 775?

Could you give me some example to let commit message better?
Thank you.

**Comment by extend1994** [comment]
@sufuf3 "change messages_hr.js permissions from 775 to 664" only describe what you have done, not explaining that you manually add the file because of it? If it were me, I will say something like "Manually add files because messages_hr.js stops auto-update from getting the files under localization and therefore change messages_hr.js permissions from 775 to 664". It might be a little long and redundant. Maybe we can discuss this to let it better.

**Comment by sufuf3** [comment]
@extend1994 I modified the commit message
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@dakshshah96 @cdnjs/intern3 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@qwe19272375 @hare1039 @maruilian11 @pvnr0082t 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@hare1039 @qwe19272375 @pvnr0082t @maruilian11
Please help me review this PR, Thank you.

**Pull request merged**
