### PR TITLE
add TypeWatch v2.2.2 with git autoupdate config

### LINKED ISSUE #7848: [Request] Add typewatch
**Library name:** jquery.typewatch
**Git repository url:** https://github.com/dennyferra/TypeWatch
**License(s):** Dual licensed under the MIT and GPL licenses:
*  http://www.opensource.org/licenses/mit-license.php
*  http://www.gnu.org/licenses/gpl.html

**Official homepage:** https://github.com/dennyferra/TypeWatch

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #7848 
@kennynaoh Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/dennyferra/TypeWatch
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 152
   - Count of watchers: 11
   - Count of forks: 43
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7848, cc @dennyferra

### CODE REVIEW

**Comment by kennynaoh** [comment]
@pvnr0082t 
I found that the `jquery.typewatch.js` version in master branch is 3.
But the version in latest release is still 2.2.2.
Please confirm that.
Thanks!

**Comment by pvnr0082t** [comment]
@kennynaoh I think you don't need to care about master branch. Maybe the author is still developing and don't want to release now.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Comment by PeterDaveHello** [comment]
We need to confirm its license.

**Comment by pvnr0082t** [comment]
@kennynaoh I confirmed license in [Check license](https://github.com/dennyferra/TypeWatch/issues/28) and it's GPLv3. Please help me review again, thank you.

**Comment by PeterDaveHello** [comment]
@pvnr0082t why not send a PR to contribute to upstream? The package.json should be updated.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I will send it.

**Comment by PeterDaveHello** [comment]
Something wrong, can you update your commit and PR to trigger a new build test?

**Comment by pvnr0082t** [comment]
@kennynaoh Please help me review again, thank you.

**Pull request merged**
