### PR TITLE
update license field & add auto-update config in datatables-colvis

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 

For #5544, datatables-colvis (ColVis) use `MIT` as its copyright license now.
see: https://github.com/DataTables/ColVis/blob/master/License.txt
repo: https://github.com/DataTables/ColVis
So I updated the license field in package.json.

The old filename field in package.json was point to `datatables.colvis.min.js`, but datatables-colvis's repo use `dataTables.colVis.js` for the real file's name.
So I add the latest stable version 1.1.2 to update the filename field.

For #5491, I add git auto-update config for it.
Would you mind checking this PR for me? Thank you~ :-D

- [ ] Not found on cdnjs repo
- [x] No already exist issue and PR
- [ ] Notable popularity : **Watch `10`, Star `34`, Fork `45`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by maruilian11** [comment]
@Amomo i think your auto update filemap doesn't include `dataTables.colvis.jqueryui.css`.

**Comment by Amomo** [comment]
oh thanks, I didn't notice that `dataTables.colvis.jqueryui.css` is all lower case.
I will fix it later~

**Comment by Amomo** [comment]
@maruilian11 I have rebased the PR, could you take a look?
Thank you~ :-D

**Comment by maruilian11** [comment]
@Amomo i think `css/dataTables.colvis*` would be better. would you mind updating it?

**Comment by Amomo** [comment]
@maruilian11 ok, I have changed it.

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Comment by PeterDaveHello** [comment]
You changed the filename but I can't see and comment in the commit message.

**Pull request closed without merging**
