### PR TITLE
Manually add findAndReplaceDOMText old versions

### LINKED ISSUE #11429: [Request] manually add old versions of findAndReplaceDOMText
Missing some tag in GitHub.
Maybe add old versions mentioned in https://github.com/padolsey/findAndReplaceDOMText#changelog.

related issue: cdnjs/cdnjs#11099

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/46368636-request-manually-add-old-versions-of-findandreplacedomtext?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by qwe19272375**
Pull request for issue: #11429 
Related issue(s): #11099 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/padolsey/findAndReplaceDOMText
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/findandreplacedomtext
 * License and its reference: 
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 25
   - Count of stars: 490
   - Count of forks: 85
 * NPM download stats (optional):
   - Downloads in the last day: 111
   - Downloads in the last week: 729
   - Downloads in the last month: 2635

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

Manually add v0.1.0~v0.3.0 of findAndReplaceDOMText because of missing
tags in GitHub repository, close #11429, cc #11099, cc @padolsey

### CODE REVIEW

**Comment by qwe19272375** [comment]
@cdnjs/intern3 please help me review this PR, thanks.

**Comment by qwe19272375** [comment]
@extend1994 thanks!
@cdnjs/intern3 please help me review this PR, thanks.

**Comment by sufuf3** [comment]
Same as @extend1994 
The files are fine.
Just need to modify the commit message.

BTW, the commit message uses 50/72 characters.
Let's revise the commit message as the followings is better to us to trace git log.
```
Manually add v0.1~v0.3.0 of findAndReplaceDOMText

Manually add v0.1~v0.3.0 of findAndReplaceDOMText from GitHub repository
because of missing tags. close #11429, cc #11099, cc @padolsey
```

**Comment by sufuf3** [comment]
Except for the commit message, I think this PR LGTM
@qwe19272375 would you continue this PR ASAP?
Thank you.

**Comment by qwe19272375** [comment]
Modified commit message.
@sufuf3 Thanks for your advice.
@cdnjs/intern3 please help me review it, thank you.

**Comment by PeterDaveHello** [comment]
@extend1994 forgot to approve?

**Comment by PeterDaveHello** [comment]
Please mention the tag is `git tag` clearly next time @qwe19272375

**Comment by PeterDaveHello** [comment]
@maruilian11 please help review this PR, thanks.

**Comment by extend1994** [comment]
Sorry, I forgot to approve this after I approved... :sweat:

**Comment by qwe19272375** [comment]
Added version `0.4.1`.
@cdnjs/intern3 please help me review this PR, thanks!

**Comment by maruilian11** [comment]
`Manually add v0.1~v0.3.0 of findAndReplaceDOMText `
--->
`Manually add findAndReplaceDOMText  old versions`?

**Comment by maruilian11** [comment]
@PeterDaveHello Sorry, I use the blame function to find the commit. But looks like the wrong commit is the last commit of version v0.4.1.

**Comment by extend1994** [comment]
@PeterDaveHello Because you once requested change, please help review this, thanks.

**Comment by xtuc** [comment]
No manual addition anymore. Please enable autoupdate for the package, see contributing.md files

**Pull request closed without merging**
