### PR TITLE
add auto-update config & update to a stable version of bootstrap-rtl

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 , From #5276, I would like to fix bootstrap-rtl to point to a stable version.
repo: https://github.com/morteza/bootstrap-rtl
The latest stable version of bootstrap-rtl is v3.3.4, but cdnjs doesn't have now.
So I add v3.3.4 and update version number to 3.3.4 in package.json.
I also add git auto-update config in package.json.
Would you mind checking this PR for me? Thank you~ :-)

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
There is a [folder for cdnjs](https://github.com/morteza/bootstrap-rtl/tree/v3.3.2/dist/cdnjs), ping morteza for help. We can do it in a better way.

**Comment by PeterDaveHello** [comment]
What happened?

**Comment by Amomo** [comment]
It has a new version now, I am fixing my commits.
I will open it later...

**Comment by maruilian11** [comment]
@Amomo because the files are under `dist`, i this you can use `css/*` :)
can you rebase and tag me again? thank you!

**Comment by Amomo** [comment]
@maruilian11 Thanks for your reminding!
I have corrected it and rebased, could you check again? Thanks~

**Comment by maruilian11** [comment]
@PeterDaveHello i think the PR is ok.

**Comment by PeterDaveHello** [comment]
[IMPORTANT - No more manual submissions](https://github.com/cdnjs/cdnjs#important---no-more-manual-submissions)

**Comment by Amomo** [comment]
@maruilian11 I have modified my first commit to point version field to a stable version.

And, in second commit, bootstrap-rtl is `Unlicensed`, see [bootstrap-rtl/UNLICENSE](https://github.com/morteza/bootstrap-rtl/blob/master/UNLICENSE) .
The author note it as `"Unlicensed Public Domain"` in bower.json.

Could you please check this PR again? Thank you very much!

**Comment by maruilian11** [comment]
@Amomo plz see this case https://github.com/cdnjs/cdnjs/pull/5552
i keep thinking how can we make sure the license is fine for us to add it?

**Comment by PeterDaveHello** [comment]
Ping @Amomo

**Pull request closed without merging**
