### PR TITLE
Add angular.js 1.7.3, 1.7.4 and 1.7.5

### PR DESCRIPTION
**Pull request by Ermineia**
# Pull request template for new library

Pull request for issue: #12937 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

## Profile of the lib

* Git repository (required):
* Official website (optional, not the repository):
* NPM package url (optional):
* License and its reference:
* GitHub / Bitbucket popularity (required):
  * Count of watchers:
  * Count of stars:
  * Count of forks:
* NPM download stats (optional):
  * Downloads in the last day:
  * Downloads in the last week:
  * Downloads in the last month:

## Essential checklist

* [ ] I'm the author of this library
  * [ ] I would like to add link to the page of this library on CDNJS on website / readme
* [ ] This lib was not found on cdnjs repo
* [ ] Doesn't already exist / has duplicate issue and PR
* [x] The lib has notable popularity
  * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [ ] More than 800 downloads stats per month on npm registry
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [ ] Has valid tags for each versions (for git auto-update)
* [ ] Auto-update setup
* [ ] Auto-update target/source is valid.
* [ ] Auto-update filemap is correct.

## Git commit checklist

* [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [x] The parent of the commit(s) in the PR is not older than 3 days.
* [x] Pull request is sent from a non-master branch with a meaningful name.
* [x] Separate unrelated changes into different commits.
* [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [ ] Close corresponding issue in commit message
* [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by Ermineia** [comment]
@PeterDaveHello can you assist me with moving this forward?  I am eager to have this latest version of the library available on cdnjs.

**Comment by extend1994** [comment]
Hi @Ermineia I am here to help merge this PR, wanna check & discuss 
1. Are v1.7.3/1.7.4/1.7.5 in 
https://github.com/cdnjs/cdnjs/pull/13026/commits/bd9da44728b8c4c83ce74e9b05da9b334e3731ad
from 
https://code.angularjs.org/ ? Please append the source code reference in the commit message, thanks :)
2. I don't think git/npm auto-update config, which cdnjs currently supports, for angular can work. The reason is that not all built files are on 
https://github.com/angular/bower-angular or https://npmjs.com/angular/. Files are only on https://code.angularjs.org/ I suppose, but cdnjs can't use it as the source of auto-update config. So commit 
https://github.com/cdnjs/cdnjs/pull/13026/commits/e7ed762b1b63af30118dc81b0081791d2d520dc1 and 
https://github.com/cdnjs/cdnjs/pull/13026/commits/895b7ce7a7bce7e4ab0783715f5075966aa44e91 won't work. What do you think?


Sorry for the late review!

**Comment by Ermineia** [comment]
@extend1994 Thanks for getting back with a review.  

I am still new with git.  When attempting to rebase to bd9da44 to amend the commit comment, I must have done something incorrect.  As a result, I am not sure what the state of my branch is now and resetting has made things more confusing.  I don't know how to recover.

**Comment by PeterDaveHello** [comment]
Added in https://github.com/cdnjs/cdnjs/commit/c4f3e68c2046b7d7403b0c2994bcaf2a89dd5046

**Pull request closed without merging**
