### PR TITLE
[New][Author] Add jexcel w/ npm auto-update via single package.json

### PR DESCRIPTION
**Pull request by paulhodel**
Related issue(s): #10671

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): http://github.com/paulhodel/jexcel
 * Official website (optional, not the repository): http://bossanova.uk/jexcel
 * NPM package url (optional): https://www.npmjs.com/package/jexcel
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 13
   - Count of stars: 90
   - Count of forks: 21
 * NPM download stats (optional):
   - Downloads in the last day: 0 
   - Downloads in the last week: 120
   - Downloads in the last month: 180

# Essential checklist
 * [x] I'm the author of this library
 * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
 *[ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
 * [ ] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by extend1994** [comment]
Hi @paulhodel Can I know who did you commit the file? Via GitHub or local git command? I will help you depends on how you work 😃

**Comment by sufuf3** [comment]
Helped rebase master and modify the commit message.

@paulhodel May I ask that should cdnjs need to host `jquery.jcalendar.css` and `jquery.jcalendar.js`?
Because I saw we just need to add `jquery.jexcel.css` and `jquery.jexcel.js` ib [README](https://github.com/paulhodel/jexcel#basic-demo)
Thank you.

**Comment by paulhodel** [comment]
jCalendar is an extension and should be included to allow date and datetime column types. Thanks.

**Comment by sufuf3** [comment]
@cdnjs/active-contributor @cdnjs/intern3 please help review this PR, thanks.

**Comment by PeterDaveHello** [comment]
The excluded files didn't seem to be confirmed that we don't need them? @extend1994 @sufuf3 can you please help send PRs to add that two libraries?

**Comment by PeterDaveHello** [comment]
@extend1994 don't bother to change author format in this moment, we didn't focus on that yet.

**Pull request merged**
