### PR TITLE
Add lemonade@2.1.0 with git autoupdate

### PR DESCRIPTION
**Pull request by Piicksarn**
@Amomo  , would you mind to have a look at the pr?
The PR is referenced to issue  #6112.
The git repo : https://github.com/dope/lemonade/tree/v2.1

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `39`, Star `425`, Fork `75`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

Thank you!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@Piicksarn Add the template first.

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine, could you take a look?
Thank you!

**Comment by dope** [comment]
@Piicksarn thanks so much!

**Comment by PeterDaveHello** [comment]
:100:

**Pull request merged**
