### PR TITLE
add jquery.mobilephonenumber@1.0.7 w/ npm auto-update

### LINKED ISSUE #8070: [Request] Add jquery.mobilePhoneNumber
**Library name:** jquery.mobilePhoneNumber
**Git repository url:** https://github.com/stripe/jquery.mobilePhoneNumber

### PR DESCRIPTION
**Pull request by nolsherry**
@pvnr0082t Please help me review this pull request, thanks!
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/stripe/jquery.mobilePhoneNumber
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/jquery.mobilephonenumber
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 265
   - Count of watchers: 53
   - Count of forks: 26
 * NPM download stats (optional):
   - Downloads in the last day: 11
   - Downloads in the last week: 198
   - Downloads in the last month: 329

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [X] This lib was not found on cdnjs repo
 * [X] No already exist / duplicated issue and PR
 * [X] The lib has notable popularity
   * [X] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [X] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [X] Has valid tags for each versions (for git auto-update)
 * [X] Auto-update setup
 * [X] Auto-update target/source is valid.
 * [X] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X] The parent of the commit(s) in the PR is not old than 3 days.
 * [X] Pull request is sending from a non-master branch with meaningful name.
 * [X] Separate unrelated changes into different commits.
 * [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [X] Close corresponding issue in commit message
 * [X] Mention related issue(s), people in commit message, comment.

close #8070, cc @michaelvillar

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@nolsherry You should check if the same issue exists next time. In this case, you should also mention #8209 in commit message and comment template.

**Comment by nolsherry** [comment]
@pvnr0082t I have modified the commit messages, please help me review this PR, thanks!

**Comment by pvnr0082t** [comment]
@nolsherry You need to separate `close`.  `close #8070, close #8209`

**Comment by nolsherry** [comment]
@pvnr0082t, I have modified the commit message, please help me review this PR, thanks!

**Pull request merged**
