### PR TITLE
add keywords in libs #5422

### PR DESCRIPTION
**Pull request by Piicksarn**

### CODE REVIEW

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you please take a look at the pr? Thank you!

**Comment by PeterDaveHello** [comment]
@cdnjs/intern first.

**Comment by Amomo** [comment]
I think these keywords are right!
@Piicksarn would you use multi-line commit message to record these affected libs.
Thank you~ :-)

**Comment by Piicksarn** [comment]
@Amomo, thanks for your suggestion and i have the commit corrected.
would you please checkout the PR again?
:smiley:

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine, could you take a look?
Thank you~ :-D

**Comment by PeterDaveHello** [comment]
I need a double check, @maruilian11 take this.

**Comment by maruilian11** [comment]
@Piicksarn i have checked it! could you rebase it and tag me again? thank you!

**Comment by Piicksarn** [comment]
@maruilian11, would you please check it again? thank you~

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok~

**Pull request merged**
