### PR TITLE
Add angular-moment-picker@0.9.11 w/ npm autoupdate

### LINKED ISSUE #9886: [Request] Add angular-moment-picker
**Library name:** angular-moment-picker
**Git repository url:** https://github.com/indrimuska/angular-moment-picker
**npm package url(optional):** 
**License(s):**
**Official homepage:** https://indrimuska.github.io/angular-moment-picker/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by qwe19272375**
Pull request for issue: #9886 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/indrimuska/angular-moment-picker
 * Official website (optional, not the repository): https://indrimuska.github.io/angular-moment-picker/
 * NPM package url (optional): https://www.npmjs.com/package/angular-moment-picker
 * License and its reference: MIT, [ref](https://github.com/indrimuska/angular-moment-picker/blob/master/LICENSE)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 16
   - Count of stars: 285
   - Count of forks: 86
 * NPM download stats (optional):
   - Downloads in the last day: 33
   - Downloads in the last week: 1223
   - Downloads in the last month: 4193

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9886, cc @indrimuska

### CODE REVIEW

**Comment by qwe19272375** [comment]
@cdnjs/intern3 please help me review this pr, thank you.

**Comment by sufuf3** [comment]
[review](https://trello.com/c/NHbUaGTb/1-review)

**Comment by qwe19272375** [comment]
Manually added angular-moment-picker@0.5.1.
@cdnjs/intern3 please help me review it, thanks.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern3 for multi-commits PR, let's increase minimum reviews from the team members to 3.

Ping @extend1994 @clairetsai818

**Comment by PeterDaveHello** [comment]
@qwe19272375 @extend1994 don't you need to request from me then?

**Pull request merged**
