### PR TITLE
Add cssesc@1.0.0 w/ npm auto-update

### LINKED ISSUE #11340: [Request] Add cssesc
**Library name:** cssesc
**Git repository url:** https://github.com/mathiasbynens/cssesc
**npm package name or url** (if there is one): cssesc
**License (List them all if it's multiple):** MIT
**Official homepage:** https://mths.be/cssesc
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by dakshshah96**
close #11340, cc @mathiasbynens

Pull request for issue: #11340 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/mathiasbynens/cssesc
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/cssesc
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 1
   - Count of stars: 40
   - Count of forks: 4
 * NPM download stats (optional):
   - Downloads in the last day: 162,706
   - Downloads in the last week: 742,415
   - Downloads in the last month: 3,409,614

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by dakshshah96** [comment]
@sufuf3 I get the following error when I run the minifier. This is probably because of ES6 JavaScript. cc @PeterDaveHello 
screenshot 2017-06-02 20 49 26

**Comment by PeterDaveHello** [comment]
@dakshshah96 what's the commit(version) minify-helper version you are using please? Updated to the latest?

**Comment by dakshshah96** [comment]
Yes @PeterDaveHello, I pulled the latest version from `master` and it still shows the same error when I run `minify.sh`.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern3 you guys have the same problem or not?

**Comment by sufuf3** [comment]
I was executed `web-minify-helper/minify.sh` in the commit https://github.com/PeterDaveHello/web-minify-helper/commit/a0445eb7e962329b897bf2eb0c1f6a7e3f590385 and it was generated the map and minified file.

Now, I update to the latest commit https://github.com/PeterDaveHello/web-minify-helper/commit/42156e139ae0a48b01f26e960196f0a403dcdc99 rerun `npm install` and `npm update`.
I meet problem as the followings:
```
Scaning direcotry...
Finding js to be compressed under . ...
Compressing cssesc.js ...
Parse error at cssesc.js:4,0
const object = {};
^
ERROR: Unexpected token: keyword (const)
    at JS_Parse_Error.Object.defineProperty.get (eval at <anonymous> (/home/sjfu/web-minify-helper/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:86:23)
    at fatal (/home/sjfu/web-minify-helper/node_modules/uglify-js/bin/uglifyjs:286:52)
    at run (/home/sjfu/web-minify-helper/node_modules/uglify-js/bin/uglifyjs:241:9)
    at Object.<anonymous> (/home/sjfu/web-minify-helper/node_modules/uglify-js/bin/uglifyjs:171:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
WARN: Dropping unused variable regexAlwaysEscape [cssesc.js:23,6]
Finding css to be compressed under . ...
All done!
```
And it just generates the `cssesc.min.js`, no map file.
My OS is Ubuntu.

**Comment by PeterDaveHello** [comment]
Looks like `uglify-js-harmony` in `web-minify-help` minified it with success, the error came from `uglify-js`.

**Comment by dakshshah96** [comment]
@sufuf3 Done 👍

**Comment by sufuf3** [comment]
@extend1994 @hare1039 @qwe19272375 
Please help review this PR, Thank you.

**Comment by sufuf3** [comment]
@extend1994 @hare1039 @qwe19272375
Please help review this PR, Thank you.

**Pull request merged**
