### PR TITLE
Add animatelo@1.0.1 w/ git auto-update 

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #10650

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/gibbok/animatelo
 * Official website (optional, not the repository): https://gibbok.github.io/animatelo/
 * NPM package url (optional): https://www.npmjs.com/package/animatelo
 * License and its reference: [MIT](https://github.com/gibbok/animatelo/blob/master/LICENSE)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 2
   - Count of stars: 56
   - Count of forks: 2
 * NPM download stats (optional):
   - Downloads in the last day: 0
   - Downloads in the last week: 3
   - Downloads in the last month: 9

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

Note this lib request issue was opened by Peter, so we can ignore the insufficient popularity.

### CODE REVIEW

**Comment by extend1994** [comment]
@cdnjs/intern3 Please help me review this pull request, thank you.

**Comment by extend1994** [comment]
@cdnjs/intern3 I renamed the files, please help me review this pull request again, thank you.

**Comment by extend1994** [comment]
@PeterDaveHello Please help me review this pull request, thank you.

Though I updated my branch again, that's because I just found I forgot to mention the origin of v1.0.0 after peer review. Change is `Manually add v1.0.0 cause the old naming scheme can't match the current one` -> `Manually add v1.0.0 from git repo because the old naming scheme can't match the current one`. So I think there is no big problem requiring another peer review. So I request your review directly.

**Comment by PeterDaveHello** [comment]
@extend1994 I'll suggest you to remove the duplicated parts in the second commit message next time.

**Pull request merged**
