### PR TITLE
add react-faux-dom@3.0.0 w/ npm auto-update

### LINKED ISSUE #9991: [Request] react-faux-dom
**Library name:** react-faux-dom
**Git repository url:** https://github.com/Olical/react-faux-dom
**npm package url(optional):** https://www.npmjs.com/package/react-faux-dom
**License(s):** Unlicence
**Official homepage:** https://github.com/Olical/react-faux-dom

### PR DESCRIPTION
**Pull request by sufuf3**
close #9991, cc @Olical
@kennynaoh please help me review this PR, thank you.

Pull request for issue: #9991 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/Olical/react-faux-dom
 * Official website (optional, not the repository): http://oli.me.uk/2015/09/09/d3-within-react-the-right-way/
 * NPM package url (optional): https://www.npmjs.com/package/react-faux-dom
 * License and its reference: Unlicense
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 22
   - Count of stars: 711
   - Count of forks: 57
 * NPM download stats (optional):
   - Downloads in the last day: 230
   - Downloads in the last week: 4088
   - Downloads in the last month: 12236

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Ping @kennynaoh

**Comment by sufuf3** [comment]
Ping @kennynaoh

**Comment by kennynaoh** [comment]
@sufuf3 Sorry for late response. I think this PR is ok. Please rebase to the latest master branch. Thanks!

**Comment by sufuf3** [comment]
@kennynaoh  I rebase to the latest master branch.
Please help me review this PR, thank you.

**Comment by Olical** [comment]
Thanks, everyone :)

**Pull request merged**
