### PR TITLE
[author] Added version 2.2.0 of jQuery-Form-Validator

### PR DESCRIPTION
**Pull request by victorjonsson**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Thanks, is it possible to use git/npm auto-update for it?

**Comment by victorjonsson** [comment]
Probably, I will look into it.

**Comment by PeterDaveHello** [comment]
Thanks.

**Comment by PeterDaveHello** [comment]
I just take a look at its repo, I think we could use git auto-update easily!

**Comment by victorjonsson** [comment]
Quick question. Would this be a correct config?

```
 "npmName": "jquery-fom-validator",
  "npmFileMap": [{
    "basePath": "/form-validator/",
    "files": [
      "*.js"
    ]
  }],
```

**Comment by PeterDaveHello** [comment]
Yes, this is for npm auto-update, I prefer to use git autoupdate, ref #3638, which is more reliable!

**Comment by victorjonsson** [comment]
Ah, thats not the git-auto-update config. Should I add this to package.json an do a new pr?

```
"autoupdate": {
    "source": "git",
    "target": "git://giithub.com/victorjonsson/jQuery-Form-Validator.git,
    "basePath": "",
    "files": [
      "form-validator/*"    
    ]
  }
```

**Comment by PeterDaveHello** [comment]
I think you should set bashPath to `form-validator`.

**Comment by victorjonsson** [comment]
As such?

```
"autoupdate": {
    "source": "git",
    "target": "git://github.com/victorjonsson/jQuery-Form-Validator.git,
    "basePath": "form-validator",
    "files": [
      "*"    
    ]
  }
```

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by victorjonsson** [comment]
#4583

**Comment by victorjonsson** [comment]
How does this work by the way? Will it automatically merge my PR:s as long as the tests passes?

**Comment by PeterDaveHello** [comment]
You don't need to send PR anymore unless you changed the structure.

**Comment by victorjonsson** [comment]
Awesome!

**Comment by victorjonsson** [comment]
I just tried to push tag only to see if it came through but it has not. Maybe it's something I'm misunderstanding here. I thought that pushed tags automatically would be fetched to this repo somehow?

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs#enabling-npm-auto-update
> many libs will change the naming or directory structure during different versions, and we may need to minify the lib without pre-minified dist files, so it'll be reasonable to delay for at most 30 hours, if you think there is a lib didn't been updated, please wait at least 30 hours for the process to audit it.

**Comment by victorjonsson** [comment]
okey. Another question: If I remove a tag will it also remove the code in the cdnjs-repo?

**Comment by PeterDaveHello** [comment]
No, once it picked, it won't be removed.

**Comment by victorjonsson** [comment]
Ok, then I know. Thanks!

**Pull request merged**
