### PR TITLE
add jQuery-linkify v1.1.7

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/SoapBox/linkifyjs
**Watch 21
  Star 143
 Fork 34**
@Piicksarn could you help me check out the PR for #6033 ? thank you~
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by Piicksarn** [comment]
@maruilian11, it's fine but need rebase to master!
thank you!

**Comment by maruilian11** [comment]
@Piicksarn i have rebased it ~

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you please have a look at the pr?
Thank you!

@ymh514, you could take a look at it as well.

**Comment by ymh514** [comment]
@Piicksarn Thanks a lot.

**Pull request merged**
