### PR TITLE
Enrich jquery-scrolldepth's package.json #5194

### PR DESCRIPTION
**Pull request by Piicksarn**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I think we can also add git auto-update config in it?

**Comment by Piicksarn** [comment]
@maruilian11, would you please checkout the PR for me?
the git repository url : https://github.com/robflaherty/jquery-scrolldepth
Thank you!

**Comment by maruilian11** [comment]
@Piicksarn would u mind add a commit to remove the unrecognized field, like `moduletype`, `dependencies` and  `ignore`? for #5476 thank you!

**Comment by Piicksarn** [comment]
@maruilian11, would you please take a look again?
Thank you!:))

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Comment by Piicksarn** [comment]
@maruilian11, would you please take a look again?
thank you^^

**Comment by maruilian11** [comment]
i think you can remove the `dependencies` field, too :)

**Comment by Piicksarn** [comment]
@maruilian11, no～peter had told about keeping the `dependencies` here!

**Comment by Piicksarn** [comment]
@maruilian11,would you mind to checkout the pr again? thank you!

**Comment by maruilian11** [comment]
@Piicksarn really? can you show me where he talk about keep the `dependencies`? thank you!
i think this PR is ok. can you rebase it and tag me again?
btw, you can change the assignee to me, so i can check the PR more quickly, thank you~

**Comment by Piicksarn** [comment]
@maruilian11, peter commanded below the code, so after i rebase my commit than it disappeared!
And the pr is already rebase to master.
thanks for checking the pr again!

**Comment by maruilian11** [comment]
@Piicksarn so you mean we need to keep all the dependencies for all libs? or just this case?

**Comment by maruilian11** [comment]
@Piicksarn i think the PR is ok. can you rebase it and tag me again? thank you~

**Comment by Piicksarn** [comment]
@maruilian11, i have it rebased and need your help for checking the pr!~
thank you!

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Pull request merged**
