### PR TITLE
Add redux-form-material-ui@4.1.2 w/ npm auto-update

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #10332 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/erikras/redux-form-material-ui
 * Official website (optional, not the repository): 
 * NPM package url (optional): https://www.npmjs.com/package/redux-form-material-ui
 * License and its reference: [MIT](https://github.com/erikras/redux-form-material-ui/blob/master/LICENSE)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 9
   - Count of stars: 245
   - Count of forks: 48
 * NPM download stats (optional):
   - Downloads in the last day: 505
   - Downloads in the last week: 2,592
   - Downloads in the last month: 10,220

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

The first line of commit message is 51 chars, but clean and clear, easy to understand.
Note the [demo page](http://erikras.github.io/redux-form-material-ui/) will stop web browser operation.

### CODE REVIEW

**Comment by extend1994** [comment]
@cdnjs/intern3 please help me review this pull request, thank you.

**Comment by extend1994** [comment]
@hare1039 I mentioned that in comment of pull request, I think it's fine because it's still clean and clear, easy to understand.

**Comment by extend1994** [comment]
@PeterDaveHello please help me review this pull request, thank you.

**Comment by PeterDaveHello** [comment]
@extend1994 you should ask review from your mates again.

**Comment by extend1994** [comment]
@PeterDaveHello Okay Sorry!

**Pull request merged**
