### PR TITLE
jquery.isotope - add npm auto-update

### PR DESCRIPTION
**Pull request by desandro**
Update Isotope description, homepage, maintainers, git url

### CODE REVIEW

**Comment by desandro** [comment]
On a related note, what kind of effort would it take to move the url from `jquery.isotope` to just `isotope`? jQuery is no longer required as of v2.

**Comment by drewfreyling** [comment]
That would be ok for future versions but we'd have to leave the existing versions (2.0.0, 1.5.25) under the jquery.isotope name. Looping in @PeterDaveHello to get his opinion on this too.

**Comment by desandro** [comment]
Ah, thanks! I'm cool that.

**Comment by PeterDaveHello** [comment]
Renaming is okay, I'm going to rebuild the test, because we had a problem on circleCI and fixed now.

**Pull request merged**
