### PR TITLE
Add modestmaps@3.3.5 w/ npm auto-update

### LINKED ISSUE #11132: [Request] Add modestmaps-js
**Library name:** modestmaps-js
**Git repository url:** https://github.com/stamen/modestmaps-js
**npm package name or url** (if there is one): https://www.npmjs.com/package/modestmaps
**License (List them all if it's multiple):** BSD
**Official homepage:** http://modestmaps.com/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by dakshshah96**
Pull request for issue: #11132 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/stamen/modestmaps-js
 * Official website (optional, not the repository): http://modestmaps.com/
 * NPM package url (optional): https://www.npmjs.com/package/modestmaps
 * License and its reference: **Awaiting author response on BSD license**
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 68
   - Count of stars: 565
   - Count of forks: 156
 * NPM download stats (optional):
   - Downloads in the last day: 8
   - Downloads in the last week: 307
   - Downloads in the last month: 1,422

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by extend1994** [comment]
Please ask reivew from us after the author's response about the license.

**Comment by dakshshah96** [comment]
@extend1994 Please add `in progress` and `waiting for response` label here.

**Comment by PeterDaveHello** [comment]
@dakshshah96 better tag @qwe19272375 to do it

**Comment by sufuf3** [comment]
@extend1994 May I ask that what license is your concern?
Because the license link in `modestmaps.js` always direct to `BSD-2-Clause` (https://github.com/stamen/modestmaps-js/blob/master/modestmaps.js#L7-L8)

And there is no response from the author.
Maybe we can continue.
What do you think?

I think this PR looks good to me.

**Comment by sufuf3** [comment]
@dakshshah96 
thanks for contribution.
Would you mind working on this and helping improve this PR?
If you have any question, please let us know.

Many thanks.

**Pull request merged**
