### PR TITLE
Add git autoupdate config in crunch

### PR DESCRIPTION
**Pull request by Piicksarn**
@LeaYeh would you please help me checking the commit :)?
This commit is for adding git autoupdate config in crunch lib.
Thank you！

### CODE REVIEW

**Comment by LeaYeh** [comment]
i thought replace crunch.js with crunch*.js would be better, because the author would be possible add .min file in the future.

**Comment by Piicksarn** [comment]
ok!~i have changed the file map to crunch*.js.

**Comment by LeaYeh** [comment]
i think it is fine. @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Thanks.

**Pull request merged**
