### PR TITLE
[new] bootstrap-slider

### PR DESCRIPTION
**Pull request by dbeckwith**
https://github.com/seiyria/bootstrap-slider

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
should not touch sortable, and filename field invalid

**Comment by dbeckwith** [comment]
sorry, not sure how the sortable file got in there, I'll fix both of those things

**Comment by dbeckwith** [comment]
There, I reverted the sortable package.json back to what it was and fixed the filename field.

**Comment by PeterDaveHello** [comment]
Please squash them into only one commit as document said, thanks.

**Comment by dbeckwith** [comment]
done

**Pull request merged**
