### PR TITLE
add react-bootstrap-table w/ npm autoupdate

### LINKED ISSUE #8751: [Request] Add react-bootstrap-table
**Library name:** react-bootstrap-table
**Git repository url:** https://github.com/AllenFang/react-bootstrap-table
**npm package url(optional):** 
**License(s):**
**Official homepage:** https://github.com/AllenFang/react-bootstrap-table
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8751 
@x09326 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/AllenFang/react-bootstrap-table
 * Official website (optional, not the repository):  http://allenfang.github.io/react-bootstrap-table/
 * NPM package url (optional): https://www.npmjs.com/package/react-bootstrap-table
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 628
   - Count of watchers: 44
   - Count of forks: 240
 * NPM download stats (optional):
   - Downloads in the last day: 667
   - Downloads in the last week: 4756
   - Downloads in the last month: 21427

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment

close #8751, cc @AllenFang

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@pvnr0082t as we discussed before, we need double confirmations in this case, so just assign to two reviewers at the same time, thanks.

**Comment by kennynaoh** [comment]
I think it is also necessary to add the css file, isn't it?
Thanks!

**Comment by pvnr0082t** [comment]
@kennynaoh @x09326 I have added css files. Please help me review again, thank you.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Thanks.

**Comment by PeterDaveHello** [comment]
@x09326 please also help review this PR, thanks.

**Comment by x09326** [comment]
@pvnr0082t 
Sorry for the late response.
I think it is okay.
Please rebase it with the master branch.

**Comment by pvnr0082t** [comment]
@kennynaoh @x09326 I have rebased with the latest master branch. Please help me review again, thank you.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Thanks.

**Comment by PeterDaveHello** [comment]
@pvnr0082t where did you get the js file of v0.1.0?

**Comment by pvnr0082t** [comment]
@PeterDaveHello I grab js file of v0.1.0 from npm.

**Comment by PeterDaveHello** [comment]
@pvnr0082t I only see those files:
├── css
│   ├── react-bootstrap-table.css
│   └── react-bootstrap-table.min.css
├── dist
│   └── react-bootstrap-dropdown.min.js
├── lib
│   ├── BootstrapTable.js
│   ├── Const.js
│   ├── index.js
│   ├── TableBody.js
│   ├── TableColumn.js
│   ├── TableHeaderColumn.js
│   ├── TableHeader.js
│   └── TableRow.js
├── package.json
└── README.md

Did I miss something?

**Comment by pvnr0082t** [comment]
@PeterDaveHello I diff the content of `react-bootstrap-dropdown.min.js` in v0.1.0 and `react-bootstrap-table.min.js` in v0.1.1. They are the same but different name and haven't been minified, so I rename `react-bootstrap-dropdown.min.js` -> `react-bootstrap-table.js` and minified them.
Actually, the files named `react-bootstrap-table.min.js` really minified until v1.2.9.

**Comment by PeterDaveHello** [comment]
Awesome!

**Pull request merged**
