### PR TITLE
[author] [new] Add goodshare.js 3.0

### PR DESCRIPTION
**Pull request by enjoyiacm**

### CODE REVIEW

**Comment by enjoyiacm** [comment]
What's wrong? How to fix that: "ci/circleci — Your tests failed"?

**Comment by PeterDaveHello** [comment]
You should add the files.

**Comment by enjoyiacm** [comment]
Anybody here?

**Comment by PeterDaveHello** [comment]
You should add real files, cc @cdnjs/intern.

**Comment by enjoyiacm** [comment]
You mean, add to this PR goodshare.min.js from my repo?

**Comment by enjoyiacm** [comment]
Whats wrong again?

**Comment by PeterDaveHello** [comment]
I think the [Details](https://circleci.com/gh/cdnjs/cdnjs/4466) told you. And I think you should consider to read our readme and contributing document first, thanks

**Comment by enjoyiacm** [comment]
I',m translate your documentations to my language and and did everything I understood from the translation..

**Comment by PeterDaveHello** [comment]
You should put the file under the version of the current version.

**Comment by enjoyiacm** [comment]
File ``goodshare.min.js`` put from https://github.com/enjoyiacm/goodshare.js/tree/3.0 it's current version of my project.

**Comment by PeterDaveHello** [comment]
You should also commit it in 3.0 folder. And by the way, we usually host the libs with notable popularity only.

**Comment by enjoyiacm** [comment]
``...with notable popularity only.``

Hmm.. After this sentence, I specifically looked for commits in your repository library, which you have included in the list. There are more than half — are the same as my project. Why do you to them is don't write? Or do you want to say that my project isn't popular because it has a total of 8 stars on GitHub?

For reference: according Yandex.Metrika, the official website of my project request at ~1.5k-2k time per hour. Therefore, administrator of my hosting said: "or transferring to cdnjs.com your project or we'll block your account". Since this all started. I'm not going to mess with CDN but just hosting can fall from a load — had to listen administrator!

**Comment by PeterDaveHello** [comment]
There is a sentence in our readme :
 > Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, but as long as reasonable popularity can be demonstrated the library will be added.

We removed that rule for a while, but there are too many libs without any stars/forks/watchers, if you don't mind, please email/tweet me your reference, I'll be happy to help you host your lib, thanks!

**Pull request closed without merging**
