### PR TITLE
Add a license of ng-clip, cc #9248

### PR DESCRIPTION
**Pull request by clairetsai818**
https://github.com/asafdav/ng-clip/blob/master/LICENSE

### CODE REVIEW

**Comment by clairetsai818** [comment]
@PeterDaveHello  please help me to check this!

**Comment by PeterDaveHello** [comment]
@clairetsai818 you mixed two libraries here, please remove one of the changes in you branch:
 - https://github.com/clairetsai818/cdnjs/blob/clairetsai818-ng-clip-2/ajax/libs/ng-clip/package.json
 - https://github.com/clairetsai818/cdnjs/blob/clairetsai818-ng-clip-2/ajax/libs/tweet/package.json

**Comment by kennynaoh** [comment]
duplicate with https://github.com/cdnjs/cdnjs/pull/9400
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
So maybe the change will help prevent the duplication.

**Pull request closed without merging**
