### PR TITLE
Add mouse0270-bootstrap-notify v3.1.6 and v3.1.7

### PR DESCRIPTION
**Pull request by maruilian11**
@Piicksarn @cdnjs/intern2 Could you help me review this PR thanks!
Just found out this repo hasn't set git tags for latest version.
And some user seem ask for the latest version, thought they may not use cdnjs, we still can update the version on cdnjs.
3.1.6 is from https://github.com/mouse0270/bootstrap-notify/commit/4ed0351388d381f5c223282b3ff8a91827ea4f8e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
3.1.7 is from https://github.com/mouse0270/bootstrap-notify/commit/f59de58ce7ea0f1fdcd32b7f1af301959897be05

https://github.com/mouse0270/bootstrap-notify/issues/127

### CODE REVIEW

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM

**Comment by maruilian11** [comment]
@PeterDaveHello I rebase this commit with the latest master branch, do I need to ping others to review again?

**Comment by PeterDaveHello** [comment]
Why not?

@x09326 can you help review this one?

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Don't you need to mention related issue like #6251 #6727 ?

**Comment by maruilian11** [comment]
got it, I will do it next time.

**Pull request merged**
