### PR TITLE
transfer mdbootstrap to git auto-update

### LINKED ISSUE #9531: Update MDBootstrap to 4.2.0
Recently, we released MDBootstrap 4.2.0. Our customers ask for MDB 4.2.0 on cdnjs. Could you please update MDBootstrap to 4.2.0?

Github repo: https://github.com/mdbootstrap/bootstrap-material-design

### PR DESCRIPTION
**Pull request by pvnr0082t**
Pull request for issue: #9531 
@x09326 @kennynaoh Please help me review this pull request, thank you.

use git auto-update instead of npm auto-update

close #9531

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@pvnr0082t let's use a shorter one-line commit message in the first commit, ref: 6bbc638

**Comment by pvnr0082t** [comment]
@kennynaoh @x09326 I have updated the commit message. Please help me review it again, thank you.

**Comment by PeterDaveHello** [comment]
```
Conflicting files
ajax/libs/mdbootstrap/4.2.0/css/mdb.css
ajax/libs/mdbootstrap/4.2.0/css/mdb.min.css
ajax/libs/mdbootstrap/4.2.0/img/overlays/01.png
ajax/libs/mdbootstrap/4.2.0/img/overlays/02.png
ajax/libs/mdbootstrap/4.2.0/img/overlays/03.png
ajax/libs/mdbootstrap/4.2.0/img/overlays/04.png
ajax/libs/mdbootstrap/4.2.0/img/overlays/05.png
ajax/libs/mdbootstrap/4.2.0/img/overlays/06.png
ajax/libs/mdbootstrap/4.2.0/img/overlays/07.png
ajax/libs/mdbootstrap/4.2.0/img/overlays/08.png
ajax/libs/mdbootstrap/4.2.0/img/overlays/09.png
```

**Comment by pvnr0082t** [comment]
@kennynaoh @x09326 I have fixed conflict. Please help me review it again, thank you.

**Comment by x09326** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM
ping @PeterDaveHello

**Pull request merged**
