### PR TITLE
[new] Add OOJS w/ npm autoupdate

### PR DESCRIPTION
**Pull request by kemayo**
Library: OOjs, core part of Mediawiki's JS.

 * Git repository (required): https://phabricator.wikimedia.org/diffusion/GOJS/
 * Official website (optional, not the repository): https://www.mediawiki.org/wiki/OOjs
 * NPM package url (optional): https://www.npmjs.com/package/oojs
 * GitHub / Bitbucket popularity (required): Not on github

Includes all npm releases.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@kemayo I think https://phabricator.wikimedia.org/diffusion/GOJS/ is good enough as git repo URL. How do you think?
BTW, Please leave message after you make some changes, thank you.

**Comment by kemayo** [comment]
Sure, that'll work. The way it's set up has a bunch of different basically-equivalent git repos which are kept in sync, depending on which tool you're using to interact with them. The phabricator one is probably representative, and the most likely one for someone to stumble across though, so I'm fine using it here.

**Comment by pvnr0082t** [comment]
@kemayo Thank you. It looks good. :facepunch:

**Comment by kemayo** [comment]
Added it. I cribbed the style from jQuery's, just referencing the team descriptor that's in the copyright notice, and linking to the AUTHORS.txt.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Some versions seem to be missing, I'll take care of them.

**Comment by PeterDaveHello** [comment]
Just found that the missing versions do not have the pre-built files, so no mind.

**Pull request merged**
