### PR TITLE
add fuckadblock v3.1.1 with git autoupdate

### PR DESCRIPTION
**Pull request by maruilian11**
@LeaYeh could u plz help me check this commit for #5137?
it's about add a new lib with git autoupdate. thx :)

### CODE REVIEW

**Comment by drewfreyling** [comment]
Closing as this is a dupe of #5153

**Comment by PeterDaveHello** [comment]
Dupe of #7152 not #5153.

**Comment by PeterDaveHello** [comment]
If there is a problem with #7152, I'll merge this one, @maruilian11 please rebase your branch with our latest master branch, thank you.

**Comment by maruilian11** [comment]
@PeterDaveHello updated.

**Comment by maruilian11** [comment]
@PeterDaveHello updated.

**Comment by drewfreyling** [comment]
@PeterDaveHello ah sorry about that one guys. Long day.

**Comment by maruilian11** [comment]
it's ok, i was not sure if we can add this lib :grin:

**Comment by PeterDaveHello** [comment]
Please use npm auto-update.

**Pull request merged**
