### PR TITLE
Add Data.Task component of Folktale library

### PR DESCRIPTION
**Pull request by graforlock**
Pull request to add a glorious **Folktale**'s Data.task component (http://folktalejs.org/). Folktale is really **new**, and already getting popular quick among  Functional Programming libraries.

Data.task is responsible for [Future] execution of asynchronous calls (buffers or ajax), but in a monadic, free from unsafe mutated-state execution.

Folktale modules (and the framework in general) were mentioned and heavily used in several books on Functional programming, to mention; Brian Lonsdorf (DrBoolean) -> 'Professor Frisby's Mostly Adequate Guide to Functional Programming' and Dan Mantyla -> 'Functional Programming in JavaScript'.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Is it possible to add npm or git auto-update config as our document says? Thanks.

**Comment by graforlock** [comment]
The problem is that its a repo is pre-build source so there is a need to run Makefile beforehand in order to make dist folder. 

There is, however, a zipped and build release however in their releases, that only requires to be unzipped.

Is any of it compatible with your convention system?

**Comment by graforlock** [comment]
Oops closed by accident.

There is a requirement to use Makefile to make dist folder as it is a source repo.

However, in the releasees there is a already built release that only needs to be unzipped.

Is any of this compatible with your conventions?

**Comment by PeterDaveHello** [comment]
hmmmm ... currently not

**Comment by PeterDaveHello** [comment]
Hello, any updates here? Thanks.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@graforlock Would you like to finish this PR?
How about add `data.task.umd.js` in your GitHub repo?
Then we can use git auto-update config to automatically add files when you release the new version.
Thank you.

**Comment by sufuf3** [comment]
Memo: Only need to manually add v3.0.0 from https://github.com/folktale/data.task/releases/download/v3.0.0/data.task-3.0.0.tar.gz refer to https://github.com/folktale/data.task/tree/v3.0.0#using-with-commonjs

**Comment by PeterDaveHello** [comment]
I believe that they have migrated to https://github.com/origamitower/folktale, and started to provide umd build on npm registry, @graforlock would you like to update this PR for that? Thanks!

**Comment by sashberd** [comment]
@PeterDaveHello Is @extend1994 [added ](https://github.com/cdnjs/cdnjs/pull/12234#pullrequestreview-80708462)new PR and this one could be closed?

**Comment by PeterDaveHello** [comment]
@sashberd they are not the same.

**Comment by sufuf3** [comment]
@graforlock thanks for contribution.
Would you like to work on this and help improve this PR?
If you have any question, please let us know.

Many thanks.

**Pull request closed without merging**
