### PR TITLE
[author] [new] Add reactstrap w/ npm auto-update via single package.json

### PR DESCRIPTION
**Pull request by TheSharpieOne**
Pull request for issue: #11470 
Related issue(s): reactstrap/reactstrap#476 #11483

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/reactstrap/reactstrap.git
 * Official website (optional, not the repository): https://reactstrap.github.io/
 * NPM package url (optional): https://www.npmjs.com/package/reactstrap
 * License and its reference: MIT ref: [in repo](https://github.com/reactstrap/reactstrap/blob/master/LICENSE) and [in package.json](https://github.com/reactstrap/reactstrap/blob/d153a7801bb88f117a5e6c92b4bf838c9af3feb5/package.json#L83)
 * GitHub / Bitbucket popularity (required): **GitHub**
   - Count of watchers: 81
   - Count of stars: 1728
   - Count of forks: 171
 * NPM download stats (optional):
   - Downloads in the last day: 4,229
   - Downloads in the last week: 17,630
   - Downloads in the last month: 61,143

# Essential checklist
 * [x] I'm the author of this library _(I am a contributor and member of reactstrap)_
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand. (see https://github.com/cdnjs/cdnjs/pull/11483#issuecomment-312019540)
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
Error:
> The branch reactstrap for this pull request is a little bit old, please rebase this branch with the latest master branch from upstream!

Checklist: 
> The parent of the commit(s) in the PR is not old than 3 days.

parent commit is 8ebf4610 Jun 27, 2017, 3:40 PM EDT (2 days ago).... rules seem a little out of whack.

**Comment by PeterDaveHello** [comment]
@TheSharpieOne well, we didn't count that by 3 days, I can rebase this branch with the latest master branch if you didn't clone the repository and work locally, what do you think?

**Comment by TheSharpieOne** [comment]
@PeterDaveHello Yes please. I have been trying to clone it locally but my work firewall makes that task near impossible.
GitHub sadly enough does not let me do that from the web UI, even though the feature does exist for the original repo the pull request is being made to.

**Comment by PeterDaveHello** [comment]
@TheSharpieOne doing now!

**Comment by virgofx** [comment]
:+1:

**Pull request merged**
