### PR TITLE
add RyanMullins-angular-hammer v2.1.10

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/RyanMullins/angular-hammer
**Watch 10
  Star 112
 Fork 87**
@LeaYeh could you help me check out the PR for #5996 ? thank you~
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Same naming problem here again, [RyanMullins/angular-hammer](https://github.com/RyanMullins/angular-hammer) was forked from [monospaced/angular-hammer](https://github.com/monospaced/angular-hammer) which was fored from [randallb/angular-hammer](https://github.com/randallb/angular-hammer), to avoid ambiguous here, I think we should better name it to `RyanMullins-angular-hammer` instead of `angular-hammer`.

cc @cdnjs/team-cdnjs @cdnjs/intern @RyanMullins @monospaced @randallb

**Comment by maruilian11** [comment]
ok.

**Comment by Amomo** [comment]
Agree. The author use `ryanmullins-angular-hammer` for bower install.

**Comment by LeaYeh** [comment]
i think this pr is fine :)
@PeterDaveHello

**Comment by PeterDaveHello** [comment]
Should say the version you add in commit message ...

**Comment by maruilian11** [comment]
ooooops :stuck_out_tongue_winking_eye:

**Comment by maruilian11** [comment]
@LeaYeh could you help me check this PR again? thank you :smiley:

**Comment by maruilian11** [comment]
@LeaYeh ：)

**Comment by LeaYeh** [comment]
i think this pr is ok.
@PeterDaveHello

**Pull request merged**
