### PR TITLE
Update git autoupdate config and add zxcvbn@4.1.1

### PR DESCRIPTION
**Pull request by Piicksarn**
@Amomo ,  would you mind to have a look at the pr?
The PR is referenced to issue  #6085, and **the older git autoupdate config isn't suitable for the new structure.**
i fix the config and add the latest version.
Furthermore, the .js file seems to be minified.

The information of the pr:
The git repo :  https://github.com/dropbox/zxcvbn/tree/4.1.1

- [ ] **`Not found on cdnjs repo`**
- [x] No already exist issue and PR
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

Thank you! :smiley:

### CODE REVIEW

**Comment by Amomo** [comment]
@Piicksarn I think your commit could separate into 2 parts.

You could add v4.1.1 and update "version" & "filename" field first.
Then, update the auto-update config in package.json.

**Comment by Amomo** [comment]
@Piicksarn could you please update your PR~?

**Comment by PeterDaveHello** [comment]
What the reson why to close it?

**Comment by Piicksarn** [comment]
The commits had already done.

**Comment by PeterDaveHello** [comment]
@Piicksarn please point out the corresponding commit before you close it.

* 9d6044a update auto-update config of zxcvbn

**Pull request closed without merging**
