### PR TITLE
d3-composite-projections library added [author] [new]

### PR DESCRIPTION
**Pull request by rveciana**
I would like to add the library to the cdn. 
The library source can be found at:
https://github.com/rveciana/d3-composite-projections

### CODE REVIEW

**Comment by Amomo** [comment]
Hi @rveciana 
Sorry for replying late.
This library currently doesn't have enough popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) for detail.

We suggest you to make a pull request when the library has more popularity.
Thanks for your contribution. :-)

**Comment by PeterDaveHello** [comment]
Looks good with its npm stats, so let's add this.

**Comment by PeterDaveHello** [comment]
@rveciana sorry for the late reply, do you mind me to send a new commit to do this or you would like to transfer to use npm auto-update in the config and then rebase this branch with our latest master branch? Many thanks.

**Comment by rveciana** [comment]
Thank you Peter,

I've downloaded the latest master version, updated my package to the latest
version and commited again. I hope it's the right way to do it. I think I
already had the auto-update configurated.

Roger

2016-02-22 8:20 GMT+01:00 Peter Dave Hello <notifications@github.com>:

**Comment by PeterDaveHello** [comment]
Hi @rveciana, the parent of the first commit in this PR still looks too old(See: https://github.com/rveciana/cdnjs/commit/dd1ba246e5d434a1f3fe828c0cb03c6419b79a81), and I didn't see the transfer from git auto-update to npm auto-update, in the **update**, https://github.com/rveciana/cdnjs/commit/548509985539e61a440055355a5b1be248669656#diff-2e803a5f51e64ca71553f8c842580da9, seems you only moved files in 0.3.1 to v0.3.5, no real changes there, is that correct? Actually we accept old versions.

**Comment by rveciana** [comment]
Sorry, I didn't understand you correctly.

I've made a new commit that I think is correct, using npm auto-update

Roger

2016-02-22 12:18 GMT+01:00 Peter Dave Hello <notifications@github.com>:

**Comment by PeterDaveHello** [comment]
@rveciana no mind, what's the reason why to moved files in 0.3.1 to v0.3.5 without real changes there, is that correct? and would you please squash/fixup these commits into only one commit and rebase your branch for this PR with our latest master branch? Thank you.

**Comment by rveciana** [comment]
I think that now I've done it
I've merged the two commits:
git rebase --interactive HEAD~2
And then my branch
git fetch origin
git rebase origin/master

Is this correct? I'm newbie to complex git projects.

The version change was due to the gulp settings, so the correct version is v0.3.5

**Comment by PeterDaveHello** [comment]
@rveciana please force push to GitHub so that I can confirm that if is good, thank you.

**Comment by rveciana** [comment]
I've been trying to do it all day, but I don't find the correct way. Is there any other solution, such as opening a new pull request with the proper commits?

**Comment by PeterDaveHello** [comment]
@rveciana for the easiest way, you can delete your forked cdnjs, re-fork, redo the commit, and send a new PR. If you would like to learn some git/GitHub skills, you can try to 1) fixup/squash your commits into only one commit, 2) rebase your master branch(the branch of your PR) upon cdnjs's master branch, 3) using force push to overwrite this PR. Since you used master branch to send a PR which is not a good practice of sending PR, it may pain a little bit, I'll respectfully suggest you to create new branches for PRs in the future! Thanks.

**Comment by rveciana** [comment]
I've made a new PR: https://github.com/cdnjs/cdnjs/pull/7080
I will definitely learn more about GIT, thank you a lot for your patience

**Comment by PeterDaveHello** [comment]
No problem @rveciana.

**Comment by PeterDaveHello** [comment]
Close per #7080

**Pull request closed without merging**
