### PR TITLE
add license kartograph-js, cc #5500

### PR DESCRIPTION
**Pull request by hare1039**
license ref: https://github.com/kartograph/kartograph.js/blob/master/LICENSE

### CODE REVIEW

**Comment by hare1039** [comment]
@kennynaoh please check

**Comment by PeterDaveHello** [comment]
@hare1039 let's use a complete and meaningful sentence to ask your mentor for help, it'll be more polite.

**Comment by hare1039** [comment]
@PeterDaveHello Okey, I'll do it next time. Thank you for telling me that.

**Comment by PeterDaveHello** [comment]
@hare1039 same as #9683

**Comment by PeterDaveHello** [comment]
@hare1039 BTW, you could update your origin comment right now, it's never too late to be polite.

**Comment by hare1039** [comment]
@PeterDaveHello thanks for the suggestion.

**Comment by kennynaoh** [comment]
LGTM
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
It looks like new CI doesn't work now. @kennynaoh You can help to trigger CI again.

**Comment by kennynaoh** [comment]
@PeterDaveHello Please help me trigger the CI again. Thanks!

**Comment by PeterDaveHello** [comment]
Done

**Comment by kennynaoh** [comment]
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
@kennynaoh You should wait for CI test finished...

**Comment by kennynaoh** [comment]
@PeterDaveHello The CI seems stuck. Please help me trigger it again. Thanks.

**Comment by PeterDaveHello** [comment]
Not that case, use circle ci's result.

**Comment by kennynaoh** [comment]
OK, ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
Please don't forget to mention the related issue next time.

**Pull request merged**
