### PR TITLE
[new][author] Add Angular-Patternfly

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
# Profile of the lib
 * Git repository (required): https://github.com/patternfly/angular-patternfly
 * Official website (optional, not the repository): http://www.patternfly.org/angular-patternfly/
 * NPM package url (optional): https://www.npmjs.com/package/angular-patternfly
 * License and its reference: Apache License 2.0 https://github.com/patternfly/angular-patternfly/blob/master/LICENSE.txt
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:26
   - Count of stars: 102
   - Count of forks: 82
 * NPM download stats (optional):
   - Downloads in the last day: 93
   - Downloads in the last week: 1167
   - Downloads in the last month: 5017

# Essential checklist
 * [ x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by maruilian11** [comment]
Hi @jeff-phillips-18, That's such a nice PR! Only few things need to be modified.
1. Would you please change `homepage` to use SSL? Thanks.
2. Would you please add a rule in auto-update filemap:
```
"npmFileMap": [
  {   
    "basePath": "dist",
    "files": [
      "!(docs|less)/**/*",
      "angular-patternfly*"
    ]   
  }   
]
```
Because the original one can't fetch `angular-patternfly.js` and `angular-patternfly.min.js`.
Of course, if you don't have much time, I'm willing to help you modify your commits. :+1:

**Comment by jeff-phillips-18** [comment]
Thank @maruilian11 !  I have updated as you suggested. Thanks for your help.

**Comment by maruilian11** [comment]
@jeff-phillips-18 The online test shows you need to rebase the master with our latest one on website. Feel free to ask question if you meet problems. Or I can directly help you with that if you don't mind. :smile:

**Comment by PeterDaveHello** [comment]
@maruilian11 That's not correct.

The correct thing to do is to rebase the branch for this pull request with our latest master branch.

**Comment by maruilian11** [comment]
Sorry, I typed too fast. I meant you need to rebase **this branch** with our latest master branch.

**Comment by jeff-phillips-18** [comment]
@maruilian11 What is the best way to rebase when using the sparse checkout?

**Pull request closed without merging**
