### PR TITLE
[new] [author] Added angular-gravatar@0.4.1

### PR DESCRIPTION
**Pull request by wallin**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Would you please fix your package.json? Thanks.

**Comment by wallin** [comment]
Fixed it!
(btw. I used the `cdnjs-importer` script to add the library + package.json)

**Comment by PeterDaveHello** [comment]
Please squash them into only one commit as our document said, thanks!

**Comment by wallin** [comment]
Sorry about that! All squashed now

**Comment by PeterDaveHello** [comment]
It'll be even better if you can reabse on our latest master branch next time, I'll manually pick it up now.

**Pull request closed without merging**
