### PR TITLE
Add bootstrap-progressbar@0.9.0

### PR DESCRIPTION
**Pull request by Piicksarn**
@maruilian11 ,  would you mind to have a look at the pr?
The PR is referenced to issue  #6078  
The information of the pr:
The git repo :  https://github.com/minddust/bootstrap-progressbar/tree/v0.9.0

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `38`, Star `470`, Fork `139`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

Thank you! :smiley:

### CODE REVIEW

**Comment by maruilian11** [comment]
@Piicksarn i think if the filemap could be `marx*.+(css|map)` would be better.

**Comment by Piicksarn** [comment]
@maruilian11, sorry...i find there is no files named marx*.+(css|map)!

**Comment by maruilian11** [comment]
@Piicksarn sorry,my bad, wrong lib, could you rebase it again? thank you

**Comment by Piicksarn** [comment]
@maruilian11, i have it rebased! would you mind to have a look at the pr again?
Thank you!

**Pull request merged**
