### PR TITLE
[new] add horsey.js@2.6.0 with git auto-update, close #5053

### LINKED ISSUE #5053: [Request] Add horsey
It would be nice if you could add https://github.com/bevacqua/horsey

### PR DESCRIPTION
**Pull request by Amomo**
Hi, @Piicksarn, I add a new lib with git auto-update from the request #5053
Would you mind checking this PR for me?
Thank you~ :-)

### CODE REVIEW

**Comment by Piicksarn** [comment]
i think it's fine～
you can use **/* when base path set to dist, unless there already exist file needless to update :D

**Comment by Amomo** [comment]
Thanks for your suggestion, I will follow that. :D
@PeterDaveHello, Could you take a look?

**Comment by PeterDaveHello** [comment]
It'll be good if you can add some keywords in package.json.

**Comment by Amomo** [comment]
Thanks! Next time I will do that.

**Comment by PeterDaveHello** [comment]
You can now send a new PR to do that.

**Comment by Amomo** [comment]
I have sent one~ #5098

**Pull request merged**
