### PR TITLE
Adding RxJS-DOM

### PR DESCRIPTION
**Pull request by mattpodwysocki**
Updating with the latest RxJS-DOM.  Note that I am the author

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Commit's parent were too old, can not merge.
Missing `filename` field?
Need to add auto-update config.

**Comment by crissdev** [comment]
@PeterDaveHello I see the library already has the auto-update config in place which makes this PR superfluous.

**Comment by PeterDaveHello** [comment]
https://cdnjs.com/libraries/rxjs-dom

**Comment by PeterDaveHello** [comment]
Thanks @crissdev

**Pull request closed without merging**
