### PR TITLE
Add glyphicons fonts.

### PR DESCRIPTION
**Pull request by yohankoehler**
*add fonts directory with glyphicons

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Is it possible to apply it to auto-update config in https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/bootswatch/package.json?

**Comment by IonicaBizau** [comment]
@PeterDaveHello There is the `npmFileMap`, probably added by the importer. Isn't that enough?

**Comment by PeterDaveHello** [comment]
I meant not manually add these files.

**Comment by PeterDaveHello** [comment]
`fonts` already exist in the config, but we can not always manually add it, so should find a method to handle this.

**Comment by alanmsm** [comment]
Still return 404 at 3.3.5 version..

**Pull request closed without merging**
