### PR TITLE
Update dygraphs to 2.0.0

### PR DESCRIPTION
**Pull request by danvk**
Pull request for issue: #10358 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of stars:
   - Count of watchers:
   - Count of forks:
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [x] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by danvk** [comment]
OK, I have no idea what this error means:

```
    dygraph 
      ✗ dygraph: filename from package.json exists 
        » ./ajax/libs/dygraph/1.1.1/dygraph.min.js does not exist but is referenced in package.json! // valid-packages-test.js:109 
```

I'm going to need some help.

**Comment by maruilian11** [comment]
Hi @danvk,  I'm here to help you send the PR.

Because our bot will check if `filename` file is there or not, you need to push real files of `2.0.0`. 

Please separate into 2 commit, 
one for updating lib info:
* update the `keywords`

 and the other for updating auto-update config:
* delete **git** auto-update and add **npm** auto-update 
* change `filename` to `dygraph.min.js`
*  change `version` to `2.0.0`
*  add real files of `2.0.0` (create `2.0.0` folder)

Because I think we don't need to fetch `tests.js` and `*.jar`, please consider using the following npm auto-update config which has been tested:
```js
"npmname": "dygraphs",
"npmfilemap": [
  {
    "basepath": "dist",
    "files": [
      "**/!(test*|*.jar)"
    ]
  }
],
```
P.S. You can use `git rebase -i HEAD~3` to avoid reopen a new PR, and please use `git rebase master` to rebase with our latest master branch. Thank you very much!

Feel free to ask for help. Or if you don't have much time on this, I am willing to send the PR for you.

**Comment by danvk** [comment]
@maruilian11 if you could handle it that would be greatly appreciated. I don't really care about the keywords.

**Comment by PeterDaveHello** [comment]
@danvk thanks for your PR, to make sure, do you mean you don't mind that @maruilian11 directly send a new PR to fix the things you wanna do? Or you'll like us to help you finish this PR? Thank.

**Comment by danvk** [comment]
The former -- I'm very happy to let you guys take care of this.

**Pull request closed without merging**
