### PR TITLE
add I18next related libs

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 for #6467, I add 
- `jquery-i18next` at v0.0.5 
- `i18next-browser-languageDetector` at v0.0.10 

and add `npm` auto-update config in their package.json.

their repo url:
- https://github.com/i18next/jquery-i18next
- https://github.com/i18next/i18next-browser-languageDetector

Would you mind checking this PR for me? Thank you~ :-D

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [ ] Notable popularity : 
`jquery-i18next`: **Watch `1`, Star `0`, Fork `0`**
`i18next-browser-languageDetector` :**Watch `2`, Star `2`, Fork `0`**

- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Why don't you use https://github.com/i18next/i18next-browser-languageDetector/blob/master/i18nextBrowserLanguageDetector.min.js ?

**Comment by Amomo** [comment]
@PeterDaveHello but "i18nextBrowserLanguageDetector.min.js" do not exist in the releases.

**Comment by PeterDaveHello** [comment]
Okay, it's new.

**Comment by maruilian11** [comment]
@Amomo these two libs seem to have new version...

**Comment by Amomo** [comment]
@maruilian11 I have updated them to latest version, could you help me check again?
Thank you~ :-D

**Comment by maruilian11** [comment]
@Amomo sorry... could you rebase them? thank you.

**Comment by Amomo** [comment]
@maruilian11  I have rebased this PR to latest master branch, could you help me check again?
Thank you! :-D

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Comment by PeterDaveHello** [comment]
Hey please don't add multiple libs in a single PR next time.

**Comment by PeterDaveHello** [comment]
@Piicksarn @LeaYeh please double check this, thanks.

**Comment by Piicksarn** [comment]
@Amomo, the pr is fine but rebase to master is required*
would you ping me again after rebasing to master?
Thank you and sorry for the delay.

**Comment by Amomo** [comment]
@Piicksarn I have rebased this PR on latest master branch.
Could you help me checking it again? Thank you! :-D

**Pull request merged**
