### PR TITLE
Add evil-icons

### PR DESCRIPTION
**Pull request by outpunk**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
As the first time you add a new lib, please also add its real files, thanks.

**Comment by outpunk** [comment]
And version into the package.json, too?

**Comment by PeterDaveHello** [comment]
Yes please.

**Comment by outpunk** [comment]
Sorry, can't squash — the repo is too big.

**Comment by PeterDaveHello** [comment]
If you don't mind, I can manually do this this morning, you can still get your credits on github.

**Comment by outpunk** [comment]
No problem. Thank you!

**Comment by outpunk** [comment]
Thanks!

**Comment by PeterDaveHello** [comment]
np

**Pull request closed without merging**
