### PR TITLE
add inferno v0.7.9 with npm auto-update config

### LINKED ISSUE #8157: [Request]: Add Inferno JS
Library name: inferno
Git repository url: https://github.com/trueadm/inferno
npm package url(optional):

License(s): The MIT license
Official homepage: http://infernojs.org/

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #8157
@pvnr0082t please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/trueadm/inferno
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/inferno
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 1,776
   - Count of watchers: 96
   - Count of forks: 56
 * NPM download stats (optional):
   - Downloads in the last day: 329
   - Downloads in the last week: 419
   - Downloads in the last month: 1419

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8157, cc @trueadm

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@kennynaoh I think you can use http://infernojs.org as `homepage`.

**Comment by kennynaoh** [comment]
@pvnr0082t 
But it doesn't work now.
Are you sure about adding [this](http://infernojs.org/) as `homepage`?
Thanks!

**Comment by pvnr0082t** [comment]
@kennynaoh But they said `new website coming soon`. I think you can add.

**Comment by trueadm** [comment]
Hi, I'm the author of Inferno. Thanks for submitting this to cdnjs! The projects website is currently in development and should appear at that URL when ready - if that helps.

**Comment by PeterDaveHello** [comment]
@trueadm Thanks.

**Comment by PeterDaveHello** [comment]
@kennynaoh let's use http://infernojs.org/ as homepage.

**Comment by kennynaoh** [comment]
Got it.
@pvnr0082t 
I have added `homepage`.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Pull request merged**
