### PR TITLE
add split.js@1.2.0 w/ git auto-update

### LINKED ISSUE #10154: [Request] Add Split.js
**Library name:** Split.js
**Git repository url:** https://github.com/nathancahill/Split.js
**npm package url(optional):** https://www.npmjs.com/package/split.js
**License(s):** https://github.com/nathancahill/Split.js/blob/master/LICENSE.txt
**Official homepage:** http://nathancahill.github.io/Split.js/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by lcd78706**
close #10154, cc @nathancahill

Pull request for issue: #10154 
Related issue(s): # #
@x09326 Please review this PR. Thanks!

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/nathancahill/Split.js
 * Official website (optional, not the repository): https://nathancahill.github.io/Split.js/
 * NPM package url (optional): https://www.npmjs.com/package/split.js
 * License and its reference: MIT https://github.com/nathancahill/Split.js/blob/v1.2.0/package.json#L14
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 2434
   - Count of watchers: 57
   - Count of forks: 125
 * NPM download stats (optional):
   - Downloads in the last day: 61
   - Downloads in the last week: 654
   - Downloads in the last month: 2199

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by lcd78706** [comment]
@pvnr0082t  I have modified it. Please review again. Thanks!

**Comment by pvnr0082t** [comment]
@lcd78706 I just asked `why`. Could you explain the reason first?

**Comment by lcd78706** [comment]
@pvnr0082t 
Because I once added a library whose license in package.json is wrong, I found its license reference from commit.
And I forgot the license in this library's package.json is correct, so I didn't paste the reference you gave.
Sorry about that.

**Comment by pvnr0082t** [comment]
@lcd78706 If license you found is different between `package.json` and license.txt or somewhere, the better way is to confirm with author first.

**Comment by PeterDaveHello** [comment]
@kennynaoh @x09326 please help review again.

**Comment by kennynaoh** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
Please mention the reason why you choose git auto-update when there are two sources or more.

**Pull request merged**
