### PR TITLE
Add gotem w/ npm auto-update via single package.json

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #10509

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/callmecavs/gotem
 * Official website (optional, not the repository): 
 * NPM package url (optional): https://www.npmjs.com/package/gotem
 * License and its reference: [MIT](https://github.com/callmecavs/gotem#license)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 11
   - Count of stars: 386
   - Count of forks: 8
 * NPM download stats (optional):
   - Downloads in the last day: 0
   - Downloads in the last week: 2 
   - Downloads in the last month: 58

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

@cdnjs/intern3 Please help me review this pull request, thank you.
Note that The first line of commit message is 52 chars, but still clear and easy to understand.

### CODE REVIEW

**Comment by callmecavs** [comment]
@extend1994 killer job writing this up, thanks so much. 

to the reviewers - im the owner, happy to answer questions if any

**Comment by hare1039** [comment]
@sufuf3 [Add library by single package.json](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson). Assignment of this week.

**Comment by extend1994** [comment]
@sufuf3 Please help me review it again, thank you.

**Comment by pvnr0082t** [comment]
@callmecavs Thanks.

@cdnjs/intern3 Please DO NOT ignore the author.

**Comment by extend1994** [comment]
@PeterDaveHello Please help me review this pull request, thank you.

**Comment by PeterDaveHello** [comment]
@callmecavs I have a question, do we need both `gotem.js` and `gotem.module.js`? Or just `gotem.js` for the browsers? Thanks.

**Comment by PeterDaveHello** [comment]
@extend1994 would you please help confirm the files should be added as as the previous comment ⬆️  asked? Thanks.

**Comment by extend1994** [comment]
@PeterDaveHello Okay, I will :+1:

**Comment by callmecavs** [comment]
@PeterDaveHello @extend1994 hey all, sorry about the delay.  the `gotem.module.js` is an ES6 module - it won't run as is in the browser.  only the `gotem.js` file should be included - that's UMD wrapped so it can execute via `<script>` tag

**Comment by PeterDaveHello** [comment]
@callmecavs would you consider to provide minified file officially so that we can have better integrity of the file? Thanks a lot!

**Comment by PeterDaveHello** [comment]
@cdnjs/intern3 ⬆️

**Pull request merged**
