### PR TITLE
add license of stylus, cc #5500

### PR DESCRIPTION
**Pull request by jj528s35**
https://github.com/stylus/stylus/blob/dev/LICENSE

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@jj528s35 You should tag me after you send PR and CI test finished.

**Comment by pvnr0082t** [comment]
@jj528s35 Please add `Ref:` at the front of reference link. 
For example: `Ref: https://github.com/stylus/stylus/blob/dev/LICENSE`

**Comment by pvnr0082t** [comment]
Remember to give a more meaningful branch name.

**Comment by pvnr0082t** [comment]
LGTM
ping @cdnjs/intern2

**Comment by kennynaoh** [comment]
LGTM

**Pull request merged**
