### PR TITLE
add paradeiser v0.4.2 with git auto-update

### LINKED ISSUE #5859: [Request] Add Paradeiser [author]
**Library name:** Paradeiser
**Git repository url:** https://github.com/lucidlemon/paradeiser
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://lucidlemon.github.io/paradeiser/
**Wanna say something? Leave message here:** Paradeiser is an easy to use menu for mobile views, it is very easy to include and is pretty lightweight as well. It is sort of an alternative to the Hamburger menu.

### PR DESCRIPTION
**Pull request by maruilian11**
close #5859, cc @lucidlemon
**git repo url:** https://github.com/lucidlemon/paradeiser
**Watch 10
  Star 328
 Fork 28**
@Amomo could u help me check this PR for #5859 ? thank you!
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine, could you take a look? Thanks! :-D

**Comment by PeterDaveHello** [comment]
Wrong file permission here ...

**Comment by PeterDaveHello** [comment]
cc @maruilian11 @drewfreyling

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs/commit/8127b58ded28d03c45814d122a64ef3a4ae96dad

**Comment by maruilian11** [comment]
sorry, i will check next time.

**Pull request merged**
