### PR TITLE
add sheepit@ w/ git autoupdate

### LINKED ISSUE #9032: [Request] Add SheepIt!
**Library name:** SheepIt!
**Git repository url:**https://github.com/wongalus/sheepit
**npm package url(optional):** 
**License(s):**SheepIt is free software and you can distribute it and/or modify it under the terms of MIT
**Official homepage:**http://www.mdelrosso.com/sheepit/
**Wanna say something? Leave message here:**This is forked from mdelrosso/sheepit
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37986166-request-add-sheepit?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #9032 
@kennynaoh @x09326 Please help me review this pull request, thank you.
Manually add the other versions due to all git tags with prefix, and add it in .gitignore

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/mdelrosso/sheepit
- Official website (optional, not the repository): http://www.mdelrosso.com/sheepit/
- NPM package url (optional):
- GitHub / Bitbucket popularity (required):
  - Count of stars: 70
  - Count of watchers: 16
  - Count of forks: 46
- NPM download stats (optional):
  - Downloads in the last day:
  - Downloads in the last week:
  - Downloads in the last month:
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [ ] The lib has notable popularity
  - [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [ ] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

close #9032 , cc @mdelrosso

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@PeterDaveHello This lib looks old. Should I still try to open an issue to suggest author add `git tags` without prefix?

**Comment by PeterDaveHello** [comment]
I don't have a reason not to ask @pvnr0082t

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by pvnr0082t** [comment]
Still no response.

**Comment by PeterDaveHello** [comment]
@pvnr0082t maybe try to manually add it first?

**Comment by sufuf3** [comment]
ping @pvnr0082t 
Thank you.

**Comment by sufuf3** [comment]
ping @pvnr0082t
Thank you.

**Comment by sufuf3** [comment]
@pvnr0082t
Would you mind working on this and helping improve this PR?

This will be a great work.
Many thanks.

**Pull request closed without merging**
