### PR TITLE
add missing versions of p2.js

### PR DESCRIPTION
**Pull request by maruilian11**
@LeaYeh could you help me check this PR for #6074 ? thank you!

### CODE REVIEW

**Comment by maruilian11** [comment]
@amomo could you help me checkout this PR? thank you!

**Comment by Amomo** [comment]
@maruilian11 the commit message is a little bit too long...
Could you use `"0.2.0~0.4.0"` to instead every version number? 

And, it will be a great help if you attach the repo's url and told me what you did in this PR in the comment.

**Comment by maruilian11** [comment]
@Amomo i think showing each version number is better, we're not sure if the author add version between 0.2.0 and 0.4.0, though its possibility is low.

**Comment by maruilian11** [comment]
@PeterDaveHello could you check this PR?

**Comment by Amomo** [comment]
@maruilian11 ok, could you rebase this PR to latest master branch?
Thank you! :-)

**Comment by PeterDaveHello** [comment]
`v0.2.0~0.4.0` will be okay.

**Pull request merged**
