### PR TITLE
Add trackpad-scroll-emulator@1.0.8 w/ git autoupdate

### LINKED ISSUE #9916: [Request] Add trackpad-scroll-emulator
**Library name:** trackpad-scroll-emulator
**Git repository url:** https://github.com/jnicol/trackpad-scroll-emulator
**License(s):** MIT

In this issue, we are going to host a new library on cdnjs, if you'll like to work locally, I'll suggest you start with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are too many files in this repo, without sparseCheckout, the whole process will be super slow, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#d-adding-a-new-library

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks.

### PR DESCRIPTION
**Pull request by petrgazarov**
Pull request for issue: https://github.com/cdnjs/cdnjs/issues/9916

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/jnicol/trackpad-scroll-emulator
 * Official website (optional, not the repository): N/A
 * NPM package url (optional): N/A
 * License and its reference: [MIT](https://github.com/jnicol/trackpad-scroll-emulator/blob/master/LICENSE)
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 195
   - Count of watchers: 15
   - Count of forks: 87

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hi @petrgazarov, please also minify the css file, thanks!

**Comment by petrgazarov** [comment]
@PeterDaveHello Do we want to add a minified version in addition to the plain css or just leave the minified version?

**Comment by PeterDaveHello** [comment]
We will add a minified version in addition to the plain css and preserve the non-minified one, unless it's not pre-compiled which means it will not work.

**Comment by petrgazarov** [comment]
Hey @PeterDaveHello, I minified the css file and left the original CSS file. Ready for review.

> preserve the non-minified one, unless it's not pre-compiled which means it will not work.

Just want to make sure I understand you correctly -> you are talking about scss and less files here?

**Comment by PeterDaveHello** [comment]
@petrgazarov you are correct :)

**Pull request merged**
