### PR TITLE
add auto-update config & minified files in coin-slider

### PR DESCRIPTION
**Pull request by Amomo**
Hi @LeaYeh , From #5195, I have add minified files in coin-slider and point filename field to `coin-slider.min.js`. I also add git auto-update config in package.json.
repo : https://github.com/kopipejst/coin-slider
Would you mind checking this PR for me? Thank you~ :-)

- [ ] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `24`, Star `118`, Fork `128`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by Amomo** [comment]
@LeaYeh I have rebased this PR to match the latest master branch.
Could you take a look? Thank you!

**Comment by Amomo** [comment]
@LeaYeh I have rebased this PR to match the latest master branch.
Could you take a look? Thank you!

**Comment by LeaYeh** [comment]
ithink this pr is ok. i'm sorry for making you wait so long, please rebase this pr again.

**Comment by Amomo** [comment]
@LeaYeh I have rebased it, could you check again? Thank you~

**Comment by LeaYeh** [comment]
@PeterDaveHello

**Pull request merged**
