### PR TITLE
Add license of geo-location-javascript, cc #9248

### PR DESCRIPTION
**Pull request by lcd78706**
https://code.google.com/archive/p/geo-location-javascript/

### CODE REVIEW

**Comment by lcd78706** [comment]
Hello, @kennynaoh 
Please check the pull request.
Thanks!

**Comment by kennynaoh** [comment]
@lcd78706 
Please change the branch name to meaningful name, like `license-geo-location-javascript`, next time.
And you just only attach the link about the license in the comment next time.
Thanks!

**Comment by kennynaoh** [comment]
LGTM
@cdnjs/intern2

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
