### PR TITLE
[New] Add jquery.scrollex@0.2.1 w/ git auto-update

### LINKED ISSUE #9019: [Request] Add jquery.scrollex
jquery.scrollex
https://github.com/ajlkn/jquery.scrollex
MIT
https://github.com/ajlkn/jquery.scrollex

### PR DESCRIPTION
**Pull request by sashberd**
close #9019, cc @ajlkn

Pull request for issue: #9019
Related issue(s): # #11736

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/ajlkn/jquery.scrollex
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/jquery.scrollex
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 18
   - Count of stars: 165
   - Count of forks: 50
 * NPM download stats (optional):
   - Downloads in the last day: 2
   - Downloads in the last week: 34
   - Downloads in the last month: 105

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sashberd** [comment]
@PeterDaveHello @sufuf3 
Hey guys
I started to get this message on rebase
image

What should I do in order to fix it
Thanks

**Comment by PeterDaveHello** [comment]
@sashberd your disk space may not be enough, please copy the text instead of screenshot next time, which is more convenient to get help, thanks.

**Comment by sashberd** [comment]
@PeterDaveHello  I have 50 GB space left on disk. How much the rebase need?

**Comment by PeterDaveHello** [comment]
@sashberd hmmm, I think I was wrong, maybe is the memory, git rebase uses memory, and it says "stdout": no space left, that's what I guess. Try to close all other applications and try again?

**Comment by sashberd** [comment]
@PeterDaveHello
Same message after all programms were closed. It is not enought storage at hard disk. When rebase at work I see my disk  storage is going down to 2GB and then I get such message
How much storage it is taken?

**Comment by PeterDaveHello** [comment]
@sashberd hmmm ... that's strange, I don't remember that it'll use so much space ... interesting, I'll think about it.

**Comment by sashberd** [comment]
@sufuf3 
Hi, I used wget command as you did and donwload files with the same command to my PC and replace them with existed one in the folder.
FYR
@PeterDaveHello As for the storage folder it is happens on my second PC. I will try to reinstall git from scratch today.
Thanks

**Comment by sashberd** [comment]
@sufuf3 @maruilian11 OK, so I remove the existed branch and create a new one, then I used wget tool to get exact files from git repo v0.2.1. 
Lets see if now the files are OK.

**Pull request merged**
