### PR TITLE
Release F2 v1.4.0 [author]

### PR DESCRIPTION
**Pull request by markhealey**
Version update to 1.4.0.

Source: https://github.com/OpenF2/F2

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Is it possible to add auto-update config as #3638 said? Thanks.

**Comment by markhealey** [comment]
@PeterDaveHello yes, we'll look at the auto-update config.

The [site isn't reflecting `1.4.0`](https://cdnjs.com/libraries/f2), is there something else we need to do?

Thanks.

**Comment by markhealey** [comment]
1.4.0 is up now (I didn't do anything).

**Comment by PeterDaveHello** [comment]
Just wait a moment.

**Pull request merged**
