### PR TITLE
add wysihtml v0.5.1

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/Voog/wysihtml
**Watch 103
  Star 2,736
 Fork 212**
@Piicksarn could you help me check out the PR for #6065 ? thank you~
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by Piicksarn** [comment]
It's fine!
@PeterDaveHello, would you mind to have a look at the pr?
Thanks!

**Comment by maruilian11** [comment]
@Piicksarn because the PR is over a day, so i rebased it, could you help me check again?

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you please have a look at the pr?
thank you!

**Comment by PeterDaveHello** [comment]
I think we can change description to "Open source rich text editor for the modern web" which is easier to be understanded, I copied it from it GitHub page.

**Comment by maruilian11** [comment]
sorry, i don't really understand, change what description?

**Comment by PeterDaveHello** [comment]
Not so hard to understand.
https://github.com/maruilian11/cdnjs/blob/59eeee5e55f1c9ec73e625ad5cce502c2540fe90/ajax/libs/wysihtml/package.json#L8

**Comment by maruilian11** [comment]
ok, i see.

**Pull request merged**
