### PR TITLE
add node-uuid v1.4.7 with npm auto-update config

### LINKED ISSUE #7990: [Request] Add node-uuid
**Library name:** node-uuid
**Git repository url:** https://github.com/broofa/node-uuid
**npm package url(optional):** https://www.npmjs.com/package/node-uuid
**License(s):** MIT
**Official homepage:** https://broofa.github.io/node-uuid/
**Wanna say something? Leave message here:**
Even though node is in the name, it can run on web browsers.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #7990 
@dannyxx001 please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/broofa/node-uuid
 * Official website (optional, not the repository): https://broofa.github.io/node-uuid/
 * NPM package url (optional): https://www.npmjs.com/package/node-uuid
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 2,938
   - Count of watchers: 97
   - Count of forks: 257
 * NPM download stats (optional):
   - Downloads in the last day: 389,698
   - Downloads in the last week: 2,137,996
   - Downloads in the last month: 9,063,472

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7990, cc @broofa

### CODE REVIEW

**Comment by dannyxx001** [comment]
Why does a failed check appear?

**Comment by PeterDaveHello** [comment]
Ping.

**Comment by dannyxx001** [comment]
I think the PR is OK. @PeterDaveHello  Please help me review again.

**Comment by PeterDaveHello** [comment]
Doesn't this branch need to reabse with the latest master branch first?

**Comment by kennynaoh** [comment]
@dannyxx001 
I have rebased to the latest master branch.
Please help me review it again.
Thanks!

**Pull request merged**
