### PR TITLE
[new] add bootstrap-sweetalert@0.4.2

### PR DESCRIPTION
**Pull request by LeaYeh**
Hi @maruilian11  for #6127 

I add  bootstrap-sweetalert@0.4.2 and add npm auto-update config in its package.json.

repo url: https://github.com/lipis/bootstrap-sweetalert
npm package url: https://www.npmjs.com/package/bootstrap-sweetalert

Would you mind checking this PR for me? Thank you~ :-D

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : Watch 60, Star 1373, Fork 1532
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please minify the css file.

**Comment by LeaYeh** [comment]
@PeterDaveHello i minified sweet-alert.css and rebased it.

**Comment by PeterDaveHello** [comment]
Wrong auto-update config.

```sh
$ ls bootstrap-sweetalert/lib/
sweet-alert-animations.less  sweet-alert.css   sweet-alert.js    sweet-alert.min.js
sweet-alert-combine.less     sweet-alert.html  sweet-alert.less
```

**Comment by LeaYeh** [comment]
@PeterDaveHello i'm not really sure which files need to add, 
but by its readme i think we need 
`lib/*.js` `lib/*.css` `lib/*.less` 
`bootstrap/*.less`
`assets/*.(less|jpg|png)`
if you don't think so maybe i can opn an issue to ask author.

**Comment by PeterDaveHello** [comment]
@LeaYeh should not add .less, but it's good to discuss with its author

**Comment by lipis** [comment]
if the cdnjs is only for serving the static files.. then the less are not needed.. only the ones that are in main: https://github.com/lipis/bootstrap-sweetalert/blob/master/bower.json#L9-L13

**Pull request closed without merging**
