### PR TITLE
manually add old versions of jquery-sparklines

### PR DESCRIPTION
**Pull request by maruilian11**
since the [issue](https://github.com/gwatts/jquery.sparkline/issues/166#issuecomment-220640223) about add `jquery.sparkline.js` and `jquery.sparkline.min.js` in dist folder has been no response for a while, we can't set up auto-update config for this lib. https://github.com/cdnjs/cdnjs/issues/6098

i decided to add v1.2.1, v1.3, v1.4.3, v1.5.1, v1.6 manually from http://omnipotent.net/jquery.sparkline/#s-download.

@Amomo could you help me check this PR? thank you!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Don't you need to mention corresponding issue of cdnjs?

**Comment by maruilian11** [comment]
@PeterDaveHello sorry, i updated the comment, is that ok?

**Comment by PeterDaveHello** [comment]
And in the commit.

**Comment by maruilian11** [comment]
@PeterDaveHello is that ok?

**Comment by PeterDaveHello** [comment]
Should clarify your commit message, so hard to read and understand.

**Comment by maruilian11** [comment]
@PeterDaveHello is that better?

**Comment by PeterDaveHello** [comment]
Make a single sentence for these:
> v1.2.1, v1.3, v1.4.3, v1.5.1, v1.6
> no response from asking for adding built files in dist,
> so we can't set up auto-update config for #6098

**Comment by maruilian11** [comment]
@PeterDaveHello is that ok?

**Comment by maruilian11** [comment]
how about this time.

**Comment by PeterDaveHello** [comment]
Is this a sentence?

**Comment by maruilian11** [comment]
how about this time.

**Comment by PeterDaveHello** [comment]
Where is the versions been added in the commit message?

**Comment by maruilian11** [comment]
@PeterDaveHello is that ok?

**Comment by PeterDaveHello** [comment]
`v1.2.1, v1.3, v1.4.3, v1.5.1, v1.6 because we can't set up auto-update for #6098` This is not a sentence.

**Comment by maruilian11** [comment]
@PeterDaveHello how about this time?

**Comment by PeterDaveHello** [comment]
And the first line of the commit message, see PR title.

**Comment by maruilian11** [comment]
@PeterDaveHello i updated.

**Pull request merged**
