### PR TITLE
[new] add feature.js@1.0.0

### PR DESCRIPTION
**Pull request by iwdmb**
+ git repo url: https://github.com/viljamis/feature.js

Watch 68
Star 2,261
Fork 72

+ Issue: #6835 

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
missing `"filename": "feature.min.js"`

**Comment by iwdmb** [comment]
Please re-confirm.

thanks.

**Comment by PeterDaveHello** [comment]
There is a official npm package, please use npm auto-update next time as document recommended, thanks.
https://github.com/viljamis/feature.js#download

**Comment by maruilian11** [comment]
@iwdmb please close the issue when the commit is merged, you can close it in commit message.
thank you for your help.

**Pull request merged**
