### PR TITLE
correct the main file type of responsive-nav.js, close #5851

### LINKED ISSUE #5851: responsive-nav.js is serving css instead of js
screen shot 2015-10-08 at 1 04 49 pm

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/viljamis/responsive-nav.js
**Watch 218
  Star 3,451
 Fork 57**
@LeaYeh could u help me check this PR for #5851 ? thank you!
- [ ] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
bad commit message

**Comment by maruilian11** [comment]
@cdnjs/intern could you please suggest me some good example of this PR's commit message.
cc #5851

**Comment by Amomo** [comment]
Um...I suggest
"change the main file in filename field of responsive-nav.js"

Is it okay?😯

**Comment by maruilian11** [comment]
thank you~

**Pull request merged**
