### PR TITLE
Update mdbootstrap v4.3.0 files and auto-update config

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #10432 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/mdbootstrap/bootstrap-material-design
 * Official website (optional, not the repository): https://mdbootstrap.com/material-design-for-bootstrap/
 * NPM package url (optional): https://www.npmjs.com/package/mdbootstrap
 * License and its reference: [MIT](https://mdbootstrap.com/license/)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 47
   - Count of stars: 737
   - Count of forks: 137
 * NPM download stats (optional):
   - Downloads in the last day: 41
   - Downloads in the last week: 217
   - Downloads in the last month: 1232

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by extend1994** [comment]
@cdnjs/intern3 please help me review this pull request, thank you.

**Comment by extend1994** [comment]
@PeterDaveHello please help me review this pull request, thank you.

**Comment by PeterDaveHello** [comment]
Wrong PR title and commit message in https://github.com/cdnjs/cdnjs/pull/10714/commits/b6e30837a7b60d74698532a7524cedf7111ad788.

**Comment by extend1994** [comment]
@PeterDaveHello OK, thanks a lot.

**Pull request merged**
