### PR TITLE
Add license of jquery-jkit, cc #5500

### PR DESCRIPTION
**Pull request by jj528s35**
https://github.com/FrediBach/jQuery-jKit/blob/master/license.txt

@pvnr0082t

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@jj528s35 You should tag me after CI test finished and you need to say something like "Please help me review this pull request, thank you" or no one knows what you want to do.

**Comment by pvnr0082t** [comment]
@jj528s35 https://github.com/FrediBach/jQuery-jKit/blob/master/license.txt is not easy to tell it's `MIT`. You can also paste http://jquery-jkit.com/ or https://github.com/FrediBach/jQuery-jKit/blob/1.1.21/jkit.jquery.json#L17 as reference.

**Comment by pvnr0082t** [comment]
Because @jj528s35 quit, I'll take over it.

**Comment by pvnr0082t** [comment]
LGTM
@cdnjs/intern2 Please help me review this PR, thank you.

**Comment by kennynaoh** [comment]
LGTM

**Pull request merged**
