### PR TITLE
add seamless-immutable@6.1.1 w/ npm auto-update

### LINKED ISSUE #8545: [Request] seamless-immutable
**Library name: seamless-immutable** 
**Git repository url: https://github.com/rtfeldman/seamless-immutable**
**npm package url(optional):** 
**License(s): https://github.com/rtfeldman/seamless-immutable/blob/master/LICENSE**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by x09326**
PR for #8545 
@kennynaoh please help me review it, thanks.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/rtfeldman/seamless-immutable
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars:1987
   - Count of watchers:34
   - Count of forks:71
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8545, cc @rtfeldman

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@x09326 any reason to use git auto-update instead of npm? Especially there are pre-built dist files in the npm package.

**Comment by rtfeldman** [comment]
I'm the author and love this idea! 😻

**Comment by x09326** [comment]
@kennynaoh 
I change git auto-update to npm auto-update.
Please help me review it, thanks.

**Comment by PeterDaveHello** [comment]
Wrong auto-update config.

**Comment by x09326** [comment]
@PeterDaveHello 
I couldn't get you.
What's wrong?

**Comment by PeterDaveHello** [comment]
@x09326 Why to use `src` as base path?

**Comment by x09326** [comment]
@kennynaoh 
I remove the basepath.
Please help me review it again, thanks.

**Comment by PeterDaveHello** [comment]
@x09326 `src` should not be in the filename, what's the reason why to get files from `src` folder? There are `seamless-immutable.development.js`,  `seamless-immutable.development.min.js` and `seamless-immutable.production.min.js` under the root of the npm package, can't we use it? When I am asking you the reason why, it's not a good idea you just modify or change something, but better figure out the reason first, and we can discuss about the solution we are going to use.

**Comment by x09326** [comment]
@PeterDaveHello 
Because of I think the js files named development.
So I think the files shouldn't be added.

I will confirm this with the author.

**Comment by PeterDaveHello** [comment]
@x09326 But there is also filename with production, that may be useful.

**Comment by PeterDaveHello** [comment]
@x09326 The development file may just for easier debugging usage, have you checked any docs of this lib?

**Comment by rtfeldman** [comment]
Yeah, both development and prod builds should be on there.

The dev build does additional checks and throws errors for more cases, whereas the prod build is designed for maximum speed and doesn't do these checks.

Some people use the dev build in production because they don't care about the performance difference, so it would definitely make sense to have both builds available via CDN.

**Comment by PeterDaveHello** [comment]
@rtfeldman Thanks.

**Pull request merged**
