### PR TITLE
[new] Add socketcluster-client v2.3.7 with git auto-update, close #5173

### LINKED ISSUE #5173: [Request] Add socketcluster
**Library name:**  
socketcluster-client

**Git repository url:** 
https://github.com/SocketCluster/socketcluster-client

**npm package url(optional):** 
https://libraries.io/npm/socketcluster-client-ws

**Official homepage:**
socketcluster.io

**Wanna say something? Leave message here:**
I love socketcluster and I thought it would be nice to be able to use a CDN instead of having to include the file(s) in my public directory. Thanks!!

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by Piicksarn**
@Amomo, would you please checkout the pr for me:)
Although the library doesn't have enough stars in git, but it had demonstrated some reason which show the detail in [#5173](https://github.com/cdnjs/cdnjs/issues/5173#issuecomment-129256821).
Thank you!

### CODE REVIEW

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine. Could you take a look? Thank you! :-D

**Comment by PeterDaveHello** [comment]
Let's add some keywords.

**Comment by Piicksarn** [comment]
@Amomo I added some keywords to the library, and need your help for check it again!
Thank you!

**Comment by Amomo** [comment]
@PeterDaveHello I think it is fine~
Could you take a look? Thank you!

**Pull request merged**
