### PR TITLE
add angularjs-nvd3-directives v0.0.8

### PR DESCRIPTION
**Pull request by maruilian11**
@Amomo could you help me check this PR? thank you!
since angularjs-nvd3-directives doesn't have tags for every version, 
i add 
v0.0.8 manually 
https://github.com/angularjs-nvd3-directives/angularjs-nvd3-directives/commit/20c113927dafbf440d5d673b3148b4898cd79567

https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/angularjs-nvd3-directives

### CODE REVIEW

**Comment by Amomo** [comment]
@maruilian11 sorry for late.
I think this PR is ok, could you rebase it on our latest master branch?
Thank you!

**Comment by maruilian11** [comment]
@Amomo it's ok :smiley:  i have updated it.

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is ok.
Could you check it again? Thank you!

**Comment by PeterDaveHello** [comment]
What's the reason why that you didn't update its version in package.json?

**Comment by maruilian11** [comment]
i forgot i add the latest version, i will pay more attention on it.

**Pull request merged**
