### PR TITLE
[new] [author] Jsy

### PR DESCRIPTION
**Pull request by labidiaymen**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Should read the document first please.

**Comment by Piicksarn** [comment]
ping @cdnjs/intern @cdnjs/intern2

**Comment by maruilian11** [comment]
@labidiaymen please squash the commits to one commit, and not use array when there is only one repository.
the PR will be close if there is no any response in next 7 days.

**Comment by PeterDaveHello** [comment]
It's a very old and invalid PR, I'll close this now, if there is any update, we could reopen it.

**Pull request closed without merging**
