### PR TITLE
Update equalize.js license and add author info

### PR DESCRIPTION
**Pull request by programmiri**
Pull request for issue: #11931

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Squashing into only one commit now.

**Comment by maruilian11** [comment]
@programmiri Actually we prefer to use [SPDX ID](https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json) now, would you please modify the `GPLv2` to `GPL-2.0`, rather than modify `MIT` part? Thank you.

**Comment by programmiri** [comment]
Hi @maruilian11 I hope I did understand you right & updated the right parts. The author of the package writes "Dual MIT & GPLv2 license" as license and I read up how to specify multiple licenses. 

The CI tests are failing because my branch is too old. I have to clone the repo on my local machine because I can't rebase online. May take a moment.

**Comment by maruilian11** [comment]
@programmiri The error msg says
```
==========ERROR==========
The branch equalize.js for this pull request is a little bit old, please rebase this branch with the latest master branch from upstream!
==========ERROR==========
```
Could you please try to rebase with the master branch?
You can do it by using `git rebase master` on equalize.js branch
Note: you need to make sure your master branch is latest.
you can checkout to master branch and pull the latest master,
and checkout back to equalize.js branch to use `git rebase master`,
then git push. I think the error will be gone. :smiley:

**Comment by PeterDaveHello** [comment]
Never mind about the rebasing, I'll do it now.

**Comment by programmiri** [comment]
@PeterDaveHello Thanks a lot! I really appreciate the feedback of all members here, it helps me - as a newbie - a lot! I'll clone the repo anyway so all will go easier next time.

**Comment by PeterDaveHello** [comment]
@programmiri nice, don't forget to enable sparseCheckout please, or it'll take your time and disk space, not kidding 😏

**Comment by sufuf3** [comment]
@maruilian11 @extend1994 @pvnr0082t @qwe19272375 @hare1039 
Please help review this PR, Thank you.

**Comment by maruilian11** [comment]
Helped make a little modification. `Update license & add author info in the package.json` ---> `Update equalize.js license & add author info `

**Pull request merged**
