### PR TITLE
add jquery.mb.bgndgallery v1.9.1

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/pupunzi/jquery.mb.bgndGallery
**Watch 6
  Star 39
 Fork 10**
@Amomo could u help me check this PR for #6952  ? thank you!
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [ ] Notable popularity cc https://github.com/cdnjs/cdnjs/issues/6952#issuecomment-182239465
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update) 
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by maruilian11** [comment]
@Amomo thank you, i have corrected it, could you help me check it again?

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine, could you take a look? Thank you!

**Comment by PeterDaveHello** [comment]
Hi @pupunzi, I saw there is a `dist` folder in git repository on GitHub, is it possible to use it in its npm package? Thanks!

**Comment by PeterDaveHello** [comment]
What's going on here?

**Comment by maruilian11** [comment]
@PeterDaveHello sorry for closing the PR carelessly!
new PR is here https://github.com/cdnjs/cdnjs/pull/7103

**Pull request closed without merging**
