### PR TITLE
add keypress v2.1.3 with git autoupdate, close #5319

### LINKED ISSUE #5319: [Request] Add dmauro/Keypress
**Library name:** dmauro/Keypress/
**Git repository url:** https://github.com/dmauro/Keypress/
**npm package url(optional):** 
**Official homepage:** http://dmauro.github.io/Keypress/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by maruilian11**
@Amomo could u plz help me check this PR for #5319? thanks a lot!
**git repo url:** https://github.com/dmauro/Keypress/
**Watch 124
  Star 2,618
 Fork 254**
* [x] Not found on cdnjs repo
* [x] No already exist issue and PR
* [x] Notable popularity
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)
* [x] Has valid tags for each versions (for git auto-update)
* [x] Auto-update setup
* [x] Auto-update target/source is valid.
* [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by Amomo** [comment]
@maruilian11 could you add more info about its repository?

**Comment by maruilian11** [comment]
@Amomo  i have added the info, could u help me check it again? thank you:)

**Comment by Amomo** [comment]
@maruilian11 sorry I didn't check it out last time.
`Filenames should not include a version number.`
Would you mind to open an issue to told the author not to note version number on minified file?
Thank you!

**Comment by maruilian11** [comment]
@Amomo i think if they don't response the issue in 10 days, how about we don't use their min file? just like other case without min file. i want to add lib on cdnjs.com asap, what do you think?

**Comment by maruilian11** [comment]
@Amomo i have asked PeterDaveHello, and he said these two way is available, so i chose minify it ourselves. i have rebase it, could u help me check it again? thanks.

**Comment by Amomo** [comment]
Ok, thank you. 😀
@PeterDaveHello I think this PR is fine, could you take a look? Thanks~

**Pull request merged**
