### PR TITLE
[new] exificient.js library

### PR DESCRIPTION
**Pull request by danielpeintner**
Implements EXI (http://www.w3.org/TR/exi/) format specificatopn

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please show us its repository info and use only one commit to add a lib.

**Comment by danielpeintner** [comment]
Repository can be found here: https://github.com/EXIficient/exificient.js

**Comment by PeterDaveHello** [comment]
We need a higher popularity to add this lib on cdn.

**Comment by danielpeintner** [comment]
May I ask what do you mean by "popularity"? How do you measure popularity?

The library is fairly new ...

**Comment by PeterDaveHello** [comment]
@danielpeintner our readme document give you an example like 100 star on GitHub, both GitHub or npm can show popularity of a lib.

**Comment by Piicksarn** [comment]
@danielpeintner, would you please send a PR again after the lib reach to enough popularity?
And we would close the pr after 10 days for no response.

Thanks for your great work and contribution :smiley: 
Piicksarn

**Comment by danielpeintner** [comment]
Thanks. Will do so..

**Pull request closed without merging**
