### PR TITLE
Add license of jquery-te, cc #5500

### PR DESCRIPTION
**Pull request by sufuf3**
https://github.com/fattihkoca/jQuery-TE/blob/master/jQuery-TE_v.1.3.2/GPL-LICENSE.txt

### CODE REVIEW

**Comment by sufuf3** [comment]
@pvnr0082t  Please help me review this pull request, thank you.

**Comment by sufuf3** [comment]
I discuss with author here: http://disq.us/p/1e1pnlr 
Because it can't create an issue at https://github.com/fattihkoca/jQuery-TE

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello I can't contact the author by many ways (twitter, http://disq.us/p/1e1pnlr ), since I can't create an issue to GitHub repo of this lib. 
I can't confirm which license of this lib should add? 
`MIT`: http://jqueryte.com/license#the_mit_license
or 
`GPL-2.0`: https://github.com/fattihkoca/jQuery-TE/blob/master/jQuery-TE_v.1.3.2/GPL-LICENSE.txt

**Comment by PeterDaveHello** [comment]
@maruilian11 @pvnr0082t would you please help here?

**Comment by pvnr0082t** [comment]
`GPL-2.0` is for v1.3.2. `MIT` is for the latest version. I think we should use MIT here. How do you think? @sufuf3

**Comment by sufuf3** [comment]
@pvnr0082t I modified to MIT license, please help me review this PR, thanks.

**Pull request merged**
