### PR TITLE
Add license of prettyCheckable, cc #5500

### PR DESCRIPTION
**Pull request by hare1039**
Add license of prettyCheckable.
ref: http://arthurgouveia.com/prettyCheckable/
The license link is located at the bottom right of the page.

### CODE REVIEW

**Comment by hare1039** [comment]
@kennynaoh Please review my work. Thanks.

**Comment by PeterDaveHello** [comment]
The reference should be as clear as possible like: https://github.com/arthurgouveia/prettyCheckable/blob/d3413af6b311cdefae8e3e9415660b4341d58dd6/dev/prettyCheckable.js#L5

**Comment by hare1039** [comment]
@PeterDaveHello Okey, I'll search the repository more carefully next time.

**Comment by PeterDaveHello** [comment]
@hare1039 Great

**Pull request merged**
