### PR TITLE
Add semantic-ui-react@0.58.3 w/ npm-autoupdate.

### LINKED ISSUE #9349: [Request] Add Semantic-UI-React
**Library name:** Semantic-UI-React
**Git repository url:**https://github.com/Semantic-Org/Semantic-UI-React
**npm package url(optional):** https://www.npmjs.com/package/semantic-ui-react 
**License(s):** https://github.com/Semantic-Org/Semantic-UI-React/blob/master/LICENSE.md
**Official homepage:** http://react.semantic-ui.com/introduction
**Wanna say something? Leave message here:**
# Thank you 👍 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by Piicksarn**
@cdnjs/intern, @cdnjs/intern2
It's for https://github.com/cdnjs/cdnjs/issues/9349
Please help me review this pull request, thank you!

----
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/Semantic-Org/Semantic-UI-React
 * Official website (optional, not the repository): http://react.semantic-ui.com
 * NPM package url (optional): https://www.npmjs.com/package/semantic-ui-react
 * GitHub / Bitbucket popularity (required):
   - Count of stars: **1037**
   - Count of watchers: **80**
   - Count of forks: **100**
 * NPM download stats (optional):
   - Downloads in the last day: **211**
   - Downloads in the last week: **2119**
   - Downloads in the last month: **7962**

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
Where did you get the file? Is not the same as what I got from npm ...

**Comment by Piicksarn** [comment]
@PeterDaveHello,
I'm terribly sorry about that. I get the file by npm install as well.
However, I did not checkout the file content which i installed few days ago.
I learn a lesson and would be much more careful next time.
Sorry & Thanks!

**Comment by PeterDaveHello** [comment]
@Piicksarn I am not sure if you did fetch from npm, you should find out what you got exactly, the published version on npm can't be removed, so if you did fetch it from npm, there must still be there, maybe from the other versions, you should confirm that and tell us what's the problem here.

**Comment by Piicksarn** [comment]
✨ @levithomason, sure!
Thanks for your advice!! 😃

**Comment by PeterDaveHello** [comment]
Thanks @levithomason, we'll fix that.

**Pull request merged**
