### PR TITLE
Create package.json

### PR DESCRIPTION
**Pull request by mar10**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/mar10/persisto
- Official website (optional, not the repository):
- NPM package url (optional): https://www.npmjs.com/package/persisto
- GitHub / Bitbucket popularity (required):
  - Count of stars: 1
  - Count of watchers: 1
  - Count of forks:
- NPM download stats (optional):
  - Downloads in the last day:
  - Downloads in the last week:
  - Downloads in the last month: 15
# Essential checklist
- [X] I'm the author of this library
  - [X] I would like to add link to the page of this library on CDNJS on website / readme
- [X] This lib was not found on cdnjs repo
- [ ] No already exist / duplicated issue and PR
- [ ] The lib has notable popularity
  - [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [X] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [ ] Has valid tags for each versions (for git auto-update)
- [ ] Auto-update setup
- [ ] Auto-update target/source is valid.
- [ ] Auto-update filemap is correct.
# Git commit checklist
- [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [ ] The parent of the commit(s) in the PR is not old than 3 days.
- [ ] Pull request is sending from a non-master branch with meaningful name.
- [ ] Separate unrelated changes into different commits.
- [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [ ] Close corresponding issue in commit message
- [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
Hi @mar10 ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Thank you. 

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by mar10** [comment]
No updates sorry, and it's unlikely that we get lots of stars in the near future for this side project.
If this is a stopper for cdnjs, I am happy with jsDelivr ;)

**Comment by maruilian11** [comment]
@PeterDaveHello Do we need to close this PR first due to the less popularity? I'm afraid PeterBot will keep asking, but the popular won't grow up in short time.

**Comment by PeterDaveHello** [comment]
Close due to no response & not enough popularity

**Comment by PeterDaveHello** [comment]
@mar10 I think you can also try https://rawgit.com/ 😄 , sorry for the inconvenience caused.

**Comment by mar10** [comment]
@PeterDaveHello no problem, I already use cdnjs for two other projects of mine. Persisto is only a small side project.

**Comment by PeterDaveHello** [comment]
@mar10 Thanks for understanding, very appreciated.

**Pull request closed without merging**
