### PR TITLE
add notie v2.1.0 

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/jaredreich/notie.js
**Watch 122
  Star 3,950
 Fork 186**
@Piicksarn could u help me check this PR for #6264 ? thank you!
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [ ] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by timwis** [comment]
Hi @maruilian11, any reason you didn't include [notie.css](https://github.com/jaredreich/notie/blob/master/dist/notie.css)? Looks to be required for use.

**Comment by maruilian11** [comment]
@timwis thanks! i will add it later.

**Comment by PeterDaveHello** [comment]
@timwis there is no css file in notie v2.1.0, that's the reason why, css and dist come from v3.0.0, anyway, I'll take care about this issue.

**Comment by timwis** [comment]
Thanks guys!

**Pull request merged**
