### PR TITLE
[new] Added gh.js@1.1.0

### PR DESCRIPTION
**Pull request by IonicaBizau**
Here's my new little thing: https://github.com/IonicaBizau/gh.js :dizzy: 

@PeterDaveHello I wanted to ask you *how to review pull requests on cdnjs*? Maybe we should create a repository where to detail how to do things inside of the team (e.g. reviewing the PRs).

Also, is it fine that I created this branch in cdnjs repo?

Thanks! :four_leaf_clover:

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I think we are just going to make sure that PR follow CONTRIBUTING.md and README.md

**Comment by PeterDaveHello** [comment]
Personally, I won't put individual branch for libs hosting on this repo.

**Comment by IonicaBizau** [comment]
@PeterDaveHello I opened #4676 and I would like to merge this branch. Can you please take a look and check if everything is fine? Thanks!

**Comment by PeterDaveHello** [comment]
Looks okay, though we usually accept libs with more population.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Will keep that in mind! However, let's suppose that `gh.js` will get popular. :smile:

**Comment by PeterDaveHello** [comment]
You can merge it by yourself.

**Pull request merged**
