### PR TITLE
Add treant-js@1.0 w/ git auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
Pull request for issue: #9365 !
@Piicksarn @cdnjs/intern2 could you help me review this PR? Thank you!
`css` file is not big enough to generate a min file.

# Profile of the lib
 * Git repository (required): https://github.com/fperucic/treant-js
 * Official website (optional, not the repository): https://fperucic.github.io/treant-js/
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required): 
   Watch 8
   Star 103
   Fork 44
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
LGTM

**Comment by maruilian11** [comment]
@x09326 if lines in files less than 15, it don't need to be minified.

**Comment by kennynaoh** [comment]
@maruilian11 Please rebase to the latest master branch, thanks!

**Comment by maruilian11** [comment]
@kennynaoh I rebase the branch with the latest master branch. Thanks!

**Comment by kennynaoh** [comment]
LGTM

**Comment by maruilian11** [comment]
@x09326 I rebase the branch with the latest master branch, could you help me check this PR? Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM

**Pull request merged**
