### PR TITLE
Add pagePiling.js with git auto-update

### LINKED ISSUE #10138: [Request] Add Page Pilling
**Library name:** Page Pilling
**Git repository url:**https://github.com/alvarotrigo/pagePiling.js#pagepilingjs
**npm package url(optional):** 
**License(s):**(The MIT License)
**Official homepage:**https://github.com/alvarotrigo/pagePiling.js#pagepilingjs
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by clairetsai818**
close #10138, cc @alvarotrigo

Pull request for issue: #10138 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/alvarotrigo/pagePiling.js
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 2797 
   - Count of watchers: 134
   - Count of forks: 490

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by clairetsai818** [comment]
@PeterDaveHello Please help me review this, thanks.

**Comment by alvarotrigo** [comment]
Thanks for that ;)

**Comment by alvarotrigo** [comment]
@PeterDaveHello yeap, in the `dist` folder: https://github.com/alvarotrigo/pagePiling.js/tree/master/dist

**Comment by PeterDaveHello** [comment]
@alvarotrigo Since we pull files from tagged version (e.g. https://github.com/alvarotrigo/pagePiling.js/tree/1.5.3/), the css file need to be manually minified in the commit.

**Comment by alvarotrigo** [comment]
@PeterDaveHello solved. Created a new release: https://github.com/alvarotrigo/pagePiling.js/tree/1.5.4

**Comment by clairetsai818** [comment]
@PeterDaveHello This library has been updated to the latest version, please help me review this. Thanks.

**Comment by clairetsai818** [comment]
@PeterDaveHello This library has been updated to the latest version, please help me review this. Thanks.

**Comment by PeterDaveHello** [comment]
Commit message of both commits are wrong. For the correct one, you can also refer to #10239

**Comment by clairetsai818** [comment]
@PeterDaveHello I've corrected commit messages. Please help me review this, thanks.

**Comment by clairetsai818** [comment]
@PeterDaveHello I've corrected the commit message, please help me review this. Thanks.

**Pull request merged**
