### PR TITLE
Add font-awesome@5.7.1 w/ npm auto-update & package.json update

### PR DESCRIPTION
**Pull request by sufuf3**
Pull request for issue: #12307 
Related issue(s): #12843

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/FortAwesome/Font-Awesome
 * Official website (optional, not the repository): https://fontawesome.com/
 * NPM package url (optional): [@fortawesome/fontawesome-free](https://www.npmjs.com/package/@fortawesome/fontawesome-free) according to https://fontawesome.com/how-to-use/on-the-web/setup/getting-started
 * License and its reference: ["OFL-1.1", "MIT", "CC-BY-4.0"](https://github.com/FortAwesome/Font-Awesome/tree/5.0.6#license)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 1362
   - Count of stars: 54854
   - Count of forks: 9507
 * NPM download stats (optional):
   - Downloads in the last day: 17023
   - Downloads in the last week: 60246
   - Downloads in the last month: 316315
Ref: https://npm-stat.com/charts.html?package=%40fortawesome%2Ffontawesome-free&from=2018-08-20&to=2018-09-20

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
1. The file structure is changed. I referred to Get-started: https://fontawesome.com/get-started/svg-with-js & https://fontawesome.com/get-started/web-fonts-with-css to add them.
2. ajax/libs/font-awesome/5.0.6/web-fonts-with-css/css/fontawesome-all.min.css is the same with 
 https://use.fontawesome.com/releases/v5.0.6/css/all.css

Memo: There is no files is the same with md5 checksum of  https://use.fontawesome.com/releases/v5.0.6/js/all.js (44f077b456f3decb0d1b00769927c002). I'll open an issue to upstream.

**Comment by sufuf3** [comment]
This PR can get v5.1.0 ~ v5.3.1 automatically.
v5.0.6 - v5.0.13 need to be added manually.
I will add old versions (v5.0.6 - v5.0.13) by another PR.
Because there are some people hope this lib can be updated ASAP.
@extend1994 Would you please help me review this PR?
Many thanks.

**Comment by andrewheberle** [comment]
Looking at the docs, loading SVG sprites from a different origin doesn't work, so having them served from a CDN is not really useful (assuming I am reading the docs correctly).

I'd just like to see the JS/SVG stuff (ie "js/all.js", "js/solid.js", "js/regular.js", "js/brands.js" and "js/fontawesome.js") and the CSS stuff (ie "css/all.css", "css/solid.css", "css/regular.css", "css/brands.css" and "css/fontawesome.css") on CDNJS as soon as possible.

**Comment by sufuf3** [comment]
Let's waiting for response. FortAwesome/Font-Awesome#12323

**Comment by andrewheberle** [comment]
Is the question about having the SVG sprites included on CDNJS still holding this up?

The Font Awesome docs for SVG sprites says that if you use a URL when referencing the SVG sprite it must be loaded from the same domain so having these files served from a CDN is not an option without assuming people are going to hack together a proxy to serve the assets locally from the CDN.

From the docs (https://fontawesome.com/how-to-use/on-the-web/advanced/svg-sprites):

> If you use URLs in the `xlink:href` they need to be loaded from the same domain. There is cross-origin protection on SVGs loaded this way. Some people just serve it directly from their static assets. You can also use a proxy.

**Comment by ExE-Boss** [comment]
@andrewheberle MDN seems to suggest that [that only applies to Internet Explorer](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use#Browser_compatibility).

**Comment by andrewheberle** [comment]
@ExE-Boss It looks like that issue is covered separately in the Font Awesome docs for SVG Sprites:

> **Internet Explorer doesn't load remote SVGs**
> If you use a URL in the `xlink:href` IE will not automatically download the file for you. Checkout this project if this is something you need.

I'm referring to the second issue/caveat noted in those docs that browsers enforce cross-origin protection for URL's in the `<use>` tag, so it would seem to indicate that SVG sprites served from CDNJS would be unusable anyway.

**Comment by MattIPv4** [comment]
@sufuf3 Any updates regarding this (I am wanting to use 5.x on the cdnjs website 😉)?

**Comment by sufuf3** [comment]
@MattIPv4 I am waiting for the reply from https://github.com/FortAwesome/Font-Awesome/issues/12323#issuecomment-425634809
Because according to https://fontawesome.com/how-to-use/on-the-web/setup/getting-started, I didn't add the SVG files.

However,  @extend1994 who is a reviewer wonder to know that why or why not to grab the SVG files. (https://github.com/cdnjs/cdnjs/pull/12517#pullrequestreview-159718443)

So, we all are waiting for the answer.

Thank you.

PS. IMO, I think developers can use these files well without SVG files on CDNJS.

**Comment by MattIPv4** [comment]
@sufuf3 Looking at what FA, I think it would be best to serve the svgs from cdnjs. They only total to 5.8M so not a huge use of space.

Part of the FA lib now is the raw svg files which developers are welcome to access and use from what I understand, so IMO including them is the best way forward.

**Comment by Sh4rK** [comment]
Hi, I would like to use fa from cdnjs as well. I think the best option is to merge _something_ (with or without the svgs, doesn't really matter) as soon as possible, so people can start using the webfont version at least. It can always be updated later, if you get an answer from FontAwesome.

**Comment by MattIPv4** [comment]
cc https://github.com/cdnjs/new-website/issues/260

**Comment by sufuf3** [comment]
Sorry for the late reply.
I've been so busy lately.
As @MattIPv4 and @extend1994 said, I'll add `sprites` and `svgs` soon.
Now, I am preparing the project of my boss, after that, I'll do this PR ASAP.
I'm awfully sorry.

**Comment by sufuf3** [comment]
@PeterDaveHello @extend1994 I apologize for the delay in fixing this PR.
I updated the PR, please help me review this.
Thank you.
Happy Chinese New Year!

**Comment by MattIPv4** [comment]
@PeterDaveHello Any update regarding this being merged? We have quite a few users still waiting on this as it is a very popular library and this version has been available through other methods for some time now 😊

**Comment by PeterDaveHello** [comment]
Here we go :tada: https://cdnjs.com/libraries/font-awesome/5.7.1

**Comment by olafcm** [comment]
The latest version of Font Awesome v5.9.0 was published 7 days ago (https://www.npmjs.com/package/@fortawesome/fontawesome-free/v/5.9.0) but does not show up on cdnjs (https://cdnjs.com/libraries/font-awesome/5.9.0) unfortunately.
Can this be fixed please?
Thank you :-)

**Comment by MattIPv4** [comment]
@PeterDaveHello Could you look into this asap, its a very popular lib?

**Comment by PeterDaveHello** [comment]
Sorry for the delay, looks like it's added already: https://github.com/cdnjs/cdnjs/commits/master/ajax/libs/font-awesome

**Pull request merged**
