### PR TITLE
[new] add pubsub-js@1.5.2 with git auto-update, close #5001

### LINKED ISSUE #5001: [Request] Add pubsub.js
https://github.com/mroderick/PubSubJS

### LINKED ISSUE #5004: [Request] HintCSS
http://kushagragour.in/lab/hint/

### PR DESCRIPTION
**Pull request by Amomo**
Hi @LeaYeh , I add a new lib with git auto-update from the request #5001
This lib is lack of minimized, so I attach on minified file.
Would you mind checking this PR for me? Thank you~ :-)

### CODE REVIEW

**Comment by LeaYeh** [comment]
maybe we couldn't absolutely assume that we need all files in src/

**Comment by PeterDaveHello** [comment]
Any updates?

**Comment by Amomo** [comment]
@LeaYeh Thanks for your reminder. I have modified it.
Could you check this PR again? Thank you~ :-)

**Comment by LeaYeh** [comment]
i think it is fine.

**Comment by Amomo** [comment]
@LeaYeh I have rebased it to latest master branch.
If it is ok, could you ping peter for me? Thank you! :-D

**Comment by LeaYeh** [comment]
sorry for late, plz rebase it again ><"

**Comment by Amomo** [comment]
@LeaYeh I have rebased it ~
Could you check it again? Thank you~ :-)

**Comment by LeaYeh** [comment]
fine! @PeterDaveHello

**Pull request merged**
