### PR TITLE
Update cryptico library license property in package.json

### PR DESCRIPTION
**Pull request by sashberd**
cc #5500
According to:
https://github.com/wwwtyro/cryptico/issues/11#issuecomment-51131177

Pull request for issue: #5500
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.
# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
 * [x] The parent of the commit(s) in the PR is not older than 3 days.
 * [x] Pull request is sent from a non-master branch with a meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sashberd** [comment]
@PeterDaveHello You are right. I updated the license
Also please help me to finish #11847. Thanks

**Comment by sashberd** [comment]
The reference in the PR description is not enough?

**Comment by PeterDaveHello** [comment]
@sashberd I didn't see any trivial point, not sure if I missed it.
@cdnjs/maintainer would you like to take a look? Thanks.

**Comment by extend1994** [comment]
https://github.com/wwwtyro/cryptico/issues/11#issuecomment-51131177 is a wrong response as https://github.com/wwwtyro/cryptico/issues/11#issuecomment-51131338 said. I guess it's The Unlicense because other repositories take this kind of license in his other work.

**Comment by sashberd** [comment]
@PeterDaveHello @extend1994 Should I use Unlicense in config?

**Comment by sashberd** [comment]
@xtuc @MattIPv4 Should we continue to update libs licences like we did in the past?

**Comment by xtuc** [comment]
@sashberd I don't feel strongly about changing or not licences but I'm not a lawyer.

**Pull request merged**
