### PR TITLE
Add expr-eval@0.12.0 w/ npm auto-update

### LINKED ISSUE #9741: [Request] Add expr-eval
**Library name:** expr-eval
**Git repository url:** https://github.com/silentmatt/expr-eval
**npm package url(optional):** https://www.npmjs.com/package/expr-eval
**License(s):** MIT
**Official homepage:** https://silentmatt.com/javascript-expression-evaluator/

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #9741

Add v0.12.0 instead of latest v1.0.0-rc3 because it is not an official version

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/silentmatt/expr-eval
 * Official website (optional, not the repository): https://silentmatt.com/javascript-expression-evaluator/
 * NPM package url (optional): https://www.npmjs.com/package/expr-eval
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 235
   - Count of watchers: 21
   - Count of forks: 102
 * NPM download stats (optional):
   - Downloads in the last day: 30
   - Downloads in the last week: 145
   - Downloads in the last month: 598

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9741, cc @silentmatt @johndoefromhere

### CODE REVIEW

**Comment by extend1994** [comment]
@PeterDaveHello please help me review this pull request, thank you.

**Comment by extend1994** [comment]
@PeterDaveHello I added the `homepage` info in package.json, plese help me review it, thank you.

**Comment by PeterDaveHello** [comment]
> Add v0.12.0 instead of latest v1.0.0-rc3 because it is not an official version

v1.0.0-rc3 is just not a stable version, it doesn't mean to be not official.

**Comment by extend1994** [comment]
Okay, I get it!

**Pull request merged**
