### PR TITLE
Add validate-js w/ npm auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
@cdnjs/intern2 Please help me review this PR, thanks!

Pull request for issue: #10477
Related issue(s): # #

# Profile of the lib
 * Git repository (required): https://github.com/rickharrison/validate.js
 * Official website (optional, not the repository): https://rickharrison.github.io/validate.js
 * NPM package url (optional): https://www.npmjs.com/package/validate-js
 * License and its reference: MIT, https://github.com/rickharrison/validate.js/blob/master/LICENSE
 * GitHub / Bitbucket popularity (required):
   Watch 72
   Star 2,006
   Fork 369
 * NPM download stats (optional):
   92 downloads in the last day
   395 downloads in the last week
   1,049 downloads in the last month
# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by maruilian11** [comment]
I add 1.0.0 ~ 1.4 with git auto-update bot.

**Comment by maruilian11** [comment]
@pvnr0082t I mentioned the source of old versions in commit msg. thanks!

**Comment by maruilian11** [comment]
@kennynaoh could you please help me review this PR, thanks.

**Comment by kennynaoh** [comment]
Sorry for late response. I think this PR is ok. Please rebase to the latest master branch. Thanks!

**Comment by maruilian11** [comment]
@kennynaoh I just rebased this branch with our latest master, thanks!

**Comment by PeterDaveHello** [comment]
You should wrap the commit message. 
 
Ref: 
https://git-scm.com/book/ch5-2.html 
``` 
Short (50 chars or less) summary of changes 
 
More detailed explanatory text, if necessary.  Wrap it to 
about 72 characters or so.  In some contexts, the first 
line is treated as the subject of an email and the rest of 
the text as the body.  The blank line separating the 
summary from the body is critical (unless you omit the body 
entirely); tools like rebase can get confused if you run 
the two together. 
 
Further paragraphs come after blank lines. 
 
  - Bullet points are okay, too 
 
  - Typically a hyphen or asterisk is used for the bullet, 
    preceded by a single space, with blank lines in 
    between, but conventions vary here 
```

**Comment by maruilian11** [comment]
@PeterDaveHello may I ask the reason to wrap it? Is commit msg too long?

**Comment by PeterDaveHello** [comment]
The quote already tell you the rule of 72 chars.

**Comment by maruilian11** [comment]
@PeterDaveHello Do you mean I should remove the body, like this:

--->Manually add validate-js old versions 1.0.0 ~ 1.4 from git tags

       cc #10477

But I think it's hard to mention the source and explain the reason why we get them from git repo in 72 chars.

**Comment by PeterDaveHello** [comment]
> These versions are from git repo tags because they aren't found in npm package.

**Comment by maruilian11** [comment]
@cdnjs/intern2 I just wrap the commit message, please help me review this PR again, thanks!

**Pull request merged**
