### PR TITLE
add jquery-chained v1.0.0 with autoupdate config

### LINKED ISSUE #7634: [Request] Add Chained
**Library name:** jquery_chained
**Git repository url:** https://github.com/tuupola/jquery_chained
**npm package url(optional):** https://www.npmjs.com/package/jquery-chained
**License(s):** MIT
**Official homepage:** http://www.appelsiini.net/projects/chained
**Wanna say something? Leave message here:** Thanks

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by dannyxx001**
PR for #7634 
@pvnr0082t please help me review this PR, thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/tuupola/jquery_chained
 * Official website (optional, not the repository): http://www.appelsiini.net/projects/chained
 * NPM package url (optional): https://www.npmjs.com/package/jquery-chained
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 473
   - Count of watchers: 33
   - Count of forks: 232
 * NPM download stats (optional):
   - Downloads in the last day: 1
   - Downloads in the last week: 13
   - Downloads in the last month: 81

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7634, cc @tuupola

### CODE REVIEW

**Comment by tuupola** [comment]
Looks good to me. Should the autoupdate config also be in original repos package.json?

**Comment by PeterDaveHello** [comment]
@tuupola Nope, it do not to be in origin repo.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
@tuupola I found that some versions on GitHub are not on the npm package, would you like us to all the versions?

**Pull request merged**
