### PR TITLE
add bootstrap-treeview v1.2.0

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/jonmiles/bootstrap-treeview
**Watch 106
  Star 909
 Fork 378**
@Amomo could u help me check this PR for #6872 ? thank you!
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update) 
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Again, why don't you use npm?

**Comment by maruilian11** [comment]
because when i used `npm install bootstrap-treeview`, error happened.

**Comment by PeterDaveHello** [comment]
@maruilian11 That is not a reason.

**Comment by maruilian11** [comment]
@PeterDaveHello i have installed bootstrap-treeview successfully, but it needs `bower` and `nodejs-legacy`, do we still choose to  use npm auto-update config?

**Comment by PeterDaveHello** [comment]
I don't care about its dependencies.

**Comment by maruilian11** [comment]
@Amomo i have changed to npm auto-update, could you help me check this PR? thank you!

**Comment by PeterDaveHello** [comment]
There is no need to review a test failed PR @maruilian11

**Comment by maruilian11** [comment]
＠amomo i rebuild the test, and it pass now~

**Comment by PeterDaveHello** [comment]
Wrong commit message.

**Comment by maruilian11** [comment]
@Amomo i have added @ in commit message.

**Comment by maruilian11** [comment]
ping @Amomo

**Pull request merged**
