### PR TITLE
Add tingle@0.9.0 with git auto-update

### LINKED ISSUE #8128: [Request] Add tingle.js
**Library name:** tingle.js
**Git repository url:** https://github.com/robinparisi/tingle
**npm package url(optional):** https://www.npmjs.com/package/tingle.js
**License(s):** MIT
**Official homepage:** http://robinparisi.github.io/tingle/

### PR DESCRIPTION
**Pull request by clairetsai818**
close #8128, cc @robinparisi.

Pull request for issue: #8128 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/robinparisi/tingle/tree/v0.9.0
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 271
   - Count of watchers: 20
   - Count of forks: 41

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by clairetsai818** [comment]
@PeterDaveHello Please help me review this, thanks!

**Comment by clairetsai818** [comment]
@PeterDaveHello Please help me review this, thanks.

**Comment by clairetsai818** [comment]
@PeterDaveHello Please help me review this, thanks.

**Comment by PeterDaveHello** [comment]
@clairetsai818 You should mention what have you modified/updated first, then ask for review.

**Comment by clairetsai818** [comment]
@PeterDaveHello I've corrected the commit message, please help me review this. Thanks!

**Pull request merged**
