### PR TITLE
Update hls.js metadata, auto-update w/ new versions

### PR DESCRIPTION
**Pull request by extend1994**
# Pull request template for new library

Related issue(s): #13087, #12927, video-dev/hls.js#1890 
(This PR is to help #13087.)

## Profile of the lib

* Git repository (required): https://github.com/video-dev/hls.js
* Official website (optional, not the repository): https://hls-js.netlify.com/demo/
* NPM package url (optional): https://www.npmjs.com/package/hls.js

### CODE REVIEW

**Comment by extend1994** [comment]
@PeterDaveHello hls.js 8.0.0-beta.3 seems a mistake
Ref: https://github.com/cdnjs/cdnjs/commit/aff2818f30dfc267f924d2f3db9c3386962be04e

**Comment by PeterDaveHello** [comment]
Any reference about that mistake?

**Comment by extend1994** [comment]
Assumed it was a mistake because there is no 8.0.0-beta.3 on npm or GitHub, and the latest version looks like v0.12.2.
@tjenkinson Could you help check this issue?

**Comment by extend1994** [comment]
@tjenkinson Thanks for your quick response!

**Comment by PeterDaveHello** [comment]
@extend1994 FYR, here is the commit of cached 8.0.0-beta.3 tag in its git repository:

commit e43bdd401ad3c4efa468f44255534a19ca4ebb75
Author: John Bartos <jbartos@jwplayer.com>
Date:   Thu Sep 21 11:06:14 2017 -0400

    Update dist


and here is the list of all the cached tags:

8.0.0-beta.3
v0.0.1
v0.0.2
v0.0.3
v0.0.4
v0.0.5
v0.0.6
v0.0.7
v0.0.8
v0.0.9
v0.1.0
v0.1.1
v0.1.10
v0.1.11
v0.1.2
v0.1.3
v0.1.4
v0.1.5
v0.1.6
v0.1.7
v0.1.8
v0.1.9
v0.10.0
v0.10.1
v0.11.0
v0.12.0
v0.12.1
v0.12.2
v0.2.0
v0.2.1
v0.2.2
v0.2.3
v0.2.4
v0.2.5
v0.2.6
v0.3.0
v0.3.1
v0.3.10
v0.3.11
v0.3.12
v0.3.13
v0.3.14
v0.3.15
v0.3.2
v0.3.3
v0.3.4
v0.3.5
v0.3.6
v0.3.7
v0.3.8
v0.3.9
v0.4.0
v0.4.1
v0.4.10
v0.4.2
v0.4.3
v0.4.4
v0.4.5
v0.4.6
v0.4.7
v0.4.8
v0.4.9
v0.5.0
v0.5.1
v0.5.10
v0.5.11
v0.5.12
v0.5.13
v0.5.14
v0.5.15
v0.5.16
v0.5.17
v0.5.18
v0.5.19
v0.5.2
v0.5.20
v0.5.21
v0.5.22
v0.5.23
v0.5.24
v0.5.25
v0.5.26
v0.5.27
v0.5.28
v0.5.29
v0.5.3
v0.5.30
v0.5.32
v0.5.33
v0.5.34
v0.5.35
v0.5.36
v0.5.37
v0.5.38
v0.5.39
v0.5.4
v0.5.40
v0.5.41
v0.5.42
v0.5.43
v0.5.44
v0.5.45
v0.5.46
v0.5.47
v0.5.48
v0.5.49
v0.5.5
v0.5.50
v0.5.51
v0.5.52
v0.5.6
v0.5.7
v0.5.8
v0.5.9
v0.6.0
v0.6.1
v0.6.10
v0.6.11
v0.6.12
v0.6.13
v0.6.14
v0.6.15
v0.6.16
v0.6.17
v0.6.18
v0.6.19
v0.6.2
v0.6.2-0
v0.6.2-1
v0.6.2-2
v0.6.2-3
v0.6.2-4
v0.6.2-5
v0.6.2-6
v0.6.2-7
v0.6.20
v0.6.21
v0.6.3
v0.6.4
v0.6.5
v0.6.6
v0.6.7
v0.6.8
v0.6.9
v0.7.0
v0.7.1
v0.7.10
v0.7.11
v0.7.2
v0.7.3
v0.7.4
v0.7.5
v0.7.6
v0.7.7
v0.7.8
v0.7.9
v0.8.0
v0.8.1
v0.8.2
v0.8.3
v0.8.4
v0.8.5
v0.8.6
v0.8.7
v0.8.8
v0.8.9
v0.9.0
v0.9.1

I agree that v8.0.0-beta.3 looks wrong

**Comment by olafcm** [comment]
@extend1994 Any chance you could fix the v8.0.0-beta.3 issue so the lib will be published again on cdnjs? Would be highly appreciated! 🙏

**Comment by extend1994** [comment]
@PeterDaveHello thanks for the information, do I have to do anything to 8.0.0-beta.3?

**Comment by olafcm** [comment]
@PeterDaveHello Can you maybe help @extend1994 with this merge? Thanks again!

**Comment by PeterDaveHello** [comment]
@olafcm sure, I'll take a look soon!

**Comment by olafcm** [comment]
@PeterDaveHello If you find some time to finalize this merge, I would appreciate that very much 🙏

**Comment by olafcm** [comment]
@PeterDaveHello Sorry to keep asking again but I was hoping you could finalize this merge please. Thank you so much 👍 👍

**Comment by olafcm** [comment]
Thank you @PeterDaveHello 🎈 🎈

**Comment by PeterDaveHello** [comment]
Thank you all :+1:

**Pull request merged**
