### PR TITLE
Add keen.js v3.2.7 with git autoupdate.

### PR DESCRIPTION
**Pull request by Piicksarn**
**`git repository : `** https://github.com/keen/keen-js/tree/v3.2.7
**`Watch : 64 /  Star : 350 /  Fork : 101`**

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Don't you need your members to review this PR?

**Comment by Piicksarn** [comment]
@PeterDaveHello, i just want to make sure the pr could pass the online test before ping others for checking.

**Comment by Piicksarn** [comment]
@maruilian11, would you mind to checkout the pr for me?
Thank you!

**Comment by PeterDaveHello** [comment]
Okay, that's fine.

**Comment by maruilian11** [comment]
@Piicksarn i think the PR is ok, could u rebase and tag me again? thank you~

**Comment by Piicksarn** [comment]
@maruilian11, would you mind to have a look again at the pr?
Thank you~ :blush:

**Comment by maruilian11** [comment]
@Piicksarn i'm sorry could you rebase again? thank you!!!

**Comment by Piicksarn** [comment]
@maruilian11, i have it rebased to master! thank you!

**Comment by Piicksarn** [comment]
@maruilian11, i have it rebased!
thank you~~^^

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Pull request merged**
