### PR TITLE
add jquerymobile-router v0.93

### LINKED ISSUE #7255: [Request] Add jQueryMobile-Router
**Library name:** jQueryMobile-Router
**Git repository url:** https://github.com/azicchetti/jquerymobile-router
**npm package url(optional):** 
**License(s):** GPL, MIT
**Official homepage:** https://github.com/azicchetti/jquerymobile-router

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #7255 
@kennynaoh Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/azicchetti/jquerymobile-router
 * Official website (optional, not the repository): 
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 418
   - Count of watchers: 30
   - Count of forks: 85
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

with git autoupdate config, close #7255, cc @azicchetti

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Ping @kennynaoh. Please review PRs before sending new PRs, the late review may cause PR author do additional rebase process.

**Comment by kennynaoh** [comment]
@PeterDaveHello @pvnr0082t 
sorry about that.
I have a question.
There are two license it use.
Which one should be added or both of them?
Thanks.

**Comment by PeterDaveHello** [comment]
@kennynaoh Both, use "licenses" array.

**Comment by pvnr0082t** [comment]
@kennynaoh I have updated ```license``` field in package.json. Please review again, thank you.

**Comment by PeterDaveHello** [comment]
Thank you both.

**Pull request merged**
