### PR TITLE
[new] add qrcode.js@0.0.1, close #5164

### LINKED ISSUE #5164: [Request] Add qrcode.js
**Library name: qrcode.js
*_Git repository url: https://github.com/davidshimjs/qrcodejs
*_npm package url(optional):** 
**Official homepage: http://davidshimjs.github.io/qrcodejs/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by steadiest**
This is javascript qr code generator without jquery.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@steadiest I'm sorry for the late reply, are you still interested in finishing this PR? I think there are few parts we need to deal with here, thanks.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello What can we do for this PR?
There is no git tag for no upstream. 
And someone ask for git tag but still no response since 6 May 2015. davidshimjs/qrcodejs#56 davidshimjs/qrcodejs#96
And I can't find any version number in the commit message.
the related issue is #9878
And if this lib really needs to be added, should we add these files from this commit(https://github.com/davidshimjs/qrcodejs/tree/9695b8a0020a43ade540ed716ba4feb74b9672a9)? Because this commit added the bower.json and mention its version is v0.0.1.

Thank you.

**Comment by PeterDaveHello** [comment]
Let's close this one first, thanks.

**Pull request closed without merging**
