### PR TITLE
[author] [new] Add pusher-angular v0.1.4

### PR DESCRIPTION
**Pull request by hamchapman**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Don't you want to use npm as #4211 ? I prefer to use npm, it'll be faster to update a lib, what do you think?

**Comment by hamchapman** [comment]
I'm not too bothered either way, but I'd rather have it update via git if possible. If it's a big advantage for you guys to have it updated via npm then I'm okay with that, but my personal preference is for git.

**Comment by PeterDaveHello** [comment]
Yeah, it's a big advantage, if you are sure you'll update npm package regular, I'll suggest you to use npm update, it's more efficient for us, and check for update every hour, git auto-update doesn't, because every round of git auto-update will take much time.

**Comment by hamchapman** [comment]
Okay, please could you merge in #4211 instead then please? Thanks for your help!

**Comment by PeterDaveHello** [comment]
Okay, I'll be happy to, but seems you deleted the branch so that I can reopen it, would you please undo and open it again? thanks.

**Comment by hamchapman** [comment]
I've force pushed the npm autoupdating version to update this pull request. Hope that's okay.

**Comment by PeterDaveHello** [comment]
Thank you @hamchapman.

**Pull request merged**
