### PR TITLE
Add KaTeX v0.7.0 via downloading katex.zip

### PR DESCRIPTION
**Pull request by pvnr0082t**
Pull request for issue: #10337 
- Manually add KaTeX v0.7.0 due to there is no dist folder on GitHub repo.
@kennynaoh Please help me review this pull request, thank you.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Ping @kennynaoh

**Comment by kennynaoh** [comment]
@pvnr0082t Sorry for late response. I think this PR is ok. Please rebase to the latest master branch. Thanks!

**Comment by pvnr0082t** [comment]
@kennynaoh I have rebased onto the latest master branch. Please help me review it again, thank you.

**Comment by PeterDaveHello** [comment]
You should provide the download link, btw v0.7.1 released, let's also add it, and contact with upstream to discuss about the possibility to make auto-update work again, thanks.

**Comment by pvnr0082t** [comment]
v0.7.0 download link: https://github.com/Khan/KaTeX/releases/download/v0.7.0/katex.zip
@PeterDaveHello I have discussed with upstream to put `dist` folder back to GitHub repo(https://github.com/Khan/KaTeX/issues/641), and v0.7.1 had already been added by auto-updater (5d56415be533c7f9f22d8f0ec5ce19cfa4a46e70).

**Comment by PeterDaveHello** [comment]
@pvnr0082t just give this info in the first comment and commit message next time before review, so we can review and merge more efficiently.

**Pull request merged**
