### PR TITLE
Vega-Lite does not need css files

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@domoritz that's intention to do that for potential future changes compatible, flexibility, so we'll keep it, thanks.

**Comment by domoritz** [comment]
Thanks @PeterDaveHello for looking at my PRs! Vega-Lite will probably never have css files but I'm okay with keeping this as is.

**Comment by PeterDaveHello** [comment]
@domoritz Thank you, too.

**Comment by PeterDaveHello** [comment]
@domoritz We just try to use a simple way that can applied on many libraries so the maintanence work load can be lower, we are only few people and mostly students, but there are 2.8k libraries there, we actually don't have enough support and resource :)

**Comment by domoritz** [comment]
@PeterDaveHello Thanks for your hard work!

**Comment by PeterDaveHello** [comment]
@domoritz you're welcome.

**Pull request closed without merging**
