### PR TITLE
add spinkit v1.2.5

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/tobiasahlin/SpinKit
**Watch 357
  Star 10,361
 Fork 935**
@Amomo  could u help me check this PR for #6654 ? thank you!

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity 
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by Amomo** [comment]
Hi @maruilian11, sorry for late.
`"gulpfile.js"` is a file used by `gulp`(the streaming build system) to build the project. 
I think we don't need it, could you make some fix? thanks :-)

**Comment by maruilian11** [comment]
@Amomo  thank you, i have removed them.

**Comment by PeterDaveHello** [comment]
There is no `spinners` folder in the root of its npm pacakge.

**Comment by maruilian11** [comment]
@Amomo i have added the basepath, could you help me check the PR again? thank you!

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine, could you take it a look? Thanks! :-D

**Pull request merged**
