### PR TITLE
Add fermata@0.10.8 w/ npm auto-update

### PR DESCRIPTION
**Pull request by lcd78706**
Pull request for issue: #10656 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/natevw/fermata
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/fermata
 * License and its reference: MIT https://github.com/natevw/fermata#mit-license
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 14
   - Count of stars: 330
   - Count of forks: 27
 * NPM download stats (optional):
   - Downloads in the last day: 44
   - Downloads in the last week: 151
   - Downloads in the last month: 467

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by lcd78706** [comment]
@x09326 
Please review this PR. Thanks!

**Comment by x09326** [comment]
@PeterDaveHello Is the beta version okay?

**Comment by lcd78706** [comment]
@x09326 
I have modified it to the latest stable version. 
Please review it again. Thanks!

**Comment by x09326** [comment]
@lcd78706 Sorry for the late response, please rebase with the latest master branch, thanks.

**Comment by lcd78706** [comment]
@x09326 
I have rebased with the latest master branch. Please review it again. Thanks!

**Comment by x09326** [comment]
LGTM @cdnjs/intern2 please help me review it.

**Comment by lcd78706** [comment]
@pvnr0082t 
Sorry, I forgot it, and I have modified it. 
Please review it again. Thanks!

**Comment by x09326** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
Thanks guys!

**Comment by PeterDaveHello** [comment]
@x09326 please use "approve" feature instead of "LGTM", thanks.

**Pull request merged**
