### PR TITLE
add npm autoupdate config for Uniform.js

### LINKED ISSUE #7660: [Request] update jquery.uniform
**Library name:** jquery.uniform
**Git repository url:** https://github.com/AudithSoftworks/Uniform
**npm package url(optional):** https://www.npmjs.com/package/jquery.uniform
**License(s):** MIT
**Official homepage:** http://opensource.audith.org/uniform
**Wanna say something? Leave message here:** I am the owner and would like my package to be added to CDNjs.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #7660 
@dannyxx001 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/AudithSoftworks/Uniform
 * Official website (optional, not the repository): http://opensource.audith.org/uniform
 * NPM package url (optional): https://www.npmjs.com/package/jquery.uniform
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 2231
   - Count of watchers: 76
   - Count of forks: 374
 * NPM download stats (optional):
   - Downloads in the last day: 46
   - Downloads in the last week: 72
   - Downloads in the last month: 176

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7660, cc @AudithSoftworks

### CODE REVIEW

**Comment by dannyxx001** [comment]
Yeah, I think the format is OK. However, the version is not the latest. @PeterDaveHello I don't know whether we should update it manually or just let it autoupdate.

**Comment by PeterDaveHello** [comment]
We should try to keep its structure as before, see:
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/Uniform.js/2.1.2

So let's try this:
```json
  "npmFileMap": [
    {
      "basePath": "dist",
      "files": [
        "**/*"
      ]
    },
    {
      "basePath": "",
      "files": [
        "themes/**/*.+(png|css)"
      ]
    },
    {
      "basePath": "lib",
      "files": [
        "jquery.uniform.js"
      ]
    }
  ]
```

**Comment by pvnr0082t** [comment]
@dannyxx001 I have updated the autoupdate config. Please help me review again, thank you.

**Comment by dannyxx001** [comment]
I think it's the same as Peter's suggestion. @PeterDaveHello please review again, thanks.

**Comment by shehi** [comment]
@PeterDaveHello the latest version is 2.2.0 and the file to be included actually is ```lib/jquery.uniform.js```.

**Comment by PeterDaveHello** [comment]
@shehi thanks!

**Pull request merged**
