### PR TITLE
add minified file of audiosynth, and point audiosynth.js to audiosynth.min.js, #5195

### PR DESCRIPTION
**Pull request by Amomo**
Hi @LeaYeh , I add a minified file of audiosynth.js, and point filename field to `audiosynth.min.js`.
Would you mind checking this PR from #5195 for me? Thank you~ :-)

### CODE REVIEW

**Comment by LeaYeh** [comment]
it is fine

**Comment by PeterDaveHello** [comment]
point **audiosynth.js** to `audiosynth.min.js`?

**Comment by Amomo** [comment]
Oooh! I got it. My wording is wrong! 
@LeaYeh I have fixed the commit message.
Could you check it for me? Thank you. :-D

**Comment by LeaYeh** [comment]
ok.

**Comment by Amomo** [comment]
@LeaYeh I have rebased it to latest master branch.
If it is ok, could you ping peter for me? Thank you! :-D

**Comment by LeaYeh** [comment]
sorry for late, try to rebase it again and i will check it ASPA.

**Comment by PeterDaveHello** [comment]
What's the reason why to close this one?

**Comment by Amomo** [comment]
partially duplicated with #5280

**Comment by PeterDaveHello** [comment]
@LeaYeh you should check the PR list before send a PR.

**Pull request closed without merging**
