### PR TITLE
add fetch-jsonp@1.0.0 w/ npm autoupdate

### LINKED ISSUE #8676: [Request] Add fetch-jsonp
**Library name:** fetch-jsonp
**Git repository url:https://github.com/camsong/fetch-jsonp**
**npm package url(optional): https://www.npmjs.com/package/fetch-jsonp** 
**License(s): MIT**
**Official homepage:https://github.com/camsong/fetch-jsonp**
**Wanna say something? Leave message here:**
Useful since the Fetch API does not support JSONP.

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8676 
@kennynaoh Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/camsong/fetch-jsonp
 * Official website (optional, not the repository): 
 * NPM package url (optional): https://www.npmjs.com/package/fetch-jsonp
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 137
   - Count of watchers: 2
   - Count of forks: 20
 * NPM download stats (optional):
   - Downloads in the last day: 248
   - Downloads in the last week: 1223
   - Downloads in the last month: 5311

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8676, cc @camsong

### CODE REVIEW

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Comment by camsong** [comment]
I'm the author of  fetch-jsonp. Great thanks for doing this @pvnr0082t

**Comment by PeterDaveHello** [comment]
Here we go.

**Comment by dax70** [comment]
Thanks for adding this! 👍

**Comment by PeterDaveHello** [comment]
@dax70 You are welcome.

**Pull request merged**
