### PR TITLE
Add nipplejs@0.6.7 w/ git auto-update  close #11056, cc @yoannmoinet

### LINKED ISSUE #11056: [Request] Add nipplejs
**Library name:** nipplejs
**Git repository url:** https://github.com/yoannmoinet/nipplejs
**npm package name or url** (if there is one): nipplejs 
**License (List them all if it's multiple):** MIT
**Official homepage:** http://yoannmoinet.github.io/nipplejs
**Wanna say something? Leave message here:**

### PR DESCRIPTION
**Pull request by ajay2507**
Pull request for issue: #11056 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/yoannmoinet/nipplejs.git
 * Official website (optional, not the repository): https://yoannmoinet.github.io/nipplejs/
 * NPM package url (optional): https://www.npmjs.com/package/nipplejs
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 20
   - Count of stars: 760
   - Count of forks: 46
 * NPM download stats (optional):
   - Downloads in the last day: 16
   - Downloads in the last week: 133
   - Downloads in the last month: 796

# Essential checklist
 * [ ] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by ajay2507** [comment]
@pvnr0082t  Hi, kindly provide me a complete commit message, so that I can include that message.

**Comment by pvnr0082t** [comment]
@ajay2507 Like this:
```
Add nipplejs@0.6.7 w/ git auto-update

close #11056, cc @yoannmoinet
```

Thanks.

**Comment by ajay2507** [comment]
Okay thanks.

**Comment by pvnr0082t** [comment]
move to #11342.

**Pull request closed without merging**
