### PR TITLE
Update card configuration to auto-update from NPM

### PR DESCRIPTION
**Pull request by jessepollak**
This PR adds an auto configuration for jessepollak/card and closes jessepollak/card#180.

Let me know if there's anything else I need to do

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please don't bump version here.

**Comment by jessepollak** [comment]
Updated, thanks!

**Comment by PeterDaveHello** [comment]
Could you please squash them into only one commit? Thanks.

**Comment by jessepollak** [comment]
Will do — it will take me a little while because I have to clone the whole repo to squash.

**Comment by PeterDaveHello** [comment]
hmmm ... nope, maybe you can try `git reset HEAD^` to undo latest commit and use `git commit --amend` to commit in the same latest commit again. It's very fast and easy!

**Comment by jessepollak** [comment]
I've never had it cloned, I made these changes on the web on Github :)

**Comment by PeterDaveHello** [comment]
Oh, sure, maybe you can close this one and open a new one, so that you don't need to squash, just do it in one step!

**Comment by jessepollak** [comment]
Oh, nice good idea!

**Pull request closed without merging**
