### PR TITLE
add angular-ui/ui-slider v0.3.1

### LINKED ISSUE #6870: [Request] Add angular-ui/ui-slider
**Library name:** jQuery UI Slider for AngularJS
**Git repository url:** https://github.com/angular-ui/ui-slider.git
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/angular-ui/ui-slider
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #6870
@pvnr0082t  please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/angular-ui/ui-slider.git
 * Official website (optional, not the repository): https://github.com/angular-ui/ui-slider
 * NPM package url (optional): https://www.npmjs.com/package/angular-ui-slider
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 237
   - Count of watchers: 37
   - Count of forks: 168
 * NPM download stats (optional):
   - Downloads in the last day: 51
   - Downloads in the last week: 165
   - Downloads in the last month: 646

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

npm auto-update config added, close #6870, cc @PowerKiKi

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@kennynaoh you need to pass the build first.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I have fixed it. Thanks.
@pvnr0082t 
Please help me review it again.
Thanks.

**Comment by pvnr0082t** [comment]
@kennynaoh The version on GitHub is v0.3.1 but on npm is v0.3.0. You can open the issue to remind author updating the latest version on npm.

**Comment by kennynaoh** [comment]
@pvnr0082t 
OK
Thanks

**Comment by PeterDaveHello** [comment]
Let's use `angular-ui-slider` as its folder name.

**Comment by kennynaoh** [comment]
@pvnr0082t 
The version problem has solved.
And also changed the folder name.
Please help me review it again.
Thanks.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Pull request merged**
