### PR TITLE
update Kule Lazy 3.0.1015beta

### PR DESCRIPTION
**Pull request by keicheng**
I updated a new version and add image files for old version(3.0.1007beta)

maybe need a new PR or not?

### CODE REVIEW

**Comment by maruilian11** [comment]
hi, @keicheng i click the tag `3.0.1015beta`, but the package.json is still point to `3.0.1007beta`.
the repo has `3.0.1015beta` and `3.0.1007beta` two files, but we usually use tag to differentiate versions.
for example, when i click tag `3.0.1007beta` i should only see `css` folder and package which point to `3.0.1007beta` and other files like `LICENSE`, `README.md`...
in the same way, when i click tag `3.0.1015beta` i should only see `css` folder and package which point to `3.0.1015beta` and other files like `LICENSE`, `README.md`...

if you can do this, you won't need to send new PR with new version until you file structure changes.

**Comment by PeterDaveHello** [comment]
404 not found
https://github.com/keicheng/kule.lazy/tree/v3.0.1015beta/css

**Comment by PeterDaveHello** [comment]
@keicheng I think you should better not to add the version number into folder name, git is already a version control system, you can use commit hash and version tag to checkout different versions, and also, our auto-updater need a static folder name as its base path to grab the files, dynamic as current will not work.

**Comment by PeterDaveHello** [comment]
I added v3.0.1015beta here 1659967 for you, leave this issue opened to help you fix the structure in your repo.

**Comment by keicheng** [comment]
抱歉，我英文不好，所以請讓我用中文說明

非常感謝兩位，我會研究並嘗試你們說的方式
如果你們在台北，或是哪天你們到台北
有朝一日務必讓我請你們吃飯，真的感激不盡

**Comment by PeterDaveHello** [comment]
@keicheng you can write me an email in Chinese if you need help,

- peter at cdnjs dot com 
- hsu at peterdavehello dot com

BTW, I accepted your kindness, but you don't need to buy me a dinner :smile:

**Comment by keicheng** [comment]
haha, ok

i check again
is "peterdavehello dot com" or "peterdavehello dot org"?

**Comment by PeterDaveHello** [comment]
> is "peterdavehello dot com" or "peterdavehello dot org"?
Oops, itss org, just typo, updated.

**Comment by keicheng** [comment]
i got it!

**Comment by PeterDaveHello** [comment]
Should still fix the structure on the repo @keicheng.

**Comment by keicheng** [comment]
Yes, I done. It`s right?
https://github.com/keicheng/kule.lazy/tree/v3.0.1015beta/css

**Comment by PeterDaveHello** [comment]
Looks fine now.

**Comment by keicheng** [comment]
@PeterDaveHello , @maruilian11 
I got correct tag method. Thanks!

**Comment by PeterDaveHello** [comment]
@keicheng np

**Comment by maruilian11** [comment]
:smile:

**Comment by keicheng** [comment]
i updated lazy, i edited pachage,json and set a new tag of lazy.
https://github.com/keicheng/kule.lazy/tree/v3.0.1101beta/dist

i need a new PR?

**Comment by PeterDaveHello** [comment]
@keicheng You may need to send a new pr for the new dist folder i think.

**Comment by keicheng** [comment]
ok, i try it.

**Pull request closed without merging**
