### PR TITLE
[new] add angular-video-bg@0.3.3 with git auto-update, close #5174

### LINKED ISSUE #5174: [Request] Add angular-video-bg
**Library name: angular-video-bg** 
**Git repository url: https://github.com/kanzelm3/angular-video-bg.git**
**npm package url(optional): non** 
**Official homepage: http://kanzelm3.github.io/angular-video-bg/**
**Wanna say something? Leave message here: angular-video-bg is an Angular.js YouTube video background player directive. It stresses simplicity and performance.**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 , I add a new lib with git auto-update from the request #5174
repo: https://github.com/kanzelm3/angular-video-bg
And, I pick some keywords from README.md
Would you mind checking this PR for me? Thank you~ :-)

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `13`, Star `120`, Fork `12`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by maruilian11** [comment]
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity 
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

@Amomo sorry for checking late, i think this PR is ok！ can u rebase it and tag me?  thank you!

**Comment by Amomo** [comment]
@maruilian11 I have rebased it~
Could you take a look? Thank you~

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Comment by PeterDaveHello** [comment]
Do we need `angular-video-bg-spec.js`? I don't think so.

**Comment by Amomo** [comment]
ok, I removed it.
@maruilian11 I have modified this PR. Could you check it again?
Thank you~ :-D

**Comment by maruilian11** [comment]
@Amomo sorry for checking late, can you rebase it and tag me again? thank you very much!!!

**Comment by Amomo** [comment]
@maruilian11 I have rebased it, could you take a look? Thank you!

**Comment by maruilian11** [comment]
sorry, i just find that could you update your filemap to `angular-video-bg*.js`

**Comment by Amomo** [comment]
@maruilian11 because I don't want to collect `angular-video-bg-spec.js`, I only point to `angular-video-bg.js`. The minified file has been pointed in filename field. Is it ok?

**Comment by maruilian11** [comment]
@Amomo oh, sorry i didn't see `angular-video-bg-spec.js`, i thought we still need to add `.min.js` in filemap, or how do we make differences between there is the min file or not on the repo?

**Comment by Amomo** [comment]
@maruilian11 
Ummm...I think if "filename" field point to a minified file which is not exist by default, it will be minified by `cdnjs/build/minify.js`. So I didn't add `angular-video-bg.min.js` in filemap at first, I think cdnjs may minify `angular-video-bg.js` by itself.

But the lib really provide `angular-video-bg.min.js`, I will modify my filemap to collect it.
Thanks for your question! :-D

**Comment by Amomo** [comment]
@maruilian11 Could you take a look again? Thank you! :-D

**Comment by maruilian11** [comment]
@Amomo i think you can use `angular-video-bg*.js` next time:)
@PeterDaveHello i think this PR is ok.

**Comment by PeterDaveHello** [comment]
we don't need `angular-video-bg-spec.js` ...

**Comment by Amomo** [comment]
I don't add it...

**Comment by PeterDaveHello** [comment]
I don't say you added it :P

**Comment by maruilian11** [comment]
i don't remember why i keep saying this = =

**Pull request merged**
