### PR TITLE
[New] Add rot.js@0.6.0 w/ git auto-update

### LINKED ISSUE #11744: [Request] rot.js v0.6
https://github.com/ondras/rot.js
ROguelike Toolkit
1092 stars

### PR DESCRIPTION
**Pull request by sufuf3**
### Memo: 
Although there are more versions from npm, the files we can use is from GitHub.
So I choose git auto-update.

---

close #11744

Pull request for issue: #11744
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/ondras/rot.js
 * Official website (optional, not the repository): https://github.com/ondras/rot.js
 * NPM package url (optional): https://www.npmjs.com/package/rot-js
 * License and its reference: BSD-3-Clause
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 86
   - Count of stars: 1099
   - Count of forks: 158
 * NPM download stats (optional):
   - Downloads in the last day: 8
   - Downloads in the last week: 24
   - Downloads in the last month: 159

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
The file under `lib` of lib from npm mention `Add objects for Node.js environment` so I think it can't use in web front-end, could you use this file in web front-end?
Also, the file from npm is different from https://github.com/ondras/rot.js/blob/master/rot.js so I think it's good to add this lib from GitHub.
What do you think?

Thank you.

**Comment by extend1994** [comment]
I saw that and I tried to use it. It's a huge project as you can see there are so many paged introducing the lib. I am unsure if I use it correctly. So I think it's good to confirm with the author. If you have confirmed it can not be used in front-end, no argument on it.

**Comment by sufuf3** [comment]
@cdnjs/active-contributor @cdnjs/intern3 please help me review this PR.
Thank you.

Memo: if you check files from `npm i rot-js` you can see the code are for the back-end.
Although there are more versions from npm, the files we can use is from GitHub.
So I choose git auto-update.

**Comment by sufuf3** [comment]
ping @extend1994 @hare1039 @qwe19272375 @cdnjs/active-contributor

**Pull request merged**
