### PR TITLE
Update repo url of jquery-requestAnimationFrame v0.1.2

### LINKED ISSUE #6883: [Request] jQuery requestAnimationFrame
**Library name:** jQuery requestAnimationFrame
**Git repository url:** https://github.com/gnarf/jquery-requestAnimationFrame
**License(s):** MIT license
**Official homepage:** https://github.com/gnarf/jquery-requestAnimationFrame

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #6883
@PeterDaveHello  please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/gnarf/jquery-requestAnimationFrame
 * Official website (optional, not the repository): https://github.com/gnarf/jquery-requestAnimationFrame
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 335
   - Count of watchers: 26
   - Count of forks: 35
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

url updated, cc @gnarf

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@kennynaoh Please ask other reviewers in @cdnjs/intern2 first, thanks.

**Comment by kennynaoh** [comment]
@pvnr0082t 
Please help me review this PR 
Thanks

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think the problem is fixed. Please review this pull request, thank you.

**Comment by PeterDaveHello** [comment]
Nope, the PR title and commit message are pretty bad. Please describe what you have done in the commit.

**Comment by kennynaoh** [comment]
Thanks for reviewing
I have updated the commit message
Please help me review it again
Thanks

**Comment by pvnr0082t** [comment]
@PeterDaveHello title and commit message is fixed. I think it's ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
Nope, still bad. What's the reason why to close a closed issue ticket?
Try this: `Update/fix repo url of jquery-requestAnimationFrame`

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I have changed the commit message
Please help me review it again
Thanks

**Comment by kennynaoh** [comment]
Sorry, I think I deleted some files which they should be not deleted
I will fix it later
Thanks

**Comment by kennynaoh** [comment]
@PeterDaveHello 
Sorry, I not sure why I closed this PR
Is this successful or not?
Should I create another new PR again?
Thanks

**Comment by PeterDaveHello** [comment]
Of course not, why not just reopen it?

**Comment by kennynaoh** [comment]
I can't click that button.
The message of the button "Reopen and comment"
is "There are no new commits on the kennynaoh:jquery-requestAnimationFrame branch"
What should I do?
Is there another way to reopen it?
Thanks

**Comment by PeterDaveHello** [comment]
@kennynaoh Did you delete the branch on GitHub? Maybe try to push it back, if you still can't reopen it, than just open a new PR.

**Pull request closed without merging**
