### PR TITLE
add angular-sortable-view with npm auto-update

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #8621 
@x09326 please help me review this pull request, thank you.
Manually add the other versions from git repo because npm auto-update can't get some of the old versions
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/kamilkp/angular-sortable-view
 * Official website (optional, not the repository): https://kamilkp.github.io/angular-sortable-view/#?tab=7
 * NPM package url (optional): https://www.npmjs.com/package/angular-sortable-view
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 320
   - Count of watchers: 20
   - Count of forks: 80
 * NPM download stats (optional):
   - Downloads in the last day: 69
   - Downloads in the last week: 272
   - Downloads in the last month: 1564

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@kennynaoh please solving the pending PRs first(Including the PRs waiting for review)

**Comment by PeterDaveHello** [comment]
@x09326 do you have any comments about this PR? Thanks.

**Comment by x09326** [comment]
@PeterDaveHello 
I don't have any comments, please help me review it, thanks.

**Comment by PeterDaveHello** [comment]
@x09326 so it's good for you or not?

**Comment by kennynaoh** [comment]
ping @x09326

**Comment by x09326** [comment]
LGTM

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 
I have rebased to the latest master branch again.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
@kennynaoh you didn't rebase it.

**Comment by kennynaoh** [comment]
Sorry, something wrong with me.
@pvnr0082t , @x09326 
I have rebased to the latest master branch.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
LGTM, @cdnjs/intern2 please merge this.

**Pull request merged**
