### PR TITLE
Added js-data

### PR DESCRIPTION
**Pull request by jmdobry**
Added js-data-angular@1.8.0

Added js-data-angular@2.4.0

Added js-data-http@1.2.3

Added js-data-firebase@1.1.1

Added js-data-localstorage@1.1.1

Added js-data-localforage@1.1.0

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please commit different libs in different commits as readme said, thanks.

**Comment by jmdobry** [comment]
Done

**Comment by PeterDaveHello** [comment]
Seems you touched sortable lib, need to remove that.

**Comment by jmdobry** [comment]
I'm not sure what to do about sortable. Even when I do a fresh clone of `cdnjs` it tells me there are changes in sortable. Nothing I do seems to get rid of the changes.

**Comment by PeterDaveHello** [comment]
Are you using Mac OS? I don't think a fresh clone will cause the same problem @@
PS: You can clone locally, it'll be fast.

**Comment by jmdobry** [comment]
I am on MAC OS

**Comment by PeterDaveHello** [comment]
Ref: #3650

**Comment by jmdobry** [comment]
I had done the `git update-index --assume-unchanged ajax/libs/Sortable/package.json` solution mentioned in #3792, but I guess that was insufficient...

**Comment by PeterDaveHello** [comment]
Did you try clone again but locally? A fresh clone should not have this problem, only rebased repo will have.

**Comment by jmdobry** [comment]
This is what I did:

```
> git clone git@github.com:cdnjs/cdnjs.git
> cd cdnjs && git status && cd .. // shows "modified:   ajax/libs/Sortable/package.json"
> git clone -l ./cdnjs cdnjs2
> cd cdnjs2
> git status // still shows "modified:   ajax/libs/Sortable/package.json"
```

**Comment by PeterDaveHello** [comment]
Would you please try to clone without parameter -l?

**Comment by jmdobry** [comment]
```
> git clone ./cdnjs cdnjs3
> cd cdnjs3
> git status // still shows "modified:   ajax/libs/Sortable/package.json"
```

**Comment by jmdobry** [comment]
Looks like I managed to remove the changes to Sortable. I used the cdnjs-importer to add the libs to `cdnjs3/`, then manually copied the files to `cdnjs2`, where I had run several `git update-index --assume-unchanged` commands.

**Comment by PeterDaveHello** [comment]
Thank you.

**Pull request merged**
