### PR TITLE
Add eModal@1.2.65 w/ npm auto-update

### LINKED ISSUE #10119: [Request] Add eModal
**Library name:** eModal
**Git repository url:** https://github.com/saribe/eModal
**npm package url(optional):** https://www.npmjs.com/package/emodal
**License(s):** MIT
**Official homepage:** https://saribe.github.io/eModal/#demo

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are too many files in this repo, without sparseCheckout, the whole process will be super slow, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
 - https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#d-adding-a-new-library

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄 .

### PR DESCRIPTION
**Pull request by LuisRBarreras**
#Pull request for issue: #10119 
Review @extend1994 and @hare1039 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/saribe/eModal
 * Official website (optional, not the repository): https://saribe.github.io/eModal/#demo
 * NPM package url (optional): https://www.npmjs.com/package/emodal
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 27
   - Count of stars: 172
   - Count of forks: 55
 * NPM download stats (optional):
   - Downloads in the last day: 3
   - Downloads in the last week: 18
   - Downloads in the last month: 75

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@sufuf3 you should as me or @pvnr0082t for review as we discussed before.

**Comment by PeterDaveHello** [comment]
Hi @LuisRBarreras, thank you for the contribution, I just found one thing that we'll need to confirmed, I just found that the file you added in the commit `eModal.js` seems to use different file format with the one on its npm package, not sure if you edited it? The origin one seems to use `dos` file format, but yours seem to use `unix` file format, personally I'll prefer to use unix file format, unfortunately we should not touch the content by ourselves, would you please help to use the official one? Thanks.

@cdnjs/intern3 I do teach and ask you guys to check the hash of files, so why didn't you do that?

**Comment by LuisRBarreras** [comment]
Hello @PeterDaveHello,  I don't edit the files, but the problem comes from the fact the source file was taken from github and not from npm.  
I'm going to fix that and make sure to use the correct file format

**Comment by PeterDaveHello** [comment]
@LuisRBarreras cool, since we use npm auto-update here, so it'll be better to be the same as the one on npm, thanks.

**Comment by LuisRBarreras** [comment]
Note:
From the npm:
- File eModal. j's in **DOS format**
- File eModal. min. j's in **Unix format**
 
I leave in that way, without changing the format

**Comment by PeterDaveHello** [comment]
@LuisRBarreras would you please rebase you branch with out latest master branch?

**Comment by PeterDaveHello** [comment]
@LuisRBarreras I'm really glad that you like it, I also noticed the difference better the src and min file, how ever, to keep the file integrity, especially for SRI support, I'll like to keep as what they are as upstream, thanks for your contribution.

SRI references:
 - https://www.w3.org/TR/SRI/
 - https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by PeterDaveHello** [comment]
Thank you all for your contribution.

@LuisRBarreras, as @sufuf3 and @extend1994 mentions, we could have a better commit message next time 😄

**Pull request merged**
