### PR TITLE
setup autoupdate for ember-resource.js

### PR DESCRIPTION
**Pull request by sandlerr**
# Profile of the lib
 * Git repository (required): https://github.com/zendesk/ember-resource/
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 143
   - Count of watchers: 259
   - Count of forks: 32

cc @staugaard @shajith @jish

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Thanks @sandlerr.

**Comment by PeterDaveHello** [comment]
BTW if there may be other directories and files under directories, the files config need to change from `"*"` to `"**/*"`

**Comment by sandlerr** [comment]
Thanks @PeterDaveHello !

**Comment by PeterDaveHello** [comment]
You're welcome @sandlerr

**Pull request merged**
