### PR TITLE
add lory.js@2.2.0 w/ npm auto-update config

### LINKED ISSUE #8495: [Request] Add lory
**Library name:** lory
**Git repository url:**https://github.com/meandmax/lory
**npm package url(optional):** https://www.npmjs.com/package/lory.js
**License(s):**MIT
**Official homepage:**https://meandmax.github.io/lory/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by nolsherry**
@pvnr0082t, please help me review this PR, thanks! 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/meandmax/lory
 * Official website (optional, not the repository): https://meandmax.github.io/lory/
 * NPM package url (optional): https://www.npmjs.com/package/lory.js
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 674
   - Count of watchers: 26
   - Count of forks: 97
 * NPM download stats (optional):
   - Downloads in the last day: 102
   - Downloads in the last week: 729
   - Downloads in the last month: 3534

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [X] This lib was not found on cdnjs repo
 * [X] No already exist / duplicated issue and PR
 * [X] The lib has notable popularity
   * [X] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [X] More than 500 downloads stats per month on npm registry
 * [X] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [X] Has valid tags for each versions (for git auto-update)
 * [X] Auto-update setup
 * [X] Auto-update target/source is valid.
 * [X] Auto-update filemap is correct.

# Git commit checklist
 * [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X] The parent of the commit(s) in the PR is not old than 3 days.
 * [X] Pull request is sending from a non-master branch with meaningful name.
 * [X] Separate unrelated changes into different commits.
 * [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [X] Close corresponding issue in commit message
 * [X] Mention related issue(s), people in commit message, comment.

close #8495, cc @meandmax

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@nolsherry Any reason you minified files without `.map`?

**Comment by pvnr0082t** [comment]
The latest version goes to `v2.1.3`. Please update to the latest version, thank you.

**Comment by PeterDaveHello** [comment]
@pvnr0082t v2.1.0 is officially minified, and the structure changed from v2.1.3, @nolsherry please contact with the author to discuss about the best way to handle this.

**Comment by meandmax** [comment]
@nolsherry, @PeterDaveHello, @pvnr0082t ... the current version is 2.2.0 also with map files.

https://github.com/meandmax/lory/tree/master/dist

Do I need to do anything?

cheers
Max

**Comment by nolsherry** [comment]
Thanks @meandmax for your contribution.
Because I found that the file structure in recent release(`v2.1.6`, `v2.1.7`, and `v2.2.0`).
Could you remain these kind of structure(with minified file and map file)?
By the way, some old versions without minifying, we can help you minify it with map.

cc @PeterDaveHello

**Comment by meandmax** [comment]
@nolsherry the filestructure will stay like it is now, with minified files, map files and unminified files.

**Comment by PeterDaveHello** [comment]
@meandmax Thank you for the info!

**Comment by meandmax** [comment]
@PeterDaveHello So could we merge this then, because than I could update the readme of lory with newest version on cdnjs?

**Comment by PeterDaveHello** [comment]
@meandmax Please give us few more hours, we have a standard review process for every PR, I'll give this PR a higher priority and make it been merged ASAP, thanks for your patient!

**Comment by PeterDaveHello** [comment]
@cdnjs/intern2 please help review this PR, we need this been merged ASAP, thanks!

**Comment by meandmax** [comment]
@PeterDaveHello, @cdnjs/intern2 And as I read in the documentation the package.json file without a version number should be enough to always get the latest version in cdnjs. Is this correct? Then we can remove the dist files from this PR.

**Comment by PeterDaveHello** [comment]
@meandmax nope, it's just for the first time you want to add a lib on CDNJS and you don't want to clone the repo and add the files by yourself, then you can just add package.json without version, in that case, I'll manually import that lib.

**Comment by nolsherry** [comment]
@kennynaoh , @pvnr0082t , I have updated the latest version `v2.2.0`, please help me review this PR, thanks.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM

**Comment by kennynaoh** [comment]
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Thank you all guys!

**Pull request merged**
