### PR TITLE
add history 1.12.5

### PR DESCRIPTION
**Pull request by mjackson**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please also add `repository` in package.json

**Comment by mjackson** [comment]
Nevermind.

**Comment by PeterDaveHello** [comment]
@mjackson sorry for the inconvenience. @Piicksarn  please help send another PR to add this lib.

**Comment by ashwinr** [comment]
sigh, @PeterDaveHello, what changes would the new PR have -- just the repository?

**Comment by PeterDaveHello** [comment]
@ashwinr I think so. Feel free to try it if you want :+1:

**Comment by ashwinr** [comment]
here it is: https://github.com/cdnjs/cdnjs/pull/6058

**Comment by PeterDaveHello** [comment]
Merged, thanks.

**Pull request closed without merging**
