### PR TITLE
add taggd@2.0.3 w/ git autoupdate

### LINKED ISSUE #8236: [Request] Add taggd
**Library name:** taggd
**Git repository url:** https://github.com/timseverien/taggd
**npm package url(optional):**  
**License(s):** MIT
**Official homepage:** https://timseverien.com/taggd/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8236 
@x09326 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/timseverien/taggd
 * Official website (optional, not the repository): https://timseverien.github.io/taggd/
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 161
   - Count of watchers: 22
   - Count of forks: 30
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8236, cc @timseverien

### CODE REVIEW

**Comment by x09326** [comment]
@pvnr0082t 
Can you confirm the license?
Because I saw the **taggd.css** use the WTFPL license.

**Comment by timseverien** [comment]
Author of the library here.

Taggd’s package.json contains the MIT license. The stylesheet is optional and carries a custom license, hence it’s included in the file itself. It’s good as is.

I have plans to release version 3 in the near future that is incompatible, both the API as file structure.

- Can auto-update deal with this? Or...
- should I submit a new PR once version 3 is released? Or
- can I do stuff on my end to ensure it keeps working?

**Comment by PeterDaveHello** [comment]
Hi @timseverien,

Thanks for your comments, as you can see there is a auto-update config in the package.json in this PR, if you didn't change the file/directory structure in future releases, yes, our auto-updater will fetch the new versions, as you can see in our commit history, there are many commits came from the bot.

I think we could set both WTFPL and MIT license in the package.json, so it'll display them both once on our page, what do you think?

**Comment by timseverien** [comment]
Oh, okay. I’ll submit a PR once v3 is out :)

I didn’t knew you could set multiple licenses in package.json. Good to know! It does seem most fitting, but I’m happy either way.

**Comment by PeterDaveHello** [comment]
@timseverien since we haven't merge this PR, you don't need to send a new one.
@pvnr0082t so let's update the license info.

**Comment by pvnr0082t** [comment]
@x09326 I have updated license info. Please help me review again, thank you.

**Pull request merged**
