### PR TITLE
Update ember-simple-auth to 0.7.3

### PR DESCRIPTION
**Pull request by NathanJang**
This package is not on npm and does not have precompiled files in its
git repository.

Files were compressed with UglifyJS.

Please advise whether or not other versions should be added.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Thanks, is it possible to add auto-update config for it? thanks!

**Comment by NathanJang** [comment]
I don't know how to add an auto-update for it. The README says auto-update only supports packages hosted on npm and Github. However, it is not hosted on npm and does not have built files in its [git repository](https://github.com/simplabs/ember-simple-auth).

**Comment by PeterDaveHello** [comment]
Okay, thank you.

**Comment by NathanJang** [comment]
Thanks! Should I add older versions as well?

**Comment by NathanJang** [comment]
On second thought, ember-simple-auth does have built files available for download on its tags page.

**Pull request merged**
