### PR TITLE
[new] [author] Please add unify@1.0.0

### PR DESCRIPTION
**Pull request by mike-feldmeier**
First time add to cdnjs.  Be gentle!

### CODE REVIEW

**Comment by mike-feldmeier** [comment]
Hmm.  Getting the following error from the CI test:

unify 
      ✗ unify: format check 
        » unify: package.json wrong format, correct one should be like this.

And the format it shows is an exact copy of the one in the repository...

**Comment by PeterDaveHello** [comment]
Nope, must be difference, but you can copy and paste.

**Comment by mike-feldmeier** [comment]
Can and did.

**Comment by PeterDaveHello** [comment]
Didn't see it yet.

**Comment by mike-feldmeier** [comment]
Closing request.  Apparently Cdnjs is too flaky to be able to accept basic requests.

**Comment by PeterDaveHello** [comment]
Sorry for the inconvenience, we need to make everything as good as possible, so that the after maintenance work will be easier.

**Comment by mike-feldmeier** [comment]
Making it as difficult as possible does not make it as "good" as possible.
I jumped through all of the undocumented hoops of your tests, only to be
denied because your test can't recognize basic string equality.  I'm done
jumping through hoops for some poorly built cdn and will not add anything
to this library due to this mismanagement.  Good idea, piss poor execution.

**Comment by PeterDaveHello** [comment]
I don't think we make it as difficult as possible, the test process also provide a valid example for you, copy and paste is easy, I just take a look at your package.json, seems you used wrong indent, that's the reason why you didn't pass the test, coding style is important, I'll keep it in the test.

**Comment by mike-feldmeier** [comment]
It was a direct copy and paste from what the test provided as was
mentioned, so no, it doesn't "provide a valid example.". Keep whatever you
want, your test and mismanagement of what should be a simple process have
removed the usefulness of what could be a helpful tool.  I will not
continue contributing to it.

**Comment by PeterDaveHello** [comment]
Not really, your indent is inconsistent if you want to confirm this issue, thought the example output been added 2 spaces of each line, will add prompt for this, and just let you know, I'll make the valid example downloadable, so it'll be easier soon.

**Comment by mike-feldmeier** [comment]
Not really sure what you're saying, since your reply was unintelligible.
I'm not going to continue a conversation with someone who can't understand
basic concepts such as copy and paste.  Your test is providing an incorrect
example that also defies your documentation on the matter (not to mention
that indentation has no effect on a json document).  As I have no intention
of continuing to contribute to your project, I really have no interest in
what changes you do to the numerous useless hoops you subject your
supporters to.

**Comment by PeterDaveHello** [comment]
That's fine. I don't think putting a non-popular lib here is actually contributing :smile:

**Comment by mike-feldmeier** [comment]
As this entire thread has shown, what a small person like you thinks is
really inconsequential :D

**Comment by PeterDaveHello** [comment]
Nope, we provide service, submit your own lib with low popularity is obviously not contributing, because this is for your own, if the popularity is high, yeah, that's contributing, because there are really users can use this service, you should not **garble** the reason why your lib not been merged. If small person was inconsequential, I don't need to spend time to talk to you here.

**Comment by mike-feldmeier** [comment]
This will be my last response.  When I closed this item, I had no idea that
there would be someone as retarded to keep drudging up the same thing over
and over.  Yes, this particular library is small, and is used only by a few
dozen sites.  As my first attempt at using this particular CDN, I purposely
picked a simple one.  Why the hell would I start with a more complex one
while learning the ins and outs of a new CDN?  As for "garbling" the reason
why the lib hasn't been merged, I have been as clear as I can possibly be:
 your test script is supplying an invalid example.  You can dance around it
with your unintelligible gibberish, but when one copy-pastes your example
into a github editor with a 2-space indent set, and the test still fails,
guess what?  Your test sucks.  Your refusal to accept, much less comprehend
this fact, makes you a small person.  Your actions over the course of this
thread make you a small person.  Instead of just patching the problem, you
go on a rampage making nonsensical ramblings, continuously drawing someone
back in who had already left.  You are small, unprofessional, and obviously
unaware of the basics.  You can take your unnecessarily complicated and
broken BS and shove it right up your ass.  I have added you to my spam
filter, so don't bother dragging me back into this again.

**Comment by PeterDaveHello** [comment]
Up to you, the indent is obviously wrong:
https://github.com/cdnjs/cdnjs/blob/cd9349e8f47d90ce14434f467c2e7c289811b224/ajax/libs/unify/package.json

```js
{ 
    "name": "unify", 
    "description": "A tiny plugin for jQuery to unify and enhance touch/mouse events", 
    "keywords": [ 
      "jquery", 
      "mouse", 
      "touch", 
      "drag", 
      "move" 
    ], 
    "version": "1.0.0", 
    "author": { 
      "name": "Mike Feldmeier", 
      "url": "http://www.mikefeldmeier.com" 
    }, 
    "license": "MIT", 
    "filename": "unify.min.js", 
    "repository": { 
      "type": "git", 
      "url": "https://github.com/mike-feldmeier/unify" 
    } 
  } 
```

**Pull request closed without merging**
