### PR TITLE
Add old versions before 2.1.2 of dimple

### PR DESCRIPTION
**Pull request by Piicksarn**
@Amomo, @maruilian11 would you please help me checkout the pr?
This is for #5768, and some files show incompatible version number, which in stub object part of content , with their origin name.
I have opened an issue for this problem [#247](https://github.com/PMSI-AlignAlytics/dimple/issues/247)
thank you! 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/PMSI-AlignAlytics/dimple
- Official website (optional, not the repository): http://dimplejs.org
- NPM package url (optional): https://www.npmjs.com/package/dimple-js
- GitHub / Bitbucket popularity (required):
  - Count of stars: 2242
  - Count of watchers: 112
  - Count of forks: 413
- NPM download stats (optional):
  - Downloads in the last day: 1
  - Downloads in the last week: 21 
  - Downloads in the last month: 70
# Essential checklist
- [ ] I'm the author of this library
  - [x] I would like to add link to the page of this library on CDNJS on website / readme
- [ ] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [x] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [ ] Has valid tags for each versions (for git auto-update)
- [ ] Auto-update setup
- [ ] Auto-update target/source is valid.
- [ ] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by maruilian11** [comment]
the issue link is not correct, please modify it.
you should add lib git repo url and npm package url if they exist.

why do you need to open the issue to ask the author to modify old file name?
what does it change?

**Comment by Piicksarn** [comment]
@maruilian11, @Amomo 
[#247](https://github.com/PMSI-AlignAlytics/dimple/issues/247) is not for modifying the file name, it's for modifying the content in the file.
Each file includes stub object and the version number recorded in this part.
After i renaming the files for #5768, the very convenience way to checkout the files' version is looking for the version number recorded inside the file(in stub object part).
However, some of version number recorded are incompatible with which named for files' name.
That is the reason for opening [#247](https://github.com/PMSI-AlignAlytics/dimple/issues/247).

Without [#247](https://github.com/PMSI-AlignAlytics/dimple/issues/247), this commit still could work, but not convenient for checking the version.

The problems u mentioned above, i have already corrected.
Would you mind to have a look? Thanks.

**Comment by maruilian11** [comment]
ok, I know about the issue.
and, what is your source of the files? where do you get them?

**Comment by Piicksarn** [comment]
under dist folder:
https://github.com/PMSI-AlignAlytics/dimple/tree/2.1.6/dist

**Comment by PeterDaveHello** [comment]
@Piicksarn can you give an example of `some of version number recorded are incompatible with which named for files' name.` ? It'll be easier to discuss.

**Comment by Piicksarn** [comment]
https://github.com/PMSI-AlignAlytics/dimple/blob/master/dist/dimple.v1.0.1.js#L7

**Comment by PeterDaveHello** [comment]
I don't think it's an issue for us, we use tag, not the content to recognize the version.

**Comment by Piicksarn** [comment]
@PeterDaveHello, yes, so that i said `without #247, this commit still could work`

**Comment by PeterDaveHello** [comment]
Should better not to touch the public published version especially we now support SRI, the case just looks link a mistake that forgot to bump the version, anyway, you can try to confirm it first.

**Comment by maruilian11** [comment]
@Piicksarn 
you should always keep your branch upon with the latest master branch.
and the author seems to forget to tag v2.1.3, could you also add it in this commit?
the commit message may change for v2.1.3.

**Comment by Piicksarn** [comment]
https://github.com/PMSI-AlignAlytics/dimple/issues/251

@maruilian11, i'd rebase the commit after the tag added. 😀

**Comment by PeterDaveHello** [comment]
@Piicksarn I didn't see you rebase it, anything wrong here?

**Comment by Piicksarn** [comment]
@PeterDaveHello, i am waiting author add the tag for 2.1.3.
I mention it above.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello Are we really need to wait author add the tag for v2.1.3?
There is no response from upstream since 10 Sep 2016.
If there is no v2.1.3 tag, I think we can just follow the upstream?

Not sure is it the better way?
Thanks.

**Comment by PeterDaveHello** [comment]
@sufuf3 I'll let you try to add it

**Pull request closed without merging**
