### PR TITLE
Add license of owl-carousel, cc #9248

### PR DESCRIPTION
**Pull request by NiniHsu**
http://owlgraphic.com/owlcarousel/

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@kennynaoh are you the mentor of this student?

**Comment by kennynaoh** [comment]
yes, I will take a look at this.

**Comment by kennynaoh** [comment]
@NiniHsu 
Please remove comma behind the license.
Thanks!

**Comment by NiniHsu** [comment]
Hi, @kennynaoh 
Please take a look.
Thank you.

**Comment by kennynaoh** [comment]
@NiniHsu 
Please use more meaningful branch name, like `owl-carousel-license`, next time.
Thanks!

**Comment by kennynaoh** [comment]
LGTM
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
