### PR TITLE
[author] angular-css v1.0.6

### PR DESCRIPTION
**Pull request by alexandercastillo**
Thanks!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Ref to #3638, would you please setup auto-update on it? thanks.

**Comment by alexandercastillo** [comment]
It's already set up, or am I missing something?
Thanks.

**Comment by PeterDaveHello** [comment]
If so, you don't need to send a PR to update this lib.

And I found it's already v1.0.6, see 383aaa3

**Comment by alexandercastillo** [comment]
Great! Thanks!

**Pull request closed without merging**
