### PR TITLE
add forerunnerdb v1.3.534

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/Irrelon/ForerunnerDB
**Watch 24
  Star 420
 Fork 31**
@Piicksarn  could u help me check this PR? thank you!
cc https://github.com/maruilian11/cdnjs/commit/5fb974eb7f459976d9dab7ce773975cdf7f9ade1#commitcomment-15424124

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity 
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@maruilian11 next time, open an issue first.

**Comment by PeterDaveHello** [comment]
@Irrelon would you please help us confirm these files need to be included are correct? Thanks.

**Comment by Irrelon** [comment]
@PeterDaveHello Yes I can confirm those files are correct. The dist folder they live in is the only folder that would make sense to host on a cdn as they are the minified and un-minified final files you would include via a script tag in your project.

**Comment by PeterDaveHello** [comment]
@Irrelon Thanks.

**Pull request merged**
