### PR TITLE
update waypoints to 3.1.1

### PR DESCRIPTION
**Pull request by simondoty**
I think I've finally got this right. package.json has auto-update configured.
If the git repo isn't structured in a way that allows for auto-update,  please manually add the project for now and give instructions for what needs to be done to get auto-update to work.

Source url: https://github.com/imakewebthings/waypoints
The code is in the lib directory, not the dist library. I'm not the repo owner, so I can't change that.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
As #3638 said, please also add auto-update config for it, thanks.

**Comment by simondoty** [comment]
There is auto-update config in the package.json file.
from last commit:

"autoupdate": {
     "source": "git",
-    "target": "git://github.com/imakewebthings/jquery-waypoints.git",
-    "basePath": "",
+    "target": "git://github.com/imakewebthings/waypoints.git",
+    "basePath": "lib",
     "files": [
-      "shortcuts/*/*.js",
-      "waypoints.min.js",
-      "waypoints.js"
+      "shortcuts/infinite.min.js",
+      "shortcuts/sticky.min.js",
+      "shortcuts/inview.min.js",
+      "jquery.waypoints.min.js",
+      "noframework.waypoints.min.js",
+      "zepto.waypoints.min.js"
     ]
   }

**Comment by simondoty** [comment]
@PeterDaveHello, I see you leave the same comment on almost everyone's PR, and people are still confused. I tried to add the auto-update config as per the discussion you linked. 
As far as I can tell it is exactly as it should be. If it's not, please let me know how so, because I can't fix something if I don't see the problem with it.

**Comment by PeterDaveHello** [comment]
I think I just pasted this message at a wrong PR, sorry.

**Comment by PeterDaveHello** [comment]
I reviewed this PR jsut now, would you please change files field to `shortcuts/*.js` and `*.js` because we also provide unminified files before, thanks.

**Comment by simondoty** [comment]
OK, made those changes

**Comment by PeterDaveHello** [comment]
Would you please squash these commits into only one commit as our document said？ Thanks.

**Comment by PeterDaveHello** [comment]
No response?

**Pull request closed without merging**
