### PR TITLE
[new] add fuckadblock@3.2.0

### PR DESCRIPTION
**Pull request by eliyastein**
My last pull request failed the test, Hope I got it right this time. Sorry I'm new to this process, open to any feedback. I've followed the instructions to the best of my ability.

FuckAdBlock is a library for checking for the presence of ad blockers. It's very useful for web publishers and has somewhat of a following.

Git repository (required): https://github.com/sitexw/FuckAdBlock
GitHub / Bitbucket popularity (required):
Count of stars: 828
Count of watchers: 61
Count of forks: 98

### CODE REVIEW

**Comment by drewfreyling** [comment]
Is this a dupe of #5153 ?

**Comment by eliyastein** [comment]
@drewfreyling - yes it is. My sincere apologies, I didn't realize that this has come up before. 

Did you guys decide not to add it? It seems that there might have been some confusion if I'm interpreting the prior conversation correctly. This library does NOT circumvent ad blockers. It allows websites to detect the presence of an ad blocker so that they can change their messaging accordingly. The ad blocker will always be successful in blocking ads despite the functionality this lib provides. This lib provides great utility to many websites, both small and large, that rely on ad revenue to stay operational.

Thanks for your consideration.

**Comment by PeterDaveHello** [comment]
@eliyastein sorry for the late reply, would you please squash/fixup the commits into only one commit? Or maybe send a new PR upon the latest master branch will be easier for you?

**Comment by eliyastein** [comment]
@PeterDaveHello - Thanks for the response. I've submitted a new PR. Closing this one now.

**Pull request closed without merging**
