### PR TITLE
Datepicker update from v0.6.5 to v1.0.3

### PR DESCRIPTION
**Pull request by sevenveils**
Pull request for issue: #13178 13178
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

## Profile of the lib

* Git repository (required): https://github.com/fengyuanchen/datepicker
* Official website (optional, not the repository):
* NPM package url (optional): https://www.npmjs.com/package/@chenfengyuan/datepicker
* License and its reference: MIT
* GitHub / Bitbucket popularity (required):
  * Count of watchers: 40
  * Count of stars: 809
  * Count of forks: 347
* NPM download stats (optional):
  * Downloads in the last day: 180
  * Downloads in the last week: 1421
  * Downloads in the last month: 4964

## Essential checklist

* [ ] I'm the author of this library
  * [ ] I would like to add link to the page of this library on CDNJS on website / readme
* [ ] This lib was not found on cdnjs repo
* [ ] Doesn't already exist / has duplicate issue and PR
* [ ] The lib has notable popularity
  * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [ ] More than 800 downloads stats per month on npm registry
* [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [ ] Has valid tags for each versions (for git auto-update)
* [ ] Auto-update setup
* [ ] Auto-update target/source is valid.
* [ ] Auto-update filemap is correct.

## Git commit checklist

* [ ] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [ ] The parent of the commit(s) in the PR is not older than 3 days.
* [ ] Pull request is sent from a non-master branch with a meaningful name.
* [ ] Separate unrelated changes into different commits.
* [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [ ] Close corresponding issue in commit message
* [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sevenveils** [comment]
@PeterDaveHello Thank you for the offer, that's very kind of you. I squashed my commits, rebased from master, and recreated the branch. Can the PR be reopened or do I need to make a new one? I'm sorry I made such a mess of this one.

**Comment by PeterDaveHello** [comment]
@sevenveils No worries at all, I'm not sure if it can be reopened, as the origin branch was deleted, I can't click the reopen button, feel free to push again, try reopen or create a new PR, no sorry needed.

**Comment by sevenveils** [comment]
@PeterDaveHello I'll open a new PR in that case. Is it possible to have this one be deleted?

**Comment by PeterDaveHello** [comment]
@sevenveils I don't think GitHub has the feature to delete a pull request, but it's fine, you can do it better next time ;)

**Pull request closed without merging**
