### PR TITLE
add materialize-autocomplete@1.0.7 w/ npm auto-update

### LINKED ISSUE #9940: [Request] Materialize-Autocomplete
**Library name: materialize-autocomplete
**Git repository url: https://github.com/icefox0801/materialize-autocomplete
**npm package url(optional): https://www.npmjs.com/package/materialize-autocomplete
**License(s): http://spdx.org/licenses/MIT
**Official homepage: https://icefox0801.github.io/materialize-autocomplete/

### PR DESCRIPTION
**Pull request by sufuf3**
npm auto-update config added, close #9940, cc @icefox0801
@kennynaoh please help me review this PR, thank you.

Pull request for issue: #9940
Related issue(s): # 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/icefox0801/materialize-autocomplete
 * Official website (optional, not the repository): https://icefox0801.github.io/materialize-autocomplete/
 * NPM package url (optional): https://www.npmjs.com/package/materialize-autocomplete
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 26
   - Count of watchers: 6
   - Count of forks: 14
 * NPM download stats (optional):
   - Downloads in the last day: 55
   - Downloads in the last week: 162
   - Downloads in the last month: 724

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by kennynaoh** [comment]
@sufuf3 Please fill in the detail information in comment table. Thanks!

**Comment by sufuf3** [comment]
@kennynaoh I updated the comment table. Please help me review this PR, thank you.

**Comment by kennynaoh** [comment]
LGTM

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
