### PR TITLE
Add license of diff_match_patch, cc #5500

### PR DESCRIPTION
**Pull request by NiniHsu**
Reference: https://code.google.com/p/google-diff-match-patch/

### CODE REVIEW

**Comment by NiniHsu** [comment]
@kennynaoh please help me check this PR.
Thank you!

**Comment by kennynaoh** [comment]
@NiniHsu you mix the two commits, please fix it. Thanks!

**Comment by kennynaoh** [comment]
LGTM
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
