### PR TITLE
Add eldarion-ajax releases 0.13.0 through 0.16.0

### PR DESCRIPTION
**Pull request by paltman**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): http://github.com/eldarion/eldarion-ajax
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference: BSD
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 99
   - Count of stars: 758
   - Count of forks: 164
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@paltman I noticed your base branch is very old(4+ years), which caused your changes conflicts with the current repository, would you please update your master branch first? If there is disk space or network concern, you can give me write access to your forked repository and I'll help you update it, thanks.

**Comment by sufuf3** [comment]
@paltman thanks for contribution.
Would you like to work on this and help improve this PR? 
If you have any question, please let us know.

Many thanks.

**Comment by sufuf3** [comment]
@paltman thanks for contribution.
Would you mind working on this and helping improve this PR?
If you have any question, please let us know.

Many thanks.

**Comment by sashberd** [comment]
See #12703 for close reason.

**Pull request closed without merging**
