### PR TITLE
[Author] Add tocas-ui@2.3.2 w/ git auto-update

### PR DESCRIPTION
**Pull request by YamiOdymel**
Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/TeaMeow/TocasUI
 * Official website (optional, not the repository): https://tocas-ui.com/
 * NPM package url (optional): https://npmjs.com/package/tocas-ui
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 13
   - Count of stars: 102
   - Count of forks: 9
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by YamiOdymel** [comment]
I think it's all good now, but I'm editing the pull request and the files via GitHub website, so I couldn't merge the commits into only one (nor edit them), I'll close this Pull Request and create another if it's a requirement.

**Comment by sufuf3** [comment]
I think this PR is fine.
Just need to squash to one commit.

Would you want to try git command to squash to one commit? 
If you want to try to use git command but worried cdnjs's repo is too huge. You could use `sparseCheckout`, it lets you check out only the files you want. Here is the tutorial: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md

Or, I can help you squash to one commit. 😄

**Comment by YamiOdymel** [comment]
I tried it before the PR was created, and .. 2 GB is still a little bit large for me. 

I am not pretty good at Git, I'm afraid I'll do something wrong and need to re-clone the repository (That would be a nightmare 😨).

It would be great if you can help me to squash the commits, do I have to create the permission for you to assign my forked repository? How do I help you?

**Comment by sufuf3** [comment]
I'll help you squash it.
I think you don't need to create the permission.

Just make a confirm, may I ask that which auto-update do you like to use, npm or git?
Because I found that there are 19 releases versions from GitHub, and 1 releases versions from npm.
You use git auto-update in `package.json`, but the commit message show npm auto-update.

If you want to use git auto-update, I can help you squash the commit message and modify the commit message from `npm` to `git`.

If you want to use npm auto-update, I think the `package.json` need to modify the auto-update part.

PS. As usually, we prefer to use more releases versions as the auto-update option.
But if you think npm is stable than GitHub repo, then npm is a good choice.

**Comment by YamiOdymel** [comment]
Oops, I typed `npm auto-update` in the title because people are doing the same (Sorry for that).

Please help me to change the commit message from `npm` to `git` since I always update the project on GitHub, thank you.

**Comment by sufuf3** [comment]
@cdnjs/library-reviewer 
Please help review this PR, Thank you.

**Pull request merged**
