### PR TITLE
add license github-repo-widget , cc #9248

### PR DESCRIPTION
**Pull request by hare1039**
https://github.com/JoelSutherland/GitHub-jQuery-Repo-Widget/blob/master/LICENSE

### CODE REVIEW

**Comment by hare1039** [comment]
@kennynaoh please check

**Comment by kennynaoh** [comment]
@hare1039
Please mention issue number in commit message next time, like this PR title
Thanks!

**Comment by kennynaoh** [comment]
LGTM
cc @cdnjs/intern2

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
