### PR TITLE
add show-your-terms@1.1.1 w/ npm autoupdate

### LINKED ISSUE #8381: [Request] Add Show your terms!
**Library name:** Show your terms!
**Git repository url:** https://github.com/kandebonfim/show-your-terms
**npm package url(optional):** https://www.npmjs.com/package/show-your-terms
**License(s):** MIT License
**Official homepage:** https://kandebonfim.github.io/show-your-terms/
**Wanna say something? Leave message here:** Show your terms! had 85 downloads in the last week and some people are asking me for a more reliable cdn. :D

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8381 
@x09326 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/kandebonfim/show-your-terms
 * Official website (optional, not the repository): https://kandebonfim.github.io/show-your-terms/
 * NPM package url (optional): https://www.npmjs.com/package/show-your-terms
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 127
   - Count of watchers: 5
   - Count of forks: 9
 * NPM download stats (optional):
   - Downloads in the last day: 4
   - Downloads in the last week: 6
   - Downloads in the last month: 23

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8381, cc @kandebonfim

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
No homepage info in package.json?

**Comment by pvnr0082t** [comment]
@PeterDaveHello Because I think that just a demo. How do you think?

**Comment by PeterDaveHello** [comment]
@pvnr0082t We can use it.

**Comment by pvnr0082t** [comment]
@x09326 I have added homepage info. Please help me review again, thank you.

**Pull request merged**
