### PR TITLE
[new] componentjs

### PR DESCRIPTION
**Pull request by AuspeXeu**
Added componentjs

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Thanks!

**Comment by AuspeXeu** [comment]
@PeterDaveHello I guess you need to re-index the search again ;)

**Comment by PeterDaveHello** [comment]
ok sure ...

**Comment by PeterDaveHello** [comment]
Done.

**Comment by PeterDaveHello** [comment]
Please let me know if you still have problem @AuspeXeu, thanks!

**Comment by AuspeXeu** [comment]
Like a charm, thanks!

**Pull request merged**
