### PR TITLE
add dragula v2.1.2 with git autoupdate, close #5175

### LINKED ISSUE #5175: [Request] dragula
**Library name:** dragula
**Git repository url:** https://github.com/bevacqua/dragula
**npm package url(optional):**  https://www.npmjs.com/package/dragula
**Official homepage:** http://bevacqua.github.io/dragula
**Wanna say something? Leave message here:**
Drag and drop library

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by maruilian11**
@Amomo could u plz help me check this pr from #5175 . thx~

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Any updates?

**Comment by Amomo** [comment]
@maruilian11 sorry!! I am late for checking this PR.
I think your commit is fine. Could you rebase this PR to the latest branch?

**Comment by maruilian11** [comment]
@Amomo never mind~ could u help me check again?

**Comment by Amomo** [comment]
Good! The commit meets latest branch.
@PeterDaveHello I think this PR is well.

**Comment by PeterDaveHello** [comment]
:facepunch:

**Pull request merged**
