### PR TITLE
Update package.json for jquery.lazy

### PR DESCRIPTION
**Pull request by eisbehr-**
The Library is already available on cdnjs, I'll just added the new plugin file to cdn too.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@eisbehr- what about using this single rule: `"jquery*.js",`?

**Comment by eisbehr-** [comment]
Yes, this would be a solution too! :)

Is it even possible, and allowed by cdnjs, to add `"plugins/jquery*.js"` too?
With this even all plugins would be hosted as single files.

**Comment by PeterDaveHello** [comment]
@eisbehr- no problem, but just please don't add the famous "jQuery" in it :smile:

**Comment by PeterDaveHello** [comment]
Another method is to create `dist` folder for distribution purpose, and we can use pattern `"**/*"` to grab all the files in it.

**Comment by eisbehr-** [comment]
Okay, thanks. I'll create a new PR tomorrow adding those and change it to mask usage. 

A dist folder is no option for now, because I don't want to change the stucture in a working repo. ;)

**Comment by PeterDaveHello** [comment]
@eisbehr- Okay, thanks.

**Pull request closed without merging**
