### PR TITLE
add fakeLoader.js@1.1.0

### PR DESCRIPTION
**Pull request by onlineth**
PR for https://github.com/cdnjs/cdnjs/issues/8337

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/joaopereirawd/fakeLoader.js
- Official website (optional, not the repository): http://joaopereirawd.github.io/fakeLoader.js/
- NPM package url (optional):
- GitHub / Bitbucket popularity (required):
  - Count of stars: 395
  - Count of watchers: 30
  - Count of forks: 127
- NPM download stats (optional):
  - Downloads in the last day:
  - Downloads in the last week:
  - Downloads in the last month:
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [x] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [ ] Has valid tags for each versions (for git auto-update)
- [ ] Auto-update setup
- [ ] Auto-update target/source is valid.
- [ ] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@onlineth Thanks.

**Comment by onlineth** [comment]
Sure thing - I'd like to help out more, does this PR along with the commit look correct/using best practices?

**Comment by PeterDaveHello** [comment]
hmmm ... I have concerns have the correct version, since there is no version info in the repo's git tag or the minified js file, would you please confirm with the author? For the best practice, we'll also need to setup auto-update for the lib so that the future versions can be automatically added, currently we support npm or git tag auto-update.

**Comment by onlineth** [comment]
@PeterDaveHello So, I believe that the minified script does not have the version included but the [other unminified version](https://github.com/joaopereirawd/fakeLoader.js/blob/master/fakeLoader.js) does. As far as the automatic update system, I have contacted the author asking for him to either to add a package.json file or a tag on the repo. Just a quick question, if a library request cannot support autoupdate (like currently this one), should I not do a PR for it?

**Comment by PeterDaveHello** [comment]
If the lib is popular enough, we'll still add it, but maybe we could wait for author's comment first.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Pull request closed without merging**
