### PR TITLE
add currency-flags@0.3.0 w/ git auto-update

### PR DESCRIPTION
**Pull request by sufuf3**
cc #9920, cc @oliverviljamaa
@kennynaoh please help me review this PR, thank you.

Pull request for issue: #9920 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/transferwise/currency-flags
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 6
   - Count of stars: 3
   - Count of forks: 0
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by oliverviljamaa** [comment]
Good job!
We hope to get more momentum on it, lots of currencies are still missing.

**Comment by kennynaoh** [comment]
@PeterDaveHello The popularity is not enough. Should we wait or it's fine to add? Thanks!

**Comment by PeterDaveHello** [comment]
Don't we confirm the popularity before sending a PR?

**Comment by kennynaoh** [comment]
@sufuf3 Please confirm the popularity before sending a PR next time.

**Comment by sufuf3** [comment]
OK, sorry about that.

**Comment by PeterDaveHello** [comment]
I'll accept this PR this time, make sure everything is good then I'll review it.

**Comment by kennynaoh** [comment]
@sufuf3 I think this PR is ok. Please rebase to the latest master branch.

**Comment by sufuf3** [comment]
@kennynaoh please help me review this PR, thank you.

**Comment by PeterDaveHello** [comment]
Please add some more keywords next time.

**Pull request merged**
