### PR TITLE
Added iGrowl w/ git auto-update #10205

### PR DESCRIPTION
**Pull request by elhadiahmed**
Pull request for issue: #10205
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:
   - Count of stars:
   - Count of forks:
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@elhadiahmed do you need help about how to fix the error in CI?

**Comment by elhadiahmed** [comment]
@PeterDaveHello yes please, is it because I cloned the repo 4 days before I pushed ? I never used rebase before.

**Comment by elhadiahmed** [comment]
from what I understood from the git-rebase documentation is that I should do a `git rebase master Issue10205` and push again, correct ?

**Comment by PeterDaveHello** [comment]
@elhadiahmed correct, you should pull you master branch to the latest, and do the rebase `git rebase master Issue10205`

**Comment by elhadiahmed** [comment]
@PeterDaveHello for some reason, the rebase command took few hours to finish and at the end it gave an error `fatal: cannot write output: No space left on device` would it be acceptable to pull master again and create a new branch and commit the package.json file to it and create a new pull request ?

**Comment by PeterDaveHello** [comment]
@elhadiahmed it's fine, but I wonder if you didn't enable sparseCheckout?

**Comment by elhadiahmed** [comment]
@PeterDaveHello I actually did, and I spent around 8 hours checkout the 4.5 GB repo because the speed here in Egypt is not the best, but I am working on upgrading it soon

**Comment by PeterDaveHello** [comment]
@elhadiahmed If you enabled the spraseCheckout properly, I think it'll take about 3GB disk space, many there is something wrong?

**Comment by elhadiahmed** [comment]
My sparse-checkout file looks like this
```
/build
/documents
/test
/tools
/MIT-LICENSE
/hooks
/MAINTAINERS
/*.yml
/*.md
/*.json
/*.sh
/*.js
/ajax/libs/jquery/*
```

**Comment by PeterDaveHello** [comment]
@elhadiahmed Looks fine, can you make sure there is nothing else but jquery under ajax/libs? Thanks

**Comment by elhadiahmed** [comment]
Yes

```
➜  open_source ll -a cdnjs/ajax/libs
total 0
drwxr-xr-x   3 hadi  staff   102B Jan 22 15:59 .
drwxr-xr-x   3 hadi  staff   102B Jan 21 00:19 ..
drwxr-xr-x  71 hadi  staff   2.4K Jan 21 00:19 jquery
```

**Comment by PeterDaveHello** [comment]
@elhadiahmed hmmmm ... that's odd that you need 4GB on your disk ...

**Pull request closed without merging**
