### PR TITLE
[new] Adds all versions of library co

### PR DESCRIPTION
**Pull request by boopathi**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please read the document first for what you need to send a PR, thanks.

**Comment by boopathi** [comment]
So this is a new library addition, and I would append the [new] tag to the PR. 

Regarding npm auto-update, The library (github repo) maintains `index.js` as the entry point and does not have any `dist/<lib.js>` or `dist/lib.min.js`. So I browserified `index.js` and added them as `co.js`.

What is `npmFilemap.files`. Do you copy all the `npmFilemap.files` to `//<cdnjs>/<lib>/<version>/<files>` ?

**Comment by PeterDaveHello** [comment]
Yes, and please tell me where did you get these files from, add auto-update if is possible, thanks.

**Comment by boopathi** [comment]
The repository information is mentioned in `package.json` .

Repo: https://github.com/tj/co 
npm: https://www.npmjs.com/package/co 

I did `browserify index.js --standalone co > co.js` and minified using `uglify`

**Comment by PeterDaveHello** [comment]
Touch its filename is not a good idea, please leave it alone.

**Comment by boopathi** [comment]
I didn't get that!

**Comment by PeterDaveHello** [comment]
Please don't change its filename.

**Comment by PeterDaveHello** [comment]
Any updates?

**Comment by boopathi** [comment]
Renamed files!

**Comment by PeterDaveHello** [comment]
Because this pr is a little bit old, would you please rebase/sync with our latest master branch?
And please squash these commits into only one commit, thanks!

**Comment by PeterDaveHello** [comment]
I did this manually.

**Pull request closed without merging**
