### PR TITLE
[new] add angular-xeditable@0.1.9 with git auto-update, close #5283

### LINKED ISSUE #5283: [Request] angular-xeditable
Library name: angular-xeditable

Git repository url: https://github.com/vitalets/angular-xeditable

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 , I add a new lib with git auto-update from the request #5283
repo: https://github.com/vitalets/angular-xeditable
The library has provided a minified css file, so I didn't add one.
And, because they don't provide keywords, I pick some words from readme.md.
Would you mind checking this PR for me? Thank you~ :-)

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `76`, Star `1,236`, Fork `273`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by maruilian11** [comment]
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity 
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

@PeterDaveHello i think it's ok.

**Comment by Amomo** [comment]
@maruilian11 I have rebased it~
Would you mind checking again? Thank you😆

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Comment by PeterDaveHello** [comment]
Should rebase ...

**Comment by maruilian11** [comment]
@PeterDaveHello sorry, but when i checked it, it was rebased not over 24h.

**Comment by PeterDaveHello** [comment]
As you're in @cdnjs/intern, always rebase when you modify commits.

**Comment by Amomo** [comment]
Oh......sorry. I will remember it. 🙋

**Pull request merged**
