### PR TITLE
Add plates@0.4.11 w/ npm auto-update

### LINKED ISSUE #8706: [Request] Add plates
**Library name:** plates
**Git repository url:**https://github.com/flatiron/plates
**npm package url(optional):** 
**License(s):**MIT
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by Piicksarn**
@Amomo , @maruilian11  this pr close #8706
Thanks!

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/flatiron/plates
 * Official website (optional, not the repository): None
 * NPM package url (optional): https://www.npmjs.com/package/plates
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 808
   - Count of watchers: 33
   - Count of forks: 67
 * NPM download stats (optional):
   - Downloads in the last day: 4
   - Downloads in the last week: 96
   - Downloads in the last month: 373

# Essential checklist
 * [ ] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
no map file for the minified file?

**Comment by PeterDaveHello** [comment]
@Piicksarn you should use the assignee feature to assign the PR.

**Comment by Piicksarn** [comment]
@Amomo , @maruilian11, I need your help for checking the pr.
Thank you!

**Comment by PeterDaveHello** [comment]
Is this an official npm package?

**Comment by Amomo** [comment]
@PeterDaveHello I think it is an official npm package.
The owner of [plates's npm package](https://www.npmjs.com/package/plates), __[V1](https://www.npmjs.com/~V1)__, is a member of flatiron/plates, his username on GitHub is __3rd-Eden__.

**Comment by Piicksarn** [comment]
@PeterDaveHello, I saw there's a link to the git repo of library on NPM package url, furthermore, i could install the lib when i used `npm install plates`, so that i believed it's an official npm package.
Is it a wrong checkout step for the official npm package?

**Comment by PeterDaveHello** [comment]
@Piicksarn what you are talking about definitely can not prove that the npm package is published officially, please confirm that precisely.

**Comment by maruilian11** [comment]
as @Amomo said, I think the npm package is official, too.
I think this PR is ok. @Piicksarn could you rebase it upon the latest master? thanks.

**Pull request merged**
