### PR TITLE
[maintainer] Update to repo location and enabling auto update

### PR DESCRIPTION
**Pull request by rhubarbselleven**
Updating repository URL due to project ownership change and enabled auto update

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@rhubarbselleven Thanks

**Comment by PeterDaveHello** [comment]
@rhubarbselleven please don't change the version here, we will update it after merge this PR, thanks.

**Comment by rhubarbselleven** [comment]
Thanks @PeterDaveHello did you want me to update this PR minus the version change?

**Comment by PeterDaveHello** [comment]
> Thanks @PeterDaveHello did you want me to update this PR minus the version change?

Yes, thanks. It'll be great if you can also rebase this branch with our latest master branch.

**Comment by rhubarbselleven** [comment]
Hey @PeterDaveHello, finding it difficult to work with the size of this repo (am remote atm). 

I'll simply re-fork and open a new PR with the changes.

**Comment by PeterDaveHello** [comment]
That's fine, thanks @rhubarbselleven

**Pull request closed without merging**
