### PR TITLE
[new]Add trumbowyg v1.1.7 with git autoupdate, close #5058.

### LINKED ISSUE #5058: [Request] Add Trumbowyg
Project GitHub:
https://github.com/Alex-D/Trumbowyg

### PR DESCRIPTION
**Pull request by Piicksarn**
@maruilian11, I add the library again.
Would you please take a look on it?
The PR before : #5062 
Thank you!

### CODE REVIEW

**Comment by maruilian11** [comment]
@Piicksarn i can't find the <code>/css</code> file in origin repo, and i think we need all files except <code>langs</code>, so maybe you should include others in filemap field, the maintainer said we should keep the structure under file <code>dist</code> means we should create same file like origin repo, in this case, we should create <code>plugins</code> <code>ui</code> and other folder under them and put <code>.js</code> <code>.css> in them like origin. filemap field can still be <code>***/**</code> (not in this case) won't be matter. haha do you understand?

**Comment by Piicksarn** [comment]
@maruilian11, would you mind to have a look at the pr?

**Comment by maruilian11** [comment]
@Piicksarn i think we don't need `langs`.

**Comment by Piicksarn** [comment]
@maruilian11, would you mind to check it again?
thank you!!

**Comment by maruilian11** [comment]
@Piicksarn why not use `plugins/**/*.+(css|js|png)`, too?

**Comment by Piicksarn** [comment]
@maruilian11, how do you think about the pr now? :)

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Comment by PeterDaveHello** [comment]
Why not `**/*` ?

**Comment by Piicksarn** [comment]
@maruilian11, i have the pr rebased to the master.
would you mind to have a look again? Thank you ! :smiley:

**Comment by maruilian11** [comment]
@Piicksarn i think you should also add files under `langs`, sorry i thought they are unnecessary.

**Pull request closed without merging**
