### PR TITLE
add add-to-homescreen@3.2.2 w/ git autoupdate

### LINKED ISSUE #8025: [Request] Add add-to-homescreen
**Library name: add-to-homescreen** 
**Git repository url: https://github.com/cubiq/add-to-homescreen**
**npm package url(optional):** 
**License(s): MIT License**
**Official homepage:http://cubiq.org/add-to-home-screen**
**Wanna say something? Leave message here:
One of the famoust library for adding webapp to the homescreen**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/34489534-request-add-add-to-homescreen?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8025 
@x09326 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/cubiq/add-to-homescreen
- Official website (optional, not the repository): https://github.com/cubiq/add-to-homescreen
- NPM package url (optional):
- GitHub / Bitbucket popularity (required):
  - Count of stars: 1479
  - Count of watchers: 91
  - Count of forks: 338
- NPM download stats (optional):
  - Downloads in the last day:
  - Downloads in the last week:
  - Downloads in the last month:
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [ ] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [ ] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

close #8025, cc @cubiq

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Is it possible to discuss with the author about providing `dist` folder? Since it's a little bit strange to use src in the path but the minified file.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello there is no response from the upstream since 27 Jun 2016.
Should we still wait for the answer?
Or continue work on this PR?

Thank you.
cc @pvnr0082t

**Comment by PeterDaveHello** [comment]
It looks like we can use `src` and `style` as basePath? Maybe don't even need `imgs`.

**Comment by sufuf3** [comment]
That‘s what I thought too.
So, how can I improve this PR?
I can't help modify this PR. 😞

**Comment by PeterDaveHello** [comment]
Let's close this one.

**Pull request closed without merging**
