### PR TITLE
point backbone-react-component.js to backbone-react-component-min.js

### PR DESCRIPTION
**Pull request by maruilian11**
@LeaYeh could u plz help me check this pr from #5195? thx.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
This is not pr **from** #5195

**Comment by LeaYeh** [comment]
i think it is fine, but you should modify your comment.

**Comment by maruilian11** [comment]
@LeaYeh i have changed the commit msg, could u help me check again? thank u~

**Comment by maruilian11** [comment]
@Piicksarn could u  help me check this PR? i think LeaYeh is busy currently. thank u very much :)

**Comment by LeaYeh** [comment]
i think it is fine.

**Comment by maruilian11** [comment]
@PeterDaveHello is that ok?

**Pull request merged**
