### PR TITLE
Added jquery.scroll4ever using the new way

### PR DESCRIPTION
**Pull request by luanlmd**
There we go.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Would you please also add its real files as the first commit to add a lib? So that you can pass the test.

**Comment by luanlmd** [comment]
Do I need to add the files just the first time if I'm using the autoupdate method? And should I redo the initial commit or sync the upstream repo and do another commit to add the files?

**Comment by PeterDaveHello** [comment]
Just the first time, you can do it in the same commit, and use force push to update this PR, thanks!

**Comment by luanlmd** [comment]
Looks like it is all right now.

**Comment by PeterDaveHello** [comment]
:+1:

**Pull request merged**
