### PR TITLE
add i18next-locize-backend v0.1.1

### LINKED ISSUE #7737: [Request] Add i18next-locize-backend
**Library name:** i18next-locize-backend
**Git repository url:** https://github.com/locize/i18next-locize-backend
**npm package url(optional):** https://www.npmjs.com/package/i18next-locize-backend
**License(s):** https://github.com/locize/i18next-locize-backend/blob/master/LICENSE (MIT)
**Official homepage:** http://i18next.com/docs/ecosystem/#backends
**Wanna say something? Leave message here:** thx a lot

### PR DESCRIPTION
**Pull request by dannyxx001**
PR for #7737 
@x09326 please help me review this PR, thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/locize/i18next-locize-backend
 * Official website (optional, not the repository): http://i18next.com/docs/ecosystem/#backends
 * NPM package url (optional): https://www.npmjs.com/package/i18next-locize-backend
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 1
   - Count of watchers: 2
   - Count of forks: 0
 * NPM download stats (optional):
   - Downloads in the last day: 23
   - Downloads in the last week: 252
   - Downloads in the last month: 454

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

with npm autoupdate config

close #7737, cc @jamuhl

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
The files looks the same as the files under `dist/umd` I wonder maybe we should set base path to `dist/umd/` and grab all files (pattern `**/*`) from it, @dannyxx001 have you checked the file structure in the old versions? Are they all have `dist/umd/`? Or they just have `i18nextLocizeBackend(.min).js` in the root? Or both? Maybe we could discuss with its author which one looks better from the author side.

**Comment by dannyxx001** [comment]
The files are truly the same under `dist/umd` and root. However, I don't know how to check the older version in npm. I only check the version in github, but there is no `dist` in github. The older version all put the files in the `root` in github. So I think I will ask author later.

**Comment by PeterDaveHello** [comment]
@dannyxx001 npm install pkgname@version

**Comment by dannyxx001** [comment]
@PeterDaveHello Yeah, all the version except v0.0.1 (first version) has a `dist` directory, and the files in `dist/umd` and `root` are all the same.

**Comment by PeterDaveHello** [comment]
@dannyxx001 hmmmm ... great, i prefer using dist folder.

**Comment by dannyxx001** [comment]
OK, I had updated it.

**Comment by x09326** [comment]
@PeterDaveHello 
I think this PR is okay, please help me review it, thanks.

**Pull request merged**
