### PR TITLE
add license to datejs, cc #5500

### PR DESCRIPTION
**Pull request by qwe19272375**
https://github.com/datejs/Datejs/blob/master/LICENSE
https://github.com/datejs/Datejs/blob/master/package.json

### CODE REVIEW

**Comment by qwe19272375** [comment]
@nolsherry Please help me review it, thanks.

**Comment by nolsherry** [comment]
LGTM 
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM

**Pull request merged**
