### PR TITLE
[new] add jquery-tiny-pubsub@0.7.0

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 this PR is for #6199.
I add `jquery-tiny-pubsub` at `v0.7.0` and add `git` auto-update config in its package.json.

Would you mind checking this PR for me? Thank you~ :-D

# Profile of the lib
 * Git repository (required): https://github.com/cowboy/jquery-tiny-pubsub
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 50
   - Count of watchers: **720**
   - Count of forks: 178

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by maruilian11** [comment]
the popularity seems wrong😂

**Comment by maruilian11** [comment]
@Amomo you miss `homepage`, and i think if you can also add `dependencies`, it would be better  :)

**Comment by Amomo** [comment]
@maruilian11 I have add `homepage`. Could you help me checking again? thanks.

**Comment by PeterDaveHello** [comment]
No need to manually add a homepage to the GitHub repository ... please remove it.

**Comment by Amomo** [comment]
ok, I removed it.
@maruilian11 Could you help me checking this PR again? Thanks! :-D

**Comment by maruilian11** [comment]
@PeterDaveHello don't we need `homepage` to point to the lib repo on website?
@Amomo sorry for my late, could you rebase this branch upon our latest master?

**Comment by PeterDaveHello** [comment]
@maruilian11 There is repository link on the lib page.

**Comment by maruilian11** [comment]
@PeterDaveHello so it doesn't depend on `homepage`, ok.

**Comment by PeterDaveHello** [comment]
So what's the report/status of this review ?

**Comment by maruilian11** [comment]
>@Amomo sorry for my late, could you rebase this branch upon our latest master?

@PeterDaveHello wait for update.

**Comment by PeterDaveHello** [comment]
Update for what?

**Comment by maruilian11** [comment]
@Amomo i think this PR is ok, could you rebase this branch upon our latest master branch, thank you.

**Comment by Amomo** [comment]
@maruilian11 could you help me checking this PR again? thanks~

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Pull request merged**
