### PR TITLE
[new][author] HIW JavaScript API v5.0.0 and v5.0.1

### PR DESCRIPTION
**Pull request by JoshMcCullough**
HIW JavaScript API v5.0.0 and v5.0.1 - http://developers.healthindicators.gov

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
The parent of your commit was too old, would you please rebase/sync with our latest master branch, thanks.

**Comment by JoshMcCullough** [comment]
@PeterDaveHello Sorry about that, updated.

**Comment by PeterDaveHello** [comment]
hmmmm ... you should use rebase but not merge.

**Comment by JoshMcCullough** [comment]
@PeterDaveHello Apologies, again - PR# 4640 is ready.

**Pull request closed without merging**
