### PR TITLE
update floatlabels.js to 1.0.0 head

### PR DESCRIPTION
**Pull request by RoryStolzenberg**
source: https://github.com/clubdesign/floatlabels.js/ (version from .js files)

(no npm repo or git tags)

Originally added in #2946 / 9ac1ef2

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
If there is no npm version or git tag, how can we know this is v1.0?

**Comment by RoryStolzenberg** [comment]
Fair question – the project doesn't seem to have ever changed its designation from 1.0. How should updates be handled for an unversioned library? Do I need to just pull request version numbers on the project?

**Comment by PeterDaveHello** [comment]
I think we should open an issue there, and see what the author think.

**Comment by PeterDaveHello** [comment]
Hello, any updates here? Thanks.

**Comment by RoryStolzenberg** [comment]
No activity on that repo in quite a while. Bumped the request and offered to help maintain, we'll see if we get any movement.

**Comment by sufuf3** [comment]
@PeterDaveHello there is no response about adding git tag from upstream 2 years ago.
And CDNJS already host v1.0 https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/floatlabels.js/1.0.0/floatlabels.js
Although I think the files we host is different from this v1.0 commit https://github.com/probots-io/floatlabels.js/tree/99617b972850c80beaca4eb67a0d3bb91c229d83
So should we still wait for upstream and open this PR?
Thank you.

**Comment by PeterDaveHello** [comment]
Let's close this until there is a static version reference from upstream, before that, we do nothing on this.

**Pull request closed without merging**
