### PR TITLE
[new] Add new chessboard.js

### LINKED ISSUE #12943: [request] chessboard.js
**Name**: chessboard.js

**License**: MIT

**Webpage**: http://chessboardjs.com/ 

**Source code**: https://github.com/oakmac/chessboardjs/

**Download**: http://chessboardjs.com/releases/0.3.0/chessboardjs-0.3.0.zip

**Git repository URL**: https://github.com/oakmac/chessboardjs.git

If I'm missing anything, please let me know.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/63172569-request-chessboard-js?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by akiraheid**
Close #12943 cc @oakmac

# Pull request template for new library

Pull request for issue: #12943 
Related issue(s): # #
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

## Profile of the lib

* Git repository (required): https://github.com/oakmac/chessboardjs.git
* Official website (optional, not the repository): https://chessboardjs.com
* License and its reference: MIT
* GitHub / Bitbucket popularity (required):
  * Count of watchers: 83
  * Count of stars: 1082
  * Count of forks: 220

## Essential checklist

* [ ] I'm the author of this library
  * [ ] I would like to add link to the page of this library on CDNJS on website / readme
* [x] This lib was not found on cdnjs repo
* [x] Doesn't already exist / has duplicate issue and PR
* [x] The lib has notable popularity
  * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [ ] More than 800 downloads stats per month on npm registry
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [x] Has valid tags for each versions (for git auto-update)
* [x] Auto-update setup
* [x] Auto-update target/source is valid.
* [x] Auto-update filemap is correct.

## Git commit checklist

* [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [x] The parent of the commit(s) in the PR is not older than 3 days.
* [x] Pull request is sent from a non-master branch with a meaningful name.
* [x] Separate unrelated changes into different commits.
* [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [ ] Close corresponding issue in commit message
* [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by akiraheid** [comment]
Is the filename property right? I wasn't sure what it was supposed to be since chessboard.js has a CSS file, JS file, and image files.

**Comment by akiraheid** [comment]
@extend1994 Sorry, this is my first PR for the repo. Is that the preferred method? I thought the git auto update automatically pulled the official releases from the git repo.

**Comment by extend1994** [comment]
@akiraheid You're right, this library is just a special case because it wasn't released by git tags :) I can help/show you how to deal with it.
It's very welcome if you want to make other contribution (add other libraries).
What do you think?

**Comment by extend1994** [comment]
@akiraheid Your guessing is basically correct.
Only at step 1, you only need to add existed unminified/minified files in the releases folders, for example, `chessboardjs/website/releases/0.2.0/css/chessboard-0.2.0.css` & `chessboardjs/website/releases/0.2.0/css/chessboard-0.2.0.min.css`. You will also need to rename the files to trim version number according to https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-common-conventions
> Filenames should not include a version number and be lowercase.
This is OK: useful.min.js, but this is not: useful-2.0.1.min.js.

Here are the answers to your questions:
- Yes, you need to put image assets in each version folder
- You don't need to include `LICENSE.txt`

**Comment by oakmac** [comment]
Is there something I can do as the owner of the chessboardjs repo to make this easier / simpler?

**Comment by akiraheid** [comment]
@extend1994 I've added the released versions

**Comment by akiraheid** [comment]
Bump

**Comment by MattIPv4** [comment]
Closing, source repo deleted.

**Pull request closed without merging**
