### PR TITLE
Add git autoupdate config in gumby

### PR DESCRIPTION
**Pull request by LeaYeh**
@maruilian11  could you plz help check this commit?

### CODE REVIEW

**Comment by maruilian11** [comment]
i think we also need img, and  it seems that we don't need to include "gumby.min.js" twice.

**Comment by maruilian11** [comment]
i think it's ok. @PeterDaveHello

**Comment by PeterDaveHello** [comment]
What's the reason why too grab a empty css file?
https://github.com/GumbyFramework/Gumby/blob/2.6.4/css/style.css

Do we need these all files?
https://github.com/GumbyFramework/Gumby/tree/2.6.4/js/libs

I think you should ask its author when you don't really know what files should be added.

**Comment by PeterDaveHello** [comment]
Any updates?

**Pull request closed without merging**
