### PR TITLE
[Author] Add numbro v1.11.1 w/ repo & author info update

### PR DESCRIPTION
**Pull request by BenjaminVanRyseghem**
numbro repo has been moved, thus the auto update is failing.

I manually updated the package.json to fix it.

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
it's slightly a pain to clone 3Go of data for that...

**Comment by PeterDaveHello** [comment]
@BenjaminVanRyseghem you can do it on GitHub web GUI.

**Comment by BenjaminVanRyseghem** [comment]
@PeterDaveHello AFAIK you can't edit a file and add another one in one single commit in the web ui 😕 

I'll wait a bit, and everything will be easier :smile:

**Comment by PeterDaveHello** [comment]
@BenjaminVanRyseghem you can do it in multiple commit, and we'll squash them. On the other hand, you can create a new pull request with the correct content.

**Comment by BenjaminVanRyseghem** [comment]
@PeterDaveHello I'll upload the file in a separate commit if you plan to squash them (I'm only around 22% of cloning after roughly an hour)

**Comment by PeterDaveHello** [comment]
@BenjaminVanRyseghem I don't think you need to clone it, just commit again, I'll squash it.

**Comment by BenjaminVanRyseghem** [comment]
finally :smile:

**Pull request merged**
