### PR TITLE
add Md-data-table w/ npm auto-update

### LINKED ISSUE #8613: [Request] Add mdDataTable
**Library name: mdDataTable 
**Git repository url: https://github.com/iamisti/mdDataTable
**npm package url(optional): mdDataTable
**License(s): MIT
**Official homepage: https://github.com/iamisti/mdDataTable

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by x09326**
PR for #8613 
@kennynaoh @pvnr0082t please help me review it, thanks.

Manually add the old versions from git repo because npm auto-update can't
get some of the old versions

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/iamisti/mdDataTable
 * Official website (optional, not the repository):
 * NPM package url (optional):https://www.npmjs.com/package/md-data-table
 * GitHub / Bitbucket popularity (required):
   - Count of stars:301
   - Count of watchers:35
   - Count of forks:67
 * NPM download stats (optional):
   - Downloads in the last day:50
   - Downloads in the last week:113
   - Downloads in the last month:372

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8613, cc @iamisti

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@x09326 Why did you do the minify without generating `.map` file? And some of `md-data-table-templates.js` in old versions don't be minified.

**Comment by x09326** [comment]
@pvnr0082t 
I have generated map file and I updated the latest version 1.6.9.
Please help me review it.

**Comment by pvnr0082t** [comment]
You don't fetch `md-data-table-templates.js` in old versions but v1.6.9. Please add it and minify it. Thanks.

**Comment by x09326** [comment]
@pvnr0082t 
I have added it.
Please help me review it again, thanks.

**Comment by pvnr0082t** [comment]
@x09326 But you don't minify them. I think they should be minified.

**Comment by x09326** [comment]
@pvnr0082t 
I have rebased it.
And I think they don't need to be minified.
Please help me review it.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM

**Comment by kennynaoh** [comment]
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
is `v.0.2.5` a valid version?
I found `ajax/libs/md-data-table/.0.2.5/md-data-table-templates.js`

**Comment by x09326** [comment]
@PeterDaveHello 
Yes, it is a valid version.
Sorry I didn't notice that.
I added other files of the version and rebased with the latest branch.

**Comment by PeterDaveHello** [comment]
@x09326 start with a dot is very strange, I don't think it's valid.

**Comment by x09326** [comment]
@PeterDaveHello 
Okay, I will open an issue to confirm that.

**Comment by PeterDaveHello** [comment]
Actually I doubt if it's just a typo of v0.2.5, let's see if the author has some idea.

**Comment by iamisti** [comment]
Hi Guys, I'm the author of the lib, please don't use the one starts with `v.0...`. It was just a mistake by me, and anyway nobody is using that version, since it was just a very early release.

**Comment by iamisti** [comment]
One question: Will it  be automatically updated, once I'll have newer version? Or how does that work?

**Comment by PeterDaveHello** [comment]
@iamisti yes we have auto-update mechanism and will fetch the content under `dist` folder in this case.

**Comment by x09326** [comment]
@pvnr0082t @kennynaoh 
I have removed the ```v.0.2.5``` version.
Please help me review it, thanks.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
@pvnr0082t @kennynaoh please make sure the min file and map file part is 100% correct!

**Comment by pvnr0082t** [comment]
I think it's ok this time.

**Comment by kennynaoh** [comment]
@x09326 
Because the author released the latest version `v1.7.0`  two days ago.
Please update it in the first commit.
Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh It's okay not to do that if auto-update will work on it.

**Comment by kennynaoh** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
`main.css` looks the same as `md-data-table-style.css`, we don't need to add them twice.

**Comment by x09326** [comment]
@kennynaoh @pvnr0082t 
I have deleted ```main.css```.
Please help me review it, thanks.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by iamisti** [comment]
Looks fine to me guys!

**Comment by kennynaoh** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@x09326 the latest version you added is not v1.6.9 just let you know.

**Pull request merged**
