### PR TITLE
add git autoupdate config in jquery-tagsinput

### PR DESCRIPTION
**Pull request by Piicksarn**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Can you also add git auto-update config for it?

**Comment by Piicksarn** [comment]
@Amomo, would you please checkout the pr for me?
Thank you!～

**Comment by Piicksarn** [comment]
@Amomo, would you please checkout the pr for me?
the git repo url : https://github.com/xoxco/jQuery-Tags-Input
Thank you!～

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine.
Could you take a look? Thank you~ :-D

**Pull request merged**
