### PR TITLE
Add react-virtualized v6.3.1 with npm auto-update

### LINKED ISSUE #7650: [Request] Add React-Virtualized
**title**: React-Virtualized
**github**: https://github.com/bvaughn/react-virtualized
**npm**: https://www.npmjs.com/package/react-virtualized
**license**: MIT
**homepage**: https://bvaughn.github.io/react-virtualized

Great library for displaying large data sets.

This library includes 3 different dists: CommonJS, UMD and ES6.

It also requires a single styles.css file, which is my main reason for requesting the cdn.

Gracias!

### PR DESCRIPTION
**Pull request by x09326**
PR for #7650 
@pvnr0082t please help me review this PR, thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/bvaughn/react-virtualized
 * Official website (optional, not the repository): https://bvaughn.github.io/react-virtualized/
 * NPM package url (optional): https://www.npmjs.com/package/react-virtualized
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 1744
   - Count of watchers: 44
   - Count of forks: 76
 * NPM download stats (optional):
   - Downloads in the last day: 1615
   - Downloads in the last week: 9584
   - Downloads in the last month: 33955

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7650, cc @bvaughn

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@x09326 I think it should be ```umd/react-virtualized.min.js```
https://github.com/x09326/cdnjs/blob/react-virtualized/ajax/libs/react-virtualized/package.json#L3

**Comment by pvnr0082t** [comment]
@x09326 I think we don't need to add ```index.js``` and  __test__ file such as ```commonjs/Collection/TestData.js``` , ```commonjs/TestUtils.js``` maybe.
@PeterDaveHello I'm not sure. Is it right?

**Comment by PeterDaveHello** [comment]
@x09326 can you confirm with its author?

**Comment by bvaughn** [comment]
I _think_ @pvnr0082t is right. For CDN purposes, the UMD target is perhaps the most appropriate.

The Common JS target is the default in the NPM distributed version of react-virtualized but that's in order to be more compatible with typical project setup and NPM usage.

**Comment by x09326** [comment]
@bvaughn thank you for your help!

@pvnr0082t 
I chagned the **filename** and **files** fileds. please help me reivew it, thanks.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
I think we can take `dist/umd` as the base path/root, @bvaughn what do you think?

**Comment by bvaughn** [comment]
Seems reasonable.

**Comment by PeterDaveHello** [comment]
Okay, @x09326 let's change it. @bvaughn thanks for your prompt reply.

**Comment by x09326** [comment]
@pvnr0082t 
I changed the **filename** and **npmFileMap** fileds.
Please help me review it, thanks.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Pull request merged**
