### PR TITLE
[author] [new] ajile: asynchronous js importing & loading extension

### PR DESCRIPTION
**Pull request by iskitz**
Added all of __ajile's__ available versions and its auto-update config via this initial commit.

__ajile's__ original source code can be found at

+ https://github.com/iskitz/ajile/tree/master/code
+ https://github.com/iskitz/ajile/tree/master/use

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
According to the auto-update config :
```
, "autoupdate":
    { "source"  : "git"
    , "target"  : "git://github.com/iskitz/ajile.git"
    , "basePath": ""
    , "files":
        [ "code/com.iskitz.ajile.src.js"
        , "use/com.iskitz.ajile.js"
        , "use/index.js"
        ]
    }
}
```

The files should be at corresponding code/use folder.

**Comment by iskitz** [comment]
Hi @PeterDaveHello,

I thought the *__files__* property was an array of strings that each contain a path that exists within the git repository. [ajile's git directory structure](https://github.com/iskitz/ajile/) has `use/` and `code/` at its root. Should the *__files__* attribute's strings point to the paths that will be created on http://cdnjs.com/libraries/ajile instead? What paths would be correct if the ones I've specified aren't?

Thanks,
Mike

**Comment by PeterDaveHello** [comment]
Yes, so in every version/folder, the files will still be put in `use/` and `code/`, not directly under the root of that version.

**Comment by iskitz** [comment]
Ok @PeterDaveHello

So if I don't want my __cdnjs__ files to live under directories like `code/` and `use/` I need to put them all into one directory in my github repo?

That's a bit of a conflict since I use a versioned file name approach in my repo while __cdnjs__ uses versioned folders. I think I can make an adjustment to accommodate this but __cdnjs's git auto-update__ would be more flexible if it allowed files to be pulled in from any directory structure like below:

```javascript
{ ...
, "autoupdate":
    { "source"  : "git"
    , "target"  : "git://github.com/iskitz/ajile.git"
    , "basePath": ""
    , "files":
        [ "code/com.iskitz.ajile.src.js"  // iskitz/ajile/code/ => cdnjs/libraries/ajile/
        , "use/com.iskitz.ajile.js"       // iskitz/ajile/use/  => cdnjs/libraries/ajile/
        , "use/index.js"
        ]
    }
}
```
For now, would moving/copying `com.iskitz.ajile.src.js` from _iskitz/ajile/**code**/_ to _iskitz/ajile/**use**/_ in my git repo and changing the __cdnjs__ `autoupdate` config to what's below allow all files to be served from http://cdnjs.com/libraries/ajile/ ?

```javascript
{ ...
, "autoupdate":
    { "source"  : "git"
    , "target"  : "git://github.com/iskitz/ajile.git"
    , "basePath": "/use/"      // <<<<<<<<<<<<<<<<<<<<< changed
    , "files":
        [ "com.iskitz.ajile.src.js"
        , "com.iskitz.ajile.js"
        , "index.js"
        ]
    }
}
```

**Comment by PeterDaveHello** [comment]
Yeah, looks better now!

**Comment by iskitz** [comment]
@PeterDaveHello Thanks! Pull Request updated and CircleCI tests passed!

**Comment by iskitz** [comment]
@PeterDaveHello looks like this pull request is ready to be merged. Can you merge this or is something else still needed?

Thanks,
Mike

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by iskitz** [comment]
Thanks!

**Comment by iskitz** [comment]
Hi @PeterDaveHello. How long does it take for added/updated libraries to show up on http://cdnjs.com/ ? I've been checking for __ajile__ there and at http://cdnjs.com/libraries/ajile for the past ~28 hours since [you successfully merged my PR](https://github.com/cdnjs/cdnjs/commit/d41240f48cb8204dd9b2f4371dfdf846eaad8acd) but I still don't see it listed. Do you now why? :-(

**Comment by PeterDaveHello** [comment]
Seems the website didn't update, I'll respectfully suggest you to access your lib via urls like this：
https://cdnjs.cloudflare.com/ajax/libs/ajile/2.1.7/index.js
https://cdnjs.cloudflare.com/ajax/libs/ajile/2.1.7/com.iskitz.ajile.js
https://cdnjs.cloudflare.com/ajax/libs/ajile/2.1.7/com.iskitz.ajile.src.js

We'll fix the website ASAP, thanks for reporting this problem!

**Comment by PeterDaveHello** [comment]
tag @thomasdavis

**Comment by iskitz** [comment]
@PeterDaveHello & @thomasdavis, thanks for working on this.

**Comment by iskitz** [comment]
__Hey @PeterDaveHello and @thomasdavis,__

__So *ajile's* still not listed on cdnjs.com's main page__

>ajile cdnjs list

__but it does now show up in a cdnjs.com search__

>ajile cdnjs search

__Unfortunately, it still doesn't have a details page @ cdnjs.com/libraries/ajile__

>ajile cdnjs detail

**Comment by PeterDaveHello** [comment]
Yeah, the search is powered by algolia, but the content is maintained by us, only @thomasdavis can figure out.

**Comment by PeterDaveHello** [comment]
fixed.

**Comment by iskitz** [comment]
:+1: Thanks! :clap:

**Pull request merged**
