### PR TITLE
[author] [new] added ScrollMagic 1.3.0

### PR DESCRIPTION
**Pull request by janpaepke**
Source URL here:
https://github.com/janpaepke/ScrollMagic

Auto-Update will be added after release of 2.0, when it will also be published to npm and the file structure changes.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hi @janpaepke, is it possible to add auto-update config for it? thanks.

**Comment by janpaepke** [comment]
As I said in my comment above auto-update will be added after the release of 2.0, because it will cause the file structure to change. :)

**Comment by PeterDaveHello** [comment]
I meant if you are sure that you'll support it, you can add the config in the same PR, or if you just want me merge this now? up to you :)

**Comment by janpaepke** [comment]
Just merge now. I'll send another pr after release. :)

**Comment by PeterDaveHello** [comment]
Okay, thanks.

**Pull request merged**
