### PR TITLE
Enrich ModelCore's package.json(field: license)

### PR DESCRIPTION
**Pull request by LeaYeh**
Hi @Amomo , 
From #5500, I have added license info. https://github.com/klederson/ModelCore/blob/1.1.1/src/ModelCore.js#L2
Would you mind checking this PR for me? Thank you.

### CODE REVIEW

**Comment by LeaYeh** [comment]
hi @cdnjs/intern, i got in problem and need your suggests.
i was added licence info on github (then sent this pr) but i got a format error by ci.
then i wanted to fetch this commit to fix it, but when i `git checkout -b LeaYeh-patch-ModelCore [upstream]/LeaYeh-patch-ModelCore-1` then i got below error msg
```
fatal: Cannot update paths and switch to branch 'LeaYeh-patch-ModelCore' at the same time.
Did you intend to checkout 'origin/LeaYeh-patch-ModelCore-1' which can not be resolved as commit?
```

**Comment by PeterDaveHello** [comment]
@LeaYeh You should use ` git fetch `

**Comment by LeaYeh** [comment]
@PeterDaveHello , `git fetch [upstream]` then it work!
but the stupid thing is that was already have licence info before... that's why i got the format error (double licence field)
so i will close this pr, hope this was not waste your time too much...

**Comment by PeterDaveHello** [comment]
np

**Comment by PeterDaveHello** [comment]
and don't forget to delete your branch

**Pull request closed without merging**
