### PR TITLE
Update the auto-update config of vee-validate

### LINKED ISSUE #11831: Update vee-validate auto-update config
The current config will grab something we don't need which means we need to update it.

### PR DESCRIPTION
**Pull request by sufuf3**
close #11831

Pull request for issue: #11831
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/logaretm/vee-validate
 * Official website (optional, not the repository): http://vee-validate.logaretm.com
 * NPM package url (optional): https://www.npmjs.com/package/vee-validate
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 73
   - Count of stars: 2517
   - Count of forks: 313
 * NPM download stats (optional):
   - Downloads in the last day: 737
   - Downloads in the last week: 19098
   - Downloads in the last month: 69,817

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@extend1994 Please take a look ISSUE #11831
> The current config will grab something we don't need which means we need to update it.
We don't need `.md` file.

**Comment by extend1994** [comment]
@sufuf3 So don't we need to mention the reason if it is described in issue?

**Comment by sufuf3** [comment]
@extend1994 I don't know, but the reason why I do this PR because of this issue's comment
Please help me review this PR, thanks.

**Comment by extend1994** [comment]
@PeterDaveHello I think we still need to mention why we need to update the config if it is described in the issue?

**Comment by sufuf3** [comment]
@extend1994 I mentioned it
> We don't need .md file.

**Comment by extend1994** [comment]
Oh I mean in the commit message.

**Comment by sufuf3** [comment]
I think we don't 
FYI: https://github.com/cdnjs/cdnjs/search?q=update+auto-update&type=Commits&utf8=✓

**Comment by sufuf3** [comment]
Sorry for not check the file, it seems cannot use in front-end.
I updated the pattern, @cdnjs/intern3 please help me review this PR.
Thank you.

**Pull request merged**
