### PR TITLE
Add esri-leaflet-renderers@2.0.4 w/ npm autoupdate

### LINKED ISSUE #8862: [Request] Add esri-leaflet-heatmap
**Library name:** esri-leaflet-heatmap
**Git repository url:** https://github.com/Esri/esri-leaflet-renderers/

### PR DESCRIPTION
**Pull request by x09326**
PR for #8862 
@pvnr0082t please help me review it.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/Esri/esri-leaflet-renderers
 * Official website (optional, not the repository):https://esri.github.io/esri-leaflet
 * NPM package url (optional):https://www.npmjs.com/package/esri-leaflet-renderers
 * GitHub / Bitbucket popularity (required):
   - Count of stars:22
   - Count of watchers:12
   - Count of forks:15
 * NPM download stats (optional):
   - Downloads in the last day:9
   - Downloads in the last week:34
   - Downloads in the last month:148

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8862, cc @jgravois

### CODE REVIEW

**Comment by x09326** [comment]
@PeterDaveHello 
The github release versions are more than npm.
But the versions are beta version.
Should I manually add them?

**Comment by pvnr0082t** [comment]
@x09326 I think `esri-leaflet-renderers.js` is the minified file of `esri-leaflet-renderers-debug.js`. You don't need to minified again.

**Comment by x09326** [comment]
@pvnr0082t 
I have fixed it.

**Comment by x09326** [comment]
@pvnr0082t 
I have rebased it.
Please help me review it, thanks.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
LGTM, @pvnr0082t @x09326 please merge it, thanks

**Pull request merged**
