### PR TITLE
[Author] Fix messages_ar.js content of jquery-validation@1.18.0

### PR DESCRIPTION
**Pull request by Arkni**
# Pull request template for new library

Pull request for issue: 
Related issue(s): #13032 (see https://github.com/cdnjs/cdnjs/issues/13032#issuecomment-435388465)

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

## Profile of the lib

* Git repository (required): https://github.com/jquery-validation/jquery-validation
* Official website (optional, not the repository): https://jqueryvalidation.org
* NPM package url (optional): https://www.npmjs.com/package/jquery-validation
* License and its reference: MIT
* GitHub / Bitbucket popularity (required):
  * Count of watchers: 526
  * Count of stars: 9113
  * Count of forks: 2622
* NPM download stats (optional):
  * Downloads in the last day:
  * Downloads in the last week:
  * Downloads in the last month:

## Essential checklist

* [x] I'm the author of this library
  * [ ] I would like to add link to the page of this library on CDNJS on website / readme
* [ ] This lib was not found on cdnjs repo
* [ ] Doesn't already exist / has duplicate issue and PR
* [ ] The lib has notable popularity
  * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [ ] More than 800 downloads stats per month on npm registry
* [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [ ] Has valid tags for each versions (for git auto-update)
* [ ] Auto-update setup
* [ ] Auto-update target/source is valid.
* [ ] Auto-update filemap is correct.

## Git commit checklist

* [X] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [X] The parent of the commit(s) in the PR is not older than 3 days.
* [X] Pull request is sent from a non-master branch with a meaningful name.
* [X] Separate unrelated changes into different commits.
* [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [X] Close corresponding issue in commit message
* [X] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hi @Arkni, as we have checksum and using SRI on CDNJS, it's better not to edit the files once it's added, any other ideas? Thanks.

**Comment by PeterDaveHello** [comment]
@Arkni Thanks, so will the release on the release page and on CDNJS still be different or they'll be aligned in this case? 

I'd prefer to make sure they are the same and have another release soon for the patch, should be more safe and not confusing, if it's possible.

**Comment by Arkni** [comment]
@PeterDaveHello,

Unfortunately, they will still defer by one file (`localization/messages_ar.js`) and there is no way to change it on our side too as we also provide an archive of the release that can be downloaded which contains the right file.

We are working on creating a new release soon (hopefully by the end of the week). Also, I just noticed that the auto-update bot is configured to pull the localization files from `src` ([`/ajax/libs/jquery-validate/package.json#L27-L32`](https://github.com/cdnjs/cdnjs/blob/dbd922be69db85cf0cf67710471fdd65ca89c1d8/ajax/libs/jquery-validate/package.json#L27-L32)), because as of `1.18.0`, we started to provide (finally!) the localization files on the dist folder too (both non-minified and minified). So, it's safe to pull the file from there now.

Thanks a lot for your help, we really appreciate it :)

**Comment by PeterDaveHello** [comment]
@Arkni thanks for all the explaination in details! Would you like to send a pull request to update the auto-update config for the new localization files? Looks like we're going to have a awesome release soon!

**Comment by Arkni** [comment]
@PeterDaveHello,

I will send one by the end of the week.

By the way, can we close this PR and the linked issue as they are not relevant anymore ?

Thanks :)

**Comment by PeterDaveHello** [comment]
@Arkni sure!

**Pull request closed without merging**
