### PR TITLE
Enrich 6to5's package.json(field: license)

### PR DESCRIPTION
**Pull request by LeaYeh**
Hi @Amomo  , 
From #5500, I have added license info. https://github.com/babel/babel/blob/master/LICENSE#L3
repo : https://github.com/babel/babel
Would you mind checking this PR for me? Thank you.

### CODE REVIEW

**Comment by Amomo** [comment]
Hi @LeaYeh as Peter said in #5828

You should make your commit message easy to recognize `which license you add`.
Don't use only `field: license`.

And, your PR comment shouldn't be written in the commit message.

**Comment by LeaYeh** [comment]
i think @PeterDaveHello means we should point out which line in file we recognized that is "MIT" not about commit.
https://github.com/babel/babel/blob/master/LICENSE#L3

**Comment by maruilian11** [comment]
i thought he said `LICENSE` **file** is not so reliable.

**Comment by LeaYeh** [comment]
@maruilian11  but it is clearly point out that is "MIT", or what do you mean **reliable** ?

**Comment by PeterDaveHello** [comment]
If you only point to a file, the file may not be so reliable, unless you can tell me every time you did that you really read all the sentences and words in it, if not, I think there should be a word "MIT" or something to clarify its license, that's all, in this case, line 3 already said its MIT, it's okay, isn't it?

**Comment by maruilian11** [comment]
oh got it

**Comment by Amomo** [comment]
Oh, I see the difference! Thank you everyone~

I am sorry @LeaYeh,
This is a good PR, could you rebase it? Thank you! :-D

**Comment by LeaYeh** [comment]
@Amomo ok, i already rebased it. pls check it again

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine, could you take a look?
Thank you! :-)

**Pull request merged**
