### PR TITLE
Add i18next-xhr-backend@1.4.2 w/ npm auto-update

### PR DESCRIPTION
**Pull request by dakshshah96**
Pull request for issue: #10720
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/i18next/i18next-xhr-backend
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/i18next-xhr-backend
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 2
   - Count of stars: 47
   - Count of forks: 40
 * NPM download stats (optional):
   - Downloads in the last day: 2,191
   - Downloads in the last week: 13,805
   - Downloads in the last month: 57,005

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by dakshshah96** [comment]
@sufuf3 Can you please clarify that? I didn't get what you meant about the manual additions.

**Comment by sufuf3** [comment]
@dakshshah96 Sorry about that.
1. Could you `cc @jamuhl` in the commit message to notice author?
2. Could you manually add v0.0.2 from GitHub in another commit? Let CDNJS host v0.0.2 because npm auto-update can't get this version.

Thank you.

**Comment by dakshshah96** [comment]
@sufuf3 Done 👍

**Comment by sufuf3** [comment]
@extend1994 I removed it, please help review this PR, thanks.

**Comment by PeterDaveHello** [comment]
Thanks all!

**Pull request merged**
