### PR TITLE
[new] add typicons

### PR DESCRIPTION
**Pull request by equinox7**
http://www.typicons.com/
https://github.com/stephenhutchings/typicons.font

### CODE REVIEW

**Comment by equinox7** [comment]
Created new pull request with one commit.

**Comment by PeterDaveHello** [comment]
Don't we need svg and png images under src? Thanks.

**Comment by equinox7** [comment]
@PeterDaveHello Personally I do not need src images. This is not the only icon font without src images in it. For example **octicons** has only fonts and styles in it too.

**Comment by PeterDaveHello** [comment]
@equinox7 I just want to confirm if the png and svg files should also be distributed, maybe we can confirm with its author?

**Comment by equinox7** [comment]
@PeterDaveHello There are [usage notes](http://www.typicons.com/more/how-to-use-typicons/) only for font icons. If you want, I can try contact author.

**Comment by PeterDaveHello** [comment]
@equinox7 okay I will take a look, thanks a lot

**Comment by PeterDaveHello** [comment]
LGTM, let's give it a try.

**Pull request merged**
