### PR TITLE
add ngDraggable@0.1.8 w/ git auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
**npm package url:** https://www.npmjs.com/package/ng-draggable (wait to check)
**git repo url:** https://github.com/fatlinesofcode/ngDraggable
**Watch 43
  Star 459
 Fork 258**
@PeterDaveHello  could u help me check this PR for #7471 ? thank you!
ask about license here https://github.com/fatlinesofcode/ngDraggable/issues/241
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
There are many versions on GitHub but only v1.0.0 on npm, you should confirm that first.

**Comment by maruilian11** [comment]
@PeterDaveHello so i need to turn auto-update config to git and add v1.0.0 from npm?

**Comment by PeterDaveHello** [comment]
I don't even think it's an official npm package, haven't you confirm that first?

**Comment by maruilian11** [comment]
hmmm...
so how do i tell if it is an official npm package?
some author won't mention npm package on lib repo.

**Comment by PeterDaveHello** [comment]
Doesn't npm package mention author of the package? Why not just go to open an issue to confirm with authors on GitHub?

**Comment by maruilian11** [comment]
ok, i will open the issue, but i have opened two issue before and didn't get any response.

**Comment by PeterDaveHello** [comment]
The author of the npm package doesn't look like the author on GitHub, isn't so hard to say that ...
https://www.npmjs.com/~devup

**Comment by maruilian11** [comment]
@Amomo i have modified the source to official git repo, could you help me check this PR? thanks!

**Comment by Amomo** [comment]
@PeterDaveHello 
I think this PR is ok by using git auto-update config and v0.1.8 on GitHub.

**Pull request merged**
