### PR TITLE
[author][new] dom-class 0.5.0

### PR DESCRIPTION
**Pull request by WebReflection**
Explained in [different](https://www.webreflection.co.uk/blog/2015/09/17/simplified-web-components-via-dom-class) [posts](https://www.webreflection.co.uk/blog/2015/09/21/dom-class-bindings-vs-performance), and enriched with [bindings demo](http://webreflection.github.io/dom-class/demo/) and [other comparisons](http://webreflection.github.io/dom-class/demo/domclass-vs-knockoutjs/), it'd be awesome to have the single and hybrid version of this project in cdnJS.

Thanks!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@WebReflection @cdnjs/intern please help me audit it.

**Comment by WebReflection** [comment]
not sure I understand what I can do to help

**Comment by PeterDaveHello** [comment]
Sorry, wrong tag.

**Comment by drewfreyling** [comment]
This library doesn't meet our popularity requirement for cdnjs.

**Comment by WebReflection** [comment]
sorry @drewfreyling but you accepted libraries with around 12 stars or something before. Can you please tell me  what is the minimum amount of stars cdnjs requires? I have many projects here, first time one PR gets closed this way. Thanks for clarification.

**Comment by drewfreyling** [comment]
@WebReflection the readme mentions 100 stars or something similar to demonstrate popularity. We had it relaxed at one stage but then everybody started uploading what can only be described as "personal projects" rather than useful libraries used in the community which is why it has been reintroduced.

**Comment by WebReflection** [comment]
100 stars looks way beyond the intent described in cdn js home page.

You should probably fix that text and say "_We host it only if your is popular already and has at least 100 stars on Github_", where most of my "popular" project became popular thanks to the ability to be discovered via cdn js.

screenshot from 2015-10-01 09-54-25

Anyway, thanks for the clarification.

**Comment by PeterDaveHello** [comment]
@WebReflection thanks for your suggestion, will you please send a new PR when you got maybe 50 starts? I saw that you wrote some cool projects with notable popularity, we can host you lib earlier!

**Comment by WebReflection** [comment]
that's kind @PeterDaveHello but I'm not sure I want to be privileged compared to others developers.
I see this project like a great opportunity to make a library popular so that others can easily test.

I understand someone might take advantage and it's not easy to filter all of them, it's also a free service so I can't complain. 100 stars thought are not so easy to achieve, specially for newcomers in the community (but neither for me).

Easy for already popular companies to always strike that through common hype and thousands followers. Anyway, I'll probably try again just to see if the situation went back to "relaxed".

Thanks

**Comment by PeterDaveHello** [comment]
hmmmm ... that's not really like privilege I think, we sometimes push the libs with potential, or make the limit lower for the active, high-quality contributor, it's reasonable, and 100 stars is just an example, any way, you're welcome to send the PR again in future.

**Comment by WebReflection** [comment]
fair enough, I might try in the future.

**Comment by PeterDaveHello** [comment]
@WebReflection Thank you

**Pull request closed without merging**
