### PR TITLE
[author][new] add jambonbeurre v0.4.0

### PR DESCRIPTION
**Pull request by Jumpyjumper**
origin: https://github.com/Jumpyjumper/JambonBeurre

description: JambonBeurre is a tasty progressively enhanced off-canvas (hamburger) menu designed to be compatible with old and modern browsers/devices. It is easy to use and implement and with no JavaScript requirement. However, if you so choose, it is also implemented with JS as AMD style library that allows for heavly customized and super-smooth responsive menus.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Need to squash them into only one commit.
Need to setup auto-update config as #3638 said.
Need higher popularity.

**Comment by drewfreyling** [comment]
@PeterDaveHello I'd be inclined to close this PR based on your 3rd point.

**Comment by PeterDaveHello** [comment]
Fine, I wouldn't mind.

**Comment by Piicksarn** [comment]
ping @cdnjs/intern @cdnjs/intern2

**Comment by pvnr0082t** [comment]
@PeterDaveHello Does this PR need to be closed? It has been wait for higher popularity for a long time.

**Comment by PeterDaveHello** [comment]
We could add it when it got more popularity!

**Pull request closed without merging**
