### PR TITLE
add leaflet-tilelayer-geojson v1.0.4

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #6746 
@pvnr0082t  please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/glenrobertson/leaflet-tilelayer-geojson/
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/leaflet-tilelayer-geojson
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 163
   - Count of watchers: 27
   - Count of forks: 54
 * NPM download stats (optional):
   - Downloads in the last day: 0
   - Downloads in the last week: 18
   - Downloads in the last month: 113

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

git auto-update config added, cc @glenrobertson

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I think you added too may files here. Please check it.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
Sorry, I forgot to remove it.
But I have updated it already.
Thanks.

**Comment by PeterDaveHello** [comment]
@kennynaoh You should be more careful before you send a PR.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
Sorry about that.
I will be more careful next time.
Thanks.

**Comment by PeterDaveHello** [comment]
@kennynaoh Nice!

**Comment by PeterDaveHello** [comment]
The npm package seems to be non officially maintained, have you confirm that?

**Comment by glenrobertson** [comment]
Hey @kennynoah. I don't understand this stuff too well but let me know how I can help!

**Comment by kennynaoh** [comment]
Hello @glenrobertson 
We want to host your library in cdnjs project.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
How to confirm the npm package is officially maintained or not.
Thanks

**Comment by PeterDaveHello** [comment]
@kennynaoh You can ask its author.

**Comment by kennynaoh** [comment]
@glenrobertson 
Does the npm package officially maintain?
Thanks.

**Comment by PeterDaveHello** [comment]
@kennynaoh why don't you open an issue in the repo of this lib and ask if the author owned a certain npm package with the package name? Your question is not clear at all.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
OK, thanks.

**Comment by PeterDaveHello** [comment]
@kennynaoh you still didn't say the npm package npm on the issue, there thousands of hundreds of packages, how can the author know what is the library you are talking about? Let's make your question more clear.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
Sorry about that.
I will update the question more clear.
Thanks.

**Comment by kennynaoh** [comment]
@pvnr0082t 
I have confirm with the author.
The npm package is officially maintained.
Please help me review it again.
Thanks.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
The [npm](https://www.npmjs.com/package/leaflet-tilelayer-geojson) package isn't maintained by the author.
What should I do next?
Thanks.

**Comment by PeterDaveHello** [comment]
So you should use git auto-update as the source.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
Got it, thanks.
@pvnr0082t 
I have updated it.
Please help me review this PR again.
Thanks.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Pull request merged**
