### PR TITLE
[new] add jquery-treetable@3.2.0 with git auto-update

### PR DESCRIPTION
**Pull request by Amomo**
Hi @Piicksarn 

For #6013, I add jquery-treetable at v3.2.0 and add git auto-update config in its package.json.
repo: https://github.com/ludo/jquery-treetable

Would you mind checking this PR for me? Thank you~ :-D

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `45`, Star `451`, Fork `175`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you please have a look at the pr?
Thank you!

**Comment by PeterDaveHello** [comment]
Do we really need screen.css?

**Comment by Amomo** [comment]
Opps! As its "bower.json" said, `screen.css` isn't in main files.
I should remove it from here. Thanks, Peter. :-D

@Piicksarn could you please check this PR again? Thank you!

**Comment by Piicksarn** [comment]
@PeterDaveHello, I think the pr is fine!
Would you mind to have a look at the pr?
Thank you!

**Comment by Piicksarn** [comment]
@Amomo, would you mind to rebased it again?

**Comment by Amomo** [comment]
@Piicksarn I have rebased my PR to latest branch, could you check it again?
Thank you! :-D

**Pull request merged**
