### PR TITLE
Add bootstrap-toggle@2.2.1 with git autoupdate

### PR DESCRIPTION
**Pull request by Piicksarn**
**git repo url:** https://github.com/minhur/bootstrap-toggle/tree/2.2.1
**Watch 28
  Star 402
 Fork 110**
@maruilian11  could you help me check out the PR for #6259  ? thank you~
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity 
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
No need to add css files?

**Comment by Piicksarn** [comment]
@maruilian11, i have it rebased!
would you mind to have a look at the pr?

**Comment by Piicksarn** [comment]
@maruilian11, i have it rebased!
would you mind to have a look at the pr?

**Comment by maruilian11** [comment]
@Piicksarn please add real `.css`

**Comment by Piicksarn** [comment]
@maruilian11, would you mind to checkout the pr again?
Thank you!

**Pull request merged**
