### PR TITLE
add license info for less.js

### PR DESCRIPTION
**Pull request by LeaYeh**
@Amomo 

hey Amomo, i add license field with Apache-2.0 
lib: https://github.com/less/less.js/blob/master/LICENSE

#5500

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@LeaYeh, as I said before, I think you should first reply on the issues/PRs mentioned you, then send your PR.

**Comment by LeaYeh** [comment]
i lose all of assignment massage OAO

**Comment by PeterDaveHello** [comment]
And did you try to find them out?

**Comment by LeaYeh** [comment]
@PeterDaveHello  hey Peter, i rebase this pr again, could you check this pr for me?
btw, i think i have finish checking PRs which mentioned me.

**Comment by Amomo** [comment]
@LeaYeh could you make you commit message to start with the key action you done?
And, please also modify the title to make it more readable.

Thank you~

**Comment by PeterDaveHello** [comment]
Use [checklist](https://github.com/cdnjs/cdnjs/issues/5315) please.

**Comment by Amomo** [comment]
Hi @LeaYeh could you modify your commit message and PR title like...
`add license field of ...` or `Enrich ...'s package.json(field: license) `
to make you message more clear?

And, don't forget to rebase the commit after modifying. Thank you! :-D

**Comment by Amomo** [comment]
@LeaYeh could you please update your PR~?

**Comment by PeterDaveHello** [comment]
Added in dc2056d55f7e5731850994cd4f29a3575f15bbd2

**Pull request closed without merging**
