### PR TITLE
Add Skel and Layers plugin for Skel

### PR DESCRIPTION
**Pull request by rivanvx**
Add Skel and Layers Plugin for Skel.

Skel: A lightweight responsive framework for the www.
Layers: A plugin for Skel that streamlines building stuff like off-canvas navigation, toolbars, modals, and other stuff.

I used UglifyCSS for minimizing CSS and I did my best to check I follow all the rules.

### CODE REVIEW

**Comment by rivanvx** [comment]
What should I do now that CI failed?

**Comment by PeterDaveHello** [comment]
We have a problem on circleCI, it was fixed now, but I think you missed a css file to minify.

**Comment by rivanvx** [comment]
Thanks!

**Comment by PeterDaveHello** [comment]
np

**Pull request merged**
