### PR TITLE
[author][new] ValJS V0.7

### PR DESCRIPTION
**Pull request by dlid**
First version of ValJS
Minified source: https://github.com/dlid/jquery-valjs/blob/master/jquery.valjs.min.js
Uncompressed source: https://github.com/dlid/jquery-valjs/blob/master/jquery.valjs.js

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hi @dlid, 

Is it possible to add auto-update config in it? We hope all the lib can be easily updated in future, you can use npm or git auto-update as readme and #3638 said, thanks.

**Comment by dlid** [comment]
Hi, I can absolutely do that.

Do I understand it correctly that cdnjs will use git tags to keep track of the versions? So if I want my 0.7 version to be available on cdnjs I create the 0.7 tag, and for future versions when I create a new tag - it will be picked up automatically by cdnjs?

Thanks.
/David

**Comment by PeterDaveHello** [comment]
Yes, you are right! So please add git auto-update config for it, thanks a lot.

**Comment by dlid** [comment]
I added the autoupdate in https://github.com/dlid/jquery-valjs-cdnjs/blob/master/ajax/libs/valjs/package.json now so I hope it's correct. I also created the 0.7.3 tag in the source rep and updated the files in my cdnjs-fork to the latest files.

**Comment by PeterDaveHello** [comment]
Would you please merge these two commits into only one commit? thanks.

**Comment by dlid** [comment]
I've having issues merging the commits, I'm no github ninja unfortunately. Could I drop my fork and make a new pull request instead?

**Comment by dlid** [comment]
Closing this request, Github is not friends with me. I'll try again with a separate request

**Pull request closed without merging**
