### PR TITLE
Update description of egjs

### PR DESCRIPTION
**Pull request by sufuf3**
Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/naver/egjs
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 38
   - Count of stars: 763
   - Count of forks: 86
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
Becuase the filename stops auto-update from getting the files. I updated the filename and added v2.0.0.
The README said `egjs 1.5.0 no longer adds new features.
Here is some description https://github.com/naver/egjs/wiki/Migrating-From-egjs-1.x.x-to-egjs-2.0.0 

And I think maybe we need to add the sub lib as the followings:
- egjs-agent npm install @egjs/agent
- egjs-axes npm install @egjs/axes
- egjs-component npm install @egjs/component
- egjs-flicking npm install @egjs/flicking
- egjs-infinitegrid npm install @egjs/infinitegrid
- egjs-persist npm install @egjs/persist
- egjs-rotate npm install @egjs/rotate
- egjs-visible npm install @egjs/visible
- egjs-jquery-pauseresume npm install @egjs/jquery-pauseresume
- egjs-jquery-transform npm install @egjs/jquery-transform

I will open an issue to add these libs.
Thank you.

**Comment by sufuf3** [comment]
@cdnjs/active-contributor @cdnjs/intern3 please help me review this PR, thank you.

**Comment by sufuf3** [comment]
@cdnjs/library-reviewer 
Please help me review this PR, Thank you.

**Comment by PeterDaveHello** [comment]
Nice catch @extend1994, looks like we should add them separately! Then we can update the description of the origin library to mention the change in v2.0.

**Comment by sufuf3** [comment]
@cdnjs/active-contributor @cdnjs/intern3 
I updated the description and open an issue to add the related libs of egjs.
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
After sending one commit, I resent it immediately, so got the CI fault. resent it again.

**Comment by PeterDaveHello** [comment]
`npm install` is not how you should add the library, we never need to install a npm package to add a library, also, the description needs to be discussed first, the PR should be sent once the new versions been added already, I'll close this now.

**Pull request closed without merging**
