### PR TITLE
add blockadblock v3.1.1 with git autoupdate

### PR DESCRIPTION
**Pull request by maruilian11**
@Amomo could u plz help me check this pr for #5137, thx~

### CODE REVIEW

**Comment by Amomo** [comment]
Hi @maruilian11 , the popularity of this lib seems not enough currently.
@PeterDaveHello , I am wondering that we should add it now or not.

**Comment by maruilian11** [comment]
@Amomo oh i didn't notice that haha, closing is fine for me.

**Comment by PeterDaveHello** [comment]
Acceptable popularity:
[sitexw/BlockAdBlock/README.md](https://github.com/sitexw/BlockAdBlock/blob/master/README.md)
> ([FuckAdBlock](https://github.com/sitexw/FuckAdBlock) same project but with a more convenient name)

But I wonder if we should host a lib to against users' rights about advertisement, I'll discuss this with other maintainers.

**Comment by sitexw** [comment]
What do you think then?

**Comment by PeterDaveHello** [comment]
cc @cdnjs/team-cdnjs @cdnjs/intern

**Comment by Piicksarn** [comment]
@cdnjs/intern.

**Comment by maruilian11** [comment]
we need to wait for the maintains' decision, don't we?

**Comment by PeterDaveHello** [comment]
what do you think @cdnjs/intern ?

**Comment by maruilian11** [comment]
i think user can choose if they want to use this lib, they still have the right.

**Comment by PeterDaveHello** [comment]
> i think users can choose if they want to use this lib, they still have the right.
That's the reason why users use adblock/ublock, pushing a lib to block them may make them no choice.

**Comment by sitexw** [comment]
> That's the reason why users use adblock/ublock

I do not agree he uses AdBlock against advertisements and not against the ad blocker detectors.

FuckAdBlock and BlockAdBlock were not designed to be against the user, but simply to allow webmasters to tell their users that they need these ads to survive.
Obviously, the other person uses to block access to content if they have an ad blocker, but it is their right, it is the internet, is open.
But do not deprive the many sites (small and large) that exist and live through internet.

**Comment by PeterDaveHello** [comment]
@sitexw thanks for your comment.

**Comment by PeterDaveHello** [comment]
Let's add this, please rebase this base upon the latest master branch.

**Comment by PeterDaveHello** [comment]
What's going on here？

**Comment by maruilian11** [comment]
@PeterDaveHello sorry, deleted the branch carelessly, new pr is here.
https://github.com/cdnjs/cdnjs/pull/7197

**Pull request closed without merging**
