### PR TITLE
add leaflet.heat v0.2.0 with npm auto-update

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #6746
@dannyxx001 please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/Leaflet/Leaflet.heat
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/leaflet.heat
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 432
   - Count of watchers: 44
   - Count of forks: 114
 * NPM download stats (optional):
   - Downloads in the last day: 25
   - Downloads in the last week: 162
   - Downloads in the last month: 529

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

cc #6746, cc @mourner

### CODE REVIEW

**Comment by dannyxx001** [comment]
@PeterDaveHello I think this PR is OK. Please review again, thanks.

**Comment by PeterDaveHello** [comment]
Why to minify a minified file @kennynaoh @dannyxx001 ?

**Comment by dannyxx001** [comment]
Sorry for not clearly review. @kennynaoh  I think we should remove the duplicate minified file.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
You mean the ```leaflet-heat.js``` is the minified file?
So do I need to ask author to change the file name?
Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh Thete is no need to change it.

**Pull request merged**
