### PR TITLE
add hypermedia-client@1.29.2 w/ npm auto-update

### LINKED ISSUE #8421: [Request] Add hypermedia-client
**Library name:** hypermedia-client
**Git repository url:** https://github.com/cignium/hypermedia-client
**npm package url(optional):** https://www.npmjs.com/package/cignium-hypermedia-client
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by nolsherry**
PR for #8421
@pvnr0082t , @x09326 , please help me review this PR, thanks!
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/cignium/hypermedia-client
- Official website (optional, not the repository):
- NPM package url (optional): https://www.npmjs.com/package/cignium-hypermedia-client
- GitHub / Bitbucket popularity (required):
  - Count of stars: 2
  - Count of watchers: 13
  - Count of forks: 4
- NPM download stats (optional):
  - Downloads in the last day: 175
  - Downloads in the last week: 381
  - Downloads in the last month: 829
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [X] This lib was not found on cdnjs repo
- [X] No already exist / duplicated issue and PR
- [X] The lib has notable popularity
  - [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [X] More than 500 downloads stats per month on npm registry
- [X] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [X] Has valid tags for each versions (for git auto-update)
- [X] Auto-update setup
- [X] Auto-update target/source is valid.
- [X] Auto-update filemap is correct.
# Git commit checklist
- [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [X] The parent of the commit(s) in the PR is not old than 3 days.
- [X] Pull request is sending from a non-master branch with meaningful name.
- [X] Separate unrelated changes into different commits.
- [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [X] Close corresponding issue in commit message
- [X] Mention related issue(s), people in commit message, comment.

close #8421, cc @hfjallemark

### CODE REVIEW

**Comment by kennynaoh** [comment]
And there are different naming policy between `js` file and `css` file.
I'm not sure whether it is okay.
Maybe should discuss with author to change the same naming policy.
cc @PeterDaveHello

**Comment by nolsherry** [comment]
@pvnr0082t , OK, I will add the author info in `package.json`
@kennynaoh , do you mean that we should discuss with author weather he can change the naming policy? For example, `default.css` should be renamed  `client.min.css`, Is it right?

**Comment by kennynaoh** [comment]
@nolsherry 
What I mean is `default.css` -> `default.min.css`
Because both of these two files are minified file, but one is `xxx.min.js` the other is `xxx.css`.

**Comment by hfjallemark** [comment]
That makes more sense. We could provide both minified and unminified versions of both js and css. Not something we can have in the near future but will add it to our backlog. cc @nranas

**Comment by kennynaoh** [comment]
Thanks @hfjallemark

**Comment by nolsherry** [comment]
@kennynaoh , sorry, I misunderstood your meaning.
@hfjallemark , I am sorry for passing on wrong messages to you, and thanks for your help.

**Comment by nolsherry** [comment]
@pvnr0082t , @kennynaoh , @x09326 , I found that the structure of `v1.0.0`, `v1.0.1` and `v1.0.2` from npm are different from other versions after `v1.0.2`. It does not exist `dist` folder, should we add these versions to `.gitignore` file? Or should I need confirm with the author?

**Comment by kennynaoh** [comment]
@nolsherry 
It's fine without `dist/` in the version you mentioned.
You could confirm with author which files need to be grab in those versions.
And you can manually add it due to file structure changed.
Thanks!

**Comment by nolsherry** [comment]
@kennynaoh , the author has responsed in [hypermedia-client/issues#88](https://github.com/cignium/hypermedia-client/issues/88), maybe  we can consider ignoring these versions. What do you think?

cc @PeterDaveHello

**Comment by kennynaoh** [comment]
@nolsherry I think we should ignore `v1.0.0`~`v1.0.2` because the author said they will not work on cdn.

**Comment by nolsherry** [comment]
@kennynaoh I have modified `.gitignore` file to ignore the version 1.0.0, 1.0.1 and 1.0.2,
please help me review this PR, thanks!

**Comment by kennynaoh** [comment]
I think we don't need to update .gitignore to ignore those versions because auto-update get nothing in those versions. We can just leave them along.

**Comment by PeterDaveHello** [comment]
Thanks guys :+1:

**Pull request merged**
