### PR TITLE
Add license of infinity

### PR DESCRIPTION
**Pull request by x09326**
Ref: https://github.com/airbnb/infinity/blob/master/LICENSE
@cdnjs/intern2  please help me review it, thanks.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM

**Comment by x09326** [comment]
@cdnjs/intern2 
The author said the extra sentence wouldn't change its license type, so I think it's a **BSD-3-Clause** license.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
@x09326 you should mention the origin PR #9703 in commit message and comment next time

**Pull request merged**
