### PR TITLE
[New] Add angular-parse w/ git auto-update

### LINKED ISSUE #8180: [Request] Add angular-parse
**Library name:** angular-parse
**Git repository url:** https://github.com/ivnivnch/angular-parse

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/34967166-request-add-angular-parse?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sashberd**
close #8180, cc @ivnivnch
Pull request for issue: #8180 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/ivnivnch/angular-parse
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/angular-parse
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 3
   - Count of stars: 28
   - Count of forks: 9
 * NPM download stats (optional):
   - Downloads in the last day: 52
   - Downloads in the last week: 266
   - Downloads in the last month: 1201

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sashberd** [comment]
@extend1994 The new PR for your review.
The git version was downloaded via wget 
the npm versions were downloaded via npm install command
IF the problem still exists. Please help me to fix it, cause I have no idea what is the problem

**Comment by sashberd** [comment]
@sufuf3 I readd the files with wget and npm install one by one and GIT does not find changes in the git tree
I have no idea how to fix this, moreover, we already faced ith this problem and only readd items by you or other reviews solved it
Please help me to solve this problem from your side this time. 
Thanks

**Comment by sufuf3** [comment]
@sashberd I can help you.
But before that, would you please try these method in your windows OS?
Maybe you can set unix format in your windows OS and try again.
Like these method: https://stackoverflow.com/questions/1110678/m-at-the-end-of-every-line-in-vim
https://forum.sublimetext.com/t/how-to-set-the-default-line-endings-for-unix/3344/3
https://en.wikipedia.org/wiki/Newline

What do you think?
If it's still not work, please let me know.
I'll help you improve this PR.

Many thanks.

**Comment by sashberd** [comment]
@sufuf3 I used this technique [http://shanelabs.com/blog/2012/06/27/getting-rid-of-m-newline-characters-in-notepad/](url), if it is not helped [lease help me to fix this files

**Comment by sashberd** [comment]
@sufuf3 ping

**Comment by sashberd** [comment]
@sufuf3 @extend1994 Ping

**Comment by sashberd** [comment]
@MattIPv4 Please review this one. Thanks

**Comment by MattIPv4** [comment]
I think it'd be best to close this unless there is still a great demand for it beyond the low popularity?

**Comment by sashberd** [comment]
This one was also asked on issue open, but Peter approved the add of this
lib

**Comment by MattIPv4** [comment]
It looks like the popularity of this has decreased significatnly since this was originally requested/approved, when it was already below what we normally consider popular. I don't really see a reason to be adding this at present with very little demand and use.

**Pull request closed without merging**
