### PR TITLE
manually add parallaxify

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #8221 
@pvnr0082t, @x09326 please help me review this pull request, thank you.
`v0.0.1` -> https://github.com/hwthorn/parallaxify/commit/da67338e1ecbfd75259f66006bffd7dfae8a14bb#diff-9e1a7db63605440b0fdc61611347bbf5R2
`v0.0.2` -> https://github.com/hwthorn/parallaxify/commit/993793fd318b379a6ed4ec5db05948d04f6ce426#diff-9e1a7db63605440b0fdc61611347bbf5R2
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/hwthorn/parallaxify
 * Official website (optional, not the repository): https://hwthorn.github.io/parallaxify/
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 246
   - Count of watchers: 24
   - Count of forks: 61
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 
I have fixed the commit message.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by x09326** [comment]
@kennynaoh 
Please rebase with the latest branch.

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 
I have rebased to the latest master branch.
Please help me review it again.
Thanks!

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326
I have rebased to the latest master branch.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by x09326** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
You should provide the commit as version references as you manually added them.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
You mean add commit ref in commit message?

**Comment by PeterDaveHello** [comment]
@kennynaoh PR comment is fine.

**Comment by kennynaoh** [comment]
OK

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 
I have added version reference in PR comment and rebased to the latest master branch.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Well done @kennynaoh

**Pull request merged**
