### PR TITLE
Ghover

### PR DESCRIPTION
**Pull request by GA-MO**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/GA-MO/g-hover
 * Official website (optional, not the repository): https://ga-mo.github.io/g-hover
 * NPM package url (optional):
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 1
   - Count of stars: 1
   - Count of forks: 0

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by x09326** [comment]
@PeterDaveHello 
I think it's okay. Should I help squash and rebase the branch with the latest master branch?

**Comment by x09326** [comment]
@GA-MO 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by GA-MO** [comment]
Waiting for npm package downloaded 300 times per month

**Comment by PeterDaveHello** [comment]
Let's close this and reopen it when it reached the popularity requirement, thanks.

**Pull request closed without merging**
