### PR TITLE
add auto-update config & update to a stable version of zocial

### PR DESCRIPTION
**Pull request by Amomo**
Hi @LeaYeh , From #5276, I would like to fix zocial to point to a stable version.
repo: https://github.com/samcollins/css-social-buttons
The latest stable version of zocial is v1.1.1, but cdnjs doesn't have now.
So I add v1.1.1 and update version number in package.json.
I also add auto-update config and update info in package.json.
I use `zocial*` to collect not only css file, but also the font files because they will be used by zocial.css.
Would you mind checking this PR for me? Thank you~ :-)

- [ ] Not found on cdnjs repo : `zocial`
- [x] No already exist issue and PR
- [x] Notable popularity : `1467` star, `267` fork
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by tresni** [comment]
:+1: was going to do this myself so glad to see someone else has :)

**Comment by Amomo** [comment]
Hi @Piicksarn would you mind checking this PR for me?
Thank you~ :-D

**Comment by Amomo** [comment]
285e62d has done it.

**Comment by PeterDaveHello** [comment]
#5287

**Pull request closed without merging**
