### PR TITLE
add scrollmonitor v1.0.12 with git autoupdate, close #5222

### LINKED ISSUE #5222: [Request] Add scrollmonitor
**Library name:** scrollmonitor
**Git repository url:**https://github.com/sakabako/scrollMonitor
**npm package url(optional):** https://www.npmjs.com/package/scrollmonitor
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by maruilian11**
@Piicksarn could u plz help me check this pr from #5222, thank u~

### CODE REVIEW

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you please check out the pr?
Thank you!

**Comment by PeterDaveHello** [comment]
We don't need `testling` and `spm` ...

**Comment by Piicksarn** [comment]
Sorry.. i'll bear in mind!

**Comment by maruilian11** [comment]
@Piicksarn could u help me check it again? thank u~

**Comment by Piicksarn** [comment]
@PeterDaveHello would you please take a look on it?
Thank you!

**Pull request merged**
