### PR TITLE
[New] Add angular-file-saver w/ npm auto-update via single package.json

### PR DESCRIPTION
**Pull request by dmr-loggly**
cc @alferov

## Profile of the lib

* Git repository (required): https://github.com/alferov/angular-file-saver
* Official website (optional, not the repository): http://alferov.github.io/angular-file-saver/
* NPM package url (optional): https://www.npmjs.com/package/angular-file-saver
* License and its reference: MIT https://github.com/alferov/angular-file-saver/blob/master/license.md
* GitHub / Bitbucket popularity (required):
  * Count of watchers: 14
  * Count of stars: 210 
  * Count of forks: 57
* NPM download stats (optional):
  * Downloads in the last week: 10,356

## Essential checklist

* [ ] I'm the author of this library
  * [ ] I would like to add link to the page of this library on CDNJS on website / readme
* [x] This lib was not found on cdnjs repo
* [x] Doesn't already exist / has duplicate issue and PR
* [x] The lib has notable popularity
  * [x] More than 200 Stars on [GitHub / Bitbucket]
  * [x] More than 800 downloads stats per month on npm registry
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [x] Has valid tags for each versions (for git auto-update)
* [ ] Auto-update setup
* [ ] Auto-update target/source is valid.
* [ ] Auto-update filemap is correct.

## Git commit checklist

* [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [x] The parent of the commit(s) in the PR is not older than 3 days.
* [x] Pull request is sent from a non-master branch with a meaningful name.
* [x] Separate unrelated changes into different commits.
* [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [ ] Close corresponding issue in commit message
* [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by dmr-loggly** [comment]
I believe everything here should be correct, but I'm not 100% sure how to validate everything in the auto-update checklist.

**Comment by dmr-loggly** [comment]
@extend1994, I have ammended my commit to address your original comments.

**Comment by dmr-loggly** [comment]
Cheers! Thanks for your help, @extend1994.

**Comment by extend1994** [comment]
@dmr-loggly No problem 🎉

**Pull request merged**
