### PR TITLE
point cookiejar.js to cookiejar.min.js, #5195

### PR DESCRIPTION
**Pull request by LeaYeh**
Hi @Amomo  , From #5195, I add the minify files to each version of cookiejar, and point cookiejar.js to cookiejar.min.js in package.json.
Would you mind checking this PR for me? Thank you~ :-)

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
What's the reason why to touch ajax/libs/cookiejar/0.5/cookiejar.min.js?

**Comment by LeaYeh** [comment]
do not need to make same structure in each version?

**Comment by Amomo** [comment]
Hi @LeaYeh , sorry for late.
I think you need to separate your commit into 2 parts.
One is for adding minified version for v0.5 & v0.5.1, and another is for modify the "filename" field in package.json.

**Comment by PeterDaveHello** [comment]
> do not need to make same structure in each version?

What's the relation between making same structure in each version and touching unrelated file?

**Pull request closed without merging**
