### PR TITLE
point to a stable version v0.3.4 of json-mask

### PR DESCRIPTION
**Pull request by Amomo**
@Piicksarn , From #5276, I would like to fix json-mask to point to a stable version.
repo: https://github.com/nemtsov/json-mask
In cdnjs, json-mask has auto-update config, so it is the latest version now.
I only modify the field of version to a stable version `0.3.4`.
Would you mind checking this PR for me? Thank you~ :-)

- [ ] Not found on cdnjs repo : `json-mask`
- [ ] No already exist issue and PR : `#5276`
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Wrong syntax in the checklist.

**Comment by Amomo** [comment]
I'm trying to fix that. 😂

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you please take a look on the PR!
thank you ~

**Comment by PeterDaveHello** [comment]
Forgot to bump version here: https://github.com/cdnjs/cdnjs/commit/3323214ab3d090aa5dfceffa9d69d555853369b2#diff-041d0ccc57aa8b8eb08caf802b746780

**Pull request merged**
