### PR TITLE
Importer rita 1.1.19 [author] [new]

### PR DESCRIPTION
**Pull request by dhowe**
Files from: https://github.com/dhowe/RiTaJS/tree/master/dist

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@dhowe sorry for the late reply, the latest version on cdnjs is v1.1.51, could you please tag v1.1.19 so that the bot will automatically add it? Thanks.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by cqx931** [comment]
This PR was an old attempt to add ritajs to cdnjs and is no more needed.
ritajs has successfully been added to cdnjs in this PR https://github.com/cdnjs/cdnjs/pull/8446 in July 2016.

**Comment by PeterDaveHello** [comment]
Thanks @cqx931

**Pull request closed without merging**
