### PR TITLE
Add jquery-simulate@1.0.1 w/ git auto-update

### PR DESCRIPTION
**Pull request by sufuf3**
Pull request for issue: #
Related issue(s): #10444 #10036

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/jquery/jquery-simulate
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 20
   - Count of stars: 128
   - Count of forks: 89
 * NPM download stats (optional):
   - Downloads in the last day: 
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@cdnjs/intern3 please help me review this PR, thanks.

**Comment by sufuf3** [comment]
@hare1039 I cc to the main contributor, please help me review this PR, thanks.

**Comment by sufuf3** [comment]
@hare1039 @clairetsai818 please help me review this PR, thank you!

**Comment by kennynaoh** [comment]
@sufuf3 why did you cc #10036?

**Comment by sufuf3** [comment]
@kennynaoh the library of `slickgrid` (#10036 #10444) need add this library, but CDNJS didn't host this library. 
I think they have a relationship.
so I cc #10036

**Comment by kennynaoh** [comment]
@sufuf3 I think the reason is not clear. Is it necessary to open an another issue? What do you think?
cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
@sufuf3 I think you don't need to cc `#10036`. The main reason you mentioned in https://github.com/cdnjs/cdnjs/pull/10444#issuecomment-297875628. You should cc `#10444`.

**Comment by sufuf3** [comment]
@pvnr0082t I modified it. Please help me review this PR, again, thanks.

**Comment by maruilian11** [comment]
@PeterDaveHello I think this PR is ok.

**Comment by PeterDaveHello** [comment]
Please create another for this kind of library next time.

**Comment by maruilian11** [comment]
@PeterDaveHello create another what??

**Pull request merged**
