### PR TITLE
Add license of across-tabs

### PR DESCRIPTION
**Pull request by sashberd**
cc#5500

Pull request for issue: #5500 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:
   - Count of stars:
   - Count of forks:
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [X ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ X] The parent of the commit(s) in the PR is not old than 3 days.
 * [ X] Pull request is sending from a non-master branch with meaningful name.
 * [X ] Separate unrelated changes into different commits.
 * [X ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [X ] Close corresponding issue in commit message
 * [X ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sashberd** [comment]
@PeterDaveHello I would like to edit the check-boxes on #5500, cause they are outdated. Inside #5500 I attached text file with my revision

**Comment by PeterDaveHello** [comment]
@sashberd thanks. @extend1994 please help review and update it.

**Comment by extend1994** [comment]
@PeterDaveHello There is a question by @sashberd in https://github.com/cdnjs/cdnjs/issues/5500#issuecomment-329163215
> I made some work on referenced above libraries, here result.
Can I make one PR for all changes that I made or I should do one by one 😨
license-update.txt
At all I have 34 changes in all libraries above

I think it's okay to do the all license updates in one PR?

**Comment by PeterDaveHello** [comment]
@extend1994 It's fine to have them in a single PR.

**Pull request closed without merging**
