### PR TITLE
add labella v0.1.1 

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/twitter/labella.js
**Watch 73
  Star 3,066
 Fork 76**
@Amomo  could u help me check this PR for #6628 ? thank you!

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity 
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Why not to use http://twitter.github.io/labella.js/ as its homepage url?

**Comment by maruilian11** [comment]
@PeterDaveHello changed

**Comment by PeterDaveHello** [comment]
Use https thanks

**Comment by maruilian11** [comment]
@PeterDaveHello ok, done.

**Pull request merged**
