### PR TITLE
Add html-minifier with git auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
Pull request for issue: #9834 
@cdnjs/intern @cdnjs/intern2 Please help me review this PR, thanks!
There is no `dist` in npm package, so I chose to use git auto-update.
There is no bundle js file before v0.5.0.
Bundle files before v0.5.6 called `all.js`, I modify their name to `htmlminifier.js` to be the same with current files.

# Profile of the lib
 * Git repository (required): https://github.com/kangax/html-minifier
 * Official website (optional, not the repository): https://kangax.github.io/html-minifier/
 * NPM package url (optional): https://www.npmjs.com/package/html-minifier
 * GitHub / Bitbucket popularity (required): 
   Watch 71
   Star 1,984
   Fork 229
 * NPM download stats (optional):
   77,859 downloads in the last day
   461,926 downloads in the last week
   1,935,216 downloads in the last month

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
LGTM

**Comment by x09326** [comment]
@maruilian11 
Please rebase to the latest master branch.

**Comment by maruilian11** [comment]
@x09326 I have rebased the branch with the latest master branch, thanks!

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
So where is v0.4.3?

**Comment by maruilian11** [comment]
@PeterDaveHello `dist` appear after v0.5.0, so I didn't add versions before v0.5.0.

**Comment by PeterDaveHello** [comment]
@maruilian11 When do we add version depend on dist?  Never heard that.

**Comment by maruilian11** [comment]
@Piicksarn @cdnjs/intern2 I also add old versions 0.4.0 ~ 0.4.5, please help me review this PR, thanks!

**Comment by maruilian11** [comment]
@pvnr0082t I combine the two commits, thanks.

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
