### PR TITLE
add zooming@0.8.1 w/ npm auto-update

### LINKED ISSUE #10010: [Author] [Request] Zooming
**Library name:** Zooming
**Git repository url:** https://github.com/kingdido999/zooming
**npm package url(optional):** https://www.npmjs.com/package/zooming
**License(s):** MIT
**Official homepage:** http://desmonding.me/zooming/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by dada0423**
close #10010, cc @kingdido999

Pull request for issue: #10010
Related issue(s): # #
@pvnt0082t please review this PR, thank you
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/kingdido999/zooming
 * Official website (optional, not the repository):
 * NPM package url (optional):https://www.npmjs.com/package/zooming
 * License and its reference:MIT
 * GitHub / Bitbucket popularity (required):
   - Count of stars:309
   - Count of watchers:6
   - Count of forks:17
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@dada0423 You forgot to tag me. You need to check CI test status after you send pull request.

**Comment by dada0423** [comment]
@pvnr0082t please help me to review this PR thank you

**Comment by PeterDaveHello** [comment]
@dada0423 I think @pvnr0082t already approved your PR, and just waiting for a double review.

**Comment by PeterDaveHello** [comment]
@dada0423 as your mentor said, next time please don't forget to ask for review, or you'll need to update/rebase your PR, you should just wait for only 4 mins after you sent it and then you'll got the testing result, not a long time. I'll merge this PR this time.

**Comment by PeterDaveHello** [comment]
@pvnr0082t note that the old versions have different structure, you should better mention that in the review if you noticed it, especially for the newbies they cannot take care of it.

**Comment by pvnr0082t** [comment]
@PeterDaveHello Okay, I will be careful about that.

**Comment by pvnr0082t** [comment]
@dada0423 Please help add cdnjs version badge for the library. Thanks.

**Pull request merged**
