### PR TITLE
Add vue-ls w/ npm auto-update

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #10733 
Related issues: https://github.com/RobinCK/vue-ls/issues/5

@cdnjs/intern3 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/RobinCK/vue-ls
 * Official website (optional, not the repository): https://robinck.github.io/vue-ls/
 * NPM package url (optional): https://www.npmjs.com/package/vue-ls
 * License and its reference: [MIT](https://github.com/RobinCK/vue-ls/blob/master/LICENSE)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 2
   - Count of stars: 31
   - Count of forks: 4
 * NPM download stats (optional):
   - Downloads in the last day: 14
   - Downloads in the last week: 266
   - Downloads in the last month: 1,127

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by extend1994** [comment]
@pvnr0082t I didn't notice that, sorry! I will discuss with the author and report here, thanks.

**Comment by extend1994** [comment]
@pvnr0082t The author response is here: https://github.com/RobinCK/vue-ls/issues/5. He said we don't need `dist/vue-ls.esm.js` in v2.2.0~v2.2.12. Between these versions, some are on npm and will be gotten via auto-update, so I think I should add one line to `.gitignore` in another commit (other than current two commits and therefore it will be three commits)?

**Comment by pvnr0082t** [comment]
@extend1994 Can't we just exclude it in the rule?

**Comment by extend1994** [comment]
@pvnr0082t Yes we can, just forgot it! Now it should be fixed, please help me review it, thank you!

**Comment by maruilian11** [comment]
Looks like there are some versions which not added to git tags and npm package, but can be found in commits.
https://github.com/RobinCK/vue-ls/commit/02702596e36106a208884ec7cb74c55b9f5a606b

**Comment by PeterDaveHello** [comment]
@extend1994 can you add that?

**Comment by extend1994** [comment]
@maruilian11 @PeterDaveHello  According to https://github.com/RobinCK/vue-ls/commits/master?after=3965c450f86841666b28c3da6f9524342eb646ac+34, it seemed that only publish script in package.json changed between v2.2.1 and v2.2.2. They are commits https://github.com/RobinCK/vue-ls/commit/175ec6f0b78e61baca01c244ecfb0fbb22c3c427 and https://github.com/RobinCK/vue-ls/commit/a2beaf24ff4cf6915e56a01e118132f1a64fe3fe. So I think we don't need to add v2.2.1?

**Pull request merged**
