### PR TITLE
add jspanel3 w/ npm autoupdate

### LINKED ISSUE #8624: [Request] Add jsPanel3
**Library name:** jsPanel3
**Git repository url:https://github.com/Flyer53/jsPanel3
**npm package url(optional):** https://www.npmjs.com/package/jspanel3
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8624 
@kennynaoh @x09326 Please help me review this pull request, thank you.
Manually add versions 3.0.0-rc1.* from http://jspanel.de/downloads/jsPanel3-all-releases.zip because there is no minified files on git repo and npm.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/Flyer53/jsPanel3
 * Official website (optional, not the repository): http://jspanel.de/
 * NPM package url (optional): https://www.npmjs.com/package/jspanel3
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 24
   - Count of watchers: 4
   - Count of forks: 5
 * NPM download stats (optional):
   - Downloads in the last day: 5
   - Downloads in the last week: 87
   - Downloads in the last month: 268

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8624, cc @Flyer53

### CODE REVIEW

**Comment by kennynaoh** [comment]
Sorry for late response.
Please rebase to the latest master br.
Thanks!

**Comment by pvnr0082t** [comment]
@kennynaoh I have rebased it on the latest master branch. Please help me review it again, thank you.

**Comment by x09326** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM
ping @PeterDaveHello

**Pull request merged**
