### PR TITLE
add marginotes v0.1.0 with autoupdate config

### LINKED ISSUE #7322: [Request] Add  marginotes
**Library name:** marginotes
**Git repository url:** https://github.com/fdansv/marginotes

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #7322 
@PeterDaveHello Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/fdansv/marginotes
 * Official website (optional, not the repository): 
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 644
   - Count of watchers: 15
   - Count of forks: 24
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7322, cc @fdansv

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
There is no [git tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) in that repository, **but you checked the check list**, **git tag** is what our git auto-updater relys on, is there is no any valid tag, the updater can not recognized what are the correct versions we can use, and also, you can not make sure the specific versions. So please discuss with its author about that, thanks.

References:
 - https://git-scm.com/book/en/v2/Git-Basics-Tagging
 - https://help.github.com/articles/creating-releases/
 - https://help.github.com/articles/working-with-tags/

**Comment by pvnr0082t** [comment]
@PeterDaveHello Okay, I got it.

**Comment by pvnr0082t** [comment]
@PeterDaveHello The author of this library has already added the git tags.

**Comment by PeterDaveHello** [comment]
@pvnr0082t Nice, did you rebase your branch with our latest master branch? So that i can merge this.

**Comment by pvnr0082t** [comment]
@PeterDaveHello Yes, I did. Thank you.

**Comment by PeterDaveHello** [comment]
Seems there is new commits before the tagged version, so you need to update your file from upstream and re-minify it again.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I updated and re-minified the files.

**Comment by PeterDaveHello** [comment]
@pvnr0082t just wanna confirm with you, did you also regenerate the map file? Thanks.

**Comment by pvnr0082t** [comment]
@PeterDaveHello YES!

**Comment by PeterDaveHello** [comment]
@pvnr0082t Nice, thank you.

**Comment by fdansv** [comment]
@pvnr0082t @PeterDaveHello this is great guys, thank you so much :D

**Comment by PeterDaveHello** [comment]
@fdansv You're welcome, feel free to use our service, you can also consider to add this info in the readme :D

**Pull request merged**
