### PR TITLE
[New] Add clarity-ui@0.10.2 w/ npm auto-update

### PR DESCRIPTION
**Pull request by sufuf3**
Pull request for issue: #11600
Related issue(s): #11689 #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/vmware/clarity
 * Official website (optional, not the repository): https://vmware.github.io/clarity/
 * NPM package url (optional): https://www.npmjs.com/package/clarity-ui
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 103
   - Count of stars: 1744
   - Count of forks: 181
 * NPM download stats (optional):
   - Downloads in the last day: 1835
   - Downloads in the last week: 9914
   - Downloads in the last month: 38,838

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
Although the latest version is `v0.10.0-rc.1`, I think it not the stable version, but cdnjs can host, so I add `v0.9.16`.
Although GitHub versions more than npm, according to [Installing Clarity UI](https://github.com/vmware/clarity#installing-clarity-ui) it said Include the `clarity-ui.min.css` in HTML, and the files I can get from npm. (GitHub can't find the files)

**Comment by sufuf3** [comment]
@hare1039 @qwe19272375 @pvnr0082t @maruilian11
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@cdnjs/intern3 @pvnr0082t @maruilian11 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
updated the version @hare1039 @qwe19272375 @pvnr0082t @maruilian11
Please help me review this PR, Thank you.

**Comment by extend1994** [comment]
@sufuf3 Don't forget PR title.

**Comment by sufuf3** [comment]
Thanks

**Pull request merged**
