### PR TITLE
add license of selectivizr, cc #5500

### PR DESCRIPTION
**Pull request by dada0423**
https://github.com/keithclark/selectivizr/blob/master/selectivizr.js#L3
I have corrected already .please review
@pvnr0082t

### CODE REVIEW

**Comment by dada0423** [comment]
@pvnr0082t 
Please review this "add license work"

**Comment by pvnr0082t** [comment]
@dada0423 Please correct not only comment but __`commit message`__.

**Comment by pvnr0082t** [comment]
LGTM
ping @cdnjs/intern2

**Comment by kennynaoh** [comment]
LGTM

**Pull request merged**
