### PR TITLE
[New] Add recordrtc@5.4.6 w/ npm auto-update

### PR DESCRIPTION
**Pull request by thijstriemstra**
# Profile of the lib
 * Git repository (required): https://github.com/muaz-khan/RecordRTC.git
 * Official website (optional, not the repository): http://recordrtc.org/
 * NPM package url (optional): https://npmjs.org/package/recordrtc
 * License and its reference: MIT (https://github.com/muaz-khan/RecordRTC/blob/master/LICENSE)
 * GitHub popularity (required):
   - Count of watchers: 106
   - Count of stars: 1459
   - Count of forks: 618
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x ] This lib was not found on cdnjs repo
 * [ x] No already exist / duplicated issue and PR
 * [x ] The lib has notable popularity

### CODE REVIEW

**Comment by thijstriemstra** [comment]
ping @PeterDaveHello

**Comment by thijstriemstra** [comment]
@extend1994 ah stupid that I didn't see that before. I will close this as soon as #12139 is merged.

**Comment by thijstriemstra** [comment]
Duplicate of #12139

**Comment by PeterDaveHello** [comment]
Thanks, @thijstriemstra! Try another one if you'd like to :)

**Pull request closed without merging**
