### PR TITLE
Add license of ng-csv, cc #9248

### PR DESCRIPTION
**Pull request by jj528s35**
https://github.com/asafdav/ng-csv/blob/master/LICENSE

### CODE REVIEW

**Comment by pvnr0082t** [comment]
LGTM

**Comment by pvnr0082t** [comment]
@jj528s35 Please give a more meaningful branch name like `license-ng-csv` next time.

**Comment by pvnr0082t** [comment]
@jj528s35 Please tag me after you sent the PR. Thanks.

**Comment by x09326** [comment]
LGTM

**Pull request merged**
