### PR TITLE
[author][new] add cutback-js

### PR DESCRIPTION
**Pull request by jlaran**
Original Cutback-js URL: https://github.com/jlaran/cutback-js

### CODE REVIEW

**Comment by jlaran** [comment]
Hi, I want to know what is the error with my pull request? I need to upload my library ASAP. Please help!

**Comment by jlaran** [comment]
Could someone help me please?

**Comment by drewfreyling** [comment]
@jlaran unfortunately the library doesn't meet the popularity requirement in the readme.

**Comment by PeterDaveHello** [comment]
Oops, sorry for my late and missing, yep but as @drewfreyling says, it's popularity is too low on GitHub, if we missed anything else, please ping me and provide much more info about it.

**Pull request closed without merging**
