### PR TITLE
[New] Add jclic.js w/ git auto-update

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #10676
Related issue(s): #10707 #11170

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/projectestac/jclic.js
 * Official website (optional, not the repository): https://projectestac.github.io/jclic.js
 * NPM package url (optional): https://www.npmjs.com/package/jclic
 * License and its reference: [EUPL-1.1](https://github.com/projectestac/jclic.js/blob/master/LICENSE.txt)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 9
   - Count of stars: 5
   - Count of forks: 3
 * NPM download stats (optional):
   - Downloads in the last day: 5
   - Downloads in the last week: 442
   - Downloads in the last month: 730

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by extend1994** [comment]
@cdnjs/intern3 @dakshshah96 Please help me review this pull request, thank you.

**Comment by extend1994** [comment]
@maruilian11 @pvnr0082t Please help me review the pull request, thank you.

**Comment by extend1994** [comment]
ping @maruilian11 @pvnr0082t

**Comment by extend1994** [comment]
ping @maruilian11 @pvnr0082t

**Comment by extend1994** [comment]
ping @maruilian11 @pvnr0082t

**Comment by maruilian11** [comment]
How about `0.0.0` on npm package?

**Comment by extend1994** [comment]
@maruilian11 Refer http://semver.org/#spec-item-4
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

My considering is that 0.0.0 is released too early, so I didn't add it. Can you give some suggestions? Thank you.

**Comment by maruilian11** [comment]
@PeterDaveHello What do you think? I think we can still add `0.0.0`.

**Comment by frncesc** [comment]
Despite the 0.x version numbering, the [API](https://projectestac.github.io/jclic.js/doc/index.html) is stable and always backwards compatible between versions. New modules and functions may be added, but we don't plan to remove anything.

The "0" is here because few features of [JClic](https://projectestac.github.io/jclic/) (the Java authoring tool on which jclic.js is based) have not yet been implemented, like playing MIDI music files or using "custom skins", but core features can be considered finished at 99% (of course, always improveable!)

JClic.js is currently used in more than 2.000 packages of educational activities created by teachers, as you can see in: https://clic.xtec.cat/repo

We already have the module available via [unpkg](https://unpkg.com/jclic) and [JSDelivr](http://www.jsdelivr.com/projects/jclic.js), so It would be great if it were also in CDNJS.

Thank you!

**Comment by PeterDaveHello** [comment]
@frncesc Thanks for the updates.

**Comment by extend1994** [comment]
1. Use GitHub as the source because it has more complete versions than npm
2. Update pattern from `**/*` to `**/!(*.LICENSE)` because of `jclic.components.LICENSE` in v0.1.49 which was released 14 days ago.

**Comment by extend1994** [comment]
ping @maruilian11 @pvnr0082t

**Comment by PeterDaveHello** [comment]
@hare1039 take a look?

**Comment by maruilian11** [comment]
@extend1994 I can't fetch v1.0.49 with the auto-update config, can you do that? Thanks.

**Comment by PeterDaveHello** [comment]
@sufuf3 ⬆️ please help test it, thanks.

**Comment by extend1994** [comment]
@maruilian11 I can fetch that.

**Comment by maruilian11** [comment]
hmmm... that's a little wired. I can fetch all verions before `0.1.49`, but only `0.1.49` I can't fetch it. And no any error msg shows...

**Comment by PeterDaveHello** [comment]
@sufuf3 didn't I request test from you? Why did you just request from me?

**Comment by PeterDaveHello** [comment]
It's fine to not manually adding v0.0.0 as it's usually not a version.

**Comment by sufuf3** [comment]
Sorry.
Reply to https://github.com/cdnjs/cdnjs/pull/11608#issuecomment-333698134 I can fetch v0.1.49

**Comment by PeterDaveHello** [comment]
@sufuf3 thanks.

**Comment by frncesc** [comment]
Thank you very much to everyone!

**Pull request merged**
