### PR TITLE
[new] [author] Add preact

### PR DESCRIPTION
**Pull request by developit**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/developit/preact
 * Official website (optional, not the repository): https://preactjs.com
 * NPM package url (optional): https://www.npmjs.com/package/preact
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 3065
   - Count of watchers: 89
   - Count of forks: 83
 * NPM download stats (optional):
   - Downloads in the last day: 184
   - Downloads in the last week: 3,514
   - Downloads in the last month: 15,400

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit. \*
 * [ ] Close corresponding issue in commit message \*
 * [ ] Mention related issue(s), people in commit message, comment. \*

\* I used Github's web interface, since attempting to clone cdnjs in order to make the changes locally took over an hour.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Thanks @developit

**Comment by mohsen1** [comment]
@developit Can you also publish preact-compat please?

**Comment by developit** [comment]
@mohsen1 hmm - might be worth publishing a combined. Preact-compat depends on PropTypes, which is awkward to use from a CDN.

**Comment by mohsen1** [comment]
With H/2 it works beautifully. We are requiring super small modules from CDN. 

Also a quick question, if we are not using PropTypes (because of TypeScript) can we just avoid including it?

**Comment by developit** [comment]
@mohsen1 I believe so, yes. The checks would never run, so it would just be an unreferenced object.  I don't quite remember the process to get a lib added here but I'll look into it when I get a chance.

**Comment by mohsen1** [comment]
@developit 

I'm not familiar with the process of adding a new lib to CDNjs otherwise I would help. Can you take a look at adding preact compat to CDNjs? It would help our app a lot. Thanks!

**Pull request merged**
