### PR TITLE
[new] Add OpenDyslexic 2.1.0

### PR DESCRIPTION
**Pull request by TheTannerRyan**

### CODE REVIEW

**Comment by drewfreyling** [comment]
@PeterDaveHello what do you think of the git auto update here? The git tags don't match the version number provided here which I'm assuming @TheTannerRyan pulled from the `bower.json` file in the repo.

**Comment by TheTannerRyan** [comment]
@drewfreyling It is the correct version number seen confirmed by the original author: https://github.com/jsdelivr/jsdelivr/pull/3959

**Comment by drewfreyling** [comment]
@TheTannerRyan I have to agree with @jimaek here. The author makes no mention of the current version in the readme or via tags in the repo.

**Comment by PeterDaveHello** [comment]
Pulling from a non-official repo is a bad idea I think ...

**Pull request closed without merging**
