### PR TITLE
Add rowGrid.js w/ git auto-update via single package.json

### PR DESCRIPTION
**Pull request by ahsanbagwan**
Pull request for issue: #11513

 * Git repository: https://github.com/brunjo/rowGrid.js
 * License and its reference: MIT
 * GitHub popularity:
   - Count of watchers: 31
   - Count of stars: 643
   - Count of forks: 83

### CODE REVIEW

**Comment by sufuf3** [comment]
@ahsanbagwan Do you want to continue this PR?
Thank you.

**Comment by sufuf3** [comment]
@PeterDaveHello Should we close this PR?
Because there is no response from the contributor since Sep 10.
Thank you.

**Comment by sufuf3** [comment]
@PeterDaveHello There is no response from the contributor since 5 Aug.
And this is a beginner issue.
What can we do for this PR?
Many thanks.

**Comment by sashberd** [comment]
@sufuf3 I would like to continue this PR but I cannot do rebase to latest master. It provides me a lot of errors of pathing and merging. Could you help me to rebase to latest commit and I will continue from there? Thanks

**Comment by ahsanbagwan** [comment]
@sufuf3 Been tied up with personal stuff. My bad for not responding earlier.

**Comment by extend1994** [comment]
@sashberd Directly open another pull request might be a more efficient way to help add this library (It will take a lot of time to rebase).

@ahsanbagwan Thanks for your reply! I will close this PR for now, if you have time in the future and the library is still not added, it's very welcome to reopen the PR or open a new pull request for the library :+1: 

cc @PeterDaveHello

**Pull request closed without merging**
