### PR TITLE
add dash-shaka-playback w/ npm auto-update

### LINKED ISSUE #8205: [Request] Add dash-shaka-playback
**Library name:** dash-shaka-playback
**Git repository url:** https://github.com/clappr/dash-shaka-playback
**npm package url(optional):** https://www.npmjs.com/package/dash-shaka-playback
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #8205 
@pvnr0082t please help me review this pull request, thank you.
Manually add the old versions because there has different file name format
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/clappr/dash-shaka-playback
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/dash-shaka-playback
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 18
   - Count of watchers: 7
   - Count of forks: 3
 * NPM download stats (optional):
   - Downloads in the last day: 31
   - Downloads in the last week: 64
   - Downloads in the last month: 503

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8205, cc @leandromoreira

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@kennynaoh I didn't see any different naming scheme. Do I miss something?

**Comment by kennynaoh** [comment]
@pvnr0082t 
What you mean different naming scheme.
Sorry I couldn't get it.

**Comment by pvnr0082t** [comment]
@kennynaoh I mean I didn't see any different file name between different. So what's your "name format" mean?

**Comment by kennynaoh** [comment]
@pvnr0082t 
They are all minified file

**Comment by pvnr0082t** [comment]
@PeterDaveHello Can auto-updater support minified files does not named `*.min.js` like this case?

**Comment by leandromoreira** [comment]
> @PeterDaveHello Can auto-updater support minified files does not named *.min.js like this case?

Otherwise I can generate a *min.js if that's the case.

**Comment by PeterDaveHello** [comment]
I didn't see any naming problem here.

@kennynaoh you should not point the version to a non-stable version, btw v2.0.0 release, so please just add it.
@pvnr0082t nope, and we don't need to manually minify the files here, so there is not a problem.

@leandromoreira thanks, I think we don't need it :smile:

**Comment by kennynaoh** [comment]
Thanks @PeterDaveHello 
So I think I still need to add old version manually except the beta-version, right?
Because the auto-update will add old beta version automatically, and we don't need beta version.
Am I right?
Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh Nope, add them all or drop them all.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
So if the latest version isn't stable version in other case, we need to point previous version which is stable version.
Am I right?
Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh Of course, I think the document mentioned it for a long time.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
OK, thanks!

**Comment by kennynaoh** [comment]
@pvnr0082t 
I have pointed the stable version.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by pvnr0082t** [comment]
@kennynaoh multi-commit PR need multi reviewers. @x09326 Please help review this PR. Thanks.

**Comment by x09326** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
LGTM, @x09326 please merge it.

**Pull request merged**
