### PR TITLE
[New] Add recharts w/ npm auto-update

### PR DESCRIPTION
**Pull request by sufuf3**
Pull request for issue: #12227
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/recharts/recharts 
 * Official website (optional, not the repository): http://recharts.org
 * NPM package url (optional): https://www.npmjs.com/package/recharts
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 145
   - Count of stars: 7532
   - Count of forks: 546
 * NPM download stats (optional):
   - Downloads in the last day: 1961
   - Downloads in the last week: 50,596
   - Downloads in the last month: 222,178

# Essential checklist
 * [ ] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
1. Manually add v0.2.0 ~ v0.3.7 because the files is under `watch/js` which was generated by lib from `webpack.config.js`. And minify the files by PeterDaveHello/web-minify-helper.
```js
  return {
    entry: entries,

    output: {
      path: path.join(__dirname, 'watch/js'),
      filename: '[name].js',
      library: 'chart',
      libraryTarget: 'umd'
    },
```
2. Using the following pattern to get v0.4.5 ~ v0.5.0
```js
    {
      "basePath": "lib",
      "files": [
        "recharts*"
      ]
    }
```
The code for generating recharts.js is 
```js
  output: {
    path: path.resolve(__dirname, 'lib'),
    filename: 'recharts.js',
    library: 'Recharts',
    libraryTarget: 'umd',
  },
```
3. Using the following pattern to get the versions after v0.5.1 (https://github.com/recharts/recharts/blob/master/webpack.config.js#L8-L14)
```js
    {
      "basePath": "umd",
      "files": [
        "**/*"
      ]
    }
```

**Comment by sufuf3** [comment]
@extend1994 Using `watch/js` as the basePath is not a good idea because I thought we'd like use normal basePath to fetch the files, also using non-normal basePath would cause the maintenance complexity increasing in future I think, because as usual we use "" as the bathPath and the pattern is `watch/js/chart*`.
(As https://github.com/cdnjs/cdnjs/pull/11876#issuecomment-335065707 said)
What do you think?

As your comment, mention `front-end files` is a little bit weird I thought. Because all the files which be hosted on CDNJS can be used in web front-end, isn't it? I don't think we have to do this.
Actually, we have to exclude non-front-end files as default, don't we?
So, would you please tell me why we have to mention `front-end files` in commit message?

Thank you.

**Comment by extend1994** [comment]
For the first question, I just thought if you manually add some versions of the lib which don't fit auto-update configuration, why not also manually add the versions which fit auto-update but only for old versions. I believe it make complexity lowest. Still, I just express my opinion rather than request you to change it.

For the second question, `These files` is too ambiguous in my view. At first glance, I can't totally get what files are you pointing to. You can use other words other than `front-end files`, it's just a easy example.

**Comment by sufuf3** [comment]
@extend1994 I modified the second commit message as your require.
Please help me review this PR, thank you.

About removing the pattern which does to get the old versions v0.4.5 ~ v0.5.0 and manually adding them, I think it's not necessary because the pattern is used by us as usual, also the pattern still can grab the files. This can make the pattern more flexible, as https://github.com/cdnjs/cdnjs/pull/11439#issuecomment-312471744 said.
Thank you.

**Comment by sufuf3** [comment]
@extend1994 I modified as your require, please help me review this PR, thanks.

**Comment by PeterDaveHello** [comment]
I wonder how do we confirm that `watch/js` is what we need in the old versions?

**Comment by PeterDaveHello** [comment]
Ping @sufuf3

**Pull request merged**
