### PR TITLE
Update Matreshka.js repo url and auto-update filemap

### PR DESCRIPTION
**Pull request by finom**

### CODE REVIEW

**Comment by finom** [comment]
What's going on guys, is that my side issue?

**Comment by PeterDaveHello** [comment]
@finom seems not, but would you please update your commit message to be more clear? Something like :
`update repo url and auto-update filemap of matreshka`

Thanks

**Comment by finom** [comment]
@PeterDaveHello I've renamed pull request. Can I keep commit name as is? There are  too many files to clone (I used Github UI to change file).

**Comment by PeterDaveHello** [comment]
Nope, that's not a good commit message, if you won't mind, I'll manually pick the commit and modify its commit message.

**Comment by finom** [comment]
@PeterDaveHello I don't mind. Thanks.

**Comment by finom** [comment]
Thanks.

**Comment by PeterDaveHello** [comment]
np

**Pull request closed without merging**
