### PR TITLE
Add support for npm autoupdate and migrate packages

### PR DESCRIPTION
**Pull request by IonicaBizau**
Implements autoupdate via npm. Related: https://github.com/cdnjs/autoupdate/pull/29

Also, migrated packages.

Closes https://github.com/cdnjs/cdnjs/issues/5311

### CODE REVIEW

**Comment by IonicaBizau** [comment]
@PeterDaveHello Can you please check why tests are failing? `npm test` fails locally saying it cannot find file `X` which is fine.

It's unclear to me what's the specific error which appears here.

**Comment by PeterDaveHello** [comment]
@IonicaBizau Sure, I'll take a look at it!

**Comment by PeterDaveHello** [comment]
@IonicaBizau ths issue may be a little bit complex and need more time, since I never touch `test/auto-update-test.js` before (except few syntax refactor), and as you can see from its history:

* 9938828c108 refactor test/auto-update-test.js Peter Dave Hello 3 months ago
* 38f03f4a15d add a few tests, need more Misha Koryak 2 years, 8 months ago
* 4fbed1ede92 refactor code to be more testable Misha Koryak 2 years, 8 months ago

It's really seldom be touched ... I'll need more time to trace the code, really busy recently lol ...

Our new friend @petrgazarov may also be interested in this part, I believe that you both have better skill than me in javascript, it'll be very strong that we trace this together :smile:

**Comment by IonicaBizau** [comment]
@PeterDaveHello Ah, the error simply says: `ERROR: maximum time limit exceeded`... 😭

**Comment by PeterDaveHello** [comment]
@IonicaBizau That's another issue not related with the error mention, since there are too many libraries been touched, which is the situation we usually will not face in normal PR, so the default timeout is not enough for it, I'll improve this part in future.

**Comment by IonicaBizau** [comment]
@PeterDaveHello But how can we make tests to pass in this specific PR?

**Comment by PeterDaveHello** [comment]
@IonicaBizau In this situation, currently, I'll just modify the timeout limit, I'm rewriting this part of testing process to make it faster in future so that we don't need to manually modify the timeout for it.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Any progress on this?

**Comment by PeterDaveHello** [comment]
not yet 😢

**Comment by PeterDaveHello** [comment]
I just resolved some conflicts and the timeout issue first(and now there are more, lol ...), and trying to find out the reason why the error didn't show on CI, still working on finding out the problem you mentioned ...

**Comment by PeterDaveHello** [comment]
@pvnr0082t maybe you can also take a look and see if you can help.

**Comment by PeterDaveHello** [comment]
Sorry that I didn't have enough time to debug on this yet, but just to let you know that there is a bug been fixed in the origin npm auto-updater:
b14a3c2ac7d247f07901042a145a47c119ca3e40

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by IonicaBizau** [comment]
@PeterDaveHello Sorry, is there anything else I should do?

**Comment by PeterDaveHello** [comment]
@IonicaBizau sorry, the bot is just pinging the PRs without updates for 2 weeks, I didn't figure it out yet, maybe we can close this one until the problem been fixed, so you won't be pinged?

**Comment by IonicaBizau** [comment]
@PeterDaveHello Any progress on this?

**Comment by PeterDaveHello** [comment]
@IonicaBizau can you please fix the conflict? Just re-do the fixes on `package.json` may fix that, I'll dig the problem again after this, and see if we can merge it in few days, thanks a lot!

**Comment by IonicaBizau** [comment]
Um.. ok. Will check that out.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Can we finish this?

**Comment by MattIPv4** [comment]
@IonicaBizau / @PeterDaveHello any updates?

**Comment by IonicaBizau** [comment]
@PeterDaveHello Can we finish this?

**Comment by MattIPv4** [comment]
@IonicaBizau There are a huge number of conflicts, what is the plan?

**Comment by IonicaBizau** [comment]
What's the progress on this? Should we fix the conflicts and merge it?

The conflicts are simply from package.json files I guess.

**Comment by MattIPv4** [comment]
I honestly had forgotten this exists. @xtuc might be interested in this.

I think it's probably best if we split the commits up so that there is a commit just for changing the relevant JS logic (beyond https://github.com/cdnjs/autoupdate/pull/29), a commit for updating the docs, and then a new commit that fixes all the package.json files (scrapping the existing changes to avoid all these conflicts).

**Comment by xtuc** [comment]
Pushed the doc change here https://github.com/cdnjs/cdnjs/commit/d01b0019cc9736442089232ca7d43379f678730c

**Comment by MattIPv4** [comment]
This repository is now robot-only. We now support a single auto-update format, using the `autoupdate` attr previously used for git only. We will need to ensure all JSON files in cdnjs/packages are using the single new standard at some stage.

**Pull request closed without merging**
