### PR TITLE
Update jQuery-Impromptu to v6.2.1 (plus git and npm auto-update hooks)

### PR DESCRIPTION
**Pull request by uusijani**
Source of new version (v6.2.1): https://github.com/trentrichardson/jQuery-Impromptu

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please leave the indent alone, and remove `devDependencies` field, and we don't use double auto-update config, maybe you can remove npm auto-update config, thanks.

**Comment by uusijani** [comment]
Hi @PeterDaveHello, the issues you mentioned should now be fixed. (I'm making this comment in case you're not receiving notifications about the fix commits and test automaton pass, but do tell if more fixes are needed.)

**Comment by PeterDaveHello** [comment]
Please squash these commits into only one commit and rebase(sync) with our latest master branch, thanks.

**Comment by uusijani** [comment]
@PeterDaveHello done, hopefully right this time! Thanks for guiding me through this (it's my first pull request, in case you couldn't tell).

**Comment by PeterDaveHello** [comment]
Thanks.

**Pull request merged**
