### PR TITLE
[update] Change ajv package.json npm auo-update

### LINKED ISSUE #13315: [author] Is it ok to point ajv to ajv-dist package?
Currently, in order to work with cdnjs ajv includes the bundles into npm package.

It increases the bundle size: https://github.com/epoberezkin/ajv/issues/940

Is it possible to point ajv (https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/ajv/package.json) to ajv-dist package on npm https://www.npmjs.com/package/ajv-dist (so I can remove the bundles from ajv package).

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/72484904-author-is-it-ok-to-point-ajv-to-ajv-dist-package?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by epoberezkin**

### CODE REVIEW

**Comment by epoberezkin** [comment]
Could it please be merged?

**Comment by epoberezkin** [comment]
It is blocking epoberezkin/ajv#940

**Comment by extend1994** [comment]
Hi @epoberezkin 
So distributions would be  at `ajv-dist` package in the future, right?
I asked because I saw v6.10.1/v6.10.1 are only available on `ajv`.
Once we make sure that we can get future versions from new location `ajv-dist`, we can make merge happen :)

**Comment by epoberezkin** [comment]
@extend1994 thank you - I will update ajv-dist to auto-publish

**Comment by MattIPv4** [comment]
Versions aren't being published to ajv-dist, closing.

**Comment by epoberezkin** [comment]
@MattIPv4 sorry for the delay, I've finally come around to automating the chain - ajv releases are now pushed to ajv-dist, and ajv-dist to npm, so from Ajv v7 the bundles are only in ajv-dist.

Currently the bundle there is for v7.0.0-rc.5, and v7.0.0 is about to be released - it would be great to flip cdnjs before it.

Thank you!

**Comment by MattIPv4** [comment]
If you could make a PR in cdnjs/packages with the update, that'd be great 👍

**Comment by epoberezkin** [comment]
Thank you - it is here: https://github.com/cdnjs/packages/pull/543

**Pull request closed without merging**
