### PR TITLE
Autoupdate ionicons

### PR DESCRIPTION
**Pull request by tomsterritt**

### CODE REVIEW

**Comment by tomsterritt** [comment]
Somewhat confused now. I was previously told updating autoupdate config would be sufficient. What's wrong?

**Comment by PeterDaveHello** [comment]
I think you should take a look at the error message first, there is no version v2.0.1 in the repo, so you should not touch the version number here.

**Comment by tomsterritt** [comment]
I've reverted the change in version number. To clarify then, if I don't supply a new version of the code as well I don't update the version number, _only_ the autoupdate section?

**Comment by PeterDaveHello** [comment]
Yeah, the version field will be updated once we update with the real files.

**Comment by PeterDaveHello** [comment]
I think you should keep the origin structure in cdnjs, there are 4 folders:
css/  fonts/  png/  src/

**Comment by moesalih** [comment]
What's the status on this?

**Comment by PeterDaveHello** [comment]
Manually picked in 9319fe8 Autoupdate ionicons Tom Sterritt 4 months ago

**Pull request closed without merging**
