### PR TITLE
[new] add Buttons@2.0.0 with git auto-update, close #5285

### LINKED ISSUE #5285: [Request] Add Buttons
**Library name:** Buttons
**Git repository url:** https://github.com/alexwolfe/Buttons/
**Official homepage:** http://unicorn-ui.com/buttons/

### PR DESCRIPTION
**Pull request by Amomo**
Hi @LeaYeh  , I add a new lib with git auto-update from the request #5285
repo: https://github.com/alexwolfe/Buttons
Would you mind checking this PR for me? Thank you~ :-)

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `305`, Star `4476`, Fork `831`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by Amomo** [comment]
Hi @maruilian11  would you mind checking this PR for me?
Thank you~ :-D

**Comment by maruilian11** [comment]
@Amomo can i ask you why you consider `.css` to be the main file? thanks.
@PeterDaveHello i think it's ok.

**Comment by Amomo** [comment]
@maruilian11 oh! Because it's a CSS button library, it spend more effort on css style.
[Buttons](http://unicorn-ui.com/buttons/builder/) You can try it, really interesting~ 😁

**Comment by PeterDaveHello** [comment]
Should rebase ...

**Pull request merged**
