### PR TITLE
Update jquery.hoverintent auto-update config, close #11656

### LINKED ISSUE #11656: jquery.hoverIntent.js is not updated
I just worked with this library and I think that the file in cdnjs is not latest or updated, nevertheless the versions in the files are the same
You can compare this [file](https://github.com/briancherne/jquery-hoverIntent/blob/master/jquery.hoverIntent.js) with one stored at cdnjs

FYR

### PR DESCRIPTION
**Pull request by sashberd**
Pull request for issue: #11656
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:
   - Count of stars:
   - Count of forks:
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sashberd** [comment]
@sufuf3 @extend1994 
What wrong with spaces?... I  changed only  one row...

**Comment by sufuf3** [comment]
Need to remove extra spaces(two blank) in line head.
`            "jquery.hoverIntent*"` to `          "jquery.hoverIntent*"`

**Comment by sashberd** [comment]
@sufuf3 
It was like this in previous commit, and still it got failed status

**Comment by sufuf3** [comment]
Un maybe need to discuss at https://gitter.im/cdnjs/cdnjs
But my English is very poor. 

I have to call someone discusses at gitter together.
Or maybe at the same time( GMT +8, 21:50 ) 
What do you think?

**Comment by sashberd** [comment]
@sufuf3 
waiting for you in Gitter

**Comment by sashberd** [comment]
@extend1994 That what I did!

**Comment by sufuf3** [comment]
@sashberd would you try to separate the commit?
- The first commit is `Update jquery.hoverintent auto-update config, close #11656` (Just modify package.json)
- The second commit is 
```
Update jquery.hoverintent@1.9.0, cc #11656

Because there is a minified file from v1.9.0 of lib, let the minified file as the same with upstream.
```

But if you think this part is a little bother you.
Then maybe we can mention about what we do in this commit because it will be useful to us to trace the git logs.
And a good detail commit message always helps maintainer can know what this commit does.(https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project) 
such as the followings:
```
Update jquery.hoverintent auto-update config & v1.9.0

- Update auto-update config
- Update v1.9.0 because there is a minified file from v1.9.0 of lib, close #11656
```

What do you think?
Thank you.

except for this part, I think this PR looks good to me.

**Pull request closed without merging**
