### PR TITLE
Add roll@0.1.2 w/ npm auto-update

### LINKED ISSUE #10109: [Request] Add roll
**Library name:** roll
**Git repository url:** https://github.com/williamngan/roll
**npm package url(optional):** rolljs
**License(s):** Apache-2.0

### PR DESCRIPTION
**Pull request by qwe19272375**
Pull request for issue: #10109 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/williamngan/roll
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/rolljs
 * License and its reference: Apache-2.0, [ref](https://github.com/williamngan/roll/blob/master/LICENSE)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 29
   - Count of stars: 909
   - Count of forks: 60
 * NPM download stats (optional):
   - Downloads in the last day: 0
   - Downloads in the last week: 3
   - Downloads in the last month: 33

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #10109, cc @williamngan

### CODE REVIEW

**Comment by qwe19272375** [comment]
@pvnr0082t Please help me review this pull request, thank you.

**Comment by qwe19272375** [comment]
@pvnr0082t There are two files named `roll.js` and one of them already minified.
Should I minify both?

**Comment by pvnr0082t** [comment]
@qwe19272375 Sure, they don't look like the same file.

**Comment by qwe19272375** [comment]
@pvnr0082t `module/roll.min.js` and `module/roll.min.js.map` added, please help me review it, thank you.

**Pull request merged**
