### PR TITLE
add techan.js v0.6.0 with autoupdate config

### LINKED ISSUE #7588: [Request] Add smoothState.js
**Library name:** smoothState.js
**Git repository url:** https://github.com/miguel-perez/smoothState.js
**Official homepage:**  http://smoothstate.com/

### LINKED ISSUE #7595: [Request] Add techan.js
**Library name:** techan.js
**Git repository url:** https://github.com/andredumas/techan.js
**npm package url(optional):** n/a
**License(s):** MIT
**Official homepage:** http://techanjs.org/
**Wanna say something? Leave message here:** n/a

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by dannyxx001**
PR for #7595 
@pvnr0082t please help me review this pull request, thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/andredumas/techan.js
 * Official website (optional, not the repository): http://techanjs.org/
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 472
   - Count of watchers: 69
   - Count of forks: 132
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7595, cc @andredumas

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@dannyxx001 please mention the issue you are working for in the head of you first comment.

**Comment by PeterDaveHello** [comment]
You tagged the wrong person and the wrong issue.

**Comment by dannyxx001** [comment]
Sorry, I originally want to send another PR, so I tag wrong issue and person. ˊwˋ

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this pull request is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
Why don't you add the homepage info which was provided in the origin issue?

**Comment by dannyxx001** [comment]
OK, I have updated it. @pvnr0082t please help me review again, thanks.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this pull request is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
Thank you both.

**Pull request merged**
