### PR TITLE
[New] Add zensh-ui-autocomplete w/ git auto-update via single package.json

### LINKED ISSUE #8202: [Request] zensh/ui-autocomplete
**Library name:** ui-autocomplete
**Git repository url:** https://github.com/zensh/ui-autocomplete
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by sashberd**
close #8202, cc @zensh

Pull request for issue: #8202
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/zensh/ui-autocomplete/
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 7
   - Count of stars: 68
   - Count of forks: 41
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sashberd** [comment]
I'm getting ahead of your reviews about minified file version. As Angular developer I faced with problem when you do uglify on angular files. The problem is with annotation of angular dependency injection vars. In order to solve this problem, when I used Grunt with Uglify, I had to run ng-annotate Grunt task. I do not have such option inside my koala minifer tool. thus the file was not minifed.

**Comment by sashberd** [comment]
@sufuf3 I made PR via single package.json. FYR

**Comment by sufuf3** [comment]
@sashberd Would you squash the commit?
You can use `git rebase -i HEAD~2` to squash to one commit.
Thank you.

Except this part, everything looks good to me. 👍

**Comment by sashberd** [comment]
@sufuf3 The PR was squashed. Sorry for unsquashed PR. FYR

**Comment by sufuf3** [comment]
@maruilian11 @extend1994 Please help review this PR, thanks.

**Pull request merged**
