### PR TITLE
[new] Added allmighty-autocomplete@1.0.140706

### PR DESCRIPTION
**Pull request by geoperez**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I can't see the difference between your fork and the origin repo, we should pull from the origin one.

**Comment by geoperez** [comment]
The original doesn't have the package.json file and I changed a little bit the CSS.

**Comment by PeterDaveHello** [comment]
Package.json is not required to be in origin repo, and it makes no sense to use the same name.

**Comment by geoperez** [comment]
Ok, so how I can add this library?

**Comment by PeterDaveHello** [comment]
The better way is to confirm its version and point to the origin repo.

**Comment by geoperez** [comment]
Ok, I'll try to pull a request to origin with the minify versions. Thank you.

**Comment by PeterDaveHello** [comment]
Thanks.

**Comment by geoperez** [comment]
Pull Request in origin https://github.com/JustGoscha/allmighty-autocomplete/pull/86

**Comment by PeterDaveHello** [comment]
It's MIT license, I think you can use it directly, the reason why I don't take your fork is that I can't not find the obvious changing and you are use the same name as origin repo.

**Comment by geoperez** [comment]
Sorry but I'm not understanding you. How can I use it directly?

**Comment by PeterDaveHello** [comment]
You can just update package.json to point to its origin repo.

**Comment by geoperez** [comment]
Done, I updated the package.json

**Comment by PeterDaveHello** [comment]
Did you also change the files to its origin? Thanks.

**Comment by geoperez** [comment]
I'm waiting origin accepts my pull request.

**Comment by PeterDaveHello** [comment]
I think your PR to the origin repo can be in next release.

**Comment by geoperez** [comment]
OK, thanks

**Comment by PeterDaveHello** [comment]
So, are these files from the origin repo? I need to confirm that.

**Comment by geoperez** [comment]
Not yet, origin repo is not answering. Maybe I should remove this pull request and wait origin.

**Comment by PeterDaveHello** [comment]
Why not just send PR with origin files? I can merge it immediately.

**Comment by geoperez** [comment]
Ready the origin files.

**Comment by PeterDaveHello** [comment]
Would you please squash them into only one commit and rebase with our latest master branch? Thanks.

**Comment by geoperez** [comment]
I did the squash thing using git reset soft and commit, but I'm not really sure if i did it right. Apologies if I'm not doing well

**Comment by PeterDaveHello** [comment]
Seems not, would you please try again?

**Comment by geoperez** [comment]
I guess this is done.

**Comment by PeterDaveHello** [comment]
I'll need you to rebase with our latest master branch, ha.

**Pull request merged**
