### PR TITLE
[new] Add angular-material

### PR DESCRIPTION
**Pull request by int64ago**

### CODE REVIEW

**Comment by int64ago** [comment]
Can auto-update fetch old versions automatically if the version field is the latest version

**Comment by PeterDaveHello** [comment]
Yes, would you please take a look at angular-material.min.js? I don't think it's really minfied, seems comments are duplicated.

**Comment by int64ago** [comment]
It's official compressed version, I find that if comment is like this:
```
/*!
 something...
*/
```
Most of compressors can't remove comments after compression.
So I think it's better to leave minified version like this.
What do you think?

**Comment by PeterDaveHello** [comment]
Okay, thanks.

**Pull request merged**
