### PR TITLE
Manually add forge w/ npm auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
@cdnjs/intern2 Please help me review this PR, thanks!
I write a simple shell script to install each version of node-forge from npm package, and run `npm run minify` and `npm run bundle` to get `forge.min.js` and `forge.bundle.js`.

Pull request for issue: #6190 
Related issue(s): # #

# Profile of the lib
 * Git repository (required): https://github.com/digitalbazaar/forge
 * Official website (optional, not the repository): http://new.digitalbazaar.com/
 * NPM package url (optional): https://www.npmjs.com/package/node-forge
 * License and its reference: BSD-3-Clause, GPL-2.0, https://github.com/digitalbazaar/forge/blob/master/LICENSE
 * GitHub / Bitbucket popularity (required):
   Watch 101
   Star 1,741
   Fork 284
 * NPM download stats (optional):
   32,462 downloads in the last day
   180,577 downloads in the last week
   714,302 downloads in the last month

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by maruilian11** [comment]
@pvnr0082t 
1. versions before v0.2.23 didn't provide minify and bundle script, there are `forge.min.js`s in v0.2.0 ~ v0.2.13 originally. 
2. v0.2.25 can't be downloaded from npm pacakge.

**Comment by pvnr0082t** [comment]
@maruilian11 I use `pnpm i node-forge@0.2.25` and it can work. I think you can try it! :+1:

**Comment by maruilian11** [comment]
@pvnr0082t thank you! I have added v0.2.25.

**Comment by maruilian11** [comment]
@pvnr0082t I mentioned the it in commit msg.

**Comment by pvnr0082t** [comment]
@maruilian11 That's the step how you add them. I think you should mention the `reason` in the commit message.

**Comment by maruilian11** [comment]
@pvnr0082t is the reason ok?

**Comment by pvnr0082t** [comment]
@maruilian11 Yes, it looks good. :+1:  The same meaning as `there is no pre-built files`.

**Comment by PeterDaveHello** [comment]
1. Isn't the name "node-"forge menas for nodejs? Why don't we just use `forge`?
2. Have you take a look at https://github.com/digitalbazaar/forge-dist repository which is design for browser release?

**Comment by maruilian11** [comment]
@PeterDaveHello yes, I saw this repo before. sorry for not changing the lib name.
@cdnjs/intern2 please help me review this PR again, thanks!

**Comment by PeterDaveHello** [comment]
@maruilian11 So if you confirmed that we don't need it?

**Comment by PeterDaveHello** [comment]
PR title doesn't need to be updated?

**Comment by maruilian11** [comment]
>@maruilian11 So if you confirmed that we don't need it?

@PeterDaveHello do you mean the word "node"? or those old versions?
sorry for not changing the title.

**Comment by PeterDaveHello** [comment]
`forge-dist`

**Comment by maruilian11** [comment]
@PeterDaveHello yes, there is no pre-built files on `forge-dist` before tag 0.7.0, and I just saw the introduction about building pre-built files on npm package. So I used npm to build these files.
Do you prefer we change to use git auto-update instead?

**Comment by PeterDaveHello** [comment]
The concern is that is `node-` prefix in the npm package, and there is a forge`-dist` for browser release, so please confirm with the author about if we fetched to correct files from the correct source.

**Comment by maruilian11** [comment]
@PeterDaveHello this reference is mention in `forge-dist`, npm package `node-forge` can building the browser bundle with `npm install` and `npm run minify`, which is also the way I get these old version from npm.
https://github.com/digitalbazaar/forge-dist/tree/0.6.49#building-a-browser-bundle

Do we still need to confirm that?

**Comment by PeterDaveHello** [comment]
It's talking about the building process ... not about how you get it ... though its structure looks good, the concern I've said it's because the prefix of npm package and the browser release purpose repository.

**Comment by PeterDaveHello** [comment]
@maruilian11 btw, do not keep rebasing your branch, it helps nothing but makes spam to the person been mentioned ...

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by PeterDaveHello** [comment]
Pending too long, move to #11162

**Pull request closed without merging**
