### PR TITLE
Add chromatism@2.6.0 w/ npm auto-update

### LINKED ISSUE #11373: [Request] Add chromatism
**Library name:** chromatism
**Git repository url:** https://github.com/toish/chromatism#browser-without-bundling
**npm package name or url** (if there is one): https://www.npmjs.com/package/chromatism
**License (List them all if it's multiple):** ISC
**Official homepage:** 
**Wanna say something? Leave message here:**

### PR DESCRIPTION
**Pull request by dakshshah96**
close #11373, cc @toish

Pull request for issue: #11373 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/toish/chromatism
 * Official website (optional, not the repository): 
 * NPM package url (optional): https://www.npmjs.com/package/chromatism
 * License and its reference: ISC
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 20
   - Count of stars: 1,595
   - Count of forks: 26
 * NPM download stats (optional):
   - Downloads in the last day: 279
   - Downloads in the last week: 1,719
   - Downloads in the last month: 4,131

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by toish** [comment]
Thanks @dakshshah96 !

**Comment by toish** [comment]
@extend1994 Pre-v1.10.0 was set up as a CJS module, so those versions would be incompatible with the browser without a build step to handle common JS `require()` :(

**Comment by dakshshah96** [comment]
@PeterDaveHello What should we do about Pre-v1.10.0?

**Comment by toish** [comment]
@dakshshah96 In pre-v1.10.0, the script loads all the functions into the global scope, which is NOT ideal. But that wouldn't be a huge issue if it wasn't for the script trying to assign to `module.exports` at the bottom, which will throw an error. Is there anyway pre-v1.10.0 can be excluded? Those versions are not commonly used.

**Comment by dakshshah96** [comment]
@toish Yes, `module.exports` will throw an error. I think we should exclude pre-v1.10.0. Let's see what @PeterDaveHello has to say about it. :)

**Comment by PeterDaveHello** [comment]
@dakshshah96 Let's just exclude it, no problem.

**Pull request merged**
