### PR TITLE
Update Visibility.js to 1.2.4

### PR DESCRIPTION
**Pull request by ai**
@PeterDaveHello new version of Visibility.js (I am a author).

Wait for this PR before release.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@ai was the main filename changed?

**Comment by ai** [comment]
Sorry. I updated PR.

**Comment by PeterDaveHello** [comment]
@ai is it possible to setup the auto-update config here? So no more manaual updates needed.

**Comment by ai** [comment]
@PeterDaveHello I didn’t really develop this library, only support it. So I think we will have 1-3 releases in next few year. In this case, I think, auto-update config will take more time :)

**Comment by PeterDaveHello** [comment]
Sorry, I didn't get it, what do you mean "will take more time" here? Actually we hope all the libs have auto-update config which can decrease the workload of our maintainers, and you don't need to submit new PR, waiting for revuiew, the new versions will be available within just 30 mins after released, should be better.

**Comment by ai** [comment]
Could you accept this release first? It block version release ;).

**Comment by ai** [comment]
I don’t want to add auto-update config, because I think it will be the last Visibility.js release ;)

**Comment by ai** [comment]
Thanks =^_^=

**Pull request merged**
