### PR TITLE
Enrich hprose-html5's package.json(field: license)

### PR DESCRIPTION
**Pull request by bmiwdmb**
#5500

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Commit's parent was a little bit too old, it'll be better to rebase with our latest master branch before commiting and sending PR, thanks.

**Comment by bmiwdmb** [comment]
fix finshed. Please review the pull request!

**Comment by PeterDaveHello** [comment]
Would you please use the new format with SPDX license identifier for the license field as 7f1517b did? Thanks!

**Comment by bmiwdmb** [comment]
fix finshed. Please review the pull request!

**Comment by PeterDaveHello** [comment]
Great :+1:

**Pull request merged**
