### PR TITLE
add redux-saga@0.12.1 w/ npm autoupdate

### LINKED ISSUE #9501: [Request] Add Redux Saga
**Library name: redux-saga** 
**Git repository url: https://github.com/yelouafi/redux-saga**
**npm package url(optional): https://www.npmjs.org/package/redux-saga** 
**License(s): MIT**
**Official homepage: http://yelouafi.github.io/redux-saga/**
**Wanna say something? Leave message here: the author has provide a umdpkg and the build command in the package.json**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #9501 
@x09326 Please help me review this pull request, thank you.
There is no pre-built files before v0.3.0, I think we can ignore them.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/yelouafi/redux-saga
 * Official website (optional, not the repository): https://yelouafi.github.io/redux-saga/
 * NPM package url (optional): https://www.npmjs.com/package/redux-saga
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 4866
   - Count of watchers: 126
   - Count of forks: 317
 * NPM download stats (optional):
   - Downloads in the last day: 1426
   - Downloads in the last week: 32032
   - Downloads in the last month: 116079

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9501, cc @yelouafi

### CODE REVIEW

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by ian4hu** [comment]
@pvnr0082t Is there any document for build the minimized and non-minimized version for cdnjs or just run `npm build`?

And it will be good if there is a source-map for the built js.

**Comment by PeterDaveHello** [comment]
@ian4hu What is yhe reason why you need to "build" cdnjs?

**Comment by pvnr0082t** [comment]
@ian4hu Sorry, I didn't get you about build the minimized and non-minimized version. Is there any explanation? Thanks.

**Comment by ian4hu** [comment]
@pvnr0082t  @PeterDaveHello  I thought it the wrong way.

I thought cdnjs use a build script to fetch and **build** the package, but it just **fetch** it from npm.

**Pull request merged**
