### PR TITLE
add missing versions of prototype

### LINKED ISSUE #7909: [Request] missing versions of prototype
prototype doesn't provide prebuilt files in repo, so need to manually download from its website and add it.

https://github.com/sstephenson/prototype
http://prototypejs.org/download/

We can first add the missing version manually, and after that, maybe open issue to discuss is it possible to provide prebuilt files in the repo.

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #7909 
@kennynaoh Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/sstephenson/prototype
 * Official website (optional, not the repository): http://prototypejs.org/
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 3125
   - Count of watchers: 203
   - Count of forks: 564
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7909

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@pvnr0082t please tell us the process you added this missing versions for reviewing.

**Comment by pvnr0082t** [comment]
@kennynaoh @PeterDaveHello I downloaded ```prototype.js```(v1.5.0 - v1.6.1) from http://prototypejs.org/download/ manually. And minified the files.

**Comment by PeterDaveHello** [comment]
We should keep the structure consistent, I won't like to generate map file here.

**Comment by pvnr0082t** [comment]
@kennynaoh I have fixed minified files without map. Please help me review again, thank you.

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs#conventions
> Filenames should not include a version number.

**Comment by pvnr0082t** [comment]
@kennynaoh I have fixed filename for some versions. Please help me review again, thank you.

**Comment by PeterDaveHello** [comment]
@pvnr0082t please mention the version you added in the commit message.

**Comment by pvnr0082t** [comment]
@kennynaoh I have mentioned the versions in the commit message. Please help me review again, thank you.

**Comment by PeterDaveHello** [comment]
```
add missing versions of prototype, close #7909

(v1.5.0/v1.5.1/v1.5.1.1/v1.5.1.2/v1.6.0/v1.6.0.2/v1.6.0.3/v1.6.1)
```

**Comment by pvnr0082t** [comment]
@kennynaoh I have updated the commit message. Please help me review again, thank you.

**Comment by PeterDaveHello** [comment]
Maybe this is much more friendly to read, for next time:
`(1.5.0 / 1.5.1 / 1.5.1.1 / 1.5.1.2 / 1.6.0 / 1.6.0.2 / 1.6.0.3 / 1.6.1)`

**Pull request merged**
