### PR TITLE
Add hola-player@0.0.12 w/ npm autoupdate, closes #10131

### LINKED ISSUE #10131: [Request] Add hola-player
**Library name:** hola_player 
**Git repository url:** https://github.com/hola/hola_player
**npm package url(optional):** https://www.npmjs.com/package/@hola.org/hola_player
**License(s):** Apache 2
**Official homepage:** http://holacdn.com/player
**Wanna say something? Leave message here:**
I added previously library hola-video.js (https://github.com/cdnjs/cdnjs/pull/9640). And now it's actually the same library but renamed.

### PR DESCRIPTION
**Pull request by sreym**
Pull request for issue: #10131
Related issue(s): #9638

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/hola/hola_player
 * Official website (optional, not the repository): http://holacdn.com/player
 * NPM package url (optional): https://www.npmjs.com/package/@hola.org/hola_player
 * License and its reference: Apache 2
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 2
   - Count of watchers: 25
   - Count of forks: 1

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sreym** [comment]
Previously I added lib: #9640 and it has changed the name. Actually I'm not sure what is better way to do it. But previous library will not be updated at all. And actually can be removed.

**Comment by PeterDaveHello** [comment]
We will not remove the hosted one, if they are the same thing, maybe just change the auto-update source of the origin one?

**Comment by sreym** [comment]
It has changed a version order. So it might be broken in the future.

**Comment by PeterDaveHello** [comment]
We do not change the name and delete old versions, it'll break current user.

 So now you can see why we need to have popularity requirement, the large project never easily change their name since it'll cause some issues.

The case here, I'll do nothing until it reach the minimum population requirement, then we can add it as a new lib, that's more easy and fair IMO.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Pull request closed without merging**
