### PR TITLE
add hyperapp@0.1.0 w/ npm autoupdate

### LINKED ISSUE #10498: [Request] Add hyperapp
**Library name:** hyperapp
**Git repository url:** https://github.com/hyperapp/hyperapp
**npm package url(optional):** npmjs.com/package/hyperapp
**License(s):** MIT

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are too many files in this repo, without sparseCheckout, the whole process will be super slow, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
 - https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#d-adding-a-new-library

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄 .

### PR DESCRIPTION
**Pull request by honestree**
close #10498, cc @jbucaran 

Pull request for issue: #10498
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/hyperapp/hyperapp
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/hyperapp
 * License and its reference: https://github.com/hyperapp/hyperapp/blob/master/LICENSE
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 43
   - Count of stars: 1199
   - Count of forks: 71
 * NPM download stats (optional):
   - Downloads in the last day: 73
   - Downloads in the last week: 466
   - Downloads in the last month: 914

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
  * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
* [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by honestree** [comment]
@kennynaoh 
Please help me review this PR! thanks.

**Comment by honestree** [comment]
@kennynaoh
okay! I fixed the commit message!

**Comment by jbucaran** [comment]
@kennynaoh @honestree Thanks! Could you publish 0.1.0 instead? 

Also, I was wondering if cdnjs will automatically update based in the latest npm release?

**Comment by honestree** [comment]
@jbucaran 
Since I added the auto-update script in package.json, the robot would automatically update the library based on npm release.

**Comment by jbucaran** [comment]
@honestree That's great! 👍

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs/issues/10498#issuecomment-279219934

**Pull request closed without merging**
