### PR TITLE
Add stackicons@1.0 w/ git auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
Pull request for issue: #6092
Related issue(s): # #

# Profile of the lib
 * Git repository (required): https://github.com/parkerbennett/stackicons
 * Official website (optional, not the repository): http://stackicons.com
 * NPM package url (optional):
 * License and its reference: MIT, https://github.com/parkerbennett/stackicons/blob/master/LICENSE
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:39
   - Count of stars:957
   - Count of forks:125
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update) https://github.com/parkerbennett/stackicons/issues/15
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Do we really need `*.glyphs`?

**Comment by PeterDaveHello** [comment]
Why do we need `_source/font source`?

**Comment by maruilian11** [comment]
@PeterDaveHello does it cause my test fail?
```console
error: unable to create file ajax/libs/mathjax/2.2/fonts/HTML-CSS/TeX/png/SansSerif/Regular/100/0025.png (No space left on device)

**Comment by PeterDaveHello** [comment]
What's the reason why to remove auto-update config here?

**Comment by maruilian11** [comment]
@PeterDaveHello i didn't remove it, there is no tag on its repo.
https://github.com/cdnjs/cdnjs/issues/6092#issuecomment-162507185

**Comment by PeterDaveHello** [comment]
@maruilian11 ok.

**Comment by PeterDaveHello** [comment]
Please rebase your branch with latest master branch and tell me how did you get these files, what's the pattern you added the files in this commit.

**Comment by maruilian11** [comment]
@PeterDaveHello 
1. git clone lib repo
2. use git rebase to remove commits after  [Pushing Version 1.0](https://github.com/parkerbennett/stackicons/commit/285ed85e668495d6a57f5da9aee2f40425dc690f)
3. use git reset to unstage Pushing Version 1.0
4. use git status to look which files were modified
5. add those modified file as this commit

**Comment by PeterDaveHello** [comment]
Funny, why don't you just `git checkout 285ed85e668495d6a57f5da9aee2f40425dc690f` but use a complex process?

**Comment by maruilian11** [comment]
@PeterDaveHello ok, i will try it next time.

**Comment by PeterDaveHello** [comment]
Nope, use this step this time, your steps are too complex to valid.

**Comment by maruilian11** [comment]
@PeterDaveHello updated

**Comment by PeterDaveHello** [comment]
So tell me the pattern you grab this files, because there is no filemap in package.json.

**Comment by maruilian11** [comment]
@PeterDaveHello 
1. git clone lib repo
2. git checkout 285ed85e668495d6a57f5da9aee2f40425dc690f
3. git diff-tree --no-commit-id --name-only -r 285ed85e to look which files were modified
4. add those modified file as this commit

**Comment by PeterDaveHello** [comment]
This is not a pattern, the filemap in auto-update is.

**Comment by maruilian11** [comment]
@PeterDaveHello 
basePath: ""
`apple-touch-icon*.png`,
`css/+(fontviewer*|stackicons*|style*).css`,
`fonts/Stackicons/**/*.+(eot|svg|ttf|woff)`,
`icon.png`,
`img/*.png`,
` js/vendor/fontviewer*.js`

**Comment by maruilian11** [comment]
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
I don't think we need to host `apple-touch-icon*.png` or `icon.png`, maybe you can confirm with its author.

**Comment by maruilian11** [comment]
@cdnjs/intern2 please help me review this PR.

 * `apple-touch-icon*.png` and `icon.png` are for homepage website usage.
 * `logo-stackicons_340x40.png` is just the logo image, mentioned in readme.md.
 * `js` file is only for http://stackicons.com/stackicons-social-characters.html 
 * there is no tag, I still add git auto-update config for future.

**Comment by maruilian11** [comment]
I add 1.0 for https://github.com/parkerbennett/stackicons/commit/285ed85e668495d6a57f5da9aee2f40425dc690f

**Pull request merged**
