### PR TITLE
[new] Added ngreact@0.1.5

### PR DESCRIPTION
**Pull request by eseceve**

### CODE REVIEW

**Comment by drewfreyling** [comment]
I'm not sure we serve up `.jsx` files here. Tagging @PeterDaveHello for clarification.
Can you also squash your commits please?
Also, you will need to have a look at your npm map, adding .* will include files that we don't serve as well.

**Comment by PeterDaveHello** [comment]
I am not sure, and what's the source of the files?

**Comment by drewfreyling** [comment]
@thomasdavis do you know if we support .jsx files? @eseceve where did you get these files from?

**Comment by drewfreyling** [comment]
closed due to no response.

**Pull request closed without merging**
