### PR TITLE
Manually add missing versions of zingchart

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #9686

Add v0.0.1~v2.0.5 from git repo cause auto-update can't fetch them

git repo: https://github.com/zingchart/ZingChart
@cdnjs/intern3 Please help me review this pull request, thank you.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
hmmmm, the permission check on ci would only run on the latest version of the libs, @pvnr0082t you create an issue for it.

**Comment by extend1994** [comment]
@pvnr0082t I updated the files' permissions, please help me review it, thank you.

**Comment by extend1994** [comment]
@pvnr0082t Sorry...I didn't update it correctly, it should work now! Please help me review it, thank you.

**Comment by maruilian11** [comment]
@extend1994 Could you please tell me why you choose not add `zingchart-phantomjs-min.js` and `modules-phantomjs` folder.

**Comment by maruilian11** [comment]
I think you wanted to use `because`, not `cause` in your commit msg.

**Comment by extend1994** [comment]
@maruilian11 "cause" means the same as "because".

**Comment by PeterDaveHello** [comment]
`'cause` would be better, much more clear, cause may be ambiguous

**Comment by extend1994** [comment]
@maruilian11 @PeterDaveHello After I check the definitions of them, I chose to use "because" because " 'cause " or "cause" both are more informal expression.

**Comment by PeterDaveHello** [comment]
@extend1994 please also mention how did you actually get/grab these versions in more detail next time, thanks.

**Pull request merged**
