### PR TITLE
[New] Add tabellajs@0.4.1 w/ git auto-update

### LINKED ISSUE #9591: [Request] Add Tabella.js
**Library name:** Tabella.js
**Git repository url:** https://github.com/iliketomatoes/tabellajs
**License(s):** AGPL-3.0
**Official homepage:** https://iliketomatoes.github.io/tabellajs/

### PR DESCRIPTION
**Pull request by sashberd**
close #9591, cc @iliketomatoes, using koala tool for minifing css files

Pull request for issue: #9591
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/iliketomatoes/tabellajs
 * Official website (optional, not the repository): http://iliketomatoes.github.io/tabellajs/
 * NPM package url (optional):
 * License and its reference: AGPL-3.0
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 18
   - Count of stars: 192
   - Count of forks: 37
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by maruilian11** [comment]
And the repo's popularity is not enough so far, maybe we can wait for a while.

**Comment by sufuf3** [comment]
@maruilian11 the lib opened on 13 Nov 2016 and created by @PeterDaveHello 
The 200 stars rule is from this year.
I think add this lib is fine.
What do you think?

Thanks.

**Comment by sashberd** [comment]
@maruilian11 I think you are right. There is no need for images. I will remove them from PR

**Comment by sashberd** [comment]
@maruilian11 @sufuf3 The PR was updated. FYR

**Comment by sashberd** [comment]
@sufuf3 The PR was updated. FYR

**Comment by sashberd** [comment]
@sufuf3 The PR was updated. FYR

**Comment by sufuf3** [comment]
Would you please wrap the commit message body(`close #9591, cc @iliketomatoes, using web-minify-helper tool for minifying css files`) at 72 characters to follow 50/72 rule?
This is useful to maintain this huge project.
Thanks

**Comment by sashberd** [comment]
@PeterDaveHello May be I missed some thing but I do not see any changes that you are. So what should I do?

**Comment by PeterDaveHello** [comment]
@sashberd try to fetch the latest version again?

**Comment by sashberd** [comment]
@PeterDaveHello The file was fetched again. FYR

**Pull request merged**
