### PR TITLE
add license to eve.js

### PR DESCRIPTION
**Pull request by hsiaohsuan1l1l**
#6324

[ref](https://github.com/Yuffster/Eve.js/blob/master/MIT_LICENSE.txt)

### CODE REVIEW

**Comment by Amomo** [comment]
PR for #6324

**Comment by Amomo** [comment]
Hi @hsiaohsuan1l1l could you attach the reference of your commit?

**Comment by Amomo** [comment]
Hi @hsiaohsuan1l1l 
I can't find license info in your link, could you give me other reference?

**Comment by hsiaohsuan1l1l** [comment]
Is it OK now?

**Comment by Amomo** [comment]
Good! :+1:

**Pull request merged**
