### PR TITLE
update autoupdate config of leapjs

### PR DESCRIPTION
**Pull request by Piicksarn**

### CODE REVIEW

**Comment by drewfreyling** [comment]
Please add just the js files in question to the auto-update. Since they don't have a build or dist folder, we don't want to pickup random js files in the future that may not have anything to do with the release.

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs#conventions
Filenames should not include a version number.

**Comment by Piicksarn** [comment]
Is the solution right?

**Comment by PeterDaveHello** [comment]
Definitely not, maybe you can try npm auto-update instead of git repo.

**Comment by PeterDaveHello** [comment]
Any updates?

**Comment by drewfreyling** [comment]
Closing due to no response.

**Comment by PeterDaveHello** [comment]
@Piicksarn let's rebase and merge this. I'll modify it's filename manually.

**Comment by Piicksarn** [comment]
@PeterDaveHello, i have it rebased to master!

**Comment by PeterDaveHello** [comment]
Wrong commit message.

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you please have a look again at the pr? 
Thank you!

**Comment by PeterDaveHello** [comment]
@Piicksarn this PR is out-dated, currently, I'll need to to let it stat at npm auto-update, but change the file from `"leap.min.js"` to `"leap*.+(js|map)"`, hope we can finish this very soon.

**Comment by PeterDaveHello** [comment]
No need to do this transfer anymore.

**Pull request closed without merging**
