### PR TITLE
[New] Add videojs-background w/ npm auto-update

### LINKED ISSUE #9815: [Request] Add videojs-Background
**Library name:** videojs-Background
**Git repository url:** https://github.com/matthojo/videojs-Background
**License(s):** MIT

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39681440-request-add-videojs-background?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sashberd**
close #9815, cc @matthojo

Pull request for issue: #9815 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/matthojo/videojs-Background/tree/master
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/videojs-background
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 8
   - Count of stars:66
   - Count of forks:34
 * NPM download stats (optional):
   - Downloads in the last day: 0
   - Downloads in the last week: 16
   - Downloads in the last month: 99

# Essential checklist
 * [ ] I'm the author of this library
   * [X] I would like to add link to the page of this library on CDNJS on website / readme
 * [X] This lib was not found on cdnjs repo
 * [X] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [X] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [X] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X] The parent of the commit(s) in the PR is not old than 3 days.
 * [X] Pull request is sending from a non-master branch with meaningful name.
 * [X] Separate unrelated changes into different commits.
 * [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [X] Close corresponding issue in commit message
 * [X] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by maruilian11** [comment]
Hi @sashberd, this PR is great! Would you please move the adding old version part to the second commt? We hope they can be separated. Thanks.

**Comment by sashberd** [comment]
@extend1994  The version 1.02 and 1.0.6 are exists on npm
image

**Comment by extend1994** [comment]
@sashberd Yes they are. But the current auto-update config can not fetch then because there are no no `dist` folder in those two versions. `videojs-Background.js` is under `lib` in those versions. However, there are also `lib` folders in other versions. You might need to check if a user can use the files under `lib`.

**Comment by sashberd** [comment]
@extend1994 Ohhh.. you are right, I will add the manually

**Comment by sashberd** [comment]
@extend1994 The PR was updated

**Comment by sashberd** [comment]
@sufuf3 As for the number 2 in your list - I got feedback from @maruilian11 that there is no need to mention cc and number of related question in second commit, only in commit that close the issue (the main one - the first one), thus I am little bit confused - you says thing and another member vise versa... So what is the rule?

**Comment by sufuf3** [comment]
@sashberd Not sure which comment of @maruilian11 mention that.
But she also added old versions and cc issue number in commit message in the past.
Like https://github.com/cdnjs/cdnjs/pull/11204/commits

I thought this rule is good to follow.
What do you think?

And please manually add v1.0.2 and v1.0.6 from npm, because there are minified files from GitHub.
It's good to host the origin files from upstream, and we don't have to minify the files with minified tool by us.

Thanks.

**Comment by sashberd** [comment]
@sufuf3 I made the PR with manually added version only from npm. FYR

**Comment by sashberd** [comment]
@sufuf3 See the @maruilian11  PR [review](https://github.com/cdnjs/cdnjs/pull/12025) in web3 message.
image

**Comment by sufuf3** [comment]
Ummm...
@sashberd Thanks.
I thought she was kind to you that she did not require many rules to you, because you are a new activate contributor.
Through you sent many PR and you are looking forward to this project.
I though that if you know more about how to maintain a project, you will know that a good commit message is helpful to the maintainer to maintain, also good for everyone who watches this project via tracing git log.

And also she was right that we only `close #issue_number` in the first commit message, the `close` will close issue after the PR be merged. `cc #issue_number` just show the related issue in the commit message, it's good to mention it because you can see the commit in that issue page.

@maruilian11 I think not only "just" add old versions, but also cc issue number is better.
Like we sent the PR as usual in the past.
What do you think?

Many thanks.

**Comment by sashberd** [comment]
@sufuf3 Now I got it. From now I will add cc #issue_number to the manual version commits. This one will be also updated

**Comment by sashberd** [comment]
@sufuf3 ping

**Comment by sashberd** [comment]
@sufuf3 The PR was updated FYR

**Comment by sufuf3** [comment]
@sashberd would you mind revising as this [request](https://github.com/cdnjs/cdnjs/pull/12030#pullrequestreview-83968352)?
All of them did not be modified.
But this part is good for developers to have them.

Thanks for your great work.

**Comment by sashberd** [comment]
@sufuf3 I do not understand what is the problem. 
All parts of you previous review was updated and pushed.
e.g. Version were added, files were minified and @ was replaced with v
Can provide more detailed problem?
Thanks

**Comment by sufuf3** [comment]
1. The second [commit](https://github.com/cdnjs/cdnjs/pull/12030/commits)
```
Manually add videojs-background versions

@1.0.0~@1.0.2, @1.0.4, @1.0.6. Version were added from npm due to inconsitent folders struct for autoupdate configuration, cc #9815
```

Would you please change to 
```
Manually add videojs-background old versions

v1.0.0 ~ v1.0.2, v1.0.4, v1.0.6. Version were added from npm due to
inconsistent folders struct for auto-update configuration, cc #9815
```
?

2. There are no `videojs-background.min.js` in v1.0.2, v1.0.4, v1.0.6. Would you mind adding them from https://github.com/matthojo/videojs-Background/tree/v1.0.2/dist, https://github.com/matthojo/videojs-Background/tree/v1.0.4/dist, https://github.com/matthojo/videojs-Background/tree/v1.0.6/dist. As you can see there is just a `videojs-background.min.js` in v1.0.7. https://github.com/cdnjs/cdnjs/pull/12030/files

3. There is still no minified file in v1.0.0 ~ v1.0.1 -> https://github.com/cdnjs/cdnjs/pull/12030/files.

Many thanks.

**Comment by sufuf3** [comment]
Move to #12422

**Pull request closed without merging**
