### PR TITLE
add angular-signalr-hub w/ npm autoupdate

### LINKED ISSUE #8892: [Request] Add angular-signalr-hub
**Library name:** angular-signalr-hub
**Git repository url:** https://github.com/JustMaier/angular-signalr-hub
**npm package url(optional):** https://www.npmjs.com/package/angular-signalr-hub
**License(s):** MIT License
**Official homepage:** https://github.com/JustMaier/angular-signalr-hub
**Wanna say something? Leave message here:** Thanks!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8892 
@kennynaoh @x09326 Please help me review this pull request, thank you.
Manually add the other versions from git repo because npm auto-update can't get some of the old versions

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/JustMaier/angular-signalr-hub
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/angular-signalr-hub
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 237
   - Count of watchers: 31
   - Count of forks: 67
 * NPM download stats (optional):
   - Downloads in the last day: 45
   - Downloads in the last week: 267
   - Downloads in the last month: 1072

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8892 , cc @JustMaier

### CODE REVIEW

**Comment by kennynaoh** [comment]
@pvnr0082t 
What about the version `v1.5.1` on npm?

**Comment by pvnr0082t** [comment]
@x09326 @kennynaoh I missed that. I have added v1.5.1. Please help me review again, thank you.

**Comment by kennynaoh** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Pull request merged**
