### PR TITLE
Enrich label.css's package.json(field: license)

### PR DESCRIPTION
**Pull request by LeaYeh**
Hi @maruilian11 , 
From #5500, I have added license info.
repo : https://github.com/usablica/label.css
Would you mind checking this PR for me? Thank you~ :-)

- [ ] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `41`, Star `767`, Fork `53`**
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.

### CODE REVIEW

**Comment by maruilian11** [comment]
@LeaYeh could you tell me how you tell its license is MIT? thank you.

**Comment by maruilian11** [comment]
@LeaYeh  oh i see now. could you rebase and tag me again? thank you!

**Comment by LeaYeh** [comment]
ok, i already rebased it.
@maruilian11

**Comment by PeterDaveHello** [comment]
Not GPL? https://github.com/usablica/label.css/blob/master/sass/label.scss#L19

**Comment by LeaYeh** [comment]
@PeterDaveHello 
i recognized the repo is MIT license by [readme](https://github.com/usablica/label.css/blob/master/README.md#license), i am confused that you noticed me it has GPL license inside.
is it repo using both of them at same time? and then we should pick up the more strict one(GPL)?

**Comment by PeterDaveHello** [comment]
@LeaYeh You should confirm with its author

**Pull request merged**
