### PR TITLE
[New] Add milojs w/ npm auto-update

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #10340

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/milojs/milo
 * Official website (optional, not the repository): https://milojs.github.io/milo/
 * NPM package url (optional): https://www.npmjs.com/package/milojs
 * License and its reference: [BSD-2-Clause](https://github.com/milojs/milo#license)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 45
   - Count of stars: 63
   - Count of forks: 5
 * NPM download stats (optional):
   - Downloads in the last day: 0
   - Downloads in the last week: 2
   - Downloads in the last month: 229

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by extend1994** [comment]
1. Use npm as the source because it has newer versions. 
2. There is no `milo.bundle.map` in v0.0.3 ~ v0.1.9 & v1.6.1 because I manually minify milo.bundle.js in v0.0.3 ~ v0.0.7 & v0.1.1 ~ v0.1.10 and the author didn't generate it in v0.0.9/0.1.0 and v1.6.1.
3. Add this library according to https://github.com/cdnjs/cdnjs/issues/10340#issuecomment-326267506 though its insufficient popularity.

**Comment by sufuf3** [comment]
If we add old versions and future versions by auto-update config the `milo.bundle.js` still can be minified.
Also, I found that if we minify `milo.bundle.js`, `milo.bundle.min.js` is different from `milo.min.js`.

So should we minify `milo.bundle.js` or discuss with the author that should `milo.bundle.js` can rename to `milo.js`?
What do you think?

Thank you.

**Comment by extend1994** [comment]
@sufuf3 I don't think milo.bundle.min.js will exactly be the same with milo.min.js because the used method could be different.
@PeterDaveHello In the source repo, the minified file of milo.bundle.js is milo.min.js. Can we prevent milo.bundle.js from being minified?

**Comment by PeterDaveHello** [comment]
1. You should never rename the map, so do not rename them in this case.
2. As you can see here:
https://github.com/milojs/milo/blob/0.0.3/Gruntfile.js#L26

The minified files should be built from `milo.bundle.js` to `milo.js` using browserify, and browserify is not the same thing as minify.

**Comment by extend1994** [comment]
OK thank you!
I tried to `grunt` to generate `milo.js ` but failed. I got the message which is the same as the result of `grunt test`. Maybe there is something wrong. I will open an issue to check this.

**Comment by PeterDaveHello** [comment]
Check the corresponding nodejs and npm version and the dependency first.

**Comment by extend1994** [comment]
@PeterDaveHello Thank you for guiding. I just fixed the problem and passed `grunt test`. But according to the result of  `grunt`, I think `milo.bundle.js` is built from `milo.js`? Besides, I get the same result using `browserify lib/milo.js > milo.bundle.js`. If so, I think it's correct to minify `milo.bundle.js`? 
And see `Gruntfile.js` in master branch https://github.com/milojs/milo/blob/master/Gruntfile.js#L72-L84, it shows that the author use `uglify` package to minify `dist/milo.bundle.js` to `dist/milo.min.js` For the old versions I manually add, I think it's alright to rename `milo.bundle.js` to `milo.min.js`. But for the future versions, I am afraid that `milo.bundle.js` will be minified by bot.

**Comment by PeterDaveHello** [comment]
Tell me the environment you're using and I'll take a look.

**Comment by extend1994** [comment]
@PeterDaveHello 
Here my system infos: node v4.8.4, npm v2.15.11
Take v0.1.10 for example (from git repo and checkout)
First, I use `npm install` but the following message appears
```
karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.8.4","npm":"2.15.11"})
```

So I change to use node v1.8.4 ( npm is v2.9.0) using the command `nvm use v1` and the message doesn't appear again.
Second, after using the command `npm test`, it showas
```
>> Mocha exploded! 
>> Error: Cannot find module 'mol-proto'
...
```

By checking `package.json`, I found it comes from https://github.com/milojs/milo/blob/0.1.10/package.json#L41
```
"protojs": "git://github.com/milojs/proto.git"
```
Hence, I try to find a version corresponding milojs v0.1.10, which was tagged on Nov 20, 2014.
The result is proto v0.1.11 ( mol-proto on npm ). Ref: https://github.com/milojs/proto/blob/8b39222a555b896684983a63696fca4e3b7be264/package.json
After using the command `npm install mol-proto@0.1.11`, I pass `grunt test`.

About the relationship between `milo.bundle.js` and `milo.min.js`, according to https://github.com/milojs/milo/blob/0.1.10/Gruntfile.js#L21-L25, I think `milo.bundle.js` is built from `milo.js`. According to https://github.com/milojs/milo/blob/0.1.10/Gruntfile.js#L49-L61, I think the author use `uglify` to minify  `milo.bundle.js` to `milo.min.js`.
Please help me take a loot at it. Thank you!

**Comment by PeterDaveHello** [comment]
hmmm @sufuf3 can you help verify the issue?

**Comment by maruilian11** [comment]
@PeterDaveHello Can we set the auto-update bot not doing anything about minifying?

**Comment by PeterDaveHello** [comment]
Of course we can.

**Comment by maruilian11** [comment]
@extend1994 Maybe confirm with the author? What's the difference between using `uglify` and `browserify`?

**Comment by PeterDaveHello** [comment]
They have totally different function @maruilian11 I don't believe that you can't Google it can tell it.

**Comment by PeterDaveHello** [comment]
They have totally different function @maruilian11 I don't believe that you can't Google it can tell it. Uglify is for minification, browserify is for wrapping the script to work in a browser(compare to node.js engine).

**Comment by maruilian11** [comment]
@PeterDaveHello OK. Sorry I mistake something after seeing extend1994's comment.
@extend1994 What's your mean about:
>Or...maybe I should not build the files?
I think the we can just fetch the files in `dist` without any minifying. And add old versions manually?

**Comment by extend1994** [comment]
@maruilian11 I said that because I saw https://github.com/cdnjs/cdnjs/pull/11162#issuecomment-299638501

**Comment by maruilian11** [comment]
@PeterDaveHello So in this case, we just need to set the auto-update to fetch the built files?

**Comment by PeterDaveHello** [comment]
It's a little bit messy here, aren't we trying to prevent building assets by ourselves? Unless they are directly requested and we decided to do it, don't we just ignore the few versions need to be built manually?

**Comment by extend1994** [comment]
@PeterDaveHello How about just leaving the versions without minified files and needs manual building alone (Don't add those versions)? I think it will become much simpler.

**Comment by PeterDaveHello** [comment]
@extend1994 Sounds good.

**Comment by extend1994** [comment]
@cdnjs/library-reviewer @cdnjs/intern3 Please help review this PR, thanks!

**Comment by extend1994** [comment]
@maruilian11 I added v0.2.3 in Git repo. Please help review this. Thank you.

**Comment by extend1994** [comment]
ping @maruilian11

**Comment by maruilian11** [comment]
@extend1994 I think we still need to add `milo.bundle.js` from v0.0.3 ~ v0.1.10, right? And we don't need to manually built with official tool, just use `web-minify-helper` because the author minify `milo.bundle.js` to `milo.min.js` with `uglify`, too.

**Comment by extend1994** [comment]
@maruilian11 According to https://github.com/cdnjs/cdnjs/pull/11773#issuecomment-335067958 &  https://github.com/cdnjs/cdnjs/pull/11773#issuecomment-335067986, I think the answer to your question is "No". No need to add those versions.

**Comment by sufuf3** [comment]
Help rebase to the latest master.

As https://github.com/cdnjs/cdnjs/pull/11773#issuecomment-335067958 & https://github.com/cdnjs/cdnjs/pull/11773#issuecomment-335067986 , I think we don't have to add `milo.bundle.js` from GitHub or `mol-milo` from npm in v0.0.3~v0.0.7 & v0.1.1 ~ v0.1.10

Although `milo.bundle.js` can be used in web front-end. (the file can be minified by https://github.com/PeterDaveHello/web-minify-helper and generate milo.bundle.min.js and milo.bundle.min.js.map)
Thanks

**Comment by extend1994** [comment]
@PeterDaveHello Could you please help review this pull request? Thank you.

**Pull request merged**
