### PR TITLE
Add a project similar.

### PR DESCRIPTION
**Pull request by InputSimilar**
Project name: similar;
Version: 1.1.0;
Description: Keywords search box to achieve the recommended search
Accessibility.

Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/InputSimilar/similar
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of stars:
   - Count of watchers:
   - Count of forks:
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
Hi @InputSimilar ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail,

**Comment by InputSimilar** [comment]
Okay!

**Comment by InputSimilar** [comment]
@pvnr0082t **Similar** is a new project, it takes some time to be understood.

**Comment by pvnr0082t** [comment]
@InputSimilar Okay, let's wait for it.

**Comment by InputSimilar** [comment]
@pvnr0082t Can be combined in advance?

**Comment by pvnr0082t** [comment]
@InputSimilar Sorry, it's not my call. 
cc @PeterDaveHello

**Comment by InputSimilar** [comment]
@PeterDaveHello @pvnr0082t Can be combined in advance?

**Comment by PeterDaveHello** [comment]
What do you mean combined? I didn't get it.

**Comment by InputSimilar** [comment]
@pvnr0082t ,I expect that **Similar** projects can be incorporated into **CdnJS**, although **Similar** are not yet familiar. Thank you!

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by dakshshah96** [comment]
Hey @InputSimilar,

Since your library doesn't meet the minimum popularity requirements, I'm closing this PR right now. Thanks for wanting to be a part of cdnjs but we have limitations on what libraries we can host.

For your reference, the notable popularity criteria is — GitHub (more than 100 stars) and/or npm (more than 500 downloads per month).

Don't forget to ping any one of us once the library has notable popularity. All the best!

**Pull request closed without merging**
