### PR TITLE
Add WebGazer.js@1.0.0 w/ git auto-update

### LINKED ISSUE #11237: [Request] Add WebGazer.js
**Library name:** WebGazer.js
**Git repository url:** https://github.com/brownhci/WebGazer
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** GPL-3.0
**Official homepage:** https://webgazer.cs.brown.edu/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by dakshshah96**
close #11237, cc @Skylion007

Pull request for issue: #11237 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/brownhci/WebGazer
 * Official website (optional, not the repository): https://webgazer.cs.brown.edu/
 * NPM package url (optional):
 * License and its reference: GPL-3.0, LGPL-3.0
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 77
   - Count of stars: 1,788
   - Count of forks: 166
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@dakshshah96 Could you ask the author can add a tag for it?
Because CDNJS auto-update add by version tags of the library. And there is no git tags on GitHub repository of this library.

And I saw the `webgazer.js` need `ridgeWorker.js`, maybe we just need `webgazer.min.js` only. 
Because I saw this --> https://github.com/brownhci/WebGazer/blob/master/build/build_documentation 
I think maybe discuss with the author about that which files that CDNJS should host is better.

Thank you!

**Comment by PeterDaveHello** [comment]
@sufuf3 please draft and improve your comments before you sent it, this one is a little bit to understand ...

**Comment by dakshshah96** [comment]
@sufuf3 Done 👍 Waiting for author response now.

* Addition of git tags: https://github.com/brownhci/WebGazer/issues/58
* Filed which need to be hosted: https://github.com/brownhci/WebGazer/issues/59

**Comment by dakshshah96** [comment]
@sufuf3 Can you please add `waiting for response` label here?

**Comment by sufuf3** [comment]
@dakshshah96 There is still no response from the author.
But I think maybe we can try to discuss with the author by Email.
What do you think?
`Skylion.aaron@gmail.com` this is his email.
I search from https://github.com/Skylion007

If there is no response in 7 days, maybe we have to discuss how to do this PR.
Thank you.

**Comment by sufuf3** [comment]
@dakshshah96 
thanks for contribution.
Would you mind working on this, like send a email to the author to discuss the issue?
If you have any question, please let us know.

Many thanks.

**Comment by sashberd** [comment]
@sufuf3 @PeterDaveHello @extend1994 I do not think we can support [such configuration](https://github.com/brownhci/WebGazer/issues/59) in order to host this lib. What do you think?

**Comment by extend1994** [comment]
Agree, I don't think we can host this library because it doesn't have the pre-built files. @PeterDaveHello Can we just close it? Maybe reopen it when it has built files.

**Comment by PeterDaveHello** [comment]
@extend1994 sure

**Pull request closed without merging**
