### PR TITLE
Add prettycron@0.11.0 w/ git auto-update

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #10567
Related issue(s): azza-bazoo/prettycron#33, #4763

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/azza-bazoo/prettycron
 * Official website (optional, not the repository): https://azza-bazoo.github.io/prettycron/
 * NPM package url (optional): https://www.npmjs.com/package/prettycron
 * License and its reference: [LGPL-3.0](https://github.com/azza-bazoo/prettycron/blob/master/LICENSE.md)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 4
   - Count of stars: 54
   - Count of forks: 36
 * NPM download stats (optional):
   - Downloads in the last day: 92
   - Downloads in the last week: 533
   - Downloads in the last month: 3,743

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by extend1994** [comment]
@cdnjs/intern3 Please help me review this pull request, thank you.
Note I add the lib from GitHub because npm seemed outdated. For more details, please read related issues and #10567.

**Comment by extend1994** [comment]
@sufuf3 I think they are outdated and should not be added.

**Comment by extend1994** [comment]
@PeterDaveHello I added v0.9.0/v0.9.1 on npm, please help me review it, thank you.

**Comment by PeterDaveHello** [comment]
@extend1994 you need to add another "close" keyword before #4763 in the commit message.

**Comment by PeterDaveHello** [comment]
@pvnr0082t good to you or not?

**Pull request merged**
