### PR TITLE
add keywords in libs #5422

### PR DESCRIPTION
**Pull request by Piicksarn**
Affected libs( 13 libs):
  - [jquery-maskmoney](https://github.com/plentz/jquery-maskmoney/blob/master/bower.json)
  - [jquery-smooth-scroll](https://github.com/kswedberg/jquery-smooth-scroll/blob/master/bower.json)
  - [chosen](https://github.com/harvesthq/chosen/blob/master/package.json)
  - [css-spinning-spinners](https://github.com/BillyNate/css-spinning-spinners/blob/master/bower.json)
  - [drawer](https://github.com/blivesta/drawer/blob/master/bower.json)
  - [echarts](https://github.com/ecomfe/echarts/blob/master/bower.json)
  - [ember-charts](https://github.com/ecomfe/echarts/blob/master/bower.json)
  - [ember-computed-reverse]()
  - [es5-shim](https://github.com/es-shims/es5-shim/blob/master/bower.json)
  - [hopscotch]()
  - [html5-history-api]()
  - [jQuery-viewport-checker](https://github.com/dirkgroenen/jQuery-viewport-checker/blob/master/bower.json)
  - [jquery-bootpag](https://github.com/botmonster/jquery-bootpag/blob/master/bower.json)

### CODE REVIEW

**Comment by Amomo** [comment]
@Piicksarn I think your addition is fine, but please let the second line of commit message blank.

**Comment by PeterDaveHello** [comment]
And also, i think i asked you to tell us where did you get the keywords.

**Comment by Piicksarn** [comment]
@Amomo, i have already let the second line of commit message blank!
And also show the links where referenced by the keywords.
would you mind to check it again?
Thank you! :smiley:

**Comment by PeterDaveHello** [comment]
but you didn't rebase it with latest master branch

**Comment by Piicksarn** [comment]
@Amomo, would you mind to checkout the pr? thank you~!!

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine, could you take a look? Thank you!

**Pull request merged**
