### PR TITLE
Add react-chartjs-2@2.0.5 w/ npm auto-update

### PR DESCRIPTION
**Pull request by zduerr**
Pull request for issue: #10501 
Related issue(s): 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/gor181/react-chartjs-2
 * Official website (optional, not the repository): https://gor181.github.io/react-chartjs-2/
 * NPM package url (optional): https://www.npmjs.com/package/react-chartjs-2
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 17
   - Count of stars: 282
   - Count of forks: 67
 * NPM download stats (optional):
   - Downloads in the last day: 1,649
   - Downloads in the last week: 7,107
   - Downloads in the last month: 33,596

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by PeterDaveHello** [comment]
Oops, looks like I added it by myself, @zduerr would you be interested in picking another beginner issue? Sorry for the inconvenience caused.

**Comment by zduerr** [comment]
I thought this was approved already, sorry for not making the fixes.  I'll tackle another one, no problem.

**Comment by PeterDaveHello** [comment]
@zduerr Thanks

**Pull request closed without merging**
