### PR TITLE
update auto-update config of push.js

### PR DESCRIPTION
**Pull request by x09326**
PR for #8748 
@kennynaoh please help me review it,thanks.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@x09326 would you please try to exclude only the already known file we won't like to have? The current change may exclude other files.

**Comment by x09326** [comment]
@PeterDaveHello 
How about ```"push!(_tests.js)"```?

**Comment by PeterDaveHello** [comment]
Looks fine!

**Comment by x09326** [comment]
@kennynaoh 
I have modified the filemap.
Please help me review it, thanks.

**Pull request merged**
