### PR TITLE
add i18next git autoupdate and update keywords, close #5426 

### LINKED ISSUE #5426: [Request] Add i18next (upgrade)
**Library name: i18next** 
**Git repository url: https://github.com/i18next/i18next**
**npm package url(optional): i18next** 
**Official homepage: http://i18next.com/**
**Please upgrade to the latest version: 1.10.2 
currently: https://cdnjs.cloudflare.com/ajax/libs/i18next/1.6.3/i18next-1.6.3.min.js**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/i18next/i18next
**Watch 47
  Star 1,083
 Fork 180**
@LeaYeh could u help me check this PR for #5426? thank you!
i add some keywords from README.md.
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity 
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by maruilian11** [comment]
@Amomo could u help me check this PR? thank you very much!

**Comment by maruilian11** [comment]
@Amomo i have corrected it~ can you check it again? thank you!

**Comment by Amomo** [comment]
@maruilian11 I think your PR is fine this time, but it run into a system bug see #5538.
Could you re-send your commit again?

**Comment by maruilian11** [comment]
@Amomo thank you for your explaining :)

**Comment by Amomo** [comment]
@maruilian11 I think you may need to try some times till it pass. 😫

**Comment by maruilian11** [comment]
@Amomo could you help me check it again? thank you very much~~

**Comment by Amomo** [comment]
@maruilian11 sorry for finding it late...😨
I think you should separate your current commit into `"update keywords ..."` and `"add git autoupdate ..."` because they represent two different action.

**Comment by maruilian11** [comment]
@Amomo it's not late at all, i just add it haha. could you help me check it again? thank you very much~~

**Comment by Amomo** [comment]
Ummm... @maruilian11 could you make your commit message more clearly?
Because the key points of your commits are "adding the auto-update config" and "adding the keywords", you should put them in the starting in your message.
I think it will be more readable.

**Comment by maruilian11** [comment]
@Amomo is that ok?

**Comment by Amomo** [comment]
oh! @maruilian11 you should start with a verb, so please use `add` and `update`.

I was talking about your actions last time, so I said it as a noun...

**Comment by maruilian11** [comment]
@Amomo is that ok?

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine, could you take a look? Thanks~

**Pull request merged**
