### PR TITLE
Add simple-statistics package

### PR DESCRIPTION
**Pull request by tmcw**
Proposing the addition of simple statistics to cdnjs: it's a statistical programming library, with classifiers, regression, and the like.

* [Website](http://simplestatistics.org/)
* [Docs](http://simplestatistics.org/docs/)

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please also add the real files as the first commit to add a new lib, thanks!

**Comment by tmcw** [comment]
:+1: Added source files to the branch for 1.0.0

**Comment by PeterDaveHello** [comment]
Would you please squash them into only one commit as our document said? Thanks.

**Comment by tmcw** [comment]
Okay, working on it - is there any protip for working with the cdnjs git repo? Even with a fast computer & connection, it takes a long time to do any git command.

**Comment by PeterDaveHello** [comment]
Yes, see our sparse-checkout document.

**Comment by tmcw** [comment]
Okay - thanks, squashed the commits into one.

**Comment by PeterDaveHello** [comment]
Ping @cdnjs/intern to review this PR.

**Comment by LeaYeh** [comment]
Please check package.json again, you didn't pass the unit test. (see error in msg [Detial](https://circleci.com/gh/cdnjs/cdnjs/3498))

**Comment by tmcw** [comment]
Fixed - filename field is now added and filenames are corrected @LeaYeh

**Comment by PeterDaveHello** [comment]
@tmcw you can set the filemap to `**/*` next time!

**Pull request merged**
