### PR TITLE
[author][new] Ractive-Require 0.1.0

### PR DESCRIPTION
**Pull request by XavierBoubert**
From: https://github.com/XavierBoubert/ractive-require

**With npm auto-update**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Thanks, it'll be better to squash into only one commit next time.

**Comment by XavierBoubert** [comment]
Thans PeterDaveHello. How can I do that? I can't pull on my computer, the repo is too large (with _--depth 1_ too). I have made my commits directly on the GitHub website but I don't think we can commit more than one file at a time.

**Comment by PeterDaveHello** [comment]
I think we can only do that on local.

**Comment by XavierBoubert** [comment]
Ok thank you. ;-)

**Pull request merged**
