### PR TITLE
SAT.js #6642

### PR DESCRIPTION
**Pull request by goldenratio**
SAT.js #6642

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please also add auto-update config, and squash/fixup these commits into only one commit, thanks.

**Comment by goldenratio** [comment]
I need help with squash.

**Comment by goldenratio** [comment]
added auto updater

**Comment by PeterDaveHello** [comment]
> I need help with squash.

What kind of help do you need?

**Comment by maruilian11** [comment]
@goldenratio you can use `git rebase -i HEAD~5` :+1:

**Comment by goldenratio** [comment]
do I have to clone the whole project for that?

**Comment by PeterDaveHello** [comment]
Yes, please take a look at: [sparseCheckout.md](https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md), thanks.

**Comment by goldenratio** [comment]
Sorry don't have time for it. You can decline the PR.

I think there should be better solution to add JS lib to CDN. Probably a
web interface with required input fields, and all the PR magic is done
under the hood.

Regards,
Karthik

+372 53018096

**Comment by PeterDaveHello** [comment]
@goldenratio No problem, we can add by our side if this lib fits our requirement, please wait, thanks.

**Comment by PeterDaveHello** [comment]
Hello, any updates here? Thanks.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Pull request closed without merging**
