### PR TITLE
[new] add angularLocalStorage v0.3.0

### PR DESCRIPTION
**Pull request by Ryuno-Ki**
In [cooperation](agrublev/angularLocalStorage/issues/71) with @panuhorsmalahti I ask for adding [this library](https://github.com/agrublev/angularLocalStorage) to CDNjs.

I verified myself, that `npm test` passes (after running both, `npm install` for karma and `bower install` for dependencies).

The library isn't on NPM yet.

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
I don't understand the CI's error message:

```
    angularLocalStorage 
      ✗ angularLocalStorage package.json is valid 
        » angularLocalStorage didn't parse as any known format: 
  	  » NPM package.json 
  		Property is required (true): /properties/filename // valid-packages-test.js:81 
   
      ✗ angularLocalStorage: filename from package.json exists 
        » ./ajax/libs/angularLocalStorage/0.3.0/undefined does not exist but is referenced in package.json! // valid-packages-test.js:100 
  ✗ Broken » 5702 honored ∙ 2 broken (2.832s) 
  npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

npm test returned exit code 1
```

running `npm test` yields

```
> angularLocalStorage@0.3.0 test $HOME/src/angularLocalStorage
> ./node_modules/karma/bin/karma start --single-run --browsers PhantomJS

DEBUG [config]: autoWatch set to false, because of singleRun
DEBUG [plugin]: Loading karma-* from $HOME/src/angularLocalStorage/node_modules
DEBUG [plugin]: Loading plugin $HOME/src/angularLocalStorage/node_modules/karma-jasmine.
DEBUG [plugin]: Loading plugin $HOME/src/angularLocalStorage/node_modules/karma-phantomjs-launcher.
DEBUG [proxy]: createProxyHandler urlRoot=/
INFO [karma]: Karma v0.11.14 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
DEBUG [temp-dir]: Creating temp dir at /tmp/karma-15568649
DEBUG [launcher]: $HOME/src/angularLocalStorage/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs /tmp/karma-15568649/capture.js
DEBUG [watcher]: Resolved files:
	$HOME/src/angularLocalStorage/node_modules/karma-jasmine/lib/jasmine.js
	$HOME/src/angularLocalStorage/node_modules/karma-jasmine/lib/adapter.js
	$HOME/src/angularLocalStorage/components/angular/angular.js
	$HOME/src/angularLocalStorage/components/angular-cookies/angular-cookies.js
	$HOME/src/angularLocalStorage/components/angular-mocks/angular-mocks.js
	$HOME/src/angularLocalStorage/src/angularLocalStorage.js
	$HOME/src/angularLocalStorage/test/angularLocalStorage.spec.js
DEBUG [web-server]: serving: $HOME/src/angularLocalStorage/node_modules/karma/static/client.html
DEBUG [web-server]: serving: $HOME/src/angularLocalStorage/node_modules/karma/static/karma.js
DEBUG [web-server]: upgrade /socket.io/1/websocket/Pn_EquWc8uG0HC8sxYdM
DEBUG [karma]: A browser has connected on socket Pn_EquWc8uG0HC8sxYdM
INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket Pn_EquWc8uG0HC8sxYdM with id 15568649
DEBUG [launcher]: PhantomJS (id 15568649) captured in 0.854 secs
DEBUG [web-server]: serving: $HOME/src/angularLocalStorage/node_modules/karma/static/context.html
DEBUG [web-server]: serving (cached): $HOME/src/angularLocalStorage/node_modules/karma-jasmine/lib/jasmine.js
DEBUG [web-server]: serving (cached): $HOME/src/angularLocalStorage/test/angularLocalStorage.spec.js
DEBUG [web-server]: serving (cached): $HOME/src/angularLocalStorage/node_modules/karma-jasmine/lib/adapter.js
DEBUG [web-server]: serving (cached): $HOME/src/angularLocalStorage/components/angular/angular.js
DEBUG [web-server]: serving (cached): $HOME/src/angularLocalStorage/components/angular-cookies/angular-cookies.js
DEBUG [web-server]: serving (cached): $HOME/src/angularLocalStorage/components/angular-mocks/angular-mocks.js
DEBUG [web-server]: serving (cached): $HOME/src/angularLocalStorage/src/angularLocalStorage.js
PhantomJS 1.9.8 (Linux): Executed 14 of 14 SUCCESS (0.041 secs / 0.039 secs)
DEBUG [karma]: Run complete, exitting.
DEBUG [launcher]: Disconnecting all browsers
DEBUG [launcher]: Process PhantomJS exitted with code 0
```

which looks fine to me.

The NPM docs don't [say anything about property](https://docs.npmjs.com/files/package.json), too. Can someone assist me? Where does this `undefined` come from?

**Comment by PeterDaveHello** [comment]
Please add git auto-update config for it as #3638, and I'll need you to squash the current 2 commits into only one commit as our document said, thanks.

**Comment by Ryuno-Ki** [comment]
As stated above, the lib isn't hosted on npm (yet). So I don't know, where to place what.

I squashed both commits meanwhile.

**Comment by PeterDaveHello** [comment]
It has dist folder in its git repo, so we could use git auto-update as #3638 said.

**Comment by Ryuno-Ki** [comment]
Adjusted what I found in other projects. Of course already squashed.

**Comment by PeterDaveHello** [comment]
:+1:

**Pull request merged**
