### PR TITLE
update license info of libraries #1

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 

For #5544, I have update the license info of these 10 libraries.
- ScrollMagic　[ref](https://github.com/janpaepke/ScrollMagic/blob/master/LICENSE.md)
- UAParser.js　[ref](https://github.com/faisalman/ua-parser-js#license)
- bootstrap-rtl　[ref](https://github.com/morteza/bootstrap-rtl#license)
- chainvas　[ref](https://github.com/LeaVerou/chainvas/blob/master/chainvas.js#L4)
- classlist　[ref](https://github.com/eligrey/classList.js/blob/master/LICENSE.md#L1)
- crypto-js　[ref](https://code.google.com/p/crypto-js/)
- d3-geo-projection　[ref](https://github.com/d3/d3-geo-projection/blob/master/LICENSE)
- datatables-colvis　[ref](https://github.com/DataTables/ColVis/blob/master/js/dataTables.colVis.js#L15)
- datatables-fixedheader 　[ref](https://github.com/DataTables/FixedHeader/blob/master/License.txt#L1)
- django.js 　[ref](https://github.com/noirbizarre/django.js/blob/master/LICENSE)

Among of them, "bootstrap-rtl" and "classlist" choose to release into `"public domain"`.
So I note their license as `"Unlicense"`, according to this [doc](http://unlicense.org/).

Would you mind checking this PR for me? Thank you~ :-D

### CODE REVIEW

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Comment by PeterDaveHello** [comment]
As I said in #6576's comment, I need you to re-check all the license again first.

**Comment by Amomo** [comment]
@maruilian11 oops! because you comment on my old commit, the previous comment was gone.

You asked me to proof the license of "ScrollMagic".
Originally, I ref to its package.json.
Now, I ref to its `LICENSE.md`. Does this proof ok?

**Comment by maruilian11** [comment]
@Amomo sorry for saying the comment won't be deleted by force-push, they do disappear 😂

**Comment by PeterDaveHello** [comment]
Close due to no response.

**Pull request closed without merging**
