### PR TITLE
add mui v2.4.0

### PR DESCRIPTION
**Pull request by yepiaoyang**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars:
   - Count of watchers:
   - Count of forks:
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by yepiaoyang** [comment]
I'll do better next time

**Comment by PeterDaveHello** [comment]
@yepiaoyang Sure.

**Comment by PeterDaveHello** [comment]
@yepiaoyang did you just delete the forked repo again? It's not a good idea.
Would you please try to enable the sparse-checkout feature as our document says: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md ?
I believe this can help you.

**Comment by yepiaoyang** [comment]
Yes,it's my need.3ku

**Comment by PeterDaveHello** [comment]
Okay, so wait for your next PR, but please don't delete that repo again, thanks.

**Comment by yepiaoyang** [comment]
OKay. 
But 'core.sparsecheckout' work badly:
image

It looks like all file to be downloaded

**Comment by PeterDaveHello** [comment]
@yepiaoyang you are talking about cloning problem not checkout, that's different, but I think you can try one thing: just work on GitHub without cloning the repo, what do you think?

**Pull request closed without merging**
