### PR TITLE
add bytes@2.4.0 w/ npm autoupdate

### LINKED ISSUE #8560: [Request] bytes.js
**Library name:** bytes.js
**Git repository url:** https://github.com/visionmedia/bytes.js
**npm package url(optional):** https://www.npmjs.com/package/bytes
**License(s):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8560 
@kennynaoh Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/visionmedia/bytes.js
- Official website (optional, not the repository):
- NPM package url (optional): https://www.npmjs.com/package/bytes
- GitHub / Bitbucket popularity (required):
  - Count of stars: 130
  - Count of watchers: 9
  - Count of forks: 22
- NPM download stats (optional):
  - Downloads in the last day: 122,070
  - Downloads in the last week: 2,124,136
  - Downloads in the last month: 8,919,440 
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [x] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [x] More than 500 downloads stats per month on npm registry
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

close #8560, cc @dougwilson

### CODE REVIEW

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Comment by PeterDaveHello** [comment]
Does this work in browsers? It says "**node** byte string parser" on the GitHub page.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello as this comment https://github.com/visionmedia/bytes.js/issues/37#issuecomment-247835271
It seems that they are not really interested in putting lib on CDNJS.
What can we do for this PR?
Close it? or discuss with the author again?

Thank you.

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs/issues/8560#issuecomment-328882560

**Pull request closed without merging**
