### PR TITLE
Updating git repo and homepage url in jquery-contextMenu's package.json 

### PR DESCRIPTION
**Pull request by Piicksarn**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Can you make another commit to update its url of homepage?

**Comment by Piicksarn** [comment]
@maruilian11, would you please checkout the pr for me?
The commits before are "enrich package.json" and "update homepage url".
I squash two commits into one, as both of them relate to enriching package.json.
Thank you!

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Comment by PeterDaveHello** [comment]
This is not an enrich. Please update your commit message.

**Comment by Piicksarn** [comment]
@PeterDaveHello, i have it corrected!

**Comment by PeterDaveHello** [comment]
No you didn't ...

**Comment by Piicksarn** [comment]
@maruilian11, would you please take a look again? thank you :kissing_closed_eyes:

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Comment by PeterDaveHello** [comment]
need rebase ...

**Comment by Piicksarn** [comment]
@maruilian11, would you please checkout the pr again?
thank you!

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Pull request merged**
