### PR TITLE
[new] add onepage-scroll@1.3.1 with git auto-update, close #5013

### LINKED ISSUE #5013: [Request] One Page Scroll
CDN for https://github.com/peachananr/onepage-scroll

### PR DESCRIPTION
**Pull request by Amomo**
Hi @Piicksarn , I add a new lib with git auto-update from the request #5013 
This lib is lack of a minified css file, so I add one.
I have recorded it in the "requiredFile" field.
Would you mind checking this PR for me? Thank you~ :-)

### CODE REVIEW

**Comment by Piicksarn** [comment]
mm..I'm not sure about line 31~33, I haven't used this format before.
@PeterDaveHello ...I wonder the "requiredFile" is really needed?

**Comment by PeterDaveHello** [comment]
Yes we need.

**Comment by Piicksarn** [comment]
@Amomo after you rebasing to master, we can ask Peter to check:^)

**Comment by Amomo** [comment]
Hi @Piicksarn , It has rebased with latest master branch now.
Could you take a look?

**Comment by Piicksarn** [comment]
It's fine!
@PeterDaveHello, would you take a look for the commit?

**Comment by PeterDaveHello** [comment]
You said that you rebased 6 hours ago, but the commit's parent was 12 hours ago ...

**Pull request merged**
