### PR TITLE
[author] [new] Adds Freewall

### PR DESCRIPTION
**Pull request by tonytlwu**
https://github.com/kombai/freewall

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Would you please also setup auto-update config for it? Thanks.

**Comment by tonytlwu** [comment]
auto-update config has been added to package.json

Thanks.

**Comment by PeterDaveHello** [comment]
Didn't see it.

**Comment by tonytlwu** [comment]
Sorry. Updated the wrong file. Give it a check now :)

**Comment by PeterDaveHello** [comment]
Would you please squash them into only one commit as our document said? Thanks!

**Pull request closed without merging**
