### PR TITLE
Add vimeo.ga.js@0.6 w/ git auto-udpate

### LINKED ISSUE #8085: [Request] Add vimeo.ga.js
**Library name:** vimeo.ga.js
**Git repository url:**https://github.com/sanderheilbron/vimeo.ga.js
**npm package url(optional):** 
**License(s):**MIT
Copyright © 2015 Sander Heilbron.
**Official homepage:**https://www.sanderheilbron.nl/vimeo.ga.js/

**Wanna say something? Leave message here:**

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by x09326**
PR for #8085 
@pvnr0082t @kennynaoh please help me review it, thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/sanderheilbron/vimeo.ga.js
 * Official website (optional, not the repository):https://github.com/sanderheilbron/vimeo.ga.js
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars:78
   - Count of watchers:12
   - Count of forks:57
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8085, cc @sanderheilbron

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@x09326 I think you can manually add old versions from `v0.1` to v`0.6` because the [change log](https://github.com/sanderheilbron/vimeo.ga.js#changelog) shows that there has `v0.1`, `v0.2` and `v0.3` but not tagged. Thanks.

**Comment by x09326** [comment]
@pvnr0082t 
I have added them.
Please help me review it, thanks.

**Comment by pvnr0082t** [comment]
@x09326 You need to `cc #8085` in the second commit message.

**Comment by pvnr0082t** [comment]
Multi-commit PR need multi-reviewer.

**Comment by x09326** [comment]
I have modified the commit message.
@pvnr0082t @kennynaoh 
Please help me review it, thanks.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM

**Comment by kennynaoh** [comment]
ping @PeterDaveHello

**Pull request merged**
