### PR TITLE
Add data-layer-helper@0.1.0 w/ npm auto-update

### LINKED ISSUE #8188: [Request] Add data-layer-helper
**Library name:** data-layer-helper
**Git repository url:** https://github.com/google/data-layer-helper
**npm package url(optional):** https://libraries.io/npm/data-layer-helper
**License(s):** Apache 2.0
**Official homepage:** 
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/34985136-request-add-data-layer-helper?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by x09326**
PR for #8188 
@pvnr0082t please help me review it, thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required):https://github.com/google/data-layer-helper
- Official website (optional, not the repository):
- NPM package url (optional):https://www.npmjs.com/package/data-layer-helper
- GitHub / Bitbucket popularity (required):
  - Count of stars:132
  - Count of watchers:44
  - Count of forks:29
- NPM download stats (optional):
  - Downloads in the last day:0
  - Downloads in the last week:5
  - Downloads in the last month:21
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [x] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [ ] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

close #8188, cc @bnkuhn

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@x09326 I think `data-layer-helper.js` is already a minified file. You don't need to minify it again.

**Comment by x09326** [comment]
@pvnr0082t 
I remove them.
Please help me review it again, thanks.

**Comment by PeterDaveHello** [comment]
Is this a official npm package? Looks not.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello there is no response from the upstream since 21 Jun.
Should we still wait for the author's reply?
Or close this PR, because there is no git tag?

Thank you.

**Pull request closed without merging**
