### PR TITLE
Add sjcl w/ npm autoupdate & update version

### LINKED ISSUE #8853: [Request] SJCL 1.0.4
**Library name: sjcl** 
**Git repository url: https://github.com/bitwiseshiftleft/sjcl**
**npm package url(optional):** https://www.npmjs.com/package/sjcl
**License(s): BSD-2-Clause / optionally GPL 2.0** ([See LICENSE.txt](https://github.com/bitwiseshiftleft/sjcl/blob/master/LICENSE.txt))
**Official homepage: https://bitwiseshiftleft.github.io/sjcl/**
**Wanna say something? Leave message here: This needs to be updated to 1.0.4.**

### PR DESCRIPTION
**Pull request by x09326**
PR for #8853, #5500
@pvnr0082t @kennynaoh 
Please help me review it, thanks.

# Profile of the lib
 * Git repository (required):https://github.com/bitwiseshiftleft/sjcl
 * Official website (optional, not the repository):
 * NPM package url (optional):https://www.npmjs.com/package/sjcl
 * GitHub / Bitbucket popularity (required):
   - Count of stars:3517
   - Count of watchers:212
   - Count of forks:476
 * NPM download stats (optional):
   - Downloads in the last day:669
   - Downloads in the last week:3489
   - Downloads in the last month:13456

close #8853, cc #5500

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@x09326 I think you can do commits as following:
- add sjcl@1.0.6 w/ npm autoupdate and modify version info
- add license info of sjcl

**Comment by pvnr0082t** [comment]
We just need to `close #8853` one time in commit message and `cc` the issue in other commits.

**Comment by x09326** [comment]
@pvnr0082t 
I have modified commits.
Please help me review it.

**Comment by x09326** [comment]
@pvnr0082t 
I have fixed the commit message.
Please help me review it again, thanks.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
Is [this](https://bitwiseshiftleft.github.io/sjcl/) can be `homepage`?

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@kennynaoh , it can, please do not manually generate hyper link, just paste it, so that we can read the address directly, thanks.

**Comment by PeterDaveHello** [comment]
@x09326 good job :+1: Making old libs up to date is always much more important than keep adding new libs!

**Pull request merged**
