### PR TITLE
[New] Add react-dropzone@4.2.8 w/ npm auto-update

### LINKED ISSUE #12189: [Request] Add react-dropzone
**Library name:** react-dropzone
**Library description:** Simple HTML5 drag-drop zone with React.js.
**Git repository url:** https://github.com/react-dropzone/react-dropzone
**npm package name or url** (if there is one): https://www.npmjs.com/package/react-dropzone
**License (List them all if it's multiple):** MIT
**Official homepage:** https://react-dropzone.js.org/

its mit license, as well as having 3k+ stars

### PR DESCRIPTION
**Pull request by sufuf3**
close #12189 

Pull request for issue: #12189
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/react-dropzone/react-dropzone
 * Official website (optional, not the repository): https://react-dropzone.js.org/
 * NPM package url (optional): https://www.npmjs.com/package/react-dropzone
 * License and its reference: [MIT](https://github.com/react-dropzone/react-dropzone/blob/master/LICENSE)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 55
   - Count of stars: 3683
   - Count of forks: 392
 * NPM download stats (optional):
   - Downloads in the last day: 17697
   - Downloads in the last week: 122,747
   - Downloads in the last month: 532,953

# Essential checklist
 * [ ] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
1. I get the files from npm, because the files can be used in front-end.
2. Exclude the files under `es` folder because the files be used in back-end. 
Add index.js because it is [`UMD`](https://github.com/react-dropzone/react-dropzone/blob/master/webpack.config.js#L3-L11).
3. Using the pattern `!(es){,/**}` to add all the files except the files under es.
4. Minify the file by web-minify-helper.

Please help me review this PR, thanks.

**Comment by sufuf3** [comment]
@extend1994 I used the commit which has be committed before **23 Dec 2017**.
I'm not sure which commit did I use(09e0acf30d50d7 or d85f93711d4f6f05af3), because I was pulled the latest commit before review.(I think I used commit on Nov 13, 2017, but I not sure.)

My latest commit is the same with the repo's latest commit(27c1a82110f923a836), now. (I updated it recently.)

Would you try the commit before **23 Dec 2017** of web-minify-helper?
If there is no file or fields or commit message need to be modified, I don't think it's necessary to require people to use the latest commit of web-minify-helper after this PR's date.
What do you think?

Many thanks

**Comment by extend1994** [comment]
@sufuf3 Agree with you on the opinion of that we don't always need to use latest web-minify-helper after sending PR. However, I still get different checksum using older commits. My npm version is v2.15.11, node is v4.8.4, not sure if these are related to different result.

**Comment by sufuf3** [comment]
@extend1994 My environment is the same with yours.
However, could you please tell me that your `uglify-es` and `uglify-js` version?
These tools' version should be install v3.1.9, because web-minify-helper is based on them.

Also, would you please let me know that is it really necessary to check the minified file which be generated by web-minify-helper? Is there any concern that we should check it?
Actually, I only met you would check the checksum of the generated minified files, other reviewers I met didn't check this before.
I am a little bit confuse about it.

Thank you.

**Comment by PeterDaveHello** [comment]
@extend1994 let's move to nodejs v8.x by the way.

**Comment by extend1994** [comment]
@sufuf3 I thought reviewers need to check the file integrity if reviewers are using the same tool.
@PeterDaveHello I moved to v8 now. Don't we need to check the checksum of minified files?

**Comment by PeterDaveHello** [comment]
Looks like new versions like v4.2.7/4.2.8 use minified file instead, @sufuf3 can you please directly update this PR to use the latest version only and let me take care of the old ones? Thanks.

**Comment by sufuf3** [comment]
@PeterDaveHello @PeterDaveHello I updated the version to v4.2.8
Please help me review this PR, thanks.

**Comment by PeterDaveHello** [comment]
:+1:

**Pull request merged**
