### PR TITLE
add dropdown.js@0.0.2dev w/ git auto-update

### LINKED ISSUE #9153: [Request] Add dropdown.js
**Library name: dropdown.js ** 
**Git repository url: https://github.com/FezVrasta/dropdown.js **
**npm package url(optional):** 
**License(s): MIT **
**Official homepage: https://github.com/FezVrasta/dropdown.js **
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #9153 
@pvnr0082t please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/FezVrasta/dropdown.js
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 156
   - Count of watchers: 18
   - Count of forks: 69
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9153, cc @FezVrasta

### CODE REVIEW

**Comment by pvnr0082t** [comment]
It seems like something happened to circleci. Please re-push to trigger CI again.

**Comment by PeterDaveHello** [comment]
I triggered it.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
Oops~
@pvnr0082t 
I didn't see the message above and I push again.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
