### PR TITLE
Add version 2.2 of gist-embed

### PR DESCRIPTION
**Pull request by blairvanderhoof**
I still dont know why these old versions show up in this pull request. I just need version 2.2.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
You should remove it or we can't merge it.

**Comment by PeterDaveHello** [comment]
Your commit's parent was toooooo old I think, should sync/rebase with our latest master branch, thanks.

**Comment by blairvanderhoof** [comment]
How the heck do I work off this forked repo. It's so huge that github app crashes when i check changes.  Git status from the command line also freezes. Any tips?

**Comment by PeterDaveHello** [comment]
Yes. please take a look at our sparse-checkout document, in the root of this repo, just open it via GitHub.
BTW, to sync a out-date forked repo, the fastest way may be to delete the old one and re-fork it!

**Comment by blairvanderhoof** [comment]
I did re-fork, its still slow as molasses.  Will check the sparse checkout.

**Comment by maruilian11** [comment]
sorry for wrong tag

**Pull request closed without merging**
