### PR TITLE
update license info of libraries #3

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 

For #5544, I have update the license info of these 10 libraries.
- jqPlot　[ref](https://github.com/jqPlot/jqPlot/#legal-notices)
- jquery-form-validator　[ref](http://www.formvalidator.net/#license)
- jquery-mockjax　[ref](https://github.com/jakerella/jquery-mockjax#license)
- jquery.blockUI　[ref](https://github.com/malsup/blockui#copyright-and-license)
- jquery.collapsible　[ref](https://github.com/juven14/Collapsible/blob/master/LICENSE#L1)
- jquery.form　[ref](https://github.com/malsup/form#copyright-and-license)
- jquery.mb.YTPlayer　[ref](https://github.com/pupunzi/jquery.mb.YTPlayer/tree/master/licences)
- machina.js　[ref](https://github.com/ifandelse/machina.js/blob/master/LICENSE)
- mixitup　[ref](https://mixitup.kunkalabs.com/licenses/)
- placeholder-shiv 　[ref](https://github.com/walterdavis/placeholder-shiv/blob/master/LICENSE.txt)

Would you mind checking this PR for me? Thank you~ :-D

### CODE REVIEW

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Comment by PeterDaveHello** [comment]
As I said in #6576's comment, I need you to re-check all the license again first.

**Comment by PeterDaveHello** [comment]
As I said in #6576's comment, I need you to re-check all the license again first.

**Comment by Amomo** [comment]
backup @maruilian11's comments, prevent from deleted by force-push
```
https://github.com/jqPlot/jqPlot/blob/master/package.json#L36
please check with the author, thank you.

https://github.com/victorjonsson/jQuery-Form-Validator/blob/master/bower.json#L17
please check with the author, thank you.

https://github.com/pupunzi/jquery.mb.YTPlayer/blob/master/package.json#L19
please check with the author, thanks.
```

**Comment by maruilian11** [comment]
@Amomo force-push won't delete those comments :smile:

**Comment by PeterDaveHello** [comment]
Close due to no response.

**Comment by PeterDaveHello** [comment]
Ping @Piicksarn

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello 
I think some license of lib need to be checked.
But as your mention `As I said in #6576's comment, I need you to re-check all the license again first.` 
So before this PR, the contributor need to re-check license first.
But there is no response from the contributor since 19 Mar.

So what can we do for this PR?

Thank you.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern3 try to pick those can be practice for the next intern please.

**Pull request closed without merging**
