### PR TITLE
[new] [author] Initial release of tanner-bootstrap theme - v1.0.0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Finally, looks okay now :+1: 
But I still want to confirm that there is no source file in your git repo, only minified dist file, is this correct?
Thanks.

**Comment by TheTannerRyan** [comment]
Just the minified dist file. 

Also, if I just update my repo and change the version number, will it automatically update, or do I have to clone, commit and send a push request every time?

**Comment by PeterDaveHello** [comment]
If you add tag for it, yes, will be automatically updated with in 24 hours. But what's the reason why don't put the source file? If we want to check the codes or contribute, it'll be better to have it, right?

**Comment by TheTannerRyan** [comment]
I just added a source file

**Comment by drewfreyling** [comment]
@PeterDaveHello This is one of those where I would probably err on the side of not adding it to the repo as nobody is using it yet and no starts. But your call.

**Comment by PeterDaveHello** [comment]
Sounds reasonable, what do you think @thomasdavis ?

**Comment by TheTannerRyan** [comment]
For some reason, my account was deleted.

**Comment by PeterDaveHello** [comment]
Hey @TheTannerRyan, what happened?

**Comment by TheTannerRyan** [comment]
@PeterDaveHello I have no clue.

**Comment by PeterDaveHello** [comment]
I think you should add your repo back first.

**Comment by PeterDaveHello** [comment]
no response?

**Comment by PeterDaveHello** [comment]
Close due to no response.

**Pull request closed without merging**
