### PR TITLE
update license info of libraries #4

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 

For #5544, I have update the license info of these 7 libraries.

- [plupload](https://github.com/moxiecode/plupload)　[ref](https://github.com/moxiecode/plupload/blob/master/license.txt)
- [showdown](https://github.com/showdownjs/showdown)　[ref](https://github.com/showdownjs/showdown/blob/master/license.txt)
- [speakingurl](https://github.com/pid/speakingurl)　[ref](https://github.com/pid/speakingurl#license)
- [spectrum-i18n](https://github.com/bgrins/spectrum)　[ref](https://github.com/bgrins/spectrum/blob/master/package.json#L6)
- [tagmanager](https://github.com/max-favilli/tagmanager)　[ref](https://github.com/max-favilli/tagmanager#copyright-and-license)
- [webkit.js](https://github.com/trevorlinton/webkit.js)　[ref](https://webkit.org/licensing-webkit/)
- [yamlcss](https://github.com/yamlcss/yaml)　[ref](https://github.com/yamlcss/yaml/blob/master/License.txt#L12)

Would you mind checking this PR for me? Thank you~ :-D

### CODE REVIEW

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Comment by PeterDaveHello** [comment]
So what do you think on this package.json?
https://github.com/moxiecode/plupload/blob/master/package.json#L19-L31

Don't be too naive with these, I need you to do a double re-check on this.

**Comment by maruilian11** [comment]
@PeterDaveHello you mean we should also add `GNU Lesser General
Public License` ?
```>
If this is what you want to do, use the GNU Lesser General
Public License instead of this License.
```

**Comment by PeterDaveHello** [comment]
So what about the other licenses and other libs? I thought you didn't do it very carefully.

**Comment by maruilian11** [comment]
i will check them again.

**Comment by PeterDaveHello** [comment]
@maruilian11 Let @Amomo check first ...

**Comment by maruilian11** [comment]
@PeterDaveHello i can't find these commercial licenses on http://spdx.org/licenses/
https://github.com/yamlcss/yaml/blob/master/Readme.md#yaml-under-commercial-distribution-license-yaml-cdl
do we also need to mention it in package.json?

**Comment by PeterDaveHello** [comment]
So let them be object still as origin

**Comment by Amomo** [comment]
backup @maruilian11's comments, prevent from deleted by force-push
```
https://github.com/showdownjs/showdown/blob/master/package.json#L33
please check with author. thank you.

https://github.com/trevorlinton/webkit.js#license
please check with author. thanks.
```
Because these comments were written on my old commits, not on this Pull Request, they won't show up in the updated commits.

**Comment by Amomo** [comment]
Hi @maruilian11 I fix some problems in this PR.

1. **plupload** is under `GPL-2.0` and `Commercial License`.
I update "GPLv2" to "GPL-2.0", and keep Commercial License as objects.
2. The [old reference](https://webkit.org/licensing-webkit/) of **webkit.js** which I attached was wrong. `webkit.js` is not equal to [`Webkit`](https://webkit.org/). webkit.js is only under BSD License. [ref](https://github.com/trevorlinton/webkit.js#license)
3. **showdown** is under BSD 3-Clause License as I referenced. You can see its [license.txt](https://github.com/showdownjs/showdown/blob/master/license.txt) and [original text
](https://opensource.org/licenses/BSD-3-Clause) of BSD-3-Clause.

Could you help me checking this PR again? Thank you! :-D

**Comment by maruilian11** [comment]
@PeterDaveHello if the lib's both license.txt and homepage say the license is BSD-3-Clause, only the package.json says the license is BSD-2-Clause, could we regard it as BSD-3-Clause directly? or we still need to confirm with the author?

**Comment by PeterDaveHello** [comment]
Of course try to confirm it first.

**Comment by maruilian11** [comment]
@Amomo could you confirm **showdown**? thanks.

**Comment by Amomo** [comment]
@maruilian11 
I have sent a PR to **showdown**, it is using `BSD-3-Clause` license in package.json now.
https://github.com/showdownjs/showdown/pull/228

And, I have rebased this PR on latest master branch, could you check it again?
Thank you! :-D

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern you can try to add license into into upstreams' package.json as another contribution.

**Pull request merged**
