### PR TITLE
[new] add blissfuljs@1.0.0

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11  

For #6477, I add blissfuljs at v1.0.0 and add git auto-update config in its package.json.
repo: https://github.com/LeaVerou/bliss

And, there is a unnecessary file named `bliss._.js`, so my filemap look like this:
```sh
    "files": [
      "bliss.js",
      "bliss.min.js",
      "bliss.shy*.js"
    ]
```
Why I think `bliss._.js` is unnecessary?
Because at the bottom of [HomePage](http://blissfuljs.com/), the author only recommend to download "bliss.js", "bliss.shy.js" and their minified file.

Would you mind checking this PR for me? Thank you~ :-D

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `39`, Star `1,214`, Fork `63`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by maruilian11** [comment]
@Amomo  I think the PR is ok, could u rebase it?

**Comment by Amomo** [comment]
@maruilian11 I have rebased this PR, could you help me check it again?
Thank you! :-D

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Comment by LeaVerou** [comment]
To clear up the confusion: bliss._.js is what bliss.shy.js is concatenated with to produce bliss.js :)
It has no use on its own.

**Pull request merged**
