### PR TITLE
add easyModal v1.3.1 with autoupdate config

### LINKED ISSUE #6985: [Request] easyModal.js
**Library name: easyModal.js
*_Git repository url: http://flaviusmatis.github.io/easyModal.js/
*_npm package url(optional):** 
**License(s): https://github.com/flaviusmatis/easyModal.js/blob/master/LICENSE.txt
*_Official homepage: http://flaviusmatis.github.io/easyModal.js/
*_Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #6985 
@PeterDaveHello Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/flaviusmatis/easyModal.js
- Official website (optional, not the repository): http://flaviusmatis.github.io/easyModal.js/
- NPM package url (optional):
- GitHub / Bitbucket popularity (required):
  - Count of stars: 101
  - Count of watchers: 13
  - Count of forks: 47
- NPM download stats (optional):
  - Downloads in the last day:
  - Downloads in the last week:
  - Downloads in the last month:
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [ ] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [ ] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

close #6985, cc @flaviusmatis

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Inconsistent version number in package.json and the js file, also it lack of the git tags for auto-updater to recognize the versions.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello there is no response from the upstream since 9 Jun 2016
What can we do for this PR?
because there is no git tag.
Should we still wait for the author's answer?

Thank you.

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs/issues/6985#issuecomment-328883092

**Pull request closed without merging**
