### PR TITLE
add & point to minified files in package.json of mori

### PR DESCRIPTION
**Pull request by Amomo**
Hi @Piicksarn  , From #5195, I have add minified files in mori and point filename field to `mori.min.js` in package.json.
repo : https://github.com/swannodette/mori
Would you mind checking this PR for me? Thank you~ :-)

- [ ] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `75`, Star `1,723`, Fork `85`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you please take a look at the commit? Thank you~

**Comment by PeterDaveHello** [comment]
Please also minify v0.3.0 and v0.3.1, thanks.

**Comment by Amomo** [comment]
@Piicksarn I have added minified v0.3.0 & v0.3.1, and rebased.
Could you check this PR again? Thank you~ :-D

**Comment by Piicksarn** [comment]
OK!
@PeterDaveHello, would you please take a look at the pr?
thank you!

**Pull request merged**
