### PR TITLE
[new] Add jquery.countdown v2.0.5 with git auto-update, close #5143

### LINKED ISSUE #5143: [Request] Update jQuery Countdown 2.0.2
Library name: jQuery Countdown
Git repository url: None
npm package url(optional): None
Official homepage: http://keith-wood.name/countdown.html
Wanna say something? Leave message here: New version! 2.0.2. Please update :)
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by Piicksarn**

### CODE REVIEW

**Comment by Piicksarn** [comment]
@maruilian11, would you mind to checkout the pr for me?
the git repository url is shown below: 
https://github.com/hilios/jQuery.countdown
Thank you!

**Comment by Piicksarn** [comment]
@PeterDaveHello, the PR did not run the online test!
And i have checked out the [CircleCi](https://circleci.com/gh/cdnjs/cdnjs), it did not show the PR!

**Comment by PeterDaveHello** [comment]
https://circleci.statuspage.io/

> AWS S3 performance issue 
> 
> **Update** - AWS S3 is still experiencing availability issues, we are monitoring the situation and  doing what we can to mitigate its impact. 
> *Aug 10, 02:49 PDT*
> 
> **Update** - AWS S3 is experiencing performance issues. Your builds may fail with
> downloading cache from S3. We are monitoring and investigating. 
> *Aug  10, 00:42 PDT*
> 
> **Investigating** - The output of the build commands is
> currently not visible in the UI. We’re investigating the issue and
> we’ll post an update when we have more information.
> *Aug 10, 00:24 PDT*

**Comment by Piicksarn** [comment]
@maruilian11, I have it rebased and need your help for check it again!
Thank you!

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Pull request merged**
