### PR TITLE
add highstock v1.2.4

### PR DESCRIPTION
**Pull request by maruilian11**
@Amomo could you help me check this PR for #6641 ? thank you!
downloaded from https://github.com/highcharts/highcharts/tree/highstock-v1.2.4/js

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
minify `*src.js` to `src.*min.js` makes no sense

Take a look at this: https://code.highcharts.com/

For example:
https://code.highcharts.com/stock/1.2.4/highstock.js
https://code.highcharts.com/stock/1.2.4/highcharts-more.js

Maybe you can add both v1.2.4 & v1.2.5

**Comment by Amomo** [comment]
@maruilian11 
Could you name the minified files using `[FileName].js`, not ``[FileName].src.min.js`?

**Comment by PeterDaveHello** [comment]
There is officially released files, so why minify and rename it ?

**Comment by maruilian11** [comment]
@Amomo i have removed `*.src.min.js`, could you help me check this PR?

**Comment by maruilian11** [comment]
ping @Amomo

**Comment by Amomo** [comment]
@maruilian11 
I mean, we need a minified version for those `[FileName].src.js` files.
But do not use `*.src.min.js` as the end of minified filenames.

Like the official files,
https://code.highcharts.com/stock/1.2.4/highstock.src.js is a **source** file.
https://code.highcharts.com/stock/1.2.4/highstock.js is a **minified** file.

Do you see the difference between them?

**Comment by maruilian11** [comment]
@Amomo is that ok?

**Comment by Amomo** [comment]
@maruilian11 yes, great!
@PeterDaveHello I think this PR is fine, could you take a look? Thanks!

**Comment by PeterDaveHello** [comment]
Please tell me how you get these files step by step.

**Comment by maruilian11** [comment]
@PeterDaveHello 
1. git clone git@github.com:highcharts/highcharts.git
2. git checkout highstock-1.2.4
3. i use [1.3.10](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/highstock/1.3.10) as an example to  copy files
4. use minify.sh to make minified file.

is it clear enough?

**Comment by PeterDaveHello** [comment]
Okay let's try it, please update your branch for this PR.

**Comment by maruilian11** [comment]
@PeterDaveHello updated.

**Pull request merged**
