### PR TITLE
add pwstrength-bootstrap w/ npm autoupdate

### LINKED ISSUE #8815: [Request] Add jquery.pwstrength.bootstrap
**Library name:** jquery.pwstrength.bootstrap
**Git repository url:** https://github.com/ablanco/jquery.pwstrength.bootstrap
**npm package url(optional):**  https://www.npmjs.com/package/pwstrength-bootstrap
**License(s):** MIT
**Official homepage:** nope
**Wanna say something? Leave message here:** Thanks for providing us great service! :)

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8815 
@kennynaoh @x09326 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/ablanco/jquery.pwstrength.bootstrap/tree/0.7.0
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/pwstrength-bootstrap
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 192
   - Count of watchers: 20
   - Count of forks: 133
 * NPM download stats (optional):
   - Downloads in the last day: 24
   - Downloads in the last week: 49
   - Downloads in the last month: 192

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8815 , cc @ablanco

### CODE REVIEW

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Comment by PeterDaveHello** [comment]
@kennynaoh this need a double review.

**Comment by x09326** [comment]
@PeterDaveHello 
I think this PR is okay, please help me review it, thanks.

**Comment by PeterDaveHello** [comment]
@pvnr0082t any reason to have such a long library name made by ... yourself? I prefer to use its npm name.

**Comment by pvnr0082t** [comment]
@kennynaoh @x09326  I have used npm name as library name. Please help me review again, thank you.

**Pull request merged**
