### PR TITLE
[Author] Add tiny-slider w/ git auto-update

### PR DESCRIPTION
**Pull request by ganlanyuan**
Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/ganlanyuan/tiny-slider
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/tiny-slider
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 7
   - Count of stars: 93
   - Count of forks: 22
 * NPM download stats (optional):
   - Downloads in the last day: 47
   - Downloads in the last week: 990
   - Downloads in the last month: 2502

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by ganlanyuan** [comment]
Thanks

**Comment by sufuf3** [comment]
@ganlanyuan Thank you for your contribution.
1. Could you add `sourcemaps` folder and the files under `sourcemaps`?
2. May I ask you how do you send this pull request? via GitHub website or use git command?
I think the commit message need to modify as the followings, if you use git command, we can help you how to do this.
But if you use GitHub website, it can't modify the commit message. After you modify this PR, I can help you squash to one commit and modify the commit message.
```
Add tiny-slider@2.1.2 w/ git auto-update
```
Thank you.

**Comment by ganlanyuan** [comment]
1. Okay
2. Via GitHub website

I will do this tmr. Yes, please help me squash to one commit.
Thank you so much!

**Comment by ganlanyuan** [comment]
@sufuf3 `sourcemaps/` folder added, could you help squash the commits?

BTW, the map files for all the versions are not in the git repo, because I added `*.map` in the `.gitignore` file. What should I do with this? Should I remove `*.map` from the `.gitignore` file?

**Comment by PeterDaveHello** [comment]
I'll do it.

**Comment by ganlanyuan** [comment]
@PeterDaveHello Thank you so much! 👍

**Comment by PeterDaveHello** [comment]
@ganlanyuan you're welcome :) We'll review it soon (3:34 AM here, need to take rest now)

**Comment by ganlanyuan** [comment]
Sure, sweet dreams.

**Comment by PeterDaveHello** [comment]
@ganlanyuan thanks.

**Comment by ganlanyuan** [comment]
@sufuf3 Thank you so much for your help! 👍 
Could I add `sourcemaps/` folder to git repo in the future versions?

**Comment by sufuf3** [comment]
You're welcome. 
Yes, you can add sourcemaps folder in the future. :)

**Comment by PeterDaveHello** [comment]
@sufuf3 can you please double check everything? It's making me afraid that seeing same types of problems appear many times, about the careless you mean.

**Comment by sufuf3** [comment]
I'm really sorry, I'll pay attention next time.

**Comment by ganlanyuan** [comment]
Thank you all! 👍

**Comment by PeterDaveHello** [comment]
Thanks @ganlanyuan

**Pull request merged**
