### PR TITLE
[new] add angular-selectize2@3.0.1

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 this PR is for #6168
I add `angular-selectize2` at `v3.0.1` and add `git` auto-update config in its package.json.

Would you mind checking this PR for me? Thank you~ :-D

# Profile of the lib
 * Git repository (required): https://github.com/machineboy2045/angular-selectize
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 14
   - Count of watchers: **142**
   - Count of forks: 61

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by maruilian11** [comment]
@Amomo miss `homepage`, maybe you can add `dependencies` and turn `author` structure to object.
thanks!

**Comment by PeterDaveHello** [comment]
@maruilian11 no need to add dependencies is it's missing

**Comment by maruilian11** [comment]
sorry, i thought it had.

**Comment by PeterDaveHello** [comment]
Since I can found many angular-selectize/angular-selectize2, please use `author`-`angular-selectize2` format naming for this lib, other things are all good to be merged.

**Comment by Amomo** [comment]
@maruilian11 I have turned `author` field as object, and renamed the lib name.
Could you help me checking this PR again? Thanks!

**Comment by PeterDaveHello** [comment]
I have no idea why to **turn author field as object**, what's the reference to do that?

**Comment by Amomo** [comment]
I turn the info of the author (name & email) from a **string** to an **object**.
Ummm... I think both fine. 🤔

**Comment by PeterDaveHello** [comment]
@Amomo should save your time to solve more issues rather then the things we don't care about(at least right now)

**Comment by maruilian11** [comment]
>I have no idea why to **turn author field as object**, what's the reference to do that?

i think both are fine, too.
i forgot to mention you can add url to `author` 😓
just a little thing which i thought it could be done with `homepage` added.

and..
sorry for my late check😓
could you rebase this branch upon our latest master ? thanks.

**Comment by PeterDaveHello** [comment]
Don't add the author url, it's wasting time, you can go the the repo or npm page see its author info, we don't really use that info yet, so **leave it alone**, let it be the same as upstream will be good.

**Comment by maruilian11** [comment]
ok.

**Comment by PeterDaveHello** [comment]
So now ... ?

**Comment by maruilian11** [comment]
>sorry for my late check😓
could you rebase this branch upon our latest master ? thanks.

@PeterDaveHello wait for updating.

**Comment by Amomo** [comment]
Hi @maruilian11 
Sorry for update this PR so late. 😞 
Could you help me checking it agin? thx~

**Comment by maruilian11** [comment]
map file, please.

**Comment by Amomo** [comment]
@maruilian11 
I have attached the map file, could you help me checking again? Thanks!

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is OK.

**Pull request merged**
