### PR TITLE
[new] director

### PR DESCRIPTION
**Pull request by AuspeXeu**
Source: https://github.com/flatiron/director/releases

### CODE REVIEW

**Comment by drewfreyling** [comment]
Thanks!

**Comment by AuspeXeu** [comment]
Welcome! When will that be mirrored to the cdn? :)

**Comment by PeterDaveHello** [comment]
With in 30 mins @AuspeXeu

**Comment by AuspeXeu** [comment]
Well. Can't find it on the website though @PeterDaveHello

**Comment by PeterDaveHello** [comment]
https://cdnjs.com/libraries/Director

**Comment by AuspeXeu** [comment]
Well the search still does not offer it as a result ...

**Comment by PeterDaveHello** [comment]
hmmmm ... let's ask help for search feature from @redox, thanks!

**Comment by redox** [comment]
The reindexing wasn't performed. I've just run it manually, but I assume there is a cron (or equivalent) running the `npm run reindex` task, is that correct @thomasdavis? How often is it run?

**Comment by PeterDaveHello** [comment]
oops, sorry, I think I should take this issue but not mention @redox 
I'll do it on my machine next time, though @thomasdavis set permission for me on our server, I don't know why I can't know log in ...

**Comment by redox** [comment]
No worries :+1:

**Comment by PeterDaveHello** [comment]
Sorry for the inconvenience caused.

**Comment by AuspeXeu** [comment]
Cool! Thanks guys =)

**Pull request merged**
