### PR TITLE
roundSlider plugin added

### PR DESCRIPTION
**Pull request by soundar24**
roundSlider plugin added into CdnJS.

For more details about roundSlider, check here: http://roundsliderui.com/

### CODE REVIEW

**Comment by soundar24** [comment]
Please add this new jQuery plugin (roundSlider) into CdnJS.

For more details about this plugin please visit here:  http://roundsliderui.com/
GitHub link:  https://github.com/soundar24/roundSlider

**Comment by PeterDaveHello** [comment]
Missing end newline in package.json, missing auto-update config.

**Comment by soundar24** [comment]
Updated the auto-update config in package.json file.

**Comment by soundar24** [comment]
I have modified the thing as per the previous comment, is there any other thing i need to do still ? Can you please check this and let me know whether i need to update anything.

**Comment by soundar24** [comment]
It just noticed that "Your CircleCI tests were canceled". What should i do now ? where can i get the details information about this issue ? How to resolve this issue and what are the remaining things i need to do to include the files in the CDN ?

**Comment by PeterDaveHello** [comment]
Got problem from circleCI

**Comment by PeterDaveHello** [comment]
Now build failed.

**Pull request closed without merging**
