### PR TITLE
Add iview@0.9.17 w/ npm auto-update

### PR DESCRIPTION
**Pull request by hare1039**
Pull request for issue: #10319
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/iview/iview
 * Official website (optional, not the repository): https://www.iviewui.com
 * NPM package url (optional): https://npmjs.org/package/iview
 * License and its reference: MIT, [ref](https://github.com/iview/iview/blob/master/LICENSE)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 183
   - Count of stars: 3,490
   - Count of forks: 411
 * NPM download stats (optional):
   - Downloads in the last day: 41
   - Downloads in the last week: 260
   - Downloads in the last month: 2,689

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by hare1039** [comment]
@cdnjs/intern3 Please help me review this PR. Thank you.
Note the older versions in npm had release candidates, which I don't really sure how to / not to add them.

**Comment by hare1039** [comment]
@pvnr0082t Please help me reviewing this PR. Thanks.

**Comment by hare1039** [comment]
ping

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by pvnr0082t** [comment]
@hare1039 Please rebase it onto the latest master branch. Thanks.

**Comment by hare1039** [comment]
@pvnr0082t I rebased it.

**Pull request merged**
