### PR TITLE
add browser-logos v28.2.0 with git auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/alrra/browser-logos
**Watch 113
  Star 3,834
 Fork 279**
@PeterDaveHello  could u help me check this PR for #7865  ? thank you!
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR 
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update) 
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

**here are my steps with this PR**
1. npm istall alrra/browser-logos
2. cd browser-logos
3. use `ls -R |grep '.json\|.md\|.editorconfig\|.git\|.gitattributes\|.github\|.npmignore\|.scripts'` to confirm if there is any file should not be added.
4. `rm CHANGELOG.md README.md package.json archive/README.md`
5. `mv browser-logos 28.1.0`
6. make package.json according to package.json and bower.json on alrra/browser-logos

**check license here**
https://github.com/alrra/browser-logos/issues/83#issuecomment-220035622
https://github.com/alrra/browser-logos#legal
since **All logos and trademarks are the property of their respective owners!**,
i didn't set license for this lib, or do you have any idea?

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
cdnjs's npm auto-update doesn't support npm namespace yet.
```js
  "npmName": "alrra/browser-logos",
```

```js
  "npmFileMap": [
    {
      "basePath": "",
      "files": [
        "**/!(*.+(json|md))"
      ]
    }
  ]
```
It's not a good behavior to exclude the files you don't want in a non-dist directory, pick the files you want.

**Comment by maruilian11** [comment]
not really understand this
>cdnjs's npm auto-update doesn't support npm namespace yet.
so i need to change to git auto-update?

**Comment by PeterDaveHello** [comment]
Yes, should use git auto-update.

**Comment by maruilian11** [comment]
**here are my steps with this PR**
1. wget and unzip https://github.com/alrra/browser-logos/archive/28.2.0.zip
2. cd browser-logos
3. use `ls -R |grep '.json\|.md\|.editorconfig\|.git\|.gitattributes\|.github\|.npmignore\|.scripts'` to confirm if there is any file should not be added.
4. `rm README.md archive/README.md`
5. `mv browser-logos 28.2.0`
6. replace 28.1.0 with 28.2.0 in cdnjs folder

**Comment by PeterDaveHello** [comment]
What's the reason why to host `ajax/libs/browser-logos/28.2.0/.editorconfig`? You really don't like to double check your pull request.

**Comment by maruilian11** [comment]
sorry i find i should use `ls -al -R |grep '.json\|.md\|.editorconfig\|.git\|.gitattributes\|.github\|.npmignore\|.scripts'` in step 3

**Comment by maruilian11** [comment]
@Amomo could you help me check this PR? thanks.

**Comment by Amomo** [comment]
@maruilian11 
I think this PR is ok, could you rebase it on our latest master branch?
Thank you!

**Comment by maruilian11** [comment]
@Amomo updated~

**Comment by PeterDaveHello** [comment]
```js
  "repository": {
    "type": "git",
    "url": "git@github.com/alrra/browser-logos.git"
  },
```

Wrong repo url ...

**Pull request merged**
