### PR TITLE
Add jquery-bracket@0.11.0 w/ git auto-update

### LINKED ISSUE #8938: [Request] Add jQueryBracket
**Library name:**  teijo/jquery-bracket
**Git repository url:** https://github.com/teijo/jquery-bracket
**npm package url(optional):** https://www.npmjs.com/package/jquery-bracket
**License(s):** MIT
**Official homepage:** http://www.aropupu.fi/bracket/

### PR DESCRIPTION
**Pull request by sashberd**
close #8938, cc @teijo

Pull request for issue: #8938
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/teijo/jquery-bracket
 * Official website (optional, not the repository): http://aropupu.fi/bracket/
 * NPM package url (optional): https://www.npmjs.com/package/jquery-bracket
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 45
   - Count of stars: 306
   - Count of forks: 209
 * NPM download stats (optional):
   - Downloads in the last day: 1
   - Downloads in the last week: 33
   - Downloads in the last month: 176

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@extend1994 @maruilian11 Pleas egelp review this PR, thanks.

**Comment by sashberd** [comment]
@extend1994  The PR was updated FYR

**Comment by sashberd** [comment]
@extend1994 The PR was updated, FYR

**Comment by extend1994** [comment]
@sashberd Did you forget to push?

**Comment by sashberd** [comment]
@extend1994 Nope, Just it takes time to push it by git

**Comment by extend1994** [comment]
@sashberd It would be better to tag me after you got approval from @PeterBot.
Please move `accordingly` to the first line, it still meets 50/72 rule and more readable. Thanks.

**Comment by sashberd** [comment]
@extend1994 The PR was updated. FYR

**Pull request merged**
