### PR TITLE
Add prettydate w/ git auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/fengyuanchen/prettydate
**Watch 5
  Star 48
 Fork 11**
@Amomo could u help me check this PR for #7681 ? thank you!

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR 
- [ ] The lib has notable popularity (the author has two lib with high popularity, so we can see its potential.)
  - [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry 
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update) 
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
What about [i18n](https://github.com/fengyuanchen/prettydate/tree/master/i18n)?

**Comment by maruilian11** [comment]
@Amomo i added `/i18n`, could you help me check this PR? thanks!

**Comment by PeterDaveHello** [comment]
Maybe it's time to implement multi-filemap support in git auto-updater, let's do it first.

**Comment by Piicksarn** [comment]
@maruilian11, I'd help u checkout the pr after the pr updated/rebased.

**Comment by maruilian11** [comment]
@Piicksarn we need to wait the multi-filemap support in git auto-update.

**Comment by PeterDaveHello** [comment]
@maruilian11 Or you can implement it as you already have the intership and contribute for a long time.

**Comment by maruilian11** [comment]
@Piicksarn @cdnjs/intern2 could you help me check this PR? Thank you!
0.1.0 is from git tag
0.0.1 https://github.com/fengyuanchen/prettydate/commit/c1f3d3c2fb7d128be7a59b1cf6fbe64c1a9ec982
0.0.2 https://github.com/fengyuanchen/prettydate/commit/273fac44e3e6802982915c28548f8280b1781771#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
0.0.3 https://github.com/fengyuanchen/prettydate/commit/bf621ec0362136c3f45e7579c85d68e9337d5d02#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by pvnr0082t** [comment]
@maruilian11 It seems that CI test stuck. Please rebase it and push again to trigger CI. Thanks

**Comment by PeterDaveHello** [comment]
Now running

**Comment by maruilian11** [comment]
@Piicksarn @cdnjs/intern2 I resent the commits, the CI test finally pass, could you help me review this PR? Thank you!

**Comment by kennynaoh** [comment]
LGTM

**Pull request merged**
