### PR TITLE
Add license of fiber #6324

### PR DESCRIPTION
**Pull request by Asu4ni**
source: https://github.com/linkedin/Fiber/blob/master/LICENSE.txt
#6324

### CODE REVIEW

**Comment by Amomo** [comment]
Hi @Asu4ni please make your commit message readable!
"Add license used" is not a good commit message.

**Comment by Amomo** [comment]
Hi @Asu4ni please try again! Try to finish a good PR.

You can open a new PR to do it right, 
or it's welcome to ask us if you need any help in fixing this PR! :-D

**Comment by Asu4ni** [comment]
Do I have to start a new branch and redo the commit？
It seems that opening a new PR still doesn't allow me to change the commit message. Thanks!

**Comment by Amomo** [comment]
Yes,
As you can't modify the commit message or delete your old commit in your browser.
You need to open a new PR by redo the steps in a new branch.

Or you can do it locally, clone your forked cdnjs repo, and pull your branch "patch-1", so you can modify the commit message by git commands.

**Pull request closed without merging**
