### PR TITLE
Enable autoupdate in sockjs-client package.json

### PR DESCRIPTION
**Pull request by brycekahle**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I think the change of maintainer should be in another commit, what do you think?

**Comment by brycekahle** [comment]
I think the one line is not worth another commit. Especially because it is a metadata file.

**Comment by PeterDaveHello** [comment]
Yeah, but the commit message is `Enable autoupdate in sockjs-client package.json`, is not about worth or not, the change didn't match the commit message, I think you can also add a line in the commit message to talk about the change.

**Comment by brycekahle** [comment]
Updated to 2 commits as requested

**Comment by PeterDaveHello** [comment]
Thanks!

**Pull request merged**
