### PR TITLE
add gliojs v0.0.7 with npm autoupdate config

### LINKED ISSUE #7561: [Request] gliojs
**Library name:** gliojs
**Git repository url:** https://github.com/luisvinicius167/gliojs
**npm package url(optional):**  https://www.npmjs.com/package/gliojs
**License(s):** MIT
**Official homepage:** http://luisvinicius167.github.io/gliojs/

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #7561 
@dannyxx001 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/luisvinicius167/gliojs
 * Official website (optional, not the repository): http://luisvinicius167.github.io/gliojs/
 * NPM package url (optional): https://www.npmjs.com/package/gliojs
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 168
   - Count of watchers: 10
   - Count of forks: 10
 * NPM download stats (optional):
   - Downloads in the last day: 0
   - Downloads in the last week: 16
   - Downloads in the last month: 31

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7561, cc @luisvinicius167

### CODE REVIEW

**Comment by dannyxx001** [comment]
@PeterDaveHello I think this PR is OK. Please review again, thanks.

**Comment by PeterDaveHello** [comment]
Missing repository info in `package.json`

**Comment by pvnr0082t** [comment]
@dannyxx001 I have already added the repository info in ```package.json```. Please review again, thank you.

**Comment by dannyxx001** [comment]
Yeah, I think it's OK. @PeterDaveHello Please review again, thanks. XD

**Comment by luisvinicius167** [comment]
Great! Thanks!

**Pull request merged**
