### PR TITLE
Satellizer

### PR DESCRIPTION
**Pull request by nsamarak**
Pull request for issue: #12808 
Related issue(s): N/A

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/sahat/satellizer
 * Official website (optional, not the repository): N/A
 * NPM package url (optional): https://www.npmjs.com/package/satellizer
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 267
   - Count of stars: 8,110
   - Count of forks: 1,291
 * NPM download stats (optional):
   - Downloads in the last day: 283
   - Downloads in the last week: 1,984
   - Downloads in the last month: 7,518

# Essential checklist
 * [ ] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] Doesn't already exist / has duplicate issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
 * [x] The parent of the commit(s) in the PR is not older than 3 days.
 * [x] Pull request is sent from a non-master branch with a meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sashberd** [comment]
@nsamarak As I understand from your PR the problem is that library cdnjs autoupdate config is not updating anymore this library. If I am right, please open issue with description of the problem and provide number of the issue in the PR description. 

As for the PR:

1) You do not need to change autoupdate config to npm, version 1.0.0 on npm is not exists, thus the number of release on npm are the same as on git
2)You can update filename and version number in the same commit with autoupdate. Please do git rebase and squash or remove all unnecessary commits
3) As for autoupdate config, just add new filemap configurations like:

```
"autoupdate": {
  "source": "git",
    "target": "git://github.com/sahat/satellizer.git",
    "fileMap": [
      {
        "basePath": "",
        "files": [
          "satellizer*.js"
        ]
      },
 {
      "basePath": "dist",
      "files": [
        "**/*"
      ]
    }
   ]
  }
```
4) If you use dist folder in autoupdate config, do not use it in filename
5) Please  add v0.15.5(latest) files to the lib folder in order to fetch configuration

You are almost did it!!!
Thanks for you contribution

**Comment by nsamarak** [comment]
@sashberd Thanks for the guidance!

Regarding adding v15 to the libs folder, are you saying that I should create a version-specific folder under nsamarak/cdnjs/tree/satellizer/ajax/libs/satellizer and manually copy the files there?

**Comment by sashberd** [comment]
@nsamarak Yes, indeed.

**Comment by nsamarak** [comment]
It looks like satellizer is already distributing their js through a different CDN, so I'm going to close this pull request. I appreciate the effort in looking over it!

**Pull request closed without merging**
