### PR TITLE
[new] [author] added d3fc

### PR DESCRIPTION
**Pull request by ColinEberhardt**
This PR adds v0.4.0 of the d3fc library:

https://github.com/ScottLogic/d3fc

The `package.json` has been configured to auto-update via npm.

The files within this PR are all from our latest release:

https://github.com/ScottLogic/d3fc/releases/tag/v0.4.0

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hi @ColinEberhardt, thanks for your PR, I'm sorry that currently we use different syntax between `npm` and `git` auto-update, please take a look at this part and update your package.json, thank you!
https://github.com/cdnjs/cdnjs#enabling-gitrecommended-or-npm-auto-update

**Comment by ColinEberhardt** [comment]
Hi @PeterDaveHello I fell into the trap of first adding the GitHub auto-update then changing it to npm! All fixed now, and the CI server is happy :-)

**Comment by PeterDaveHello** [comment]
Would you please squash them into only one commit as our document said? Thanks!

**Comment by ColinEberhardt** [comment]
@PeterDaveHello - my apologies, I've now squashed, and tests are passing.

**Comment by PeterDaveHello** [comment]
no problem, thanks!

**Comment by PeterDaveHello** [comment]
It'll be even better if you can reabse on our latest master branch next time, I'll manually pick it up now.

**Comment by ColinEberhardt** [comment]
> It'll be even better if you can reabse on our latest master branch next time, I'll manually pick it up now.

Thanks - will do.

**Pull request closed without merging**
