### PR TITLE
add LogosDistort v0.3.8

### LINKED ISSUE #7418: [Request] Add LogosDistort
**Library name:** LogosDistort
**Git repository url:** https://github.com/hellsan631/LogosDistort
**License:** MIT
**Official homepage:** https://github.com/hellsan631/LogosDistort
**Wanna say something? Leave message here:**
LogosDistort is a fancy jQuery plugin that helps you create unique 3D perspective distortions with mouse interaction using CSS matrix3d transforms.

### PR DESCRIPTION
**Pull request by x09326**
@pvnr0082t Please help me review it, thank you
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/hellsan631/LogosDistort
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 72
   - Count of watchers: 5
   - Count of forks: 24
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

with git autoupdate config close #7418, cc @louis-lau

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this pull request is ok. Please check it again, thank you.

**Comment by PeterDaveHello** [comment]
@pvnr0082t Okay, I will check it later, thanks.

**Comment by PeterDaveHello** [comment]
Please manually minify the css file.

**Comment by x09326** [comment]
@PeterDaveHello I have minified the file.

**Comment by PeterDaveHello** [comment]
@x09326 So please call your reviewer to review that change and the whole PR again for you.

**Comment by x09326** [comment]
@pvnr0082t please help me check it again, thank you.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I review it again and I think it's ok. Please check this pull request again.

**Pull request merged**
