### PR TITLE
add leaflet.toolbar.js v0.1.2 with npm autoupdate

### LINKED ISSUE #7779: [Request] Add leaflet.toolbar.js
**Library name:** leaflet.toolbar.js
**Git repository url:** https://github.com/Leaflet/Leaflet.toolbar
**npm package url(optional):** https://www.npmjs.com/package/leaflet-toolbar
**License(s):** MIT
**Official homepage:** https://github.com/Leaflet/Leaflet.toolbar
**Wanna say something? Leave message here:** Thank you!
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #7779 
@kennynaoh Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/Leaflet/Leaflet.toolbar
- Official website (optional, not the repository):
- NPM package url (optional): https://www.npmjs.com/package/leaflet-toolbar
- GitHub / Bitbucket popularity (required):
  - Count of stars: 70
  - Count of watchers: 17
  - Count of forks: 31
- NPM download stats (optional):
  - Downloads in the last day: 0
  - Downloads in the last week: 28
  - Downloads in the last month: 107
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [ ] The lib has notable popularity
  - [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [ ] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

close #7779, cc @justinmanley

### CODE REVIEW

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Comment by PeterDaveHello** [comment]
@pvnr0082t in the case that we can not directly apply the minify process on a lib, would you please confirm with its author that is it possible to change the naming so that we can automatically update the lib on cdnjs?

**Comment by pvnr0082t** [comment]
@kennynaoh @PeterDaveHello Author has added minified files in `dist` folder in master branch but there is no new release. Should I ask author if he can give a new release? Or we can manually add old version first.

**Comment by PeterDaveHello** [comment]
@pvnr0082t No need to ask for new release, you, can add old versions and autoupdate config first.

**Comment by pvnr0082t** [comment]
@kennynaoh I have added old versions of leaflet.toolbar.js. Please help me review again, thank you.

**Comment by kennynaoh** [comment]
@pvnr0082t 
Sorry for late review.
Please rebase to the latest master branch.
Thanks!

**Comment by pvnr0082t** [comment]
@kennynaoh I have rebased it. Please help me review again, thank you.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Comment by PeterDaveHello** [comment]
I'll like to make the filename consistent, but the case looks a little bit complex here, v0.1.0 is using different naming schema, and css files have no minified version from upstream, @pvnr0082t can you confirm with the author if it's possible to change to the most common naming style like this:

- javascript.js -> javascript.min.js
- style.css -> style.min.css

Thanks.

**Comment by PeterDaveHello** [comment]
Hello, any updates here? Thanks.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello There is no response from the upstream since 3 Aug 2016.
Should we wait for the author reply about naming style?
Or maybe just continue this PR?

Thank you.

**Comment by sufuf3** [comment]
@pvnr0082t would you do this?
Thank you.

**Comment by sufuf3** [comment]
@PeterDaveHello could we close this PR?

This library doesn't have not many popularity (103 star from GitHub and 169 downloads in the last month from npm). 
Also there is no response from the contributor since 13 Sep.

Thanks.

**Comment by justinmanley** [comment]
I updated Leaflet.toolbar a few months ago and it has had files in the requested format (.min.js and .min.css) since ~mid September. Please let me know if there is anything else you need.

**Comment by PeterDaveHello** [comment]
Hi @justinmanley , thanks for the update, as the file's filename without `.min` are still minified, and there are still files with `-src`, I think we don't really need `.min` files here, it's fine :)

**Pull request closed without merging**
