### PR TITLE
add license field with MIT in bespoke.js

### PR DESCRIPTION
**Pull request by LeaYeh**
#5500
@Amomo could you help me to check out this pr?

### CODE REVIEW

**Comment by Amomo** [comment]
@LeaYeh please attach `lib's GitHub repo` in PR comment in the future～
It would help us to review your PR easier and faster.

And, `starting your commit message with a verb` would help others understand your commits clear and effectively. Would you mind to modify your commit message?

Thank you!

**Comment by LeaYeh** [comment]
lib: https://github.com/markdalgleish/bespoke.js/tree/v1.0.0

**Comment by Amomo** [comment]
@LeaYeh Thank you for attaching lib repo's url.
Could you modify your commit message to `start with a verb`?

**Comment by LeaYeh** [comment]
oops I misunderstood what you meant.

**Comment by Amomo** [comment]
@LeaYeh because adding the license field is the key part in your PR, I think to start with `"add license field ... in bespoke.js"` would make the message more readable.

**Comment by LeaYeh** [comment]
same as the commit?

**Comment by Amomo** [comment]
@LeaYeh as you change this PR's title, you commit message should put the key point at the starting.

**Comment by Amomo** [comment]
Hi @LeaYeh could you make your commit message as same as your PR title?

And, your commit is facing a conflict problem.
Please let your branch meet the latest master branch first.
Then, do your modification again. Thank you! :-D

**Comment by Amomo** [comment]
@LeaYeh could you please update your PR~?

**Comment by PeterDaveHello** [comment]
Added in d0935dabf7069a8c693c02e99dcbf1f42bbfdd5f

**Pull request closed without merging**
