### PR TITLE
Update 10up-sanitize.css w/ npm auto-update

### PR DESCRIPTION
**Pull request by kernc**
https://github.com/jonathantneal/sanitize.css

# Pull request template for new library

Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

## Profile of the lib

* Git repository (required):
* Official website (optional, not the repository):
* NPM package url (optional):
* License and its reference:
* GitHub / Bitbucket popularity (required):
  * Count of watchers:
  * Count of stars:
  * Count of forks:
* NPM download stats (optional):
  * Downloads in the last day:
  * Downloads in the last week:
  * Downloads in the last month:

## Essential checklist

* [ ] I'm the author of this library
  * [ ] I would like to add link to the page of this library on CDNJS on website / readme
* [ ] This lib was not found on cdnjs repo
* [ ] Doesn't already exist / has duplicate issue and PR
* [x] The lib has notable popularity
  * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [ ] More than 800 downloads stats per month on npm registry
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [ ] Has valid tags for each versions (for git auto-update)
* [x] Auto-update setup
* [ ] Auto-update target/source is valid.
* [ ] Auto-update filemap is correct.

## Git commit checklist

* [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [x] The parent of the commit(s) in the PR is not older than 3 days.
* [x] Pull request is sent from a non-master branch with a meaningful name.
* [ ] Separate unrelated changes into different commits.
* [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [ ] Close corresponding issue in commit message
* [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by kernc** [comment]
@jonathantneal approves of this change.

**Comment by jonathantneal** [comment]
I do!

**Comment by kernc** [comment]
@cdnjs how does one get [non-default filenames](https://github.com/cdnjs/cdnjs/pull/13843/files#diff-589439d827e24dcaaf63598e69c97f8bR5) auto-minimized? :grin:

**Comment by MattIPv4** [comment]
I think the bot auto minifies every file it can, though I'm not super familiar with that aspect of our auto-updating and it's not really something I'd rely on.

**Comment by kernc** [comment]
That'd be lovely to rely on. Thanks.

**Pull request merged**
