### PR TITLE
add tween.js@16.3.5 w/ npm auto-update

### LINKED ISSUE #8674: [Request] Add tween.js
**Library name:** tween.js
**Git repository url:** https://github.com/tweenjs/tween.js/
**npm package url(optional):** https://npmjs.org/package/tween.js
**License(s):** MIT 
**Official homepage:** https://github.com/tweenjs/tween.js
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #8674 
@pvnr0082t please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/tweenjs/tween.js
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/tween.js
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 3,214
   - Count of watchers: 166
   - Count of forks: 535
 * NPM download stats (optional):
   - Downloads in the last day: 570
   - Downloads in the last week: 2,564
   - Downloads in the last month: 9,337

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8674, cc @sole

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@kennynaoh There are 15 versions on npm but 23 on GitHub. Could you please manually add other versions? Thanks.

**Comment by kennynaoh** [comment]
@pvnr0082t 
I have added old versions of the lib.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
@kennynaoh why don't you add `v0.11.0`~ `v0.14.0` ?

**Comment by kennynaoh** [comment]
@pvnr0082t 
Because there has no `Tween.js` in `v0.11.0`~`v0.14.0`.

**Comment by pvnr0082t** [comment]
@kennynaoh I think you can confirm if `index.js` in  `v0.11.0`~ `v0.14.0` are unnamed `Tween.js` with author. If yes, you can manually add and rename them.

**Comment by PeterDaveHello** [comment]
@pvnr0082t Fair enough!

**Comment by kennynaoh** [comment]
@pvnr0082t 
I have confirmed with author and added version `v0.11.0`~`v0.14.0`.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
@x09326 can you also help review this PR?

**Comment by x09326** [comment]
@PeterDaveHello 
I think this PR is okay, please help me review it, thanks.

**Comment by PeterDaveHello** [comment]
Why @kennynaoh updated the commit in this PR again?

**Comment by kennynaoh** [comment]
@PeterDaveHello 
Sorry about that.
Because I think this PR is too long, I rebased it.

**Comment by PeterDaveHello** [comment]
@kennynaoh So this need to be review again.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
@kennynaoh it's good to rebase with the latest master branch, just don't forget to ask for the review again, and you can do it again and again before the next review, I think you could do it even again before @pvnr0082t review it today, anyway, I merged it, thanks.

**Pull request merged**
