### PR TITLE
Add missing packages directory to Sencha Ext JS 6.0.0

### PR DESCRIPTION
**Pull request by richard-vd**
This recently added library was incomplete. This pull request adds the missing 'packages' directory, it is essential for Ext JS charts to function.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
What's the source of these files? Thanks.

**Comment by richard-vd** [comment]
The source is the official Ext JS 6.0.0 GPL download: http://cdn.sencha.com/ext/gpl/ext-6.0.0-gpl.zip

Before committing, I removed the inappropriate files and verified that the charts package works in my local repository.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern, please take a look at this PR.

**Comment by richard-vd** [comment]
@maruilian11: that's a typo in the subject of ca11db7. Please don't close this PR, you mean close #5319 instead.

**Comment by PeterDaveHello** [comment]
ping @cdnjs/intern

**Comment by maruilian11** [comment]
@richard-vd  sorry for my mistake, I have corrected it and sent new PR.

**Comment by richard-vd** [comment]
Is there anything I can do to help get this PR committed?

**Comment by maruilian11** [comment]
hi @richard-vd  cdnjs already has extjs v6.0.0
https://cdnjs.com/libraries/extjs
if there is any reason you think the files on cdnjs are not enough, please let me know.
thank you!

**Comment by richard-vd** [comment]
Yes it does, but the extjs v6.0.0 on cdnjs it is incomplete in its current state. The whole 'packages' directory is missing (containing the charts functionality). My pull request adds the missing files.

The files in my pull request are coming from the official Ext JS 6.0.0 GPL download: http://cdn.sencha.com/ext/gpl/ext-6.0.0-gpl.zip

**Comment by PeterDaveHello** [comment]
@richard-vd, so, did you mean even [ext-all.js](https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.0/ext-all.js) doesn't contain the functions you want? And if you can tell me the actual steps to get these 146 files? I removed the file type that we don't support, and there is 196 files under `packages`, or if you don't mind, I'll add them by my side, thanks.

**Comment by richard-vd** [comment]
@PeterDaveHello, charts are not in ext-all.js. See https://docs.sencha.com/extjs/6.0/components/introduction_to_charting.html#Using_Sencha_Charts_without_Sencha_Cmd

Here are the steps to get to the 146 files of my pull request:

```bash
# go to the extjs/6.0.0 directory inside the cdnjs git repo
cd cdnjs/ajax/libs/extjs/6.0.0

# download the library (GPL version) to the current directory
curl http://cdn.sencha.com/ext/gpl/ext-6.0.0-gpl.zip -O

# remove packages dir to make sure we start clean
rm -rf packages

# unzip the packages dir of the library, and exclude unwanted files and directories
unzip ext-6.0.0-gpl.zip ext-6.0.0/build/packages/* -d . -x "*.scss" "*.txt" "*.html" "*.md" "*.rb" "*.json" "*/demo-files/*" "*/ext-watermark/*"

# move the packages dir to where we want it
mv ext-6.0.0/build/packages/ packages

# clean up
rm -rf ext-6.0.0
rm -f ext-6.0.0-gpl.zip
```

**Comment by PeterDaveHello** [comment]
ok, thanks, would you please rebase your branch with our latest master branch? thanks!

**Comment by richard-vd** [comment]
Done!

**Comment by PeterDaveHello** [comment]
Thanks a lot @richard-vd

**Comment by richard-vd** [comment]
...and already on [cdnjs.com](https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.0/packages/charts/classic/charts.js)! :-)

That's great, thank you!

**Comment by PeterDaveHello** [comment]
:+1:

**Pull request merged**
