### PR TITLE
add react-data-grid with npm auto-update

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #9066 
@pvnr0082t, @x09326 please help me review this pull request, thank you.
Manually add other versions from npm under themes/ because file structure changed after v1.0.38
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/adazzle/react-data-grid
- Official website (optional, not the repository): https://adazzle.github.io/react-data-grid/
- NPM package url (optional): https://www.npmjs.com/package/react-data-grid
- GitHub / Bitbucket popularity (required):
  - Count of stars: 809
  - Count of watchers: 68
  - Count of forks: 338
- NPM download stats (optional):
  - Downloads in the last day: 16,466
  - Downloads in the last week: 47,994
  - Downloads in the last month: 84,907
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [x] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [x] More than 500 downloads stats per month on npm registry
- [ ] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@kennynaoh I didn't see any file structure changed. Just one more file `react-data-grid.css` added in dist folder.

**Comment by kennynaoh** [comment]
@pvnr0082t 
I need to add `css` file manually before `v1.0.39`, because there has no `css` file under `dist/`
Thanks!

**Comment by pvnr0082t** [comment]
Okay, i see. But you don't minified the `css` files.

**Comment by pvnr0082t** [comment]
@kennynaoh There is a typo in commit message. It should be `old`, not `pld`.

**Comment by PeterDaveHello** [comment]
@pvnr0082t let's try to use the PR review feature to ask for changes.

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 ,
I have minified `css` files and fixed commit message.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
let' remove `0.12.20-cm-ci-improvements*` versions.

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 
I have removed all the detailed versions and updated .gitignore.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by kennynaoh** [comment]
@PeterDaveHello 
`*-*` can not ignore that?

**Comment by PeterDaveHello** [comment]
`0.12.15-alpha1` is a normal version, why do we need to ignore that?

**Comment by kennynaoh** [comment]
OK

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 
I updated the .gitignore.
Please help me review it again.
Thanks!

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 
I have solved the conflict problem.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
@PeterDaveHello 
The file is under `themes/`

**Comment by PeterDaveHello** [comment]
@kennynaoh as we discussed many times, tell us before we ask you, now please update your first comment about all the details, thanks.

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 
I have updated the commit message.
Please help me review it again.
Thanks!

**Comment by kennynaoh** [comment]
Like this
>let's remove 0.12.20-cm-ci-improvements* versions.

**Comment by pvnr0082t** [comment]
@kennynaoh detailed? Is that typo?

**Comment by kennynaoh** [comment]
Sorry about that.
@pvnr0082t , @x09326 
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Let's make filename in v0.12.0/0.12.1 the same structure as the others as there are only two very early versions have the different naming scheme.

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 , I have modified the filename structure in v0.12.0/0.12.1.
Please help me review it again.
Thanks!

**Comment by x09326** [comment]
LGTM

**Comment by pvnr0082t** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
Thank you all :100:

**Pull request merged**
