### PR TITLE
Add asmCrypto@0.0.11 w/ git auto-update

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #10495

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/vibornoff/asmcrypto.js
 * NPM package url (optional): https://www.npmjs.com/package/asmcrypto.js
 * License and its reference: [MIT](https://github.com/vibornoff/asmcrypto.js/blob/master/LICENSE)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 27
   - Count of stars: 310
   - Count of forks: 76
 * NPM download stats (optional):
   - Downloads in the last day: 8
   - Downloads in the last week: 35 
   - Downloads in the last month: 133

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

@cdnjs/intern3 Please help me review this pull request, thank you.

### CODE REVIEW

**Comment by extend1994** [comment]
@PeterDaveHello Please help me review this pull request, thank you.

**Comment by PeterDaveHello** [comment]
@extend1994 use the same name in the PR title/commit message as what it is in the repo please.

**Comment by extend1994** [comment]
@PeterDaveHello I used the name `asmCrypto` because I think the library's name is `asmCrypto` which shows in the library issue and README in its repo. In this case, should I use `asmcrypto.js`?

**Comment by PeterDaveHello** [comment]
@extend1994 It's better to make them the "same"

**Comment by extend1994** [comment]
Okay, thanks!

**Pull request merged**
