### PR TITLE
[New] Add gitbook-plugin-code-editor@1.2.1 w/ npm auto-update

### LINKED ISSUE #9798: [Request] Add gitbook-plugin-code-editor
**Library name:** gitbook-plugin-code-editor
**Git repository url:** https://github.com/zingchart/gitbook-plugin-code-editor
**npm package url(optional):** https://www.npmjs.com/package/gitbook-plugin-code-editor
**License(s):** MIT
**Official homepage:**
**Wanna say something? Leave message here:** cc #6754

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39647991-request-add-gitbook-plugin-code-editor?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sajochiu**
Pull request for issue: #9798 
Related issue(s): #9414 #9798

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/zingchart/gitbook-plugin-code-editor
 * Official website (optional, not the repository):
 * NPM package url (optional):https://www.npmjs.com/package/gitbook-plugin-code-editor
 * License and its reference:MIT
 * GitHub / Bitbucket popularity (required):
   - Count of stars:9
   - Count of watchers:12
   - Count of forks:0
 * NPM download stats (optional):
   - Downloads in the last day:7
   - Downloads in the last week:250
   - Downloads in the last month:1762

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by x09326** [comment]
LGTM
@cdnjs/intern2 please help me review it, thanks.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello There is no response since 19 Mar
And I found this is intern's practice.
Although this lib has not enough popularity.
https://www.npmjs.com/package/gitbook-plugin-code-editor 65 downloads in the last month
https://github.com/zingchart/gitbook-plugin-code-editor 12 stars

So What can we do for this PR?
Help fix? close it?

Thank you.

**Comment by PeterDaveHello** [comment]
Let's close this one.

**Comment by PeterDaveHello** [comment]
@sufuf3 please help test if the minify problem still exists, thanks.

**Comment by sufuf3** [comment]
Yes, I got the error message as the followings:
```sh
module.js:327
    throw err;
    ^

Error: Cannot find module 'clean-css'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/sufuf3/web-minify-helper/node_modules/clean-css-cli/index.js:4:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
local compressor failed, now try to compress with javascript-/cssminifier.com
```

**Comment by PeterDaveHello** [comment]
`Error: Cannot find module 'clean-css'`? @sufuf3 you sure about you install your dependency properly?

**Comment by sufuf3** [comment]
when I pull master, I always run `npm install`. Now, I ran again, it does not show what I install. (Not sure, is this problem of this part. https://github.com/PeterDaveHello/web-minify-helper/blob/master/package.json#L5)
But I ran `npm i clean-css` and rerun minified tool, I got the followings message.

```sh
/**
^^^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/sufuf3/web-minify-helper/node_modules/clean-css-cli/index.js:5:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by PeterDaveHello** [comment]
@sufuf3 what master ... ? I can't understand what have you done here in fact.

**Comment by sufuf3** [comment]
Sorry the ` pull master` is `git pull git@github.com:PeterDaveHello/web-minify-helper.git master`.

I installed dependency via `npm i clean-css`.
Then, I minified the files again and got the error message as this comment https://github.com/cdnjs/cdnjs/pull/10022#issuecomment-329727275.

**Comment by PeterDaveHello** [comment]
@sufuf3 so I thought you should mention it clear especially you are pulling something else, not this cdnjs project ...

**Comment by sufuf3** [comment]
Yes, you're right.
I should mention it clear, sorry about that.

**Comment by PeterDaveHello** [comment]
@extend1994 @maruilian11 please help take a look if the problem really exist and if you can fix it without me, thanks.

**Comment by maruilian11** [comment]
@sufuf3 Do you still have this problem? Can you give some detail about the time you get the error msg?  And you only get this error on this branch?

**Comment by sufuf3** [comment]
Sorry, I fount https://github.com/zingchart/gitbook-plugin-code-editor/blob/master/assets/editorLoad.js this file can't use in front-end.
I helped modify the pattern.

@cdnjs/active-contributor @cdnjs/intern3 Please help review this PR, thanks.

**Comment by sufuf3** [comment]
@maruilian11 @extend1994  Please help review this PR, thanks.

**Comment by PeterDaveHello** [comment]
Okay let's close before we got new updates, thanks @sajochiu

**Pull request closed without merging**
