### PR TITLE
[author] [new] Add qrious w/ npm auto-update via single package.json

### PR DESCRIPTION
**Pull request by neocotic**
Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/neocotic/qrious
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/qrious
 * License and its reference: GPL-3.0
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 18
   - Count of stars: 310
   - Count of forks: 41
 * NPM download stats (optional):
   - Downloads in the last day: 83
   - Downloads in the last week: 1663
   - Downloads in the last month: 5315

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by neocotic** [comment]
Is it possible to exclude 1.x releases from the git auto-updated? 1.x versions had a different package name and directory structure.

**Comment by neocotic** [comment]
I've switched to npm auto-update and added the missing "filename" property.

**Comment by neocotic** [comment]
@sufuf3 I'm currently planning on getting rid of the page on my homepage and creating it's own homepage, but I didn't want to hold this up until then nor did I want to add yet another reference to the current site at this time. The site currently has no more info than then repo README.

I would like to use the npm auto-update. The package name changed after v1, which is why the version counts don't match. I would not like the old package name to be included here, so npm would be my preferred choice.

**Comment by sufuf3** [comment]
@neocotic OK, then I think this PR is fine.

Just need to squash one commit.
Would you squash the commit? And let the commit message as the followings:
```
Add qrious w/ npm auto-update via single package.json
```

Thank you.

**Comment by PeterDaveHello** [comment]
@sufuf3 Confirm if contributor is using git command line before asking squashing, just remind you again.

**Comment by sufuf3** [comment]
Oh, I missed that, I am sorry.
@neocotic May I ask you how do you send this pull request? via GitHub website or use git command?
I think the commit should squash to one commit, if you use git command, we can help you how to do this.
But if you use GitHub website, it can't squash the commit.

**Comment by PeterDaveHello** [comment]
@sufuf3 if it may not be able to be squashed, why should you ask that? I think your comment should be more clear?

**Comment by PeterDaveHello** [comment]
@sufuf3 yeah that's better.

**Comment by neocotic** [comment]
I used the GitHub website.

**Comment by sufuf3** [comment]
OK. 
May I help you squash to one commit? :smiley: 
It will be useful to us to maintain the git log.

**Comment by neocotic** [comment]
Sure.

**Comment by sufuf3** [comment]
Help squash to one commit and modified the commit message.
@cdnjs/intern3 please help review this PR, thanks. :smiley:

**Comment by neocotic** [comment]
Thanks all! Quick questions:

* I'm seeing a 404 error for https://cdnjs.cloudflare.com/ajax/libs/qrious/4.0.2/qrious.min.js. Is this just a matter of time?
* I was expecting to see other files from `dist` available as well, but I'm only seeing the main file. Did I miss something in the configuration or is this also a matter of time?

**Comment by PeterDaveHello** [comment]
@neocotic I think you checked the link too early that it was not pulled done yet, the 404 may be cached in your nearest edge node for a short time, it's online already by my side.

dist should be displayed as it's meaningless for the endusers.

**Comment by neocotic** [comment]
Thank you. I just got ahead of myself :smile:

**Comment by dakshshah96** [comment]
@neocotic It's live now 😄

**Pull request merged**
