### PR TITLE
add npm auto-update config of visibility.js

### PR DESCRIPTION
**Pull request by maruilian11**
for #7305

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@ai would you please help confirm that?
I can see three files under lib:
`visibility.core.js`,  `visibility.fallback.js` and  `visibility.timers.js`

But previous versions on CDNJS have only the minified `visibility.fallback.min.js`, `visibility.min.js`

**Comment by ai** [comment]
Yeap, I manually build files for CDN.

visibility.min.js = min(visibility.core.js + visibility.timers.js)
visibility.fallback.min.js = min(visibility.fallback.js)

**Comment by PeterDaveHello** [comment]
@ai So is it possible to add pre-built files in the npm package so that we can use auto-update on it and follow the origin structure on cdnjs?

**Comment by ai** [comment]
This library maybe will not have future releases ;). Is auto-update really important for this case? :)

**Comment by PeterDaveHello** [comment]
@ai hmmmm ... if this library maybe will not have future releases, that's fine, but it'll be good if we can have it.

**Comment by maruilian11** [comment]
@PeterDaveHello so let's close this pr?

**Comment by PeterDaveHello** [comment]
Okay, let's close this, @ai if you have new versions on this lib, please let us know, so that we can add it, thanks!

**Pull request closed without merging**
