### PR TITLE
add react-select v0.9.1 with npm auto-update

### LINKED ISSUE #8029: [Request] Add react-select
**Library name: react-select** 
**Git repository url: https://github.com/JedWatson/react-select**
**npm package url(optional):** 
**License(s): MIT**
**Official homepage: http://jedwatson.github.io/react-select/**
**Wanna say something? Leave message here:**

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #8029 
@x09326 please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/JedWatson/react-select
 * Official website (optional, not the repository): http://jedwatson.github.io/react-select/
 * NPM package url (optional): https://www.npmjs.com/package/react-select
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 3,540
   - Count of watchers: 92
   - Count of forks: 789
 * NPM download stats (optional):
   - Downloads in the last day: 6,977
   - Downloads in the last week: 46,962
   - Downloads in the last month: 184,657

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8029, cc @JedWatson

### CODE REVIEW

**Comment by x09326** [comment]
@PeterDaveHello 
I think this PR is okay, please help me review it, thanks.

**Comment by JedWatson** [comment]
:+1:

- [x] I'm the author of this library
  - [x] I would like to add link to the page of this library on CDNJS on website / readme

**Comment by PeterDaveHello** [comment]
You should add a stable version, not a beta version.

**Comment by kennynaoh** [comment]
So I should use git not npm, right?
Due to the latest version on npm is beta version.
Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh Totally wrong, npm can choose tje version you want.

**Comment by kennynaoh** [comment]
@x09326 
I have changed the version to latest non-beta version.
Please help me review it again.
Thanks!

**Comment by x09326** [comment]
@PeterDaveHello 
I think this PR is okay, please help me review it, thanks.

**Pull request merged**
