### PR TITLE
Add custommarkup w/ git autoupdate

### PR DESCRIPTION
**Pull request by hare1039**
Pull request for issue: #10318
Duplicate issues: #10519, #10492, #10377.

@cdnjs/intern3 Please help me reviewing this PR. Thanks.
Note the old version `main.css` is already minified.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/talonbragg/Custom-Markup
 * Official website (optional, not the repository): https://custommarkup.ml
 * NPM package url (optional): https://www.npmjs.com/package/custommarkup
 * License and its reference: MIT, [ref](https://github.com/talonbragg/Custom-Markup/blob/master/LICENSE)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 4
   - Count of stars: 18
   - Count of forks: 7
 * NPM download stats (optional):
   - Downloads in the last day: 21
   - Downloads in the last week: 334
   - Downloads in the last month: 494

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by hare1039** [comment]
@extend1994 The `main.css` is already minified. I can't compress it any more uning `minify.sh`.

**Comment by extend1994** [comment]
@hare1039 Sorry! I missed it.

**Comment by hare1039** [comment]
@clairetsai818 I think the `gulpfile.js` is used for building the solution.
And it would be better if we follow the authors autoupdate https://github.com/talonbragg/Custom-Markup/blob/master/package.json#L25
What do you think?

**Comment by talonbragg** [comment]
Thanks for working on this everybody!

**Comment by clairetsai818** [comment]
@PeterDaveHello Should we just follow the author's autoupdate [file map](https://github.com/talonbragg/Custom-Markup/blob/master/package.json#L25) which exclude `gulpfile.js`?

**Comment by PeterDaveHello** [comment]
@clairetsai818 gulpfile.js should be excluded

**Comment by hare1039** [comment]
@sufuf3 Thank you for pointing out the problem.
The author update the library versions recently.

I switch the auto-update to git since the `dist` folder exist in every git tag.
Note the `1.0.0/main.css` in npm is different `1.0/main.css` in GitHub repo.

@cdnjs/intern3 Please review this PR again. Thank you.

**Comment by hare1039** [comment]
ping @cdnjs/intern3

**Comment by hare1039** [comment]
@pvnr0082t I've rebased to master branch. Please help me review this PR. Thanks.

**Comment by talonbragg** [comment]
Thanks for working so hard on this!

**Comment by hare1039** [comment]
@pvnr0082t I changed the naming of `cm.min.css`. Please review this PR again. Thanks.

**Pull request merged**
