### PR TITLE
Enrich FileSaver.js' package.json(field: license)

### PR DESCRIPTION
**Pull request by LeaYeh**
Hi @maruilian11   , 
From #5500, I have added license info. https://github.com/eligrey/FileSaver.js/blob/master/LICENSE.md
repo : https://github.com/eligrey/FileSaver.js
Would you mind checking this PR for me? Thank you.

### CODE REVIEW

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok. i have checked this license, and it's actually a MIT license.

**Comment by PeterDaveHello** [comment]
Oh you sure?
https://github.com/eligrey/FileSaver.js/blob/f23c4a66dc9fa1af818322f08eb29a371ccb4ccf/FileSaver.js#L6

**Comment by maruilian11** [comment]
@PeterDaveHello but the format of their LICENSE.md is MIT and it didn't mention X11 license like https://spdx.org/licenses/X11.html
should we confirm with auther?

**Comment by PeterDaveHello** [comment]
Why not?

**Comment by maruilian11** [comment]
@LeaYeh could you please confirm the license with author?

**Comment by LeaYeh** [comment]
@maruilian11 i already ask the author https://github.com/eligrey/FileSaver.js/issues/178
this licence clearly is `MIT`

**Comment by eligrey** [comment]
Yep, sorry for the confusion. It should only have said MIT.

**Comment by PeterDaveHello** [comment]
Thanks @eligrey

**Comment by maruilian11** [comment]
@LeaYeh could you rebase the commit? thank you~

**Comment by LeaYeh** [comment]
i think maybe just 2 day behind we dont need to rebase :palm_tree: 
if rebase is necessary...
@PeterDaveHello if i sent pr by github editor, how to rebase it?

**Comment by PeterDaveHello** [comment]
@LeaYeh you should tell me.

**Comment by PeterDaveHello** [comment]
@LeaYeh and of course you need to rebase as we discussed before

**Comment by LeaYeh** [comment]
@maruilian11 could you give me some hints that how to rebase on github? sorry i didnt follow discussion before ><"

**Comment by PeterDaveHello** [comment]
@LeaYeh Who told you to rebase on GitHub? Nobody, you said that, so you should tell us.

**Comment by maruilian11** [comment]
@LeaYeh i usually set sparseCheckout to pull it, then, rebase it, but, i don't know if there is another way to rebase on github.

**Comment by LeaYeh** [comment]
@maruilian11 i already rebased it, could pls check it again ? thanks

**Comment by maruilian11** [comment]
@PeterDaveHello i think the pr is ok.

**Pull request merged**
