### PR TITLE
Add network-js@2.1.0 w/ npm autoupdate

### PR DESCRIPTION
**Pull request by Piicksarn**
@cdnjs/intern @cdnjs/intern2 , please help me checkout  the pr, thanks!

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/nesk/network.js
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/network-js
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 179
   - Count of watchers: 24
   - Count of forks: 48
 * NPM download stats (optional):
   - Downloads in the last day: 1
   - Downloads in the last week: 18
   - Downloads in the last month: 109

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by maruilian11** [comment]
please add versions not on npm package.

**Comment by Piicksarn** [comment]
https://github.com/nesk/network.js/issues/56

**Comment by maruilian11** [comment]
if `v2.0.0-alpha1` file structure is ok, we may add it first.

**Comment by Piicksarn** [comment]
@cdnjs/intern @cdnjs/intern2 
I got the response from author(nesk/network.js#56), and add 2.0.0-alpha1 manually only.
Thank you all!

**Comment by pvnr0082t** [comment]
@PeterDaveHello Is it better to add all old versions at the same time? Or it's fine to add old version npm auto-updater can't get?

**Comment by PeterDaveHello** [comment]
@pvnr0082t I prefer to add the missing versions that auto-updater cannot get, add them all is making review process harder

**Comment by pvnr0082t** [comment]
LGTM

**Comment by Piicksarn** [comment]
@cdnjs/intern @cdnjs/intern2 
I've it rebased to master, would you mind to have a check?

Thanks

**Comment by pvnr0082t** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
need one more review 👍

**Comment by maruilian11** [comment]
@Piicksarn I can help you review this PR, could you please rebase the commit upon our latest master again? and ping me, thanks.
and please remember mention the issue number in init comment.

**Comment by Piicksarn** [comment]
@cdnjs/intern @cdnjs/intern2 
I've it rebased to master, would you mind to have a check?
Thanks

**Pull request merged**
