### PR TITLE
add angular-google-chart v0.0.11 with git autoupdate, close #5054.

### LINKED ISSUE #5054: [Request] Add angular-google-chart
https://github.com/angular-google-chart/angular-google-chart

### PR DESCRIPTION
**Pull request by Piicksarn**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Seems there are `min` and `map` in future release, would you please make sure with its author when will they release the new version? Maybe we could add that types of file in the auto-update filemap, thanks.

**Comment by Piicksarn** [comment]
okay!
[Question for the next new version. #205](https://github.com/angular-google-chart/angular-google-chart/issues/205)

**Comment by PeterDaveHello** [comment]
I'll merge first, ping me anytime you got updates.

**Comment by Piicksarn** [comment]
sure! i'll ping you when i got any updates.
thank you!

**Pull request merged**
