### PR TITLE
[new] Add jquery-cropper w/ auto-update

### PR DESCRIPTION
**Pull request by olafcm**
# Pull request template for new library

Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

## Profile of the lib

* Git repository (required): https://github.com/fengyuanchen/jquery-cropper
* Official website (optional, not the repository): https://fengyuanchen.github.io/jquery-cropper/
* NPM package url (optional): https://www.npmjs.com/package/jquery-cropper
* License and its reference: MIT
* GitHub / Bitbucket popularity (required):
  * Count of watchers: 23
  * Count of stars: 356
  * Count of forks: 140
* NPM download stats (optional):
  * Downloads in the last day:
  * Downloads in the last week:
  * Downloads in the last month:

## Essential checklist

* [ ] I'm the author of this library
  * [ ] I would like to add link to the page of this library on CDNJS on website / readme
* [X] This lib was not found on cdnjs repo
* [X] Doesn't already exist / has duplicate issue and PR
* [X] The lib has notable popularity
  * [X] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [X] More than 800 downloads stats per month on npm registry
* [X] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [ ] Has valid tags for each versions (for git auto-update)
* [X] Auto-update setup
* [X] Auto-update target/source is valid.
* [X] Auto-update filemap is correct.

## Git commit checklist

* [ ] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [ ] The parent of the commit(s) in the PR is not older than 3 days.
* [ ] Pull request is sent from a non-master branch with a meaningful name.
* [ ] Separate unrelated changes into different commits.
* [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [ ] Close corresponding issue in commit message
* [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by olafcm** [comment]
@xtuc Thank you for approving the PR! Can you also merge it now? Thanks 😃

**Comment by olafcm** [comment]
@xtuc Thanks! How to have the bot pull in this lib? Nothing here yet: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/jquery-cropper/
Or should I add the files through another PR?

**Comment by xtuc** [comment]
We are currently investigating an issue with the autoupdate via Git. There's something left to do on your side.

**Comment by olafcm** [comment]
Are you sure, maybe I do not understand the update process correctly but I thought this package.json config would autoupdate using npm?

**Comment by xtuc** [comment]
Yes you are right, it's configured to be autoupdate whenever you publish on npm.

**Comment by olafcm** [comment]
Should I manually pull in current releases.

**Comment by xtuc** [comment]
As I said, we need to investigate what the bot is doing. I can see all the versions locally on the bot's machine but the bot is not committing them for some reason.

**Comment by olafcm** [comment]
Can the packages added by the new bot? (https://github.com/cdnjs/cdnjs/issues/13840#issuecomment-616175231)

**Comment by olafcm** [comment]
The pull request was closed but the bot has not committed the files yet (https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/jquery-cropper/). Please help thx

**Comment by olafcm** [comment]
@xtuc Any update on this bug? Thanks 😊

**Pull request merged**
