### PR TITLE
Add bootstrap-sidebar@0.2.2 w/ git auto-update

### LINKED ISSUE #9773: [Request] Add bootstrap-sidebar
**Library name:** bootstrap-sidebar
**Git repository url:** https://github.com/asyraf9/bootstrap-sidebar
**npm package url(optional):** 
**License(s):** 
**Official homepage:** 
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #9773

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/asyraf9/bootstrap-sidebar
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference: [MIT](https://github.com/asyraf9/bootstrap-sidebar/blob/master/bower.json)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 35
   - Count of stars: 247
   - Count of forks: 66
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9773, cc @asyraf9

### CODE REVIEW

**Comment by extend1994** [comment]
@PeterDaveHello please help me review this pull request, thank you.

**Comment by extend1994** [comment]
@PeterDaveHello the map files are added, please help review it, thank you.

**Comment by PeterDaveHello** [comment]
@pvnr0082t please help review this PR, thank you.

**Comment by maruilian11** [comment]
please don't mention `close issue and cc the author` in comments next time.

**Comment by extend1994** [comment]
@pvnr0082t I rebased the branch, please help me review it, thank you.
@maruilian11 Thanks for your reminder!

**Pull request merged**
