### PR TITLE
add androidicons@1.0.0 w/ git autoupdate

### LINKED ISSUE #9218: [Request] Add androidicons
**Library name:** androidicons
**Git repository url:** https://github.com/opoloo/androidicons

### PR DESCRIPTION
**Pull request by Piicksarn**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/opoloo/androidicons
- Official website (optional, not the repository): http://www.androidicons.com
- NPM package url (optional):
- GitHub / Bitbucket popularity (required):
  - Count of stars: 633
  - Count of watchers: 63
  - Count of forks: 120
- NPM download stats (optional):
  - Downloads in the last day:
  - Downloads in the last week:
  - Downloads in the last month:
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [x] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
No reviewer assigned?

**Comment by Piicksarn** [comment]
@PeterDaveHello, this pr still include some problems, I'll remember to assign others after i fix it.
Thank you!

**Comment by PeterDaveHello** [comment]
@Piicksarn any updates?

**Comment by PeterDaveHello** [comment]
@Piicksarn any updates?

**Comment by Piicksarn** [comment]
@PeterDaveHello, I still try for solution.

**Comment by PeterDaveHello** [comment]
@Piicksarn Any help you need?

**Comment by Piicksarn** [comment]
I'm stuck on the problem i mentioned on #9218.
Trying to be familiar with git hash now 😥

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by PeterDaveHello** [comment]
Close due to no response.

**Pull request closed without merging**
