### PR TITLE
add sourcemaps to dc.js

### PR DESCRIPTION
**Pull request by gordonwoodhull**
Hello wonderful cdnjs community,

Please take this pull request, adding sourcemaps to dc.js - mostly to stop Chrome's debugger from complaining, but also occasionally to aide debugging. :grinning: 

Thanks!
Gordon

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I didn't see dc.js.map there.

**Comment by gordonwoodhull** [comment]
Hi @PeterDaveHello, thanks for taking a look. 

I'm not sure what you mean - I've added `dc.js.map` to npmFileMap files

https://github.com/cdnjs/cdnjs/pull/5713/files#diff-089a95e4aa07dc266d3338570cf37d44R40

and also checked it is being distributed through npm.

**Comment by PeterDaveHello** [comment]
There is no that file in its npm package.

**Comment by gordonwoodhull** [comment]
Thanks @PeterDaveHello - I was looking at the beta.19 branch, which we also distro through cdnjs. The dc.js.map was indeed missing in 1.7.3

I've published a 1.7.4 npm release and updated this PR accordingly. Does it look good now?

**Comment by PeterDaveHello** [comment]
You should leave version field alone because we haven't add it yet, and it'll be better if you can remove `copyright` field in an individual commit because it's useless in cdnjs, many thanks.

**Comment by gordonwoodhull** [comment]
Okay, I rewrote my branch with a single commit adding the maps and removing the copyright line.

Thanks!

**Comment by gordonwoodhull** [comment]
Thanks!

**Comment by PeterDaveHello** [comment]
np, thank you too

**Pull request merged**
