### PR TITLE
[author] [new] ProStyle animation library

### PR DESCRIPTION
**Pull request by GaryChamberlain**
Hopefully I got this right now.  @PeterDaveHello thank-you for your help and your generous offer to cherry pick.  Yes, please cherry pick if needed.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
A small problem here, you use `**/*.js` in auto-update config, but only add `min.js` files in the commit, I think you should make them the same, thanks.

**Comment by GaryChamberlain** [comment]
I'll fix and squash.

**Comment by PeterDaveHello** [comment]
hmmmm and the build failed ...

**Comment by PeterDaveHello** [comment]
by the way, you can use `--amend` with commit so that you don't need to squash!

**Comment by GaryChamberlain** [comment]
@PeterDaveHello Is this good?

**Comment by PeterDaveHello** [comment]
I think you should also clean up the commit message, there are some unrelated strings.

**Comment by GaryChamberlain** [comment]
@PeterDaveHello good idea. I just amended it. Thanks for all the help!

**Pull request merged**
