### PR TITLE
update outdated-browser to 1.1.0

### PR DESCRIPTION
**Pull request by CitySim**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
We don't serve html files, and would you please tell us the source? It'll be better to add auto-update config for it.

**Comment by CitySim** [comment]
source:
* https://github.com/burocratik/Outdated-Browser/tree/master
* https://github.com/burocratik/outdated-browser/archive/master.zip

is there any documentation on how to add autoupdate for non-npm modules? and i removed the html files

**Comment by PeterDaveHello** [comment]
I think you should pull from v1.1.0, not the master, and would you please also add auto-update for it (#3638)? thanks!

**Comment by CitySim** [comment]
source is now: https://github.com/burocratik/outdated-browser/archive/1.1.0.tar.gz
I left the old files (1.0.1) named "outdated**B**rowser" but changed the filename in the `package.json` to lower-case, not sure if this will cause problems

**Comment by PeterDaveHello** [comment]
Oh, it's really nice, thanks @CitySim :+1:

**Pull request merged**
