### PR TITLE
Manually add es5 files of ice@3.7.0 & update package.json

### PR DESCRIPTION
**Pull request by pepone**
Pull request for issue: #11681

### CODE REVIEW

**Comment by pepone** [comment]
Hi @extend1994
I just remove the "namespace" field.

Thanks

**Comment by extend1994** [comment]
@pepone I will help you rebase the branch soon, don't worry about the error 😃

**Comment by PeterDaveHello** [comment]
@extend1994 I prefer not to touch namespace next time, all the fields need to be removed will be caught by `npm test`.

**Comment by extend1994** [comment]
Okay I will remember it.

**Pull request merged**
