### PR TITLE
Update package.json of jsoneditor

### PR DESCRIPTION
**Pull request by josdejong**
Changes:

- Fixes not all files from `dist` folder being copied.
- Fixes broken project url.
- Updated description.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@josdejong may I know the reason why to use git auto-update not npm? Thanks.

**Comment by josdejong** [comment]
O, I thought the npmFileMap was old and autoupdate was new and the way to go. I don't have any preference as long as it works.

**Comment by josdejong** [comment]
I now see in the cdnjs docs that npm is recommended https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md, Will update the PR accordingly

**Comment by josdejong** [comment]
I've updated the PR, CircleCI is still running

**Comment by PeterDaveHello** [comment]
@josdejong would you please squash/fixup them into only only commit? Thanks!

**Comment by josdejong** [comment]
ok I will create a new PR

**Comment by josdejong** [comment]
New PR is here: #7025

**Pull request closed without merging**
