### PR TITLE
add muicss w/ npm auto-update

### LINKED ISSUE #8334: [Request] Add MUI
**Library name:** MUI
**Git repository url:** https://github.com/muicss/mui
**License(s):** MIT
**Official homepage:** https://www.muicss.com/

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #8334
@pvnr0082t , @x09326 please help me review this pull request, thank you.
Manually add some old versions from git repo, add v0.0.1~v0.0.3 from zip file the author offered and some file structure and naming structure are changed.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/muicss/mui
 * Official website (optional, not the repository): https://www.muicss.com
 * NPM package url (optional): https://www.npmjs.com/package/muicss
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 2711
   - Count of watchers: 141
   - Count of forks: 301
 * NPM download stats (optional):
   - Downloads in the last day: 110
   - Downloads in the last week: 1901
   - Downloads in the last month: 5748

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8334, cc @iamJoeTaylor

### CODE REVIEW

**Comment by x09326** [comment]
LGTM

**Comment by pvnr0082t** [comment]
@kennynaoh How about v0.1.19-rc1 and v0.0.6-rc1?

**Comment by kennynaoh** [comment]
@x09326 , @pvnr0082t 
I have minified it in some versions.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
> @kennynaoh How about v0.1.19-rc1 and v0.0.6-rc1?

So what's the reply for this?

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 
Sorry about that.
Please review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by iamJoeTaylor** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@iamJoeTaylor is it possible to also provide minified files under `/dist/email/`? Thanks.

**Pull request merged**
