### PR TITLE
add Hyphenator@5.1.0 w/ git autoupdate

### LINKED ISSUE #8050: [Request] Add Hyphenator
**Library name:** Hyphenator
**Git repository url:** https://github.com/mnater/hyphenator
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://mnater.github.io/Hyphenator/

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8050 
@kennynaoh Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/mnater/hyphenator
 * Official website (optional, not the repository): 
 * NPM package url (optional): 
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 303
   - Count of watchers: 24
   - Count of forks: 40
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8050, cc @mnater

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Ping @kennynaoh

**Comment by kennynaoh** [comment]
Sorry for late review.
@PeterDaveHello 
Should the `modalLangDialog.html` file need to be added?
https://github.com/mnater/Hyphenator/blob/master/Hyphenator.js#L1494

**Comment by PeterDaveHello** [comment]
We don't support html on CDN yet, can you confirm that is this required?

**Comment by pvnr0082t** [comment]
@kennynaoh The author said that Hyphenator.js can work without `modalLangDialog.html`. 
ref: https://github.com/mnater/Hyphenator/issues/266 
Please help me review again, thank you.

**Comment by kennynaoh** [comment]
@pvnr0082t 
Please rebase to the latest master branch.
Thanks!

**Comment by pvnr0082t** [comment]
@kennynaoh I have rebase to the latest master branch. Please help me review again, thank you.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Comment by PeterDaveHello** [comment]
@pvnr0082t some old tags (https://github.com/mnater/Hyphenator/tags) need manual works to add them, next time you should try to also submit those versions.

**Pull request merged**
