### PR TITLE
[new] add KindEditor

### PR DESCRIPTION
**Pull request by huaiping**
KindEditor is a lightweight, Open Source, cross browser, web based WYSIWYG HTML editor. KindEditor has the ability to convert standard textareas to rich text editing.

http://kindeditor.org/

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@huaiping I'm so sorry about this late reply, not sure if you're still interested in this PR, I think there are few parts we need to deal with, like `ajax/libs/KindEditor/4.1.1/.gitignore` and `ajax/libs/KindEditor/README.md` need to be removed, once the problems been fixed, we can merge this PR, thanks.

**Comment by PeterDaveHello** [comment]
Hello, any updates here? Thanks.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello this PR duplicated with #8146 
can we close it?
Because there is no response since 14 Dec 2016.
Thank you.

**Comment by PeterDaveHello** [comment]
Okay, let's close it.

**Pull request closed without merging**
