### PR TITLE
Add Flickity, w/ auto-update & v0.2.3 files

### PR DESCRIPTION
**Pull request by desandro**
Added new library: [Flickity](http://flickity.metafizzy.co/) with original v0.2.3 files

Replaces cdnjs/cdnjs#4361

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please also add minified css, thanks!

**Comment by desandro** [comment]
Minified CSS is not currently produced when building `flickity/dest`. Is this required?

**Comment by PeterDaveHello** [comment]
Yes is required, so I'll respectfully ask you to manually minify it as our document said, thanks!

**Comment by desandro** [comment]
Sure thing! `flickity.min.css` added, and rebased for 1 commit.

**Comment by PeterDaveHello** [comment]
Thanks!

**Pull request merged**
