### PR TITLE
Add intense-images@1.0.3 w/ npm auto-update

### LINKED ISSUE #11242: [Request] Add intense-images
**Library name:** intense-images
**Git repository url:** https://github.com/tholman/intense-images
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** http://tholman.com/intense-images
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by dakshshah96**
close #11242, cc @tholman

Pull request for issue: #11242 
Related issue: #10933 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/tholman/intense-images
 * Official website (optional, not the repository): http://tholman.com/intense-images
 * NPM package url (optional): https://www.npmjs.com/package/intense-images
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 78
   - Count of stars: 2,286
   - Count of forks: 279
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by dakshshah96** [comment]
@sufuf3 Author has added git tags.

However, this package is hosted on npm (https://www.npmjs.com/package/@tholman/intense-images) and we can use that instead. I'll update this PR.

**Comment by PeterDaveHello** [comment]
@dakshshah96 nice

**Comment by dakshshah96** [comment]
@extend1994 Done 👍

**Comment by dakshshah96** [comment]
@pvnr0082t Done 👍

**Comment by PeterDaveHello** [comment]
The npm info in the comment is wrong, isn't it?

**Pull request merged**
