### PR TITLE
add sentient lang with npm auto-update

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #8730 
@pvnr0082t, @x09326 please help me review this pull request, thank you.
There aren't exist the file author want to host in version 0.0.0-alpha.27~0.0.0-alpha.39
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/sentient-lang/sentient-lang
 * Official website (optional, not the repository): https://sentient-lang.org/
 * NPM package url (optional): https://www.npmjs.com/package/sentient-lang
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 3
   - Count of watchers: 1
   - Count of forks: 0
 * NPM download stats (optional):
   - Downloads in the last day: 94
   - Downloads in the last week: 139
   - Downloads in the last month: 740

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
Why do the `sentient.js` in `0.0.0-alpha.0` and `0.0.0-alpha.1` not be minified? @kennynaoh

**Comment by kennynaoh** [comment]
Sorry I didn't notice that.
What should I do about these two versions?
Because the `sentient.js` file in other version are minified.
If I minify it by myself, it has different naming scheme from other version.
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
In this case, maybe just minify these two versions, btw, this lib is not popular enough to add it with only non-stable/experimental versions, please be careful next time.

**Comment by kennynaoh** [comment]
OK

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 
I have minified the file in version `0.0.0-alpha.0` and `0.0.0-alpha.1`.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by pvnr0082t** [comment]
@kennynaoh Why did you minify the file without generating `map`?

**Comment by kennynaoh** [comment]
The other version of minified file without `map` file, so I didn't create map file.

**Comment by pvnr0082t** [comment]
@PeterDaveHello In this case, should the files need to be minified with `.map`?

**Comment by PeterDaveHello** [comment]
No file map in this situation is fine, thanks you.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by x09326** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
Thanks.

**Pull request merged**
