### PR TITLE
[request] [author] PostgREST Client

### PR DESCRIPTION
**Pull request by calebmer**
Library name: postgrest-client 
Git repository url: https://github.com/calebmer/postgrest-client
npm package url: https://www.npmjs.com/package/postgrest-client
License: MIT

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please take a look at this:
https://github.com/cdnjs/cdnjs#create-or-update-packagejson

and you can take jquery as an example to add some details like 
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/jquery/package.json
```js
{
  "name": "jquery",
  "npmName": "jquery",
  "npmFileMap": [
    {
      "basePath": "/dist/",
      "files": [
        "jquery.*"
      ]
    }
  ],
  "filename": "jquery.min.js",
  "version": "3.0.0-alpha1",
  "description": "JavaScript library for DOM operations",
  "homepage": "http://jquery.com/",
  "keywords": [
    "jquery",
    "library",
    "ajax",
    "framework",
    "toolkit",
    "popular"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/jquery/jquery.git"
  },
  "license": "MIT",
  "author": {
    "name": "jQuery Foundation and other contributors",
    "url": "https://github.com/jquery/jquery/blob/master/AUTHORS.txt"
  }
}
```

**Comment by PeterDaveHello** [comment]
BTW once this PR passed the test, and we reviewed it, we'll need you to squash/fiup them into only one commit, thanks!

**Comment by calebmer** [comment]
👍 Tests pass and commits have been squashed.

**Comment by PeterDaveHello** [comment]
Don't we need `lib` folder?

**Comment by PeterDaveHello** [comment]
@calebmer I noticed that in v1.0.0/1.0.1, the content in `dist` folder looks like current `lib` folder, do you have any idea about how to add its older versions? Thanks.

**Comment by calebmer** [comment]
The older versions did not have a single file build for the client which
could be hosted on cdnjs. If it's really needed, running `webpack` or
`browserify` on index.js should do the trick.

**Comment by PeterDaveHello** [comment]
Nope it's not needed, I'll just update .gitginore to ignore them, since looks v1.1.0 has the same stucture as v1.1.1, I'll add v1.1.0. Would you please confirm that we don't need `lib` folder? Thanks.

**Comment by calebmer** [comment]
Yes. You don't need `lib`, it's the pre compiled files.

**Comment by PeterDaveHello** [comment]
Ok, thanks!

**Pull request merged**
