### PR TITLE
Added Cleverbot.io.js v1.0

### PR DESCRIPTION
**Pull request by dtesler**
[cleverbot.io](https://cleverbot.io) JavaScript client.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please squash all these commits into only one commit as our document said, thanks!

**Comment by dtesler** [comment]
I'm not quite sure how to do that

**Comment by PeterDaveHello** [comment]
https://help.github.com/articles/about-git-rebase/

**Comment by drewfreyling** [comment]
Closing due to no response and a lack of library popularity.

**Pull request closed without merging**
