### PR TITLE
load.js add license field with MIT

### PR DESCRIPTION
**Pull request by LeaYeh**
@maruilian11 could plz check this pr?
lib: https://github.com/chriso/load.js
this lib has only one version.

#5500

### CODE REVIEW

**Comment by maruilian11** [comment]
@LeaYeh may i ask you how do you tell its license is MIT? thank you!

**Comment by PeterDaveHello** [comment]
https://github.com/chriso/load.js#license

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Comment by LeaYeh** [comment]
@maruilian11  okay i rebase it again.

**Comment by maruilian11** [comment]
@LeaYeh sorry for checking late...  could you rebase it again? thank you :(

**Pull request merged**
