### PR TITLE
[New] Add texthighlighter w/ git auto-update

### PR DESCRIPTION
**Pull request by sufuf3**
Pull request for issue: #11298 
Related issue(s): #9273, #9234

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/mir3z/texthighlighter
 * Official website (optional, not the repository): https://mir3z.github.com/texthighlighter/
 * NPM package url (optional):
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 14
   - Count of stars: 140
   - Count of forks: 64
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@cdnjs/intern3 
Please help me review this PR, Thank you.

Note:
Although there is a new version from npm(https://www.npmjs.com/package/texthighlighter)
but the repository is from https://github.com/guidupuy/texthighlighter
the `guidupuy/texthighlighter` is fork from `mir3z/texthighlighter`, and `guidupuy/texthighlighter` is not enough popular so I add origin library.

**Comment by sufuf3** [comment]
@extend1994 I modified the commit message, please help me review the PR, thanks.

**Comment by sufuf3** [comment]
@pvnr0082t 
Please help me review this PR, Thank you.

**Comment by PeterDaveHello** [comment]
Don't we need `jquery.textHighlighter.pack.min.js` in old versions?
Also, please mention how do you get the old versions with some details.

**Comment by sufuf3** [comment]
Yes, we need. I'll add `jquery.textHighlighter.pack.min.js`.
But I have two questions:
1. Should I rename it from `jquery.textHighlighter.pack.min.js` to `TextHighlighter.min.js`?
2. Should I remove  `jquery.textHighlighter.js` and `jquery.textHighlighter.min.js`? 
Because the `README.md` of v1.2.0 say just add `TextHighlighter.min.js`, and the old versions (v0.1~v0.2.1) said just add `jquery.textHighlighter.pack.js` to head section of web page. 

Here are the reference: 
- new version README: https://github.com/mir3z/texthighlighter/tree/v1.2.0#getting-started
- old versions homepage tutorial: https://web.archive.org/web/20140530233115/http://mir3z.github.io:80/jquery.texthighlighter/

**Comment by sufuf3** [comment]
@PeterDaveHello , please help me review this PR, Thank you.

- I added `jquery.textHighlighter.pack.min.js` and renamed the file of old versions from `jquery.textHighlighter.pack.min.js` to `TextHighlighter.min.js`
- And removed `jquery.textHighlighter.js` and `jquery.textHighlighter.min.js` from old versions.
Because the `README.md` of v1.2.0 say just add `TextHighlighter.min.js`, and the old versions (v0.1~v0.2.1) said just add `jquery.textHighlighter.pack.js` to head section of web page. 
- And modified the commit message.

reference: 
- new version README: https://github.com/mir3z/texthighlighter/tree/v1.2.0#getting-started
- old versions homepage tutorial: https://web.archive.org/web/20140530233115/http://mir3z.github.io:80/jquery.texthighlighter/

**Comment by sufuf3** [comment]
in old versions, I added `jquery.textHighlighter.js` and `jquery.textHighlighter.min.js` in my conjecture, because the link of old versions' homepage can't access (HTTP code is 404), I can't figure out which file I should add. 
When you said we need to add `jquery.textHighlighter.pack.min.js` I search the old versions' homepage history from https://web.archive.org, just knew we should add this file finally.

@cdnjs/library-reviewer 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@cdnjs/library-reviewer
Please help me review this PR, Thank you.

**Comment by PeterDaveHello** [comment]
Shouldn't you request review from @cdnjs/intern3 first?

**Comment by sufuf3** [comment]
@cdnjs/intern3 Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@extend1994 as this comment https://github.com/cdnjs/cdnjs/pull/11332#pullrequestreview-43714580 said, I think don't have to rename 'jquery.textHighlighter.pack.min.js '.
What do you say?

**Comment by sufuf3** [comment]
@cdnjs/library-reviewer 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@hare1039 @qwe19272375 @pvnr0082t @maruilian11 
Please help me review this PR, Thank you.

**Comment by maruilian11** [comment]
Don't we need `jquery.textHighlighter.js`?

**Comment by sufuf3** [comment]
@maruilian11 I don't think we need it because the tutorial teaches me just use `TextHighlighter.min.js`.
And in the demo files, I didn't find `jquery.textHighlighter.js` in them.

**Comment by PeterDaveHello** [comment]
Looks like we need it.

**Comment by sufuf3** [comment]
@maruilian11 I added the `jquery.textHighlighter.js` and modified the fileMap from `TextHighlighter*` to `+(*textHighlighter|TextHighlighter).*`.
Please help me review this PR, Thank you.

@extend1994 @hare1039  Please help me review this PR, too. Thank you.

**Comment by sufuf3** [comment]
@PeterDaveHello 
Please help me review this PR, Thank you.

**Pull request merged**
