### PR TITLE
Add three-orbit-controls@72.0.0 w/ npm-autoupdate

### PR DESCRIPTION
**Pull request by Piicksarn**
@cdnjs/intern @cdnjs/intern2,
Please help me for checking the pr, thank u!

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/mattdesl/three-orbit-controls
- Official website (optional, not the repository): 
- NPM package url (optional): https://nodei.co/npm/three-orbit-controls/
- GitHub / Bitbucket popularity (required):
  - Count of stars: 57
  - Count of watchers: 3
  - Count of forks: 14
- NPM download stats (optional):
  - Downloads in the last day: 93
  - Downloads in the last week: 535
  - Downloads in the last month: 1753
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [x] The lib has notable popularity
  - [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [x] More than 500 downloads stats per month on npm registry
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
LGTM

**Comment by maruilian11** [comment]
@Piicksarn how can you make sure `index.js` can be directly used in browser? thanks!

**Comment by Piicksarn** [comment]
@maruilian11,
I wonder to know which part make you confused to the usage of index.js 
There is a link for the turtorial : https://www.npmjs.com/package/three-orbit-controls/tutorial
The link above shows the installation of the library and not shows the requirement of other library's installation.
https://github.com/mattdesl/three-orbit-controls#usage
The second link is the usage of it.
I didn't the find any problem of index.js
And after trying **test.js**, tracing the code of **test.js**, I think index.js is what the user needed and could show the effect on browser.
Have you tried **test.js**?

**Comment by maruilian11** [comment]
I tried to follow the https://github.com/mattdesl/three-orbit-controls#testing npm install and npm start, but it ran out of all my ram and aborted. 
can you rebase this commit upon our latest master? I think this PR is ok.

**Comment by Piicksarn** [comment]
@maruilian11, i have it rebased!
pls. help me for reviewing, thank you!

**Comment by PeterDaveHello** [comment]
Please confirm that this will work in browser.

**Comment by Piicksarn** [comment]
@mattdesl :sparkles: 
We need to confirm the file which we contained be able to work in browser.
Would you mind to help us for making  a discussion of index.js?

**Comment by Piicksarn** [comment]
@mattdesl :sparkles:
Would you mind to help us for making a discussion of index.js?

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello I don't think this lib can use in web front-end.
Can we close this PR?
Thank you.

**Comment by PeterDaveHello** [comment]
Let's close this one.

**Pull request closed without merging**
