### PR TITLE
[author] [new] Add animsition

### PR DESCRIPTION
**Pull request by ungki**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please add its real files as the first time you add the new lib, thanks.

**Comment by ungki** [comment]
repo      : https://github.com/blivesta/animsition
ghpage : http://git.blivesta.com/animsition

thanks @PeterDaveHello

**Comment by PeterDaveHello** [comment]
type in target field, and please squash/merge these commits into only one commit, thanks!

**Comment by ungki** [comment]
My local have error. I don't know it error. PR again.

**Pull request closed without merging**
