### PR TITLE
add auto-update config & update to a stable version of onsen

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 , From #5276, I would like to fix onsen to point to a stable version.
repo: https://github.com/OnsenUI/OnsenUI
The latest stable version of onsen is v1.3.8, but cdnjs doesn't have now.
So I add v1.3.8 and update version number in package.json.
I also add auto-update config and update info in package.json.
Would you mind checking this PR for me? Thank you~ :-)

### CODE REVIEW

**Comment by maruilian11** [comment]
i think we don't need the files under <code> /css/font_awesome/fonts </code> and <code> /build/js/angular </code>

**Comment by Amomo** [comment]
@maruilian11 I use `js/*` and `css/*`, and I think `*` sign would not collect the files in subdirectories.
You can reference the discussion in this PR #5117, it mentions how notations do matching.
https://github.com/isaacs/node-glob

**Comment by maruilian11** [comment]
@Amomo oh~ i see~ thank you for learning me a lesson！
@PeterDaveHello i think it's ok.

**Comment by PeterDaveHello** [comment]
Please rebase with our latest master branch.

**Comment by Amomo** [comment]
@PeterDaveHello I have rebased it!

**Comment by PeterDaveHello** [comment]
A little bit late, can you do it again?

**Comment by Amomo** [comment]
Ok, I have rebased it again.

**Pull request merged**
