### PR TITLE
update package.json of jquery.formset

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 , From #5420, I have updated info in package.json of jquery.formset.
From #5500, I also add license info.
old repo : https://code.google.com/p/django-dynamic-formset/
repo : https://github.com/elo80ka/django-dynamic-formset
The repo on GitHub don't have tags, so I don't add auto-update config.
Would you mind checking this PR for me? Thank you~ :-)

- [ ] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `13`, Star `113`, Fork `67`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by maruilian11** [comment]
@Amomo would u please open a issue and asked the author if he/she can consider adding tags? thank you!

**Comment by Amomo** [comment]
@maruilian11 I have opened an issue for asking the author to add tags.
https://github.com/elo80ka/django-dynamic-formset/issues/91
And, I have rebased this PR, could you take a look? thank you~

**Comment by maruilian11** [comment]
@Amomo sorry for checking it late, can you rebase it again and me :(

**Comment by Amomo** [comment]
@maruilian11 
Because author has add tags in the library now, I sent a commit to add auto-update config in package.json in the second commit.
Could you check this PR again? Thank you~ :-D

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Comment by PeterDaveHello** [comment]
Let's make `repositories` field `repository`

**Comment by Amomo** [comment]
@maruilian11 I have modified the `repository` field, could you check this PR again?
Thank you very much!

**Comment by Amomo** [comment]
@maruilian11 could you please check this PR again? Thank you! :-D

**Comment by maruilian11** [comment]
@Amomo i think this PR is ok,  i'm sorry, could you rebase again? thank you!!!

**Comment by Amomo** [comment]
@maruilian11 I have rebased it! Thank you~

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Pull request merged**
