### PR TITLE
Enrich 960gs' package.json(field: license)

### PR DESCRIPTION
**Pull request by LeaYeh**
Hi @Piicksarn  , 
From #5500, I have added license info. https://github.com/nathansmith/960-Grid-System/issues/31
Would you mind checking this PR for me? Thank you.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@LeaYeh Please try to use single PR to add multiple licenses info of libs.

**Comment by LeaYeh** [comment]
but author said he used MIT licence, why we need to add multiple licenses info?

**Comment by PeterDaveHello** [comment]
@LeaYeh Please try to use single PR to add multiple licenses info of **libs**.

**Comment by PeterDaveHello** [comment]
It's under duo licenses.

**Pull request closed without merging**
