### PR TITLE
[new] add segment-js@0.1.2

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11

For #6529, I add segment-js at v0.1.2 and add `npm` auto-update config in its package.json.

repo url: https://github.com/lmgonzalves/segment
npm package url: https://www.npmjs.com/package/segment-js

Would you mind checking this PR for me? Thank you~ :-D

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `38`, Star `836`, Fork `42`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by maruilian11** [comment]
@Amomo could you please tell me why we need `.node.js` ??

**Comment by Amomo** [comment]
@maruilian11 oh, you're right, we don't host this kind of file. Thank you for finding it out.
Could you help me check again? Thank you! :-)

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Comment by PeterDaveHello** [comment]
Let's try to exclude the node file with wildcard in auto-update config.

**Comment by PeterDaveHello** [comment]
and noticed that the file with node naming was minified, usually we don't minify code to run under nodejs, maybe it can run on browser also, I'm not sure, would you please confirm that?

**Comment by Amomo** [comment]
@PeterDaveHello 
Ummm, so I just put the node.js file back, and set the auto-update config like previous?

**Comment by PeterDaveHello** [comment]
@Amomo may contact with author first?

**Comment by Amomo** [comment]
ok

**Comment by lmgonzalves** [comment]
@PeterDaveHello @Amomo 
Hi, I'm the author of `segment`. The library is stable and ready for use in production. But now the latest release is `1.0.0` and I've created a tag for that. Also, the `.node` file is not for the browser, but just to work with `npm`, I've unminified it to avoid confusions.

Please let me know if something else is needed. And thanks for help distributing `segment` :)

**Comment by PeterDaveHello** [comment]
@lmgonzalves thanks, we will add a new version and let you know.

**Pull request closed without merging**
