### PR TITLE
add knockout-delegated-events@0.6.1 w/ npm autoupdate

### LINKED ISSUE #8647: [Request] knockout-delegatedEvents
**Library name:** 
knockout-delegatedEvents
**Git repository url:**
https://github.com/rniemeyer/knockout-delegatedEvents
**npm package url(optional):** 
https://www.npmjs.com/package/knockout-delegated-events
**License(s):**
The MIT License (MIT)
**Official homepage:**
http://www.knockmeout.net/2012/11/revisit-event-delegation-in-knockout-js.html
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8647 
@kennynaoh Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/rniemeyer/knockout-delegatedEvents
 * Official website (optional, not the repository): http://www.knockmeout.net/2012/11/revisit-event-delegation-in-knockout-js.html
 * NPM package url (optional): https://www.npmjs.com/package/knockout-delegated-events
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 143
   - Count of watchers: 18
   - Count of forks: 39
 * NPM download stats (optional):
   - Downloads in the last day: 0
   - Downloads in the last week: 5
   - Downloads in the last month: 27

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8647 , cc @rniemeyer

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I doubt is the homepage should be the url you provided, in the readme, it says that url links to the "background" of this lib.

**Comment by pvnr0082t** [comment]
@PeterDaveHello So the background url about lib should not be homepage?

**Comment by PeterDaveHello** [comment]
@pvnr0082t I don't think it's a "homepage", do you?

**Comment by pvnr0082t** [comment]
@kennynaoh I have removed homepage field. Please help me review again, thank you.

**Comment by PeterDaveHello** [comment]
@pvnr0082t the branch name is a little bit too long, and I'll respect you to delete some useless branches.

**Comment by drewfreyling** [comment]
Why does the branch name on someone's fork matter @peterdavehello?

**Comment by PeterDaveHello** [comment]
@drewfreyling It makes default merge commit message too long.

**Pull request merged**
