### PR TITLE
add git auto-update config of prism, close #6612

### LINKED ISSUE #6612: [Request] Update prism
**Library name:** prism
**CNDJS url:** https://cdnjs.com/libraries/prism
**Git repository url:** https://github.com/PrismJS/prism
**Official homepage:** http://prismjs.com/
**Wanna say something? Leave message here:**

Please update latest version.
**Latest version:** 1.3.0
**Available version:** 0.0.1

### PR DESCRIPTION
**Pull request by maruilian11**
@Piicksarn could you help me check the PR for #6612 ? thank you!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
What about the `themes`? 
PS: npm package: https://www.npmjs.com/package/prismjs

**Comment by maruilian11** [comment]
@PeterDaveHello but npm package only have versions under 1.0.0, according  to the issue, 1.3.0 is required, or we use npm auto-update, the add version to 1.3.0 by an other PR?

**Comment by PeterDaveHello** [comment]
> @PeterDaveHello but npm package only have versions under 1.0.0, according to the issue, 1.3.0 is required, or we use npm auto-update, the add version to 1.3.0 by an other PR?

Okay, if so, don't use it.

**Comment by maruilian11** [comment]
@PeterDaveHello i had some mistakes, npm package do have v1.3.0, so i still use npm auto-update config.

**Comment by PeterDaveHello** [comment]
@maruilian11 Okay,  i was wondering why i saw v1.3.0 earlier...

**Comment by PeterDaveHello** [comment]
Failed.

**Comment by maruilian11** [comment]
@PeterDaveHello the error message said...
```>
/ajax/libs/prism/0.0.1/plugins/autolinker/prism-autolinker.min.css does not exist but is required!
```
i thought adding auto-update config doesn't need to add new file?
so, in this case, i need to add a new version ?

**Comment by maruilian11** [comment]
@PeterDaveHello i have added v1.3.0.

**Comment by PeterDaveHello** [comment]
If you have problem with npm, use git auto-udpate.

**Comment by maruilian11** [comment]
@PeterDaveHello i have changed to git auto-update.

**Comment by maruilian11** [comment]
@Piicksarn could you help me check this PR?

**Comment by maruilian11** [comment]
ping @Piicksarn

**Comment by Piicksarn** [comment]
@maruilian11, sorry for my delay, would you please rebase to master again?
:cry:

**Comment by maruilian11** [comment]
@Piicksarn @Amomo could you help me check this PR? it's a little in hurry.

**Comment by maruilian11** [comment]
@Amomo thank you, i have corrected it~

**Comment by Amomo** [comment]
@PeterDaveHello 
maruilian11 added files from "components/", "plugins/", "themes/" and "prism.js" with their minified file at v1.4.1 in the first commit. No file is lost.
Then, she add npm auto-update config in package.json.

 I think this PR is fine. Could you take a look, thanks!

**Comment by PeterDaveHello** [comment]
@Amomo Okay

**Comment by maruilian11** [comment]
@PeterDaveHello please check the auto-update config, thanks.

**Pull request merged**
