### PR TITLE
Add zingchart-react@1.0.5 w/ npm auto-update

### LINKED ISSUE #9796: [Request] Add ZingChart-React
**Library name:** ZingChart-React 
**Git repository url:** https://github.com/zingchart/ZingChart-React
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:**
**Wanna say something? Leave message here:** cc #6754

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by lcd78706**
Pull request for issue: #9796 
Related issue(s): # #9414 

@kennynaoh  Please review this PR. Thanks!
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/zingchart/ZingChart-React
 * Official website (optional, not the repository): 
 * NPM package url (optional): https://www.npmjs.com/package/zingchart-react
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 49
   - Count of watchers: 18
   - Count of forks: 4
 * NPM download stats (optional):
   - Downloads in the last day: 12
   - Downloads in the last week: 59
   - Downloads in the last month: 180

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

cc #9414, close #9796, cc @mike-schultz, cc @danne931, cc @derekfletes

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@lcd78706 Hey I think we don't need to cc so many authors.

**Comment by lcd78706** [comment]
@PeterDaveHello 
Shouldn't I cc the author or contributor"s" ?

**Comment by PeterDaveHello** [comment]
@lcd78706 contributors are kind of author, I'll only cc the main author, or the repository owner, but not the contributors.

**Comment by lcd78706** [comment]
@PeterDaveHello  So I have to amend the commit message ?

**Comment by PeterDaveHello** [comment]
@lcd78706 no need, just be careful next time.

**Comment by lcd78706** [comment]
@PeterDaveHello  OK. I'll be careful.

**Comment by kennynaoh** [comment]
@lcd78706 Please also fill in the related issue in comment table next time.

**Comment by kennynaoh** [comment]
LGTM
ping @cdnjs/intern2

**Comment by lcd78706** [comment]
@pvnr0082t  I have modified the commit message.

**Comment by pvnr0082t** [comment]
@lcd78706 You should wait for CI test finished.

**Comment by PeterDaveHello** [comment]
Anyway, it's done now.

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
