### PR TITLE
modify npm auto-update example

### PR DESCRIPTION
**Pull request by maruilian11**
i think `dist` and `**/*` is better.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
There is no `dist` now ...

```
array/    chain/    collection/    date/    function/    index.js   lang/    LICENSE  math.js  number.js  object.js     README.md  string.js   utility/
array.js  chain.js  collection.js  date.js  function.js  internal/  lang.js  math/    number/  object/    package.json  string/    support.js  utility.js
```

**Comment by maruilian11** [comment]
but according to the structure example under npm auto-update example, i think we still can use `dist` and `**/*` to let people understand what we mean. or we can change a lib name?

**Comment by PeterDaveHello** [comment]
there is no dist now ... don't do a work not help

**Comment by PeterDaveHello** [comment]
I think you can choose another lib as example

**Comment by maruilian11** [comment]
i have modified lib to `function-plot`.

**Comment by PeterDaveHello** [comment]
cc #6236

**Comment by PeterDaveHello** [comment]
ping @maruilian11 to open a new issue for readme.md

**Comment by maruilian11** [comment]
ok.

**Pull request merged**
