### PR TITLE
[new] Adding page.js

### PR DESCRIPTION
**Pull request by jcoffland**
Trying this again with autoupdate.

### CODE REVIEW

**Comment by jcoffland** [comment]
The tests failed but shouldn't it automatically pull in the latest version?

**Comment by PeterDaveHello** [comment]
The first PR to add a lib should contain is real files.

**Comment by jcoffland** [comment]
Ok, thanks, I'll try that.

**Comment by jcoffland** [comment]
The original Javascript in git is incomplete.  It has dependencies on other packages and is not minified.  I don't have control of the original project.  Are there ways to solve this?  Is it possible to automatically pull from npm archives?

**Comment by PeterDaveHello** [comment]
We support npm auto-update.

**Comment by jcoffland** [comment]
@PeterDaveHello Any idea why this is still failing?

**Comment by PeterDaveHello** [comment]
As it said ...

>       ✗ page.js package.json is valid 
        » page.js didn't parse as any known format: 
  	  » NPM package.json 
  		Property is required (true): /properties/filename // valid-packages-test.js:82

**Comment by jcoffland** [comment]
Ok, I saw that but didn't understand it.  After some thought I think I get what it means.

**Comment by PeterDaveHello** [comment]
And please squash these commits into only one commit and rebase(sync) your branch with our latest master branch, thanks.

**Comment by jcoffland** [comment]
How's it look now?

**Comment by PeterDaveHello** [comment]
Looks okay, it'll be even better if you can clean up the commit message, ha.

**Comment by jcoffland** [comment]
Ok, I'll do that next time.  BTW, squashing is a pain.  I had done everything on GitHub up to that point.  Then I had to clone the entire repo which is current over 1GiB.  This takes awhile.  I wish there was a better way.  I suppose some friction keeps the lazy devs away.  Thanks for the merge!

**Comment by PeterDaveHello** [comment]
Yeah, we need time to setup a whole new method to handle this issue. BTW, the size of repo should be only about 800MB.

**Comment by jcoffland** [comment]
If I run ```du``` on my clone it says it's using 12GiB.  When I cloned the repo it downloaded 624.96 MiB in objects according to git.  So you're right the download is less than 1GiB but still large.

Yeah, I'm sure a new method would be a lot of work.  Thanks for creating this project, BTW.

**Comment by PeterDaveHello** [comment]
np

**Comment by PeterDaveHello** [comment]
Oh BTW, I think you can add `--depth 10` to decrease the repo size because you don't need the history and old, dirty things that we already dropped.

**Comment by jcoffland** [comment]
I read that doing this can make your push fail.  Haven't tried it though.

**Comment by PeterDaveHello** [comment]
I don't think so, I use it many times.

**Comment by jcoffland** [comment]
Good to know.

**Comment by PeterDaveHello** [comment]
BTW, I think this will help you:
https://github.com/cdnjs/cdnjs/blob/master/sparseCheckout.md

**Comment by jcoffland** [comment]
Thanks!

**Pull request merged**
