### PR TITLE
add v1.1.6~1.1.12, v2.0.3 & update auto-update config of line-chart

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11, for #6560

We have "line-chart" with git auto-update to v1.1.4.
Because the filemap has changed in v1.1.6~1.1.12 and v2.0.0~2.0.3.
So we don't have the newer versions.

And, I found that "line-chart" start using `npm` from v2.0.0.
So, I add the versions we lost before v2.0.0 in first commit.
Then, add v2.0.3 to modify the "filename" field in package.json.
Finally, I update the auto-update config to npm auto-update config.

GitHub repo: https://github.com/n3-charts/line-chart/
npm package url: https://www.npmjs.com/package/n3-charts

Would you mind checking this PR for me? Thank you~ :-D

- [ ] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `53`, Star `1,083`, Fork `165`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by maruilian11** [comment]
@Amomo could you also update the `license`? thank you.

**Comment by Amomo** [comment]
@maruilian11 ok, I have updated the "license" field.
Could you check this PR again? Thank you~ :-D

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Comment by Amomo** [comment]
ok, I use `"**/*"` now~

@maruilian11 could you help me checking this PR again?
Thank you! :-D

**Pull request merged**
