### PR TITLE
Add license of tweet, cc #9248

### PR DESCRIPTION
**Pull request by clairetsai818**
https://github.com/seaofclouds/tweet#licensed-under-the-mit

### CODE REVIEW

**Comment by clairetsai818** [comment]
@PeterDaveHello please help me to check this!

**Comment by pvnr0082t** [comment]
@clairetsai818 You can paste the reference link in `README` like this https://github.com/seaofclouds/tweet#licensed-under-the-mit. It will be more precise.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by clairetsai818** [comment]
@pvnr0082t got it! Thanks a lot.

**Comment by PeterDaveHello** [comment]
@clairetsai818 note the the commit message is a little bit not clear, should be something like the title of this PR.

**Pull request merged**
