### PR TITLE
add please-wait v0.0.5 with autoupdate config

### LINKED ISSUE #7537: [Request] PleaseWait.js
**Library name:*PleaseWait.js* 
**Git repository url:*https://github.com/Pathgather/please-wait*
**npm package url(optional):*please-wait* 
**License(s):*MIT*
**Official homepage:*http://pathgather.github.io/please-wait/*
**Wanna say something? Leave message here:**

### PR DESCRIPTION
**Pull request by dannyxx001**
@kennynaoh please help me check this pull request, thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/Pathgather/please-wait
 * Official website (optional, not the repository): http://pathgather.github.io/please-wait/
 * NPM package url (optional): https://www.npmjs.com/package/please-wait
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 1317
   - Count of watchers: 41
   - Count of forks: 79
 * NPM download stats (optional):
   - Downloads in the last day: 6
   - Downloads in the last week: 76
   - Downloads in the last month: 307

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7537, cc @jhdavids8

### CODE REVIEW

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is ok
Please help me check again
Thanks

**Comment by PeterDaveHello** [comment]
@kennynaoh We don't use **check**, try to use **review** as the keyword instead of **check**.

**Comment by PeterDaveHello** [comment]
@dannyxx001 @kennynaoh the css file is not minified, any reason?

**Comment by dannyxx001** [comment]
Sorry, I forgot that the css file also needs to be minify, and I have updated it.

**Comment by PeterDaveHello** [comment]
@dannyxx001 you should mention the issue you are working for in the head of the first comment.

**Pull request merged**
