### PR TITLE
New - Add LightService 9.1.0

### PR DESCRIPTION
**Pull request by contactsamie**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
Git repository (required):https://github.com/contactsamie/LightService
Official website (optional, not the repository):
NPM package url (optional): https://www.npmjs.com/package/lightservice
GitHub / Bitbucket popularity (required):
Count of stars:1
Count of watchers:1
Count of folks:1
NPM download stats (optional):
Downloads in the last day:18
Downloads in the last week:1064
Downloads in the last month:1695

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
npm test passed.

@contactsamie our git auto-updater needs the tags on git repos so that it can determine the versions, and I saw your lib has npm package, which will be recommended, not sure if you would like to use it?

I found that there are more files than you committed in npm package's cdn folder like this:
```
└── 9.1.0
    ├── lightservice.js
    ├── lightservice.min.js
    ├── lightservice-timemachine.js
    ├── lightservice-timemachine.min.js
    ├── visual2.lightservice.js
    ├── visual2.lightservice.min.js
    ├── visual.lightservice.js
    └── visual.lightservice.min.js
```

also saw those files in the `dist` folder, you sure about not hosting them on cdnjs?

actually I think we can just use the `dist` folder, what do you think?

**Comment by contactsamie** [comment]
yes we can use the dist folder, ill just need to update my build to put the package in there

**Comment by contactsamie** [comment]
yes ill love to have them all hosted

**Comment by contactsamie** [comment]
ill just take cdn folder off my build step

**Comment by contactsamie** [comment]
what do you mean by ' tags on git repos ' didnt get that part

**Comment by contactsamie** [comment]
@PeterDaveHello  for the auto updater

**Comment by PeterDaveHello** [comment]
@contactsamie 

> yes we can use the dist folder, ill just need to update my build to put the package in there

There is no need to put a pacakge.json there

> yes ill love to have them all hosted

So the rule can be `"**/*"` with `dist` as basePath

> what do you mean by ' tags on git repos ' didnt get that part

https://git-scm.com/book/en/Git-Basics-Tagging, but I prefer using npm auto-update, it'll be easier

BTW I can do the commit for you if it's wasting your time.

**Comment by contactsamie** [comment]
@PeterDaveHello  Nice. I find the tagging thing interesting for some reason. I tried that.
Yes lets do a commit right away! Many thanks

**Comment by PeterDaveHello** [comment]
hmmm ... so will you go to send a new PR? or you want me to do that?

**Comment by contactsamie** [comment]
yes, I'll do that

**Comment by PeterDaveHello** [comment]
Okay.

**Comment by PeterDaveHello** [comment]
#7057

**Pull request closed without merging**
