### PR TITLE
[New] add qoopido.nucleus w/ single package.json and npm auto-update

### PR DESCRIPTION
**Pull request by dlueth**
Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/dlueth/qoopido.nucleus
 * Official website (optional, not the repository): https://nucleus.qoopido.com/
 * NPM package url (optional): https://www.npmjs.com/package/qoopido.nucleus
 * License and its reference: MIT (https://raw.githubusercontent.com/dlueth/qoopido.nucleus/master/LICENSE)
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 2
   - Count of watchers: 1
   - Count of forks: 0
 * NPM download stats (optional):
   - Downloads in the last day: 0
   - Downloads in the last week: 16
   - Downloads in the last month: 37

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
Hi @dlueth  ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue,

**Comment by dlueth** [comment]
@pvnr0082t The nature of this lib is to get loaded via CDN into a browser. So, sadly enough, it will not reach very high download numbers on npm I am afraid. Though it has >100k requests per month via jsdelivr :(

**Comment by dlueth** [comment]
In addition, it is the direct successor of qoopido.js which is already part of cdnjs ;)

**Comment by pvnr0082t** [comment]
Can this lib be hosted? @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Yeah I think we can host this.

**Comment by dlueth** [comment]
@pvnr0082t @PeterDaveHello thanks guys, greatly appreciated!

**Comment by PeterDaveHello** [comment]
@dlueth you're welcome

**Comment by dlueth** [comment]
@pvnr0082t @PeterDaveHello anything else I need to do? ;)

**Comment by PeterDaveHello** [comment]
@dlueth Nope, sorry for the late reply, get this merged now

**Pull request merged**
