### PR TITLE
[New] Add simplePagination.js w/ git auto-update

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #6527

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/flaviusmatis/simplePagination.js
 * Official website (optional, not the repository): https://flaviusmatis.github.io/simplePagination.js/
 * License and its reference: [MIT](https://github.com/flaviusmatis/simplePagination.js/blob/master/LICENSE.txt)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 60
   - Count of stars: 646
   - Count of forks: 310

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by extend1994** [comment]
The details about commit logs are in second commit.

**Comment by extend1994** [comment]
Please don't review this PR for now. I found something wrong with my commits. Thanks.

**Comment by extend1994** [comment]
@PeterDaveHello You said 
> There is a v0.0.3 commit bumped its version, flaviusmatis/simplePagination.js@7146811.
We can take it as the snapshot of v0.0.3 and manually add it.

in https://github.com/cdnjs/cdnjs/issues/6527#issuecomment-172314071.
But I noticed that according to versions changing in `jquery.simplePagination.js` , like https://github.com/flaviusmatis/simplePagination.js/commit/23c0f4a83c4eed20db142d9d21c56d98c8d66fec#diff-d69a9b4d862991fba2e742d259d72c3cL2. I know we should recognize version using package.json or bower.json. But I noticed bower.json was not created by the author. Take the commit https://github.com/flaviusmatis/simplePagination.js/commit/cc7e8edd0abed2192f85ac558d844590dc74be99#diff-0a08a7565aba4405282251491979bb6b bower.json first created to see the content of https://github.com/flaviusmatis/simplePagination.js/blob/cc7e8edd0abed2192f85ac558d844590dc74be99/jquery.simplePagination.js. the version displayed in `jquery.simplePagination.js` had been `v1.6`. The version changes in `jquery.simplePagination.js` were all made by the author. So I am thinking that can I add v1.0.0 ~ v1.6? Thank you.

**Comment by PeterDaveHello** [comment]
Looks good to use the result of tracing the version number in the js file 👍

**Comment by extend1994** [comment]
@cdnjs/intern3 Now it's ready. Please help me review this PR, thanks.

**Comment by sufuf3** [comment]
Not sure that can we just use `flaviusmatis/simplePagination.js@c86400c` or `flaviusmatis/simplePagination.js@c86400ce08e8fb925871deb9d27effb371a36fdf` ... to replace https://github.com/flaviusmatis/simplePagination.js/commit/c86400ce08e8fb925871deb9d27effb371a36fdf

IMO, the commit message will be more readable in local.
And both of them can show the link in GitHub website.

What do you think?
Thank you.

**Comment by extend1994** [comment]
I think the current one is fine. Like https://github.com/cdnjs/cdnjs/pull/8683#pullrequestreview-64681823. Thanks.

**Comment by sufuf3** [comment]
OK!
How about 
```
Add v1.0.0 ~ v1.5 of the lib from GitHub by tracing commit logs because
the author didn't create tags for them. cc #6527, #11170
```
to 
```
Add v1.0.0 ~ v1.5 of the lib from GitHub by tracing commit logs because
the author didn't create **git** tags for them. cc #6527, #11170
```
as this mention https://github.com/cdnjs/cdnjs/pull/11436#issuecomment-331544485 ?

**Comment by extend1994** [comment]
@sufuf3 I updated it, please review it, thanks for suggestion.

**Comment by extend1994** [comment]
ping @cdnjs/library-reviewer @cdnjs/active-contributor

**Comment by maruilian11** [comment]
I think you minify the file with Peter's tool, right? Please also mention it in the commit msg. Thanks.

**Comment by extend1994** [comment]
@maruilian11 Thanks. I just updated it. Please help review it.

**Comment by PeterDaveHello** [comment]
@sufuf3 ?

**Pull request merged**
