### PR TITLE
[new] add reconnecting-websocket

### PR DESCRIPTION
**Pull request by dsri**
From https://github.com/joewalnes/reconnecting-websocket

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Looks okay now, but I notice that its version is 0.0.0, a little bit strange, which can not be recognize the real version, do you know the guys working on this lib? we may need their help!

**Comment by dsri** [comment]
Version is updated to 1.0.0 in source repo and in this PR.

**Comment by PeterDaveHello** [comment]
I think you can check the build log first, the name field should be the same as its folder name.

**Comment by dsri** [comment]
Was based on source repo package file. Updated now

**Comment by dsri** [comment]
Fixed. Thanks

**Comment by PeterDaveHello** [comment]
Thanks!

**Comment by PeterDaveHello** [comment]
BTW, if you want this lib can be auto-updated, there should be tags in their repo, maybe you can open an issue their to ask for this reason.

**Comment by dsri** [comment]
Thanks - will look into that. You know how long until this gets updated on the public site?

**Comment by PeterDaveHello** [comment]
Normally, in 30 mins.

**Comment by dsri** [comment]
It's there now, but just a heads up it did take a couple of days.

**Comment by PeterDaveHello** [comment]
@dsri We had problem then, fixed now.

**Pull request merged**
