### PR TITLE
[new] [author] Add leaflet-geocoder-mapzen@1.3.0

### PR DESCRIPTION
**Pull request by louh**
Hi, I'd like to add the [leaflet-mapzen-geocoder](https://github.com/mapzen/leaflet-geocoder/) library to cdnjs.

Repository: https://github.com/mapzen/leaflet-geocoder/
Website: https://mapzen.com/projects/search/
Demo: https://mapzen.github.io/leaflet-geocoder/
npm package: https://www.npmjs.com/package/leaflet-geocoder-mapzen/

The package is gaining popularity rapidly and it is a very useful plugin for [Leaflet](http://leafletjs.com/) and [Mapzen Search](https://mapzen.com/projects/search/). It was recently renamed and moved to the Mapzen organization so some of the download stats are lower than the reality, but this allows us to support and promote the library better in the long term. We would love to have this hosted by cdnjs since we use this library as part of our [tutorials](https://mapzen.com/documentation/search/add-search-to-a-map/) that we use in our workshops.

Thanks!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Seems there is no minified css/js on the upstream, will them been added in future? Thanks.

**Comment by louh** [comment]
At some point, yes, we should do that. We're currently not building files into the `dist/` folder but that can change in the future. Does cdnjs automatically minify files or no?

**Comment by PeterDaveHello** [comment]
@louh nope, I take care of the minification work, it'll be good to provide a official minified version, thanks.

**Comment by louh** [comment]
I just put in a prepublish script to minify files:
https://github.com/mapzen/leaflet-geocoder/commit/d03e9438f2ba10da9c155c737f6b3f79fc03ef9e

**Comment by PeterDaveHello** [comment]
:+1: Thanks you @louh

**Pull request merged**
