### PR TITLE
Add cloning tips

### PR DESCRIPTION
**Pull request by klausenbusk**
I'm not sure if this should be added and I'm not a native speaker (feel free to reword it).

### CODE REVIEW

**Comment by klausenbusk** [comment]
I'm not sure anyone notice PR in this repo, so: /cc @MattIPv4

**Comment by MattIPv4** [comment]
👋 As noted by the bot, the repo is now robot-only, so humans shouldn't ever need to be cloning it or submitting PRs really.

I think adding docs covering how to clone it may mislead contributors looking to add packages by implying that they should be cloning this repo to get involved. Fwiw, we used to have quite in-depth docs here on sparse checkout + some scripts to automate creating a sparse checkout config, but we opted to remove those when we made this repo robot-only.

@xtuc what do you think, should we add cloning docs?

**Comment by xtuc** [comment]
@klausenbusk could you please tell us the motiviation to clone the repo? (I remember that you mentioned in an issue but forgot, sorry). We don't want people to clone the repo because they are going to run into issues.

**Comment by klausenbusk** [comment]
> @klausenbusk could you please tell us the motiviation to clone the repo? (I remember that you mentioned in an issue but forgot, sorry). We don't want people to clone the repo because they are going to run into issues.

I'm trying to run the autoupdater in GitHub Actions (https://github.com/cdnjs/bot-ansible/issues/11), and I need a fast and effective to clone the repo, but @MattIPv4 made a fair point, it is probably more harm than good.

**Comment by xtuc** [comment]
We have a slack, I can help you getting running. Can you please send me or email?

**Comment by klausenbusk** [comment]
> We have a slack, I can help you getting running. Can you please send me or email?

Feel free to add me: kristian@klausen.dk

**Pull request closed without merging**
