### PR TITLE
add bootstrap.native v1.0.2 with npm auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/thednp/bootstrap.native
**Watch 13
  Star 166
 Fork 24**
@Amomo could u help me check this PR for #8256 ? thank you!
**only minifill in `/assets` is not on cdnjs, i have sent PR to add it** https://github.com/cdnjs/cdnjs/pull/8549

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR 
 * [x] The lib has notable popularity.
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry 
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update) 
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
There are only 6 releases on npm but 11 on GitHub, for this case, next time, please manually add all the versions. Since there is CDN usage in upstream's readme, please also try to add CDNJS.

**Comment by PeterDaveHello** [comment]
Ping @maruilian11, any updates?

**Comment by maruilian11** [comment]
@PeterDaveHello the author has added cdnjs in README.md.
i will add other version on github manually.

**Comment by thednp** [comment]
Hey there. I have a question, does your script also push new releases to npm as well?

I'm a n00b with npm stuff, so I need to know.

**Comment by PeterDaveHello** [comment]
@thednp we pull updates from npm, so you need to push new versions to npm.

**Comment by thednp** [comment]
I did that yesterday.

**Comment by PeterDaveHello** [comment]
@thednp So as you can see there is it https://cdnjs.com/libraries/bootstrap.native/1.0.3

**Comment by thednp** [comment]
Yes, thank you.

**Comment by PeterDaveHello** [comment]
@thednp no problems

**Pull request merged**
