### PR TITLE
Add angular-mapboxgl-directive@0.14.0 w/ npm autoupdate

### LINKED ISSUE #9254: [Request] Add angular-mapboxgl-directive
**Library name:** angular-mapboxgl-directive
**Git repository url:** https://github.com/Naimikan/angular-mapboxgl-directive
**npm package url(optional):** https://www.npmjs.com/package/angular-mapboxgl-directive
**License(s):** MIT
**Official homepage:** https://naimikan.github.io/angular-mapboxgl-directive/#/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by extend1994**
PR for #9254 
@PeterDaveHello Please help me review this pull request, thank you!

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/Naimikan/angular-mapboxgl-directive
 * Official website (optional, not the repository): https://naimikan.github.io/angular-mapboxgl-directive/#/
 * NPM package url (optional): https://www.npmjs.com/package/angular-mapboxgl-directive
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 2
   - Count of watchers: 2
   - Count of forks: 0
 * NPM download stats (optional):
   - Downloads in the last day: 1
   - Downloads in the last week: 4
   - Downloads in the last month: 730

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9254, cc @Naimikan

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@extend1994 the css file needs to be minified, take a look at [web-minify-helper](https://github.com/PeterDaveHello/web-minify-helper) if you don't know how to minify it.

**Comment by extend1994** [comment]
@PeterDaveHello I have minified the css file with web-minify-helper, thanks for your reminder!

**Comment by PeterDaveHello** [comment]
@extend1994 could you please use the minify helper with --no-map option to prevent the generation of the map file? Looks like it did generate it but you didn't add it, in this case we actually do not need it, just don't generate it, the result of minified css will be a little bit different(you can compare them by yourself)

**Comment by extend1994** [comment]
@PeterDaveHello Please help me review this pull request, thank you!

**Pull request merged**
