### PR TITLE
add enllax.js@1.1.0 w/ git autoupdate

### LINKED ISSUE #8450: [Request] Add Enllax.js
**Library name:** Enllax.js
**Git repository url:** https://github.com/mmkjony/enllax.js
**License(s):** MIT (https://github.com/mmkjony/enllax.js/blob/master/LICENSE)
**Official homepage:** http://mmkjony.github.io/enllax.js/

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35762827-request-add-enllax-js?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8450 
@kennynaoh Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/mmkjony/enllax.js
- Official website (optional, not the repository): https://mmkjony.github.io/enllax.js/
- NPM package url (optional):
- GitHub / Bitbucket popularity (required):
  - Count of stars: 98
  - Count of watchers: 12
  - Count of forks: 35
- NPM download stats (optional):
  - Downloads in the last day:
  - Downloads in the last week:
  - Downloads in the last month:
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [ ] The lib has notable popularity
  - [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [ ] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

close #8450, cc @mmkjony

### CODE REVIEW

**Comment by kennynaoh** [comment]
@pvnr0082t 
Sorry for late review.
Please rebase to the latest master branch.
Thanks!

**Comment by pvnr0082t** [comment]
@kennynaoh I have rebased it. Please help me review again, thank you.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Comment by PeterDaveHello** [comment]
They now have a dist folder, what about manually commit the old versions and use `dist` in auto-update config for future release? Maybe you can confirm with its author.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello there is no response since 25 Jul 2016.
So do we really need to add the files under `dist`?
Or just following the git tag?
Or, use two basePath in auto-update config?

Not sure which one is better, could you give us some suggestions?

Thank you.

**Comment by PeterDaveHello** [comment]
@pvnr0082t can you try to manually add them all with the new auto-update config?

**Comment by sufuf3** [comment]
@pvnr0082t 
Would you mind working on this and help improve this PR?

This will be a great work.
Many thanks.

**Comment by PeterDaveHello** [comment]
@sufuf3 you can create a new PR.

**Pull request closed without merging**
