### PR TITLE
[author] jquery.scregal v1.1

### PR DESCRIPTION
**Pull request by kunass2**
with good auto-update

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
What's the reason why to change it's main file jquery.scregal.min.js to jquery.scregal.js? minified version is preferred.

**Comment by PeterDaveHello** [comment]
And I have another question, don't you need its css file?

**Comment by kunass2** [comment]
Ok, i see. I know that about minified version. I change it by next pull request. And I add css file. I think i change the structure by adding two directories: css/ and js/. Is it good? Can i upload img/ with a very small images?

**Comment by PeterDaveHello** [comment]
Yes, of course you can.

**Comment by kunass2** [comment]
I have a question. Why every time when i fork cdnjs repository to my account, and then clone it to my computer, there is some changes ready to commot them. Why they always appear, although i changed nothing? Because of this, I cannot rebase my local repo on yours current version of cdnjs. Hence i cannot create a correct pull request. The file that I keep seeing changed is from Sortable library. Package json deleted, and created. Why?

**Comment by PeterDaveHello** [comment]
#3650

**Comment by kunass2** [comment]
So far, it is not resolved:-) ok, we still waiting...

**Pull request merged**
