### PR TITLE
Add git autoupdate config in paypaljsbuttons

### PR DESCRIPTION
**Pull request by LeaYeh**

### CODE REVIEW

**Comment by LeaYeh** [comment]
hey @Piicksarn ,
could you help me checking the commit abut git autoupdate config in paypaljsbuttons?

**Comment by LeaYeh** [comment]
done.
https://github.com/paypal/JavaScriptButtons/issues/135

**Comment by Piicksarn** [comment]
@PeterDaveHello would you take a look for this pull request?

**Comment by PeterDaveHello** [comment]
I think you should ask for adding tags for each releases, not for v1.0.2 ... Seems there is already v2.0.1, what's the reason why to add v1.0.2 instead of v2.0.1?

**Comment by PeterDaveHello** [comment]
Any updates?

**Comment by Piicksarn** [comment]
I think I gave a bad advice, so I create a new issue about asking for the tags to the versions.
and the issue link shown below:
https://github.com/paypal/JavaScriptButtons/issues/137

**Pull request closed without merging**
