### PR TITLE
Correct build of shaka-player v1.6.5

### PR DESCRIPTION
**Pull request by joeyparrish**
Somehow the auto-update bot pulled Shaka Player v2.0.0-beta as v1.6.5.
This corrects the v1.6.5 builds.

Reported in google/shaka-player#373

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@joeyparrish Thanks.
@terinjokes would you please help us purge the cache of shaka-player v1.6.5?

**Comment by joeyparrish** [comment]
Hi @PeterDaveHello, @terinjokes, any update on purging the cache?

**Comment by PeterDaveHello** [comment]
@joeyparrish so that we don't have the permission to purge the cache directly, I'll ping Cloudflare again ...

**Comment by joeyparrish** [comment]
Thank you!

**Comment by joeyparrish** [comment]
Any update?  Was Cloudflare able to purge the cache?

**Comment by PeterDaveHello** [comment]
So sorry about that ... @thomasdavis @ryankirkman please take a look at this issue, thanks.

**Comment by terinjokes** [comment]
My apologies. I never got this thread in my GitHub notifications.

**Comment by PeterDaveHello** [comment]
@terinjokes I can email you next time if it's better for you, thanks.

**Comment by terinjokes** [comment]
@PeterDaveHello that would be great.

**Comment by PeterDaveHello** [comment]
@terinjokes Okay, I'll do it next time, thanks!

**Comment by joeyparrish** [comment]
Since #8234 is closed, does that mean the cache has been purged?

**Pull request merged**
