### PR TITLE
Add lobipanel w/ git auto-update via single package.json

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #10738

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/arboshiki/lobipanel
 * Official website (optional, not the repository): https://lobianijs.com/site/lobipanel
 * License and its reference: [MIT](https://github.com/arboshiki/lobipanel/blob/master/LICENSE)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 14
   - Count of stars: 107
   - Count of forks: 31

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by extend1994** [comment]
Accidentally close again...Reopen it now

**Comment by extend1994** [comment]
@cdnjs/intern3 Please help me review this pull request, thank you.

**Comment by extend1994** [comment]
@pvnr0082t I modified the commit message, please help me review it, thank you.

**Comment by extend1994** [comment]
@pvnr0082t I revised the commit message, please help me review it, thank you!

**Comment by maruilian11** [comment]
It's better to use a sentence in commit msg, not just follow the first line.

**Comment by extend1994** [comment]
@maruilian11 Do you mean change from 
> Add lobipanel w/ git auto-update
via single package.json. close #10738, cc @arboshiki

to
> Add lobipanel w/ git auto-update
Add lobipanel w/ git auto-update via single package.json. close #10738, cc @arboshiki

?

**Comment by maruilian11** [comment]
it duplicated too much, just use `Add it via single package.json.`

**Comment by extend1994** [comment]
@maruilian11 I modified it, please help me review it, thank you.

**Comment by maruilian11** [comment]
@extend1994 I just confirm with Peter that It doesn't matter if the last word of the first line over the 50th character. So could you please modify the message to 
```
Add lobipanel w/ git auto-update via single package.json.

close #10738, cc @arboshiki
```

thanks.

**Comment by PeterDaveHello** [comment]
@maruilian11 I'm not saying the last word doesn't matter ...

**Comment by extend1994** [comment]
@maruilian11 I revised the commit message, please help me review it, thank you!

**Comment by maruilian11** [comment]
Ok, I didn't explain it well. Quote it directly. 
>We can accept that you don't have another whole word after 50th char, the last word could be acceptable.

by Peter

**Comment by maruilian11** [comment]
@cdnjs/intern2  Please help me make the double check, thanks.

**Pull request merged**
