### PR TITLE
add mockstate@0.0.7 w/ npm auto-update

### LINKED ISSUE #9323: [Request] Add mockstate
*_Library name: Mockstate
*_Git repository url: https://github.com/luisvinicius167/mockstate
*_npm package url(optional): https://www.npmjs.com/package/mockstate
*_License(s): MIT
*_Official homepage: https://github.com/luisvinicius167/mockstate
*_Wanna say something? A centralized state management for Javascript applications, made easy.

### PR DESCRIPTION
**Pull request by nolsherry**
Pull request for issue: #9323
Related issue(s): #7770

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/luisvinicius167/mockstate
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/mockstate
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 175
   - Count of watchers: 13
   - Count of forks: 10
 * NPM download stats (optional):
   - Downloads in the last day: 2
   - Downloads in the last week: 41
   - Downloads in the last month: 129

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [X] This lib was not found on cdnjs repo
 * [X] No already exist / duplicated issue and PR
 * [X] The lib has notable popularity
   * [X] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [X] Has valid tags for each versions (for git auto-update)
 * [X] Auto-update setup
 * [X] Auto-update target/source is valid.
 * [X] Auto-update filemap is correct.

# Git commit checklist
 * [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X] The parent of the commit(s) in the PR is not old than 3 days.
 * [X] Pull request is sending from a non-master branch with meaningful name.
 * [X] Separate unrelated changes into different commits.
 * [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [X] Close corresponding issue in commit message
 * [X] Mention related issue(s), people in commit message, comment.

close #9323, cc @luisvinicius167

### CODE REVIEW

**Comment by nolsherry** [comment]
@kennynaoh please help me review this PR, thanks!

**Comment by kennynaoh** [comment]
@nolsherry There is exist library on CDNJS but different library name with same git repo. Could you make sure with author whether the author just change the library name from riotux to mockstate? If so, you can just update the auto-update part in package.json to update the latest version. Thanks!

**Comment by nolsherry** [comment]
@kennynaoh , I have rebased this branch, please help me review this PR, thanks!

**Comment by PeterDaveHello** [comment]
It's been so long, I'll rebase it.

**Pull request merged**
