### PR TITLE
add license of localStorage, cc #9248

### PR DESCRIPTION
**Pull request by qwe19272375**
https://github.com/mortzdk/localStorage/blob/master/LICENSE

### CODE REVIEW

**Comment by qwe19272375** [comment]
@nolsherry

**Comment by nolsherry** [comment]
LGTM
ping @cdnjs/intern2

**Comment by kennynaoh** [comment]
@qwe19272375 
Please also mention the issue number in commit message next time, like this PR title, and use more meaningful branch name, thanks!

**Comment by kennynaoh** [comment]
LGTM

**Comment by pvnr0082t** [comment]
LGTM
BTW, @qwe19272375 didn't create a branch... @kennynaoh

**Comment by PeterDaveHello** [comment]
@pvnr0082t Then... not good enough to be merged.

**Comment by qwe19272375** [comment]
@pvnr0082t I'll make a new PR to make changes on a new branch.
Thanks!

**Pull request closed without merging**
