### PR TITLE
[new] Add oboe.js v2.1.2 with git auto-update, close #5241

### LINKED ISSUE #5241: [Request] Add _library_name_OboeJS
**Library name:OboeJS** 
**Git repository url: https://github.com/jimhigson/oboe.js**
**npm package url(optional): https://www.npmjs.com/package/oboe** 
**Official homepage: http://oboejs.com/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by Piicksarn**
@Amomo would you mind to check the pr for me?
the pr is for adding a new lib: oboe.js
and the git repository url is shown below:
https://github.com/jimhigson/oboe.js

### CODE REVIEW

**Comment by Piicksarn** [comment]
@Amomo would you mind to check the pr for me?
the pr is for adding a new lib: oboe.js
and the git repository url is shown below:
https://github.com/jimhigson/oboe.js

I have it rebased to master~

**Comment by Amomo** [comment]
@Piicksarn Sorry for the delay.
I found that `oboe-node.js` is a node module, and it is partially duplicated with `oboe-browser.js`.
I think we could only collect `oboe-browser.js` and its minified file.
@PeterDaveHello What do you think?

**Comment by PeterDaveHello** [comment]
Can remove the node version.

**Comment by Piicksarn** [comment]
@Amomo, I have it corrected and rebased to master.
I need your help to checkout the commit~
Thank you!

**Comment by Amomo** [comment]
@Piicksarn Because we don't collect the node version, I think you could use `oboe-browser*.js` in auto-update field.

**Comment by Piicksarn** [comment]
thank you @Amomo ! i will be careful next time!
and I have it corrected!

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine. Could you take a look? Thank you~

**Pull request merged**
