### PR TITLE
test nodejs v0.12

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Test nodejs v0.12 on circle-ci

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I'm considering the timing to migrate on v0.12. 
Any suggestions will be very welcome.

cc @cdnjs/team-cdnjs @cdnjs/intern

**Comment by ryankirkman** [comment]
Yep, let's migrate. node `0.10` is old news. Hopefully we get some performance increases :)

**Comment by PeterDaveHello** [comment]
@cdnjs/intern please migrate your nodejs to v0.12 and reply here to let me know you're done.

**Comment by Piicksarn** [comment]
@PeterDaveHello, i have done.

**Comment by maruilian11** [comment]
done

**Comment by Amomo** [comment]
already v0.12~ 😁

**Comment by PeterDaveHello** [comment]
Where is @LeaYeh ?

**Comment by PeterDaveHello** [comment]
Ping @LeaYeh, again.

**Comment by PeterDaveHello** [comment]
Now bumping to v0.12.7.

**Comment by Amomo** [comment]
Finish updating~ v0.12.7 now.

**Pull request closed without merging**
