### PR TITLE
Add bagjs v2.0.2 with npm auto-update config

### LINKED ISSUE #7933: [Request] Add bag.js
**Library name:** bag.js
**Git repository url:** https://github.com/nodeca/bag.js

### PR DESCRIPTION
**Pull request by x09326**
PR for #7933 
@kennynaoh please help me review it, thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/nodeca/bag.js
 * Official website (optional, not the repository):
 * NPM package url (optional):https://www.npmjs.com/package/bagjs
 * GitHub / Bitbucket popularity (required):
   - Count of stars:52
   - Count of watchers:9
   - Count of forks:8
 * NPM download stats (optional):
   - Downloads in the last day:10
   - Downloads in the last week:136
   - Downloads in the last month:497

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7933, cc @nodeca

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Ping @kennynaoh

**Comment by kennynaoh** [comment]
@x09326 
Because I am late for reviewing, there are lots of commit behind master branch.
Sorry about that.
Maybe you could rebase to the latest master branch.
Thanks!

**Comment by x09326** [comment]
@kennynaoh 
I have rebased it, please help me review it again, thanks.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Pull request merged**
