### PR TITLE
[new] Added medium-editor@4.10.1

### PR DESCRIPTION
**Pull request by IonicaBizau**
:star: [**medium-editor**](https://github.com/daviferreira/medium-editor) on cdn! :star2: 

Solves https://github.com/daviferreira/medium-editor/issues/272. :smile: :fireworks:  Thanks! :cake:

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Filename points to `css` make no sense, should change it.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Addressed in https://github.com/IonicaBizauKitchen/cdnjs/commit/a97e38f65ca0d99fac094c495c0ca01126a3d0b5. Hopefully it's fine. :four_leaf_clover:

**Comment by IonicaBizau** [comment]
@PeterDaveHello When will be the library available on the cdnjs website? For example, *svg.draggy.js* was merged yesterday but it's still not available. Is there a cron job that runs daily? How does that work?

**Comment by PeterDaveHello** [comment]
Already on it, see https://cdnjs.com/libraries/svg.draggy.js, I think the search index process was missed due to we were fixing some problem yesterday, should be available with 15~30 mins, please try again later!

**Comment by IonicaBizau** [comment]
@PeterDaveHello Got it! But what is the normal behavior? Is there a cron job which adds the libraries? If so, when does it run?

**Comment by PeterDaveHello** [comment]
Yes, cronjob runs every 30 mins.

**Comment by IonicaBizau** [comment]
Ah, cool! :+1: Thanks!

**Pull request merged**
