### PR TITLE
update license info of libraries #2

### PR DESCRIPTION
**Pull request by Amomo**
Hi @Piicksarn 

For #5544, I have update the license info of these 11 libraries.
- datatables-tabletools　[ref](https://github.com/DataTables/TableTools/blob/master/License.txt)
- ekko-lightbox　[ref](https://github.com/ashleydw/lightbox/blob/master/LICENSE#L1)
- embedly-jquery　[ref](https://github.com/embedly/embedly-jquery/blob/master/LICENSE)
- emojione　[ref](https://github.com/Ranks/emojione/blob/master/LICENSE.md)
- equalize.js　[ref](https://github.com/tsvensen/equalize.js#legal)
- evil.js　[ref](https://github.com/kitcambridge/evil.js#license)
- extjs　[ref](https://www.sencha.com/legal/GPL/)
- geoext　[ref](http://trac.geoext.org/wiki/license#TheGeoExtLicense)
- intercom.js 　[ref](https://github.com/diy/intercom.js#license)
- jQuery.dotdotdot　[ref](https://github.com/BeSite/jQuery.dotdotdot/blob/master/LICENSE.txt#L1)
- jo　[ref](https://github.com/davebalmer/jo/blob/ec767af487b8653778c36168c7b3a5f478753cc5/LICENSE.mdown#license)

Among of them, "evil.js" choose to release into `"public domain"`.
So I note their license as `"Unlicense"`, according to this [doc](http://unlicense.org/).

Would you mind checking this PR for me? Thank you~ :-D

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
As I said in #6576's comment, I need you to re-check all the license again first.

**Comment by PeterDaveHello** [comment]
Close due to no response.

**Comment by PeterDaveHello** [comment]
Ping @Piicksarn

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello 
I think some license of lib need to be checked.
But as your mention `As I said in #6576's comment, I need you to re-check all the license again first.` 
So before this PR, the contributor need to re-check license first.
But there is no response from the contributor since 19 Mar.

So what can we do for this PR?

Thank you.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern3 try to pick those can be practice for the next intern please.

**Pull request closed without merging**
