### PR TITLE
[author] Update package.json

### PR DESCRIPTION
**Pull request by dlueth**
- add git autoupdate settings
- remove npm autoupdate settings

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Should be `Update package.json of qoopido.js` next time :+1:

**Comment by PeterDaveHello** [comment]
@dlueth, after this update, we'll grab these files:
> asset.js  emitter.js   pool.js   renderer.js  transport.js  worker.js
> base.js   particle.js  proxy.js  support.js   url.js

Which one is the main file?

**Comment by dlueth** [comment]
@PeterDaveHello 
The main file is ```base.js```. Anything wrong about ```"filename": "base.js",```? Does this path need to be absolute in the relation to the original repositories directory structure?

Beside that, for NPM autoupdate files used to be fetched recursively which seems not to be the case for git autoupdate when using 

```
"files": [
      "*.js"
    ]
```

Do I need to change that to

```
"files": [
      "**/*.js"
    ]
```

to recursively fetch all JS files?

**Comment by PeterDaveHello** [comment]
Just need to confirm the filename.
`**/` prefix will fetch recursively.

**Comment by dlueth** [comment]
OK, will start a new pull request than - spent some time yesterday trying to figure out how to properly squash my commits but did not find a way. So this will (sorry) be a new pull request :(

Any tips how to easily accomplish that perhaps?

**Comment by PeterDaveHello** [comment]
`git rebase`

**Comment by dlueth** [comment]
Please close this pull request - problem to squash still persists on my side :(

**Comment by PeterDaveHello** [comment]
Already closed by merge.

**Comment by dlueth** [comment]
Thanks for changing the files part :+1:

**Comment by PeterDaveHello** [comment]
np

**Pull request merged**
