### PR TITLE
[Author] Add jcanvas@20.0.0 w/ npm auto-update and update package.json

### PR DESCRIPTION
**Pull request by caleb531**
Hi,

My library, jcanvas, is already hosted on jcanvas (at v16.7.3). However, I recently updated to v20.0.0, which the bot did not catch. Therefore, I am submitting this PR to update the package.

# Profile of the lib
 * Name: jcanvas
 * Git repository (required): https://github.com/caleb531/jcanvas
 * Official website (optional, not the repository): https://projects.calebevans.me/jcanvas/
 * NPM package url (optional): https://www.npmjs.com/package/jcanvas
 * License and its reference: MIT (https://github.com/caleb531/jcanvas/blob/master/LICENSE.txt)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 39
   - Count of stars: 471
   - Count of forks: 150

# Essential checklist
 * [X] I'm the author of this library

# Auto-update checklist
 * [X] Has valid tags for each versions (for git auto-update)
 * [X] Auto-update setup
 * [X] Auto-update target/source is valid.
 * [X] Auto-update filemap is correct.

# Git commit checklist
 * [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X] The parent of the commit(s) in the PR is not old than 3 days.
 * [X] Pull request is sending from a non-master branch with meaningful name.
 * [X] Separate unrelated changes into different commits.
 * [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [X] Close corresponding issue in commit message
 * [X] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by caleb531** [comment]
@dakshshah96 *facepalm* I couldn't sworn I published v20 on npm already, but apparently not. I've published it just now, so maybe the bot will catch it this time (as it has in the past). Also, the library information you requested has been added above.

**Comment by caleb531** [comment]
> Add all files for v20.0.0 to ajax/libs/jcanvas/20.0.0/ instead of putting everything into dist. The location of package.json is correct.

Done, with `basePath` and `files` updated as you suggested.

> Once you've made the changes, please squash all your commits and use the following commit message:

I believe GitHub allows you to squash these commits when you merge the PR ([see the post here](https://github.com/blog/2141-squash-your-commits)). I think that would be much better than squashing the commits and force pushing on my end.

**Comment by Gianfranco97** [comment]
@caleb531 Una pregunta, quieres que vea una manera de hacerlo en dos partes (primero pido el correo y luego la clave) o lo dejo de la manera como esta?

**Comment by sufuf3** [comment]
@caleb531 I really sorry for my late review.
I think the files are all fine.
But Would you squash the commit message?
Although you thought squashing these commits is OK when we merge this PR.
But we still want every commit always pass the `npm test`, and this is useful to us to maintain the every commit message.

If you think this is a little bit bother, I can help you squash the commit message.

- One is (with v20.0.0 files and the updating `filename, version , npmFileMap` od package.json)
```
Add jcanvas@20.0.0 w/ npm auto-update
```
- Another is 
```
Update author, homepage of jcanvas
```

Thank you for your great work and contribution.

**Comment by caleb531** [comment]
@sufuf3 @dakshshah96 Alright, I squashed my commits and force-pushed. However, the issue has been somehow closed, and I am unable to reopen.

**Comment by sufuf3** [comment]
I can't help reopen this PR.
@PeterDaveHello could you help reopen this PR?

**Comment by PeterDaveHello** [comment]
@caleb531 maybe just create another pull request if you can't reopen it, I can't either.

**Pull request closed without merging**
