### PR TITLE
add angular-cached-resource v1.4.2

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/goodeggs/angular-cached-resource
**Watch 19
  Star 209
 Fork 25**
@Amomo could u help me check this PR for #6819 ? thank you!
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update) 
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Why don't you use npm on this lib?

**Comment by maruilian11** [comment]
@PeterDaveHello because i can't find a appropriate file like `angular-cached-resource.js` on origin repo to be added. could you give me some advice？

**Comment by PeterDaveHello** [comment]
@maruilian11 you should say it first, don't wait for reviewer's asking. Now please rebase the branch for this PR with our latest master branch.

**Comment by maruilian11** [comment]
@PeterDaveHello done, i will said it next time.

**Comment by PeterDaveHello** [comment]
Thank you.

**Pull request merged**
