### PR TITLE
add asynquence v0.9.0 with npm auto-update config

### LINKED ISSUE #8059: [Request] Add asynquence
**Library name:** asynquence
**Git repository url:** https://github.com/getify/asynquence

### PR DESCRIPTION
**Pull request by nolsherry**
@pvnr0082t, please help me to review this pull request, thanks!
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/getify/asynquence
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/asynquence
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 706
   - Count of watchers: 47
   - Count of forks: 47
 * NPM download stats (optional):
   - Downloads in the last day: 151
   - Downloads in the last week: 556
   - Downloads in the last month: 1568

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [X] This lib was not found on cdnjs repo
 * [X] No already exist / duplicated issue and PR
 * [X] The lib has notable popularity
   * [X] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [X] More than 500 downloads stats per month on npm registry
 * [X] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [X] Has valid tags for each versions (for git auto-update)
 * [X] Auto-update setup
 * [X] Auto-update target/source is valid.
 * [X] Auto-update filemap is correct.

# Git commit checklist
 * [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X] The parent of the commit(s) in the PR is not old than 3 days.
 * [X] Pull request is sending from a non-master branch with meaningful name.
 * [X] Separate unrelated changes into different commits.
 * [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [X] Close corresponding issue in commit message
 * [X] Mention related issue(s), people in commit message, comment.

close #8059, cc @getify

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
What's the reason why the branch for this PR is not based on the latest master as 2 hours ago?

**Comment by PeterDaveHello** [comment]
A 5 hours ago PR is even based on a newer branch than yours. https://github.com/cdnjs/cdnjs/pull/8092

**Comment by pvnr0082t** [comment]
@nolsherry Please rebase on the latest master branch.

**Comment by nolsherry** [comment]
@pvnr0082t, I have rebased on the latest master branch.
Please help me to review this pull request, thanks!

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
@nolsherry mention the issue for this PR at the top of the comments next time.

**Pull request merged**
