### PR TITLE
p5.js: correct v1.0.0 files

### PR DESCRIPTION
**Pull request by jeremydouglass**
cdnjs (robocdn) accidentally cached p5.js v0.10.2 files as v1.0.0.
This commit corrects the files to the true files
from the official v1.0.0 release: https://github.com/processing/p5.js/releases/tag/1.0.0

Pull request for issue: #13912

## Profile of the lib

* Git repository (required):
https://github.com/processing/p5.js/

* Official website (optional, not the repository):
http://p5js.org/

* GitHub / Bitbucket popularity (required):
  * Used by: 5.2K
  * Count of watchers: 482
  * Count of stars: 13K
  * Count of forks: 2.1K

## Essential checklist

* [ ] I'm the author of this library
  (but I'm tagging author/core dev @lmccart to review and sign off)

* [x] The lib has notable popularity
  * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [x] More than 800 downloads stats per month on npm registry (>5000/week)
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)

## Git commit checklist

* [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [x] The parent of the commit(s) in the PR is not older than 3 days.
* [x] Pull request is sent from a non-master branch with a meaningful name.
* [x] Close corresponding issue in commit message

### CODE REVIEW

**Comment by jeremydouglass** [comment]
@lmccart please review and endorse this fix here

**Comment by lmccart** [comment]
@jeremydouglass this looks all good, thank you!

**Comment by MattIPv4** [comment]
As per #13912, we have the correct files from the NPM package at v1.0.0. It seems the NPM package has the incorrect files/headers. Not an issue with cdnjs.

**Comment by MattIPv4** [comment]
(It's worth also noting we'll never accept a PR that modifies existing versioned files, as this will change the hashes of these files and break any webpage using the existing files with SRI.)

**Comment by jeremydouglass** [comment]
@lmccart It seems like the header error in 1.0.0 is unfixable as far as cdnjs is concerned. I'd suggest making a p5.js 1.0.1 release for NPM (?), CDNJS will presumably then pick it up automatically with their robocdn bot (?).

Then we won't get confused forum questions about why people can't find 1.0.0 anywhere (they can, it is just mislabeled).

**Comment by lmccart** [comment]
@MattIPv4 that's correct, the NPM package has the wrong header. we were hoping to rectify this for the files loaded via CDNJS, but your policy makes sense. thanks for letting us know!

**Pull request closed without merging**
