### PR TITLE
Modifiy repository field in package.json of chaplin.

### PR DESCRIPTION
**Pull request by Piicksarn**
@Amomo, would you please check out the commit for me?
the git repository url is shown below:
https://github.com/chaplinjs/chaplin

### CODE REVIEW

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine.
Could you take a look? Thank you.

**Comment by PeterDaveHello** [comment]
Wrong.

**Comment by Piicksarn** [comment]
@Amomo, would you please checkout the pr again?
Thank you!

**Comment by Amomo** [comment]
@Piicksarn Sorry for checking this PR late.
I think your correction is fine, could you rebase the branch to match cdnjs's master branch?
Thank you!

**Comment by Piicksarn** [comment]
@Amomo, would you please have a look again?
thank you~~~:D

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine, could you take a look?

**Comment by PeterDaveHello** [comment]
Your commit message didn't match what you did in the commit.

**Comment by Piicksarn** [comment]
@Amomo, would you have a look again...QQ...

**Comment by Amomo** [comment]
maybe we can start with "fix"...but I think "correct" is fine
@PeterDaveHello I think this modification is ok, could you take a look?
Thank you~

**Comment by PeterDaveHello** [comment]
This is not a correct. Also wrong title.

**Comment by Amomo** [comment]
@Piicksarn could you also modify your PR's title?

**Comment by Piicksarn** [comment]
@Amomo, i have it corrected!
Sorry & Thank you!! QAQ....

**Comment by Amomo** [comment]
@PeterDaveHello could you take a look again?
Thank you~

**Comment by PeterDaveHello** [comment]
This is not a fix ...

**Comment by Piicksarn** [comment]
@Amomo, would you mind to check it again?
Thank you!! :smiley:

**Comment by PeterDaveHello** [comment]
> This is not a correct. Also wrong title.

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you have a look at the pr again?
Thank u!

**Comment by PeterDaveHello** [comment]
Thanks.

**Pull request merged**
