### PR TITLE
add vue-filter w/ npm auto-update

### PR DESCRIPTION
**Pull request by kennynaoh**
Pull request for issue: #9489
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.
@pvnr0082t @x09326 Please help me review this PR, thanks!
Manually add v0.1.0 from npm due to different file structure except v0.1.1
The author said v0.1.1 doesn't work correct https://github.com/wy-ei/vue-filter/issues/7#issuecomment-268971778

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/wy-ei/vue-filter
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/vue-filter
 * License and its reference: MIT https://github.com/wy-ei/vue-filter/blob/master/LICENSE
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 55
   - Count of watchers: 2
   - Count of forks: 3
 * NPM download stats (optional):
   - Downloads in the last day: 5
   - Downloads in the last week: 163
   - Downloads in the last month: 630

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
The second commit, can you just write you add v0.1.0? No need to say old version in the first line and mention its version later.

**Comment by kennynaoh** [comment]
@x09326 @pvnr0082t I have modified the second commit message. Please help me review it. Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Pull request merged**
