### PR TITLE
Add react-quill v0.2.2 with git autoupdate, close #5687.

### LINKED ISSUE #5687: [Request] react-quill
**Library name:** react-quill
**Git repository url:** https://github.com/zenoamaro/react-quill
**npm package url(optional):** https://www.npmjs.com/package/react-quill
**License(s):** MIT
**Official homepage:** https://zenoamaro.github.io/react-quill

You guys are really awesome, thanks! Hope you're currently having a great day!

### PR DESCRIPTION
**Pull request by Piicksarn**
**`git repository : `** https://github.com/zenoamaro/react-quill
**`Watch : 8 /  Star : 99 /  Fork : 26`**

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by Piicksarn** [comment]
@maruilian11, would you mind to have a look at the pr?
Thank you~

**Comment by maruilian11** [comment]
@Piicksarn i think you should add `dependencies`.

**Comment by PeterDaveHello** [comment]
That's not so required, but, okay, add it because official package.json has it.

**Comment by Piicksarn** [comment]
@maruilian11, i add it!
would you mind to checkout the pr again?
Thank you!

**Comment by maruilian11** [comment]
@PeterDaveHello  i think this PR is ok.

**Pull request merged**
