### PR TITLE
Add at.js v1.3.2 with git auto-update, close #5196.

### LINKED ISSUE #5196: [Request] Add At.js
**Library name:** At.js
**Git repository url:** https://github.com/ichord/At.js
**npm package url(optional):** 
**Official homepage:**
**Wanna say something? Leave message here:**

### PR DESCRIPTION
**Pull request by Piicksarn**
**`git repository : `** https://github.com/ichord/At.js/tree/v1.3.2
**`Watch : 143 /  Star : 3581 /  Fork : 398`**

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by Piicksarn** [comment]
@Amomo, would you mind to checkout the pr for me?
thank you! :smiley:

**Comment by Amomo** [comment]
@Piicksarn you miss the repo field, could you add it in package.json?

**Comment by Piicksarn** [comment]
@Amomo, thank you!!
i have it corrected!
would you mind to check it again?

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine, could you take a look?
Thank you~ :-D

**Pull request merged**
