### PR TITLE
Update jquery.hoverintent auto-update config & homepage

### LINKED ISSUE #11656: jquery.hoverIntent.js is not updated
I just worked with this library and I think that the file in cdnjs is not latest or updated, nevertheless the versions in the files are the same
You can compare this [file](https://github.com/briancherne/jquery-hoverIntent/blob/master/jquery.hoverIntent.js) with one stored at cdnjs

FYR

### PR DESCRIPTION
**Pull request by sashberd**
- Update auto-update config
- Update v1.9.0 because there is a minified file from v1.9.0 of lib

close #11656

Pull request for issue: #11656 
Related issue(s): #11785

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/briancherne/jquery-hoverIntent
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 41
   - Count of stars:696
   - Count of forks:188
 * NPM download stats (optional):
   - Downloads in the last day: 
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [X ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ X] This lib was not found on cdnjs repo
 * [ X] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ X] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ X] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [X ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [X ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X] The parent of the commit(s) in the PR is not old than 3 days.
 * [X ] Pull request is sending from a non-master branch with meaningful name.
 * [ X] Separate unrelated changes into different commits.
 * [X ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [X ] Close corresponding issue in commit message
 * [ X] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sashberd** [comment]
@sufuf3 
The comment was updated. The update cause me some problems, so I had to close and delete branch and repush everything to another branch with new comment
FYR

**Comment by PeterDaveHello** [comment]
@sashberd thanks for the updates.

**Comment by PeterDaveHello** [comment]
@sufuf3 @extend1994 What's the reason why we can touch the hosted files?

**Comment by sufuf3** [comment]
As https://github.com/cdnjs/cdnjs/commit/a168be04442c2d92af0cbea52f15d17bd8c776ac#commitcomment-24072925 said.
I found the origin rule just gets `jquery.hoverIntent.js`and generate the `jquery.hoverIntent.min.js` by CDNJS's minified tool.
It's cause the `jquery.hoverIntent.min.js`(v1.9.0) in CDNJS is different from upstream.
Most of the time CDNJS always get the right files from upstream, so I think maybe we need to let `jquery.hoverIntent.min.js` as the same as upstream.

That's what I think.

Thanks.

**Comment by PeterDaveHello** [comment]
@sufuf3 We don't touch the already hosted files, said many times. Unless the files were spoofed with integrity, security issues.

**Comment by sufuf3** [comment]
OK, I will keep in mind.
Then what can we do for `v1.9.0`?
Can we add another folder named `1.9.0-1` and add the files as the same as upstream?
Not sure that what can we do is better.
Could you give me some suggestions?

Thank you.

**Comment by PeterDaveHello** [comment]
@sufuf3 Why don't we just update the config?

**Comment by sashberd** [comment]
@sufuf3 So what the solution should be?

**Comment by extend1994** [comment]
I was a little confused that should the priority of files from the upstream be higher or lower than the files we have already host. So sorry for the file we touched. Now I see the priority and will remember it.

@sashberd What we did (remove `jquery.hoverIntent.min.js` and `jquery.hoverIntent.min.js.map`) might affect users use them. So let's just update the auto-update config. Don't touch the existed files. Thank you.

**Comment by sufuf3** [comment]
@sashberd just follow @extend1994 said then update the commit message from A to B.
- A
```
Update jquery.hoverintent auto-update config & v1.9.0

- Update auto-update config
- Update v1.9.0 because there is a minified file from v1.9.0 of lib
close #11656
```

- B
```
Update jquery.hoverintent auto-update config, close #11656
```

Then, everything is good.

Thank you.

**Pull request merged**
