### PR TITLE
[new] add dialog-polyfill@0.3.0 with git auto-update, close #5008

### LINKED ISSUE #5008: [Request] GoogleChrome/dialog-polyfill

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11, I add a new lib with git auto-update from the request #5008
This lib is lack of a minified version, so I attach on the minified files.
I have recorded them in the "requiredFile" field.
Would you mind checking this PR for me? Thank you~ :-)

*I have removed the file in `requiredFile` field, which has been pointed by `filename` field.

### CODE REVIEW

**Comment by maruilian11** [comment]
i think it's ok. @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Should rebase with latest master branch.

**Comment by Amomo** [comment]
Hi @maruilian11 , I have rebased this PR with latest master branch now.
Could you check it again? Thank you~

**Comment by PeterDaveHello** [comment]
You rebased with a 11 hours ago commit, not latest master branch now.

**Comment by Amomo** [comment]
oops! It's ready now. Thank you for reminding.

**Comment by Amomo** [comment]
Hi @maruilian11 , This branch has rebased with latest master branch now.
Could you take a look?

**Comment by PeterDaveHello** [comment]
Any updates?

**Comment by maruilian11** [comment]
@Amomo sorry, i check up late, can u update the branch again...
my bad.....

**Comment by Amomo** [comment]
@maruilian11 It's okay~
I rebase it to match the latest master branch now.
Could you take a look again? Thank you~ :-D

**Comment by maruilian11** [comment]
@Amomo sorry... the day you deal with these PRs, i seemed not to check the email...
can u rebase it again? feel very sorry...:(

**Comment by Amomo** [comment]
@maruilian11 Never mind~ I have rebased it! :-D

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Comment by Amomo** [comment]
@PeterDaveHello I have rebased this PR with latest master branch.
Could you come to take a look? Thank you! :-D

**Pull request merged**
