### PR TITLE
[author][new] select2-bootstrap-css v1.4.6

### PR DESCRIPTION
**Pull request by fk**
Files from the root of the [bootstrap3 branch](https://github.com/t0m/select2-bootstrap-css/tree/bootstrap3) of [select2-bootstrap-css](https://github.com/t0m/select2-bootstrap-css):

 * [select2-bootstrap.css](https://github.com/t0m/select2-bootstrap-css/blob/dffa8740723d12cf5b9a56a28cc3dcd5e08ac3e2/_jekyll/css/select2-bootstrap.css)
 * [select2-bootstrap.min.css](https://github.com/t0m/select2-bootstrap-css/blob/dffa8740723d12cf5b9a56a28cc3dcd5e08ac3e2/select2-bootstrap.min.css)

While I'm not the original project author, I'm a collaborator and the main maintainer of the bootstrap3 branch.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please add the missing filed `filename` to point to the mainfile(minified), thanks.

**Comment by fk** [comment]
@PeterDaveHello Dang! Sorry! Fixed! :)

**Comment by PeterDaveHello** [comment]
Would you please merge/squash these commits into only one commit as our document said? thanks.

**Comment by fk** [comment]
Dang again, sorry; squashed!

**Comment by PeterDaveHello** [comment]
Thanks a lot @fk, I'm going to merge now!

**Pull request merged**
