### PR TITLE
Add license of swfobject, cc #5500

### PR DESCRIPTION
**Pull request by lcd78706**
Reference: https://github.com/swfobject/swfobject/blob/master/LICENSE

### CODE REVIEW

**Comment by lcd78706** [comment]
@kennynaoh 
Please review this PR. Thanks!

**Comment by kennynaoh** [comment]
LGTM
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
It looks like new CI doesn't work now. @kennynaoh You can try to trigger CI again..

**Comment by kennynaoh** [comment]
@PeterDaveHello Please help me trigger the CI again. Thanks!

**Comment by PeterDaveHello** [comment]
Done

**Comment by kennynaoh** [comment]
@PeterDaveHello The CI seems stuck. Please help me trigger it again. Thanks.

**Comment by PeterDaveHello** [comment]
Not that case, use circle ci's result.

**Comment by kennynaoh** [comment]
OK, ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
