### PR TITLE
Add amazon-cognito-identity-js@1.12.0 w/ git auto-update

### LINKED ISSUE #9725: [Request] Add amazon-cognito-identity
**Library name: amazon-cognito-identity-js (amazon-cognito-identity.min.js)** 
**Git repository url: https://github.com/aws/amazon-cognito-identity-js/**
**npm package url(optional):** 
**License(s): Amazon Software License**
**Official homepage: https://aws.amazon.com/cognito/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #9725

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/aws/amazon-cognito-identity-js/
 * Official website (optional, not the repository): https://aws.amazon.com/cognito/
 * NPM package url (optional):
 * License and its reference: [Amazon Software License](https://github.com/aws/amazon-cognito-identity-js/blob/v1.12.0/LICENSE.txt)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 48
   - Count of stars: 235
   - Count of forks: 91
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9725, cc @aws

### CODE REVIEW

**Comment by extend1994** [comment]
@PeterDaveHello please help me review this pull request, thank you.

**Comment by PeterDaveHello** [comment]
@extend1994 would you please confirm that the amazon software license is a kind of open source license or not?

**Comment by extend1994** [comment]
@PeterDaveHello yes, I can confirm it right now.

**Comment by PeterDaveHello** [comment]
@extend1994 Great!

**Comment by extend1994** [comment]
@PeterDaveHello According to [Open Source Initiative](https://opensource.org/licenses/alphabetical) and [Amazon Software License Reference](https://aws.amazon.com/asl/), I suggest that it is not an open source license, what do you think?

**Comment by PeterDaveHello** [comment]
@extend1994 I will like to discuss with the author and issuer first

**Comment by extend1994** [comment]
@PeterDaveHello Do you mean I should do it or you are going to do it?

**Comment by PeterDaveHello** [comment]
@extend1994 Just suggestions for you

**Comment by extend1994** [comment]
@PeterDaveHello okay :)

**Comment by extend1994** [comment]
@PeterDaveHello Could you please help me take a look at aws/amazon-cognito-identity-js#261? I am not sure it's a kind of open source license or not.

**Comment by PeterDaveHello** [comment]
Base on https://github.com/aws/amazon-cognito-identity-js/issues/261, as it's not open source software, and aws should have their own cdn service to host it, we may not host this one.

**Pull request closed without merging**
