### PR TITLE
add zone.js v0.6.12 with npm auto-update config

### LINKED ISSUE #7983: [Request] Add zone.js
zone.js
https://github.com/angular/zone.js
https://www.npmjs.com/package/zone.js
MIT

Useful library for running async code within a container. Necessary for running Angular 2 applications.

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #7983 
@dannyxx001 please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/angular/zone.js
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/zone.js
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 1,470
   - Count of watchers: 93
   - Count of forks: 123
 * NPM download stats (optional):
   - Downloads in the last day: 8,280
   - Downloads in the last week: 51,067
   - Downloads in the last month: 210,402

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7983, cc @btford

### CODE REVIEW

**Comment by dannyxx001** [comment]
@PeterDaveHello I think the PR is OK. Please review again, thanks.

**Comment by PeterDaveHello** [comment]
What's the reason why to add files for nodejs and test purpose? I thought the files for browsers already been minified as you can recognize.

**Comment by kennynaoh** [comment]
So I should remove the files about `test`, like `async-test.js`, `fake-async-test.js`, and `sync-test.js` and so do `zone.js.d.ts`, right?
Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh and the node file...

**Comment by kennynaoh** [comment]
OK
@dannyxx001 
I have fixed the file problem.
Please help me review it again.
Thanks!

**Comment by dannyxx001** [comment]
Sorry for late response, I think the PR is OK. We can rebase first then call Peter.

**Comment by kennynaoh** [comment]
@dannyxx001 
I have rebased to the latest master branch.
Please help me review it again.
Thanks!

**Pull request merged**
