### PR TITLE
point css3pie's version number to a stable version 1.0.0

### PR DESCRIPTION
**Pull request by LeaYeh**
@Piicksarn could you help me to check this pr? 
 #5276

### CODE REVIEW

**Comment by Piicksarn** [comment]
@LeaYeh, it need to rebase to master!

**Comment by LeaYeh** [comment]
okay i already rebase it.

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you mind to have a look at the pr?
thank you!

**Comment by PeterDaveHello** [comment]
Wrong commit message.

**Comment by PeterDaveHello** [comment]
Pleas make the title shorter, and say that you changed its filename in commit message.

**Comment by PeterDaveHello** [comment]
Close due to no response.

**Pull request closed without merging**
