### PR TITLE
[new] [author] Add pileup.js library

### PR DESCRIPTION
**Pull request by danvk**
[pileup.js][1] is an actively-developed genome viewer. Read more [here][2].

This is set to use NPM auto-update. I'd be happy to delete older versions from this PR. I generated them by running `node auto-update.js run pileup`. I verified that `npm run test` passes.

[1]: https://github.com/hammerlab/pileup.js
[2]: http://www.hammerlab.org/2015/06/19/introducing-pileup-js-a-browser-based-genome-viewer/

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please also provide minified css files for the old versions, thanks.

**Comment by danvk** [comment]
Thanks for taking a look @PeterDaveHello. I've added minified CSS files for all versions.

**Comment by PeterDaveHello** [comment]
@danvk ok, please also rebase this branch with our latest master branch, its parent is a little bit too old, thanks!

**Comment by danvk** [comment]
@PeterDaveHello are you sure? I see this on github:
screen shot 2015-12-01 at 11 08 07 am

And this PR contains only new files.

**Comment by danvk** [comment]
(In any case, I've rebased.)

**Comment by PeterDaveHello** [comment]
I found that we missed the license info, I just merged it first, but can you clarify its license @danvk ? Thanks.

**Pull request merged**
