### PR TITLE
add appbase-js v0.10.8 w/ npm auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
@Amomo could u help me check this PR for #8687 ? thank you!

**git repo url:** https://github.com/appbaseio/appbase-js
**Watch 6
  Star 5
 Fork 6**

**npm package url:** https://www.npmjs.com/package/appbase-js
**29 downloads in the last day
72 downloads in the last week
282 downloads in the last month**

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR 
 * [x] The lib has notable popularity  https://github.com/cdnjs/cdnjs/issues/8687#issuecomment-244734247
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry 
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update) 
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Different comment with the commit?

**Comment by maruilian11** [comment]
when I checked the PR not sent, I put the "Enter" accidentally.
and I find out its popularity is not enough, so I closed the PR without revising it.

**Comment by PeterDaveHello** [comment]
I think I replied on that issue and said we could add it earlier, let's finish this ASAP.

**Comment by maruilian11** [comment]
@Amomo @Piicksarn I add this lib with npm auto-update, could you help me check this PR? thank you!

**Comment by Piicksarn** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
There is a `1.0.0` version in npm package, please confirm that if it's okay, or maybe we need to add it to `.gitignore`

**Comment by maruilian11** [comment]
@Amomo @Piicksarn I have add v1.0.0 to `gitignore`, could you help me check this PR? thanks.
https://github.com/appbaseio/appbase-js/issues/16#issuecomment-245671149

**Comment by PeterDaveHello** [comment]
You should mention the reason you add the path the `.gitignore`, and it's not `gitinore`.

**Comment by maruilian11** [comment]
got it.

**Comment by maruilian11** [comment]
@Amomo @Piicksarn 
I add v1.0.0 to `.gitignore` because there is v1.0.0 in npm package, but it's not on git repo. 
and the latest version is 0.10.8, it's wired v1.0.0 is already on npm, so I opened an issue to confirm with the author if we need to host v1.0.0, and the author said we don't.

**Comment by Piicksarn** [comment]
@PeterDaveHello, should we remove the commend in .gitinore manually when the version 1.0.0 released?

**Comment by PeterDaveHello** [comment]
@Piicksarn the author will send a PR for it, you can remove it then, or just leave it alone, both fine.

**Pull request merged**
