### PR TITLE
[new] add nuclear-js@1.1.1 with git auto-update

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11, This is a resubmission of #5166 
According to 4872683, the directory name should be `nuclear-js`, so I send a new PR to add the lib.
Would you mind checking it again? Thank you~ :-)

### CODE REVIEW

**Comment by maruilian11** [comment]
@Amomo i think it's ok. can u rebase it and tag me.
sorry, i'll check it more quickly next time.

**Comment by Amomo** [comment]
@maruilian11 I have rebased it.
Could you check again? Thank you~

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Comment by PeterDaveHello** [comment]
Funny, v1.1.0 was released 15 days ago, and v1.1.1 was released 10 days ago, but the dist folder didn't been rebuilded which means you put v1.1.0's files here. Please confirm with its author.

**Comment by Amomo** [comment]
Ok~ I have opened an issue at its repo.

**Comment by Amomo** [comment]
They have updated the dist/ folder!
@maruilian11 I have updated nuclear.js and nuclear.min.js with latest version.
Could you check again? Thank you~

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Comment by PeterDaveHello** [comment]
Hope you can be much careful next time.

**Pull request merged**
