### PR TITLE
Add license of jquery-history, cc #5500

### PR DESCRIPTION
**Pull request by NiniHsu**
Reference: https://github.com/tkyk/jquery-history-plugin/blob/master/jquery.history.js

### CODE REVIEW

**Comment by NiniHsu** [comment]
@kennynaoh please help me check this PR.
Thank you!

**Comment by kennynaoh** [comment]
@NiniHsu you can use more precise reference next time, like https://github.com/tkyk/jquery-history-plugin/blob/master/jquery.history.js#L4, thanks.

**Comment by kennynaoh** [comment]
LGTM
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
LGTM

**Comment by NiniHsu** [comment]
@kennynaoh I will remember next time. Thanks!

**Pull request merged**
