### PR TITLE
[New][Author] Add nestable2 w/ git auto-update via single package.json

### PR DESCRIPTION
**Pull request by pjona**
Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/RamonSmit/Nestable2
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/nestable2
 * License and its reference: https://github.com/RamonSmit/Nestable2/blob/master/LICENSE
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 12
   - Count of stars: 54
   - Count of forks: 28
 * NPM download stats (optional):
   - Downloads in the last day: 23
   - Downloads in the last week: 146
   - Downloads in the last month: 275

# Essential checklist
 * [ ] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

# Extra information
This is quite old library, but I just start active develop it in last time. Package is on npm from exactly one month (from 22th May 2017) so stats are not very high. Previous time there was only bower installation, so most of the people using bower.

### CODE REVIEW

**Comment by dakshshah96** [comment]
@pjona, No need to close the PR. One of the maintainers will modify the commit message for you :) Let's wait for them.

**Comment by pjona** [comment]
@sufuf3 I used Github website to fork the repository and make all changes, so I send another commit.

**Comment by sufuf3** [comment]
@pjona Thank you.
I'll help you squash to one commit and revise the commit message. :)

**Comment by RamonSmit** [comment]
@pjona @dakshshah96 I'm not entirely sure how the `package.json` works, but if it's possible to add multiple authors, then it would be fair to me if @pjona and @RamonSmit are added to the list. 

Just a opinion :-).

**Comment by dakshshah96** [comment]
@RamonSmit Multiple authors can be added :)

@sufuf3 Please add the other authors too.

**Comment by pjona** [comment]
If there are multiple authors we should skip `author` property and use `authors`?

```
"authors": [
  {
    "name": "David Bushell",
    "email": "hi@dbushell.com",
    "url": "https://github.com/dbushell"
  },
  {
    "name": "Ramon Smit",
    "email": "ramon@daltcore.com",
    "url": "https://github.com/RamonSmit"
  },
  {
    "name": "Marek Skiba",
    "email": "skibamarek@gmail.com",
    "url": "https://github.com/pjona"
  }
],
```

**Comment by dakshshah96** [comment]
@pjona That's right :)
cc @sufuf3

**Comment by pjona** [comment]
@dakshshah96 Ok, I added more authors.
@sufuf3 can you help me once again with squashing everything into one commit?

**Comment by sufuf3** [comment]
It's my pleasure. I'll help you squash to one commit.

**Comment by sufuf3** [comment]
@cdnjs/library-reviewer 
Please help review this PR, Thank you.

**Comment by PeterDaveHello** [comment]
@pjona is it possible to remove the folder `jquery.nestable.min.css` and `jquery.nestable.min.js` in `dist`? I'm afraid I don't understand their meaning, they just made the url much more longer.

**Comment by pjona** [comment]
@PeterDaveHello You are right, it shouldn't be like that. I removed unneeded directories, check right now.

**Comment by PeterDaveHello** [comment]
@pjona thanks! So this change would not only be in this commit but also the future releases right?

**Comment by pjona** [comment]
@PeterDaveHello Yes, I changed way of generating this files in `gulpfile.js`, so this is how it will be looks for all future releases. Do you want new release (tag) with this changes?

**Comment by PeterDaveHello** [comment]
@pjona No I don't think so :)

**Comment by PeterDaveHello** [comment]
@extend1994  @dakshshah96  @sufuf3 I directly update the auto-update as above, which can help grab both src and old versions, please take a look.

**Pull request merged**
