### PR TITLE
Add license of jquery-resize, cc #5500

### PR DESCRIPTION
**Pull request by NiniHsu**
Reference: http://benalman.com/about/license/

### CODE REVIEW

**Comment by NiniHsu** [comment]
@kennynaoh please help me review this PR.
Thank you!

**Comment by PeterDaveHello** [comment]
@NiniHsu I think we could try to fix the old one instead of openning new ones next time, if you really need to open a new one, please also mention each other issues so that we can easily know what's going on here. cc #9850

**Comment by NiniHsu** [comment]
@PeterDaveHello I accidently deleted the commit on the web, so the old PR was closed.
I am sorry for this.

**Comment by PeterDaveHello** [comment]
@NiniHsu No worry, but you can ask your mentor nextime before opening a new one as you can still fix the old one.

**Comment by kennynaoh** [comment]
LGTM
ping @cdnjs/intern2

**Pull request merged**
