### PR TITLE
[new] es-class 1.2.0 - all files

### PR DESCRIPTION
**Pull request by WebReflection**
Hopefully the "OK PR" version of es-class.

Thanks

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I have a question, so `es-class.npm.js` didn't have `max` and non-`max` version? Or AKA minified and un-minified.

**Comment by PeterDaveHello** [comment]
And there are still only that two files under build folder in the latest npm release.

**Comment by WebReflection** [comment]
that's the default for about every project I have hosted in here. The npm version is meant to run either on the server, where minification is less important than good debugging, or through browserify, where minification will happen within the tool.

So, usually I hve the npm version that exports to the module via CommonJS, node/iojs or browserify will just work there without problems, if you grab on the fly is probably a runtime browserify env for debugging/testing only.

AMD and global versions have max and minified by default. Does this work?

**Comment by PeterDaveHello** [comment]
Yes, and can you make sure that we can got other files via npm package in future releases?

**Comment by WebReflection** [comment]
I am pushing now them bumping to 1.2.1 on npm

**Comment by PeterDaveHello** [comment]
Why do we need to host the files for server side only on cdn? I think cdn is for client side.

**Comment by WebReflection** [comment]
> Why do we need to host the files for server side only on cdn? I think cdn is for client side.

it gives developers the ability to use CommonJS via CDN ... do you want a specific white list of 4 files instead of 5?

**Comment by PeterDaveHello** [comment]
That's fine, just confirm that.

**Comment by WebReflection** [comment]
btw ... lol, I just pushed client files only to npm package and now you are asking me to drop the npm file for the package :D 

this is what I've meant before when I've asked if it had to reflect npm registry. This is new to me, not sure we are in a deadlock now, eheh

**Comment by PeterDaveHello** [comment]
No no no, just want to confirm that you want it on cdn, you can host that 5 files, that's fine.

**Comment by WebReflection** [comment]
cool, so npm 1.2.1 should contans everything we need

**Comment by PeterDaveHello** [comment]
Okay, I think you should fix the error in this build, so I'l merge it.

**Comment by WebReflection** [comment]
honestly no idea what's the error about. 

> ./ajax/libs/es-class/1.2.0/es-class.js does not exist but is referenced in package.json

the file **is** there ... am I doing anything wrong in here?

```js
"filename": "es-class.js",
  "npmName": "es-class",
  "npmFileMap": [
    {
      "basePath": "/build/",
      "files": [
        "*.js"
      ]
    }
  ]
```

**Comment by PeterDaveHello** [comment]
Because you put them in `build` ... should move out.

**Comment by WebReflection** [comment]
dumb me

**Comment by PeterDaveHello** [comment]
Please squash them into only one commit, thanks.

**Comment by WebReflection** [comment]
you know what ... I'm close to give up here ...

**Comment by PeterDaveHello** [comment]
I believe that this will help you https://github.com/cdnjs/cdnjs/blob/master/sparseCheckout.md

**Comment by PeterDaveHello** [comment]
BTW, you can just use `git reset HEAD^` to undo the last commit, and use `--amend` to add files to the previous commit, and this method works very fast.

**Comment by WebReflection** [comment]
tried that, went bananas with the push after ... let's see if I'll ever manage. thanks though, and sorry for bothering so much for a 1KB library

**Comment by PeterDaveHello** [comment]
that's fine, hope you got something during this period, like git skills :smile:

**Comment by WebReflection** [comment]
pretty sure I'm going to screw all of it next time anyway ... as usual

**Comment by WebReflection** [comment]
no, this is going nowhere. I'll try again from scratch. have a nice day

**Comment by WebReflection** [comment]
Sorry Peter, just trying to get it right for the last attempt ...

let's scratch npm, would this be OK as autoupdate?

```js
"autoupdate": {
    "source": "git",
    "target": "git://github.com/WebReflection/es-class.git",
    "basePath": "build",
    "files": [
      "es-class.amd.js",
      "es-class.max.amd.js",
      "es-class.js",
      "es-class.max.js"
    ]
  }
```

Also [here](https://github.com/cdnjs/cdnjs#enabling-gitrecommended-or-npm-auto-update) is not entirely clear if autoupdate works by tags or it just checks last commit.

Cheers

**Comment by PeterDaveHello** [comment]
Nice, yes, it uses tags as contributing document says,  see https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#f-ps

**Comment by WebReflection** [comment]
I do hope this is OK. https://github.com/cdnjs/cdnjs/pull/4743

**Pull request closed without merging**
