### PR TITLE
[New] Add noty@3.1.2 w/ npm auto-update

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #11743

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/needim/noty
 * Official website (optional, not the repository): https://ned.im/noty
 * NPM package url (optional): https://www.npmjs.com/package/noty
 * License and its reference: [MIT](https://github.com/needim/noty/blob/master/LICENSE.txt)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 236
   - Count of stars: 5,454
   - Count of forks: 838
 * NPM download stats (optional):
   - Downloads in the last day: 505
   - Downloads in the last week: 3,222
   - Downloads in the last month: 13,573 

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by extend1994** [comment]
Use npm instead of GitHub as the source of auto-update config because we prefer npm and the versions we are v3.0.0 ~ v3.1.2, which exist on both platform. The lib `jquery-noty` is a predecessor of this lib, according to the discussions in https://github.com/cdnjs/cdnjs/issues/11743, we are going to host them separately.

**Comment by sufuf3** [comment]
Have a question~
I found that there are 23 releases versions from npm, and 46 releases versions from GitHub.
As usual, we prefer to use more releases versions as the auto-update option.
And I can't find the discussion with auto-update config that using npm is better.
So why we need to choose npm?

And I have the impression that we have to use `noty*` in `lib` as basepath, isn't it?

**Comment by sufuf3** [comment]
And the commit message needs to modify...

**Comment by extend1994** [comment]
@sufuf3 
1. I minified noty.css and wrapped the commit message. 
2. Please read [#issuecomment-326729581](#issuecomment-326729581) and #11743. noty and jquery-noty are going to be hosted on CDNJS separately. The versions before v3.0.0 belongs to jquery-noty. So the number of versions on npm and GitHub are the same.

Please help review this PR, thank you.

**Comment by extend1994** [comment]
ping @cdnjs/intern3 @cdnjs/library-reviewer @cdnjs/active-contributor

**Comment by maruilian11** [comment]
We can't provide partially minify function for one directory. Can you please ask the author if he/she can provide `css`'s minified file.

**Comment by extend1994** [comment]
@maruilian11 I asked Peter about this, and he said we can do that. I will give the reference later. Please help me review other parts. Thanks.

**Comment by extend1994** [comment]
The reference was given in https://github.com/cdnjs/cdnjs/pull/11504#issuecomment-331507316.

**Comment by maruilian11** [comment]
@extend1994 Yes, in this name scheme, we can minify the file. Sorry for not noticing that.

**Comment by maruilian11** [comment]
Then, I think it's better to mention you minify the css youself in the commit msg?

**Comment by sufuf3** [comment]
@maruilian11 May I ask that why we need to mention this in the commit message?
Sorry that I don't know before.
I sent PRs before when I add a new lib if there are some file need to be minified, I always generate the minified file without mention it.
I afraid that I did something wrong before.
Thank you.

**Comment by maruilian11** [comment]
@sufuf3 It's about the tracing. If you mention it, which will help us figure where the minified files from.
Don't worry about the previous PR, can you mention it from now? :smiley:

**Comment by extend1994** [comment]
@maruilian11 I add the part you said. Please help me review it, thanks!

**Pull request merged**
