### PR TITLE
add expect 1.12.2

### PR DESCRIPTION
**Pull request by mjackson**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please also add `repository` in package.json

**Comment by mjackson** [comment]
Why do I need a repository? I thought the whole point of using the `npmName` field was that you weren't going to be pulling from the git repo anymore.

**Comment by PeterDaveHello** [comment]
We will show the count of watcher, star and fork on search result of the repo, so please add it.

**Comment by mjackson** [comment]
Nevermind.

**Comment by PeterDaveHello** [comment]
@mjackson sorry for the inconvenience. @maruilian11 please help send another PR to add this lib.

**Pull request closed without merging**
