### PR TITLE
Add videojs-vimeo@2.0.2 w/ npm auto-update

### PR DESCRIPTION
**Pull request by x09326**
Pull request for issue: #9524
Related issue(s): # #
Manaully add v1.0.2 due to the filename is different from the other versions.
@kennynaoh @pvnr0082t 
Please help me review it, thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/videojs/videojs-vimeo
 * Official website (optional, not the repository):
 * NPM package url (optional):https://www.npmjs.com/package/videojs-vimeo
 * GitHub / Bitbucket popularity (required):
   - Count of stars:112
   - Count of watchers:25
   - Count of forks:80
 * NPM download stats (optional):
   - Downloads in the last day:28
   - Downloads in the last week:114
   - Downloads in the last month:474

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by x09326** [comment]
@kennynaoh @pvnr0082t 
The filename in version v1.0.2 is different.
What should I do?
Please help me, thanks.

**Comment by pvnr0082t** [comment]
@x09326 You should confirm if they are same file but different filename with author. If yes, you can change filename in old version to make it consistent.

**Comment by PeterDaveHello** [comment]
I didn't see the file under v1.0.2's `lib` directory in the git repo, only the root, can we just move on?

**Comment by x09326** [comment]
@PeterDaveHello The file is under `src`.

**Comment by PeterDaveHello** [comment]
@x09326 Maybe we could just use lib?

**Comment by x09326** [comment]
@PeterDaveHello I'm not sure, maybe I need to confirm that too.

**Comment by PeterDaveHello** [comment]
Any updates here?

**Comment by x09326** [comment]
The author have not reply yet.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@extend1994 I saw you'd like to add this lib https://github.com/cdnjs/cdnjs/issues/11170#issuecomment-316740825
If you have time please work on this PR, thank you.

**Comment by extend1994** [comment]
Waiting https://github.com/videojs/videojs-vimeo/issues/94#issuecomment-329138754

**Comment by sufuf3** [comment]
@PeterDaveHello Could we close this one and wait for response from upstream?
Also, the issue was assigned by @extend1994 herself.

Many thanks.

**Pull request closed without merging**
