### PR TITLE
Add Jouele v2.1.2 with git auto-update config

### LINKED ISSUE #7419: [Request] Add Jouele
**Library name: Jouele 
**Git repository url:https://github.com/ilyabirman/Jouele
**npm package url(optional):** 
**License(s):MIT License
**Official homepage:http://ilyabirman.net/projects/jouele/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by x09326**
PR for #7419 
@dannyxx001 please help me review it, thanks.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/ilyabirman/Jouele/tree/v2.1.2
 * Official website (optional, not the repository): http://ilyabirman.net/projects/jouele/
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 115
   - Count of watchers: 8
   - Count of forks: 13
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7419, cc @ilyabirman

### CODE REVIEW

**Comment by dannyxx001** [comment]
Yeah, I think this PR is OK. @PeterDaveHello please review again, thanks.

**Comment by PeterDaveHello** [comment]
Your files in the PR looks inconsistent with the origin repo, please check it.

**Comment by x09326** [comment]
@PeterDaveHello 
The ```jouele.min.js``` was named ```jouele.js```.
Because the file was minified, then the field of ```filename``` should include ```min```, so I renamed it.

**Comment by PeterDaveHello** [comment]
@x09326 nope, please don't do that.

**Comment by x09326** [comment]
Um, so what should I do?
Open an issue to ask the author rename it?
Or do minify by myself? But I do the minify then the capacity of the file won't be minify.

**Comment by PeterDaveHello** [comment]
@x09326 Nope, just leave it alone as origin.

**Comment by x09326** [comment]
@dannyxx001 
I haved changed to origin files, please help me review it, thanks

**Pull request merged**
