### PR TITLE
[Author] Add jcanvas@20.0.0 w/ npm auto-update and update package.json (again)

### PR DESCRIPTION
**Pull request by caleb531**
Hi,

Something broke when I tried to rebase and force-push in #11471. This time, I've rebranched and recommitted everything to be as requested (i.e. only the minimal number of distinct commits).

@sufuf3 and @PeterDaveHello, please take a look and let me know if this looks good to you.

# Profile of the lib
 * Name: jcanvas
 * Git repository (required): https://github.com/caleb531/jcanvas
 * Official website (optional, not the repository): https://projects.calebevans.me/jcanvas/
 * NPM package url (optional): https://www.npmjs.com/package/jcanvas
 * License and its reference: MIT (https://github.com/caleb531/jcanvas/blob/master/LICENSE.txt)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 39
   - Count of stars: 473
   - Count of forks: 152

# Essential checklist
 * [X] I'm the author of this library

# Auto-update checklist
 * [X] Has valid tags for each versions (for git auto-update)
 * [X] Auto-update setup
 * [X] Auto-update target/source is valid.
 * [X] Auto-update filemap is correct.

# Git commit checklist
 * [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X] The parent of the commit(s) in the PR is not old than 3 days.
 * [X] Pull request is sending from a non-master branch with meaningful name.
 * [X] Separate unrelated changes into different commits.
 * [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [X] Close corresponding issue in commit message
 * [X] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@caleb531 thanks

**Comment by caleb531** [comment]
@PeterBot tells me my branch is too old (need to pull from upstream), so I will close this PR and reopen with a fresher branch.

**Comment by PeterDaveHello** [comment]
@caleb531 I can update it for you if you want.

**Comment by caleb531** [comment]
@PeterDaveHello Yes, please—that would be fantastic, thanks.

**Comment by PeterDaveHello** [comment]
@caleb531 Okay, give me few mins please.

**Comment by PeterDaveHello** [comment]
@caleb531 as you deleted the repostory and closed the pull request, I can't update it for you :(

**Comment by caleb531** [comment]
@PeterDaveHello yeah, so sorry about that. Let me push up again and create a new PR.

**Comment by PeterDaveHello** [comment]
@caleb531 no worries

**Pull request closed without merging**
