### PR TITLE
Add git auto-update for EaselJS

### LINKED ISSUE #11362: [Request] Add the auto-update config of EaselJS
**Library name:** EaselJS
**Git repository url:** https://github.com/CreateJS/EaselJS
**License (List them all if it's multiple):** MIT
**Official homepage:** http://www.createjs.com/easeljs

### PR DESCRIPTION
**Pull request by dakshshah96**
close #11362

Pull request for issue: #11362

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Looks like we should discuss with its authors about the possibility to remove version number in filenames?

**Comment by dakshshah96** [comment]
@PeterDaveHello I don't think it'll be possible since even they have their own CDN at http://code.createjs.com/ . They also have another website at http://createjs.com/ which also has links to their files and that's the standard format they use.

Not possible to use file rules and work around this?

**Comment by PeterDaveHello** [comment]
@dakshshah96 This is one of our basic conventions, and even other commen public CDN service, without this convention, I need to spend addtional time on manually commit them every versions which is a very not good idea. (It's better to save time to work on the automation, development works, and project management, promotion, isn't it?)

In most cases, I believe that we can provide better performance and security, also, they'll get promotion by serving on cdnjs, so I think we can still talk to them about the chance, what do you think?

**Comment by dakshshah96** [comment]
@PeterDaveHello Done 👍  https://github.com/CreateJS/EaselJS/issues/879

**Comment by sufuf3** [comment]
@dakshshah96 as the maintainer of this lib said https://github.com/CreateJS/EaselJS/issues/879#issuecomment-327253615
I think until now we still add this lib manually.
When the filenames do not include version number anymore, we can add auto-update config.
 What do you think?

**Comment by sufuf3** [comment]
The author said they have simplified the naming in the v1.0.0 (CreateJS/EaselJS#879).
So we can work on this. :)

**Comment by sufuf3** [comment]
@dakshshah96 Would you help add old versions which filename with version and we need to rename the filename?
If there is no response in 7 days or you are busy recently, I can help you this PR. 
Thanks for your great work and contribution.

**Comment by maruilian11** [comment]
@dakshshah96 Would you like to keep going on this? There is another PR opened for it. https://github.com/cdnjs/cdnjs/pull/11851

**Comment by PeterDaveHello** [comment]
Let's move to #11851

**Pull request closed without merging**
