### PR TITLE
[new] es-class 1.2.0

### PR DESCRIPTION
**Pull request by WebReflection**
Please make this library available to the entire World Wide Web.

It has been shown and discussed in few talks already, I've never realized it wasn't here.

Thank you very much!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
There is only `es-class.js`, `es-class.npm.js` under `build`.

**Comment by WebReflection** [comment]
actually not sure I understand what you mean. I've used for the first time this automatic tool for new libraries, but it should serve and automatically update what's inside build/ folder, correct?

**Comment by PeterDaveHello** [comment]
you added other files, where are they from?

**Comment by WebReflection** [comment]
uhm ... something weird is going on ... 

so everything is here: https://github.com/WebReflection/es-class/tree/master/build

and this PR should include all of them

**Comment by WebReflection** [comment]
I think I'll do the "close and re-PR" dance one more time. Apologies

**Comment by PeterDaveHello** [comment]
Maybe you forgot to put them on npm package? You can use git auto-update if you put them in git repo.

**Comment by WebReflection** [comment]
That might be the reason. I am re-cloning and will manually submit soon.

Once question though: does it have to be in npm too ? 'cause I tend to publish in npm only the npm module version of my scripts, and not all of them.

If cdnjs relies in npm published scripts then that explains why I always have problems making PRs :-)

Thanks for any outcome

**Comment by PeterDaveHello** [comment]
Not relys on npm, but can do auto-update from npm, also from git repo.

**Comment by WebReflection** [comment]
I hope I've fixed everything in here: https://github.com/cdnjs/cdnjs/pull/4741

**Pull request closed without merging**
