### PR TITLE
Enrich markdown.js' package.json(field: license)

### PR DESCRIPTION
**Pull request by LeaYeh**
Hi @Amomo  , 
From #5500, I have added license info.
repo : https://github.com/evilstreak/markdown-js
Would you mind checking this PR for me? Thank you.

- [ ] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `160`, Star `3940`, Fork `565`**
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.

### CODE REVIEW

**Comment by Amomo** [comment]
Hi @LeaYeh I think this PR is fine.
Could you rebase it to match the latest master branch? Thank you! :-D

**Comment by drewfreyling** [comment]
@Amomo The diff would be the same either way so not much point in rebasing?

**Comment by PeterDaveHello** [comment]
@drewfreyling we should keep the history clean and easier to be traced in future. The merge commit that crossed too many commits will make the process of trace or debug harder.

**Comment by Amomo** [comment]
@LeaYeh could you rebase this PR? Thank you~

**Comment by PeterDaveHello** [comment]
* d0935da Add missing license field with SPDX identifier Peter Dave Hello 2 weeks ago

**Pull request closed without merging**
