### PR TITLE
add slidebars@2.0.2 and update package.json of slidebars

### LINKED ISSUE #8478: [Request] Add Slidebars 2.0.2
**Library name:** Slidebars 2.0.2
**Git repository url:** https://github.com/adchsm/Slidebars.git
**npm package url(optional):** 
**License(s):**  https://github.com/adchsm/Slidebars/blob/master/license.txt
**Official homepage:** http://www.adchsm.com/slidebars/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #8478 
@pvnr0082t please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/adchsm/Slidebars
 * Official website (optional, not the repository): https://www.adchsm.com/slidebars
 * NPM package url (optional): https://www.npmjs.com/package/slidebars
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 1154
   - Count of watchers: 97
   - Count of forks: 279
 * NPM download stats (optional):
   - Downloads in the last day: 2
   - Downloads in the last week: 17
   - Downloads in the last month: 46

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8478

### CODE REVIEW

**Comment by pvnr0082t** [comment]
> * GitHub / Bitbucket popularity (required):
>   - Count of stars: 97
>   - Count of watchers: 1154
>   - Count of forks: 279

@kennynaoh You filled in wrong order.

**Comment by pvnr0082t** [comment]
@kennynaoh You didn't check the lib in cdnjs. The `slidebar` already exists in cdnjs. 
ref: https://cdnjs.com/libraries/slidebars
Maybe you just need to add auto-update config for `slidebar`

**Comment by kennynaoh** [comment]
@pvnr0082t 
I have fixed it.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
@kennynaoh You need to separate `add slidebars@2.0.2`, `add npm auto-update`, `add information in package.json` into 3 commits.

**Comment by kennynaoh** [comment]
@pvnr0082t 
I have fixed the commit message.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
@kennynaoh Because slidebars already exists in cdnjs, we don't need to cc the author. Please modify commit message.

**Comment by PeterDaveHello** [comment]
@kennynaoh you should review the old PRs before you send the new PRs: #8486

**Comment by kennynaoh** [comment]
@PeterDaveHello , ok

**Comment by kennynaoh** [comment]
@pvnr0082t 
I have removed `author` in commit message.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
Wrong commit message, you add npm auto-update config twice?

**Comment by kennynaoh** [comment]
@pvnr0082t 
I have fixed the commit message.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
I think you misunderstand. `add slidebars@2.0.2`, `add npm auto-update`, `add information in package.json` are three commits.

**Comment by PeterDaveHello** [comment]
the "information" could also be much more precise.

**Comment by kennynaoh** [comment]
@pvnr0082t
I have fixed the commit message.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
@kennynaoh I think it's better to change the version info to 2.0.2 in the first commit.

**Comment by kennynaoh** [comment]
@pvnr0082t 
What do you mean?
I don't get it.
Thanks!

**Comment by pvnr0082t** [comment]
@kennynaoh You change version to 2.0.2 in the third commit now.

**Comment by kennynaoh** [comment]
@pvnr0082t 
I have fixed it, I changed the version to 2.0.2 in first commit.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
Why don't you mention the lib you modified in the second and third commit message?

**Comment by kennynaoh** [comment]
@pvnr0082t 
I have fixed the commit message.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Pull request merged**
