### PR TITLE
Add localmodel library

### PR DESCRIPTION
**Pull request by RickCraig**
Adding the first fully working version: 0.6.0

### CODE REVIEW

**Comment by RickCraig** [comment]
Can someone help me with the build, I can't find a reason why it's failing. Thanks!

**Comment by Amomo** [comment]
Hi @RickCraig

Recently, the build sometimes get failed before the test starting.
We are checking this problem.
Could you try to resend your commit a few times before the problem fixed?

Sorry for the inconvenience.

**Comment by Amomo** [comment]
Hi @RickCraig 
Would you please squash them into only one commit? Thank you! :-)

**Comment by RickCraig** [comment]
Rebased and squashed, thanks for all your help @Amomo 

I was delayed due to the sortable/Sortable issue, but I found the document on doing a sparse checkout and that solved it for me :sheep:

**Comment by Amomo** [comment]
@RickCraig Great! :+1: 

@PeterDaveHello I think is PR is fine, could take a look? Thank you!

**Comment by PeterDaveHello** [comment]
Do you need to read the document @Amomo ?

**Comment by Amomo** [comment]
Oh... I am too late to find that...

@RickCraig I am very very sorry...😔
According to our document, because `localmodel` don't have 100+ stars on GitHub.
We won't accept it currently.
Sorry I didn't notice that at the beginning.

Could you resend a PR when `localmodel` has more popularity?
Thank you for your every effort on this PR.

**Pull request closed without merging**
