### PR TITLE
Add rison@0.1.3 w/ git auto-update

### PR DESCRIPTION
**Pull request by finch185277**
Pull request for issue: #11505

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/Nanonid/rison
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference:MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:3
   - Count of stars:103
   - Count of forks:27
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@sashberd It fine for this PR. Because the issue created on 4 Jul 2017 which before this [commit](https://github.com/cdnjs/cdnjs/commit/c484b8b1bdfaaf32e742a1687e927afe2de710c0#diff-6a3371457528722a734f3c51d9238c13). So this lib follow the popularity in past.
 
@finch185277 It's my bad.
There is no git tag in this lib. would you discuss with the author?
Here is an example: https://github.com/essoduke/jQuery-tinyMap/issues/19

And maybe we can add https://www.npmjs.com/package/rison. However, the lib's name should be revise to `jonasfj-rison`.
What do you think?

Many thanks

**Comment by finch185277** [comment]
I opened an [issue](https://github.com/Nanonid/rison/issues/27) to discuss with the author.

**Comment by sufuf3** [comment]
@finch185277 nice work.
Also, would you please add `cdnjs/cdnjs#12347`and `cdnjs/cdnjs#11505` in that issue comment?

Many thanks.

**Comment by sashberd** [comment]
@MattIPv4 This one had low popularity in the day of adding also no git tag, no npm. Suggest to close

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄

**Pull request closed without merging**
