### PR TITLE
Add keyboardjs v2.2.0 with git auto-update config

### LINKED ISSUE #7509: [Request] KeyboardJS
**Library name:** KeyboardJS
**Git repository url:** https://github.com/RobertWHurst/KeyboardJS
**npm package url(optional):** https://www.npmjs.com/package/keyboardjs
**License(s):** https://github.com/RobertWHurst/KeyboardJS/blob/master/LICENSE
**Official homepage:** https://github.com/RobertWHurst/KeyboardJS
**Wanna say something? Leave message here:**

### PR DESCRIPTION
**Pull request by x09326**
PR for #7509 
@pvnr0082t please help me review this pull request, thanks.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/RobertWHurst/KeyboardJS
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/keyboardjs
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 1140
   - Count of watchers: 41
   - Count of forks: 136
 * NPM download stats (optional):
   - Downloads in the last day: 30
   - Downloads in the last week: 213
   - Downloads in the last month: 983

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7509, cc @Mottie

### CODE REVIEW

**Comment by pvnr0082t** [comment]
I think you shoud try:
https://github.com/RobertWHurst/KeyboardJS/tree/master/dist
@PeterDaveHello I think it's better to use git autoupdate. I'm not sure.

**Comment by pvnr0082t** [comment]
@x09326 The fork number of this repo is 136.

**Comment by PeterDaveHello** [comment]
Looks like the file you grabbed from `lib` folder in `npm` package is not for distribution, browser will need the file from `dist` folder in the repo as its readme says:
https://github.com/RobertWHurst/KeyboardJS#keyboardjs

**Comment by x09326** [comment]
@pvnr0082t 
I have already modified it to git auto-update.
Please help me review it again, thank you.

**Pull request merged**
