### PR TITLE
[author] jquery.scregal v1.1

### PR DESCRIPTION
**Pull request by kunass2**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I think the config of auto-update will not work, and the commit log should include the lib's name.

**Comment by kunass2** [comment]
May I ask, why my auto-update will not work?

**Comment by PeterDaveHello** [comment]
A wildcard symbol will only match the first layer, doesn't contain any useful files in this project.

You can take uikit's package.json as an example :)

**Comment by kunass2** [comment]
It means that:  "*" is wrong. Where can i take package.json example from?

**Comment by PeterDaveHello** [comment]
From here please https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/uikit/package.json
And please leave other parts alone, like the url of the repo, there is no reason to change the protocol to https, git protocol is more efficient then https, though some firewalls may block it, but most of the users or contributors don't need to run the auto-update process, so git will be better here.

**Comment by drewfreyling** [comment]
Closing because @kunass2 added #4183

**Pull request closed without merging**
