### PR TITLE
[new] Added Shave@0.2.3 with npm auto-update

### PR DESCRIPTION
**Pull request by JamesHealdUK**
Pull request for issue: #9927
Related issue(s): N/A

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/dollarshaveclub/shave
 * Official website (optional, not the repository): https://dollarshaveclub.github.io/shave/
 * NPM package url (optional): https://www.npmjs.com/package/shave
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 1163
   - Count of watchers: 44
   - Count of forks: 48
 * NPM download stats (optional):
   - Downloads in the last day: 30
   - Downloads in the last week: 321
   - Downloads in the last month: 1196

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup # ?? Im unsure as this wasnt documented in depth so I just tried my best with the information given in the contribution document.
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit. # Not applicable?
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@mercyg let's send your first PR ASAP :)

**Comment by PeterDaveHello** [comment]
@JamesHealdUK thanks for the PR, there are some issues need to be fixed and the issues are mentioned in the CI, would you like to try to fix it by your own or you'll need our help? Maybe you can try to fix it first, and ping me if you need help :) @pvnr0082t and @x09326 will also help you.

**Comment by JamesHealdUK** [comment]
Thanks a lot for the offer @PeterDaveHello ! I've just given it a shot myself and Im hoping to build will go through as planned... Il give it a few attempts and see how I get on.

Exciting times!

**Comment by PeterDaveHello** [comment]
@JamesHealdUK Nice, feel free to ask for help you if need it!

**Comment by JamesHealdUK** [comment]
Hopefully thats all correct? Not sure whether or not to close it so Il leave it up to you guys to decide what to do next! :D

**Comment by PeterDaveHello** [comment]
@JamesHealdUK awesome! Maybe next time you could try with git command line locally to learn some git skills, and also you can squash the commits into only one, rather than 7 commits here (I'll squash them for you before merging)! BTW, next time if there are more versions on git repo, let's use git auto-update, if more one npm, then use npm auto-update :+1: ref: #10000

**Comment by PeterDaveHello** [comment]
PS: Note that I changed the commit message, please take a look at: https://github.com/cdnjs/cdnjs/commit/83e31303b989dc55bde7b14483c60152dbb5c700

**Comment by JamesHealdUK** [comment]
Cheers, @PeterDaveHello ! Learnt a lot over the course of this pull request,will definitely keep this all in mind for the next contribution. I also didnt know about the squash command either, so thats been really helpful.

Got only one question though (sorry to spam up the pull request comments with this!) but Id like to know how to clone the cdnjs repo without cloning all 60GB of it? I tried this https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md but ended up with no files in my cdnjs folder... Just .git and thats it, it was 2.9gb big though, so the size was right.

Tried  `git checkout origin/master` and it takes a while doing nothing and ends with `Killed.`, with still nothing in my repo folder.

**Comment by PeterDaveHello** [comment]
@JamesHealdUK Can you show me the content of .git/info/sparse-checkout?

**Comment by JamesHealdUK** [comment]
```
/build
/documents
/test
/tools
/MIT-LICENSE
/hooks
/MAINTAINERS
/*.yml
/*.md
/*.json
/*.sh
/*.js
/ajax/libs/jquery/*
#/ajax/libs/*/package.json // for tools/createSparseCheckoutConfig.js

```

Unsure whats going on here... I just copied and pasted it to give it a try to see if I could get it working.

**Comment by PeterDaveHello** [comment]
@JamesHealdUK Have you tried git reset --hard? Would you please also show me result of git branch?

**Pull request merged**
