### PR TITLE
add dc.min.css in auto-update filemap of dc

### PR DESCRIPTION
**Pull request by gordonwoodhull**
adding one more artifact to our distro
(oh joy)

thank you!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Commit's parent was too old, would you please rebase your branch with our latest master branch? Thanks.

**Comment by gordonwoodhull** [comment]
I see. I was trying to avoid downloading the 10GB repo again by using the GitHub UI, but now I see that's impossible. Will do.

**Comment by PeterDaveHello** [comment]
@gordonwoodhull Sorry for that, i think you can try sparse-checkout, i wrote a doc about it in the root of cdnjs repo,   will really help. Thanks.

**Comment by gordonwoodhull** [comment]
That's great to know about, thanks!

**Comment by PeterDaveHello** [comment]
No problem.

**Comment by gordonwoodhull** [comment]
Okay, my branch should be properly rooted now. Thanks again for the hint. :)

**Comment by gordonwoodhull** [comment]
Oh, maybe this PR wasn't necessary? I already see the added file on cdnjs.

**Comment by PeterDaveHello** [comment]
That's manually minified, looks okay to merge, it'll be better if the commit msg can be much clear next time :+1:

**Comment by gordonwoodhull** [comment]
Okay will do. Thanks again!

**Comment by PeterDaveHello** [comment]
:+1:

**Pull request merged**
