### PR TITLE
add cartodb.js v3.15.9 with npm auto-update config

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #6746
@dannyxx001  please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/CartoDB/cartodb.js
- Official website (optional, not the repository): http://docs.cartodb.com/cartodb-platform/cartodb-js/
- NPM package url (optional): https://www.npmjs.com/package/cartodb.js
- GitHub / Bitbucket popularity (required):
  - Count of stars: 267
  - Count of watchers: 99
  - Count of forks: 183
- NPM download stats (optional):
  - Downloads in the last day: 60
  - Downloads in the last week: 90
  - Downloads in the last month: 216
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [ ] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [ ] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [ ] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

cc #6746, cc @javisantana

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@kennynaoh https://github.com/kennynaoh/cdnjs/blob/cartodb.js/ajax/libs/cartodb.js/3.15.9/themes/css/cartodb.css#L1 show that it has been minified already. You don't need to minify again.

**Comment by kennynaoh** [comment]
@pvnr0082t 
I have updated the file.
Please help me review this PR again.
Thanks.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
Minify `cartodb.uncompressed.js` to `cartodb.uncompressed.min.js` makes no sense, can you check if there is something like `cartodb.js` or `cartodb.min.js`?

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I found the ```cartodb.js``` in [github](cartodb.uncompressed.js), but it's not in npm package.
And it's almost the same as the ```cartodb.uncompressed.js```.
The different place is at the begin and the end of two files.
What should I do next?
Thanks.

**Comment by PeterDaveHello** [comment]
@kennynaoh Can you confirm with its author is there is a "compressed" distribution file? Thanks.

**Comment by kennynaoh** [comment]
Sure!

**Comment by PeterDaveHello** [comment]
Hello, any updates here? Thanks.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello there is no response from the author since 9 May 2016.
Should we still wait for the author's reply?
Or
Can we minify the file by us and continue this PR?

Thank you.

**Comment by PeterDaveHello** [comment]
@sufuf3 we can try to host it.

**Comment by sufuf3** [comment]
I added this PR into the todo list, here: https://github.com/cdnjs/cdnjs/issues/11170#issuecomment-329140204

**Comment by PeterDaveHello** [comment]
@sufuf3 try to send a new one directly so we can close this one :)

**Comment by sufuf3** [comment]
This lib is a little complicated.
1. This issue in this PR is `compressed` problem, I think https://github.com/CartoDB/cartodb.js/blob/develop/Makefile#L13-L34 `$(UGLIFYJS) dist/cartodb.uncompressed.js > dist/cartodb.js` give us the answer. 
2. the version problem
- GtiHub cartodb.js repo: 
   - version: the latest version is `v4.0.0-beta.9`, stable version is `v4-1.1.2` or `v3.15.12`
- GitHub cartodb.js-bower repo:
   - description: this repo is generated by [`bower.sh`](https://github.com/CartoDB/cartodb.js/blob/develop/bower.sh) from cartodb.js repo.
   - version: the latest version is `v3.15.10`
- npm:
   - version: the latest version is `v3.15.9`

I opened and issue CartoDB/cartodb.js#1993 to request this problem.
Hope we can get the response from upstream, then the lib will be good to be added.
If there is no response a while, I don't know is it good to generate the file by us from GtiHub cartodb.js repo? or maybe we just add the files from GitHub cartodb.js-bower repo and npm.
Thanks.

**Comment by sufuf3** [comment]
@PeterDaveHello one of the member of `CartoDB` [said](https://github.com/CartoDB/cartodb.js/issues/1993#issuecomment-353776046)
> The version v3.15.12 is deprecated and will no longer be maintained.

I think maybe we can just manually add this lib. (before v3.15.12)
But I'm not sure it is a good idea.

Should I manually add this lib recently? Or add this lib after the stable version v4 release?
And I don't know which lib named is good, `cartodb.js` or `carto.js`(maybe the repo name will be changed in future)?

Would you mind giving me some suggestions, please?

Many thanks.

**Comment by sashberd** [comment]
@PeterDaveHello waiting for your suggestion

**Comment by extend1994** [comment]
Reponse: https://github.com/CartoDB/carto.js/issues/1723#issuecomment-402482601

**Comment by sashberd** [comment]
Moved to #13706

**Pull request closed without merging**
