### PR TITLE
Adds new library immstruct

### PR DESCRIPTION
**Pull request by mikaelbr**
Adds new library: Immstruct - https://github.com/omniscientjs/immstruct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
There is no dist directory in its npm package, possible to use git auto-update? thanks.

**Comment by mikaelbr** [comment]
Ah. Sorry. I'll update the npm package with dist. That should do it?

**Comment by PeterDaveHello** [comment]
Would you please squash these 2 commits into only one commit as readme file said? thank you.

**Comment by mikaelbr** [comment]
Fixed. Was having a really hard time with the massive repo size and Sortable package insisting on renaming it self in the terminal and causing a unstaged change on every prompt return. So tried to do git as little as possible. :+1:

**Comment by PeterDaveHello** [comment]
Sorry for the inconvenience, I'm going to merge now!

**Comment by mikaelbr** [comment]
Thanks for your help

**Comment by PeterDaveHello** [comment]
No problem.

**Pull request merged**
