### PR TITLE
Add at.js v1.3.2 with git auto-update, close #5196

### LINKED ISSUE #5196: [Request] Add At.js
**Library name:** At.js
**Git repository url:** https://github.com/ichord/At.js
**npm package url(optional):** 
**Official homepage:**
**Wanna say something? Leave message here:**

### PR DESCRIPTION
**Pull request by Piicksarn**
@maruilian11, this PR is for adding new lib At.js.
Would you please checking this PR for me? 
the information of lib is shown below
https://github.com/ichord/At.js

### CODE REVIEW

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Comment by PeterDaveHello** [comment]
Why don't you tag 5196 in your commit message but manually add it in comment?

**Comment by Piicksarn** [comment]
@maruilian11, i have the commit massage corrected.
and thank you for checking again!

**Comment by Piicksarn** [comment]
i have the commit rebased to master~

**Comment by Piicksarn** [comment]
@maruilian11 would you mind to check it again?
I have it rebased to master :dancer: 
Thank you!

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Comment by PeterDaveHello** [comment]
Totally wrong structure, do both of you not need to check the consistency of the directory/file structure and filemap in auto-update?

**Comment by Piicksarn** [comment]
Excuse me @PeterDaveHello, I have checked the structure and filemap in auto-update.
But i still don't know what the problem is...:fearful:
Could you give me a hint?:disappointed:

**Comment by PeterDaveHello** [comment]
What's the reason why you don't need to put `*.css` under `css` folder?

**Comment by LeaYeh** [comment]
i think it was an expression problem.
i was consider that when i used `**/*` in filemap it would mean automatic add all directory/file with origin structure.

**Comment by PeterDaveHello** [comment]
That's funny, there is no any doc talking about automatically keep structure with origin, filemap is just a set of filename matching.

**Pull request closed without merging**
