### PR TITLE
add jsmediatags v3.0.5 with autoupdate config

### LINKED ISSUE #7072: [Request] Add jsmediatags
**Library name:** jsmediatags
**Git repository url:** https://github.com/aadsm/jsmediatags
**npm package url(optional):**  jsmediatags

### PR DESCRIPTION
**Pull request by dannyxx001**
@PeterDaveHello please help me check this pull request, thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/aadsm/JavaScript-ID3-Reader
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/jsmediatags
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 388
   - Count of watchers: 28
   - Count of forks: 101
 * NPM download stats (optional):
   - Downloads in the last day: 27
   - Downloads in the last week: 56
   - Downloads in the last month: 176

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7072, cc @aadsm

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Looks like it needs manually building:
https://www.npmjs.com/package/jsmediatags#browser

**Comment by PeterDaveHello** [comment]
img missing:
https://github.com/kartik-v/bootstrap-star-rating/blob/v4.0.1/css/star-rating.css

**Comment by aadsm** [comment]
https://github.com/aadsm/JavaScript-ID3-Reader is not the same as https://www.npmjs.com/package/jsmediatags.

jsmediatags is hosted at https://github.com/aadsm/jsmediatags. JavaScript-ID3-Reader is deprecated in favour of jsmediatags.
Let me add a version tag for autoupdate though.

**Comment by PeterDaveHello** [comment]
@aadsm Thanks for your help.

**Comment by PeterDaveHello** [comment]
@dannyxx001 please update your PR to use git auto-update since its author added a version tag for it with pre-built files.

**Comment by dannyxx001** [comment]
@aadsm Thank you.
@PeterDaveHello OK, I have updated it, please help me check again, thanks.

**Pull request merged**
