### PR TITLE
Added spa.js@2.0.1

### PR DESCRIPTION
**Pull request by zhaoda**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
#6163

**Comment by zhaoda** [comment]
There is the problem? @PeterDaveHello

**Comment by maruilian11** [comment]
hi, @zhaoda 
i'm here to help you send the PR

as #6163 mentioned, we hope you not minimize the package.json because we made some rules for package.json format. if you make it one line, the test won't pass.

**Comment by zhaoda** [comment]
hi, @maruilian11 
i have fix format in this PR

**Comment by maruilian11** [comment]
yes, i just saw it, sorry.
because the branch is not latest with out master, you may need to use `git rebase -i HEAD~5` to delete the available commit, then use `git rebase master`.
after that, we hope you resent **one** new commit with right package.json format.
thank you very much.

**Comment by zhaoda** [comment]
ok, let me try.

**Comment by zhaoda** [comment]
It seems that there is already a rebase-merge directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
	git rebase (--continue | --abort | --skip)
If that is not the case, please
	rm -fr "/Users/zhaoda/data/projects/cdnjs/.git/rebase-merge"
and run me again.  I am stopping in case you still have something
valuable there.

**Comment by zhaoda** [comment]
https://github.com/cdnjs/cdnjs/pull/6165

**Pull request closed without merging**
