### PR TITLE
Update version 2.0.2

### PR DESCRIPTION
**Pull request by swcheon**

### CODE REVIEW

**Comment by swcheon** [comment]
Please check this pull request.
jQuery Countdown Git repo is out-of-dated. Latest version -> (2.0.2)
The author of jQuery Countdown uses his Official website instead of Git Repository.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern

**Comment by Piicksarn** [comment]
@swcheon, you need to make some correction on the PR :memo: 
 - **`To retain the structure on cdnjs.`** The link shown below could help you decide which files to added.
https://cdnjs.com/libraries/jquery-countdown/2.0.1
Therefore, you need to add these files only:
  - jquery.countdown.css
  - jquery.countdown.js
  - jquery.countdown.min.css
  - jquery.countdown.min.js
  - jquery.plugin.js
  - jquery.plugin.min.js

 - **`Enrich the commit line.`** The commit should include the library name, so that it could increase readability when maintainer read the log.

Thank you for update the library! :smile: 

@cdnjs/intern, could you make a double check for the PR?Thanks! :facepunch:

**Comment by swcheon** [comment]
@Piicksarn I didn't know that. Thank you for your advice! :)

**Pull request closed without merging**
