### PR TITLE
add ng.ckeditor v2.0.2 w/ git auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
@Amomo @Piicksarn could u help me check this PR for #8798 ? thank you!

**git repo url:** https://github.com/miamarti/ng.ckeditor
**Watch 5
  Star 14
 Fork 8**

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR 
 * [ ] The lib has notable popularity  https://github.com/cdnjs/cdnjs/issues/8798#issuecomment-245563036
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry 
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update) 
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Why don't you use its name "ng.ckeditor" ?

**Comment by Piicksarn** [comment]
**`"name": "ng-ckeditor"`** in the bower.json of the lib

**Comment by PeterDaveHello** [comment]
@Piicksarn We never use bower yet.

**Comment by Piicksarn** [comment]
@PeterDaveHello, 
I realized that we did not use bower.json.
I'd like to confirm that there isn't valuable reference of bower.json?

**Comment by PeterDaveHello** [comment]
@Piicksarn The problem here is about the lib name, we can still use other info.

**Comment by maruilian11** [comment]
@PeterDaveHello because the bower name is `ng-ckeditor`, so I thought the author prefer that name.
@Piicksarn @Amomo I have modify the package name to `ng.ckeditor`, could you help me check this PR, thanks.

**Pull request merged**
