### PR TITLE
[New] Add Blotter@0.1.0 w/ git auto-update

### PR DESCRIPTION
**Pull request by finch185277**
Pull request for issue: #12646

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/bradley/Blotter
 * Official website (optional, not the repository):http://blotter.js.org
 * NPM package url (optional):
 * License and its reference:MIT (https://github.com/bradley/Blotter/blob/master/license.txt)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:33
   - Count of stars:1787
   - Count of forks:69
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [ ] Doesn't already exist / has duplicate issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
 * [x] The parent of the commit(s) in the PR is not older than 3 days.
 * [x] Pull request is sent from a non-master branch with a meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@finch185277 @extend1994 
Sorry for late review
This PR was merged, but I found there are some file need to be minified, aren't they?
Like `ajax/libs/Blotter/0.1.0/materials/liquidDistortMaterial.min.js` ...etc.
What do you think?
Many thanks.

**Comment by extend1994** [comment]
@PeterDaveHello Could you please help minify them, I think it's more efficient than opening another PR,

**Comment by extend1994** [comment]
@sufuf3 You're right. Thanks.
@PeterDaveHello Could you please help minify them, I think it's more efficient than opening another PR, so sorry for the carelessness!

**Comment by PeterDaveHello** [comment]
@extend1994 fine

**Comment by extend1994** [comment]
Thanks a lot!

**Pull request merged**
