### PR TITLE
Update sparse checkout doc to link original doc.

### PR DESCRIPTION
**Pull request by asimkt**
The content was not very self explanative. I added link to the original documentation on sparse checkout.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
This is a symbolic link, not a text file.

**Comment by asim-qb** [comment]
Then I suppose I should close this PR.

**Comment by asimkt** [comment]
Then I think I should close this PR. :)

**Comment by PeterDaveHello** [comment]
@asim-qb Yes, thanks.

**Comment by asim-qb** [comment]
Thanks @PeterDaveHello

**Comment by asimkt** [comment]
@PeterDaveHello Thanks

**Pull request closed without merging**
