### PR TITLE
add jquery-minicolors w/ npm auto-update

### LINKED ISSUE #9063: [Request] Add jquery-minicolors
**Library name:** jquery-minicolors
**Git repository url:** https://github.com/claviska/jquery-minicolors
**npm package url(optional):** https://www.npmjs.com/package/jquery-minicolors

### PR DESCRIPTION
**Pull request by x09326**
PR for #9063 
@pvnr0082t @kennynaoh please help me review it.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/claviska/jquery-minicolors
 * Official website (optional, not the repository):http://labs.abeautifulsite.net/jquery-minicolors/
 * NPM package url (optional):https://www.npmjs.com/package/@claviska/jquery-minicolors
 * GitHub / Bitbucket popularity (required):
   - Count of stars:758
   - Count of watchers:55
   - Count of forks:288
 * NPM download stats (optional):
   - Downloads in the last day:38
   - Downloads in the last week:289
   - Downloads in the last month:1441

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9063, cc @claviska

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@x09326 npm package not working here? You mentioned the npm package but say git in PR title.

**Comment by x09326** [comment]
@PeterDaveHello 
Because the git version is latest version.
And git release versions is more than npm release versions.
So I choose git auto-update.

**Comment by PeterDaveHello** [comment]
@x09326 good point, but if the lib doesn't seem to be abandoned, I think we have the responsibility to remind the author push the latest version to npm.

**Comment by x09326** [comment]
@kennynaoh @pvnr0082t 
I have changed to npm and added old versions from git repo.
Please help me review it, thanks.

**Comment by pvnr0082t** [comment]
@x09326 I think the `js` files you manually minified before `v2.1.0-beta.1` don't need to generate `.map` file because there is official minified `js` file without `.map` after `v2.1.0-beta.1`.

**Comment by x09326** [comment]
@pvnr0082t 
I have removed them.
Please help me review it, thanks.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM

**Comment by kennynaoh** [comment]
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
The map file reference is still in the `min.js`s (`//#sourceMappingURL=jquery.minicolors.min.js.map`), you can not just delete the map file but re-minify them without map option, or you'll need to manually delete all the references to the map files.

**Comment by x09326** [comment]
@pvnr0082t @kennynaoh 
I have removed the ```map``` files and reference.

**Comment by PeterDaveHello** [comment]
@x09326 Have you compared with the result of minify without generating map file?

**Comment by x09326** [comment]
@PeterDaveHello 
Yes, just deleted the reference.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
@kennynaoh can you help double check that? Especially the min file and the map file part, thanks.

**Comment by kennynaoh** [comment]
LGTM

**Comment by kennynaoh** [comment]
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
I saw `jquery.minicolors-min.js` and `jquery.minicolors.min.js` in v2.1.8, is this correct?

**Comment by x09326** [comment]
@PeterDaveHello 
The repo has these two files. [ref](https://github.com/claviska/jquery-minicolors/tree/2.1.8)
Should I remove one of them?

**Comment by PeterDaveHello** [comment]
@x09326 I'll need you to tell us if they are the same first.

**Comment by x09326** [comment]
@PeterDaveHello 
I think they are different.

**Comment by PeterDaveHello** [comment]
@x09326 Even this is valid, this must be very special case, you need to prove that the version is valid first, since it is not common, i don't think we have any version like this yet.

**Comment by x09326** [comment]
@pvnr0082t @kennynaoh 
I have removed ```jquery.minicolors-min.js```.
Please help me review it, thanks.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM
ping @PeterDaveHello

**Pull request merged**
