### PR TITLE
Add git autoupdate config in midi.js.

### PR DESCRIPTION
**Pull request by Piicksarn**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
There is no any git tag in its repo.

**Comment by Piicksarn** [comment]
I have read the README, and will be careful next time.

**Comment by PeterDaveHello** [comment]
You can

1. Close this PR

or 

2. Open an issue in its repo to tell its author and see if the author would like to set tags for them.

**Comment by Piicksarn** [comment]
I've already opened an issue in its repo.

**Comment by PeterDaveHello** [comment]
Can you provide the link in comment?

**Comment by Piicksarn** [comment]
[ Consider adding tags for the repo. #143 ](https://github.com/mudcube/MIDI.js/issues/143)

**Comment by PeterDaveHello** [comment]
Any updates?

**Comment by Piicksarn** [comment]
The author have not added the tags yet, but i think we can wait for it since the author had some activities on this lib recently.

**Comment by PeterDaveHello** [comment]
@Piicksarn what's the reason to close this?

**Pull request closed without merging**
