### PR TITLE
Datepicker update from v0.6.5 to v1.0.3

### PR DESCRIPTION
**Pull request by hgcodes**
Pull request for issue: #13178
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

## Profile of the lib

* Git repository (required): https://github.com/fengyuanchen/datepicker
* Official website (optional, not the repository):
* NPM package url (optional): https://www.npmjs.com/package/@chenfengyuan/datepicker
* License and its reference: MIT
* GitHub / Bitbucket popularity (required):
  * Count of watchers: 40
  * Count of stars: 809
  * Count of forks: 347
* NPM download stats (optional):
  * Downloads in the last day: 180
  * Downloads in the last week: 1421
  * Downloads in the last month: 4964

## Essential checklist

* [ ] I'm the author of this library
  * [ ] I would like to add link to the page of this library on CDNJS on website / readme
* [ ] This lib was not found on cdnjs repo
* [ ] Doesn't already exist / has duplicate issue and PR
* [x] The lib has notable popularity
  * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [x] More than 800 downloads stats per month on npm registry
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [ ] Has valid tags for each versions (for git auto-update)
* [ ] Auto-update setup
* [ ] Auto-update target/source is valid.
* [ ] Auto-update filemap is correct.

## Git commit checklist

* [ ] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [ ] The parent of the commit(s) in the PR is not older than 3 days.
* [x] Pull request is sent from a non-master branch with a meaningful name.
* [ ] Separate unrelated changes into different commits.
* [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [ ] Close corresponding issue in commit message
* [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@sevenveils can you squash the "Changing file from 755 to 644" commits into the ones the files being added? It'll make more sense.
Also, there is a conflicting file: ` ajax/libs/imask/package.json` which shouldn't be touched here.
Can you remove its changes here? Thanks.

**Comment by PeterDaveHello** [comment]
If the rebasing looks too complex to you, it's also fine to create a new branch to overwrite this one :)

**Comment by PeterDaveHello** [comment]
@sevenveils will you consider creating a new branch and cherry-pick only the commits you need, and overwrite this branch with the new one?

**Comment by sevenveils** [comment]
@PeterDaveHello Yes, I will do that. Sorry for the slow reply!

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting pull requests that manually add versioned files for libraries. Instead, please ensure that the library has an up-to-date auto-update config for either NPM or Git in the cdnjs repository.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.

**Pull request closed without merging**
