### PR TITLE
add ember-data.model-fragments v0.3.3 with git autoupdate, close #4717

### LINKED ISSUE #4717: [Request]ember-data.model-fragments
Would you mind adding this library to cdnjs?
https://github.com/lytics/ember-data.model-fragments

Thank you,

### PR DESCRIPTION
**Pull request by maruilian11**
@Amomo could u please help me check this PR for #4717? thank you!
**git repo url :**  https://github.com/lytics/ember-data.model-fragments
**Watch 41
  Star 168
 Fork 36** 
* [x] Not found on cdnjs repo
* [x] No already exist issue and PR
* [x] Notable popularity
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)
* [x] Has valid tags for each versions (for git auto-update)
* [x] Auto-update setup
* [x] Auto-update target/source is valid.
* [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine.
Could you take a look? Thank you~ :-D

**Comment by PeterDaveHello** [comment]
missing map file in commit ...

**Comment by maruilian11** [comment]
@Amomo i have added the missing file, could u help me check it again? thank you very much!

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine.
Could you take a look? thank you~ :-D

**Pull request merged**
