### PR TITLE
[author] [new] Add pusher-angular v0.1.4

### PR DESCRIPTION
**Pull request by hamchapman**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
What happened here @@?

**Comment by hamchapman** [comment]
I'm going to make a new pull request. I was planning on changing package.json to this instead:

{
      "name": "pusher-angular",
      "version": "0.1.4",
      "filename": "pusher-angular.min.js",
      "description": "Angular library for using Pusher",
      "main": "lib/pusher-angular.min.js",
      "autoupdate": {
        "source": "git",
        "target": "git://github.com/pusher/pusher-angular.git",
        "basePath": "/lib/",
        "files": [
          "pusher-angular.min.js",
          "pusher-angular.js"
        ]
      },
      "repository": {
        "type": "git",
        "url": "https://github.com/pusher/pusher-angular.git"
      },
      "keywords": [
        "pusher",
        "angular",
        "websockets"
      ],
      "author": "Hamilton Chapman",
      "homepage": "https://github.com/pusher/pusher-angular"
    }

but the repo became too unstable on my local machine so I killed it all and am just going to remake it.

**Comment by PeterDaveHello** [comment]
What's the diff you want? Maybe I can just merge it and change for you, so it'll be easier for you :)

**Comment by hamchapman** [comment]
I've made a new one here: https://github.com/cdnjs/cdnjs/pull/4212

**Comment by PeterDaveHello** [comment]
okay

**Pull request closed without merging**
