### PR TITLE
[author] [new] pangu 3.0.0

### PR DESCRIPTION
**Pull request by vinta**
- auto-update enabled (npm)
- official homepage: https://github.com/vinta/pangu.js
- npm page: https://www.npmjs.com/package/pangu
- version: 3.0.0

The origin of two new files:
https://github.com/vinta/pangu.js/blob/master/dist/browser/pangu.js
https://github.com/vinta/pangu.js/blob/master/dist/browser/pangu.min.js

Is this ok?

- - -

Fixes vinta/pangu.js#46

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@vinta looks good, would you please do me one more favor? Let's squash these commits into only one commit, many thanks.

**Comment by vinta** [comment]
@PeterDaveHello OK!

**Comment by PeterDaveHello** [comment]
Thanks, please ping me when you are done, and I wonder if you may need sparse-checkout:
https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md

**Comment by PeterDaveHello** [comment]
cc #6682

**Pull request closed without merging**
