### PR TITLE
add cellx with npm auto-update

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #6145 
@pvnr0082t, @x09326 please help me review this pull request, thank you.
Manually add the other versions from npm because it has different file structure before v1.6.0
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/Riim/cellx
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/cellx
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 135
   - Count of watchers: 5
   - Count of forks: 10
 * NPM download stats (optional):
   - Downloads in the last day: 11
   - Downloads in the last week: 3143
   - Downloads in the last month: 10,092

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@kennynaoh I think the reason you add old versions is the file structure changed(there is a `dist` folder after v1.6.0), not file name scheme. Filename like `cellx.js` and `cellx.min.js` has never changed.

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 
I have changed the commit message.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by x09326** [comment]
@kennynaoh 
The latest version ```1.6.50``` is updated on npm.
Please add it.

**Comment by PeterDaveHello** [comment]
@x09326 it's fine since our bot will add it faster way, thanks for your review.

**Comment by PeterDaveHello** [comment]
@x09326 added 184927278c87d2cac73e56fc302d693bf70904a1, i believe that can be much faster than manual updates.

**Pull request merged**
