### PR TITLE
[new] add hint.css@1.3.5 with git auto-update, close #5004

### LINKED ISSUE #5004: [Request] HintCSS
http://kushagragour.in/lab/hint/

### PR DESCRIPTION
**Pull request by Amomo**
Hi @Piicksarn , I add a new lib with git auto-update from the request #5004 
Would you mind checking this PR for me? Thank you~ :-)

### CODE REVIEW

**Comment by Piicksarn** [comment]
@Amomo ~
you should make a check on the target in autoupdate~:)

**Comment by PeterDaveHello** [comment]
Nice catch @Piicksarn !

**Comment by Amomo** [comment]
Oh! @Piicksarn Thank you very much!! I'm too careless!
I have made a correction! Could you check again?

**Comment by Piicksarn** [comment]
It's fine now.
@PeterDaveHello ,would you please take a look for this commit?
Thank you!

**Pull request merged**
