### PR TITLE
[new] add kissy@5.0.2

### PR DESCRIPTION
**Pull request by Amomo**
Hi @Piicksarn 

For #6429, I add kissy at v5.0.2 and add `npm` auto-update config in its package.json.

repo url: https://github.com/kissyteam/kissy
npm package url: https://www.npmjs.com/package/kissy

Would you mind checking this PR for me? Thank you~ :-D
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `206`, Star `2,019`, Fork `853`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by Piicksarn** [comment]
@Amomo, would you going me again after it have rebased to master?
I think the pr is fine.
Thank you and sorry for the delay!

**Comment by PeterDaveHello** [comment]
@Piicksarn tell me how did you review this PR, thanks.

**Comment by Piicksarn** [comment]
@PeterDaveHello, I checkout the main field in package.json for getting the information.

**Comment by PeterDaveHello** [comment]
Not enough, did you check the lib's files?

**Comment by maruilian11** [comment]
@Amomo why we need debug.js?

**Comment by maruilian11** [comment]
@Amomo I can't reach http://kissyui.com, can you?
and please add `.swf` files.

**Comment by Amomo** [comment]
@maruilian11 Ummm... I can't reach it, too. I will replace it to http://docs.kissyui.com/
Thanks for your reviewing, I will add `.swf` files also.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by PeterDaveHello** [comment]
Close due to no response.

**Pull request closed without merging**
