### PR TITLE
add license tablesort , cc #5500

### PR DESCRIPTION
**Pull request by hare1039**
https://github.com/tristen/tablesort/blob/gh-pages/LICENCE

### CODE REVIEW

**Comment by hare1039** [comment]
@kennynaoh please check

**Comment by kennynaoh** [comment]
@hare1039 you can also add this https://github.com/tristen/tablesort#licence as reference next time, and also use more meaningful branch name.
Thanks!

**Comment by kennynaoh** [comment]
LGTM
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
@kennynaoh Duplicated with #9516

**Comment by kennynaoh** [comment]
close due to duplicate PR https://github.com/cdnjs/cdnjs/pull/9516

**Pull request closed without merging**
