### PR TITLE
add minigrid v1.5.0 with git autoupdate, close #5229

### LINKED ISSUE #5229: [Request] Add minigrid
**Library name:** minigrid
**Git repository url:** https://github.com/henriquea/minigrid
**npm package url(optional):** https://www.npmjs.com/package/minigrid
**Official homepage:** http://alves.im/minigrid/
**Wanna say something? Leave message here:**
Keep the good work folks 👊

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by maruilian11**
@Amomo  could u plz help me check this pr from #5229, thx~

### CODE REVIEW

**Comment by Amomo** [comment]
Hi @maruilian11 , I think that you should minify `index.js`, and record it in "requiredFile" field.

**Comment by maruilian11** [comment]
@Amomo but i think "minigrid.min.js" is its minified file, isn't it??

**Comment by PeterDaveHello** [comment]
Let's remove index.js and use minigrid.min.js only.

**Comment by maruilian11** [comment]
@Amomo  could u help me check again, thank you!

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine. Could you take a look? Thank you~

**Comment by PeterDaveHello** [comment]
Thanks.

**Pull request merged**
