### PR TITLE
Replace npm autoupdate with git autoupdate in angular-bindonce. close 4972.

### PR DESCRIPTION
**Pull request by Piicksarn**
@Amomo, I need your help for checking this PR.
The library had released the version 0.3.3 on git, however, the latest version installed from npm autoupdate still in 0.3.1.
In order to the reason, I think it's time to change the npm autoupdate to the git autoupdate for getting the latest version of the library.
Thank you!

### CODE REVIEW

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine.
Could you take a look? thanks~

**Comment by Amomo** [comment]
@Piicksarn I think that you can use `bindonce*.js` in autoupdate config.

**Comment by Piicksarn** [comment]
@Amomo I have it corrected & rebased to master.
I edit the commit to be shorter, since the commit line before is too long.
Would you please check the PR again :^D
Thank you!

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine.
Could you take a look? Thank you!

**Comment by PeterDaveHello** [comment]
You should explain the reason why you wanna transfer this lib to use git auto-update instead of npm.

**Comment by PeterDaveHello** [comment]
I think you can also open an issue in its repository to ping its author to release new versions on npm

**Pull request merged**
