### PR TITLE
Fix license of cytoscape from LGPL to MIT, close #11052

### LINKED ISSUE #11052: cytoscape is MIT licensed
The lib was relicensed from LGPL to MIT.

Entry : https://cdnjs.com/libraries/cytoscape

Lib : https://github.com/cytoscape/cytoscape.js

License : https://github.com/cytoscape/cytoscape.js/blob/master/LICENSE

### PR DESCRIPTION
**Pull request by hare1039**
Pull request for issue: #11052
Related issue(s): # #

@cdnjs/intern3 Please help me review this PR. Thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/cytoscape/cytoscape.js
 * Official website (optional, not the repository): http://js.cytoscape.org
 * NPM package url (optional): https://www.npmjs.com/package/cytoscape
 * License and its reference: MIT, https://github.com/cytoscape/cytoscape.js/blob/master/LICENSE

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@hare1039 maybe the homepage can be also updated?

**Comment by hare1039** [comment]
The homepage url auto redirect to `http://js.cytoscape.org`, which is not `https`, so I didn't change original one.

**Comment by PeterDaveHello** [comment]
@hare1039 the homepage should be just "http://js.cytoscape.org"

**Comment by hare1039** [comment]
OK, I'll create another PR for this.

**Pull request merged**
