### PR TITLE
Update update.json of free jqGrid

### PR DESCRIPTION
**Pull request by OlegKi**
Update `package.json` of [free jqGrid](https://github.com/free-jqgrid/jqGrid).

Fix the structure of directories to better support of JavaScript modules together with the old format, where all module where merged together. One can get advantage of HTTP/2 recently installed on **cdnjs**.

Thanks in advance!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@OlegKi would you please update the first line of your commit message to let other people know what's the library you are talking about? Thanks.

**Comment by OlegKi** [comment]
Sorry, I fixed the text now.

**Comment by PeterDaveHello** [comment]
@OlegKi didn't see the update in your commit, would you please check it again? You'll also need to rebase your branch with our latest master branch, thanks.

**Comment by OlegKi** [comment]
Sorry, but I don't understand what you mean. I need just change some lines of `package.json` to include additional files on CDN (in the future releases of my "free-jqgrid" package). I created the changes of `package.json` and the pull request with respect of web GUI of github.com, thus I don't understand what you mean with rebasing of the master branch. What should I do exactly using the standard github.com GUI? If it's required I can close the pull request and to create another one with the same changes. It should uses the current state of cdnjs repository. What sell I do to apply the changes of the `package.json`? Could you please to answer more detailed?

**Comment by PeterDaveHello** [comment]
@OlegKi ,

The first line of your current commit https://github.com/cdnjs/cdnjs/pull/7437/commits/83883044a0df43ef93369d47ac4e16f6c8b081e4 is 	`Update update.json`, I'll need you to make it more accuracy and easy to understand what's the library you meant in the commit message. AFAIK, you can not modify your commits from the GUI, also can not rebase the branch from GUI, the easiest way for you may be just to delete your forked cdnjs repo, and refork it, redo a commit with better commit message, that's all. Hope this help you!

**Comment by OlegKi** [comment]
Thank you for the explanation. I'll close the pull request and recreate the new one taking in consideration of your recommendations.

**Comment by PeterDaveHello** [comment]
@OlegKi Thank you.

**Comment by OlegKi** [comment]
I posted new pool request [here](https://github.com/cdnjs/cdnjs/pull/7462). I hope it's in order now.

**Comment by PeterDaveHello** [comment]
@OlegKi Ok, i will take a look at it later.

**Pull request closed without merging**
