### PR TITLE
Fix Shaka Player version numbers

### PR DESCRIPTION
**Pull request by joeyparrish**
This corrects the release numbers in Shaka Player v2.0.3, v2.0.4, and
v2.1.3.

Closes google/shaka-player#869

# Essential checklist
 * [X] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [X] No already exist / duplicated issue and PR
 * [X] The lib has notable popularity
   * [X] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [X] More than 500 downloads stats per month on npm registry
 * [X] Project has public repository on famous online hosting platform (or been hosted on npm)

# Git commit checklist
 * [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X] The parent of the commit(s) in the PR is not old than 3 days.
 * [X] Pull request is sending from a non-master branch with meaningful name.
 * [X] Separate unrelated changes into different commits.
 * [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message  **(can't, the issue is in another repo)**
 * [X] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@joeyparrish I'm afraid that this can't be done as we enabled SRI already and this change would make the current users' website broken, if it's only about version number, maybe we don't really need to touch it?

**Comment by joeyparrish** [comment]
I'm not familiar with SRI.  What would break if we merged this PR?

**Comment by PeterDaveHello** [comment]
@joeyparrish Just think SRI is kind of checksum, the modified files would have different hashes so that the old would not work.

Ref: https://www.w3.org/TR/SRI, https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by joeyparrish** [comment]
I see.  So based on that MDN article, if we change these files that have already gone out, they may appear to be malicious changes.  Do I understand you correctly?

**Comment by PeterDaveHello** [comment]
@joeyparrish yes, that's why we shouldn't touch the published files.

**Comment by joeyparrish** [comment]
Okay, understood.  I'll close this now.  Thank you for your feedback.

**Comment by PeterDaveHello** [comment]
@joeyparrish Thanks.

**Pull request closed without merging**
