### PR TITLE
add simditor v2.3.6 with npm auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
**npm package url:** https://www.npmjs.com/package/simditor
**git repo url:** https://github.com/mycolorway/simditor
**Watch 165
  Star 2,393
 Fork 513**
@Amomo could u help me check this PR for #7371 ? thank you!
**i also add 3 libs (simple-module, simple-hotkeys, simple-uploader) depended on this lib but not hosted on cdnjs, those 3 libs are also create by mycolorway team.**
https://github.com/mycolorway/simple-module
https://github.com/mycolorway/simple-hotkeys
https://github.com/mycolorway/simple-uploader
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR 
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by Amomo** [comment]
Umm...I don't think it is a good idea to contain those dependent lib by using a `node_modules/` folder.

Maybe we can also host them as an independent lib on cdnjs.
Using __separate commits__ and a __related lib name__ like "mycolorway-simple-module"...

cc @PeterDaveHello , Could you give us some advice?

**Comment by PeterDaveHello** [comment]
Obviously bad idea.

**Comment by PeterDaveHello** [comment]
Ping

**Comment by maruilian11** [comment]
I think we can add those 3 libs independently to cdnjs.

**Comment by maruilian11** [comment]
@farthinker I found there is a v0.2.0 of `simple-hotkeys` in npm package, but v0.2.0 is not on github repo, does this version also need to be hosted on cdnjs? thank you.

**Comment by maruilian11** [comment]
@Piicksarn since 3 dependencies has been added to cdnjs, I rebase the commit upon our latest master branch, could you help me check this PR? thanks!

**Pull request merged**
