### PR TITLE
Add ryejs@0.1.3 w/ npm auto-update

### LINKED ISSUE #9185: [Request] Add rye
**Library name:** rye
**Git repository url:** https://github.com/ryejs/rye
**npm package url(optional):** https://www.npmjs.com/package/ryejs
**License(s):** [ISC](https://github.com/ryejs/rye/blob/master/LICENSE)
**Official homepage:** http://ryejs.com
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #9185 
Related issue(s): #9429 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/ryejs/rye
 * Official website (optional, not the repository): http://ryejs.com/
 * NPM package url (optional): https://www.npmjs.com/package/ryejs
 * License and its reference:  [ISC](https://github.com/ryejs/rye/blob/master/LICENSE)
 * GitHub / Bitbucket popularity (required): 
   - Count of watchers: 19
   - Count of stars: 263
   - Count of forks: 19
 * NPM download stats (optional):
   - Downloads in the last day: 1
   - Downloads in the last week: 16
   - Downloads in the last month: 82

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by extend1994** [comment]
@cdnjs/intern3 Please help me review this pull request, thank you.
Note we don't need v0.1.0 ([ref](https://github.com/cdnjs/cdnjs/pull/9429#issuecomment-283970294)) and I didn't generate map file to keep consistent file structure because in v0.1.2 there is only minified file (no map file).

**Comment by WesleydeSouza** [comment]
@sufuf3 versions prior to 0.1.3 were in a bad license state, so 0.1.3 would be the only version hosted so far.

Also, versions prior to 0.1.0 were not actually built/released on npm.

**Comment by PeterDaveHello** [comment]
@WesleydeSouza thanks

**Comment by sufuf3** [comment]
@WesleydeSouza thank you.

**Comment by extend1994** [comment]
@WesleydeSouza So the only version we need is v0.1.3, right?

**Comment by WesleydeSouza** [comment]
@extend1994 correct.

**Comment by PeterDaveHello** [comment]
@extend1994 there are 4 versions on npm, 0.1.0 is the earliest one.

**Comment by extend1994** [comment]
@WesleydeSouza Thanks! :+1: 
@PeterDaveHello Yes, but according to the author, I think we only need the latest version?

**Comment by PeterDaveHello** [comment]
@extend1994 Yes, let's ignore the old versions.

**Comment by extend1994** [comment]
@clairetsai818 @sufuf3 Please help me review it, thank you.

**Comment by extend1994** [comment]
@sufuf3 Yes I think so and therefore I modified the commit message, please help me review it, thank you.
ping @clairetsai818

**Pull request merged**
