### PR TITLE
[new]knockout-postbox

### PR DESCRIPTION
**Pull request by davidbroadfoot**

### CODE REVIEW

**Comment by davidbroadfoot** [comment]
Sourced from https://github.com/rniemeyer/knockout-postbox/blob/master/build/knockout-postbox.js

**Comment by PeterDaveHello** [comment]
Please squash these commits into only one commit as our document said, thanks!

**Comment by drewfreyling** [comment]
Also, you shouldn't have grabbed the file from master either.  Use one of the git tags instead.

**Comment by PeterDaveHello** [comment]
@drewfreyling is right!

**Pull request closed without merging**
