### PR TITLE
[New] Add fakeLoader.js@1.1.0 w/ git auto-update

### LINKED ISSUE #8337: [Request] Add fakeLoader.js
**Library name:** fakeLoader.js 
**Git repository url:** https://github.com/joaopereirawd/fakeLoader.js.git
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://joaopereirawd.github.io/fakeLoader.js/
**Wanna say something? Leave message here:**

### PR DESCRIPTION
**Pull request by sufuf3**
close #8337, close #8360

Pull request for issue: #8337
Related issue(s): #8360 #11170

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository url: https://github.com/joaopereirawd/fakeLoader.js.git
 * npm package url(optional):
 * License(s): MIT
 * Official homepage: http://joaopereirawd.github.io/fakeLoader.js/
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:35
   - Count of stars:513
   - Count of forks:205
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@extend1994 I minified the fakeLoader.css
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@dakshshah96 @hare1039 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@cdnjs/library-reviewer 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@hare1039 @qwe19272375 @pvnr0082t @maruilian11 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@hare1039 @qwe19272375 @pvnr0082t @maruilian11
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@hare1039 @qwe19272375 @pvnr0082t @maruilian11
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
I removed `fakeLoader.min.css` and `fakeLoader.min.css.map`, And rerun `~/web-minify-helper/minify.sh --no-map` again to generate the `fakeLoader.min.css`.
Please help me review this PR, Thank you.

**Comment by PeterDaveHello** [comment]
@sufuf3 please take a look at private message, thx.

**Comment by sufuf3** [comment]
@cdnjs/intern3 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@pvnr0082t @maruilian11 
Please help me review this PR, Thank you.

**Comment by PeterDaveHello** [comment]
@extend1994 see the minified js file.

**Comment by sufuf3** [comment]
@pvnr0082t @maruilian11
Please help me review this PR, Thank you.

**Comment by PeterDaveHello** [comment]
@sufuf3 looks like the origin PR is just waiting for popularity? In this situation, I think we just help finish the origin one, thanks.

**Pull request merged**
