### PR TITLE
[new][author] HIW JavaScript API v5.0.0-beta.0 and v5.0.1-beta.0

### PR DESCRIPTION
**Pull request by JoshMcCullough**
HIW JavaScript API v5.0.0-beta.0 and v5.0.1-beta.0

https://github.com/HealthIndicators/js-api
http://developers.healthindicators.gov

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I don't think we support ts type of file, what's that for?

**Comment by JoshMcCullough** [comment]
ts == TypeScript - a superset of JavaScript.

**Comment by PeterDaveHello** [comment]
@terinjokes, can we support that? I think we didn't.

**Comment by PeterDaveHello** [comment]
BTW, @JoshMcCullough, would you please provide a production version here?

**Comment by JoshMcCullough** [comment]
@PeterDaveHello The ts files are meant to be useful to users who are using TypeScript already and want the intellisense, typing, etc. of the HIW API. I've only included the TypeScript Definition (*.ts.d) files which are basically just "interface definitions", not the source code.

**Comment by JoshMcCullough** [comment]
@PeterDaveHello There is no "production" version yet - should I wait until we're out of beta to publish to CDNJS?

**Comment by PeterDaveHello** [comment]
The problem is that we don't support it. You can not access the file via our cdn.

**Comment by JoshMcCullough** [comment]
@PeterDaveHello No problem. I'll remove the `.d.ts` files and create a new pull request.

**Comment by JoshMcCullough** [comment]
@PeterDaveHello Updated PR is #4639 - thanks for your help!

**Pull request closed without merging**
