### PR TITLE
update canvas-nest.js npm file

### PR DESCRIPTION
**Pull request by hustcc**
for issue #6590 .

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@hustcc would you please send the PR from a non-master branch? Thanks.

**Comment by hustcc** [comment]
@PeterDaveHello I just do not know how to create branch with Git GUI tool. :cry:

**Comment by PeterDaveHello** [comment]
@hustcc Take a look: https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/

**Comment by hustcc** [comment]
OK, then I send the PR from `ForkRepo:update-canvas-nest` to `cdnjs:master` ?

**Comment by PeterDaveHello** [comment]
@hustcc Correct!

**Comment by hustcc** [comment]
Another PR has been sent.

**Pull request closed without merging**
