### PR TITLE
Add license of cuff,cc #9248

### PR DESCRIPTION
**Pull request by dada0423**
https://github.com/sorccu/cufon/blob/master/LICENSE.txt

### CODE REVIEW

**Comment by kennynaoh** [comment]
LGTM
@cdnjs/intern2

**Comment by pvnr0082t** [comment]
@dada0423 It's not easy to know the license is MIT in this `License` file. You can also paste the http://cufon.shoqolate.com/generate/ as reference next time.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by pvnr0082t** [comment]
@dada0423 You can create branch with meaningful name next time. :+1:

**Comment by pvnr0082t** [comment]
@dada0423 It's cufon, not cuff. Be careful next time.

**Pull request merged**
