### PR TITLE
add react-datagrid@2.1.2 w/ npm auto-update

### LINKED ISSUE #9873: [Request] Add react-datagrid
**Library name:** react-datagrid
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/40544647-request-add-react-datagrid?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by dada0423**
close #9873, cc@zippyui-react

Pull request for issue: #
Related issue(s): # #9873 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/zippyui/react-datagrid
 * Official website (optional, not the repository):http://zippyui.github.io/react-datagrid
 * NPM package url (optional):https://www.npmjs.com/package/react-datagrid
 * License and its reference:MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:48
   - Count of stars:877
   - Count of forks:139
 * NPM download stats (optional):
   - Downloads in the last day:24
   - Downloads in the last week:1745
   - Downloads in the last month:6726

# Essential checklist
 * [ ] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by dada0423** [comment]
@pvnr0082t please help me to review.thanks

**Comment by dada0423** [comment]
please review

**Comment by pvnr0082t** [comment]
@dada0423 You should tag me and be polite. review what? You still not fix all the problem.

**Comment by PeterDaveHello** [comment]
Ping

**Comment by pvnr0082t** [comment]
ping @dada0423

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello Can we close this PR?
Because I am working on it.
Thank you.

**Comment by sufuf3** [comment]
Not sure is it good to close this PR, because I am working on it.
@PeterDaveHello Would you mind taking a look?
Many thanks.

**Pull request closed without merging**
