### PR TITLE
[new] Adding jquery-datepicker-skins

### PR DESCRIPTION
**Pull request by elvisguillen**
Adding the Jquery Datepicker Skins library and assets. Had to minify css manually so I didn't add the npm git autoupdate to the package file.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
We still need to use auto-update even no minified files there, so please add it, thanks.

**Comment by PeterDaveHello** [comment]
no response?

**Comment by elvisguillen** [comment]
I'm reforking now and will implement the auto-update to the package file.

**Comment by PeterDaveHello** [comment]
Okay, thanks.

**Comment by drewfreyling** [comment]
Closing due to a lack of tags in git repo.

**Pull request closed without merging**
