### PR TITLE
[author][new] scregal v1.0

### PR DESCRIPTION
**Pull request by kunass2**
This is my first library in cdnjs

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
There is no `dist` under your project @kunass2, would you please fix it? Thanks.

**Comment by kunass2** [comment]
So, my scraggly is in cdnjs or not? I'm looking it for on the website, but i didn't find it

**Comment by PeterDaveHello** [comment]
Is in, should wait for about 15 mins, but you should fix this for future release.

**Comment by kunass2** [comment]
ok, thank You. I will fix it. I will replace "list" with "". Will it be ok?

**Comment by PeterDaveHello** [comment]
sorry, what do you mean replace `list` here?

**Comment by kunass2** [comment]
"basePath": "dist" --> "basePath": "",

**Comment by PeterDaveHello** [comment]
Yeah, it's okay.

**Pull request merged**
