### PR TITLE
Add bundle files to d3fc [author]

### PR DESCRIPTION
**Pull request by chrisprice**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@chrisprice you should not change the filename until new version been added.

**Comment by chrisprice** [comment]
Sorry didn't realise.

**Comment by chrisprice** [comment]
(updated)

**Comment by PeterDaveHello** [comment]
Can you squash them into only one commit as our document says? Or if you don't mind, let me take it as an issue, and I'll do the changes for this lib, thanks!

**Comment by chrisprice** [comment]
Happy for you to take it as an issue, thanks!

**Comment by PeterDaveHello** [comment]
v1.5.0 added here: https://github.com/cdnjs/cdnjs/commit/36cb48fd66ca151f0631ecaedab5646a0409a4f4
Do you still wanna change its main file? Thanks.

**Comment by chrisprice** [comment]
Yes please, that was the release I was trying to get the change in for. I'm
not at a computer till tomorrow but can put the PR in then?

**Comment by PeterDaveHello** [comment]
Done https://github.com/cdnjs/cdnjs/commit/5010da1062f7c9d2ab4f3d3532dbbc7cba8c2564#diff-bbf9f97e144b343dd702a023dbd865dfR4

**Comment by chrisprice** [comment]
Great, than you very much!

**Comment by PeterDaveHello** [comment]
np

**Pull request closed without merging**
