### PR TITLE
Add TimeMe.js v1.2.0 with git auto-update

### LINKED ISSUE #7576: [Request] Add TimeMe.js
**Library name: TimeMe.js** 
**Git repository url: https://github.com/jasonzissman/TimeMe.js**
**License(s): Apache License**
**Official homepage: http://jasonzissman.com/timeme/index.html**

### PR DESCRIPTION
**Pull request by x09326**
PR for #7576 
@dannyxx001 please help me review this PR, thanks.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/jasonzissman/TimeMe.js
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 65
   - Count of watchers: 5
   - Count of forks: 14
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7576, cc @jasonzissman

### CODE REVIEW

**Comment by dannyxx001** [comment]
I see it has a website for demo. I think it can be put as homepage.

**Comment by PeterDaveHello** [comment]
Demo page !== home page, but it's good to confirm with its author.

**Comment by jasonzissman** [comment]
Hi guys - not fully knowing what you are expecting from a 'home page', and
all other things being even, the github page (
https://github.com/jasonzissman/TimeMe.js) would probably best be used as
the home page.  It ultimately will be kept up to date better than my
website.  Thanks!

On Wed, Apr 27, 2016 at 7:56 AM, Peter Dave Hello <notifications@github.com>
wrote:

> Demo page !== home page, but it's good to confirm with its author.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cdnjs/cdnjs/pull/7724#issuecomment-215073329>
>



-- 
- Jason Christopher Zissman

**Comment by PeterDaveHello** [comment]
@jasonzissman thanks. So we don't need to add `homepage` field, since the default is the repo.

**Comment by dannyxx001** [comment]
Then I think this PR is OK. @PeterDaveHello please review again, thanks.

**Pull request merged**
