### PR TITLE
[New] Add cta.js@0.3.2 w/ git auto-update

### PR DESCRIPTION
**Pull request by iamstratos**
Pull request for issue: #11889 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/chinchang/cta.js
 * Official website (optional, not the repository): http://kushagragour.in/lab/ctajs
 * NPM package url (optional): https://www.npmjs.com/package/cta
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 54
   - Count of stars: 1,550
   - Count of forks: 150
 * NPM download stats (optional):
   - Downloads in the last day: 1
   - Downloads in the last week: 10
   - Downloads in the last month: 46

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by iamstratos** [comment]
@sufuf3 hey, can you help me here please?

I get ttis issue but I don't understand why:

```
✗ cta.js: format check 
131s
51
        » cta.js: package.json wrong indent, please use 2-spaces as indent, remove trailing spaces, you can use our tool: tools/fixFormat.js to fix it for you
```
I have removed trailing spaces with Sublime Text. I don't know how to use fixFormat.js thought.

**Comment by sufuf3** [comment]
@iamstratos It's some problem with file format. 
We need to remove `^M` in the end of every line.
Would you try to remove it?
Or maybe can try in GitHub website (Not sure is it good way to fix)

What do you think?
Thanks for your contribution.

**Comment by sufuf3** [comment]
@cdnjs/active-contributor @cdnjs/intern3 @cdnjs/library-reviewer 
Please help review this PR, Thank you.

**Comment by PeterDaveHello** [comment]
@iamstratos well done and thanks for your contribution 👍

**Pull request merged**
