### PR TITLE
Manually add every version of abcjs

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #10842
Related issue(s): paulrosen/abcjs#79

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/paulrosen/abcjs
 * License and its reference: [MIT](https://github.com/paulrosen/abcjs/blob/master/LICENSE.md)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 33
   - Count of stars: 239
   - Count of forks: 55

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by extend1994** [comment]
@cdnjs/intern3 Please review this pull request,thank you. Also note that the license should be MIT because you can see it in `License: The MIT License (MIT)` in README.md and LICENSE.md. Not `GPL v3` in https://abcjs.net/#can-i.

**Comment by maruilian11** [comment]
@clairetsai818 Why we need versions before `3.1.1`? I think you have confirmed that with the author, haven't you?

**Comment by extend1994** [comment]
@pvnr0082t the author just answered that the license is MIT in paulrosen/abcjs#79.
@maruilian11 The files of this lib include lib version. So Peter asked me to manually add all versions in `bin` directory.
Please help me review again then I will rebase, thanks.

**Comment by extend1994** [comment]
@sufuf3 I modified the filenames, please help me review it, thanks.

**Comment by PeterDaveHello** [comment]
@sufuf3 @extend1994 can you please make the discussion more clear? Nobody knows how's the rename going in this thread.

**Comment by maruilian11** [comment]
@extend1994 
>>>
You don't need a version before 3.1.1. Since the files weren't available on the CDN before, there isn't a reason to support the old versions.

I'm not sure what to do about the rest of this. You could use the 3.1.1 files and rename to remove the "3.1.1". There isn't a package.json file that goes with this, so you'd have to create it.

**Comment by PeterDaveHello** [comment]
@maruilian11 why don't we? We always add old versions.

**Comment by maruilian11** [comment]
@extend1994 
>You don't need a version before 3.1.1. Since the files weren't available on the CDN before, there isn't a reason to support the old versions.

>I'm not sure what to do about the rest of this. You could use the 3.1.1 files and rename to remove the "3.1.1". There isn't a package.json file that goes with this, so you'd have to create it.

Doesn't it mean we only need to add `3.1.1`?
https://github.com/paulrosen/abcjs/issues/79#issuecomment-290241953
https://github.com/paulrosen/abcjs/commit/a06a1c8d07071fa9df5f54f1459d409157f141c8

**Comment by PeterDaveHello** [comment]
@maruilian11 author of abcjs doesn't operate cdnjs ... we host all the working versions.

**Comment by maruilian11** [comment]
@PeterDaveHello hmmm.. I thought he means those files don't work in browser...

**Comment by PeterDaveHello** [comment]
@maruilian11 I didn't see it. Review the remaining parts please.

**Comment by maruilian11** [comment]
@extend1994 why name `abcjs_basic_latest-min.js` --> `abcjs_basic_midi-min.js`?

**Comment by PeterDaveHello** [comment]
@maruilian11 you compared its content?

**Comment by maruilian11** [comment]
@PeterDaveHello `abcjs_basic_latest-min.js` is different from `abcjs_basic_3.1.1-min.js`. I just wonder why add `midi` for it.

**Comment by PeterDaveHello** [comment]
@maruilian11 isn't there a naming with midi? So you don't know what the file is?

**Comment by maruilian11** [comment]
hmmm I saw it said it's `midi.js`.

**Comment by maruilian11** [comment]
Don't we also need to add `abcjs_basic_2.1b1-min.js`?

**Comment by PeterDaveHello** [comment]
@maruilian11 yeah maybe, just make sure we already added the correct things first and I want this be merged today. We can add more later.

**Comment by maruilian11** [comment]
@PeterDaveHello except that, I think this PR is fine.

**Comment by PeterDaveHello** [comment]
@maruilian11 so what's the problem you mentioned? not a problem?

**Comment by maruilian11** [comment]
You means old versions compatibility with browser?

**Comment by PeterDaveHello** [comment]
@maruilian11 no ... filename ...

**Comment by maruilian11** [comment]
you mean this one I mentioned?
https://github.com/cdnjs/cdnjs/pull/11017#issuecomment-293316869

**Comment by PeterDaveHello** [comment]
@maruilian11 of course

**Comment by maruilian11** [comment]
Just checked `abcjs_basic_latest-min.js`'s content. It's same as `abcjs_basic_3.1.1-min.js `, so I think it's fine.

**Comment by PeterDaveHello** [comment]
@maruilian11 so what the problem was? I think you say it named wrong?

**Comment by maruilian11** [comment]
@PeterDaveHello Because I saw @extend1994 rename `abcjs_basic_latest-min.js` --> `abcjs_basic_midi-min.js`, I thought it was wired. I thought `abcjs_basic_latest-min.js` and `abcjs_basic_3.1.1-min.js` should be the same file, so I thought `abcjs_basic_latest-min.js`  should rename `abcjs_basic-min.js`. But After I checked `abcjs_basic_latest-min.js`'s content, I found it is similar with `abcjs_basic_midi-min.js` of old versions. And `abcjs_basic_latest-min.js` and `abcjs_basic_midi_3.1.1-min.js` have the same content, So I think rename `abcjs_basic_latest-min.js`  --> `abcjs_basic_midi-min.js` is right.

https://github.com/paulrosen/abcjs/blob/master/bin/abcjs_basic_latest-min.js#L2

**Comment by PeterDaveHello** [comment]
So how do you confirm the rename? By checksum? Your statement looks wired, @extend1994 can you please explain and confirm?

**Comment by maruilian11** [comment]
git will check the rename for me.

**Comment by PeterDaveHello** [comment]
"How"?

**Comment by extend1994** [comment]
For the version I created this PR (v3.1.1). First I classify the files by version (in their filename). For instance, `abcjs_basic_1.1-min.js`, `abcjs_editor_1.1-min.js` and so on would be under `1.1` directory. Second, I eliminated the version number in the filenames. For example, `abcjs_basic_1.1-min.js` -> `abcjs_basic-min.js`.
As for those files whose filename involving "latest" (like `abcjs_editor_latest-min.js`), I just removed them because I think every time there is a new release, the content of it will change.
So sorry for late reply!

**Comment by maruilian11** [comment]
@PeterDaveHello 
1. fetch @extend1994 's branch
2. remove all files in `abcjs`
3. put origin files with version number in `abcjs`
4. git add all files
5. check git status

**Pull request merged**
