### PR TITLE
add form-serializer v2.5.0

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/macek/jquery-serialize-object
**Watch 35
  Star 571
 Fork 147**
@Amomo could u help me check this PR for #6194 ? thank you!
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
git repo url: https://github.com/macek/jquery-serialize-object?

**Comment by PeterDaveHello** [comment]
You used two different names here ... let's use jquery-serialize-object.

**Comment by maruilian11** [comment]
@PeterDaveHello i make some mistake, we already have this lib.
i have sent new commits.

**Comment by PeterDaveHello** [comment]
Bad PR title.

**Comment by maruilian11** [comment]
sorry, forgot to change.

**Pull request merged**
