### PR TITLE
added 1.0.0 from https://github.com/firebase/angularFire

### PR DESCRIPTION
**Pull request by akush**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please also add npm or git auto-update config as readme file or #3638 said, and I think your local branch is a little bit too old, would you please also sync/rebase with our latest master branch as our document said? thanks.

**Comment by akush** [comment]
added auto updater info and rebased.

**Comment by PeterDaveHello** [comment]
commit b422b479b32990f5d846f05b6677eaeb7dfb89b3's parent was more than 2 weeks ago, did you use force push to overwrite the rebased branch? If not, I think you should.

**Comment by drewfreyling** [comment]
Please squash to one commit.

**Comment by drewfreyling** [comment]
Closing due to no response.

**Pull request closed without merging**
