### PR TITLE
Add license of screenfull.js, cc #9248

### PR DESCRIPTION
**Pull request by emmy41124**
https://github.com/sindresorhus/screenfull.js/blob/gh-pages/license

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@emmy41124 Please give a meaningful branch name next time. Thanks.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by nolsherry** [comment]
@emmy41124 , please tag me next time after you sent the PR, thanks!

**Comment by nolsherry** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM

**Pull request merged**
