### PR TITLE
[new][author] Added webSqlTracer library

### PR DESCRIPTION
**Pull request by viskin**
Origin of the file: https://github.com/terikon/webSqlTracer.git
File name: webSqlTracer.js
There's no minified file, but the library is pretty small.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
As the first time you add a lib, real file(s) will be needed, and minified file(s) will be also needed, if you want, there is a easy script to help you minify it : https://github.com/PeterDaveHello/web-minify-helper

**Comment by viskin** [comment]
Ok, I will add minification to library's build process and contact you.

**Comment by PeterDaveHello** [comment]
Thanks.

**Comment by viskin** [comment]
Hi, after some struggle with squashing in git, deleted and added all the files anew in ba6cdf7.
minified library added.
real files are added.

**Comment by viskin** [comment]
Hi, after some struggle with squashing in git, deleted and added all the files anew in ba6cdf7.

- minified library added as asked.
- real files are added as asked.

**Comment by PeterDaveHello** [comment]
Hi @viskin, I'll still need you to squash these commits, or you can consider to send a new PR?

**Comment by viskin** [comment]
Ok, I'll prepare a new PR.

**Comment by PeterDaveHello** [comment]
Thanks.

**Pull request closed without merging**
