### PR TITLE
jquery-domPath merge sync2

### PR DESCRIPTION
**Pull request by asatour**

### CODE REVIEW

**Comment by asatour** [comment]
what's the matter here?

**Comment by asatour** [comment]
Hi, What's the next step? or it will be merged automatically from your side, will I get a notification for that?

Thanks in advance

**Comment by PeterDaveHello** [comment]
Should fix the error in CI build log, thanks.

**Comment by PeterDaveHello** [comment]
I'll respectfully suggest you to check the document, seems the PR didn't follow any of our conventions.

**Comment by asatour** [comment]
I did, and there is no error left

**Comment by PeterDaveHello** [comment]
Should squash all the commits into only one commit, thanks.

**Comment by drewfreyling** [comment]
Closing due to no lack of popularity and no response from @asatour

**Pull request closed without merging**
