### PR TITLE
add mobile-angular-ui with npm auto-update

### LINKED ISSUE #8404: [Request] Add mobile-angular-ui
**Library name:** mobile-angular-ui
**Git repository url:** [github-link](https://github.com/mcasimir/mobile-angular-ui)
**npm package url(optional):** [npm-link](https://www.npmjs.com/package/mobile-angular-ui)
**License(s):** [license-link](https://github.com/mcasimir/mobile-angular-ui/blob/master/LICENSE)
**Official homepage:** [homepage](http://mobileangularui.com/)
**Wanna say something? Leave message here:** 

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8404
@kennynaoh @x09326 Please help me review this pull request, thank you.
Manually add the other versions from git repo because npm auto-update can't get some of the old versions

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/mcasimir/mobile-angular-ui
 * Official website (optional, not the repository):  http://mobileangularui.com/
 * NPM package url (optional): https://www.npmjs.com/package/mobile-angular-ui
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 2662
   - Count of watchers: 248
   - Count of forks: 701 
 * NPM download stats (optional):
   - Downloads in the last day: 14
   - Downloads in the last week: 128
   - Downloads in the last month: 633

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8404, cc @mcasimir

### CODE REVIEW

**Comment by kennynaoh** [comment]
@PeterDaveHello 
Because there has the other PR https://github.com/cdnjs/cdnjs/pull/8419 to add the same library.
What should we do?

**Comment by PeterDaveHello** [comment]
That PR has no response for a while, this PR should also close that one.

**Comment by kennynaoh** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Pull request merged**
