### PR TITLE
Updated Fluidbox

### PR DESCRIPTION
**Pull request by terrymun**
Removed the merge commit from the master branch (should've used rebase, but totally forgot). So now there is only one commit and should be a clean PR.

Thanks guys! :+1:

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
cc #5954

**Comment by terrymun** [comment]
@PeterDaveHello Thanks Peter :)

**Comment by PeterDaveHello** [comment]
@terrymun Thank you too.

**Comment by PeterDaveHello** [comment]
@terrymun I just found that the structure was wrong. I think you should put the css and its map file under a css folder and so does js file, just like the structure in your dist folder.

**Comment by terrymun** [comment]
Alright. Should I submit another PR then? Just to modify package.json and add the map files to the respective folders.

**Comment by PeterDaveHello** [comment]
I just add the correct structure in, and leave the wrong one alone to prevent breaking current usage. There will be only correct one in next release.

**Comment by PeterDaveHello** [comment]
Also updated the filemap for this lib:
https://github.com/cdnjs/cdnjs/commit/566381137c55c22b2ef7bd7d4c8f3283838d0120
```diff
@@ -34,8 +34,7 @@
     "target": "git://github.com/terrymun/Fluidbox.git",
     "basePath": "dist",
     "files": [
-      "**/*.min.js",
-      "**/*.min.css"
+      "**/*"
     ]
   },
   "repository": {
```

**Comment by terrymun** [comment]
Thanks Peter! But does that mean I can't make a PR to pull the map files in?

**Comment by PeterDaveHello** [comment]
I think I added, so why do you need to add it?

**Comment by terrymun** [comment]
But the map files are not in the PR I made... or would that be updated automatically?

**Comment by PeterDaveHello** [comment]
I added in the right place:　https://github.com/cdnjs/cdnjs/commit/65645474156e1bec59a43c3368ba522fb47fa951
For the wrong place, I think we can just leave it alone.

**Pull request merged**
