### PR TITLE
[new] [author] add ngOfficeUiFabric@0.2.0

### PR DESCRIPTION
**Pull request by andrewconnell**
Adding [ngOfficeUiFabric](https://github.com/ngOfficeUIFabric/ng-officeuifabric) ... available on [npm](https://www.npmjs.com/package/ng-office-ui-fabric), [bower](https://github.com/ngOfficeUIFabric/package-ngofficeuifabric) or [nuget](https://www.nuget.org/packages/ng-office-ui-fabric)

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch** 23, **Star** 118, **Fork** 16
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

Adding the library [ngOfficeUiFabric](https://github.com/ngOfficeUIFabric/ng-officeuifabric) with auto-update in config, including current release (0.2.0) & -1 release (0.1.3). 

The `package.json` within this PR points the autoupdate to a different repo, [package-ngofficeuifabric](https://github.com/ngOfficeUIFabric/package-ngofficeuifabric), used for distributing the built library via npm, bower & nuget. 

The library source that everyone follows, logs issues, roadmap, etc is https://github.com/ngOfficeUIFabric/ng-officeuifabric (118 stars at the time I'm submitting this PR). We keep the source & distribution repos separate for smaller distributions.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Thanks @andrewconnell

**Comment by PeterDaveHello** [comment]
I will transfer it to use more efficient npm auto-update later

**Comment by PeterDaveHello** [comment]
* be1c536 transfer ngOfficeUiFabric to use npm auto-update

**Comment by andrewconnell** [comment]
Thank you! :+1:

**Comment by PeterDaveHello** [comment]
@andrewconnell no problem

**Pull request merged**
