### PR TITLE
Add rison w/ npm auto-update via single package.json

### PR DESCRIPTION
**Pull request by finch185277**
Pull request for issue: #11505
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/Nanonid/rison
 * Official website (optional, not the repository):
 * NPM package url (optional):https://www.npmjs.com/package/rison
 * License and its reference:MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:3
   - Count of stars:100
   - Count of forks:27
 * NPM download stats (optional):
   - Downloads in the last day:470
   - Downloads in the last week:2302
   - Downloads in the last month:14448

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by extend1994** [comment]
@finch185277 Please don't forget to fix this pull request. If you have any question, just ask us. Thanks.

**Comment by finch185277** [comment]
OK, to fix PR, I would use https://github.com/Nanonid/rison . Thanks.

**Comment by finch185277** [comment]
I open another PR : https://github.com/cdnjs/cdnjs/pull/12347
So, should I close PR here (https://github.com/cdnjs/cdnjs/pull/12274)?

**Comment by PeterDaveHello** [comment]
@finch185277 sure

**Pull request closed without merging**
