### PR TITLE
Add jQuery Once

### PR DESCRIPTION
**Pull request by RobLoach**
Add [jQuery Once](https://github.com/robloach/jquery-once), as requested at https://github.com/RobLoach/jquery-once/issues/34 .

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please squash them into one commit, thanks.

**Comment by RobLoach** [comment]
@PeterDaveHello Thanks, squashed. :bus:

**Comment by PeterDaveHello** [comment]
Please also rebase with our latest master branch, the parent of this commit was a little bit old, thanks.

**Comment by RobLoach** [comment]
@petecooper Pulled in master, rebased. Thanks!

**Pull request merged**
