### PR TITLE
Adding Eclipse Paho MQTT Library

### PR DESCRIPTION
**Pull request by jpwsutton**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/eclipse/paho.mqtt.javascript
 * Official website (optional, not the repository): https://www.eclipse.org/paho/
 * NPM package url (optional): N/A
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 38
   - Count of watchers: 15 
   - Count of forks: 14
 * NPM download stats (optional): N/A
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

- Eclipse.org Downloads in last month: 234

# Essential checklist
 * [ ] I'm the author of this library - Not Author, but committer on Eclipse Paho Project.
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket] ,(Eclipse Paho only just moved to GitHub so not many stars, however the combined project has between 15,000 to 20,000+ downloads per month)
   * [ ] More than 500 downloads stats per month on npm registry - N/A
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message- N/A
 * [ ] Mention related issue(s), people in commit message, comment. - N/A

Signed-off-by: James Sutton <james.sutton@uk.ibm.com>

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Would you please add autoupdate config, author and keywords info in package.json?

**Comment by jpwsutton** [comment]
@PeterDaveHello For the Author, would 'Eclipse Paho' be acceptable as this is a community project?
Also, in terms of the Autoupdate, it would be possible to add configuration for the normal unminified mqttws31.js file, but we don't commit the minified file and so that would have to be updated manually. Would that be ok?

**Comment by PeterDaveHello** [comment]
Hi @jpwsutton 

>  For the Author, would 'Eclipse Paho' be acceptable as this is a community project?

Yes

> Also, in terms of the Autoupdate, it would be possible to add configuration for the normal unminified mqttws31.js file, but we don't commit the minified file and so that would have to be updated manually. Would that be ok?

Yes

**Comment by jpwsutton** [comment]
Done!

**Pull request merged**
