### PR TITLE
add license of knockout.mapping, cc #9248

### PR DESCRIPTION
**Pull request by hare1039**
https://github.com/SteveSanderson/knockout.mapping/blob/master/LICENSE

### CODE REVIEW

**Comment by hare1039** [comment]
@kennynaoh please check

**Comment by kennynaoh** [comment]
@hare1039 
Please also mention issue number in commit message.
Thanks!

**Comment by kennynaoh** [comment]
LGTM
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
