### PR TITLE
add auto-update config & update package.json of dat-gui

### PR DESCRIPTION
**Pull request by Amomo**
Hi @Piicksarn , From #5420, I have updated info in package.json of dat-gui.
From #5500, I also add license info.
repo: https://github.com/dataarts/dat.gui
Would you mind checking this PR for me? Thank you~ :-)

- [ ] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `50`, Star `943`, Fork `109`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by Piicksarn** [comment]
@Amomo, the pr is fine but need rebase to master.

**Comment by Amomo** [comment]
@Piicksarn I have rebased it!
Could you take a look? Thank you~

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you please take a look at the pr?
Thank you!

**Comment by PeterDaveHello** [comment]
Can we keep the old keywords?

**Comment by Amomo** [comment]
@Piicksarn I have modified this PR!
Could you check it again? Thank you~

**Comment by Piicksarn** [comment]
@Amomo, sorry for my delay..
i think we need to make the commit be clean, so that we had better correct the keyword in the first commit. :)

**Comment by Amomo** [comment]
Oops, I fix in the wrong commit.😂Thanks for your reminder!
@Piicksarn I have fix it, could you take a look? Thank you~

**Pull request merged**
