### PR TITLE
Added i18n translation messages

### PR DESCRIPTION
**Pull request by holtkamp**
New attempt for https://github.com/cdnjs/cdnjs/pull/5845

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Not the same source as #4609? Looks different in the file.

**Comment by holtkamp** [comment]
https://github.com/cdnjs/cdnjs/pull/4609 was closed due to no response from my side, that is why I opened https://github.com/cdnjs/cdnjs/pull/5845, that one was failed because of multiple commits in one PR.

**Comment by PeterDaveHello** [comment]
So what's the source of these files?

**Comment by holtkamp** [comment]
Here you go: 
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.min.js

**Comment by PeterDaveHello** [comment]
nope, looks different

**Comment by holtkamp** [comment]
ok, should be the same content now:

http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.min.js

Problem is, this results in two commits, I can not rebase / squash into one commit because of the problems with the 'Sortable' file:

```
➜  i18n git:(patch-jquery-ui-i18n) ✗ git add *.js
➜  i18n git:(patch-jquery-ui-i18n) ✗ git commit -m "Use http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.[min.]js as source"
[patch-jquery-ui-i18n 7ba8059] Use http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.[min.]js as source
 2 files changed, 2063 insertions(+), 2058 deletions(-)
 rewrite ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.js (97%)
 rewrite ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.min.js (98%)
➜  i18n git:(patch-jquery-ui-i18n) ✗ git rebase -i HEAD~1
Cannot rebase: You have unstaged changes.
Please commit or stash them.
➜  i18n git:(patch-jquery-ui-i18n) ✗ 
```

Hope you can accept it with two commits?

**Comment by PeterDaveHello** [comment]
#3650 [sparseCheckout.md](https://github.com/cdnjs/cdnjs/blob/master/sparseCheckout.md) will help you fix it!

**Comment by holtkamp** [comment]
OK, but only to smash these 2 commits in 1? Spent significant time on this
already...

**Comment by PeterDaveHello** [comment]
Yep, no reason to use 2 commits to do this this, what about let me take this job? So you don't need to handle the commit, and will be done very soon.

**Comment by holtkamp** [comment]
will try one last time with the shallow clone, never too late to learn something new about GIT ;)

**Comment by PeterDaveHello** [comment]
Okay, don't forget sparse-checkout, will help very much!

**Comment by holtkamp** [comment]
Ok, I officially give up, tried a sparse check out of my own fork and then smash my last two commits into one and push it, but nothing seems to change. When I check ```git log``` my last two commits were squashed into one:
```
commit b1e2e700ab5be389a88ed14ca4743b7681525b3b
Author: Menno Holtkamp <menno.holtkamp@shopforce.nl>
Date:   Thu Oct 15 13:39:49 2015 +0200

    Added i18n translation messages
    
    Use http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.[min.]js as source
```
But pushing it to my fork seemed to have no effect, the returned messages suggested to pull first, but now the number of commits only increases? 

```
git init cdnjs && cd cdnjs
git config core.sparseCheckout true
echo '/ajax/libs/jqueryui/*' >> .git/info/sparse-checkout
git remote add origin https://github.com/holtkamp/cdnjs.git
git remote add upstream https://github.com/cdnjs/cdnjs.git
git pull origin patch-jquery-ui-i18n --depth 5
git checkout patch-jquery-ui-i18n
git rebase -i HEAD~2
git push
git pull
git push
```

Sorry for the incompetence, guess this is beyond my comprehension...

**Comment by PeterDaveHello** [comment]
hmmm... there must be something wrong, you can check the output when you have time, so let me take this work now?

**Comment by holtkamp** [comment]
would be great if the pro can take care of this... ;)

**Comment by PeterDaveHello** [comment]
Will do.

**Pull request closed without merging**
