### PR TITLE
Create request-frame.min.js

### PR DESCRIPTION
**Pull request by julienetie**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Would you please take a look at our readme doc and fix it? Thanks.

**Comment by julienetie** [comment]
Thanks will get to this soon

**Comment by PeterDaveHello** [comment]
@julienetie are you still interested in fixing this PR? If not, I'll close this PR, thanks.

**Comment by PeterDaveHello** [comment]
Hello, any updates here? Thanks.

**Comment by julienetie** [comment]
No longer required, thanks.

**Pull request closed without merging**
