### PR TITLE
Add license of feedback.js, cc #9248

### PR DESCRIPTION
**Pull request by extend1994**
https://github.com/niklasvh/feedback.js/blob/master/License

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@extend1994 It's not easy to know the license is MIT in this `License` file. You can also paste https://github.com/niklasvh/feedback.js#license next time.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM

**Comment by extend1994** [comment]
@pvnr0082t OK!

**Pull request merged**
