### PR TITLE
[new] Adding Readmore.js v2.0.0

### PR DESCRIPTION
**Pull request by andrepiske**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please tell us your files' source, and add git or npm auto-update config if is possible, BTW, I think you missed filename field in package.json, thanks.

**Comment by andrepiske** [comment]
I think I'm missing something here. Am I missing some step so this PR may be merged? Thanks in advance.

**Comment by PeterDaveHello** [comment]
Oh yeah, please tell us where did you get these files?
And would you please squash these commits into only one commit as our document said?
Thanks!

**Comment by andrepiske** [comment]
I got the files from https://github.com/jedfoster/Readmore.js (as is specified in the package.json autoupdate).
OK, squashed it in one commit. Hope everything is now fine!

**Comment by PeterDaveHello** [comment]
:+1:

**Pull request merged**
