### PR TITLE
[Author] Add instafetch.js w/ npm auto-update via single package.json

### PR DESCRIPTION
**Pull request by thomasvaeth**
Pull request for issue: #11190 

# Profile of the lib
 * Git repository (required): https://github.com/thomasvaeth/instafetch.js
 * Official website (optional, not the repository): http://thomasvaeth.com/instafetch.js/
 * NPM package url (optional): https://www.npmjs.com/package/instafetch.js
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 6
   - Count of stars: 113
   - Count of forks: 5
 * NPM download stats (optional):
   - Downloads in the last day: 0
   - Downloads in the last week: 20
   - Downloads in the last month: 61

# Essential checklist
 * [X] I'm the author of this library
   * [X] I would like to add link to the page of this library on CDNJS on website / readme
 * [X] This lib was not found on cdnjs repo
 * [X] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [X] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [X] Has valid tags for each versions (for git auto-update)
 * [X] Auto-update setup
 * [X] Auto-update target/source is valid.
 * [X] Auto-update filemap is correct.

# Git commit checklist
 * [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X] The parent of the commit(s) in the PR is not old than 3 days.
 * [X] Pull request is sending from a non-master branch with meaningful name.
 * [X] Separate unrelated changes into different commits.
 * [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [X] Close corresponding issue in commit message
 * [X] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by thomasvaeth** [comment]
"instafetch.min.js does not exist but is referenced in package.json!"

Hm did I do something wrong? I compared it to other repos that did the single package.json file. (First PR to CDNJS ever)

**Comment by PeterDaveHello** [comment]
@thomasvaeth you need to remove the version info, as you didn't add the assets.

**Comment by thomasvaeth** [comment]
1. My first two version were before putting it on NPM. So NPM now will be the way to go for all future versions.

2. I sent the PR using the GitHub website.

**Comment by thomasvaeth** [comment]
Thank you for the help!

**Pull request merged**
