### PR TITLE
Add Ripple.js@1.2.1 w/ git auto-update

### PR DESCRIPTION
**Pull request by ajay2507**
Pull request for issue: #11046

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):  [https://github.com/jakiestfu/Ripple.js](https://github.com/jakiestfu/Ripple.js)
 * Official website (optional, not the repository):  [https://jakiestfu.github.io/Ripple.js/demo/](https://jakiestfu.github.io/Ripple.js/demo/)
 * NPM package url (optional):
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required)
   - Count of watchers: 7
   - Count of stars: 168
   - Count of forks: 22
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by ajay2507** [comment]
@PeterDaveHello  Build is failing and it is showing 2-spaces as indent Error, I tried to fix it but it's showing again. Can you check this once?.

**Comment by hare1039** [comment]
Let me fix this

**Comment by hare1039** [comment]
Looks like
```
--- a/ajax/libs/Ripple.js/package.json
+++ b/ajax/libs/Ripple.js/package.json
@@ -30,4 +30,4 @@
     ]
   },
   "license": "MIT"
-}
+}
```

P.S. You can run `tools/fixFormat.js` to correct indents when you work locally.

**Comment by PeterDaveHello** [comment]
@hare1039 ask before squash.

**Comment by hare1039** [comment]
Ok, I will be more careful next time.

**Comment by ajay2507** [comment]
@hare1039 Thanks for your help. @sufuf3 @extend1994 I have edited the commit message. Is this commit message is fine??

**Comment by sufuf3** [comment]
@ajay2507  But this just changed the title, the commit message still needs to be changed.
Do you use the command line to send the commits or GitHub GUI? 

If you use the command line to send the commit, you can use the `git commit --amend` to change the commit message as the followings:
```
Add Ripple.js@1.2.1 w/ git auto-update

close #11046, cc @jakiestfu
```

Thanks for your great work.

**Comment by ajay2507** [comment]
Great! Thanks for your help @sufuf3. Will change commit message as you suggested.

**Comment by ajay2507** [comment]
Sorry to disturb @hare1039 I have changed the commit message but  build is failing again because of 2 space indent. I tried fixing, can you help me out regarding this. 
I have one doubt I need to set up entire repository locally to test using  tools/fixFormat.js or Is there any short way. because I have cloned only ajax/libs/* using sparsecheckout.md

**Comment by hare1039** [comment]
@ajay2507 My `sparse-checkout` contains:
```
/build
/test
/tools
/scratch
/MIT-LICENSE
/hooks
/*.yml
/*.md
/*.json
/*.sh
/*.js
/package.json
/ajax/libs/v-mask/*
#... some libraries here
```
This config are enough to run `tools/fixFormat.js`.
Would you like to try it out yourself?
Or I can fix this PR for you.

**Comment by ajay2507** [comment]
@hare1039 I will setup and run npm test as you suggested. I will try to fix this PR. If not i will ask you. Thank you.

**Comment by hare1039** [comment]
@ajay2507 Sorry for the late reply. I think this PR is OK now.
@sufuf3 @extend1994 I squash these commits. Please review this PR. Thank you guys.

**Comment by PeterDaveHello** [comment]
Thanks @ajay2507 !

**Pull request merged**
