### PR TITLE
[author] [new] Add europa w/ npm auto-update via single package.json

### PR DESCRIPTION
**Pull request by neocotic**
Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/NotNinja/europa
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/europa
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 4
   - Count of stars: 116
   - Count of forks: 21
 * NPM download stats (optional):
   - Downloads in the last day: 0
   - Downloads in the last week: 6
   - Downloads in the last month: 37

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by neocotic** [comment]
europa is the new name for the [html-md](https://www.npmjs.com/package/html-md) module.

**Comment by sufuf3** [comment]
Hi, @neocotic Thanks for your contribution.

May I ask that which auto-update do you like to use, npm or git?
Because I found that there are 7 releases versions from npm, and 11 releases versions from GitHub.
As usual, we prefer to use more releases versions as the auto-update option.
But if you think npm is stable than GitHub repo, then npm is a good choice.

Thanks a lot.

**Comment by neocotic** [comment]
@sufuf3 npm is my preferred choice. The repository has been around longer because it's the same one as was used for the old library, html-md, which has been completely replaced. That's why it has more versions than the npm module, which I only created within the last 24 hours for the new module.

Sorry if this causes any confusion.

**Comment by sufuf3** [comment]
@cdnjs/library-reviewer 
Please help review this PR, Thank you.

**Comment by maruilian11** [comment]
Hi @neocotic, we prefer to add stable versions to cdnjs, could we change to use git auto-update to fetch files on GitHub repo? Is there anything we need to notice?

**Comment by neocotic** [comment]
@maruilian11 As mentioned before, I have recently rewritten the library which included a rebranding (new module name). This means that almost all versions on Git are for the old package. Unfortunately, the rewrite took some time and is more modular, so pre-release versions were required for builds to work correctly (for now). Basically, I have the following versions, but I only really want `>= 4.0.0`.

git versions:

* 4.0.0
* ~~3.1.0~~
* ~~3.0.2~~
* ~~3.0.1~~
* ~~3.0.0~~
* ~~2.1.1~~
* ~~2.1.0~~
* ~~2.0.2~~
* ~~2.0.1~~
* ~~2.0.0~~
* ~~1.0.0~~

npm versions:

* 4.0.0
* ~~4.0.0-alpha1~~
* ~~4.0.0-alpha2~~
* ~~4.0.0-alpha3~~
* ~~4.0.0-alpha7~~
* ~~4.0.0-alpha8~~
* ~~4.0.0-alpha9~~

This is why I prefer to use npm auto-update, as it will exclude all versions related to the old package, which is now deprecated.

Is there no way that you can simply update your script to ignore any pre-release versions if you do not wish to publish them (which I totally understand)? Not so much `0.x`, but more `x-preidx` or `x-preid.x`: https://docs.npmjs.com/misc/semver#prerelease-tags

I would like to maintain the versions for the old versions on git and I see no way of unpublishing the pre-release versions from npm anymore with their new(ish) unpublish policies.

I recently got another of my projects, QRious, published to CDNJS (see #11366) which also had pre-release versions in npm and it got published without this concern being raised.

**Comment by sufuf3** [comment]
@cdnjs/library-reviewer
Please help review this PR, Thank you.

**Comment by sufuf3** [comment]
@extend1994 @maruilian11 @pvnr0082t 
Please help review this PR, Thank you.

**Comment by neocotic** [comment]
Any update on this?

**Comment by sufuf3** [comment]
@extend1994 @maruilian11 @pvnr0082t
Please help review this PR, Thank you.

**Comment by maruilian11** [comment]
@neocotic If you only want to add `4.0.0` from npm, we can use `gitignore` to ignore the pre-versions.

**Comment by neocotic** [comment]
Thank you everyone :smile:

**Comment by PeterDaveHello** [comment]
Thank you @neocotic

**Pull request merged**
