### PR TITLE
Added react-modal@0.2.0

### PR DESCRIPTION
**Pull request by arasmussen**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please don't put the all thing in one line in `package.json`, is very hard to read, and you should set its `filename` field to the minified file, thanks.

**Comment by arasmussen** [comment]
@PeterDaveHello The package.json changes came from the cdnjs-importer script, but I'll change it now. Thanks.

**Comment by PeterDaveHello** [comment]
@arasmussen It may be a bug, which version you are using? I checked the repo of the lib, origin package.json looks fine. Ping @IonicaBizau.

**Comment by PeterDaveHello** [comment]
BTW @arasmussen, please squash them into only one commit as document said, thanks.

**Comment by IonicaBizau** [comment]
I remember it was working fine, and I didn't updated anything yet. The magic [happens on this line](https://github.com/IonicaBizau/cdnjs-importer/blob/6836f6f378802c0d1d950d6a5064f28bd42db534/lib/index.js#L210).

This is probably fixed in the new version.

**Comment by arasmussen** [comment]
I just cloned the repo and npm install -g cdnjs-importer 25 minutes ago, cdnjs-importer version is 1.4.1. Will squash.

**Comment by IonicaBizau** [comment]
Strange, it should work then. But like I said, this is already fixed in 2.0.0, using [`w-json`](https://github.com/IonicaBizau/node-w-json) which has the [two space indent by default](https://github.com/IonicaBizau/node-w-json#wjsonpath-data-space-callback).

**Comment by arasmussen** [comment]
Updated

**Comment by PeterDaveHello** [comment]
Hmmmm ... should better use multi-line for array, but looks better now, will format it latter, jut wait for the passed result now.

**Pull request merged**
