### PR TITLE
[New] Add ie-love v0.3.0 w/ npm auto-update

### LINKED ISSUE #6943: [Request] Add ie-love
**Library name:** ie-love
**Git repository url:** https://github.com/corysimmons/ie-love
**npm package url(optional):** https://www.npmjs.com/package/ie-love
**License(s):** MIT
**Official homepage:** https://github.com/corysimmons/ie-love
**Wanna say something? Leave message here:** Combo polyfill for IE8. Here's the minified version https://github.com/corysimmons/ie-love/blob/master/dist/ie-love.min.js
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by sashberd**
close #6943, cc @corysimmons

Pull request for issue: #6943
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/corysimmons/ie-love
 * Official website (optional, not the repository): 
 * NPM package url (optional): https://www.npmjs.com/package/ie-love
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):`
   - Count of watchers: 1
   - Count of stars: 17
   - Count of forks: 4
 * NPM download stats (optional):
   - Downloads in the last day: 0
   - Downloads in the last week: 8
   - Downloads in the last month: 36

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sashberd** [comment]
@PeterDaveHello  What do you mean by 

> seems to use not the same file format as the upstream?
Can I help with this?

**Comment by PeterDaveHello** [comment]
@sashberd file checksum/integrity broken.

**Comment by maruilian11** [comment]
@sashberd Can you fetch the file from 0.0.3 again? Because this one seems to be different from it.
@PeterDaveHello Sorry. I usually remember to check it.

**Comment by sashberd** [comment]
@PeterDaveHello @maruilian11 The PR was updated

**Comment by sashberd** [comment]
@PeterDaveHello @maruilian11 
Guys, I have no idea what is problem with this file. 
Here the data that I got in windows:

image


Should I exclude 0.0.3 and take sources from the git?

**Comment by PeterDaveHello** [comment]
@sashberd please use text when it's possible as it's much more comparable, and not resource-wasting.

Your results looks correct but what you committed is wrong.
The sha1 of ie-love.js in your commit is `def907cac18d6c1e46ab58e7816a2a3df691d34e`, and it'll be better to use sha2 to compare as I provided earlier.

**Comment by sashberd** [comment]
@PeterDaveHello Well, I have no idea what is wrong. I am taking this files from installed npm folder.
@sufuf3 Can you help me with it?
Thanks

**Comment by PeterDaveHello** [comment]
@sashberd you didn't add the right file in the commit, and @sufuf3 I don't think you should directly  take what we should let @sashberd to understand, help doesn't mean do it.

**Comment by PeterDaveHello** [comment]
@sashberd I believe that you can checkout to commit https://github.com/cdnjs/cdnjs/commit/75c2f631430a46e2ba15fad2f9bd4372628e2e30 locally and confirm its checksum, it's simpily wrong, you fetched the correct file later, but you didn't commit it, the file in the commit was wrong.

**Pull request merged**
