### PR TITLE
add geolocator@1.2.9 w/ npm auto-update

### LINKED ISSUE #8315: [Request] Add geolocator
**Library name:geolocator** 
**Git repository url:https://github.com/onury/geolocator**
**npm package url(optional):** https://www.npmjs.com/package/geolocator
**License(s):MIT License**
**Official homepage:https://github.com/onury/geolocator**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #8315 
@dannyxx001 please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/onury/geolocator
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/geolocator
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 226
   - Count of watchers: 14
   - Count of forks: 52
 * NPM download stats (optional):
   - Downloads in the last day: 20
   - Downloads in the last week: 113
   - Downloads in the last month: 430

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8315, cc @onury

### CODE REVIEW

**Comment by x09326** [comment]
@PeterDaveHello 
I think this PR is okay, please help me review it, thanks.

**Comment by onury** [comment]
Hi, I'm the author of geolocator.js
I've just released v2 which is a complete re-write and has a different structure (files located under `/dist` not `/src`). How can I help you update your registry? I'm not so familiar with cdnjs contribution.

**Comment by PeterDaveHello** [comment]
@onury you can send a pull request to update its autoupdate config.

**Comment by onury** [comment]
@PeterDaveHello pls check out and review PR #8378

**Comment by PeterDaveHello** [comment]
Sure.

**Pull request merged**
