### PR TITLE
[new] Add Riot

### PR DESCRIPTION
**Pull request by aurri**
Origin: https://github.com/muut/riotjs

Thanks.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please squash these commits into only one commit as our document said, thanks.

**Comment by aurri** [comment]
Done.

**Comment by PeterDaveHello** [comment]
Oops, I think you missed filed npmName in package.json

**Comment by aurri** [comment]
Oops, you're right. Sorry about that. Changed to use the new autoupdate.

**Comment by PeterDaveHello** [comment]
Thanks.

**Pull request merged**
