### PR TITLE
add react-datepicker v0.27.0 with npm auto-update

### LINKED ISSUE #8104: [Request] Add React-Datepicker
Library name: react-datepicker
Git repository url: https://github.com/Hacker0x01/react-datepicker
npm package url(optional): https://www.npmjs.com/package/react-datepicker
License(s): MIT
Official homepage: https://hacker0x01.github.io/react-datepicker/

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #8104 
@x09326 please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/Hacker0x01/react-datepicker
 * Official website (optional, not the repository): https://hacker0x01.github.io/react-datepicker/
 * NPM package url (optional): https://www.npmjs.com/package/react-datepicker
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 602
   - Count of watchers: 38
   - Count of forks: 254
 * NPM download stats (optional):
   - Downloads in the last day: 2,424
   - Downloads in the last week: 13,884
   - Downloads in the last month: 61,070

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8104, cc @martijnrusschen

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Hi @kennynaoh thanks for putting this together. I'm new here, so please tell me what I need to do before this can be merged. I'm happy to help out where possible.

**Comment by PeterDaveHello** [comment]
@martijnrusschen by the good structure of this project, there is nothing else to do to host in on cdnjs, we just try to mention libs' author to let its author know that you can use cdnjs soon!

**Comment by martijnrusschen** [comment]
Sounds good! Thanks!

**Comment by PeterDaveHello** [comment]
No probs.

**Comment by x09326** [comment]
@PeterDaveHello 
I think this PR is okay, please help me review it, thanks.

**Pull request merged**
