### PR TITLE
add timeline.css v1.0.0 with git autoupdate, close #5275

### LINKED ISSUE #5275: [Request] Add Timeline.css
**Library name:** Timeline.css
**Git repository url:** https://github.com/christian-fei/Timeline.css

Note: No clearly version and tag in its repository to be recognized.

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/christian-fei/Timeline.css
**Watch 7
  Star 102
 Fork 29**
@Piicksarn i add some keywords from its repo README.md.
could u help me check this PR for #5275? thank you!
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by Piicksarn** [comment]
@maruilian11, take a look at the repository url in package.json! :^)

**Comment by maruilian11** [comment]
@Piicksarn the field is edited by the lib author, do we need to modify it?

**Comment by Piicksarn** [comment]
@maruilian11, it's fine but need rebase to the master.

**Comment by PeterDaveHello** [comment]
Wait for https://github.com/christian-fei/Timeline.css/issues/9

**Comment by maruilian11** [comment]
@Piicksarn i have changed the `license` to `MIT`. could you help me check it again? thank you!

**Comment by Piicksarn** [comment]
@PeterDaveHello, 
@maruilian11 has already had correction of license.
would you mind to have a look at the commit?
thank you!

**Comment by PeterDaveHello** [comment]
Should use 1.0 instead of 1.0.0 next time, because we use the tag to update lib, see:
https://github.com/christian-fei/Timeline.css/tags

**Pull request merged**
