### PR TITLE
Add jQuery-JSONP w/ git auto-update

### LINKED ISSUE #9849: [Request] Add jQuery-JSONP
**Library name:** jQuery-JSONP
**Git repository url:** https://github.com/jaubourg/jquery-jsonp.git
**npm package url(optional):** 
**License(s):** [MIT License](https://github.com/jaubourg/jquery-jsonp/blob/master/MIT-LICENSE.txt)
**Official homepage:**

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #9849

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/jaubourg/jquery-jsonp
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 525
   - Count of watchers: 54
   - Count of forks: 223
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9849, cc @jaubourg

### CODE REVIEW

**Comment by extend1994** [comment]
@PeterDaveHello please help me review this pull request, thank you.

**Comment by PeterDaveHello** [comment]
@extend1994 is the .min.js file minified by you? I didn't see a map file, and actually I saw officially minified file in its readme, just cannot be fetched by auto-update, but you can also use it.

**Comment by extend1994** [comment]
@PeterDaveHello yes, it is minified by me now. If I use officially minified files and rename it, the map files is not needed, right?

**Comment by PeterDaveHello** [comment]
@extend1994 Yes, so any reason that you minified without mapfile?

**Comment by extend1994** [comment]
@PeterDaveHello I thought it is not required. But it seems required actually. Sorry about that!

**Comment by PeterDaveHello** [comment]
@extend1994 It's not required, but we'll provide it if possible.

**Comment by extend1994** [comment]
@PeterDaveHello so in this case, using the officially minified files or using minified file with map by me is a better option?

**Comment by PeterDaveHello** [comment]
@extend1994 I'll use the official minified one :)

**Comment by PeterDaveHello** [comment]
@extend1994 BTW, you can also add the versions with officially minified file.

**Comment by extend1994** [comment]
@PeterDaveHello please help me review this pull request, thanks.

**Comment by extend1994** [comment]
@PeterDaveHello I revised the commit message, please help me review it, thank you!

**Pull request merged**
