### PR TITLE
Add docxtemplater w/ npm auto-update

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #9729

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/open-xml-templating/docxtemplater
 * Official website (optional, not the repository): https://docxtemplater.com
 * NPM package url (optional): https://www.npmjs.com/package/docxtemplater
 * License and its reference: [MIT and GPL-3.0](https://github.com/open-xml-templating/docxtemplater/blob/master/license.md)
 * GitHub / Bitbucket popularity (required): 
   - Count of watchers: 37
   - Count of stars: 526
   - Count of forks: 102
 * NPM download stats (optional):
   - Downloads in the last day: 635
   - Downloads in the last week: 3,020
   - Downloads in the last month: 13,866

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

Note required JavaScript files in v0.3.0 ~ v0.5.2 are minified version and I changed the filenames from `docxgen.js` to `docxtemplater.js` and `docxgen.min.js` to `docxtemplater.min.js` in v0.3.0 ~ v0.2.0.
I add `docxgen.js` based on the official documentation: http://docxtemplater.readthedocs.io/en/v0.7.4/installation.html

### CODE REVIEW

**Comment by extend1994** [comment]
@cdnjs/intern3 Please help me review this pull request, thank you.

**Comment by edi9999** [comment]
Looks good to me (I'm the maintainer of docxtemplater)

**Comment by PeterDaveHello** [comment]
@edi9999 Thanks

**Comment by extend1994** [comment]
@hare1039 Please help me review it, thanks.

**Comment by extend1994** [comment]
@hare1039 @clairetsai818 I update the files' permissions and modified the commit message, please help me review it, thank you.

**Comment by extend1994** [comment]
@PeterDaveHello Please help me review this pull request, thank you.

**Comment by PeterDaveHello** [comment]
As the issue https://github.com/cdnjs/cdnjs-drone-ci/issues/5 mentions, the bot can only check the file permission on the latest version by now, so @cdnjs/intern @cdnjs/intern2 @cdnjs/intern3 please manually check the file permission on the old versions via `git log --summary`, and you'll see something like:
```
 create mode 100755 ajax/libs/docxtemplater/0.6.1/docxtemplater.js
 create mode 100644 ajax/libs/docxtemplater/0.6.1/docxtemplater.min.js
 create mode 100755 ajax/libs/docxtemplater/0.6.2/docxtemplater.js
 create mode 100644 ajax/libs/docxtemplater/0.6.2/docxtemplater.min.js
 create mode 100755 ajax/libs/docxtemplater/0.6.3/docxtemplater.js
 create mode 100644 ajax/libs/docxtemplater/0.6.3/docxtemplater.min.js
 create mode 100755 ajax/libs/docxtemplater/0.6.4/docxtemplater.js
```

**Comment by extend1994** [comment]
@PeterDaveHello Sorry about updating file permission of `.min,js` but forgetting to update `.js`. Now they are fixed. Please help me review it, thank you!

**Comment by PeterDaveHello** [comment]
@extend1994 one more thing to make this PR even better - add symbolic links (`docxtemplater.min.js` -> `docxtemplater.js`) in the old versions without `docxtemplater.min.js`, so that the users can easily change the version number in the url without additional filename changes.

**Comment by extend1994** [comment]
@PeterDaveHello I modified the filename, please help me review it, thank you!

**Comment by PeterDaveHello** [comment]
Did you just 'modified' the filenames? I think I was asking for symbolic links?

**Comment by extend1994** [comment]
@PeterDaveHello Sorry I misunderstand what you said. So I should use the command `ln` instead of modifying the filename, right? Thanks.

**Comment by PeterDaveHello** [comment]
@extend1994 correct

**Comment by extend1994** [comment]
@PeterDaveHello I searched the way to solve the problem of symbolic link permission but I can't find a workable method. Could you please help me with this? Thank you!

**Comment by PeterDaveHello** [comment]
@extend1994 What do you mean workable? I think it's just 'ln -s origin.file new.file'

**Comment by extend1994** [comment]
I added symbolic links with the command you mentioned. I have to remove executable permission of the files that have symbolic links to pass the CI test. But I can't find the way to remove it.

**Comment by PeterDaveHello** [comment]
@extend1994 you mean executable permission on the links or on the origin files?

**Comment by extend1994** [comment]
Links.

**Comment by PeterDaveHello** [comment]
@extend1994 I don't think they are exetuable, let me take a look.

**Comment by PeterDaveHello** [comment]
@extend1994 let's see if it's fixed.

**Comment by extend1994** [comment]
@PeterDaveHello It's fixed! :+1:

**Pull request merged**
