### PR TITLE
manually add simple-module w/ npm auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
**npm package url:** https://www.npmjs.com/package/simple-module
**16 downloads in the last day
126 downloads in the last week
441 downloads in the last month**

**git repo url:** https://github.com/mycolorway/simple-module
**Watch 33
  Star 36
 Fork 12**
@Amomo @Piicksarn could u help me check this PR for #8224 ? thank you!

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR 
 * [ ] The lib has notable popularity **it's a dependency of simditor, and npm popularity is close to our request.**
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Lack of versions on npm.

**Comment by maruilian11** [comment]
@Amomo @Piicksarn 
I add v1.0.0, v2.0.0 ~ v2.0.6 and v3.0.0 ~ v3.0.2 from git repo.
and v3.0.3 is from npm package.

**Comment by PeterDaveHello** [comment]
We can make them the same file name schema.

**Comment by maruilian11** [comment]
@Piicksarn @Amomo I rename v1.0.0 ~ v2.0.6 filename (module* to simple-module*). could you help me check this PR? thanks.

**Pull request merged**
