### PR TITLE
[New][Author] Manually add powjs@1.0.0

### PR DESCRIPTION
**Pull request by achun**
Pull request for issue: #
Related issue(s): #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/powjs/powjs.git
 * Official website (optional, not the repository): http://powjs.com
 * NPM package url (optional):https://www.npmjs.com/package/powjs
 * License and its reference: [MIT](https://github.com/powjs/powjs/blob/master/LICENSE)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 1
   - Count of stars: 4
   - Count of forks: 0
 * NPM download stats (optional):
   - Downloads in the last day:6
   - Downloads in the last week: 24
   - Downloads in the last month: 24

# Essential checklist
 * [x] I'm the author of this library
 * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@achun Thanks for the contribution, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue or PR, I'll respectfully suggest you open a new issue or PR again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this PR in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this PR will be closed.

Thanks for being interested in CDNJS.

cc @PeterDaveHello

**Comment by achun** [comment]
@sufuf3 Thanks for you reply.

I am very understanding of cdnjs strategy, but also very sorry. I developed the JavaScript template engine has more than 10 years of experience. Simply put, I used the method ahead of the decade.

In 2008, I developed http://code.google.com/p/jsct/, which is based on the native javascript syntax based on string splicing. But at that time this method was too alternative, in that era of purely interpolated template engine It is acceptable to all. The advanced method has not been accepted, but now the native grammar template has become mainstream, including native grammar, or native VDOM.

PowJS is three years ago I thought of new ideas, based on native grammar and native DOM tree method,
three years I have been dissatisfied with the specific realization, until now.

At the same time I am also very worried about the way forward can be accepted by the developer, so I think if through the public CDN library to easily obtain PowJS, may allow more people to accept this advanced design method.

For cdnjs strategy, I expressed understanding, and hope cdnjs can be accept this pr.

**Comment by PeterDaveHello** [comment]
Maybe we can wait for a while to see if it growth?

**Comment by achun** [comment]
It's a pity that the popularity has so far been low.

Here is a simple semi-finished product demonstration, hoping to surprise you.

https://jsfiddle.net/achun/nerajbop/

**Pull request closed without merging**
