### PR TITLE
add lazy.js v0.4.2 with git autoupdate

### PR DESCRIPTION
**Pull request by Piicksarn**
**`git repository : `** https://github.com/dtao/lazy.js
**`Watch : 124 /  Star : 2993 /  Fork : 172`**

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by Piicksarn** [comment]
@Amomo, would you mind to have a look at the commit~
Thank you! :blush:

**Comment by Amomo** [comment]
@Piicksarn I think that you should add `, close #5659` in the end of your commit message.

**Comment by Piicksarn** [comment]
@Amomo, would you minf to checkout the commit again? thank you~~

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine, could you take a look? Thank you! :-D

**Comment by PeterDaveHello** [comment]
You didn't rebase with our latest master.

**Comment by Piicksarn** [comment]
@Amomo, i have it rebased to master and need you to check it again.
thank you~ :smiley:

**Pull request merged**
