### PR TITLE
add blueimp-load-image missing files, old versions, update auto-update cfg

### PR DESCRIPTION
**Pull request by maruilian11**
Pull request for issue: #9728 
@Piicksarn @cdnjs/intern2 could you please help me check this PR? Thanks!
the author has generated `load-image.min.js` in 1.7.0, 1.7.1, 1.7.2, 1.9.1, 1.10.0 and 1.11.2, so I didn't generated the map files.
I got all files from github.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Should transfer to git auto-update.

**Comment by PeterDaveHello** [comment]
`add 1.7.0, 1.7.1, 1.7.2, 1.9.1, 1.10.0 and 1.11.2 of blueimp-load-image.`
->
`add blueimp-load-image v1.7.0, v1.7.1, v1.7.2, v1.9.1, v1.10.0 and v1.11.2.`

**Comment by maruilian11** [comment]
old version sources:
v1.0.0 https://github.com/blueimp/JavaScript-Load-Image/commit/dbe0cb3fc541003a76cc5beeda895f2d031a89fb
v1.1.0 https://github.com/blueimp/JavaScript-Load-Image/commit/9a62f4ce9fab73bf627e5c828c2b5c477893bb3f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
v1.1.1 https://github.com/blueimp/JavaScript-Load-Image/commit/ccb467f4e716826b6aa025ea60016cfac0d0ab81#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
v1.1.2 https://github.com/blueimp/JavaScript-Load-Image/commit/d9fc9ac9e7863e581c222c978c73e541d6ffd105#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
v1.1.3 https://github.com/blueimp/JavaScript-Load-Image/commit/9948ecc74560b5140716890bb570156cf1782d9f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
v1.1.4 https://github.com/blueimp/JavaScript-Load-Image/commit/b24c43b67e2c3be177e4aa85321e87d444b31a86#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
v1.1.7 https://github.com/blueimp/JavaScript-Load-Image/commit/3202fb470d88f4e67be317fb52edecfe339e95f2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
v1.2(not added for not changing `js` files) https://github.com/blueimp/JavaScript-Load-Image/commit/48170089bf54d57e694e6fea830e825ae38b9ea0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
v1.2.0(not added for not changing `js` files) https://github.com/blueimp/JavaScript-Load-Image/commit/8f7d4b022ba8233593e70dfedc972e6b66f86fcb
v1.2.1(not added for not changing `js` files) https://github.com/blueimp/JavaScript-Load-Image/commit/7de8cd23883cb81cd1e29b68bcdca19c3dc314e4#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
v1.2.3 https://github.com/blueimp/JavaScript-Load-Image/commit/8e7c998acf9eef5b2c1d45a48a885a2798b9f7fc#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
v1.3.0 https://github.com/blueimp/JavaScript-Load-Image/commit/967c91089ab85f778822c2d0b9d3ea8593f04d1d
v1.3.1 https://github.com/blueimp/JavaScript-Load-Image/commit/f1abe48c7aa3880da31928736afcb454aaeb76d6#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
v1.3.2 https://github.com/blueimp/JavaScript-Load-Image/commit/892df6c1e556e90872fa196e1a2ec735e8f4f187#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
v1.4.0 https://github.com/blueimp/JavaScript-Load-Image/commit/d1b106c0a1dcfb83c66215e1757788595186fc86#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
v1.4.1 https://github.com/blueimp/JavaScript-Load-Image/commit/7482037da982411292fe0d5b0f8af67c4ea727e9#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
v1.5.0 https://github.com/blueimp/JavaScript-Load-Image/commit/15a2b276c0f27daa23af12f31e354b570ef12b60#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

other newly add versions are from git auto-update

**Comment by maruilian11** [comment]
@pvnr0082t thanks for your review, could you help me check this PR again? thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
`transfer to git auto-update for blueimp-load-image`
->
`transfer blueimp-load-image to git auto-update`

**Comment by maruilian11** [comment]
@PeterDaveHello I updated the commit msg.

**Comment by PeterDaveHello** [comment]
If there is no missing version between v1.0.0 and v1.11.2, just mention you added v1.0.0 ~ v1.11.2 next time.

**Comment by PeterDaveHello** [comment]
Please always rebase with master branch.

**Comment by PeterDaveHello** [comment]
Wrong/old PR title.

**Comment by maruilian11** [comment]
@PeterDaveHello got it.
about the rebasing, I was waiting for `continuous-integration/drone/pr` building success, so do I need to tag   people once I send the commit?

**Comment by PeterDaveHello** [comment]
There is no need to wait CI for rebasing, of course you should ping people for review.

**Pull request merged**
