### PR TITLE
Update jquery.scrollTo to 2.1.0

### PR DESCRIPTION
**Pull request by flesler**
Hi,

The project already had the auto-update part on the package.json, not sure why it's not pulling still by itself so here it is.

I saw on another issue that you asked him to squash the commits. I tried cloning the repo and it's currently at 1GB. The most practical way to submit changes is to add/modify files via Github web which creates a commit for each file.
Would you revise your policy?

Thanks

### CODE REVIEW

**Comment by drewfreyling** [comment]
Can you please let us know where you grabbed these files from? We are looking at going to a different repo which would just have `package.json` files but until then can you please squash into one commit?

**Comment by flesler** [comment]
I'm the owner of this plugin, it is hosted [here](https://github.com/flesler/jquery.scrollTo).
Downloading the whole thing will take some time, will do it soon but surely not today.
Thanks

**Comment by PeterDaveHello** [comment]
I already updated it in 7bdd6b1 about 2 weeks ago, what's the reason why to send this PR?

**Comment by flesler** [comment]
I created the PR before you updated that. Note that I changed the description on package.json.
Thanks for updating btw.

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs#enabling-npm-auto-update
> because many libs will change the naming or directory structure during different versions, and we may need to minify the lib without pre-minified dist files, so it'll be reasonable to delay for at most **30** hours, if you think there is a lib didn't been updated, please wait at least **30** hours for the process to audit it.

**Comment by PeterDaveHello** [comment]
Please create a new PR to update that, thanks!

**Comment by flesler** [comment]
The first version of the plugin had a different name on the minified file, I submitted another PR to change it so that auto-updates could work

**Comment by PeterDaveHello** [comment]
Okay, fine.

**Pull request closed without merging**
