### PR TITLE
Added operative@0.4.0

### PR DESCRIPTION
**Pull request by rileyjshaw**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please tell me your source and add different lib in individual pull requests so that we can audit them easily. These requirement are listed in the document already.

**Comment by rileyjshaw** [comment]
Very sorry! I accidentally pushed all commits to the same branch, so they were automatically added to this PR.

Before I fix this, can I ask what you mean by

  > Please tell me your source

?

**Comment by PeterDaveHello** [comment]
I meant the source you got these files, thanks.

**Comment by rileyjshaw** [comment]
Closing this PR - I'll make new individual ones soon.

**Pull request closed without merging**
