### PR TITLE
add livingston-css3-mediaqueries-js@1.0.0 w/ git autoupdate

### LINKED ISSUE #7844: [Request] Add ccs3-mediaqueries-js
**Library name:** ccs3-mediaqueries-js
**Git repository https://github.com/livingston/css3-mediaqueries-js**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #7844 
@x09326 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/livingston/css3-mediaqueries-js
 * Official website (optional, not the repository): http://code.google.com/p/css3-mediaqueries-js/
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 263
   - Count of watchers: 28
   - Count of forks: 113
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7844, cc @livingston

### CODE REVIEW

**Comment by x09326** [comment]
Sorry for the late response.
Please modify the ```"homepage"``` to https and do the rebase.

**Comment by pvnr0082t** [comment]
@x09326 I have update `homepage`. Please help me review again, thank you.

**Comment by x09326** [comment]
@PeterDaveHello 
I think this PR is okay, please help me review it, thanks.

**Comment by PeterDaveHello** [comment]
There may be something wrong, I wonder the repo you are using it's not the author's repo, maybe we should not treat them as the same lib.

References:
https://github.com/woutervandergraaf
https://github.com/woutervandergraaf/css3-mediaqueries-js
https://code.google.com/archive/p/css3-mediaqueries-js/source/default/commits

**Comment by pvnr0082t** [comment]
@x09326 I have updated `author` info and remove `homepage` in package.json. Please help me review again, thank you.

**Comment by x09326** [comment]
@PeterDaveHello 
I think this PR is okay, please help me review it, thanks.

**Comment by PeterDaveHello** [comment]
Looks like you forgot to rebase your branch with the latest master branch.

**Comment by PeterDaveHello** [comment]
@pvnr0082t you should also update the homepage in comment.

**Pull request merged**
