### PR TITLE
Add license of require-css, cc #5500

### PR DESCRIPTION
**Pull request by lcd78706**
https://github.com/guybedford/require-css/blob/master/LICENSE

### CODE REVIEW

**Comment by lcd78706** [comment]
@kennynaoh 
Please review this pull request. Thanks!

**Comment by kennynaoh** [comment]
@PeterDaveHello 
Could you help me trigger the CI again?
Thanks

**Comment by kennynaoh** [comment]
LGTM
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
Thanks for your contribution.

**Pull request merged**
