### PR TITLE
add angular-messages v1.4.7

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/angular/bower-angular-messages
**Watch 18
  Star 34
 Fork 40**
@Piicksarn could you help me check out the PR for #6052 ? thank you~
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity cc #6052 
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by Piicksarn** [comment]
It's fine~
@PeterDaveHello, would you please have a look at the pr?
Thank you!

**Comment by Amomo** [comment]
Same problem with #6231

@maruilian11 because you add files from npm, their version number is `1.4.7`.
Could you change your folder name and related message to a right version number?

**Comment by PeterDaveHello** [comment]
So should not use current source as auto-update source.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern you should be care of strange/unnormal things, notice that there are 1.6k git tags with hash, that makes no sense, should find another source for dist/release.

**Comment by maruilian11** [comment]
@Amomo @Piicksarn is that ok?

**Comment by Piicksarn** [comment]
@maruilian11, would you mind to rebase to master
i think the pr is fine!

**Comment by maruilian11** [comment]
@Piicksarn i have rebased it~

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you please have a look at the pr?
Thank you!

**Pull request merged**
