### PR TITLE
add welcome.js@1.0.0 with auto-update [author] [new]

### PR DESCRIPTION
**Pull request by stml**
# Profile of the lib
 * Git repository (required): https://github.com/stml/welcomejs
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 194
   - Count of watchers: 6
   - Count of forks: 16
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 stars on GitHub
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@stml would you please send the pull request from a non-master branch? We don't accept PR from master branch, and as you can see: https://ci.cdnjs.com/cdnjs/cdnjs/1785, the CI test failed.

**Comment by PeterDaveHello** [comment]
Ping.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by clairetsai818** [comment]
There are no version tags in this repo. Waiting for further response.

**Comment by PeterDaveHello** [comment]
@clairetsai818 I saw you opened an issue, you should mention it here, or mention this issue there, so that it'll be easier to trace the progress, I didn't see a connection between them.

**Comment by sufuf3** [comment]
@PeterDaveHello There is no response from the author since 2 Jan.
And there is no git tag.
What can we do for this PR?
Waiting for the response or close this PR?

Thank you.

**Comment by PeterDaveHello** [comment]
@stml feel free to open a new PR or ping me to reopen this when you have time please, thanks a lot.

**Pull request closed without merging**
