### PR TITLE
Add missing anythingslider theme images

### PR DESCRIPTION
**Pull request by gttds**
Image referenced by theme-minimalist-round.css and theme-minimalist-square.css.
Source https://github.com/CSS-Tricks/AnythingSlider/blob/master/images/arrows-minimalist.png

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Would you please also update the auto-update config in package.json to make sure we won't miss this image in future?

**Comment by gttds** [comment]
Yes no problem. Have now updated package.json as well.

**Comment by PeterDaveHello** [comment]
@gttds Thanks.

**Comment by PeterDaveHello** [comment]
@gttds do you know that if we may also need other images under `images` folder? Thanks.

**Comment by gttds** [comment]
@PeterDaveHello yes, two other images. arrows-metallic.png and cs-portfolio.png which are referenced by theme-metallic.css and theme-cs-portfolio.css respectively.

**Comment by PeterDaveHello** [comment]
So can you also add them? And maybe change the rule of images to single `"images/*.png"`, thanks.

**Comment by gttds** [comment]
No problem. Have done that and also added a gif image which is needed by one of the themes.

**Comment by PeterDaveHello** [comment]
Thanks! What about `default.png`?

**Comment by gttds** [comment]
Shouldn't be an issue as the updated rule `"images/*.+(gif|png)"` ensures that `default.png` will continue to be included in the package.

**Comment by PeterDaveHello** [comment]
@gttds but it's not in the commit, auto-update config will not affact the already exist versions.

**Comment by gttds** [comment]
It's already in the existing versions :) https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/anythingslider/1.9.6/images/default.png

**Comment by PeterDaveHello** [comment]
@gttds Oh okay, my mistake, thanks.

**Pull request merged**
