### PR TITLE
[author] HIW JavaScript API v5.0.2, v5.0.3, and v5.0.4.

### PR DESCRIPTION
**Pull request by JoshMcCullough**
http://developers.healthindicators.gov

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
What's the reason why to remove auto-update?

**Comment by JoshMcCullough** [comment]
I wanted to clarify how it works. E.g. I assume it should point to a "current release" branch which only ever gets updated when a release is done. But how does cdnjs know the version to use when it detects changes in the branch?

**Comment by PeterDaveHello** [comment]
It'll grab files from each git tags as its versions.

**Comment by JoshMcCullough** [comment]
So does it just monitor the repo for commits and if it finds commits, looks for tags which look like a version number?

**Comment by JoshMcCullough** [comment]
I'm going to update this PR with auto-update reinstated.

**Comment by PeterDaveHello** [comment]
It looks into all the tags.

**Comment by JoshMcCullough** [comment]
PR updated with autoupdate.

**Comment by PeterDaveHello** [comment]
Should set `basePath` to `Content/Scripts/API/Output/` instead of adding it to all the filename map

**Comment by JoshMcCullough** [comment]
Should be good to go now. Sorry for all the back-n-forth.

**Pull request merged**
