### PR TITLE
add redux-thunk v2.0.1

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/gaearon/redux-thunk
**Watch 33
  Star 1,239
 Fork 53**
**npm package url** https://www.npmjs.com/package/redux-thunk
**268,913 downloads in the last month**
@Amomo could u help me check this PR for #7041 ? thank you!

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Is this for browser using?

**Comment by gaearon** [comment]
We probably want to add a UMD build to Redux Thunk first, otherwise this is not usable in browser as is.

**Comment by PeterDaveHello** [comment]
@gaearon yeah I think so.

**Comment by gaearon** [comment]
Let me do that & get back to you!

**Comment by PeterDaveHello** [comment]
@gaearon oh, that's nice, thanks!

**Comment by gaearon** [comment]
OK, `redux-thunk@2.0.1` adds a correct UMD build.

**Comment by PeterDaveHello** [comment]
@gaearon Nice, I'll take a look at it!

**Comment by Amomo** [comment]
@maruilian11 could you update this PR to v2.0.1? thanks~

**Comment by PeterDaveHello** [comment]
> OK, redux-thunk@2.0.1 adds a correct UMD build.

Looks nice :+1:

**Comment by maruilian11** [comment]
@Amomo could you help me check this PR again? thanks.

**Comment by gaearon** [comment]
@maruilian11 Thank you!

**Comment by maruilian11** [comment]
@gaearon thank you, too. :laughing:

**Pull request merged**
