### PR TITLE
Add git auto-update config of fitvids

### PR DESCRIPTION
**Pull request by pvnr0082t**
Pull request for issue: #10476 

@x09326 Please help me review this pull request, thank you.

# Profile of the lib
 * Git repository (required):https://github.com/davatron5000/FitVids.js

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@x09326 I think it's okay with one line commit message here because It's redundant to do this just cause over one letter...

**Comment by x09326** [comment]
@pvnr0082t Okay, please rebase to latest master branch.

**Comment by pvnr0082t** [comment]
@x09326 I have rebased onto the latest master branch. Please help me review it again, thank you.

**Comment by pvnr0082t** [comment]
ping @x09326

**Comment by x09326** [comment]
@pvnr0082t please rebase to latest master branch, sorry for the late response

**Comment by pvnr0082t** [comment]
@x09326 I've rebased it onto the latest master branch. Please help me review it again, thank you.

**Pull request merged**
