### PR TITLE
[new] add ng-pdfviewer@0.2.1 with git auto-update

### PR DESCRIPTION
**Pull request by Amomo**
Hi @Piicksarn 

For #5020, I add ng-pdfviewer at v0.2.1 and add git auto-update config in its package.json.
repo: https://github.com/akrennmair/ng-pdfviewer

Would you mind checking this PR for me? Thank you~ :-D

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `12`, Star `122`, Fork `56`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by Piicksarn** [comment]
It's fine!
@PeterDaveHello, would you mind to have a look at the pr?
Thank you!

**Comment by PeterDaveHello** [comment]
@Piicksarn nice to see you back.

**Comment by Amomo** [comment]
me too!
Thank you @Piicksarn ~ :-D

**Comment by PeterDaveHello** [comment]
But I only saw r0.2.1, r0.2.0 and r0.1.0 here, why you use r0.2.1 as version here?
https://github.com/akrennmair/ng-pdfviewer/releases

**Pull request merged**
