### PR TITLE
modify canvas-nest.js auto-update method to npm

### PR DESCRIPTION
**Pull request by hustcc**
Hi @Piicksarn

`canvas-nest.js` has been add to project last week(see #6544 ), now need to modify the auto-update method to `npm`, thx

` Watch 9 ` ` Star 156 ` ` Fork 62 `

 - [ ] Not found on cdnjs repo
 - [ ] No already exist issue and PR
 - [x] Notable popularity : Watch 9, Star 156, Fork 62
 - [x] Project has public repository on famous online hosting platform (or been hosted on npm)
 - [x] Has valid tags for each versions (for git auto-update)
 - [x] Auto-update setup
 - [x] Auto-update target/source is valid.
 - [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@hustcc you can hust tag me next time.

**Comment by hustcc** [comment]
ok, very thanks~

**Comment by hustcc** [comment]
I have change the **code structure**, and change the `canvas-nest.*.js` files into dist folder.

Is there any thing need to modify to make sure cdnjs work well ?

**Comment by PeterDaveHello** [comment]
@hustcc you'll need to update the auto-update config:
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/canvas-nest.js/package.json#L15-L18

**Comment by hustcc** [comment]
So can help me to update the file.

The project is so hurge, that clone it need so much time, because of GWF of China. ->_->

**Comment by PeterDaveHello** [comment]
@hustcc What about trying GitHub GUI?  Could be easy!

**Comment by hustcc** [comment]
I have never used GitHub GUI, let me have a try.

**Comment by PeterDaveHello** [comment]
@hustcc Great!

**Comment by hustcc** [comment]
Please process it, #10161, thanks ^_^

**Pull request merged**
