### PR TITLE
add anchorific v1.1 w/ git auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/renettarenula/anchorific.js
**Watch 9
  Star 116
 Fork 34**
@Amomo could u help me check this PR for #6925 ? thank you!
**since the author doesn't  reply the issue about adding git tag for a while, i use git log number as version to add this lib.**

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR 
 * [x] The lib has notable popularity (the author has two lib with high popularity, so we can see its potential.)
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry 
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update) https://github.com/renettarenula/anchorific.js/issues/20
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by maruilian11** [comment]
waiting for the author add version number and git tag.
https://github.com/renettarenula/anchorific.js/issues/20#issuecomment-238135772

**Comment by maruilian11** [comment]
@Amomo @Piicksarn the author has added tags fot the lib, could you please help me check this PR? thanks!

**Comment by Piicksarn** [comment]
@maruilian11, why not minified the css file?

**Comment by maruilian11** [comment]
@Piicksarn because the css file is an example file.

**Comment by Piicksarn** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
@Piicksarn you need to ping me to merge this.

**Pull request merged**
