### PR TITLE
[new] add ember-computed-reverse.js

### PR DESCRIPTION
**Pull request by NathanJang**
From https://github.com/gdub22/ember-computed-reverse

Hopefully autoupdate will fill in the version number.

### CODE REVIEW

**Comment by NathanJang** [comment]
Hang on, I'm cloning the repo to squash these commits and complete the PR.

**Comment by pieroxy** [comment]
reserve 11GB+ locally before cloning ;-)

**Comment by NathanJang** [comment]
My internet connection doesn't let me :/

Are you going to squash the commit before merging? Because I can easily fix this on the browser, except commit spam.

**Comment by pieroxy** [comment]
I'm not part of the cdnjs project, so I can do nothing for you... I'm just a little peon like you that submitted 4 files in 4 commits and I've been asked to squash them. But I don't own my own datacenter so I can't...

**Comment by NathanJang** [comment]
Woohoo! I am however unable to squash them because my internet connection is limited and I can't clone :/

**Comment by drewfreyling** [comment]
@PeterDaveHello how do you want to handle the squashing of commits when users complain about the repo size?

**Comment by PeterDaveHello** [comment]
If they don't mind, we could do the some work to add/update a lib.

**Comment by NathanJang** [comment]
Isn't it possible for you to squash a PR yourself before merging?

**Comment by NathanJang** [comment]
There, I squashed it.

**Comment by PeterDaveHello** [comment]
Thanks.

**Comment by PeterDaveHello** [comment]
Commit's parent is too old, but I'm not going to ask you to rebase again ... I'll pick it manually.

**Comment by PeterDaveHello** [comment]
Picked in 88285a6

**Comment by NathanJang** [comment]
Thanks!

**Pull request closed without merging**
