### PR TITLE
Add EaselJS@0.8.2 ,close #9145, cc #8766

### LINKED ISSUE #9145: [Request] Add EaselJS 0.8.2
**Library name:** 
EaselJS

**Git repository url:**
https://github.com/CreateJS/EaselJS.git

**npm package url(optional):** 

**License(s):**
MIT License

**Official homepage:**
http://www.createjs.com/easeljs

**Wanna say something? Leave message here:**
EaselJS 0.8.0 is already hosted on CDNJS, but 0.8.2 is not.
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by x09326**
PR for #9145 
@pvnr0082t 
Please help me review this PR, thanks.
I get the files from git repo.

### CODE REVIEW

**Comment by x09326** [comment]
@pvnr0082t 
The reason why I write the filemap like this is due to the file name in old version is `easel.js`, but the file name is easel-(version).combined.js in latest version.
Is there a better way?

**Comment by pvnr0082t** [comment]
@x09326 You didn't commit `package.json`.

**Comment by x09326** [comment]
Sorry I found this lib on cdnjs repo.
I will ask author to build filename without version number.

**Comment by mateddy** [comment]
@x09326 Auto-update might break old version compatibility. Production sites would love to pin a specific version rather than an auto-updated version.

**Comment by PeterDaveHello** [comment]
@mateddy we only update the version on CDNJS repository, but not force update the versions users are using.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello As the comment https://github.com/CreateJS/EaselJS/issues/807#issuecomment-269270803 from upstream, they prefer to add a version number with the filename.
So, should we always manually add this lib without auto-update config?

Thank you.

**Comment by PeterDaveHello** [comment]
@sufuf3 please help manually add them, with auto-update added.

**Pull request closed without merging**
