### PR TITLE
Create jquery-ui-i18n.min.js

### PR DESCRIPTION
**Pull request by holtkamp**
Sorry for failing on https://github.com/cdnjs/cdnjs/pull/4609, was of my radar. Added both the normal and the minified file as requested: https://github.com/cdnjs/cdnjs/pull/4609#issuecomment-98949979

### CODE REVIEW

**Comment by Amomo** [comment]
Hi @holtkamp

Would you please squash them into only one commit?
And, please rebase your commit to match our latest master branch.
Thank you! :-)

**Comment by holtkamp** [comment]
Ok, I really tried, by getting my branch 'patch-1' in sync with the upstream master is really a pain. 

```
➜  cdnjs git:(master) ✗ git checkout patch-1
error: Your local changes to the following files would be overwritten by checkout:
	ajax/libs/Sortable/package.json
Please, commit your changes or stash them before you can switch branches.
Aborting
➜  cdnjs git:(master) ✗ git remote -v
origin	https://github.com/holtkamp/cdnjs.git (fetch)
origin	https://github.com/holtkamp/cdnjs.git (push)
➜  cdnjs git:(master) ✗ git remote add upstream https://github.com/cdnjs/cdnjs.git
➜  cdnjs git:(master) ✗ git fetch upstream
remote: Counting objects: 192091, done.
remote: Compressing objects: 100% (868/868), done.
remote: Total 192091 (delta 27645), reused 27328 (delta 27328), pack-reused 163840
Receiving objects: 100% (192091/192091), 371.54 MiB | 4.33 MiB/s, done.
Resolving deltas: 100% (75960/75960), completed with 8088 local objects.
From https://github.com/cdnjs/cdnjs
 * [new branch]      compatibleTest -> upstream/compatibleTest
 * [new branch]      dev-pastebin -> upstream/dev-pastebin
 * [new branch]      master     -> upstream/master
➜  cdnjs git:(master) ✗ cd ajax/libs/Sortable    
➜  Sortable git:(master) ✗ git checkout -- package.json          
➜  Sortable git:(master) ✗ git checkout -- .           
➜  cdnjs git:(master) ✗ git checkout -- .  
➜  cdnjs git:(master) ✗ git checkout patch-1
error: Your local changes to the following files would be overwritten by checkout:
	ajax/libs/Sortable/package.json
Please, commit your changes or stash them before you can switch branches.
Aborting
```
Would it be better to start this PR from scratch?

**Comment by drewfreyling** [comment]
I would think so. The issue you are seeing is from this -> http://stackoverflow.com/questions/2528589/git-windows-case-sensitive-file-names-not-handled-properly

**Comment by PeterDaveHello** [comment]
#3650
[sparseCheckout.md](https://github.com/cdnjs/cdnjs/blob/master/sparseCheckout.md)

**Comment by PeterDaveHello** [comment]
per #5931

**Pull request closed without merging**
