### PR TITLE
Create .travis.yml

### PR DESCRIPTION
**Pull request by xtuc**

### CODE REVIEW

**Comment by MattIPv4** [comment]
If we can, IMO, it'd be nicer to run CI with Actions instead of external, now that GitHub offers integrated CI?

**Comment by xtuc** [comment]
Travis doesn't seem happy with the size of the cdnjs repo... Do you think GitHub Actions would allow it? Ideally the CI would keep a copy of the entire repo instead of re-cloning for each run.

**Comment by MattIPv4** [comment]
I'm not sure if anyone is ever happy with the size of the repo - with Actions though it won't automatically checkout the repo, so we could generate a sparse config based on the contents of the PR, checkout the repo with that and then run the linter?

**Comment by xtuc** [comment]
That's a good idea

**Comment by MattIPv4** [comment]
(I think our old CI did that, but I'm not sure though)

**Pull request closed without merging**
