### PR TITLE
Add jquery.form@4.0.1 and update package.json

### PR DESCRIPTION
**Pull request by hare1039**
Pull request for issue: #10683
Related issue(s): # #

@cdnjs/intern3 Please help me on this PR. Thanks.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/jquery-form/form.git
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/jquery-form
 * License and its reference: (MIT, LGPL-3.0) https://github.com/jquery-form/form/blob/master/package.json#L8
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 249
   - Count of stars: 3921
   - Count of forks: 1203
 * NPM download stats (optional):
   - Downloads in the last day: 492
   - Downloads in the last week: 2360
   - Downloads in the last month: 12394

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by hare1039** [comment]
@extend1994 I changed the commit message. Please review this PR again. Thanks.

**Comment by maruilian11** [comment]
`No already exist / duplicated issue and PR`
have you checked that?
https://github.com/cdnjs/cdnjs/pull/10743

**Comment by hare1039** [comment]
@maruilian11 Sorry I only search in issues, and I don't know the author sended a PR. Should I close this one?

**Comment by maruilian11** [comment]
yes, please.

**Comment by hare1039** [comment]
Close due to duplicate PR.

**Pull request closed without merging**
