### PR TITLE
add angular-bootstrap-lightbox v0.10.0 

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/compact/angular-bootstrap-lightbox
**Watch 8
  Star 185
 Fork 72**
@Piicksarn could u help me check this PR for #6452 ? thank you!

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
No author info?

**Comment by maruilian11** [comment]
@PeterDaveHello not sure if the lib owner is the author, do i need to open an issue for it？

**Comment by PeterDaveHello** [comment]
Is that so hard? It's most active contributor is the repo owner, so ...
https://github.com/compact/angular-bootstrap-lightbox/graphs/contributors

**Comment by maruilian11** [comment]
just want to make sure. i will send a new pr to add it.

**Pull request merged**
