### PR TITLE
[author] stampit: cleaned up and updated auto-update information

### PR DESCRIPTION
**Pull request by sethlivingston**
- Removed non-production releases
- Switched repository from stampit-org/stampit (CommonJS) to stampit-org/bower (UMD)
- Updated auto-update information to use git instead of npm

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
We don't remove old versions @sethlivingston, can you leave them alone?

**Comment by sethlivingston** [comment]
:+1:

**Comment by PeterDaveHello** [comment]
Okay, I have several questions here:

1. What's the actually changes in the currently already exist versions?
2. Would you please separate different changes into different commits as our document said?

Thanks!

**Comment by sethlivingston** [comment]
@PeterDaveHello There is really just one change. Instead of pulling our files from NPM, we are switching to having you pull our files from our git repo--specifically, stampit-org/bower. Previously we were mistakenly posting CommonJS versions of our latest library; we should be posting UMD versions. The UMD versions come from the git repo we switched over to.

**Comment by PeterDaveHello** [comment]
Okay, I accept it.

**Comment by sethlivingston** [comment]
Thank you!

**Comment by PeterDaveHello** [comment]
np

**Comment by koresar** [comment]
:+1: finally someone took an action. Thanks @sethlivingston

**Comment by sethlivingston** [comment]
My pleasure!

**Pull request merged**
