### PR TITLE
Replace sanitize.css with codify.css

### PR DESCRIPTION
**Pull request by zdroid**
I have published my project sanitize.css long ago on the cdnjs. However, there is another project named sanitize.css which is more popular (and a bit older) than mine, so I decided to let them use that name and rebrand mine project.

I hope this pull request doesn't break anything in your network and that it can be merged.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
We can not do this which will break the current users and confus them.

**Comment by zdroid** [comment]
Is it possible to add this as a new project and mark the other one as deprecated?

**Comment by PeterDaveHello** [comment]
@zdroid I think #8846 has the same issue, and I will do #8904 do handle it, what do you think?

BTW, sorry for the late reply.

**Comment by zdroid** [comment]
@PeterDaveHello good proposal, feel free to do it :+1:

**Comment by PeterDaveHello** [comment]
Thanks @zdroid

**Comment by zdroid** [comment]
@PeterDaveHello Any news about this? You can close this PR once you've done it in the new one.

**Comment by PeterDaveHello** [comment]
I haven't implement it yet, no more time, sorry.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by zdroid** [comment]
@PeterDaveHello That's my question too. :worried:

**Comment by PeterDaveHello** [comment]
Oh sorry, I pinged all old PRs 😓

**Comment by PeterDaveHello** [comment]
@PeterBot Not yet.

**Comment by zdroid** [comment]
It's been a while... still no updates.

**Comment by PeterDaveHello** [comment]
@sashberd i think not

**Comment by zdroid** [comment]
Any outlooks to solve this finally?

**Pull request closed without merging**
