### PR TITLE
Add angular-js-bootstrap-datetimepicker v1.2.4

### LINKED ISSUE #7516: [Request] angular-js-bootstrap-datetimepicker
**Library name:** Angular UI Bootstrap Date Time Picker
**Git repository url:** https://github.com/zhaber/angular-js-bootstrap-datetimepicker
**npm package url(optional):** 
**License(s):** https://github.com/zhaber/angular-js-bootstrap-datetimepicker/blob/master/LICENSE
**Official homepage:** https://github.com/zhaber/angular-js-bootstrap-datetimepicker
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by x09326**
PR for #7516 
@kennynaoh please help me review it, thanks
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/zhaber/angular-js-bootstrap-datetimepicker
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 118
   - Count of watchers: 13
   - Count of forks: 44
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

with git auto-update config, close #7516, cc @zhaber

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@x09326 though I merged this, in fact, there is v1.2.4.1 in repo.

**Comment by x09326** [comment]
@PeterDaveHello because I'm not sure the files in v1.2.4.1 which are the latest files.
Should I open an issue to ask the author?

**Comment by PeterDaveHello** [comment]
What do you mean here? Please explain in detail so that I can know your problem.

**Comment by x09326** [comment]
Oh sorry, I misunderstand it.
Should I send a new PR for v1.2.4.1?

**Comment by PeterDaveHello** [comment]
@x09326 hmmm ... I'll take a look at it first.

**Comment by PeterDaveHello** [comment]
It was added in 2ca2b40, so no need to do it manually.

**Pull request merged**
