### PR TITLE
Improved package.json autoupdate field

### PR DESCRIPTION
**Pull request by WebReflection**
There is an extra file that arbitrary ships with this polyfill, it's called `innerHTML.js` and is a helper [necessary in some case](https://github.com/WebReflection/document-register-element/issues/21).

Thanks for the update.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Should not bump version here.

**Comment by WebReflection** [comment]
ooops, thank you for pointing that out.

**Comment by PeterDaveHello** [comment]
Please squash them into only one commit as document says, thanks.

**Comment by WebReflection** [comment]
can't do that offline, I'll try to close this and re-push a clean PR

**Comment by WebReflection** [comment]
here: https://github.com/cdnjs/cdnjs/pull/4646

apologies for this messed PR

**Pull request closed without merging**
