### PR TITLE
Correct license typo of datepick

### PR DESCRIPTION
**Pull request by dada0423**
cc #5500, cc @pvnr0082t
Please help me review.
Thanks.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@dada0423 You should not mix commit message and the comment. In this case, `Please help me review this PR` should not in commit message. Be careful next time.

**Comment by pvnr0082t** [comment]
LGTM
ping @cdnjs/intern2

**Comment by x09326** [comment]
LGTM

**Comment by pvnr0082t** [comment]
@dada0423 Please mention the related issue next time.

**Pull request merged**
