### PR TITLE
Add license of jquery-resize, cc #5500

### PR DESCRIPTION
**Pull request by NiniHsu**
Reference: http://benalman.com/about/license/

### CODE REVIEW

**Comment by NiniHsu** [comment]
@kennynaoh please help me review this PR.
Thank you!

**Comment by PeterDaveHello** [comment]
1. There is conflict file - `ajax/libs/diff_match_patch/package.json`
2. You should wait for the CI finished first (unless it's not running)

**Comment by PeterDaveHello** [comment]
You should not touch library `diff_match_patch` in the PR/commit since it has nothing to do with this PR.

**Comment by PeterDaveHello** [comment]
The code base is too old, seems you didn't update your master branch before creating the new branch.

**Pull request closed without merging**
