### PR TITLE
Remove keys with leading underscore from package json

### PR DESCRIPTION
**Pull request by petrgazarov**
Addresses issue: https://github.com/cdnjs/cdnjs/issues/9943

### CODE REVIEW

**Comment by petrgazarov** [comment]
@PeterDaveHello 👓

**Comment by PeterDaveHello** [comment]
@petrgazarov would you like to update the test(npm test) in this same PR? Thanks!

**Comment by petrgazarov** [comment]
@PeterDaveHello Not sure if I understand completely. I thought you didn't want to run this spec on `npm run test`. Isn't it used to run package json validation tests?

**Comment by PeterDaveHello** [comment]
@petrgazarov sorry that I didn't explain clear enough, actually the part you did is the format fixer and its own test, right? The additional part I'm asking is about the package json validation tests - `test/valid-packages-test.js`, make sure the `package.json`s of the libraries with the leading underscore will fail, what do you think?

**Comment by petrgazarov** [comment]
@PeterDaveHello Thanks for pointing that out, I updated the PR. I tested that it prints validation error when I run `vows` with leading underscore keys. Then fixFormat removes them and `vows` passes again.

**Comment by PeterDaveHello** [comment]
@petrgazarov Awesome, thanks a lot.

**Pull request merged**
