### PR TITLE
Add v9.12.1 & npm auto-update config in blueimp-file-upload

### PR DESCRIPTION
**Pull request by Amomo**
Hi @Piicksarn , for #6341

We already have "blueimp-file-upload", but without auto-update config.
And, I found the structure of "blueimp-file-upload" in our repo is different with official repo.

So I add v9.11.2(with official structure) and modify "filename" field in package.json to match official repo's structure in first commit.
Then, I add `npm` auto-update config in package.json.

repo url: https://github.com/blueimp/jQuery-File-Upload
npm package url: https://www.npmjs.com/package/blueimp-file-upload

Would you mind checking this PR for me? Thank you~ :-D

- [ ] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `1,524`, Star `22,233`, Fork `2,465`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@LeaYeh please help double check this PR, thanks.

**Comment by PeterDaveHello** [comment]
@maruilian11  please help double check this PR, thanks.

**Comment by maruilian11** [comment]
@Amomo i think if `css/jquery.*.css` in filemap could turn to `css/jquery.fileupload*.css` would be better~

**Comment by Amomo** [comment]
@maruilian11 I have modified it, could you check it again? Thanks! :-D

**Comment by maruilian11** [comment]
＠amomo sorry i'm late, could you rebase on our latest master branch?

**Comment by Amomo** [comment]
Hi @maruilian11 **blueimp-file-upload** has `v9.12.0` now.
Could you help me checking this PR again? Thank you! :-D

**Comment by PeterDaveHello** [comment]
Failed.

**Comment by Amomo** [comment]
oops, get fix!

**Comment by maruilian11** [comment]
@Amomo why don't we need `js/main.js`?

**Comment by Amomo** [comment]
@maruilian11 
as you can see, the comment field in `js/main.js` says its a sample file.
I think it is fine, if we don't host it.

And, because cdnjs already have "blueimp-file-upload", however the structure of this lib has changed now.
I consider that adding a new version and adding auto-update config should be separated.
I add v9.12.1 and change the path in "filename" field in pakeage.json first.
Then, I add the auto-update config.

**Comment by maruilian11** [comment]
@Amomo thank you for your explaination, you seem to lose file in img in auto-date config.

**Comment by PeterDaveHello** [comment]
Ping @Amomo

**Pull request closed without merging**
