### PR TITLE
Include plottable.css in plottable.js

### PR DESCRIPTION
**Pull request by punya**
Adds it to `package.json` (auto-update config) and back-fills past versions

@jtlan and @bluong, please make sure I didn't get anything wrong this time around.

### CODE REVIEW

**Comment by jtlan** [comment]
Yep, that's the one.

**Comment by PeterDaveHello** [comment]
Can you just update package.json? Auto-updater will do the remaining things, thank you.

**Comment by punya** [comment]
Okay, just to make sure - will it add the CSS file to existing versions? When I ran auto-update.js locally, i don't think it added them (but I could have made a mistake).

**Comment by PeterDaveHello** [comment]
No, it will not, but I'll manually trigger it to do that, so you can just update its config, thanks.

**Comment by punya** [comment]
@PeterDaveHello would you like any further changes to this PR?

**Comment by PeterDaveHello** [comment]
Nope, I'll manually cherry-pick this commit later :)

**Comment by PeterDaveHello** [comment]
Picked in 98ad3c5ffc6406ec3e379a03d6923cb67ebc2aa6

**Pull request closed without merging**
