### PR TITLE
add countable v2.1.1 with git autoupdate config

### LINKED ISSUE #7667: [Request] Add Countable
**Library name:** Countable
**Git repository url:** https://github.com/RadLikeWhoa/Countable
**npm package url(optional):** https://www.npmjs.com/package/countable
**License(s):** MIT
**Official homepage:** https://sacha.me/Countable/
**Wanna say something? Leave message here:** Please add this to your cdn

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by dannyxx001**
PR for #7667 

@kennynaoh please help me review this PR, thanks.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/RadLikeWhoa/Countable
 * Official website (optional, not the repository): https://sacha.me/Countable/
 * NPM package url (optional): https://www.npmjs.com/package/countable
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 1359
   - Count of watchers: 58
   - Count of forks: 120
 * NPM download stats (optional):
   - Downloads in the last day: 3
   - Downloads in the last week: 20
   - Downloads in the last month: 73

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7667, cc @RadLikeWhoa

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
countable on npm doesn't seem to be maintain by its own author and has only 3 releases, should use git auto-update first and confirm with its author.

**Comment by dannyxx001** [comment]
OK, I had updated it.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Comment by PeterDaveHello** [comment]
@kennynaoh This branch is too old so need to rebase on latest master branch.

**Comment by kennynaoh** [comment]
@dannyxx001 
Please rebase master first.
Thanks.

**Comment by dannyxx001** [comment]
OK, I rebased it

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think it is on latest master branch
Please help me review it again.
Thanks.

**Pull request merged**
