### PR TITLE
Update licenses format of jquery-mockjax

### PR DESCRIPTION
**Pull request by kasony-zkcodeveryway**
Ref:https://github.com/jakerella/jquery-mockjax#license
cc #11931

### CODE REVIEW

**Comment by sufuf3** [comment]
@kasony-zkcodeveryway Would you create another PR for this updating licenses format?
Because there is no branch from your fork repository.
Maybe we can close this PR, and create another PR via the new branch.
What do you think?

Thank you.

**Comment by PeterDaveHello** [comment]
@sufuf3 the forked repo was deleted, so we can only close it.

**Comment by kasony-zkcodeveryway** [comment]
@sufuf3 Sorry about deleting the repo I forked before.Now, You can close this PR. Thank U!

**Comment by PeterDaveHello** [comment]
@kasony-zkcodeveryway and please don't do it again :)

**Comment by sufuf3** [comment]
@kasony-zkcodeveryway feel free to send the PR.
I'll close this PR, now.
Thank you all, guys.

**Comment by kasony-zkcodeveryway** [comment]
@PeterDaveHello  Sorry for my mistake. I would not do it again anyway.

**Comment by PeterDaveHello** [comment]
@kasony-zkcodeveryway nice 👍

**Pull request closed without merging**
