### PR TITLE
add QuickBlox v1.9.1

### PR DESCRIPTION
**Pull request by sakrist**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
What's the source of this lib?

**Comment by sakrist** [comment]
From here https://github.com/QuickBlox/quickblox-javascript-sdk

Documentation
http://quickblox.com/developers/Javascript

All links exists in package.json file

**Comment by PeterDaveHello** [comment]
Please also add auto-update config for it as #3638 said, thanks!

**Comment by sakrist** [comment]
Done.

**Pull request merged**
