### PR TITLE
[BreezeJS] Changed deprecated npm package to correct one in package.json autoupdate section. Also included official adapters to popular libraries

### PR DESCRIPTION
**Pull request by Nieralyte**
**GitHub:** https://github.com/Breeze/breeze.js
**npm:** https://www.npmjs.com/package/breeze-client

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
What's the reason why to transfer to use git auto-update from npm update?

**Comment by Nieralyte** [comment]
Previous version of a `package.json` [was pointing](https://github.com/Nieralyte/cdnjs/blob/7f1517b734d0434fc2833f32ff3fb7549341824e/ajax/libs/breezejs/package.json#L3) to [`breezejs`](https://www.npmjs.com/package/breezejs), a deprecated npm package, so I wanted to fix that. I saw in the cdnjs docs that the recommended way to autoupdate is via GitHub: https://github.com/cdnjs/cdnjs#enabling-gitrecommended-or-npm-auto-update

Should I revert to npm?

**Comment by PeterDaveHello** [comment]
I think you should talk about that change in your commit message, and though breezejs was deprecated, npm told us can use 'breeze-client' instead, maybe the better option will be update the npmName.
> npm WARN deprecated breezejs@1.5.3: Use 'breeze-client' instead

**Comment by Nieralyte** [comment]
@PeterDaveHello: please let me know if there's something i should change

**Comment by PeterDaveHello** [comment]
By this, [IMPORTANT - No more manual submissions](https://github.com/cdnjs/cdnjs#important---no-more-manual-submissions), would you please just update its auto-update config in one commit? And I think that's all in the PR, thanks!

**Pull request closed without merging**
