### PR TITLE
add Alertify js w/ npm autoupdate

### LINKED ISSUE #8568: [Request] Add AlertifyJS
This is a more modern and popular alertify JS... seems to be actively maintained. The currently alertify is to a different  library.

http://alertifyjs.com/
https://github.com/MohammadYounes/AlertifyJS

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8568 
@x09326 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/MohammadYounes/AlertifyJS
 * Official website (optional, not the repository): http://www.alertifyjs.com
 * NPM package url (optional):https://www.npmjs.com/package/alertifyjs
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 666
   - Count of watchers: 42
   - Count of forks: 123
 * NPM download stats (optional):
   - Downloads in the last day: 64
   - Downloads in the last week: 382
   - Downloads in the last month: 2007

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8568 , cc @MohammadYounes

### CODE REVIEW

**Comment by MohammadYounes** [comment]
Awesome! Thanks :+1: 

Also I would like to add link to the page of this library on CDNJS on website / readme

**Comment by PeterDaveHello** [comment]
@MohammadYounes Thanks.

**Comment by kennynaoh** [comment]
@pvnr0082t 
I think `https://alertifyjs.com` will be better.
Thanks!

**Comment by pvnr0082t** [comment]
@kennynaoh I think it doesn't support ssl.

**Comment by kennynaoh** [comment]
How to confirm this?

**Comment by pvnr0082t** [comment]
Because there is yellow exclamation mark when I try to access https://alertifyjs.com. Didn't you meet this? @kennynaoh

**Comment by kennynaoh** [comment]
OK, and sorry for my late response.
Please rebase to the latest master branch.
Thanks!

**Comment by pvnr0082t** [comment]
@x09326 @kennynaoh I have rebased on the latest master branch. Please help me review again, thank you.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Pull request merged**
