### PR TITLE
Add license of string_score, cc #9248

### PR DESCRIPTION
**Pull request by lcd78706**
https://github.com/joshaven/string_score/blob/master/LICENSE.md

### CODE REVIEW

**Comment by lcd78706** [comment]
@kennynaoh 
Please check this pull request. Thanks!

**Comment by kennynaoh** [comment]
@lcd78706 
Good job!
Maybe next time you can use `review` not `check`, and please remember to leave the comment in #9248 .
Thanks!

**Comment by kennynaoh** [comment]
LGTM
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
