### PR TITLE
[New] add ngMask v3.0.16 with git autoupdate

### PR DESCRIPTION
**Pull request by LeaYeh**
**git repo url:** https://github.com/candreoliveira/ngMask#ngmask
**Watch 15
  Star 169
 Fork 56**
@Piicksarn  could you help me check out the PR for #6171  ? thank you~
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Failed.

**Comment by LeaYeh** [comment]
fixed, but in my local ci was passed, i dont know why online ci is fail @@?

**Comment by PeterDaveHello** [comment]
You should check the build log ...

**Comment by PeterDaveHello** [comment]
and @LeaYeh please review some other PRs that waiting for you, thanks.

**Comment by LeaYeh** [comment]
@Piicksarn could check this again?

**Pull request merged**
