### PR TITLE
point to a stable version v0.4.0 of two.js

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11  , From #5276, I would like to fix two.js to point to a stable version.
repo: https://github.com/jonobr1/two.js
In cdnjs, two.js has auto-update config already, so it is the latest version now.
I only modify the field of version to a stable version `0.4.0`.
Would you mind checking this PR for me? Thank you~ :-)

- [ ] Not found on cdnjs repo : `two.js`
- [ ] No already exist issue and PR : `#5276`
- [x] Notable popularity : `4377` star, `2344` fork
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Murderer
https://github.com/cdnjs/cdnjs/commit/7832be9e4559bf016ceb659d54908e1784ee6792#diff-3a07e36be117d72fd43fa6a16ac48cea

**Comment by Amomo** [comment]
@PeterDaveHello what should I do for this?

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Comment by maruilian11** [comment]
@Amomo sorry for checking it late.
@PeterDaveHello i think it's fine.

**Pull request merged**
