### PR TITLE
Add Waffle Grid System

### PR DESCRIPTION
**Pull request by arguiot**
Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/lucasgruwez/waffle-grid/
 * Official website (optional, not the repository): https://lucasgruwez.github.io/waffle-grid/
 * NPM package url (optional): waffle-grid
 * License and its reference: MIT License
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 22
   - Count of stars: 447
   - Count of forks: 38
 * NPM download stats (optional):
   - Downloads in the last day: 3
   - Downloads in the last week: 189
   - Downloads in the last month: 530

# Essential checklist
(X = NO and V = Yes)
 * [ X] I'm the author of this library
   * [ V] I would like to add link to the page of this library on CDNJS on website / readme
 * [ X] This lib was not found on cdnjs repo
 * [ X] No already exist / duplicated issue and PR (exist an issue)
 * [ V] The lib has notable popularity
   * [ V] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ V] More than 500 downloads stats per month on npm registry
 * [V ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by hare1039** [comment]
Hi @arguiot,
Would you fork a branch and send another PR from that branch in order to make @PeterBot pass the test?

**Comment by PeterDaveHello** [comment]
@hare1039 s/Would you/Would you please/

**Comment by PeterDaveHello** [comment]
@hare1039 and ... 
1) you should give reference about the reason
2) i'm not sure if you are sure that this will fix the build failed.

**Comment by PeterDaveHello** [comment]
@extend1994 nice review 👍

**Comment by dalisoft** [comment]
- Status
  - [ ] Review required: Waiting... (please wait up to 24 hours)
  - [ ] Tests pass: Fail
  - [ ] Waiting for popuality: Required at least 500 downloads on npm

- Warnings
  - Please edit your change for pass test

- NOTE
  - If you not fix your warning, this PR maybe rejected without any reason

**Comment by PeterDaveHello** [comment]
@dalisoft hmmmm ... I don't think we need to add the comment to pull requests.

**Comment by dalisoft** [comment]
@PeterDaveHello we should notify them for fix, because he/she maybe missed test result?!

**Comment by PeterDaveHello** [comment]
@dalisoft our reviewers and the bot already did, if there is no response for too long, the bot will jump out to remind us, I don't want to put contributors under stress, thanks.

**Comment by dalisoft** [comment]
@PeterDaveHello then ok, thanks for reply. if need help, i here.

**Comment by dalisoft** [comment]
@hare1039 what steps? I am not reviewer and i am not see any docs after my pr closed (then merged)

**Comment by hare1039** [comment]
@dalisoft I mean the description extend1994 wrote on the comment(review).

**Comment by dalisoft** [comment]
@hare1039 you is reviewer? I think it is work of author of this lib, not our. So author of this lib should fix the issue

**Comment by hare1039** [comment]
@dalisoft Ohno. I mixup the id of yours and @arguiot.

I am extremely sorry for disturbing you. :cry:

@arguiot Would you fix this PR? Thanks!

**Comment by dalisoft** [comment]
@hare1039 all is ok even fine. You just helped me to avoid my bugs for cdnjs pr. After seen recommendation, i understand the example. Thanks for you. About id of user, all is ok

**Pull request closed without merging**
