### PR TITLE
Add big.js@3.1.3 w/ npm auto-update

### LINKED ISSUE #8587: [Request] big.js
**Library name:** big.js
**Git repository url:**https://github.com/MikeMcl/big.js/
**npm package url(optional):** https://www.npmjs.com/package/big.js
**License(s):**MIT
**Official homepage:**http://mikemcl.github.io/big.js
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by x09326**
PR for #8587
@pvnr0082t please help me review it, thanks.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/MikeMcl/big.js/
 * Official website (optional, not the repository):https://mikemcl.github.io/big.js
 * NPM package url (optional):https://www.npmjs.com/package/big.js
 * GitHub / Bitbucket popularity (required):
   - Count of stars:683
   - Count of watchers:36
   - Count of forks:80
 * NPM download stats (optional):
   - Downloads in the last day:67647
   - Downloads in the last week:385752
   - Downloads in the last month:1638398

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8587, cc @MikeMcl

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@x09326 There are 13 versions released on npm but 15 on GitHub. I think you can manually add old versions.

**Comment by x09326** [comment]
@pvnr0082t 
I added the versions that npm doesn't include.
Please help me review it, thanks.

**Comment by pvnr0082t** [comment]
@PeterDaveHello Is it ok to just add versions npm can't get? Or it's better to add all other versions?

**Comment by PeterDaveHello** [comment]
@pvnr0082t It's better to add them all.

**Comment by pvnr0082t** [comment]
@x09326 Please try to add all other versions, thank you.

**Comment by x09326** [comment]
@pvnr0082t 
I added all versions.
Please review it again, thanks.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
@pvnr0082t @x09326 looks like v3.1.1 is missing.

**Pull request merged**
