### PR TITLE
Added newest version of hover.css with autoupdate

### PR DESCRIPTION
**Pull request by AndreiTelteu**
Newest version with auto-update.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Thanks.

**Comment by AndreiTelteu** [comment]
Welcome. And thanks you guys for this great cdn :)
When will this be available on the website ?

**Comment by PeterDaveHello** [comment]
within 15 mins

**Comment by PeterDaveHello** [comment]
Hmmmm ... I noticed that the structure was a little bit wrong, because the bathPath is css, so we don't need to put them in css anymore, ha.

**Comment by PeterDaveHello** [comment]
I think I'll just remove the bathPath so that we can keep its structure as the old version.

**Pull request merged**
