### PR TITLE
Add angular-summernote v0.5.0 with git autoupdate

### PR DESCRIPTION
**Pull request by Piicksarn**
**`git repository : `** https://github.com/summernote/angular-summernote/tree/0.5.0
**`Watch : 22 /  Star : 126 /  Fork : 34`**

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by Piicksarn** [comment]
@maruilian11, would you mind to checkout the pr for me?
thank you! :blush:

**Comment by PeterDaveHello** [comment]
Why don't you assign ?

**Comment by maruilian11** [comment]
@Piicksarn i think this PR is ok. please rebase and tag me again, thanks.

**Comment by Piicksarn** [comment]
@maruilian11, would you mind to check it again?
thank you! :blush:

**Comment by maruilian11** [comment]
@Piicksarn haha sorry~ our time seems not match... can you rebase again? thank you!

**Comment by Piicksarn** [comment]
@maruilian11, i have it rebased!
thank you~~

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Pull request merged**
