### PR TITLE
added 6to5 v3.4.1 for usage in the browser

### PR DESCRIPTION
**Pull request by varemenos**
6to5 can also be used in the browser, it would be great to have it's files hosted via cdnjs

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please merge/squash these commits into only one commit as document said, thanks.

**Comment by varemenos** [comment]
@PeterDaveHello Hopefully everything is in order now

**Comment by PeterDaveHello** [comment]
Possible to add auto-update config for it?

**Comment by PeterDaveHello** [comment]
I think you brake the file browser.js, it should be only one line there.

**Comment by PeterDaveHello** [comment]
I added it in  43eeeb4

**Pull request closed without merging**
