### PR TITLE
Manually add tweenjs v0.6.2

### LINKED ISSUE #9146: [Request] Add tweenjs 0.6.2
**Library name:** 
tweenjs

**Git repository url:**
https://github.com/CreateJS/TweenJS.git

**npm package url(optional):** 

**License(s):**
MIT License

**Official homepage:**
http://www.createjs.com/tweenjs

**Wanna say something? Leave message here:**
tweenjs 0.6.0 is already hosted, but 0.6.2 (latest version) is not.
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #9146 
@x09326 Please help me review this pull request, thank you.

close #9146, cc #8766

### CODE REVIEW

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
No file source?

**Comment by PeterDaveHello** [comment]
Any possibility to apply auto-update?

**Comment by pvnr0082t** [comment]
@x09326 @PeterDaveHello I didn't add it because there is no source files in previous versions.

**Comment by pvnr0082t** [comment]
The files are named with version number. Should I ask author if it's possible to name the files without version?

**Comment by PeterDaveHello** [comment]
@pvnr0082t I mean where did you get the file, no body knows that. Please discuss with its author about the possibility of making it easier for our auto-update, thanks.

**Comment by pvnr0082t** [comment]
@PeterDaveHello Oh, I fetch the file from git repo.

**Comment by PeterDaveHello** [comment]
@pvnr0082t Okay, all the updates without auto-update config should provide that info.

**Comment by pvnr0082t** [comment]
@x09326 Because there is no response in https://github.com/CreateJS/TweenJS/issues/74, I remove version number from filename manually. Please help me review it again, thank you.

**Comment by pvnr0082t** [comment]
ping @x09326

**Comment by pvnr0082t** [comment]
@x09326 I have rebased onto the latest master branch. Please help me review again, thank you.

**Pull request merged**
