### PR TITLE
[Security] Do not link to http://owlgraphic.com

### PR DESCRIPTION
**Pull request by benmurden**
This domain is being used to redirect to sometimes malicious content.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@OwlFonk would you like to take a look? Thanks.

**Comment by PeterDaveHello** [comment]
https://www.virustotal.com/en/url/35b410330ab79a29371d4d70e98098957752c89e936eadeba0377b24163497e0/analysis/1490589922/
https://www.virustotal.com/en/url/a0d510e2b5115c2387173744f5d2c0a2e4ee0b7b9aa9af6b9f8bd26c2b404eee/analysis/

**Comment by PeterDaveHello** [comment]
```
$ curl -v "http://owlgraphic.com/owlcarousel/" > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 144.76.0.242...
* TCP_NODELAY set
* Connected to owlgraphic.com (144.76.0.242) port 80 (#0)
> GET /owlcarousel/ HTTP/1.1
> Host: owlgraphic.com
> User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
> Accept: */*
> Accept-Encoding: deflate, gzip
> Referer:
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Mon, 27 Mar 2017 04:55:12 GMT
< Content-Type: text/html; charset=utf8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/5.3.10-1ubuntu3.25
< Set-Cookie: ndsp=eyJkb21haW5OYW1lIjoib3dsZ3JhcGhpYy5jb20iLCJtZW1iZXIiOiI4IiwidGVtcGxhdGUiOiJzcGxpdHRlciIsInVzZXJBZ2VudCI6Ik1vemlsbGFcLzUuMCAoV2luZG93cyBOVCA2LjE7IFdPVzY0OyBydjo1Mi4wKSBHZWNrb1wvMjAxMDAxMDEgRmlyZWZveFwvNTIuMCIsInNlc3Npb24iOiJmNWRkMmZmZGI0NWU3ZDNmMWU0NmUzODkzNzQ5YzhmZSIsInRpbWVfaW5pdCI6MTQ5MDU5MDUxMn0%3D; expires=Mon, 27-Mar-2017 21:59:59 GMT; path=/
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Content-Encoding: gzip
<
{ [909 bytes data]
100   897    0   897    0     0    825      0 --:--:--  0:00:01 --:--:--   825* Curl_http_done: called premature == 0
100   897    0   897    0     0    824      0 --:--:--  0:00:01 --:--:--   825
* Connection #0 to host owlgraphic.com left intact
```

**Comment by benmurden** [comment]
Some more information.

As you have identified, the domain redirects to track.traffic.club, but it seems this then redirects to a number of potential 3rd party targets based on location. I had it redirect to a rackspace address with a malicious application.

In any case, this is clearly no longer under the control of the original creator of Owl Carousel and should not appear on the CDNJS website.

**Comment by PeterDaveHello** [comment]
@benmurden would you please also provide the url you been redirected to? THanks

**Comment by benmurden** [comment]
It first redirected here

https://s.arclk.net/

then here

http://461d28f441682fb84c6f-4918f73bc020a8744c78d1b0c6d723e0.r24.cf1.rackcdn.com/link/

I have omitted the query string variables which contained OS, IP address, ISP details, Country, and a Base64 encoded string with more IDs in it.

Needless to say this just returns 404 now, even with the original query string, probably to protect itself from probing or detection. The page made an `alert()` with the above details contained, showed a simple warning page with these details again, and urges the user to download a file - making it appear like a request from the user's ISP.

Virus Total shows nothing, as expected.

Again, it's clear that the author is no longer in control of the domain - at best, it redirects to advertising. It has no place being associated with this application or appearing on CDNJS.

**Comment by PeterDaveHello** [comment]
@benmurden thank you very much for your report, please give me 24 hours for waiting response from the author, if there is no response within 24 hours, I'll directly remove that link, thanks again!

**Comment by benmurden** [comment]
@PeterDaveHello Thanks for the quick responses. Hope I can save someone else the unwelcome surprise!

**Comment by PeterDaveHello** [comment]
https://www.virustotal.com/en/url/76c5d83c426b8878fb866f2a8a96cfa2cd49646956909fef4245cab54ee608d6/analysis/1490703404/

**Pull request merged**
