### PR TITLE
[author] [new] ProStyle animation library v1.0.0

### PR DESCRIPTION
**Pull request by GaryChamberlain**
ProStyle is a new free library that makes it easy to build complex animation sequences on top of Greensock's GSAP.  Animations are written using a declarative JSON syntax.

Thanks!!!

website:  https://prostyle.io
npm: https://www.npmjs.com/package/prostyle

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hi @GaryChamberlain, would you please squash them into only one commit as our document says? Thanks!

**Comment by GaryChamberlain** [comment]
Sorry about that.  They are now squashed.  Thanks!

Date: Sat, 12 Sep 2015 18:54:26 -0700

**Comment by PeterDaveHello** [comment]
hmmmm ... thanks, I just tool a look at the repo, according to the property and goal, we hope the libs we hosted should have notable popularity, would you mind to wait for a few days and get higher popularity in this period? Thanks.

**Comment by GaryChamberlain** [comment]
@PeterDaveHello 
* It has over 50 downloads on NPM this week.
* It's up to 30 stars on the GitHub repo and growing, including both of the Greensock guys. (ProStyle extends GSAP)
* The three initial animations that I placed on CodePen have over 2000 views and several hearts, plus I plan to add many more pens once it is on CDNJS.
    * http://codepen.io/garyc/details/OyMmvB/
    * http://codepen.io/garyc/details/GpoNGB/
    * http://codepen.io/garyc/details/zvrZPX/

Is that enough?

**Comment by PeterDaveHello** [comment]
oh okay, would you please rebase your branch with our latest master branch? Or if you don't mind, I will manually cherry-pick your commit into master branch, thanks!

**Comment by GaryChamberlain** [comment]
@PeterDaveHello Good Now?

**Comment by PeterDaveHello** [comment]
Hmmm ... nope, we use rebase instead of merge here.

**Comment by PeterDaveHello** [comment]
Anything I can help? Or if you don't mind, I can manually pick that commit instead of merge directly, so that it'll be easier for you.

**Pull request closed without merging**
