### PR TITLE
Add exceljs

### LINKED ISSUE #9463: [Request] Add exceljs
**Library name:** exceljs
**Git repository url:** https://github.com/guyonroche/exceljs
**npm package url(optional):** https://www.npmjs.com/package/exceljs
**License(s):** MIT
**Official homepage:** https://github.com/guyonroche/exceljs
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by iffy**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/guyonroche/exceljs
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/exceljs
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 1,364
   - Count of watchers: 84
   - Count of forks: 185
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [X] This lib was not found on cdnjs repo
 * [X] No already exist / duplicated issue and PR
 * [X] The lib has notable popularity
   * [X] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [X] More than 500 downloads stats per month on npm registry
 * [X] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

Fixes #9463

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@iffy I didn't see so many files on GitHub and NPM. I'd like to know why there are too many files you commited. Thanks.

**Comment by iffy** [comment]
@pvnr0082t I don't really know what I'm doing.  I just ran `cdnjs-importer -g 'https://github.com/guyonroche/exceljs' -p ~/lib/cdnjs/` and committed whatever it did (see Issue #9463)

And actually, ExcelJS may not be browser-ready (I'm still trying to get it to work), so I'm not sure if it makes sense to CDN it.

**Comment by PeterDaveHello** [comment]
@iffy maybe you can contact with the author to make sure it'll work in browser then we can help you add this one?

**Comment by iffy** [comment]
@PeterDaveHello sounds good; I'll close this until that happens.

**Comment by PeterDaveHello** [comment]
Thanks @iffy , please let us know if there is any update!

**Pull request closed without merging**
