### PR TITLE
remove duplicated content in mojio-js, close #5372

### LINKED ISSUE #5372: there's a version of mojio-js named "oauth-token"
Over here: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/mojio-js/oauth-token. Not that I use it or anything, I just noticed while browsing the repo.

Probably caused by this: https://github.com/mojio/mojio-js/releases/tag/oauth-token

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 , from issue #5372, mojio-js has a version named `oauth-token` whose content is duplicated with v3.5.2. For this reason, I would like to remove it from cdnjs's repo.
Would you mind checking this PR for me? Thank you~ :-)
repo: https://github.com/mojio/mojio-js

### CODE REVIEW

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Comment by PeterDaveHello** [comment]
We don't delete files, it may break the websites currently using cdnjs.

**Comment by maruilian11** [comment]
@Amomo i think you can rebase it and tag me again :)

**Comment by Amomo** [comment]
@maruilian11 I have rebased it, could you take a look? Thanks~ :-D

**Pull request merged**
