### PR TITLE
[new] Adding jquery-datepicker-skins

### PR DESCRIPTION
**Pull request by elvisguillen**
Adding the Jquery Datepicker Skins library and assets. Also included the autoupdate tag in the package file.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Thanks for your PR, I noticed that there is no any version info in its repo, so it'll be better to confirm with the author first, would you please make sure for us? thanks!

**Comment by elvisguillen** [comment]
Just contacted the author to confirm. Is there any way this can be uploaded any sooner? Thanks.

**Comment by PeterDaveHello** [comment]
Once we make sure the specified version, we'll have on cdn!

**Comment by drewfreyling** [comment]
Closing due to a lack of tags in git repo.

**Pull request closed without merging**
