### PR TITLE
Added bubbly-bg package.json

### PR DESCRIPTION
**Pull request by VarunWachaspati**
Pull request for issue: #11974
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/tipsy/bubbly-bg
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/bubbly-bg
 * License and its reference: Apache License 2.0
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 20
   - Count of stars: 972
   - Count of forks: 40
 * NPM download stats (optional):
   - Downloads in the last day: 7
   - Downloads in the last week: 74
   - Downloads in the last month: 328

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by VarunWachaspati** [comment]
@maruilian11 Sorry for that, can you have a look at it now

**Comment by VarunWachaspati** [comment]
@maruilian11 Is there any way to rebase my PR without actually git cloning, running on a low Internet Bandwidth here  :sweat_smile:
My commit should solve the issues listed most certainly though
Kindly let me know

**Comment by PeterDaveHello** [comment]
@VarunWachaspati we can help you do it.

**Comment by maruilian11** [comment]
@VarunWachaspati Sorry, I just found there is another PR working on the same issue. Due to the open timing, I afraid I need to close this one. Please feel free to take another PR. And Please see if any PR has open for it. You can tell them by looking down the issue. https://github.com/cdnjs/cdnjs/pull/11982

**Pull request closed without merging**
