### PR TITLE
Add license of helium-css, cc #5500

### PR DESCRIPTION
**Pull request by lcd78706**
Ref: https://github.com/geuis/helium-css/blob/master/helium.js

### CODE REVIEW

**Comment by lcd78706** [comment]
@kennynaoh 
Please review this PR. Thanks!

**Comment by kennynaoh** [comment]
@lcd78706 The reference should be more precise next time, like https://github.com/geuis/helium-css/blob/master/helium.js#L3, thanks

**Comment by kennynaoh** [comment]
LGTM
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
