### PR TITLE
Update the tests for the autoupdate multi filemap.

### LINKED ISSUE #9155: Multi-filemap support in `autoupdate` field
Currently, the `autoupdate` field in `package.json` only support single base path with single file list like this:

``` js
  "autoupdate": {
     "source": "git",
     "target": "git://github.com/cdnjs/cdnjs.git",
     "basePath": "",
     "files": [
       "*.json"
     ]
  }
```

We did support multi-filemap in npm auto-update like this (take `waterfall.js` as example):

``` js
  "npmName": "waterfall.js",
  "npmFileMap": [
    {
      "basePath": "",
      "files": [
        "waterfall*"
      ]
    },
    {
      "basePath": "src",
      "files": [
        "waterfall*"
      ]
    }
  ]
```

We should also support the same feature in `autoupdate` field though it is used for git auto-update only, once multi-filemap support added, we can migrate `npmName` and `npmFileMap` to `autoupdate` format.

The multi-filemap should looks like this in `package.json` once it's implemented:

``` js
  "autoupdate": {
    "source": "git",
    "target": "git://github.com/cdnjs/cdnjs.git",
    "fileMap": [
      {
        "basePath": "",
        "files": [
          "*.json"
        ]
      },
      {
         "basePath": "",
         "files": [
           "*.js"
        ]
      }
    ]
  }
```

PS: the auto-updater is in [cdnjs/autoupdate](https://github.com/cdnjs/autoupdate) repo, the corresponding issue there is cdnjs/autoupdate#13

The test cases for `package.json` and example should also be updated at the same time.

### PR DESCRIPTION
**Pull request by IonicaBizau**
Fix #9155. :boom:

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@pvnr0082t please join us to test the behavior of this change!

**Comment by PeterDaveHello** [comment]
@IonicaBizau this would need to deliver with the change in package.json like #9199 #9192 , thanks.

**Comment by IonicaBizau** [comment]
What do you mean?

**Comment by PeterDaveHello** [comment]
@IonicaBizau Since the test updated, we need the auto-update also been updated at the same PR.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Can you check if the changes look good?

**Comment by PeterDaveHello** [comment]
@IonicaBizau the test failed.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Checking locally...

**Comment by PeterDaveHello** [comment]
@cdnjs/intern2 please try to confirm its behavior, make sure it's working with cdnjs/autoupdate#24

**Comment by pvnr0082t** [comment]
I pick `paste.js` which use git auto-update for the test.
```json
"autoupdate": {
  "source": "git",
  "target": "git://github.com/layerssss/paste.js.git",
  "basePath": "",
  "fileMap": [
    {
      "basePath": "",
      "files": [
        "paste*.+(js|css|map)"
      ]
    }
  ]
}
```
I added string type `"basePath"` out of fileMap and it can pass the test, and even non-string type can pass  the test.
I think we should not allow `"basePath"` out of filemap array if we apply multi-filemap, and the `"basePath"` out of filemap and in filemap also make more confused.

**Comment by PeterDaveHello** [comment]
@pvnr0082t you're right, @IonicaBizau we should try to drop and prevent the old one appear, also, the doc - documents/autoupdate.md needs to be updated.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Oh, yes! I will work on these tomorrow.

**Comment by PeterDaveHello** [comment]
@IonicaBizau just remind you that you'll need rebase with the latest master branch to "fix" the new added "package.json"s again, thanks.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Waiting for the tests.

**Comment by IonicaBizau** [comment]
@PeterDaveHello The tests passed.

**Comment by PeterDaveHello** [comment]
cdnjs/autoupdate#24 looks not working, pending for confirmation

**Comment by PeterDaveHello** [comment]
Hi @IonicaBizau, I think it does work, something may be wrong on my computer, would you please resolve the conflicts and update few tiny tests about fileMap part in the test and then we can merge these two PRs? Many thanks!

**Comment by IonicaBizau** [comment]
Moved in #9461. :rocket:

**Pull request closed without merging**
