### PR TITLE
Add license of hinclude, cc #9248

### PR DESCRIPTION
**Pull request by jj528s35**
https://github.com/mnot/hinclude/blob/master/LICENSE

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@jj528s35 Please remember to give a meaningful branch name next time.

**Comment by pvnr0082t** [comment]
@PeterDaveHello It seems that CI test got some errors. Please help me trigger CI again. Thank you.

**Comment by pvnr0082t** [comment]
LGTM
@cdnjs/intern2

**Comment by kennynaoh** [comment]
LGTM

**Pull request merged**
