### PR TITLE
[new] [author] Add angular-material-icons with auto-update

### PR DESCRIPTION
**Pull request by urmilparikh**
With all files.
https://github.com/klarsys/angular-material-icons

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please remove the files will not be served on cdn and squash all the commits into only one commit as our document said, thanks!

**Comment by urmilparikh** [comment]
Done.

**Comment by PeterDaveHello** [comment]
I think you missed the filename field to point to the main file.

**Comment by urmilparikh** [comment]
Added filename as well.

**Comment by PeterDaveHello** [comment]
Oops, you should put angular-material-icons.min.js in 0.4.0 directory, thanks.

**Comment by urmilparikh** [comment]
No problem!

**Comment by PeterDaveHello** [comment]
Looks good now!

**Comment by urmilparikh** [comment]
Thank you!

**Comment by PeterDaveHello** [comment]
np

**Pull request merged**
