### PR TITLE
Add jquery-highlighttextarea@3.1.3 w/ git auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
@Amomo @Piicksarn could u help me check this PR for #9235? thank you!
**I also add versions can't be got from npm package.**

**git repo url:** https://github.com/garysieling/jquery-highlighttextarea
**Watch 9
  Star 103
 Fork 59**

**npm package url:** https://www.npmjs.com/package/jquery-highlighttextarea
**0 downloads in the last day
43 downloads in the last week
109 downloads in the last month**

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR 
- [x] The lib has notable popularity  
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry 
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update) 
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by Piicksarn** [comment]
Wrong git repo url in pr comment message.
Commit itself is fine.

**Comment by maruilian11** [comment]
@Piicksarn thank you for your review and point the wrong repo url, I have rebased this commit upon our latest master branch, could you help me check it again? thanks!

next time you can tell me to rebase the commit first, then review the PR.

**Comment by Piicksarn** [comment]
LGTM

**Comment by maruilian11** [comment]
@Piicksarn could you please ping Peter after LGTM, thanks~

**Comment by Piicksarn** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by maruilian11** [comment]
@cdnjs/intern2 Please help me review this PR, thanks!

**Comment by maruilian11** [comment]
@cdnjs/intern2 I updated the commit, thanks.

**Comment by maruilian11** [comment]
@PeterDaveHello because `Add jquery-highlighttextarea@3.1.3 w/ git auto-update` will be over 50 characters. Do you have any better idea? thanks.

**Comment by PeterDaveHello** [comment]
@maruilian11 We can accept that you don't have another whole word after 50th char, the last word could be acceptable.

**Comment by PeterDaveHello** [comment]
Please ping me if you didn't see the CI been triggered with 10 secs next time.

**Comment by maruilian11** [comment]
ok

**Pull request merged**
