### PR TITLE
[Author] [New] Add js-popup

### PR DESCRIPTION
**Pull request by exelban**
Pull request for issue: #10972 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/exelban/js-popup
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/js-popup
 * License and its reference: Apache License 2.0
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 0
   - Count of stars: 0
   - Count of forks: 0
 * NPM download stats (optional):
   - Downloads in the last day: 20
   - Downloads in the last week: 20
   - Downloads in the last month: 20

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@sufuf3 please help @exelban finish this pull request!

**Comment by PeterDaveHello** [comment]
@exelban would you please send your pull request from a non-master branch with meaningful naming?


'**Creating and deleting branches within your repository**' Reference:
https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/

For the reason why we need to create a new branch for every pull request, please refer to the GitHub Flow: https://guides.github.com/introduction/flow/index.html

Thanks!

**Comment by exelban** [comment]
Ok, now i will change change branch.

**Comment by PeterDaveHello** [comment]
@exelban thanks! Btw, package.json should be under the root of the library folder, not the version folder.

**Comment by exelban** [comment]
Ok, i create new brunch in my fork. How i can merge new commits?

**Comment by PeterDaveHello** [comment]
@exelban you mean squash all the commits into one commit?

**Comment by exelban** [comment]
Yes.
I must to create new PR from my exelban/js-popup branch?

**Comment by PeterDaveHello** [comment]
@exelban nope, you just need to create a new branch from your exelban/cdnjs, from master to maybe js-popup

**Comment by PeterDaveHello** [comment]
@exelban there is no way to squash/fixup commits on GitHub gui, it'll need to be done locally, we can do that for you, or if you wanna learn how to do it, we'll be happy to help.

**Comment by exelban** [comment]
@PeterDaveHello Ok, i create new js-popup branch. And make dafault this branch.

**Comment by PeterDaveHello** [comment]
@exelban oh you don't need to make it default, anyway, let's see your new PR :)

**Comment by exelban** [comment]
@PeterDaveHello i must make new PR?

**Comment by PeterDaveHello** [comment]
@exelban yes, I think it's not hard at all?

**Comment by PeterDaveHello** [comment]
@exelban your progress will still be there, you don't need to redo all the commits again

**Comment by PeterDaveHello** [comment]
Move to #10975

**Pull request closed without merging**
