### PR TITLE
Add vue-validator v1.4.3 with git autoupdate

### PR DESCRIPTION
**Pull request by Piicksarn**
**`git repository : `** https://github.com/vuejs/vue-validator/tree/v1.4.3
**`Watch : 11 /  Star : 105 /  Fork : 22`**

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by Piicksarn** [comment]
@Amomo, would you mind to have a look at the pr? thank you~^^

**Comment by Amomo** [comment]
@Piicksarn sorry for checking it late.
I think this PR is fine, could you please rebased it to match latest master branch?
Thank you~

**Comment by Piicksarn** [comment]
@Amomo, i have the pr rebased to master! 
thank you~^^

**Comment by Amomo** [comment]
@Piicksarn sorry...I'm late again...😨
Could you please rebased it again? Thank you!

**Comment by Amomo** [comment]
@Piicksarn It seem this PR meet #5538 "Size issue in CI" bug, could you send your commit again?
Thank you!

**Comment by Piicksarn** [comment]
@Amomo, it pass the online check now!
thank you for checking so many time~~

**Comment by Amomo** [comment]
@Piicksarn It's fine~ but could you rebase it with the latest master branch?

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine, could you take a look?
Thank you~ :-D

**Comment by PeterDaveHello** [comment]
vue-validate or vue-validator?

**Comment by Piicksarn** [comment]
is vue-validator...
sorry, @Amomo i need your help for checking again...thank u~~!

**Comment by Amomo** [comment]
Sorry, I didn't check out that...
@PeterDaveHello I think Piicksarn has corrected it, this PR is fine.
Could you come to check again? Thank you!

**Pull request merged**
