### PR TITLE
[New][Author] Add Font-Awesome-datauri@1.0.0 w/ git auto-update

### PR DESCRIPTION
**Pull request by mwordpress**
Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/mwordpress/Font-Awesome-datauri
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:
   - Count of stars:
   - Count of forks:
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@mwordpress Thanks for the PR, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). would you please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail? It's always good to read the document before open an issue or a PR, I'll respectfully suggest you open a new issue or a PR again when the library has some notable popularity.

If you really want to add this library in CDNJS or you have something else want to discuss with us, please let us know. (We need to discuss the popularity issue and let owner decide it.)
if there is no any response in next 7 day, this PR will be closed.

Thanks for being interested in CDNJS.

PS. We add the lib relay on [git tag](https://github.com/mwordpress/Font-Awesome-datauri/tags) to add the files, but there is no git tag in this repo. If you really want to add the lib, maybe add a git tag is a good way, what do you think?
Also, if there is a `package.json` file in repo, it's good for the lib. you could add the file in your repo. Here is a tutorial: https://docs.npmjs.com/files/package.json.

Many thanks.

**Comment by mwordpress** [comment]
its new library 
im doing some changes 
https://github.com/mwordpress/Font-Awesome-datauri

**Comment by sufuf3** [comment]
There is still no git tag: https://github.com/mwordpress/Font-Awesome-datauri/tags
Would you add it?
I can't figure out the relationship between your repo and http://fortawesome.github.io/Font-Awesome/ .
Is the repo be rewrote from FortAwesome/Font-Awesome?
Or Would you please tell us more detail info?

Many thanks.

**Comment by mwordpress** [comment]
@sufuf3 look now https://github.com/mwordpress/Font-Awesome-datauri/tags

my repo use ([Data URI](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs)) to minimize http requests for modern browser this make page too fast

**Comment by sufuf3** [comment]
Thank you.
Let's wait for maintainer's response.
@PeterDaveHello Would you mind taking a look in this PR?
This PR sent by the lib's author, but the lib doesn't have enough notable popularity.
Not sure, how to do this.
Many thanks.

**Comment by mwordpress** [comment]
@sufuf3 thank you are send me to last stage :) @PeterDaveHello Wait to take my breath

**Comment by mwordpress** [comment]
@sufuf3 @PeterDaveHello note this repo will be used in my products ([this my store](https://store.mwordpress.net/))
i have many customers will use it on their site (news) if you care about cache

**Comment by sufuf3** [comment]
Thanks for the detail information.
This two weeks, the maintainer maybe can't connect to internet.
I think he is fulfilling his mandatory military service, but I'm not sure.
This is just my guess.
So, would you please wait patiently?
Many thanks.

**Comment by mwordpress** [comment]
@sufuf3 it done hosted on [jsdelivr](https://cdn.jsdelivr.net/npm/fa-datauri/) any way good luck for @PeterDaveHello in his mandatory military service

**Pull request closed without merging**
