### PR TITLE
add bitgo v0.11.68

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/BitGo/BitGoJS
**npm package url:**　https://www.npmjs.com/package/bitgo
**5,189 downloads in the last month**
@Amomo could u help me check this PR for #6109 ? thank you!

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [x] The lib has notable popularity
  - [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [x] More than 500 downloads stats per month on npm registry
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
This lib need manually build, you can not just add the src.

**Comment by maruilian11** [comment]
@PeterDaveHello so how do we add lib which needs manually build?

**Comment by PeterDaveHello** [comment]
Build and add, but no auto-update, we need discussion, you should confirm that there is no official build first, and maybe we can ask the author if is possible to have it.

**Comment by maruilian11** [comment]
@PeterDaveHello 
https://github.com/BitGo/BitGoJS/issues/28#issuecomment-223828150
>Thanks for the consideration. I'm concerned about serving crypto libraries from a CDN for security reasons and would generally vote that we not do this.

does that means we had better not add this lib to cdnjs?

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by maruilian11** [comment]
@PeterDaveHello still waiting for the issue response.

**Comment by maruilian11** [comment]
@PeterDaveHello Still get no response from BitGo team in the issue, do we keep waiting?

**Comment by PeterDaveHello** [comment]
Let's close this.

**Pull request closed without merging**
