### PR TITLE
Add react-dom w/ npm auto-update

### LINKED ISSUE #11640: [Question] React 16 Alphas/Betas Not Available?
They've been published in NPM / unpkg and previous alphas are available; however, version 16 alphas do not show up in CDNJS.

Is something not working?

Reference: https://cdnjs.com/libraries/react

### PR DESCRIPTION
**Pull request by virgofx**
close #11640

Pull request for issue: #11640
Related issue(s):  #11642 

**This is the complementing package for React 16.x**

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/facebook/react
 * Official website (optional, not the repository): https://facebook.github.io/react/
 * NPM package url (optional): https://www.npmjs.com/package/react-dom
 * License and its reference: https://github.com/facebook/react/blob/master/LICENSE
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 4,773
   - Count of stars: 72,332
   - Count of forks: 13,614
 * NPM download stats (optional):
   - Downloads in the last day: 153,008
   - Downloads in the last week: 1,016,913
   - Downloads in the last month: 4,105,149

# Essential checklist
 * [ ] I'm the author of this library
 * [X] I would like to add link to the page of this library on CDNJS on website / readme
 * [X] This lib was not found on cdnjs repo
 * [X] No already exist / duplicated issue and PR
 * [X] The lib has notable popularity
   * [X] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [X] More than 500 downloads stats per month on npm registry
 * [X] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [X] Has valid tags for each versions (for git auto-update)
 * [X] Auto-update setup
 * [X] Auto-update target/source is valid.
 * [X] Auto-update filemap is correct.

# Git commit checklist
 * [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X] The parent of the commit(s) in the PR is not old than 3 days.
 * [X] Pull request is sending from a non-master branch with meaningful name.
 * [X] Separate unrelated changes into different commits.
 * [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [X] Close corresponding issue in commit message
 * [X] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by virgofx** [comment]
@sufuf3 👍

**Comment by virgofx** [comment]
@sufuf3 👍

**Comment by virgofx** [comment]
ping @mercyg @hare1039 @PeterDaveHello

**Comment by virgofx** [comment]
Yes, it's separate now.

**Comment by virgofx** [comment]
@extend1994 Yes, both trees need to be included as it's the new defacto standard for supplying different variations of the package based on module bundler.

**Comment by virgofx** [comment]
No need to minify that one. Again, just pushing the contents of the directories *as is* will work fine. That file specifically does not have a minified/production version because it's intended for 100% development only.

**Comment by sufuf3** [comment]
@virgofx Thank you.
I have a question about `react-dom-test-utils.development.js`, is this file can use in web front-end? Like `<script src="react-dom-test-utils.development.js"></script>`

**Comment by virgofx** [comment]
Theoretically, yes. In general, most people will use this file directly from NPM for local testing; however, there are cases where static CDN versions may be required.

**Comment by sufuf3** [comment]
Then I think maybe we should exclude `*.development.*`, because when a new version release, CDNJS will generate `*.development.min.js` I think it's not a good idea to generate these files. And with `*.development.js` these files, most of the developers may modify their self.
@virgofx @extend1994 What do you think?
@PeterDaveHello could you give us some suggestions?

Thank you all.

**Comment by virgofx** [comment]
Is there any way without doing an exclude filter to just use the files provided in the library? We want to include other development* resources so doing an exclude would not work. We just don't want CDNJS to do any auto-magic generation.

**Comment by sufuf3** [comment]
@virgofx Thank you very much.
I think the files are good, just a little concern.
Let's wait for @extend1994 and @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@extend1994 @sufuf3 can you fetch the file `react-dom-unstable-native-dependencies.development.js` properly?

**Comment by extend1994** [comment]
@PeterDaveHello No, The rule in https://github.com/cdnjs/cdnjs/blob/master/auto-update.js#L188 filters this file. Sorry for not noticing this.

**Comment by PeterDaveHello** [comment]
So isn't there an inconsistent issue here? As it's added in the commit?

**Comment by extend1994** [comment]
Yes, it's an inconsistent issue.
@virgofx Can we exclude the file react-dom-unstable-native-dependencies.development.js? It seems 
okay without this file to use the library well.

**Comment by PeterDaveHello** [comment]
@extend1994 we need to figure out the reason why that we need to include or exclude it, I didn't see it here. It's good to see you traced the program, but it's not the reason why we should directly exclude the files can't be fetched, on the other hand, you should figure out(or maybe with some guessing) what's the reason why the program is doing this, is that a bug or feature? Can we do something with it to solve the issue here? I doubt you know what am I saying.

**Comment by extend1994** [comment]
@PeterDaveHello I used `git blame` to see the reason this rule was written and it's https://github.com/cdnjs/cdnjs/commit/00c8d8119a23985aaca2fddc2ea3fe0270352201. I think the reason we exclude the files involving "dependencies" is that dependencies files are commonly used to trace the dependencies, which is not required for the library users. And I found the commit(https://github.com/facebook/react/commit/cff012fc16ea6e7f40398410aacc3be20dc39804) and the issue(https://github.com/facebook/react/pull/10138) about react-dom-unstable-native-dependencies.development.js, but I can not be certain that do we (or not) need this file because I think I don't have enough knowledge about react. Based on last a few questions we asked, virgofx seemed to quite understand how react works, I think it would be better to directly ask virgofx.

Here is the quote of the commit:
>* Add react-dom-unstable-native-dependencies

react-native-web and react-primitives currently access a few internals
for shimming DOM events into native ones.  Changes in react@16 packaging
hide these internals completely.  This change adds a submodule to react-dom,
unstable-native-dependencies that includes the necessary modules to
continue enabling that method of dom-native event injection.

I am not sure if the above is enough or not. If it's not enough, could you please give some suggestions here?

**Comment by virgofx** [comment]
If the CDNJS process excludes that file, it's okay. The primary use of the CDN will be for production assets. I would argue that this get merged sooner and that rational for excluding files based on the CDNJS auto/build/pull process get resolved separately as this PR has been open for way too long and many people are just using unpkg as it doesn't have to go through the same issues here.

**Comment by virgofx** [comment]
Can we get this merged please :)

**Comment by PeterDaveHello** [comment]
@virgofx we're working on this as you can see, the auto-update issue needs to be fixed, feel free to contribute if you'd like to :)

**Comment by PeterDaveHello** [comment]
@extend1994 let's try to improved auto-update.js?

**Comment by extend1994** [comment]
@virgofx Sorry for late reply! I am trying to fix this. Hope it would be done soon.

**Comment by PeterDaveHello** [comment]
A small issue here, I don't think both of the commit message should contain `w/ npm auto-update` string, only the commit with auto-update config should do that, not sure if it's added by @virgofx @sufuf3 or @extend1994 ?

**Comment by PeterDaveHello** [comment]
Oops, I got it, there are two versions of auto-update here, which may be a little be odd ... I'll dig into it.

**Comment by PeterDaveHello** [comment]
@virgofx @sufuf3 @extend1994 do we need to have an old auto-update config and change it immediately? Otherwise, this PR looks good to me, I'll update the auto-update program.

**Comment by virgofx** [comment]
Not sure about rational for 2 versions. I believe that was required to keep the current one stable -- which is the recommended approach for CDNJS

**Comment by PeterDaveHello** [comment]
@extend1994 why did you touched the commits without any comment?

@virgofx as you use two different auto-update config here, once they are merged, the first one would never work, that's the strange point, if we'd like to add the old versions here, the method would be to manually add them.

**Comment by virgofx** [comment]
Well originally that was done per request; however, we can change it. Seeing as the current `react` houses the `react-dom` up to 15.6.x, but won't moving forward with 16, we could just use the latest/beta versions (so maybe no changes needed) Otherwise, let me know ... This should be pretty straightforward ... just need to add `react-dom` hosted on CDNJS, autopull from NPM. That simple.

**Comment by PeterDaveHello** [comment]
@virgofx Thanks for the explanation, just to confirm if @sufuf3 and @extend1994 helped organized the current two commits here? Looks like we should remove the auto-update config in the previous commit ;)

**Comment by virgofx** [comment]
Yeah, I think they've have been updates to the current versions. Trying to make changes is rather difficult as even with sparse checkout the library is too big. Anyway @sufuf3 or @extend1994 or you could just update as necessary?

**Comment by PeterDaveHello** [comment]
@virgofx Yeah I'll assign @sufuf3 to help revise this PR.

**Comment by virgofx** [comment]
Ok yah if she can revise that be great, otherwise let me know. Looking forward in finally getting this merged :+1:

**Comment by PeterDaveHello** [comment]
@virgofx it'll be done just tomorrow, it's 2:34 AM here, we need to prepare to get rest and the other works now :)

**Comment by extend1994** [comment]
@virgofx @PeterDaveHello Sorry for directly touching the commit and not leaving any comments. I thought @PeterDaveHello you want me to do it. No next time. 
The current organization was followed by https://github.com/cdnjs/cdnjs/pull/11647#pullrequestreview-55111396 by @sufuf3.

**Comment by sufuf3** [comment]
Manually add `16.0.0-alpha*` versions because there are more versions `15.0.2-alpha*` in the commit.
Help removed the auto-update config in the first commit, and modify the first commit message.
@cdnjs/active-contributor @cdnjs/intern3 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@extend1994 As this comment https://github.com/cdnjs/cdnjs/pull/11647#issuecomment-326265124 said
>  I don't think both of the commit message should contain w/ npm auto-update string, only the commit with auto-update config should do that

I don't think we need to mention it, because I really add them manually. Thanks

**Comment by extend1994** [comment]
@sufuf3 I didn't mean you should mention `w/ npm auto-update` in current `Manually add v0.14.0 ~ v16.0.0-alpha.6 of react-dom` commit. I meant maybe you should exchange the order of two commits. Because when we add files with git/npm auto-update and manually add files. The commit with auto-update are always made before the commit with manual adding files.

**Comment by sufuf3** [comment]
Why I don't change because the version filed, which need to at stable version (v15.6.1)
If I exchange the first commit about version filed I don't know what version I have to fill in.
Thank you.

**Comment by extend1994** [comment]
@cdnjs/intern3 @cdnjs/library-reviewer @cdnjs/active-contributor Please help review this PR, thank you.

**Comment by sufuf3** [comment]
@pvnr0082t @maruilian11 Please help review this PR, thank you.

**Comment by virgofx** [comment]
Thanks @PeterDaveHello , Looks good 👏

**Comment by PeterDaveHello** [comment]
@virgofx thanks for your contribution dude!

**Pull request merged**
