### PR TITLE
[new] Added backbone.modal@1.1.5

### PR DESCRIPTION
**Pull request by TattdCodeMonkey**
[Backbone.Modal](http://awkward.github.io/backbone.modal/)

[Github](https://github.com/awkward/backbone.modal)

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please remove `LICENSE` and add git auto-update config for it.

**Comment by TattdCodeMonkey** [comment]
changes made

**Comment by PeterDaveHello** [comment]
Should also provide minified css files, thanks.

**Comment by TattdCodeMonkey** [comment]
This isn't my library just something I'm using. I was providing what is in the official release. While I could add minified css for this PR, it would not be there for updates.

**Comment by PeterDaveHello** [comment]
Yeah. Our document already said that should provide it, don't worry about the updates.

**Comment by TattdCodeMonkey** [comment]
Added minified CSS

**Comment by PeterDaveHello** [comment]
```
 create mode 100755 ajax/libs/backbone.modal/1.1.5/backbone.marionette.modals-min.js
 create mode 100755 ajax/libs/backbone.modal/1.1.5/backbone.marionette.modals.js
 create mode 100755 ajax/libs/backbone.modal/1.1.5/backbone.modal-bundled-min.js
 create mode 100755 ajax/libs/backbone.modal/1.1.5/backbone.modal-bundled.js
 create mode 100644 ajax/libs/backbone.modal/1.1.5/backbone.modal-min.css
 create mode 100755 ajax/libs/backbone.modal/1.1.5/backbone.modal-min.js
 create mode 100755 ajax/libs/backbone.modal/1.1.5/backbone.modal.css
 create mode 100755 ajax/libs/backbone.modal/1.1.5/backbone.modal.js
 create mode 100644 ajax/libs/backbone.modal/1.1.5/backbone.modal.theme-min.css
 create mode 100755 ajax/libs/backbone.modal/1.1.5/backbone.modal.theme.css
 create mode 100755 ajax/libs/backbone.modal/package.json
```
Wrong file permission here ... will fix it by myself.

**Comment by TattdCodeMonkey** [comment]
Thanks!

**Pull request closed without merging**
