### PR TITLE
Add flow.js v2.9.0 with git autoupdate config.

### LINKED ISSUE #5911: [Request] Add _Flow.js_
**Library name Flow.js
**Git repository url: https://github.com/flowjs/flow.js
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by Piicksarn**
close #5911. cc @AidasK

@maruilian11, would you mind to have a look at the pr?
Thank you!

The information of the pr:
The git repo : https://github.com/flowjs/flow.js/tree/v2.9.0

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `52`, Star `1749`, Fork `185`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by maruilian11** [comment]
i think you can add `homepage` for it~
btw, could check PR for me :joy:

**Comment by maruilian11** [comment]
oh i forgot~ peterdavehello said we should use short commit message instead, and you shoud cc the auther in the commits~

**Comment by PeterDaveHello** [comment]
I didn't said that, what's wrong with you @maruilian11 ?

**Comment by maruilian11** [comment]
oh sorry just short title not short commit message :sweat_smile:

**Comment by Piicksarn** [comment]
@maruilian11, I have it corrected!
would you mind to take a look at the pr again?
Thank you!

**Comment by maruilian11** [comment]
@Piicksarn next time you can cc @auther in commit message ~
@PeterDaveHello i think this PR is ok.

**Pull request merged**
