### PR TITLE
Add rythm.js@1.2.4 w/ npm auto-update

### PR DESCRIPTION
**Pull request by hare1039**
Pull request for issue: #10652
Related issue(s): # #

@cdnjs/intern3 Please help me on this PR. Thanks.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/Okazari/Rythm.js
 * Official website (optional, not the repository): https://okazari.github.io/Rythm.js/
 * NPM package url (optional): https://www.npmjs.com/package/rythm.js
 * License and its reference: GPL-3.0, https://github.com/cdnjs/cdnjs/issues/10652

 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 8
   - Count of stars: 307
   - Count of forks: 17
 * NPM download stats (optional):
   - Downloads in the last day: 47
   - Downloads in the last week: 229
   - Downloads in the last month: 248

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by hare1039** [comment]
@pvnr0082t Please help me review on this PR. Thanks.

**Comment by hare1039** [comment]
@pvnr0082t The author said the license is GPL-3.0

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@hare1039 the license reference should link to the certain comment in the issue, not just issue number.

**Pull request merged**
