### PR TITLE
add gumshoe v3.0.2 with autoupdate config

### LINKED ISSUE #7110: [Request] Add  gumshoe
**Library name: gumshoe 
**Git repository url: https://github.com/cferdinandi/gumshoe
**npm package url(optional):** 
**License(s): MIT License
**Official homepage: http://cferdinandi.github.io/gumshoe/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by dannyxx001**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/cferdinandi/gumshoe
 * Official website (optional, not the repository): http://cferdinandi.github.io/gumshoe/ 
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 129
   - Count of watchers: 4
   - Count of forks: 9
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7110, cc @cferdinandi

### CODE REVIEW

**Comment by dannyxx001** [comment]
@PeterDaveHello please help me review this pull request, thank you.

**Comment by PeterDaveHello** [comment]
Please also try to add some keywords in `package.json` next time.

**Comment by cferdinandi** [comment]
Please note: I'm the owner of this script and do not support this move. It's MIT licensed, so you're free to fork and do this, but running from a CDN is not part of my vision for the script.

**Comment by PeterDaveHello** [comment]
@cferdinandi since we are not going to modify any code or other content in your project, so we may not create a new fork for it, BTW, you are doing great works in your libraries, awesome :smile:

**Pull request merged**
