### PR TITLE
Add select2 v3.5.4

### PR DESCRIPTION
**Pull request by jgeurts**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/select2/select2
 * Official website (optional, not the repository): https://select2.github.io/
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 16502
   - Count of watchers: 703
   - Count of forks: 3423
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
We don't need `ajax/libs/select2/3.5.4/select2_locale_en.js.template`.

**Comment by PeterDaveHello** [comment]
@jgeurts hope you don't mind that I just add it.

**Comment by jgeurts** [comment]
Thanks!

**Comment by PeterDaveHello** [comment]
@jgeurts No probs

**Comment by jgeurts** [comment]
I see that the files are on cdnjs.com, but I get a 404 when accessing - does it take a while to propagate? 

https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.4/select2.min.js

**Comment by PeterDaveHello** [comment]
@jgeurts Seems there is problem on cloudflare's server, ping @terinjokes

**Comment by terinjokes** [comment]
I was pinged a little bit ago by Ryan, we're looking at it.

**Comment by terinjokes** [comment]
This has been resolved.

**Pull request closed without merging**
