### PR TITLE
Add license info of vertx, cc #5500

### PR DESCRIPTION
**Pull request by ChiWeiHsiao**
References at line 5:
https://github.com/eclipse/vert.x/blob/master/LICENSE-eplv10-aslv20.html

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@ChiWeiHsiao You should tag your mentor in comment.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
@pvnr0082t I think she was waiting for the CI pass.

**Comment by PeterDaveHello** [comment]
@ChiWeiHsiao well done!

**Comment by ChiWeiHsiao** [comment]
Thanks!

**Pull request merged**
