### PR TITLE
add  trumbowyg v1.1.7 with git autoupdate, close #5058.

### LINKED ISSUE #5058: [Request] Add Trumbowyg
Project GitHub:
https://github.com/Alex-D/Trumbowyg

### PR DESCRIPTION
**Pull request by Piicksarn**

### CODE REVIEW

**Comment by Piicksarn** [comment]
@Amomo @LeaYeh @maruilian11

**Comment by maruilian11** [comment]
I think we need all files under dist, not just min.js and .js

**Comment by Piicksarn** [comment]
@maruilian11 ~i have it corrected!

**Comment by maruilian11** [comment]
but you seem not upload them?!
u  just upload min.js, .js and package.json, right?

**Comment by Piicksarn** [comment]
@maruilian11 how do you think about these corrections :))

**Comment by maruilian11** [comment]
i think we can't use **/* in this case.

**Comment by Piicksarn** [comment]
mm....I am confused...
How do we discuss the situation, which one should use* * / *, and which one is not , when base path is dist

**Comment by maruilian11** [comment]
<code>**/*</code> means all files, but in this case we don't need "every" file under dist.

**Comment by Piicksarn** [comment]
@maruilian11 , I tried to reduse the files which i added before.
I found that the ui folder is duplicate to the ui folder in plugins/colors folder.
for the reason, i retain the plugins file.

**Comment by Piicksarn** [comment]
@maruilian11 I have it corrected.
In this correction, I add all the files in the dist. Would you please checking this PR for me?
Thank you!

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Comment by Piicksarn** [comment]
@maruilian11,I have it rebased to master, and thack you for checking again:)

**Comment by Piicksarn** [comment]
@maruilian11, I have it rebased to master, would you please checkout the pr?
Thank you :^)

**Comment by Piicksarn** [comment]
@maruilian11 would you mind to check it again?
I have this PR rebased to master!
Thank you :^)

**Comment by maruilian11** [comment]
sorry, i didn't notice it before.
@PeterDaveHello  i think it's ok.

**Comment by PeterDaveHello** [comment]
You should not use `**/*` which will grab [ui/sass](https://github.com/Alex-D/Trumbowyg/tree/2.0.0-beta.5/dist/ui/sass)

**Comment by maruilian11** [comment]
oh that's why i said should not use <code>***/**</code> first time....
i didn't see it later and i totally forgot...
@Piicksarn i'm sorry...

**Comment by Piicksarn** [comment]
:^) it's fine @maruilian11~~
We could learn from the PR and bear in mind:^D

**Pull request closed without merging**
