### PR TITLE
rasterizeHTML.allinone.js

### PR DESCRIPTION
**Pull request by lethepeaceful**

### CODE REVIEW

**Comment by IonicaBizau** [comment]
Check the docs how to add a new library: https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library

You have to create a new directory and include the `package.json` as well.

**Comment by Piicksarn** [comment]
ping @cdnjs/intern @cdnjs/intern2

**Comment by maruilian11** [comment]
@lethepeaceful any update? we'll close this PR if there is no response in next 7 days.

**Comment by PeterDaveHello** [comment]
Close due to no response for a long time and it's also invalid.

**Pull request closed without merging**
