### PR TITLE
[new][author] BitsyCode

### PR DESCRIPTION
**Pull request by BitsyCode**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required):
- Official website (optional, not the repository):
- NPM package url (optional):
- GitHub / Bitbucket popularity (required):
  - Count of stars:
  - Count of watchers:
  - Count of forks:
- NPM download stats (optional):
  - Downloads in the last day:
  - Downloads in the last week:
  - Downloads in the last month:
# Essential checklist
- [x] I'm the author of this library
  - [x] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update)
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please read our document first, we need to know its popularity and license, and you should fixup the commits into only one commit, thanks.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by BitsyCode** [comment]
There hasn't been any updates, we are busy with adding more methods.


Thanks


________________________________

**Comment by PeterDaveHello** [comment]
Close due to no response.

**Pull request closed without merging**
