### PR TITLE
Updated bootstrap-social to 4.3.3

### PR DESCRIPTION
**Pull request by dalanzg**
I have updated bootstrap-social to 4.3.3 again. The files were copied from the original repository: https://github.com/lipis/bootstrap-social

This time I used Terminal commands and managed to perform it with only one commit.

Regards,

Dalanzg

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Wrong syntax.

**Comment by dalanzg** [comment]
Why is package.json wrong? I only changed the version number and maintained the css name.

**Comment by PeterDaveHello** [comment]
No, you changed the quotes ...

**Comment by dalanzg** [comment]
Yes, it was because of my editor.

I will submit again.

Apologize for that mistake

**Pull request closed without merging**
