### PR TITLE
Add svgeezy@1.0.0 w/ git auto-update config

### LINKED ISSUE #8950: [Request] Add svgeezy
**Library name:** svgeezy
**Git repository url:** https://github.com/benhowdle89/svgeezy

### PR DESCRIPTION
**Pull request by x09326**
PR for #8950 
@kennynaoh please help me review it, thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/benhowdle89/svgeezy
 * Official website (optional, not the repository):http://benhowdle.im/svgeezy/
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars:862
   - Count of watchers:53
   - Count of forks:91
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8950, cc @benhowdle89

### CODE REVIEW

**Comment by kennynaoh** [comment]
@x09326 
It shows the released under `WTFPL` license [here](https://github.com/benhowdle89/svgeezy/blob/master/svgeezy.js#L5).
Could you confirm with author to make sure which license should use?
Thanks!

**Comment by x09326** [comment]
https://github.com/benhowdle89/svgeezy/issues/20

Someone has asked that, but the author haven't reply yet.

**Comment by PeterDaveHello** [comment]
Seems removed. @kennynaoh please don't mention a line or section of code on a certain branch, you should use a certain "commit", as you can see now what you've mentioned didn't exist anymore, that's the reason.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
Ok, I will use a certain commit next time.
Thanks!

**Comment by x09326** [comment]
@kennynaoh 
The author said they use MIT license.
And I have rebased it.
Please help me review it, thanks.

**Comment by kennynaoh** [comment]
LGTM

**Pull request merged**
