### PR TITLE
[new] add videomail-client@1.3.19 with git auto-update, close #4929

### LINKED ISSUE #4929: [New] Add videomail-client
From https://www.npmjs.com/package/videomail-client

With the versions as tags if possible? Many thanks!

### PR DESCRIPTION
**Pull request by Amomo**
@LeaYeh , I add a new lib with git auto-update from the request #4929
Would you mind checking this PR for me?
Thank you~ :-)

### CODE REVIEW

**Comment by LeaYeh** [comment]
i think "**/*" is better

**Comment by Amomo** [comment]
@LeaYeh you're right! I have corrected it now.
Could you take a look? Thank you! :-D

**Comment by LeaYeh** [comment]
it's okay now :) @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Seems both of you didn't check its popularity.

**Comment by Amomo** [comment]
Sorry to hear that. :(
I have tried the demo on its homepage, and it looks cool~
I add it because it has 9,508 downloads in the last month from npm.
And it just move to github about a month. Seems it isn't enough.
I will keep this PR here, and wait the lib getting more popular someday.

**Pull request merged**
