### PR TITLE
[new] add placeholder.js @v2.0.0

### PR DESCRIPTION
**Pull request by hustcc**
Hi @Piicksarn

repo url: [https://github.com/hustcc/placeholder.js](https://github.com/hustcc/placeholder.js)
npm package url: [https://www.npmjs.com/package/placeholder.js](https://www.npmjs.com/package/placeholder.js)

the proeject has been recommend by toutiao.io, v2ex.com and segmentfault.com, I need cdn service, many thanks.

` Watch 2 ` ` Star 78 ` ` Fork 10 `

Would you mind checking this PR for me? Thank you~ :-D

 - [x] Not found on cdnjs repo
 - [x] No already exist issue and PR
 - [x] Notable popularity : Watch 2, Star 78, Fork 10
 - [x] Project has public repository on famous online hosting platform (or been hosted on npm)
 - [x] Has valid tags for each versions (for git auto-update)
 - [x] Auto-update setup
 - [x] Auto-update target/source is valid.
 - [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by hustcc** [comment]
Hello, very sorry to trouble you.

placeholder.js change the lib path since v3.1.0. below:

```
"npmFileMap": [{
    "basePath": "dist",
    "files": [
        "placeholder*.js"
    ]
} ],
```

change the `placeholder*.js` to dist dir.

**Comment by PeterDaveHello** [comment]
@hustcc would you like to send a PR to update that? Or you want me to do that for you?

**Comment by hustcc** [comment]
Very thanks for you to help me update it. ^_^~

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs/commit/6897990132eece32cf057759f16c5e9167b39636
@hustcc please create a new issue next time, thanks.

**Comment by hustcc** [comment]
ok~ very thanks~

**Pull request merged**
