### PR TITLE
Add license of reactive-coffee, cc #5500

### PR DESCRIPTION
**Pull request by honestree**
Reference: https://github.com/yang/reactive-coffee/blob/master/LICENSE

### CODE REVIEW

**Comment by honestree** [comment]
@x09326 Please help me review this PR, thanks!

**Comment by PeterDaveHello** [comment]
@honestree You should wait until the CI test finished.

**Comment by PeterDaveHello** [comment]
@honestree Looks like you didn't confirgure the user info correctly. Call your mentor for help please.

**Comment by x09326** [comment]
@honestree 
Can you send the result of $ git config -l to me?

**Comment by honestree** [comment]
@x09326 
I have done every thing mentioned in "https://github.com/cdnjs/cdnjs/pull/9904" 
Please help me review this PR, thanks!

**Comment by x09326** [comment]
LGTM
@cdnjs/intern2 please help me review it, thanks.

**Comment by x09326** [comment]
Okay
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
oops ... #9692 is earlier guys ...

**Pull request merged**
