### PR TITLE
Update pusher.js to version 2.2.3

### PR DESCRIPTION
**Pull request by swbullis**
url: https://raw.githubusercontent.com/pusher/pusher-js/master/dist/pusher.min.js

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please squash these two commits into only one commit as document said, and according to #3638, please also add auto-update config for it, thanks.

**Comment by swbullis** [comment]
Thanks.  This being my first time using pull requests, Ill leave this for
someone who knows what there doing, as I am not sure what your asking me to
do?

But I do love the idea behind cdnjs project and hope someone else can.

**Comment by PeterDaveHello** [comment]
I mean use `git rebase` to merge them into only one commit and let it use auto-update mechanism, if you don't mind, I can take this.

**Comment by PeterDaveHello** [comment]
no response?

**Comment by swbullis** [comment]
Sorry Peter, Yes please take it I have no idea what am being asked to do.

**Comment by PeterDaveHello** [comment]
okay

**Comment by PeterDaveHello** [comment]
Done in 25e5505

**Pull request closed without merging**
