### PR TITLE
auto-update config on jquery.nicescroll, close #6062

### LINKED ISSUE #6062: auto-update config on jquery.nicescroll
https://github.com/inuyaksa/jquery.nicescroll
https://cdnjs.com/libraries/jquery.nicescroll

### PR DESCRIPTION
**Pull request by LeaYeh**
Hi @maruilian11 

For #6062 , I add git auto-update config on jquery.nicescroll in its package.json.
repo: https://github.com/inuyaksa/jquery.nicescroll/tree/3.6.0
Would you mind checking this PR for me? Thank you~ :-D

- [ ] Not found on cdnjs repo
- [ ] No already exist issue and PR
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by maruilian11** [comment]
@LeaYeh i think the PR is ok, could you rebase it?
btw, next time you can show the repo's watch,star and fork

**Comment by LeaYeh** [comment]
@maruilian11  ok i rebased it

**Comment by LeaYeh** [comment]
@maruilian11 hello~

**Comment by maruilian11** [comment]
@LeaYeh sorry for late, can you rebase it again?

**Comment by LeaYeh** [comment]
@maruilian11 got that!

**Pull request merged**
