### PR TITLE
add foonav@0.0.6 w/ git auto-update

### LINKED ISSUE #7006: [Request] Add foonav
**Library name:** foonav
**Git repository url:** https://github.com/fooplugins/foonav

### PR DESCRIPTION
**Pull request by kennynaoh**
@PeterDaveHello please help me check my PR for #7006 , thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/fooplugins/foonav
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 32
   - Count of watchers: 5
   - Count of forks: 12
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

autoupdate config added, close #7006, cc @steveush

### CODE REVIEW

**Comment by kennynaoh** [comment]
@PeterDaveHello 
there is no licence in repository or in package.json
please help me check the licence
thanks

**Comment by PeterDaveHello** [comment]
https://github.com/fooplugins/foonav/blob/master/dist/foonav.min.js#L6
```js
/**!
 * FooNav - A jQuery navigation menu.
 * @version 0.0.6
 * @link http://fooplugins.github.io/foonav/
 * @copyright Steven Usher & Brad Vincent 2014
 * @license Released under the MIT license.
 */
```

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I re-push again.
Please help check this PR again
thanks

**Comment by PeterDaveHello** [comment]
Please fixup these commits into only one commit.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I have rebased already.
Please help me check again
Thanks

**Comment by PeterDaveHello** [comment]
@kennynaoh you should say what kind of auto-update config you added next time.

**Comment by PeterDaveHello** [comment]
Please open an issue to upstream to report about the version inconsistent problem first.

**Comment by kennynaoh** [comment]
OK
I have created issue already.
Thanks.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
Because the issue still has no response.
And I add the version 0.0.1 first.
I have rebased to the latest master branch.
Please help me review it again.
Thanks!

**Comment by PeterDaveHello** [comment]
I replied on the issue, you could also try to add v0.0.3 or even v0.0.2 manually.

**Comment by steveush** [comment]
Hi @kennynaoh ,

Apologies I missed the first notification of that issue and saw @PeterDaveHello reply today. I've fixed the versioning issue on the repo and it should now reflect as the correct version of 0.0.6.

Thanks

**Comment by PeterDaveHello** [comment]
@steveush Thanks.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I have updated the version to 0.0.6.
Please help me review it again.
Thanks!

**Comment by PeterDaveHello** [comment]
@pvnr0082t please help review this PR, thanks.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Pull request merged**
