### PR TITLE
microsoft-signalr

### PR DESCRIPTION
**Pull request by bradygaster**
# Newly-located, yet already-on-CDNJS library, Microsoft ASP.NET Core SignalR. 

Pull request for issue: #
Related issue(s): #13198 #13319 #13438 #13499

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

## Profile of the lib

* Git repository (required):https://github.com/aspnet/AspNetCore/
* Official website (optional, not the repository):http://dot.net
* NPM package url (optional):https://npmjs.com/package/@microsoft/signalr
* License and its reference:Apache-2
* GitHub / Bitbucket popularity (required):
  * Count of watchers:1,278
  * Count of stars:10,744
  * Count of forks:2,569
* NPM download stats (optional):
  * Downloads in the last day: 10,000 (est as npm provides weekly only)
  * Downloads in the last week: 113,000
  * Downloads in the last month: 400,000 (est as npm provides weekly only)

## Essential checklist

* [x] I'm the author of this library
  * [x (if allowed)] I would like to add link to the page of this library on CDNJS on website / readme
* [] This lib was not found on cdnjs repo
* [] Doesn't already exist / has duplicate issue and PR
* [x] The lib has notable popularity
  * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [x] More than 800 downloads stats per month on npm registry
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [ ] Has valid tags for each versions (for git auto-update)
* [ ] Auto-update setup
* [ ] Auto-update target/source is valid.
* [ ] Auto-update filemap is correct.

## Git commit checklist

* [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [x] The parent of the commit(s) in the PR is not older than 3 days.
* [x] Pull request is sent from a non-master branch with a meaningful name.
* [x] Separate unrelated changes into different commits.
* [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [x] Close corresponding issue in commit message
* [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by bradygaster** [comment]
pinging on this to see when to expect it to be accepted and published. cc @davidfowl @anurse

**Comment by drewfreyling** [comment]
@ryankirkman @MattIPv4 @PeterDaveHello I don't have perms to merge this but it looks ok to me.

**Comment by MattIPv4** [comment]
I don't have permission either.

**Comment by MattIPv4** [comment]
@ryankirkman should be able to.

**Comment by bradygaster** [comment]
@MattIPv4 - can we get an ETA on when this will be merged and go live? We're near the end of a month-after-GA of the new libraries. This should be easier.

**Comment by drewfreyling** [comment]
@ryankirkman @PeterDaveHello are we able to get this sorted please? It would also help if @MattIPv4  and myself had permissions to do this as we would have had it done weeks ago.

**Comment by drewfreyling** [comment]
#13524 contains some info about the current situation.

**Comment by MattIPv4** [comment]
We now have merge access to this, but the auto-update bot is currently not running (see above issue), so merging this currently won't do anything.

Unless anyone disagrees, I'm going to hold off on merging this until we have a solution for the auto-update bot, so that this config file and all the others will trigger assets to be pulled in.

**Comment by bradygaster** [comment]
@MattIPv4 - could we get an update here? We've not heard back on this PR, or when the SignalR JS files will be updated on CDNJS. We're **months** past the release with no feedback or guidance from CDNJS on how to get our content published. Please advise.

**Comment by MattIPv4** [comment]
Hey @xtuc - Any ideas why https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/microsoft-signalr/package.json isn't being picked up by the bot and adding versions (I would guess this affects all libs added via a single package.json, we've seen others with this same issue)? Do we want to manually seed it with an initial version to see it that kicks it into life?

**Comment by bradygaster** [comment]
Any news here? We're still waiting...

**Comment by MattIPv4** [comment]
@xtuc can we look at moving this package to the new bot/repo if that’s operable?

**Comment by xtuc** [comment]
I moved the package to the new autoupdater, some new versions were pushed.

**Pull request merged**
