### PR TITLE
Added angular-leaflet-directive and raven-js

### PR DESCRIPTION
**Pull request by eseceve**
Added angular-leaflet-directive@0.7.15
Updated raven-js@1.1.18

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
package.json missing

**Comment by eseceve** [comment]
What package.json?

**Comment by PeterDaveHello** [comment]
You should read the document first @eseceve .

**Comment by eseceve** [comment]
My fault. I used cdnjs-importer and I thought was ready for PR.

**Comment by PeterDaveHello** [comment]
cc @IonicaBizau

**Comment by IonicaBizau** [comment]
@eseceve Where can I see the git repo?

**Comment by eseceve** [comment]
@IonicaBizau my fork? https://github.com/eseceve/cdnjs

**Comment by IonicaBizau** [comment]
@eseceve No, I mean the project repositories. Can you show what are the commands you ran? The cdnjs-importer should add the package.json files as well.

**Comment by eseceve** [comment]
I try to update Raven.js with this command 
```bash
cdnjs-importer -c ./cdnjs git@github.com:getsentry/raven-js.git
```
https://github.com/getsentry/raven-js

**Comment by IonicaBizau** [comment]
OK! I will try it out and see what's going on.

**Comment by IonicaBizau** [comment]
@eseceve The import was fine:

```sh
$ cdnjs-importer -c ./cdnjs git@github.com:getsentry/raven-js.git
info  [14:45.02 - 08.05.2015] Clonning git@github.com:getsentry/raven-js.git into /tmp/tmp-27132TDvAqHz0qcOh
info  [14:45.13 - 08.05.2015] Set the source path: /dist
info  [14:45.13 - 08.05.2015] Creating the version directory: cdnjs/ajax/libs/raven-js/1.1.18
info  [14:45.13 - 08.05.2015] Getting the library files.
info  [14:45.13 - 08.05.2015] Writing the package.json file in cdnjs/ajax/libs/raven-js
info  [14:45.13 - 08.05.2015] Copying the library files
info  [14:45.13 - 08.05.2015] Adding the new library files in the git repository.
info  [14:45.15 - 08.05.2015] Committing the changes
info  [14:45.17 - 08.05.2015] Added raven-js@1.1.18
info  [14:45.17 - 08.05.2015] Done.
```

Also, the tests are passing:

```sh
  ✓ OK » 6049 honored (1.385s) 
```

The issue I see is that there is another library called `raven.js` (with `.` instead of `-`). Maybe that's the problem?

**Comment by eseceve** [comment]
@IonicaBizau I do not know what is the problem but I will revert my commits and I will try again with a PR for each library.

**Comment by IonicaBizau** [comment]
Since both `raven-js` and `raven.js` point to the same repository, I recommend running the following:

```sh
cd cdnjs
git checkout -b raven
cd ..
cdnjs-importer -c ./cdnjs git@github.com:getsentry/raven-js.git
cd cdnjs/ajax/libs
rm -rf raven.js/
mv raven-js raven.js
git add . -A
git commit --amend -m 'Update raven.js'
git push --all
```

The make a new PR.

**Comment by eseceve** [comment]
Thank. I will do.

**Pull request closed without merging**
