### PR TITLE
Update package.json of angular-ui-router & add missing files

### LINKED ISSUE #11713: Update auto-update config, keywords & homepage info of angular-ui-router
npm package move to https://www.npmjs.com/package/@uirouter/angularjs
cc #10264

### PR DESCRIPTION
**Pull request by sufuf3**
close #11713

Pull request for issue: #11713
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/angular-ui/ui-router
 * Official website (optional, not the repository): https://ui-router.github.io/
 * NPM package url (optional): old: https://www.npmjs.com/package/angular-ui-router
new: https://www.npmjs.com/package/@uirouter/angularjs
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 620
   - Count of stars: 13469
   - Count of forks: 3277
 * NPM download stats (optional):
   - Downloads in the last day: 2610
   - Downloads in the last week: 12929
   - Downloads in the last month: 49,796

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
Memo: 
I think we can add `stateEvents.*` because of https://ui-router.github.io/ng1/docs/latest/modules/ng1_state_events.html and `resolveService.*` because of https://ui-router.github.io/ng1/docs/1.0.0-rc.1/modules/ng1.html.
`ui-router-angularjs.*` show here https://gemnasium.com/bower/angular-ui-router/versions/1.0.3

**Comment by sufuf3** [comment]
@cdnjs/active-contributor @cdnjs/intern3 please help me review this PR, thank you.

**Comment by sufuf3** [comment]
@ncoden Should we exclude the versions involving "SNAPSHOT"?
Thank you.

**Comment by ncoden** [comment]
@sufuf3 They are not Semver versions. I would not recommand any developer to rely on them since there is no way to know the level of breaking changes we can expect in it.

**Comment by PeterDaveHello** [comment]
@ncoden fare enough 👍

**Comment by sufuf3** [comment]
@cdnjs/library-reviewer please help me review this PR, thanks.
I added missing files and ignore the SNAPSHOT versions.

**Comment by sufuf3** [comment]
@maruilian11 @extend1994 Please help me review this PR, thank you.

**Comment by sufuf3** [comment]
ping @maruilian11 @extend1994

**Comment by sufuf3** [comment]
ping @maruilian11 @extend1994

**Comment by sufuf3** [comment]
@PeterDaveHello sorry that this PR waiting for reviewer's review for a while, almost a month.
But this is a high priority PR.
So I request you to help review this PR.

Please help me review this PR, thanks.

**Comment by sufuf3** [comment]
ping @maruilian11 @extend1994

**Comment by ncoden** [comment]
:'(

**Comment by sufuf3** [comment]
@extend1994 but the commit did the `update auto-update`,  didn't it?
Actually, I think we don't have to create another issue, just send a commit, and mention detail in commit message, like we don't have to create adding badge issue to other repo, just send the PR.
What do you think?

**Comment by sufuf3** [comment]
Also, these are some commit like this
https://github.com/cdnjs/cdnjs/commit/33a1e1c4505ce115a35f6b7b12ecdefc38ffa5fc
https://github.com/cdnjs/cdnjs/commit/15bf124162681c15ba2ecd0193a93f0ef2cf8d39
https://github.com/cdnjs/cdnjs/commit/40d24691eb83000c3581cf184f24971d2cff599d

**Comment by extend1994** [comment]
I meant you can use another "commit" to update metadata and cc the original issue. Not asking you to open a new issue. Just my personal opinion.

**Comment by sufuf3** [comment]
@extend1994 I updated #11713, is it good enough?
Thank you

**Comment by sufuf3** [comment]
Just rebased with the latest master.

**Comment by sufuf3** [comment]
I would close this PR.
Because I found this lib update to v1.0.15, but this PR is waiting for review for a while.
I don't know that is there any different from v1.0.15 with this PR, I need to check the lib in my free time.
However, I am busy these days.
After I check between the lib's version and this PR, I would reopen this PR again.
Also if there is any change that I need to update, I would do that.

Anyway, if someone want to help improve this lib, please feel free to take this.

Many thanks.

**Comment by sufuf3** [comment]
Just rebased with the latest master.

This PR is fine for the latest version v1.0.15.
Thanks

**Comment by sufuf3** [comment]
@PeterDaveHello Would you please help me review this PR?
Thanks for your help.

**Comment by sufuf3** [comment]
@PeterDaveHello Would you please help me review this PR?
This is a high priority PR.
Thank you.

**Pull request merged**
