### PR TITLE
remove the empty dependencies field

### PR DESCRIPTION
**Pull request by x09326**
PR for #8073 
@kennynaoh please help me review it, thanks.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@x09326 please review the PR(s) waiting for you like #8142 before sending new ones, so that we won't have so many branches need to be rebased with the latest master branch, and also make the waiting queue not so long.

**Comment by x09326** [comment]
ping @kennynaoh

**Comment by kennynaoh** [comment]
@x09326 
Sorry for late review.
Please rebase to the latest master branch.
Thanks!

**Comment by x09326** [comment]
@kennynaoh 
I have rebased it.
Please help me review it again, thanks.

**Comment by PeterDaveHello** [comment]
@x09326 please explain the reason of choosing these keywords, thanks.

**Comment by PeterDaveHello** [comment]
You didn't add keywords, check the diff.

**Comment by x09326** [comment]
Um....I don't know what happened here.
When I sent this commit, it didn't have ```keywords``` field.
What is my next step?

**Comment by PeterDaveHello** [comment]
@x09326 You can just remove the commit about the keywords.

**Comment by x09326** [comment]
@kennynaoh 
I have modified the commit.
Please help me review it.

**Comment by kennynaoh** [comment]
@x09326 
Maybe you could talk about what library of the empty dependency you removed in commit message.
Thanks!

**Comment by PeterDaveHello** [comment]
@x09326 take a look at commit: https://github.com/x09326/cdnjs/commit/300fc2e14c0dfd2205da1a40cca43d4d225a1228#diff-f3b9ff9a5ae51e96976193d4996c3203, for the empty field, you should consider to write a small app to scan all the package.jsons and remove the empty field, then add it in the test.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by PeterDaveHello** [comment]
As we deleted all the dependency section and added test already, close this one now.

**Pull request closed without merging**
