### PR TITLE
Add EaselJS missing versions

### PR DESCRIPTION
**Pull request by kirintwn**
**Library name:** EaselJS
**Git repository url:** https://github.com/CreateJS/EaselJS

I have manually added missing versions `0.3.0 ~ v0.6.0` & `v0.8.1 ~ v1.0.0` from [github release page](https://github.com/CreateJS/EaselJS/releases).
Also added missing file `movieclip.min.js` on existed version `0.6.1`

Pull request for issue: #12231

### CODE REVIEW

**Comment by extend1994** [comment]
@cy91244 Please remember to fix this PR. Thanks.

**Comment by sashberd** [comment]
@sufuf3 I checkout this PR. Is your second comment relevant? Because I did not see any files you talked about.

**Comment by sashberd** [comment]
@sufuf3 ping

**Comment by xtuc** [comment]
Closing for lack of activity

**Pull request closed without merging**
