### PR TITLE
add nviewjs v1.0.3 with npm auto-update config

### LINKED ISSUE #6869: [Request] Add nviewjs
Library name: nviewjs
Git repository url: https://github.com/any-js/nviewjs
npm package url(optional): https://www.npmjs.com/package/nviewjs
License(s): MIT
Official homepage: http://any-js.github.io/

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #6869 
@dannyxx001 please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/any-js/nviewjs
 * Official website (optional, not the repository): http://any-js.github.io/
 * NPM package url (optional): https://www.npmjs.com/package/nviewjs
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 1
   - Count of watchers: 1
   - Count of forks: 0
 * NPM download stats (optional):
   - Downloads in the last day: 59
   - Downloads in the last week: 76
   - Downloads in the last month: 101

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #6869, cc @anyjser

### CODE REVIEW

**Comment by dannyxx001** [comment]
Can you ask author why he separate files into two directory rather than group as dist just like his git repository?

**Comment by kennynaoh** [comment]
@dannyxx001 
I think that's ok.
Maybe you cloud take a look at [this](https://github.com/cdnjs/cdnjs/pull/7890/files#diff-86b569480fd7244020fd411652abff4cR25).
Thanks!

**Comment by dannyxx001** [comment]
OK, if that's OK, then I think this PR is OK. @PeterDaveHello please help us review again, thanks.

**Comment by PeterDaveHello** [comment]
Doesn't this branch need to reabse with the latest master branch first?

**Comment by kennynaoh** [comment]
@dannyxx001 
I have rebased to the latest master branch.
Please help me review it again.
Thanks!

**Pull request merged**
