### PR TITLE
add lazyyt v1.0.1 

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/tylerpearson/lazyYT
**Watch 15
  Star 141
 Fork 57**
@Piicksarn could u help me check this PR for #6609 ? thank you!
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [ ] Has valid tags for each versions (for git auto-update) cc https://github.com/tylerpearson/lazyYT/issues/50
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
If there is no tag for v1.0.1, how can you say that you committed v1.0.1? There are not only one revision contain v1.0.1 in the code, should be confirmed.

**Comment by maruilian11** [comment]
> There are not only one revision contain v1.0.1 in the code
@PeterDaveHello not really understand this one.

**Comment by PeterDaveHello** [comment]
@maruilian11 Tell me how can you say that is v1.0.1

**Comment by maruilian11** [comment]
@PeterDaveHello here
https://github.com/maruilian11/cdnjs/blob/f387ff469d593815c65432fcd2db9f2d44719c11/ajax/libs/lazyyt/1.0.1/lazyYT.css#L3

**Comment by PeterDaveHello** [comment]
That's funny, how can you say your file is correct? That's obviously an invalid reference.

**Comment by maruilian11** [comment]
@PeterDaveHello how about this
https://github.com/tylerpearson/lazyYT/blob/master/lazyYT.js#L3

**Comment by PeterDaveHello** [comment]
@maruilian11 This is on master branch, there are many v1.0.1 in master branch revision, how can you say that the one you added is v1.0.1, what about the older one?

**Comment by maruilian11** [comment]
@PeterDaveHello change to v0.3.4

**Pull request merged**
