### PR TITLE
[author] update to bignumber.js

### PR DESCRIPTION
**Pull request by MikeMcl**
Added DEPRECATED warning to v2.x.x releases containing critical bug.
Added v2.0.6.
Added source map and unminified version subsequent to user request.
Updated package.json version number and npm auto-update config.

Unable to squash commits as using web interface.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Would you please squash them into only one commit as our document said? thanks.

**Comment by MikeMcl** [comment]
As I stated above,  I'm unable to squash the commits as I am using the web interface. I am unable to download the whole project locally.

**Comment by PeterDaveHello** [comment]
If you don't mind, I can take it.

**Comment by MikeMcl** [comment]
I am not sure what you mean, but I assume it is that you do not want to accept the pull request unless the commits are squashed.
Okay, I accept that. It is a shame I cannot do that with the Github interface.

**Comment by PeterDaveHello** [comment]
I meant that I can do the things you want in this PR if you don't mind, do you？

**Comment by MikeMcl** [comment]
No, I don't mind. That would be great.

**Comment by PeterDaveHello** [comment]
Hmmmm ... I found that we already setup auto-update config for this lib, and its already v2.0.6, but I did't see the map file in the repo ro npm package, where should I get it?

**Comment by MikeMcl** [comment]
https://github.com/MikeMcl/bignumber.js/blob/master/doc/bignumber.js.map

**Comment by PeterDaveHello** [comment]
Is it possible to put them in the same folder? Or the structure in cdnjs should also be `doc/bignumber.js.map`, not a good idea.

**Comment by MikeMcl** [comment]
Okay, I've moved the source map to the root directory.

**Comment by PeterDaveHello** [comment]
Thanks.

**Comment by PeterDaveHello** [comment]
Seems you didn't add `/* DEPRECATED. Critical bug found in division operation. Fixed in v2.0.5+. */` to v2.0.4, should I?

**Comment by MikeMcl** [comment]
v2.0.4 is actually the first fixed version, so that isn't necessary.

**Pull request closed without merging**
