### PR TITLE
Update d3 auto-update config w/ v5.5.0

### LINKED ISSUE #12845: Update d3 for versions 5.x
The latest version available for d3 on cdnjs is 4.9.  Version 5.x has been out for several months now.  It would be useful to have these available as well.

### PR DESCRIPTION
**Pull request by sashberd**
close #12845 

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
 * [x] The parent of the commit(s) in the PR is not older than 3 days.
 * [x] Pull request is sent from a non-master branch with a meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sashberd** [comment]
@extend1994 Done

**Comment by extend1994** [comment]
@sashberd 
```
The update was done due to build folder name
was changed to dist name
```
can be in same line, the limit is 72 chars.

**Comment by sashberd** [comment]
@extend1994 Done

**Comment by extend1994** [comment]
@sashberd I updated 
```
Update d3 npm auto update config
The update was done due to build folder name was changed to dist name
```

to

```
Update d3 basePath to dist for new built files
```

which is much shorter and express the same thing.
Maybe it can be a reference for you.

**Pull request merged**
