### PR TITLE
Update jquery-easing

### PR DESCRIPTION
**Pull request by maruilian11**
Pull request for issue: #10006
Related PR: https://github.com/cdnjs/cdnjs/pull/130
@cdnjs/intern @cdnjs/intern2 Please help me review this PR, thanks!

1. because `jquery.easing.compatibility.js` is under MIT license, so I add MIT in license field.
https://github.com/gdsmith/jquery.easing/blob/master/jquery.easing.compatibility.js#L7

2. v1.1.1 ~ v1.2 if from https://github.com/gdsmith/jquery.easing/tree/1.3.0

3. v1.3 is from the git tag.

# Profile of the lib
 * Git repository (required): https://github.com/gdsmith/jquery.easing
 * Official website (optional, not the repository): http://gsgd.co.uk/sandbox/jquery/easing
 * NPM package url (optional): https://www.npmjs.com/package/jquery.easing
 * GitHub / Bitbucket popularity (required):
   Watch 30
   Star 619
   Fork 306
 * NPM download stats (optional):
  76 downloads in the last day
  4,374 downloads in the last week
  15,817 downloads in the last month

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
I think we could not do any changed to files that had already been hosted, right? @PeterDaveHello

**Comment by maruilian11** [comment]
@pvnr0082t How about we combine 89b5ee9bc3798ef399efab5c8a15faf2135f2cdd and d7549e571c1180ae1fc5a5e1954282f22b4be732 because I think they both are updates.

Yes, I noticed it will modify the hosting file, but 
1. it's not official, and there is an official one.
2. the official one shouldn't work worse. so I thought it won't destroy anything.
But it's all my viewpoint.

I will follow the manager's order.

**Comment by pvnr0082t** [comment]
> How about we combine 89b5ee9 and d7549e5 because I think they both are updates.

That would be fine.

I think modify the files that had been hosted will have some effect because cdnjs supports SRI feature.

**Comment by pvnr0082t** [comment]
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Please don't touch the hosted file.

**Comment by PeterDaveHello** [comment]
> Add jquery-easing v1.3 some files 

Is this English?

**Comment by maruilian11** [comment]
@cdnjs/intern @cdnjs/intern2 I remove the commit touching hosted file and update the commit msg of adding v1.3 files, and I also add a commit to ignore 1.3.0 and 1.3.1 which files are same with v1.3.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
@kennynaoh @x09326 please also involve in/review this PR, I think you can also learn something from it.

**Comment by maruilian11** [comment]
ping @x09326 @kennynaoh

**Comment by kennynaoh** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
> 4. jquery.easing.min.js hosted on cdnjs originally is not an official minified file, see #130.
So I change to use the official one.

Comment not updated?

Don't you need to mention the detail like file source and due license reason in the commit message?

**Comment by maruilian11** [comment]
1.1.1 is from https://github.com/gdsmith/jquery.easing/blob/1.3.0/jquery.easing.1.1.1.js
1.1.2 is from https://github.com/gdsmith/jquery.easing/blob/1.3.0/jquery.easing.1.1.2.js
1.2 is from https://github.com/gdsmith/jquery.easing/blob/1.3.0/jquery.easing.1.2.js
1.3 is from https://github.com/gdsmith/jquery.easing/blob/v1.3/jquery.easing.1.3.js

**Comment by maruilian11** [comment]
@PeterDaveHello I updated the comment, mentioned the file source, and updated the commit msg about due license.

**Pull request merged**
