### PR TITLE
Enrich webuploader's package.json(field:license)

### PR DESCRIPTION
**Pull request by iwdmb**
#5500
license link: https://github.com/fex-team/webuploader/blob/master/LICENSE

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
BSD is not clear at all, please refer to https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json

**Comment by iwdmb** [comment]
Please review it. thanks!

**Comment by PeterDaveHello** [comment]
This branch 19 commits behind cdnjs:master, please rebase your branch for this PR with the latest master branch.

**Comment by iwdmb** [comment]
finished!

**Comment by PeterDaveHello** [comment]
How do you say that is a BSD-3-Clause license? Any proof?

**Comment by iwdmb** [comment]
I compare
[https://github.com/fex-team/webuploader/blob/master/LICENSE]https://github.com/fex-team/webuploader/blob/master/LICENSE
with
[https://opensource.org/licenses/BSD-3-Clause](https://opensource.org/licenses/BSD-3-Clause)

**Comment by PeterDaveHello** [comment]
They don't look the same, you can take a look at some other libraries that using BSD-3-Clause like "D3", there are some differences.

**Comment by PeterDaveHello** [comment]
The LICENSE from upstream has a diff/additional of `of this software`, the other parts are same, maybe just accept this.

**Pull request merged**
