### PR TITLE
[New] Add jquery.tosrus@2.5.0 w/ git auto-update

### PR DESCRIPTION
**Pull request by dakshshah96**
Pull request for issue: #9730
Related issue(s): #11170, #9760

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/FrDH/jQuery.TosRUs
 * Official website (optional, not the repository): http://tosrus.frebsite.nl/
 * NPM package url (optional):
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 22
   - Count of stars: 127
   - Count of forks: 35
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@extend1994 how about manually adding v1.4.0 ~ v2.4.2 after this PR be merged?
Thank you.

**Comment by extend1994** [comment]
@sufuf3 I don't it need two PRs to add this library and it's not in hurry. Or @dakshshah96 do you mind we add old versions for you?

**Comment by sufuf3** [comment]
@dakshshah96 thanks for contribution.
Would you mind working on this and helping improve this PR in first commit?
If you have any question, please let us know.

Many thanks.

**Comment by sashberd** [comment]
@sufuf3 @extend1994 I helped with this one. FYR

**Comment by sashberd** [comment]
@extend1994 The PR was updated. FYR

Note: In v2.5.0 `dist` folder I did not find and `.scss` files, so I did not add to pattern this part from `src` - `jquery.tosrus!(*.scss)`

**Pull request closed without merging**
