### PR TITLE
Add sprint with old versions

### LINKED ISSUE #7776: [Request] Add Sprint.js
**Library name:** Sprint.js
**Git repository url:** https://github.com/bendc/sprint
**npm package url(optional):** N/A
**License(s):** MIT
**Official homepage:** https://github.com/bendc/sprint

### PR DESCRIPTION
**Pull request by pvnr0082t**
Pull request for issue: #7776
@kennynaoh @x09326 Please help me review this pull request, thank you.
- I didn't apply auto-update config due to there is no any git tag.
- Manually add old versions by tracing commit log.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/bendc/sprint
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 4380
   - Count of watchers: 143
   - Count of forks: 194
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7776, cc @bendc

### CODE REVIEW

**Comment by kennynaoh** [comment]
@pvnr0082t Sorry for late response. Please rebase to the latest master branch. Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh again, you should tell us the review result first, then ask to rebase.

**Comment by kennynaoh** [comment]
I think this PR is ok.

**Comment by kennynaoh** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Any reference of the tracing result?
Does @x09326 @kennynaoh manually trace them all again?

**Comment by kennynaoh** [comment]
I trace the commit here https://github.com/bendc/sprint/commits/master/sprint.js one by one.

**Comment by pvnr0082t** [comment]
Yes, I recorded my tracing result.
0.9.1 https://github.com/bendc/sprint/commit/416fc979ecb323b776ba1a5d2de6769acc082249
0.9.0 https://github.com/bendc/sprint/commit/b074a1a79ce83a8e83243e9338552046435a6565
0.8.1 https://github.com/bendc/sprint/commit/ae7be3fe5fc15dbf46d4f4619c57b74a5c4fe3e0
0.8.0 https://github.com/bendc/sprint/commit/1964bf666f65d72e5e734e924d04d8a5b73cc80c 
0.7.4 https://github.com/bendc/sprint/commit/806c5fc893bba1667a81c19e92b28127d678738a 
0.7.3 https://github.com/bendc/sprint/commit/99a26da26a6f73e71ce2bf91d8bd6c8f44e40cfb 
0.7.2 https://github.com/bendc/sprint/commit/12ab99bbad142fb896cec3a929124f0825f36370
0.7.1 https://github.com/bendc/sprint/commit/745e2d0836ceffa49da0a4594f6b5d673131712e
0.7.0 https://github.com/bendc/sprint/commit/9913a411dc52faad8ddb2bd8d849c535247c9d55
0.6.2 https://github.com/bendc/sprint/commit/cd615b58b1cac01d1aec2145d5ce5efc6cbf7a67
0.6.0 https://github.com/bendc/sprint/commit/2c786bd775c6360e71e2975b7cc6af3f34b65659 
0.5.7 https://github.com/bendc/sprint/commit/f3ae425491939c79c758879e3607df6b7d07a67b 
0.5.6 https://github.com/bendc/sprint/commit/1e58edb98ef692905e0af24ec4e9448eef77b1cc 
0.5.5 https://github.com/bendc/sprint/commit/0b4b944f0923420fbd6eb5dd241b236c1df2a193
0.5.4 https://github.com/bendc/sprint/commit/7ea3f812bfbe5d2720c00ed3abe448eed1cf7268 
0.5.3 https://github.com/bendc/sprint/commit/6ea8efd4a340f75165ef4da9251cf144b2d3e7a8 
0.5.2 https://github.com/bendc/sprint/commit/d471b995440bfdf94d540ddf9cccd8c40d49a9e2 
0.5.1 https://github.com/bendc/sprint/commit/dd471308ce9f3b8fe54131ce329a819406a6e363 
0.5.0 https://github.com/bendc/sprint/commit/53d62e647f34da574cb1240dfbf433dde4c7c85d  
0.0.0 https://github.com/bendc/sprint/commit/5ec370d34db7143af8bf27d857179d4319080d1d

**Pull request merged**
