### PR TITLE
Added SystemJS 0.19.9

### PR DESCRIPTION
**Pull request by KarlDirck**
From dist directory of https://github.com/systemjs/systemjs/releases/tag/0.19.9
The associated package.json has been updated with the source, version, dependencies, etc.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
What's its source? This PR didn't follow our conventions, please read our document first, thanks.

**Comment by maruilian11** [comment]
@KarlDirck sorry for not updating the version to 0.19.9, it's because there is a typo error in our auto-update config of this lib.
i will immediately send a PR to fix, please wait for few hours or few days, the new version will be uploaded to our website.

**Comment by KarlDirck** [comment]
@PeterDaveHello I have updated the comment of my PR.  I thought I followed your CONTRIBUTING.md (maybe the wrong one.)  I updated the existing SystemJS package, from the dist of the latest release, following the existing convention in the package. I am new to the process so please for give me if I missed something.

@maruilian11 It does appear configured to auto npm update, but hasn't. Thank you for your assistance.  Please let me know if there is more I can do to help.

**Comment by PeterDaveHello** [comment]
@KarlDirck you should squash/fixup those commits into only one commit.

**Comment by PeterDaveHello** [comment]
Hello, any updates here? Thanks.

**Comment by PeterDaveHello** [comment]
Hello, any updates here? Thanks.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by KarlDirck** [comment]
No update or further contributions from me here.  After experiencing an outage management decided to pay for a private CDN that has and SLA and escalation.

**Comment by PeterDaveHello** [comment]
@KarlDirck sorry for the late reply, I think we already updated it to the latest version automatically: https://cdnjs.com/libraries/systemjs/0.20.11, feel free to use it and please let me know that how can I help :) Thank you!

**Pull request closed without merging**
