### PR TITLE
[new] Add MaterialDesignIcons v1.2.65 with git autoupdate, close #4993

### LINKED ISSUE #4993: [Request] materialdesignicons
https://materialdesignicons.com/
https://github.com/templarian/MaterialDesign/

### PR DESCRIPTION
**Pull request by Piicksarn**

### CODE REVIEW

**Comment by Piicksarn** [comment]
@maruilian11 , would you mind to checkout the pr for me?
Thank you!

git repository url : https://github.com/Templarian/MaterialDesign-Webfont

 - [x] Not found on cdnjs repo
 - [x] No already exist issue and PR
 - [x] Notable popularity. ***Watch : 5 Star : 15 Fork : 8***
 - [x] Project has public repository on famous online hosting platform (or been hosted on npm)
 - [x] Has valid tags for each versions (for git auto-update)
 - [x] Auto-update setup
 - [x] Auto-update target/source is valid. Auto-update filemap is correct.

The repo linked below is only for collaborators and maintained the source files, not the production ready library. So the author provide the link above for adding in cdnjs.
https://github.com/Templarian/MaterialDesign ***Watch : 71  Star : 1144   Fork : 120***

**Comment by maruilian11** [comment]
@Piicksarn i think we can remove the `bug` field in package.json :)

**Comment by Piicksarn** [comment]
@maruilian11, it's fine now~:smiley:

**Comment by maruilian11** [comment]
@Piicksarn sorry for checking late, can you rebase it and tag me again? thank you very much!!!

**Comment by Piicksarn** [comment]
@maruilian11, would you please checkout the pr again? thank you!

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Comment by PeterDaveHello** [comment]
Why don't we need `fonts` folder ... I think you both keep use the wrong thinking to add a lib's files as we discussed again and again. Should grow up with your brain storming.

**Pull request closed without merging**
