### PR TITLE
Add AnimatedHeader@0.0.1

### PR DESCRIPTION
**Pull request by Piicksarn**
@PeterDaveHello, this is for #6223
Thank u!
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/codrops/AnimatedHeader
 * Official website (optional, not the repository): http://tympanus.net/codrops/2013/06/06/on-scroll-animated-header/
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 370
   - Count of watchers: 35
   - Count of forks: 151
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Do we need that CSS? If so, please also provide a minified version.

**Comment by Piicksarn** [comment]
@PeterDaveHello,
The usefulness of css file mentioned on the [homepage](http://tympanus.net/codrops/2013/06/06/on-scroll-animated-header/).
And the latest edition of PR include the minified component.css file.
Thank you

**Comment by PeterDaveHello** [comment]
Then I wonder if we also need `default.css` and the `fonts`, don't we?

**Comment by Piicksarn** [comment]
@PeterDaveHello, no, we need the files included in the pr only, `default.css` and `fonts` are for the html designing(demo page of library) not for user

**Comment by PeterDaveHello** [comment]
Okay, we'll see, thanks.

**Pull request merged**
