### PR TITLE
Crafty JS 0.6.3

### PR DESCRIPTION
**Pull request by icco**
Grabbed from:

 - https://github.com/craftyjs/Crafty/releases/download/0.6.3/crafty.js
 - https://github.com/craftyjs/Crafty/releases/download/0.6.3/crafty-min.js

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Would you please squash these commits into only one commit? And according to #3638, should also add auto-update config for it, thanks.

**Comment by icco** [comment]
Yeah, I was trying to avoid cloning down the whole thing since I'm not on a stable internet connection, but I'll give it a try.

**Comment by icco** [comment]
Interesting, apparently I can't squash the commits, because I have a case-insensitive filesystem, so cloning this causes uncomittable changes that I can't stash or revert. Wonderful.

**Comment by icco** [comment]
Also, I don't understand how to add autoupdate for sources like crafty that don't store a compiled version of their source in their repo.

**Comment by PeterDaveHello** [comment]
I think they do have in dist folder :)
https://github.com/craftyjs/Crafty/tree/0.6.3/dist

**Comment by icco** [comment]
Ah, I was just looking at the master branch.

Based on the documentation in that pull request you linked me, I still don't understand what the right options would be to setup this auto update.

**Comment by PeterDaveHello** [comment]
Maybe you can take this commit as an example? e0f588c
Git auto-updater will pull from tags only, we also support npm auto-update.

**Comment by icco** [comment]
Yeah, sorry, I don't get it. What's the base path in relation to? Is this documented anywhere?

Crafty looks like it might be an npm package, but I have no idea what npm auto-update is.

**Comment by PeterDaveHello** [comment]
For git auto-update, only #3638 for the instruction, bathPath is the relative path from the root of the project, and there is a part about npm auto-update in the readme, it'll grab versions from npm package.

**Comment by drewfreyling** [comment]
Closing due to no response.

**Pull request closed without merging**
