### PR TITLE
Issue 6312 updated repo url and deleted nonexistent libraries

### PR DESCRIPTION
**Pull request by NYCJacob**
Pull request for issue: # 6312
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:
   - Count of stars:
   - Count of forks:
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [X ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [X ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X ] The parent of the commit(s) in the PR is not old than 3 days.
 * [X ] Pull request is sending from a non-master branch with meaningful name.
 * [X ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by NYCJacob** [comment]
not sure what I did wrong.  Do I need to redo this pull?

**Comment by PeterDaveHello** [comment]
@NYCJacob you should not delete those libs.

**Comment by NYCJacob** [comment]
sorry, but what should I do to remove repo that no longer exist, I see documentation on updating repo but not for removing.

**Comment by PeterDaveHello** [comment]
@NYCJacob nope, we can't not remove them, it'll break the users' website.

**Comment by NYCJacob** [comment]
@PeterDaveHello well the repo in the url field is not there.  Should I just leave it alone and only change the repos that have new url?

**Comment by PeterDaveHello** [comment]
@NYCJacob if we can't find the repo, maybe just leave it alone.

**Comment by NYCJacob** [comment]
I am closing this submitting another pr.

**Comment by PeterDaveHello** [comment]
@NYCJacob No problem

**Comment by PeterDaveHello** [comment]
@NYCJacob if'll be better to mention the new PR you created #10589 👍

**Pull request closed without merging**
