### PR TITLE
Manually add css_browser_selector from GitHub repo

### PR DESCRIPTION
**Pull request by pvnr0082t**
Manually add css_browser_selector v0.2.7-0.4.0 by tracing commit log
Commit log info:
0.4.0 https://github.com/rafaelp/css_browser_selector/commit/1d3c1514342a1dfd34961ca3871312d40359bb8a
0.3.5 https://github.com/rafaelp/css_browser_selector/commit/09467767610e24d24d8e5cb93c276d57faa40d93
0.3.4 https://github.com/rafaelp/css_browser_selector/commit/a772cd1d699d027819cafdfd1428ee5a7c00d9dc
0.3.3 https://github.com/rafaelp/css_browser_selector/commit/7ea3afd5b337eabd40582881f5a0752cdfaa28dc
0.3.2 https://github.com/rafaelp/css_browser_selector/commit/978a46e373be2db5cd959c0a42db7a5d53b0daa6
0.3.1 https://github.com/rafaelp/css_browser_selector/commit/abf30920f58706196f4c4811326ae378f7b33a5a
0.3.0 https://github.com/rafaelp/css_browser_selector/commit/5b438b8dbbd6896eb89eba46c06624194ba712f0
0.2.9 https://github.com/rafaelp/css_browser_selector/commit/cd45a2e9116424ca201e79bfbf4facd9d425bcd3
0.2.8 https://github.com/rafaelp/css_browser_selector/commit/2dbf3a9a9b2784cc508fc3b48adee4db2aa550f3
0.2.7 https://github.com/rafaelp/css_browser_selector/commit/5ab892878a7311e0932a398c92a7bd307298c57a

@cdnjs/intern2 @maruilian11 Please help me review this pull request, thank you.

Pull request for issue: #6704 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/rafaelp/css_browser_selector
 * Official website (optional, not the repository): http://rafael.adm.br/css_browser_selector/
 * License and its reference: CC-BY-2.5 https://creativecommons.org/licenses/by/2.5/
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 35
   - Count of stars: 608
   - Count of forks: 168

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by maruilian11** [comment]
please also mention the source in commit msg.

**Comment by pvnr0082t** [comment]
@maruilian11 @cdnjs/intern2 I've modified commit message and mentioned the source of the files. Please help me review it again, thank you.

**Comment by maruilian11** [comment]
should wrap commit msg content in 72 character.

**Comment by pvnr0082t** [comment]
@maruilian11 @cdnjs/intern2 I try to wrap my commit message. Please help me review it again, thank you.

**Comment by maruilian11** [comment]
@pvnr0082t hmmm... did you? I still see the second line of commit msg too long...
```
Add css_browser_selector v0.2.7-0.4.0 by tracing GitHub commit log, close #6704, cc @rafaelp
```

**Comment by maruilian11** [comment]
http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by pvnr0082t** [comment]
@maruilian11 @cdnjs/intern2 I tried to wrap the commit message. Please help me review it again, thank you.

**Comment by maruilian11** [comment]
We should separate adding the latest version and package.json and adding old versions, shouldn't we?

**Comment by pvnr0082t** [comment]
@maruilian11 Thanks. I have separated into two commits. Please help me review it again, thank you. @cdnjs/intern2

**Comment by pvnr0082t** [comment]
I have rebased with the latest master branch. Please help me review it again, thank you. ping @maruilian11 @cdnjs/intern2

**Comment by sufuf3** [comment]
ping @extend1994

**Comment by sufuf3** [comment]
@pvnr0082t May I ask that why don't we just use one commit to add all versions?
Because all versions need to be added manually.

And the lib release many new versions.

And the second commit message `Add css_browser_selector v0.2.7-v0.3.5 by tracing GitHub commit log` maybe change to `commit logs` is better?

What do you think?

Thank you.

**Comment by PeterDaveHello** [comment]
@pvnr0082t ?

**Comment by sufuf3** [comment]
@pvnr0082t Would you mind working on this and helping improve this PR?

Many thanks.

**Comment by sashberd** [comment]
@sufuf3 @extend1994 @PeterDaveHello I cannot rebase this PR to lates master. Can you help me to rebase or just close this PR

**Comment by extend1994** [comment]
Fail to rebase to latest master branch.

**Comment by PeterDaveHello** [comment]
@extend1994 conflicts?

**Comment by extend1994** [comment]
@PeterDaveHello 
```
fatal: write failure on 'stdout': No space left on device
```

my `df` result is like
```
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs   16G     0   16G   0% /dev
tmpfs          tmpfs     3.2G  8.0M  3.2G   1% /run
/dev/sr0       iso9660   251M  251M     0 100% /lib/live/mount/medium
/dev/loop0     squashfs  220M  220M     0 100% /lib/live/mount/rootfs/rescue_rootfs.squashfs
tmpfs          tmpfs      16G     0   16G   0% /lib/live/mount/overlay
overlay        overlay    16G  9.2G  6.6G  59% /
tmpfs          tmpfs      16G  496K   16G   1% /dev/shm
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs      16G     0   16G   0% /sys/fs/cgroup
tmpfs          tmpfs     3.2G     0  3.2G   0% /run/user/0
tmpfs          tmpfs     3.2G     0  3.2G   0% /run/user/1000
```

Still try to figure out what's the problem.

**Comment by PeterDaveHello** [comment]
@extend1994 something is wrong, the info you posted seems to be rescue environment.

**Comment by extend1994** [comment]
Can't access it via `ssh` now, I guess I should wait for a while?

**Comment by sufuf3** [comment]
@sashberd Let's mention git commit hash in the commit messages because it's good for tracing git log & maintain this project.
What do you think?
Many thanks.

**Comment by sashberd** [comment]
@sufuf3 Done. FYR

**Comment by sashberd** [comment]
@extend1994 The PR was updated.

What about this note [above](https://github.com/cdnjs/cdnjs/pull/11038#issuecomment-407057659):

> For discussion: The lib has new version, over 0.4.0, but I can not find exact commits of them. May be we can add them in separate commit, if you will help me to find them in commit log. Thanks

**Comment by sashberd** [comment]
@xtuc I think it is not possible here to create package.json cause all version were taken from commit list

**Comment by MattIPv4** [comment]
Yup, looks like there are no tagged versions for this. I guess we won't add it then as we are moving away from adding libraries that don't have either git or npm auto-update.

**Comment by xtuc** [comment]
Ok, that's interesting. From a security perpective letting people add unreviewable code is not great. Maybe we can figure out another protocol for autoupdate, branch glob? commit? etc I don't know

**Comment by MattIPv4** [comment]
I think it's a reasonable requirement to either have tagged releases on git or a versioned NPM package. If we don't have either of those, there is no easy way to determine when a new version exists.

**Comment by sashberd** [comment]
@MattIPv4 So what to do with this one? Close it?

**Comment by xtuc** [comment]
We don't allow manual adding anymore. Please add autoupdate to your package, see contributing.md files in the repo

**Pull request closed without merging**
