### PR TITLE
Add vanilla-masker@1.1.0

### PR DESCRIPTION
**Pull request by Piicksarn**
**git repo url:** https://github.com/BankFacil/vanilla-masker
**Watch 44
  Star 456
 Fork 46**
@maruilian11,  could you help for me check out the PR, which is referenced to  #6378 ? thank you~
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by maruilian11** [comment]
@Piicksarn you need `keywords` and `requiredFiles`.

**Comment by Piicksarn** [comment]
requiredFiles?~
@maruilian11, i don't understand about adding requiredFiles :sweat_smile:

**Comment by maruilian11** [comment]
Requiredfile is show min file didn't added by author, I just find this case didn't need requiredfiles because the only  min file already pointed in filename. You just need to add keywords in this case

**Comment by PeterDaveHello** [comment]
Should use npm auto-update.

**Comment by PeterDaveHello** [comment]
We have a small problem here, please rebase with our latest master branch, sorry for the inconvenient caused.

**Comment by Piicksarn** [comment]
https://github.com/BankFacil/vanilla-masker/pull/67

**Comment by Piicksarn** [comment]
@PeterDaveHello, @maruilian11, 
i have it corrected, would you mind to have a look at the pr again?
thank you!

**Comment by PeterDaveHello** [comment]
There is no need to review a test failed PR until you fix it @Piicksarn

**Comment by Piicksarn** [comment]
@maruilian11, would you mind to have a look again? Thank you!!

**Comment by maruilian11** [comment]
@Piicksarn please correct your commit message, and use files in `build`.

**Comment by Piicksarn** [comment]
@maruilian11, i have it corrected~
would you please have a look again~
Thank you! :smiley:

**Comment by Piicksarn** [comment]
@maruilian11, would you mind to have a look again? Thank you!!

**Pull request merged**
