### PR TITLE
[Author][New] Add innate.js@0.2.2 w/ git auto-update

### PR DESCRIPTION
**Pull request by wout**
A micro library eliminating the need for jQuery in most common tasks.

Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): wout/innate.js
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference: wout/innate.js/blob/master/MIT-LICENSE
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 1
   - Count of stars: 3
   - Count of forks: 0
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@wout Thanks for the PR, however, this [library](https://github.com/wout/innate.js) doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue or send a PR, I'll respectfully suggest you send a new PR again or open an issue when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this PR in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this PR will be closed.

Thanks for being interested in CDNJS.

**Comment by sufuf3** [comment]
@PeterDaveHello Could we close this PR?
Because there is no response from the author 7 days.
Also, in this PR, this lib doesn't have enough notable popularity.

Many thanks.

**Comment by PeterDaveHello** [comment]
@sufuf3 sure, we can reopen it later if we need.

**Comment by extend1994** [comment]
Help close this PR due to insufficient popularity and no response in 7 days.

**Pull request closed without merging**
