### PR TITLE
add ornajs@2.1.2

### LINKED ISSUE #6959: [Request] OrnaJS
**Library name: *OrnaJS* 
**Git repository url:*https://github.com/OrnaOrg/OrnaJS
**npm package url(optional):*https://www.npmjs.com/package/orna* 
**License(s):*MIT*
**Official homepage:*http://ornaorg.github.io*
**Wanna say something? Leave message here:*OrnaJS - make extension for inline style, like : inheritance, event, abbreviation*

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by Piicksarn**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): *https://github.com/OrnaOrg/OrnaJS/tree/1.7.0*
 * Official website (optional, not the repository): *http://ornaorg.github.io*
 * NPM package url (optional): *https://www.npmjs.com/package/ornajs*
 * GitHub / Bitbucket popularity (required):
   - Count of stars: **3**
   - Count of watchers: **5**
   - Count of folks: **2**
 * NPM download stats (optional):
   - Downloads in the last day: **6**
   - Downloads in the last week: **131**
   - Downloads in the last month: **191**

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #6959, cc @DimaPopov

### CODE REVIEW

**Comment by Piicksarn** [comment]
@maruilian11, would you mind to have a look at the pr?
Thank you!

**Comment by PeterDaveHello** [comment]
Why don't you fill the "Profile of the lib" @Piicksarn ?

**Comment by maruilian11** [comment]
@Piicksarn the author seems update the version to 1.1.0, and could you please mention the issue number, git repo url and popularity next time？thank you~

**Comment by Piicksarn** [comment]
@maruilian11, would you mind to have a look at the pr again?
Thank you!

**Comment by maruilian11** [comment]
@1.8.0 was released 23 hours ago :sob:

**Comment by PeterDaveHello** [comment]
Why don't you use npm update?

**Comment by Piicksarn** [comment]
@maruilian11, would you please checkout the pr again?
Thanks a lot.

**Comment by PeterDaveHello** [comment]
Would you please tell me what's the reason why to manually add 1.7.0 and 2.1.0 at the same time? What about v1.8.0?

**Comment by Piicksarn** [comment]
@PeterDaveHello, the lib have only current version on github, so i could not get the v1.8.0.

**Comment by PeterDaveHello** [comment]
> the lib have only current version on github, so i could not get the v1.8.0.

I think you are using npm auto-update here ... There is v1.8.0 package on npm.

**Comment by PeterDaveHello** [comment]
Since there is no structure changes, you don't need to add v1.7.0 here.

**Comment by Piicksarn** [comment]
@PeterDaveHello, ok & thanks!

**Comment by PeterDaveHello** [comment]
So please update.

**Comment by Piicksarn** [comment]
@PeterDaveHello, updated!

**Pull request merged**
