### PR TITLE
Updated qooxdoo's versions to 4.1.1 and 5.0 [author]

### PR DESCRIPTION
**Pull request by wittemann**
Source taken form http://qooxdoo.org/downloads/qx.website

Direct links:
4.1.1: http://demo.qooxdoo.org/4.1.1/framework/q-4.1.1.js
4.1.1 min: http://demo.qooxdoo.org/4.1.1/framework/q-4.1.1.min.js
4.1.1 indigo: http://demo.qooxdoo.org/4.1.1/framework/indigo-4.1.1.css

5.0: http://demo.qooxdoo.org/5.0/framework/q-5.0.js
5.0 min: http://demo.qooxdoo.org/5.0/framework/q-5.0.min.js
5.0 indigo: http://demo.qooxdoo.org/5.0/framework/indigo-5.0.css

I'm sorry we did not manage to gat any kind of auto update set up until now. But to make sure we get that done until next release, I opened up a report on our side: http://bugzilla.qooxdoo.org/show_bug.cgi?id=9168

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
> We can’t automatically merge this pull request.

**Comment by PeterDaveHello** [comment]
Commit's parent is toooooooooooooooooo old, should rebase on our latest master branch.

**Comment by wittemann** [comment]
Sorry, I thought i did the rebase before. But doing so I had serious trouble on OSX with the ajax/libs/Sortable/package.json file which seems to have changed right after an clean checkout. After digging in it seems to have to do with the capital folder name. To fix that, I added two additional commits which should not change anything hopefully.

**Comment by PeterDaveHello** [comment]
Try this : https://github.com/cdnjs/cdnjs/blob/master/sparseCheckout.md, the last 2 commits should be removed.

**Comment by wittemann** [comment]
That should do it hopefully.

**Comment by PeterDaveHello** [comment]
Nice, btw, can you setup auto-update config for it?

**Comment by wittemann** [comment]
Not right now but I opened up an issue to make sure we have that ready for the next time: http://bugzilla.qooxdoo.org/show_bug.cgi?id=9168

**Comment by wittemann** [comment]
Thanks. :)

**Comment by PeterDaveHello** [comment]
np

**Pull request merged**
