### PR TITLE
HTTPS link to https://lunrjs.com

### PR DESCRIPTION
**Pull request by coliff**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Shouldn't this be made upstream to the lunr.js package?

**Comment by coliff** [comment]
It is updated there already... not sure if it gets updated here automatically upon the next release though.

**Comment by XhmikosR** [comment]
OK so this PR is moot then :) When the package is updated here, it'll be fixed.

**Comment by coliff** [comment]
cool. no problem, I'll close this PR then.

**Pull request closed without merging**
