### PR TITLE
add angular-tooltips w/ npm autoupdate

### LINKED ISSUE #8196: [Request] Add Angular Tooltips
**Library name:**  Angular Tooltips
**Git repository url:** https://github.com/720kb/angular-tooltips

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35000959-request-add-angular-tooltips?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8196 
@kennynaoh Please help me review this pull request, thank you.
Because v1.1.3 is the only version without minified files, I manually minify them.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/720kb/angular-tooltips
- Official website (optional, not the repository): https://720kb.github.io/angular-tooltips
- NPM package url (optional): https://www.npmjs.com/package/angular-tooltips
- GitHub / Bitbucket popularity (required):
  - Count of stars: 245
  - Count of watchers: 10
  - Count of forks: 116
- NPM download stats (optional):
  - Downloads in the last day: 92
  - Downloads in the last week: 602
  - Downloads in the last month: 2785
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [x] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [x] More than 500 downloads stats per month on npm registry
- [x] Project has public repository on famous online hosting platform (or been hosted on npm
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

close #8196 , cc @45kb

### CODE REVIEW

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Comment by PeterDaveHello** [comment]
@kennynaoh please tell me the steps you reviewed this PR, since this kind of PRs are much more complex.

**Comment by kennynaoh** [comment]
I fetched the branch and confirmed the contents of these two commits.

**Comment by PeterDaveHello** [comment]
@kennynaoh, I meant how to you confirm the content, thanks.

**Comment by pvnr0082t** [comment]
ping @kennynaoh

**Comment by kennynaoh** [comment]
There are some versions on github but not on npm.
`0.1.1`~`0.1.16`, `0.1.19`, `1.0.2`, `1.0.4`
They were added manually.
And there are 41 releases, is the same as the amount of release on github.

**Comment by PeterDaveHello** [comment]
@x09326 would you please also help review this PR? Thanks.

**Comment by x09326** [comment]
@PeterDaveHello 
I think it is okay.
@pvnr0082t has added them all manually.

**Comment by PeterDaveHello** [comment]
@pvnr0082t let's rebase it first.

**Comment by pvnr0082t** [comment]
@x09326 @kennynaoh I have rebased it. Please help me review again, thank you.

**Comment by PeterDaveHello** [comment]
@pvnr0082t we should keep the structure consistency, v1.1.4 started to provide officially minified files, so please don't generate the map file for previous versions.
Adding some features in new versions will be okay, but adding some features in only old versions makes no sense.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@pvnr0082t If you have time, please help fix this PR and let it be merged.
Thank you

**Comment by sufuf3** [comment]
@pvnr0082t
Would you mind working on this and help improve this PR?

This will be a great work.
Many thanks.

**Pull request closed without merging**
