### PR TITLE
[New][Author] Add webpack-cesium@1.31.2 w/ npm auto-update

### PR DESCRIPTION
**Pull request by TJKoury**
Pull request for issue: #11442
Related issue(s): None

# Profile of the lib
 * Git repository: 
    - https://github.com/AnalyticalGraphicsInc/cesium
    - https://github.com/DigitalArsenal/webpack-cesium
 * Official website (optional, not the repository): https://cesiumjs.org
 * NPM package url: 
    - https://www.npmjs.com/package/webpack-cesium
    - https://www.npmjs.com/package/cesium
 * License and its reference: 
    - [ISC](http://www.isc.org/downloads/software-support-policy/isc-license)
    - [Apache 2](http://www.apache.org/licenses/LICENSE-2.0.html)
 * GitHub / Bitbucket popularity: 
   - Count of watchers: 268
   - Count of stars: 2,268
   - Count of forks: 1,092
 * NPM download stats:
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by dakshshah96** [comment]
Hi @TJKoury, you didn't need to create a new pull request :)

Anyway, right now.. You need to use 2 spaces as indent and remove trailing spaces. That should fix the CI error.

**Comment by TJKoury** [comment]
Still working on it, have to do this on Windows right now and even with sparseCheckout enabled every operation takes ~20 minutes....

**Comment by TJKoury** [comment]
I think I got the formatting correct using the tool.  @dakshshah96, just squashed the commits.

**Comment by dakshshah96** [comment]
@PeterDaveHello Some problem with the tests here? They aren't running I guess.

**Comment by TJKoury** [comment]
@sufuf3 @dakshshah96 those are compressed files, gzip and brotli respectively.  I don't think you can use them in tags, but I wasn't sure how your platform deals with precompressed files.  We can change the mapping if that makes sense.

**Comment by TJKoury** [comment]
I don't want to remove them from my repo as they are very useful, but I can
update the file so that you don't pull them.  Does that work?

On Jun 26, 2017 11:05 AM, "Daksh Shah" <notifications@github.com> wrote:

*@dakshshah96* requested changes on this pull request.

@TJKoury <https://github.com/tjkoury> You're right. We can't use them.

Please remove those files and change the file rule as well :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cdnjs/cdnjs/pull/11461#pullrequestreview-46289736>, or mute
the thread

**Comment by PeterDaveHello** [comment]
There is no need to add gz file as we'll gzip them on the fly, and also the br in future.

**Comment by TJKoury** [comment]
Sounds good, will remove and change the entry in the package.json.

**Comment by TJKoury** [comment]
@PeterDaveHello Should be good now.

**Comment by dakshshah96** [comment]
@TJKoury Yes, I meant you should remove the files from your commit :)

Looks fine now!

**Comment by TJKoury** [comment]
Bingo, @dakshshah96.  @sufuf3 the idea is to pre-webpack the entire complex library so that users don't have to worry about any loading any other dependencies.

**Comment by sufuf3** [comment]
@cdnjs/library-reviewer 
Please help review this PR, Thank you.

**Comment by PeterDaveHello** [comment]
@TJKoury if it's released under with not only single license, do you want to mention them on its cdnjs page?

**Comment by TJKoury** [comment]
@PeterDaveHello Sure.

**Comment by PeterDaveHello** [comment]
@TJKoury any idea about what its license should be in fact?

**Comment by TJKoury** [comment]
@PeterDaveHello The original Cesium code is Apache2, my minor contributions that are rolled into this version to make them Webpack compatible I'm releasing under ISC, which is a little more permissive (not trying to start a debate though).

**Comment by PeterDaveHello** [comment]
@TJKoury do we need to discuss this with its origin author about how should it looks like on CDNJS? Another question, as I'm not familiar with license, is ISC compatible with Apache-2.0(If so, any reference please)? Many thanks.

**Comment by TJKoury** [comment]
@PeterDaveHello Yes it's compatible, if you want me to switch to Apache2 for ease of reference I can do that, it's not a problem.

**Comment by PeterDaveHello** [comment]
@TJKoury nope, I just want to make sure everything is good, as I'm not familiar with license issue, so just ask you. The problem here is how should we display its license on the page, any suggestion or idea?

**Comment by TJKoury** [comment]
@PeterDaveHello I'll just change it to reduce confusion, there is no practical difference.

**Comment by PeterDaveHello** [comment]
@TJKoury it'll be also great! Thanks a lot!

**Comment by PeterDaveHello** [comment]
@TJKoury would you also update the license here: https://github.com/DigitalArsenal/webpack-cesium/blob/master/package.json#L31 ?

**Comment by TJKoury** [comment]
@PeterDaveHello Done

**Pull request merged**
