### PR TITLE
update auto-update cfg & add missing files of jquery-validate

### LINKED ISSUE #9491: [Request] Add jquery-validation localization
Library name:  jquery-validation
Git repository url: https://github.com/jzaefferer/jquery-validation/tree/master/src/localization

The jquery-validate library has already in cdnjs, but the localization is not.
=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
Pull request for issue: #9491 
@kennynaoh @x09326 Please help me review this pull request, thank you.
- update git auto-update config & add missing files for v1.9.0 - v1.15.1
- Manually add v1.6.0-v1.8.1 because the file structure are different from the latest version.

close #9491

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
ping @x09326 @kennynaoh

**Comment by kennynaoh** [comment]
@pvnr0082t 
There is a non-js file under `src/localization` in the latest version.
I think it's a mistake of filename.
Could you discuss with author to fix it?
Thanks!

**Comment by pvnr0082t** [comment]
@kennynaoh @x09326 `messages_az` had been fixed to `messages_az.js` in the latest version. I manually rename it for v1.15.1. Please help me review it again, thanks.

**Comment by pvnr0082t** [comment]
ping @kennynaoh @x09326

**Comment by kennynaoh** [comment]
LGTM

**Comment by pvnr0082t** [comment]
@kennynaoh @x09326 I just rebased onto the latest master branch. Please help me review it again, thank you.

**Comment by kennynaoh** [comment]
LGTM

**Comment by pvnr0082t** [comment]
@kennynaoh @x09326 I have added reason in second commit message. I manually added v1.6.0-v1.8.1 because the file structure are different from the latest version. Please help me review it again, thank you.

**Comment by kennynaoh** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Pull request merged**
