### PR TITLE
[Bernardo Silva] [new] - Add angular-truncate v2 initial versions.

### PR DESCRIPTION
**Pull request by BernardoSilva**
Those files were generated from these releases:
https://github.com/BernardoSilva/angular-truncate/releases

The project was not maintained for a long time, so since a few months now I am maintaining it for community.

This to fix an issue open in original project here: https://github.com/sparkalow/angular-truncate/issues/28
And fixes https://github.com/cdnjs/cdnjs/issues/5743

### CODE REVIEW

**Comment by BernardoSilva** [comment]
@maruilian11 Can you check if this PR is correct or if I need to do something else?

**Comment by PeterDaveHello** [comment]
The popularity of this lib is not enough to add this lib, and I think #5743 is asking [sparkalow/angular-truncate](https://github.com/sparkalow/angular-truncate).

**Comment by BernardoSilva** [comment]
Ok, Just wanted to help since the original lib is not maintained. :)
Your call.

**Comment by PeterDaveHello** [comment]
Hi @BernardoSilva, I found that you have npm package for this lib, and the stats of npm package is close to our requirement, would you mind to send a new PR to add your lib, or you can rebase your branch of this PR with our latest master branch? Thanks!

**Comment by PeterDaveHello** [comment]
BTW, I will treat your forked version as another lib, maybe naming like `BernardoSilva-angular-truncate` will be better.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by maruilian11** [comment]
@PeterDaveHello Since there is no response for a while, can we add the lib ourselves as @BernardoSilva's lib `angular-truncate-2`

**Comment by BernardoSilva** [comment]
@PeterDaveHello will have a look this week. 
Sorry for my late reply

**Comment by PeterDaveHello** [comment]
@BernardoSilva Thanks for the update.

**Comment by PeterDaveHello** [comment]
I'll rebase this PR/branch to reflect current testing result on CI first, so you can see if there is something needs fixing.

**Comment by PeterDaveHello** [comment]
oops .. @BernardoSilva would you please check the checkbox [ ] `Allow edits from maintainers.` in this page so that I can help you upload this branch? I uploaded 2GB updates for this branch but forgot that this is an old PR which has no the option enabled by default, so the update failed. Thanks.

**Comment by sufuf3** [comment]
@BernardoSilva thanks for contribution.
Would you like to work on this and help improve this PR as this [comment](https://github.com/cdnjs/cdnjs/pull/6084#issuecomment-330031708)?
If you have any question, please let us know.

Many thanks.

**Comment by BernardoSilva** [comment]
I think binding my own name into the library does not sound correct since I was not the original author.

having it as angular-truncate-2 sounds correct since everyone know it's just another version of the same library, in this case it has some improvements but is not a total rewrite or anything like it. :) 

I've also tried to rebase it but I failed since I ran out of space on my laptop at the moment :( 

@sufuf3 is there any other way to get my PR rebased?

**Comment by sufuf3** [comment]
@BernardoSilva Thanks for your reply.
@PeterDaveHello as your [comment](https://github.com/cdnjs/cdnjs/pull/6084#issuecomment-191763933), you hope the lib's name can be `BernardoSilva-angular-truncate` but the author [said](https://github.com/cdnjs/cdnjs/pull/6084#issuecomment-356580091) `angular-truncate-2` sounds correct since everyone knows this case.

What did you think?
Many thanks

PS. If the lib's name is fine, maybe we can continue to work on this PR.

**Comment by sashberd** [comment]
@PeterDaveHello @sufuf3 @extend1994 Can not rebase this PR to latest master. Please help me to do this or just close this PR

**Pull request closed without merging**
