### PR TITLE
[new] OpenLayers 3.1.1

### PR DESCRIPTION
**Pull request by nulltask**
added OpenLayers v3.1.1

- https://github.com/openlayers/ol3

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Is it possible to add auto-update config for this lib @nulltask ？

**Comment by nulltask** [comment]
Nice suggestion! But it is impossible to be auto-update because the tar-ball doesn't contain built files. :cry:

**Comment by PeterDaveHello** [comment]
No, I found its npm package with dist folder, please check it out, thanks.

**Comment by nulltask** [comment]
@PeterDaveHello Oh, my mistook. Thank you for your reply. I've just added fields to be auto update. But I can not squash these commits. (maybe #3650 is related issue.)

**Comment by PeterDaveHello** [comment]
Okay, thanks.

**Comment by nulltask** [comment]
Thank you, too!

**Pull request merged**
