### PR TITLE
add knockout-es5 v0.4.0 with autoupdate config

### LINKED ISSUE #7619: [Request] Add knockout-es5
**Library name:**knockout-es5 
**Git repository url:**https://github.com/SteveSanderson/knockout-es5
**npm package url(optional):** knockout-es5
**License(s):**MIT
**Official homepage:**http://blog.stevensanderson.com/2013/05/20/knockout-es5-a-plugin-to-simplify-your-syntax/
**Wanna say something? Leave message here:**
Everyone that uses knockoutjs want use this also. So will be very aprecited if we can have it from here.

### PR DESCRIPTION
**Pull request by dannyxx001**
PR for #7619
@x09326 please help me review this PR, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/SteveSanderson/knockout-es5
- Official website (optional, not the repository): http://blog.stevensanderson.com/2013/05/20/knockout-es5-a-plugin-to-simplify-your-syntax/
- NPM package url (optional): https://www.npmjs.com/package/knockout-es5
- GitHub / Bitbucket popularity (required):
  - Count of stars: 150
  - Count of watchers: 13
  - Count of forks: 36
- NPM download stats (optional):
  - Downloads in the last day: 10
  - Downloads in the last week: 69
  - Downloads in the last month: 113
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [x] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [ ] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

close #7619, cc @SteveSanderson

### CODE REVIEW

**Comment by x09326** [comment]
The latest version of this project in github is 0.4.2, you can open an issue to ask the author to update this project in npm.

**Comment by PeterDaveHello** [comment]
@x09326 Of course yes, nice catch.

**Comment by x09326** [comment]
@dannyxx001 
Please open an issue to ask the author, then you need to change the files to v0.4.2 and modify the PR title and commit message.

**Comment by x09326** [comment]
Wait for response.
https://github.com/SteveSanderson/knockout-es5/issues/54

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by dakshshah96** [comment]
Moved to #11445

**Pull request closed without merging**
