### PR TITLE
Create issue template

### PR DESCRIPTION
**Pull request by julmot**
When clicking the "Request a lib" button on the website you will be redirected [to this URL](https://github.com/cdnjs/cdnjs/issues/new?title=%5BRequest%5D%20Add%20_library_name_%20&body=**Library%20name%3A**%20%0A**Git%20repository%20url%3A**%0A**npm%20package%20url(optional)%3A**%20%0A**License(s)%3A**%0A**Official%20homepage%3A**%0A**Wanna%20say%20something?%20Leave%20message%20here%3A**%0A%0A=====================%0ANotes%20from%20cdnjs%20maintainer%3A%0APlease%20read%20the%20README.md%20and%20CONTRIBUTING.md%20document%20first.%0A%0AYou%20are%20welcome%20to%20add%20a%20library%20via%20sending%20pull%20request%2C%0Ait%27ll%20be%20faster%20then%20just%20opening%20a%20request%20issue%2C%0Aand%20please%20don%27t%20forget%20to%20read%20the%20guidelines%20for%20contributing%2C%20thanks!!). The issue message will be automatically filled. However, when creating a new issue directly from within GitHub, no issue message will be shown. This is solved with this template.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
We don't use this feature since ths link on the website is enough, most of the guys on GitHub knows how to open an issue.

**Comment by thomasdavis** [comment]
@PeterDaveHello Sounds like a pretty harmless addition that would have some benefit though?

**Comment by julmot** [comment]
@PeterDaveHello I wasn't coming from the website and didn't know what information to provide in a new isssue. Therefore I needed to make a research and found the link on the website. So from my point of view it wouldn't be that bad to use a issue template.

**Comment by PeterDaveHello** [comment]
Most of the directly opened issues on GitHub is not for request adding a lib, but some problems, maybe just leave a message in the GitHub template to tell the user want to request a lib to go to another link, maybe like https://cdnjs.com/requres-new-lib, so that I can maintain a single template.

**Comment by julmot** [comment]
@PeterDaveHello The link you've provided causes `Cannot GET /requres-new-lib`.

> Most of the directly opened issues on GitHub is not for request adding a lib, but some problems

how can you know that?

**Comment by PeterDaveHello** [comment]
I haven't add it, since this is still under discussion, you can update this PR first, I'll add that link once we can merge this PR.

**Comment by julmot** [comment]
@PeterDaveHello Alright, I'll update the template to include this link. But are you sure that `requres` is correctly? Did you mean `require` or better `request`?

**Comment by PeterDaveHello** [comment]
@julmot typo, should be request, thanks.

**Comment by PeterDaveHello** [comment]
Maybe we don't need to use markdown here, since this message won't be parsed before issue opened.

**Pull request merged**
