### PR TITLE
Add angular-auth0@1.0.6 w/ git auto-update

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #10556

@cdnjs/intern3 Please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/auth0/angular-auth0
 * NPM package url (optional): https://www.npmjs.com/package/angular-auth0
 * License and its reference: [MIT]()
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 3
   - Count of stars: 5
   - Count of forks: 2
 * NPM download stats (optional):
   - Downloads in the last day: 21
   - Downloads in the last week: 394
   - Downloads in the last month: 1,233

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by clairetsai818** [comment]
Same as sufuf3. I can't find that minified file neither on npm or GitHub.

**Comment by extend1994** [comment]
@sufuf3 @clairetsai818 it's minified by me. I didn't generate the map file because there is is no map file in later versions.

**Comment by sufuf3** [comment]
What minify tool did you use?
You didn't use https://github.com/PeterDaveHello/web-minify-helper , did you?

**Comment by extend1994** [comment]
@sufuf3 I use web-minify-helper. Anything wrong?

**Comment by PeterDaveHello** [comment]
@extend1994 #10842 has higher priority then #10556

**Comment by extend1994** [comment]
@PeterDaveHello Okay, I will do it.

**Comment by PeterDaveHello** [comment]
@sufuf3 reason why to approve? It's weird that you approved but there isn't any changes during this period, I can't find related discussion either.

**Comment by sufuf3** [comment]
I thought that the old version should include the map file, but if the newest version only includes `js` and `min.js` maybe the map file could exclude from v1.0.0.

**Comment by extend1994** [comment]
@cdnjs/intern3 I should add stable version of the library, please review it.

**Comment by PeterDaveHello** [comment]
@hare1039 @clairetsai818 ?

**Pull request merged**
