### PR TITLE
add multiscroll.js with npm auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
**npm package url:** https://www.npmjs.com/package/multiscroll.js
**git repo url:** https://github.com/alvarotrigo/multiscroll.js
**Watch 53
  Star 840
 Fork 259**
@Amomo could u help me check this PR for #8795 ? thank you!
**there is only the latest version(0.1.7) on npm package, i have opened the [issue](https://github.com/alvarotrigo/multiscroll.js/issues/74) for the old ones.**

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR 
 * [x] The lib has notable popularity 
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry 
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update) 
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
What about the versions not published on npm?

**Comment by maruilian11** [comment]
@Amomo I have added old version in this commit, could you help me check this PR? thank you!

**Comment by PeterDaveHello** [comment]
@Piicksarn please help review this PR, thanks.

**Comment by Piicksarn** [comment]
@PeterDaveHello,
I have a question that, should we always create **`.map`** for **.css** and **.js** file(if there isn't map file in lib)? :joy: ??

**Comment by PeterDaveHello** [comment]
@Piicksarn Only when you need to minify it.

**Comment by Piicksarn** [comment]
@maruilian11, the parent of the commit in the PR is too old ! :hushed: 
And the content of the pr is fine.

**Comment by maruilian11** [comment]
@Amomo @Piicksarn I have rebased upon our latest master branch.

**Comment by PeterDaveHello** [comment]
Wrong PR title.

**Pull request merged**
