### PR TITLE
[author] Add 2.7.4 of oCanvas

### PR DESCRIPTION
**Pull request by koggdal**
Thanks!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Is is possible to add auto-update config for it?

**Comment by koggdal** [comment]
Thanks for merging it so quickly!

It's pretty much in maintenance mode now (last release was in July). I started on the next major version a while back, but life happened and has delayed the project. But I'm not expecting to make a lot of releases until that's ready for release, and then I'll definitely set up auto-update for it!

**Comment by PeterDaveHello** [comment]
Fine.

**Comment by koggdal** [comment]
Oh, sorry, I didn't read the updated README with new instructions about that. I'll definitely do it for the next update whenever that happens!

**Comment by PeterDaveHello** [comment]
Sure.

**Pull request merged**
