### PR TITLE
Update for showdown

### PR DESCRIPTION
**Pull request by tivie**

### CODE REVIEW

**Comment by drewfreyling** [comment]
Are you able to squash your commits down to one please?

**Comment by tivie** [comment]
How can I do that? Issue a new PR? (i've done it this way because your repo is 4gb!!!)

**Comment by PeterDaveHello** [comment]
Should try this:
https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#a-sparse-checkout-and-shallow-clone

**Comment by PeterDaveHello** [comment]
We already had those versions.

**Pull request closed without merging**
