### PR TITLE
add jsrsasign w/ npm auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
@Amomo @Piicksarn could u help me check this PR for #8792 ? thank you!

**git repo url:** https://github.com/kjur/jsrsasign
**Watch 61
  Star 752
 Fork 142**

**npm package url:** https://www.npmjs.com/package/jsrsasign
**1,558 downloads in the last day
7,705 downloads in the last week
38,497 downloads in the last month**

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR 
 * [x] The lib has notable popularity  
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry 
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update) 
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
64 releases on GitHub but only 27 on npm package? Don't you need to try to manually add them all?

**Comment by Piicksarn** [comment]
@maruilian11, the lib releases the new version~

**Comment by maruilian11** [comment]
@Amomo @Piicksarn 
thanks for helping me review this huge PR.
I used git auto-update and npm auto-update to catch files in this commit.
I can't find `jsrsasign*.js` from v1.2.0 ~ v4.1.0,
v0.0.1 ~ v0.0.3, v4.8.2 ~ v5.1.0 are from npm package.
v4.1.1 ~ v4.8.1 are from git repo.
v4.1.1 ~ v4.1.5 are `.min` files with version in their names, I have corrected them to `jsrsasign.min.js`

**Comment by maruilian11** [comment]
ping @Piicksarn @Amomo

**Pull request merged**
