### PR TITLE
Add fontIconPicker w/ git auto-update via single package.json

### PR DESCRIPTION
**Pull request by khursani8**
Pull request for issue: #11514
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/micc83/fontIconPicker
 * Official website (optional, not the repository): https://codeb.it/fonticonpicker/
 * NPM package url (optional):
 * License and its reference: https://github.com/micc83/fontIconPicker/blob/master/LICENSE
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 20
   - Count of stars: 215
   - Count of forks: 76
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by khursani8** [comment]
Hi @sufuf3 
I'm using Github website for pull request and thank you for helping me solving this issue.

**Comment by sufuf3** [comment]
@khursani8 Thank you.
If you have any question, please let me know.
I can help you.  😃

**Comment by sufuf3** [comment]
@khursani8 do you need help?
If you have any question, please let me know.
I can help you. 😃

**Comment by PeterDaveHello** [comment]
Let's close this one as @khursani8 deleted the repository, this pull request can't be updated any more. 

@khursani8 please send a new one if you have time, thanks.

**Pull request closed without merging**
