### PR TITLE
point ace.js to ace.min.js, #5195

### PR DESCRIPTION
**Pull request by maruilian11**
@Piicksarn could u help me check this pr from #5195? thx.

### CODE REVIEW

**Comment by Piicksarn** [comment]
It's fine!
@PeterDaveHello,would you please take a look for this PR.
Thank you!

**Comment by PeterDaveHello** [comment]
Would you like to minify all the ace.js in each version?

**Comment by maruilian11** [comment]
@PeterDaveHello is that right?

**Comment by Piicksarn** [comment]
@PeterDaveHello, it's fine!

**Comment by PeterDaveHello** [comment]
Should also say that you minified it in commit message.

**Comment by maruilian11** [comment]
@PeterDaveHello is that ok?

**Comment by PeterDaveHello** [comment]
You should ping @Piicksarn first, not me.

**Comment by Piicksarn** [comment]
I think it's better that you separate the PR into two commits to make the task clear, for example :
 - ```minified ace.js of all versions in ace.js```
 - ```point ace.js to ace.min.js```

btw, wrong spelling in ``versions``

**Comment by maruilian11** [comment]
@Piicksarn but if i separate the PR, th first commit won't pass the npm test because it will tell me the filename didn't point to minfied file.

**Comment by PeterDaveHello** [comment]
I think `minify ace` is much easier ...

**Comment by maruilian11** [comment]
@Piicksarn could u help me check the pr again? thank u :")

**Comment by Piicksarn** [comment]
I think it's fine.
@PeterDaveHello, would you please take a look for it?

**Pull request merged**
