### PR TITLE
Add license of dd_belatedpng, cc #5500

### PR DESCRIPTION
**Pull request by NiniHsu**
http://www.dillerdesign.com/experiment/DD_belatedPNG/

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@NiniHsu any reason why to close this pull request?

**Comment by NiniHsu** [comment]
@PeterDaveHello  I pulled a wrong request.

**Comment by PeterDaveHello** [comment]
@NiniHsu Let's leave comment about the reason before you closed it next time.

**Comment by PeterDaveHello** [comment]
BTW, you "sent" a wrong "pull request", not "pulled" a wrong request.

**Comment by NiniHsu** [comment]
@PeterDaveHello Thanks for your reminder.
I will pay more attention to it next time.

**Pull request closed without merging**
