### PR TITLE
add json-formatter v0.6.0 with npm autoupdate config

### LINKED ISSUE #7594: [Request] JSON Formatter - (AnguarJS)
**Library name:** JSON Formatter
**Git repository url:** https://github.com/mohsen1/json-formatter
**npm package url(optional):** 
**License(s):** Apache 2.0
**Official homepage** https://github.com/mohsen1/json-formatter
**Wanna say something? Leave message here:** This is the AngularJS build, he has a pure JS build too.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #7594 
@dannyxx001 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/mohsen1/json-formatter
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/jsonformatter
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 216
   - Count of watchers: 15
   - Count of forks: 48
 * NPM download stats (optional):
   - Downloads in the last day: 32
   - Downloads in the last week: 1623
   - Downloads in the last month: 4411

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7594, cc @mohsen1

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Your files look not the same as v0.5.0 tagged, though the files in that tags also look strange about its version number and the last commit message ... 
https://github.com/mohsen1/json-formatter/tree/v0.5.0/dist

**Comment by mohsen1** [comment]
@pvnr0082t I published v0.6.0. Please double check

**Comment by pvnr0082t** [comment]
@dannyxx001 I have updated to v0.6.0. Please help me review again, thank you.

**Comment by dannyxx001** [comment]
@PeterDaveHello I think this PR is OK. Please review again, thanks.

**Comment by PeterDaveHello** [comment]
Any reason that you don't use npm auto-update here @pvnr0082t ?

https://github.com/mohsen1/json-formatter#usage

**Comment by pvnr0082t** [comment]
@PeterDaveHello I didn't find it on npm before, I think I missed.
@dannyxx001 I use npm autoupdate instead of git autoupdate. Please help me review again, thank you.

**Pull request merged**
