### PR TITLE
[New] Add poshytip@1.2 w/ git auto-update

### LINKED ISSUE #9388: [Request] Add Poshytip
**Library name:** Poshytip
**Git repository url:** https://github.com/vadikom/poshytip.git
**npm package url(optional):** 
**License(s):** GPL, MIT
**Official homepage:** http://vadikom.com/tools/poshy-tip-jquery-plugin-for-stylish-tooltips/
**Wanna say something? Leave message here:**  Part of the reason I'd like to see this is because you have `x-editable` (https://cdnjs.com/libraries/x-editable) in the library and that repo needs poshytip for part of it.  It'd be nice to pull them both from cdnjs.

I'll see if i can figure out how to add it myself as a PR.
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by sashberd**
close #9388, cc @vadikom, using koala tool for minifing css files

Pull request for issue: #9388
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/vadikom/poshytip
 * Official website (optional, not the repository): http://vadikom.com/tools/poshy-tip-jquery-plugin-for-stylish-tooltips/
 * NPM package url (optional):
 * License and its reference: MIT, GPL 2.0
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 14
   - Count of stars: 292
   - Count of forks: 75
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sashberd** [comment]
@sufuf3 The PR was updated by using web-minifing-tool. FYI

**Comment by sashberd** [comment]
@PeterDaveHello Yes,  it is my work git.. I already change its name to my regular one

**Comment by PeterDaveHello** [comment]
@sashberd so it's fine for you to use this identify or you'd like to modify it?

**Comment by sashberd** [comment]
It is ok

**Pull request merged**
