### PR TITLE
[new] CSS Spinning Spinners v1.1.0

### PR DESCRIPTION
**Pull request by BillyNate**

### CODE REVIEW

**Comment by BillyNate** [comment]
Contains eight equally important files, what should the filename mentioned in the package.json be?

**Comment by PeterDaveHello** [comment]
Missing field - filename, which will point to the main file.

**Comment by BillyNate** [comment]
I understood the missing field, that's why I said that all files are equally important. There is no main file.

So, just should I just set the first file as the main file to make it pass the test?

**Comment by PeterDaveHello** [comment]
Yeah, please.

**Comment by BillyNate** [comment]
Filename property added, check passed and commits squashed.

**Pull request merged**
