### PR TITLE
Add zuck.js@1.0.3 w/ npm auto-update

### LINKED ISSUE #11098: [Request] Add zuck.js
**Library name**: zuck.js
**Git repository url**: https://github.com/ramon82/zuck.js
**npm url**: https://www.npmjs.com/package/zuck.js
**License (List them all if it's multiple)**: MIT
**Official homepage**: https://ramon.codes/projects/zuck.js
**Wanna say something? Leave message here**: This library seems to be quite popular. However, not sure if this is considered as a personal project. Need feedback.

### PR DESCRIPTION
**Pull request by dakshshah96**
close #11098, cc @ramon82

Pull request for issue: #11098

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/ramon82/zuck.js
 * Official website (optional, not the repository): https://ramon.codes/projects/zuck.js/
 * NPM package url (optional): https://www.npmjs.com/package/zuck.js
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required): 
   - Count of watchers: 44
   - Count of stars: 1,981
   - Count of forks: 95
 * NPM download stats (optional):
   - Downloads in the last day: 2
   - Downloads in the last week: 66
   - Downloads in the last month: 66

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by dakshshah96** [comment]
@pvnr0082t So I should make a new file `zuck.min.css` and also keep `zuck.css` right?

**Comment by pvnr0082t** [comment]
correct. :+1:

**Comment by dakshshah96** [comment]
@pvnr0082t Done 👍

**Comment by pvnr0082t** [comment]
@dakshshah96 CI test failed. Please trigger CI again. Thanks.

**Comment by dakshshah96** [comment]
@pvnr0082t I can't understand the CI error:

```
fatal: unable to read tree d24e868d700e9c5916d36ad6139ae1e9da976610
```

**Comment by pvnr0082t** [comment]
@dakshshah96 It's fine. I think it's CI problem. Just try to trigger CI again. :+1:

**Comment by PeterDaveHello** [comment]
I'll take care of it.

**Comment by dakshshah96** [comment]
@pvnr0082t @PeterDaveHello Seems fine now 😄

**Comment by PeterDaveHello** [comment]
@dakshshah96 yes I tuned CI

**Comment by dakshshah96** [comment]
@PeterDaveHello @pvnr0082t Sorry for the trouble, I've updated the files.

**Comment by dakshshah96** [comment]
@PeterDaveHello So we can include all files inside `skins` folder also using something like this?

```
"files": [
          "zuck*",
          "skins/**/*"
        ]
```

**Comment by PeterDaveHello** [comment]
@dakshshah96 it's fine in this case :+1:

**Comment by dakshshah96** [comment]
@PeterDaveHello Done 👍

**Comment by ramon82** [comment]
Hi! I just updated zuck.js to v.1.0.4 on github and npm with all those missing minified files. Is there something that I could help from here? cc @dakshshah96

**Comment by PeterDaveHello** [comment]
@ramon82 thanks for that info, I think we are good here, once the missing files were added, I'll merge it.

**Comment by dakshshah96** [comment]
@PeterDaveHello I've added the `skins` folder and it's files along with their minified versions 👍

**Pull request merged**
