### PR TITLE
Add Lazy 3.1.160621

### PR DESCRIPTION
**Pull request by keicheng**
https://github.com/keicheng/kule.lazy/tree/v3.1.160612

### CODE REVIEW

**Comment by keicheng** [comment]
I no find any conflicts, what i need do something?

**Comment by PeterDaveHello** [comment]
I thought the bot did it earlier then this PR:　474deb25e011a5600c715cd2b7fe13143d3474b6

**Comment by keicheng** [comment]
Thanks! Can i delete old version?

**Comment by PeterDaveHello** [comment]
@keicheng Nope, we don't do that, this may break some websites using this lib.

**Comment by keicheng** [comment]
ok, thanks!

**Pull request closed without merging**
