### PR TITLE
[author] [new] Add txt.wav library@1.0.1 w/ npm autoupdate

### PR DESCRIPTION
**Pull request by georgetmayorga**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/still-life-studios/txt.wav
 * Official website (optional, not the repository): https://www.stilllife.studio/txtwav
 * NPM package url (optional): https://www.npmjs.com/package/txt.wav
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 508
   - Count of watchers: 11
   - Count of forks: 21
 * NPM download stats (optional):
   - Downloads in the last day: 1
   - Downloads in the last week: 22
   - Downloads in the last month: 22

# Essential checklist
 * [X] I'm the author of this library
   * [X] I would like to add link to the page of this library on CDNJS on website / readme
 * [X] This lib was not found on cdnjs repo
 * [X] No already exist / duplicated issue and PR
 * [X] The lib has notable popularity
   * [X] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [X] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by kennynaoh** [comment]
Hello @georgetmayorga ,
Please remove `main`, `files`, `scripts`, `bugs` field in `package.json`
Thanks!

**Comment by kennynaoh** [comment]
@georgetmayorga 
Please add `filename` (like this `js/txt.wav.min.js`)
Thanks!

**Comment by kennynaoh** [comment]
@georgetmayorga 
Please add nam auto-update in `package.json`.
```json
"npmName": "txt.wav",
"npmFileMap": [
{
      "basePath": "dist",
      "files": [
        "**/*"
      ]
}
]
```
Thanks!

**Comment by georgetmayorga** [comment]
Thanks so much for the help @kennynaoh , I believe I made the correct suggested changes

**Comment by georgetmayorga** [comment]
👍 thanks again, looks like all the tests passed! @kennynaoh

**Comment by pvnr0082t** [comment]
@georgetmayorga I think it will be better to commit `txt.wav.js` and `txt.wav.css` as well. Thank you.

**Comment by georgetmayorga** [comment]
@pvnr0082t do you mean in the package.json ? because they files are commited.

I think you mean:
```js
"filename": [
  "js/txt.wav.min.js",
  "css/txt.wav.min.css"
],
```
is this correct?

**Comment by PeterDaveHello** [comment]
@georgetmayorga you only added the minified file, let's also add the non-minified files!

**Comment by georgetmayorga** [comment]
thanks @PeterDaveHello, added 👍

**Comment by PeterDaveHello** [comment]
@georgetmayorga No problem.

**Comment by PeterDaveHello** [comment]
@georgetmayorga PR  merged! Thanks for your contribution!

**Pull request merged**
