### PR TITLE
add auto-update config & minified files in sco.js

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 , From #5195, I have add minified files in sco.js and point filename field to `scojs.min.css` in package.json.
repo : https://github.com/terebentina/sco.js
Would you mind checking this PR for me? Thank you~ :-)

- [ ] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `32`, Star `400`, Fork `95`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by maruilian11** [comment]
@Amomo don't we need `css/sco.message.min.css` in requiredFiles field?

**Comment by maruilian11** [comment]
i'm confuse about why its name is `sco.js`, but we point to `min.css`. do you know the reason?

**Comment by Amomo** [comment]
Actually...I have the same question as you.😂

I think that because sco.js has many js files, the one who first added sco.js in cdnjs couldn't pick a representative js file. Finally, He chose to point to the css file. I guess...

Oh! I forgot to add `css/sco.message.min.css`, thanks for your reminding~

**Comment by Amomo** [comment]
@maruilian11 I have corrected it and rebased!
Could you check this PR again? Thank you~ :-D

**Comment by maruilian11** [comment]
@Amomo may i ask you why you add `.min.js` for pre versions, but didn't add `.min.css` for them??

**Comment by Amomo** [comment]
@maruilian11  do you mean why I don't add `sco.message.min.css` in each version?
Because only v1.1.0 has it.

**Comment by maruilian11** [comment]
@Amomo oh, it's my bad, you do have done it. can you rebase it and tag me? thank you.

**Comment by Amomo** [comment]
@maruilian11 I have rebased this PR to match the latest master branch.
Could you take a look? Thank you! :-D

**Comment by maruilian11** [comment]
@Amomo sorry, but i seem not see any rebase commit ??

**Comment by Amomo** [comment]
oops, I forgot to push it. Sorry!
@maruilian11 Could you take a look again? Thank you! :-D

**Comment by maruilian11** [comment]
i still don't see any new commit... is my problem？ ˊ_>ˋ

**Comment by Amomo** [comment]
@maruilian11 I think f614ea2 and d216440 are latest commit...😧

**Comment by Amomo** [comment]
@maruilian11 I think it will be fine this time!
Could you take a look again? Thank you! :-D

**Comment by maruilian11** [comment]
@Amomo finally~ i can see it XD but seems that still need to rebase again.... 
btw, i think this PR is ok!

**Comment by PeterDaveHello** [comment]
What's the reason thy that `ajax/libs/sco.js/1.0.0/css/scojs.min.css` is empty?

**Comment by Amomo** [comment]
Sorry for the careless...
@maruilian11 Could you check my PR again? Thank you! :-)

**Comment by maruilian11** [comment]
@Amomo i think it's not good to add `scojs.min.css` in the second commit..
can you add it to the first one?

**Comment by Amomo** [comment]
Oh...I shouldn't add it there...😨 I have fixed it!
Additionally, I also add the license field in the new commit.
@maruilian11 could you check this PR again? Thank you very much!

**Comment by maruilian11** [comment]
@Amomo  i'm sorry, could you rebase again? thank you!!!

**Comment by Amomo** [comment]
@maruilian11 I have rebased it! Thank you~

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Pull request merged**
