### PR TITLE
[new] jScrollPane version 2.0.21

### PR DESCRIPTION
**Pull request by pavelsl**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Would you please also add auto-update config for it as #3638 said? Thanks.

**Comment by pavelsl** [comment]
Hi, hope i did everything right way.

**Comment by PeterDaveHello** [comment]
Because of the autoupdate config, should put the files into corresponding directory in this PR and also update its filename field.
And the commit's parent is too old, should rebase on the latest master branch.

**Comment by pavelsl** [comment]
Don't understand what you mean about corresponding directories. Should my project directories structure to be the same? script/jsfile style/cssfile? Is this wrong. 

Will do rebase, but don't understand the other point.

**Comment by PeterDaveHello** [comment]
You don't have that script/style directories in your PR:
`ajax/libs/jScrollPane/2.0.21/jquery.jscrollpane.min.css`
`ajax/libs/jScrollPane/2.0.21/jquery.jscrollpane.min.js`
But in the auto-update config, they should be the same.

**Comment by pavelsl** [comment]
Yep, i see now. I have created the same structure in my branch now, will upload in 10min. Thank You.

**Comment by pavelsl** [comment]
Heh, can't understand why repo management is so slow. I wait for ages each operation, git status or any other. Using Source Tree + Console itself.

**Comment by PeterDaveHello** [comment]
Try this:
https://github.com/cdnjs/cdnjs/blob/master/sparseCheckout.md

**Comment by pavelsl** [comment]
Hi, could you please create the same right commit by yourself anyhow. I realize that it shuld take time. 
I have spent a lot of time to do this by myself without a success. 

My machine is just hanging while i trying to do anything (any single operation as git status, have tried both source tree and git CLI), i can't rebase because a couple files a stucked in index, and i can't remove them or discard anything. Also after i have tried to use sparseCheckout, it was loading 300~mb and after that error was shown. 

So if you can't help here, please close this PR. Will really appreciate if you could. Thanks, anyway!

**Comment by PeterDaveHello** [comment]
New version added in https://github.com/cdnjs/cdnjs/commit/74272a4117c00221d407d1de8183d0a976616891

**Comment by pavelsl** [comment]
Hi, Thank You very much!!! You did a great job.

**Pull request closed without merging**
