### PR TITLE
Add ssi-modal w/ npm auto-update

### LINKED ISSUE #8541: [Request] Add ssi-modal
Library name: ssi-modal
Git repository url: [https://github.com/ssbeefeater/ssi-modal](https://github.com/ssbeefeater/ssi-modal)
npm package url: [https://www.npmjs.com/package/ssi-modal](https://www.npmjs.com/package/ssi-modal)
License(s): MIT
Official homepage: [http://ssbeefeater.github.io/](http://ssbeefeater.github.io/)

### PR DESCRIPTION
**Pull request by x09326**
PR for #8541 
@kennynaoh @pvnr0082t Please help me review it.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/ssbeefeater/ssi-modal/tree/master
 * Official website (optional, not the repository):https://ssbeefeater.github.io/
 * NPM package url (optional):https://www.npmjs.com/package/ssi-modal
 * GitHub / Bitbucket popularity (required):
   - Count of stars:1
   - Count of watchers:1
   - Count of forks:0
 * NPM download stats (optional):
   - Downloads in the last day:0
   - Downloads in the last week:32
   - Downloads in the last month:233

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8541, cc @ssbeefeater

### CODE REVIEW

**Comment by kennynaoh** [comment]
@x09326 
I think the file structure in `v1.0.1`~`v1.0.3` can be the same as other versions on npm.
And I think it should also add `images/` in `v1.0.0`.
Thanks!

**Comment by x09326** [comment]
@kennynaoh 
I have added ```images```.
But I couldn't get you about the file structure.
Other versions don't have ```dist``` or ```src``` folder.

**Comment by x09326** [comment]
@kennynaoh 
I have fixed them all.
Please help me review it.

**Comment by pvnr0082t** [comment]
@x09326 It seems like there has some problem of CI. Please try to push again to trigger circleCI. Thanks

**Comment by x09326** [comment]
@pvnr0082t 
done.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM

**Comment by kennynaoh** [comment]
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@x09326 please also mention the reason you manually add other versions in PR "comment", thanks

**Pull request merged**
