### PR TITLE
add more detail about bootstrap-slider's package.json

### PR DESCRIPTION
**Pull request by LeaYeh**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
hmmmmm ... actually we don't need so **more**, let's add the info meaningful in our repo!

**Comment by LeaYeh** [comment]
fixed it.

**Comment by PeterDaveHello** [comment]
Would you please remove `scripts` and fill in `author` field? `readmeFilename` should also be removed, thanks.

**Comment by LeaYeh** [comment]
check

**Comment by PeterDaveHello** [comment]
You should not remove `npmName` field as our npm auto-update needs it.

**Comment by LeaYeh** [comment]
done.

**Comment by PeterDaveHello** [comment]
Seems you remove the old one and add a new one, what about just not to touch it? And also `homepage` field. Thanks.

**Comment by LeaYeh** [comment]
check it again ><"

**Pull request merged**
