### PR TITLE
[author] Add oppia@0.0.2

### PR DESCRIPTION
**Pull request by seanlip**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

NB: the source of the added file is https://github.com/oppia/oppia/blob/develop/assets/scripts/oppia-player-0.0.2.min.js

# Profile of the lib
 * Git repository (required): https://github.com/oppia/oppia/
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 170
   - Count of watchers: 95
   - Count of forks: 253

# Essential checklist
 * [x] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@seanlip thanks for your PR, I found that there are some versions like v2.3.2 v2.3.3, should we also add them? I also wonder if we could setup auto-update config for this lib so that we can easily add the new versions, what do you think?

**Comment by seanlip** [comment]
Hi @PeterDaveHello, there are actually two things in the oppia repository: the main release (which has version numbers like v2.3.2 etc.) and the embed script (for which only version numbers 0.0.1 and 0.0.2 are supported). It's the second of these that's been updated here.

Also, thanks for the suggestion on auto-update. I considered doing this, but since we update the embedding script pretty infrequently, and the version numbering isn't the same, I think it's probably better to stick to manual updates for the time being.

Thanks!

**Comment by PeterDaveHello** [comment]
@seanlip thanks for your comment, I'll still like to have auto-update if it's possible.

**Comment by seanlip** [comment]
Thanks! It'll be a bit tricky to handle, I think (due to the version number differences), but I'll look into it and see if it's possible. I agree auto-update would be nice.

**Comment by PeterDaveHello** [comment]
@seanlip Thanks.

**Pull request merged**
