### PR TITLE
Upgrade mermaid to 8.2.3

### PR DESCRIPTION
**Pull request by jackycute**
# Pull request template for new library

Pull request for issue: #13416 
Related issue(s): #13416 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

## Profile of the lib

* Git repository (required): https://github.com/knsv/mermaid
* Official website (optional, not the repository): http://knsv.github.io/mermaid/#/
* NPM package url (optional): https://www.npmjs.com/package/mermaid
* License and its reference: https://github.com/knsv/mermaid/blob/master/LICENSE
* GitHub / Bitbucket popularity (required):
  * Count of watchers: 518
  * Count of stars: 24240
  * Count of forks: 1466
* NPM download stats (optional):
  * Downloads in the last day:
  * Downloads in the last week:
  * Downloads in the last month:

## Essential checklist

* [ ] I'm the author of this library
  * [ ] I would like to add link to the page of this library on CDNJS on website / readme
* [ ] This lib was not found on cdnjs repo
* [ ] Doesn't already exist / has duplicate issue and PR
* [x] The lib has notable popularity
  * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [x] More than 800 downloads stats per month on npm registry
* [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [ ] Has valid tags for each versions (for git auto-update)
* [ ] Auto-update setup
* [ ] Auto-update target/source is valid.
* [ ] Auto-update filemap is correct.

## Git commit checklist

* [ ] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [ ] The parent of the commit(s) in the PR is not older than 3 days.
* [ ] Pull request is sent from a non-master branch with a meaningful name.
* [ ] Separate unrelated changes into different commits.
* [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [ ] Close corresponding issue in commit message
* [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by jackycute** [comment]
```
 ✗  
   
   
    mermaid 
      ✗ mermaid: filename from package.json exists and is a file (not a directory) 
        » ./ajax/libs/mermaid/8.2.3/mermaid.min.js does not exist but is referenced in package.json! // macros.js:27 
  ✗ Broken » 29 honored ∙ 1 broken (0.014s) 
```

Hmm, seems it couldn't pass the CI, but it should install the file `mermaid.min.js`.

**Comment by MattIPv4** [comment]
@jackycute You'll need to manually provide the files for 8.2.3

**Comment by PeterDaveHello** [comment]
@jackycute the assets also need to be added in the commit, only change the version won't update it.

**Comment by jackycute** [comment]
got it, thanks @MattIPv4 and @PeterDaveHello 
since this has been added, I will just close this PR.

**Comment by PeterDaveHello** [comment]
@jackycute thank you, too!

**Pull request closed without merging**
