### PR TITLE
Add aurelia@1.0.2 w/ git auto-update

### LINKED ISSUE #9166: [Request] Add Aurelia
**Official homepage:** http://aurelia.io/

**Library name:** Aurelia framework
**Git repository url:** https://github.com/aurelia/framework
**npm package url(optional):** https://www.npmjs.com/package/aurelia-framework

**Library name:** Aurelia bootstrapper
**Git repository url:** https://github.com/aurelia/bootstrapper
**npm package url(optional):** https://www.npmjs.com/package/aurelia-bootstrapper

**Library name:** Aurelia bootstrapper
**Git repository url:** https://github.com/aurelia/bootstrapper-webpack
**npm package url(optional):** https://www.npmjs.com/package/aurelia-bootstrapper-webpack

### PR DESCRIPTION
**Pull request by dakshshah96**
close #9166, cc @paolocarrasco

Pull request for issue: #9166 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/aurelia/aurelia
 * Official website (optional, not the repository): http://www.aurelia.io/
 * NPM package url (optional): 
 * License and its reference: MIT

**Note:** Even though the repository we've used here is [this](https://github.com/aurelia/aurelia), these are actually the CDN files for [aurelia framework](https://github.com/aurelia/framework), so I'll be writing popularity stats for this [repo](https://github.com/aurelia/framework) and [npm package](https://www.npmjs.com/package/aurelia-framework) since that's the one whose popularity we should be checking.

 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 508
   - Count of stars: 9,581
   - Count of forks: 546
 * NPM download stats (optional):
   - Downloads in the last day: 1,051
   - Downloads in the last week: 5,277
   - Downloads in the last month: 24,727

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by paolocarrasco** [comment]
Sorry. I thought it was already in CDNJS.

**Comment by extend1994** [comment]
Hi @paolocarrasco Could you please provide the information about the existence of the the library you found? I enter "aurelia" in https://cdnjs.com and find nothing so I think it should not be on CDNJS now. Thanks :)

**Comment by paolocarrasco** [comment]
Hi @extend1994 
The library can't be found on cdnjs yet, that's the reason of this pull request. The library is the core of the Aurelia framework (http://aurelia.io/), sometimes regarded as a better alternative to Angular. Check
- https://www.pluralsight.com/blog/software-development/angular-2-vs-aurelia
- https://medium.com/@ZombieCodeKill/choosing-a-javascript-framework-535745d0ab90
If you want more information about the downloads:
http://www.npmtrends.com/aurelia-framework

**Comment by sufuf3** [comment]
@dakshshah96 sorry, I rereview again and found that maybe we still host `config-typescript.js` and `system.js`, because the tutorial teach me need to add these files from here http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/quick-start/2 and https://github.com/aurelia/framework/blob/master/doc/article/en-US/quick-start.md#the-indexhtml-page

Could you please help me confirm it again? I not familiar with this.
Thank you.

**Comment by paolocarrasco** [comment]
@sufuf3 `system.js` can be found already in cdnjs. The file `config-typescript.js` is a file that should be built based on your needs, according to the System.js specs (https://github.com/systemjs/systemjs/blob/master/docs/config-api.md). Following the quick start guide, you should download first the Basic Aurelia project setup. If you want another approach, you can use the [aurelia-cli.](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/the-aurelia-cli)

**Comment by sufuf3** [comment]
@paolocarrasco Thank you for your detail explain, then we just host `aurelia*.js`. 👍

**Comment by paolocarrasco** [comment]
Hi @sufuf3 @extend1994 ... I think this pull request was forgotten :cry: could you help us to perform the merge?

**Comment by dakshshah96** [comment]
@paolocarrasco Sorry about that.

@extend1994 @hare1039 @clairetsai818 Please review this PR.

**Comment by hare1039** [comment]
@dakshshah96 Should I rebase this PR now or you want to rebase it?

**Comment by dakshshah96** [comment]
Hey @hare1039, I'm new to this so can you tell me how to work on a contributor's PR? Sorry for the off-topic conversation.

**Comment by hare1039** [comment]
You can push more commits by pushing to the branch on contributor's PR.

For example, if I want to edit sufuf3's PR 
First add the remote repo: `git add remote sufuf3-fork git@github.com:sufuf3/cdnjs.git`
Than fetch down the branch: `git fetch sufuf3-fork branch:branch`
Than checkout to the branch and made some commits
Finally push the branch back: `git push sufuf3-fork branch` // might need `-f` here

Basic step are these. Please correct me if I am wrong.

**Comment by sufuf3** [comment]
@cdnjs/library-reviewer 
Please help review this PR, Thank you.

**Pull request merged**
