### PR TITLE
Added stampit@2.0.3

### PR DESCRIPTION
**Pull request by ericelliott**
Auto update

### CODE REVIEW

**Comment by nkbt** [comment]
> cdnjs/cdnjs#4778 this one is correct. Until you publish npm, tool cannot pick correct package.json. I made changes manually, so the submission is valid.

You could either update this one with correct package.json and build libs or close.

**Comment by PeterDaveHello** [comment]
@ericelliott Would you please update this PR so that I can merge it? Thanks.

**Comment by nkbt** [comment]
@PeterDaveHello this one is already fixed by #4778 
We just did the same thing with @ericelliott

**Comment by PeterDaveHello** [comment]
Ah, okay, let's close this.

**Pull request closed without merging**
