### PR TITLE
add gmaps.js version 0.4.17

### PR DESCRIPTION
**Pull request by threadhead**
update gmaps.js to version 0.4.17 https://github.com/hpneo/gmaps

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Would you please also add git auto-update config for it as #3638 said?
And I think we should not touch its repo url in the same commit, thanks!

**Comment by PeterDaveHello** [comment]
BTW, I noticed that there is no minified file under its repo, but it's still okay to add git auto-update for it!

**Comment by drewfreyling** [comment]
Looks like the `lib` folder will be removed once https://github.com/hpneo/gmaps/issues/404 is fixed. So I'll leave this here until NPM support is added.

**Comment by PeterDaveHello** [comment]
And we have conflicts here, need to rebase with our latest master branch.

**Comment by drewfreyling** [comment]
Closing due to no response.

**Pull request closed without merging**
