### PR TITLE
add optimal-select v3.2.0 with npm auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/Autarc/optimal-select
**Watch 3
  Star 11
 Fork 4**
@Amomo could u help me check this PR for #8066 ? thank you!

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR 
 * [ ] The lib has notable popularity https://github.com/cdnjs/cdnjs/issues/8066#issuecomment-225406438
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry 
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update) 
https://github.com/Autarc/optimal-select/issues/11
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Is there a problem with its npm package?

**Comment by maruilian11** [comment]
yes, as i mentioned in comment (https://github.com/Autarc/optimal-select/issues/11),
it doesn't has a `dist` in npm package.
sorry i forgot to mention this.

**Comment by maruilian11** [comment]
@Amomo i have updated the version to v3.2.0, and the author has added `dist` to npm package, could you help me check this PR again? thanks!
https://github.com/Autarc/optimal-select/issues/11

**Comment by Amomo** [comment]
@maruilian11 sorry for late.
I think this PR is ok, could you rebase it on our latest master branch?
Thank you!

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is ok, could you check it again?  Thanks.

**Pull request merged**
