### PR TITLE
add SuperScrollorama v1.0.3

### LINKED ISSUE #5924: [Request] Add superscrollorama
**Library name: superscrollorama** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/johnpolacek/superscrollorama
**Watch 129
  Star 2,221
 Fork 548**
@Piicksarn could you help me check out the PR for #5924 ? thank you~
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by Piicksarn** [comment]
@maruilian11, i think it's fine, but need rebase to the master!
thank you!

**Comment by maruilian11** [comment]
@Piicksarn could you help me check the PR again? thank you :smiley:

**Comment by Piicksarn** [comment]
ok~
@PeterDaveHello, would you please have a look at the pr?
Thank you!

**Comment by PeterDaveHello** [comment]
I don't think we need this sentence in the commit message:
"although SuperScrollama is not going to upgrade, we still want to add this lib for people still using it."

Meaningless here, cdnjs doesn't decide whatever to add a lib by if it'll update in future.

**Comment by maruilian11** [comment]
@PeterDaveHello i have removed it.

**Pull request merged**
