### PR TITLE
add Allofthelights.js v2.0 with autoupdate config

### LINKED ISSUE #7727: [Request] Add Allofthelights.js
**Library name:** Allofthelights.js
**Git repository url:** https://github.com/Pierrinho/Allofthelights.js
**npm package url (optional):** (none)
**License(s):** (none)
**Official homepage:** http://www.megaptery.com/allofthelights/

### PR DESCRIPTION
**Pull request by dannyxx001**
PR for #7727 
@pvnr0082t please help me review this PR, thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/Pierrinho/Allofthelights.js
 * Official website (optional, not the repository): http://www.megaptery.com/allofthelights/
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 100
   - Count of watchers: 7
   - Count of forks: 23
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7727, cc @Pierrinho

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@dannyxx001 The minified file v2.0 tagged does not exist . Did you minified yourself? It seems that you grab it from master branch.

**Comment by dannyxx001** [comment]
@pvnr0082t Yeah, because I use "diff" command. The js version is the same, so I think the minifed file is OK.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
It's easy to know the src file on master and v2.0 are the same since they stay on the same commit.

**Pull request merged**
