### PR TITLE
add mobile-angular-ui@1.2.1 w/ npm auto update

### PR DESCRIPTION
**Pull request by onlineth**
Close https://github.com/cdnjs/cdnjs/issues/8404
cc @mcasimir
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/mcasimir/mobile-angular-ui.git
 * Official website (optional, not the repository): http://mobileangularui.com/
 * NPM package url (optional): https://www.npmjs.com/package/mobile-angular-ui
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 2549
   - Count of watchers: 255
   - Count of forks: 668
 * NPM download stats (optional):
   - Downloads in the last day: 2
   - Downloads in the last week: 11
   - Downloads in the last month: 88

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@onlineth Thanks for your PR, let's add some keywords:
https://github.com/mcasimir/mobile-angular-ui/blob/master/bower.json#L19-L25

It's always good to add some keywords even there is no keyword from upstream!

**Comment by PeterDaveHello** [comment]
3 things in the commit message:

1. Please also mention the auto-update in the first line of the commit message
2. Since this PR has a related issue and after this PR the issue will not exist any more, please add a syntax to close the origin issue like: `close #8404`
3. Please also mention the author in the commit message like `cc @PeterDaveHello` so that the author will know that his or her lib is now available on CDNJS.

Thanks!

Ref:
https://help.github.com/articles/closing-issues-via-commit-messages/
https://github.com/blog/1386-closing-issues-via-commit-messages

**Comment by onlineth** [comment]
@PeterDaveHello ok, I've added the keywords. I'll also be sure to add the "w/ [type] autoupdate" in the commit message in the future. I'll also edit the PR request to include "close \#8404" and add cc @[author] now.

**Comment by PeterDaveHello** [comment]
@onlineth is it possible to work locally for you? Instead of on GitHub, since the commits should be squash, or the commit message will be not so meaningful, though I can still do it for you online, so just asking.

**Comment by PeterDaveHello** [comment]
Ping.

**Pull request closed without merging**
