### PR TITLE
Added spa.js@1.0.7

### PR DESCRIPTION
**Pull request by zhaoda**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Anything wrong here?

**Comment by zhaoda** [comment]
一直没有提交成功到cdnjs

**Comment by PeterDaveHello** [comment]
Should pass the test!

**Comment by zhaoda** [comment]
等我再试试吧，cdnjs仓库太大，每次操作都卡的要死

**Comment by PeterDaveHello** [comment]
Try [sparse-checkout](https://github.com/cdnjs/cdnjs/blob/master/sparseCheckout.md)

**Comment by zhaoda** [comment]
ok,try later.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern please help @zhaoda to submit this lib.

**Pull request closed without merging**
