### PR TITLE
add checkbox.css w/ npm autoupdate 

### LINKED ISSUE #8194: [Request] Add Checkbox.css
**Library name:**  Checkbox.css
**Git repository url:** https://github.com/720kb/checkbox.css

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8194 
@x09326 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/720kb/checkbox.css
 * Official website (optional, not the repository): https://720kb.github.io/checkbox.css
 * NPM package url (optional): https://www.npmjs.com/package/checkbox.css
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 300
   - Count of watchers: 14
   - Count of forks: 25
 * NPM download stats (optional):
   - Downloads in the last day: 0
   - Downloads in the last week: 16
   - Downloads in the last month: 93

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8194, cc @45kb

### CODE REVIEW

**Comment by x09326** [comment]
@pvnr0082t 
Sorry for the late response.
Please rebase it.

**Comment by pvnr0082t** [comment]
@x09326 I have rebased it. Please help me review again, thank you.

**Comment by x09326** [comment]
@PeterDaveHello 
I think this PR is okay, please help me review it, thanks.

**Comment by PeterDaveHello** [comment]
I didn't see the reason why you need to manually commit the old versions, at least you put them on their css folders.

**Comment by pvnr0082t** [comment]
Maybe I don't manually add that. I have fixed the auto-update config. @x09326 Please help me review again, thank you.

**Comment by PeterDaveHello** [comment]
@pvnr0082t let's add it with the new structure so that we can keep the consistency between different versions, thanks.

**Comment by pvnr0082t** [comment]
@x09326 I have added old versions with the new structure. Please help me review again, thank you.

**Pull request merged**
