### PR TITLE
Add reactive-coffee 1.2.4

### PR DESCRIPTION
**Pull request by yang**
Thanks again!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Should fix your commit first.

**Comment by PeterDaveHello** [comment]
Commit's parent was tooooooooooooo old, please read our document for what you need to send a valid PR, thanks.

**Comment by Amomo** [comment]
Hi @yang 

The build seems failed before the test start.
Please rebase your commit to match our latest master branch.
And resend the commit again. Thank you! :-)

**Comment by PeterDaveHello** [comment]
@Amomo what,does match mean?

**Comment by Amomo** [comment]
Umm...I mean please make your commit `ahead` cdnjs' latest commit.
The old commits in your branch should match (as same as) cdnjs' master branch.

**Comment by PeterDaveHello** [comment]
If there is no response for next 7 days, @Piicksarn please take it.

**Pull request closed without merging**
