### PR TITLE
angular-linq

### PR DESCRIPTION
**Pull request by angularPublic**

### CODE REVIEW

**Comment by rajkumarAngular** [comment]
please merge to cdnjs.

**Comment by PeterDaveHello** [comment]
Please read our document for what you need to send  a PR first, thanks.

**Comment by drewfreyling** [comment]
@angularPublic can you please squash these commits into one?

**Comment by PeterDaveHello** [comment]
And need rebase with latest master.

**Comment by drewfreyling** [comment]
Closed due to no response.

**Pull request closed without merging**
