### PR TITLE
add vue-i18n@4.0.1 w/ npm autoupdate

### LINKED ISSUE #7894: [Request] Add vue-i18n
**Library name:** vue-i18n
**Git repository url:** https://github.com/kazupon/vue-i18n
**npm package url(optional):** https://www.npmjs.com/package/vue-i18n
**License(s):**MIT
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #7894 
@kennynaoh Please help me review this pull request, thank you.
Here is an [issue](https://github.com/kazupon/vue-i18n/issues/34) discuss with author about files to get in dist folder.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/kazupon/vue-i18n
 * Official website (optional, not the repository): 
 * NPM package url (optional): https://www.npmjs.com/package/vue-i18n
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 216
   - Count of watchers: 17
   - Count of forks: 10
 * NPM download stats (optional):
   - Downloads in the last day: 50
   - Downloads in the last week: 715
   - Downloads in the last month: 2712

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7894, cc @kazupon

### CODE REVIEW

**Comment by kennynaoh** [comment]
@pvnr0082t 
Sorry for late review, please rebase to the latest master branch.

**Comment by pvnr0082t** [comment]
@kennynaoh I have rebased on the latest master branch. Please help me review again, thank you.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Comment by PeterDaveHello** [comment]
What's the reason why to drop `vue-i18n.common.js`? You didn't mention any reason.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think the [issue](https://github.com/kazupon/vue-i18n/issues/34) author talked about is the reason.
Please help me take a look again.
Thanks!

**Comment by PeterDaveHello** [comment]
I didn't see any comment to mention the reason.

**Comment by pvnr0082t** [comment]
@PeterDaveHello Author said that there is `vue-i18n.min.js` as minified file. I asked if `vue-i18n.common.js` don't need to be added. I think the reply by author is yes but I don't know the real reason.

**Comment by PeterDaveHello** [comment]
@pvnr0082t You asked about the minified common file, not the origin one. Anyway, please confirm that, I did not see a reason of not hosting it, since it's in dist folder, it's odd not to host it.

**Comment by pvnr0082t** [comment]
@kennynaoh I have confirm with author again https://github.com/kazupon/vue-i18n/issues/34. And the latest version is v4.0.1. Please help me review again, thank you.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Comment by PeterDaveHello** [comment]
What's the reqason why not to minify `vue-i18n.common.js`? @pvnr0082t @kennynaoh

**Comment by kennynaoh** [comment]
I thought the author had said that we don't need to minify `vue-i18n.common.js`, didn't it?
Actually, I am not pretty sure.

**Comment by PeterDaveHello** [comment]
@kennynaoh We should minify it.

**Comment by pvnr0082t** [comment]
@kennynaoh I have minified `vue-i18n.common.js`. Please help me review again, thank you.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Comment by PeterDaveHello** [comment]
@pvnr0082t @kennynaoh please use a shorter title/first line commit next time, I'll modify the commit this time.

**Pull request merged**
