### PR TITLE
Add lg-video@1.0.2 w/ git auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
**It's a sub-lib of popular lib(lightGallery).**
@cdnjs/library-reviewer Please help me check this PR, thanks!

Pull request for issue: #9087

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/sachinchoolur/lg-video
 * Official website (optional, not the repository): https://sachinchoolur.github.io/lightGallery/
 * NPM package url (optional): https://www.npmjs.com/package/lg-video
 * License and its reference: GPL-3.0, https://github.com/sachinchoolur/lg-video/blob/master/LICENSE.md
 * GitHub / Bitbucket popularity (required):
   Watch 1
   Star 0
   Fork 1
 * NPM download stats (optional):
   9 downloads in the last day
   80 downloads in the last week
   418 downloads in the last month

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity **It's a sub-lib of popular lib(lightGallery).**
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@extend1994 you should request review from me after as there are two approvals without rejections.

**Comment by extend1994** [comment]
@PeterDaveHello Yes I know, I planned to request your review after rebasing the branches. But I couldn't rebase the branch a few days ago. I am sorry for that! Now I rebase it and wait for the license confirmation.

**Comment by PeterDaveHello** [comment]
As my review 2 days ago: https://github.com/cdnjs/cdnjs/pull/11404#pullrequestreview-45887690, in this case, I don't think you should rebased the branch but check the license first, am I right?

@sufuf3 @maruilian11 didn't you guys either see the review ?

**Comment by PeterDaveHello** [comment]
And @sufuf3, didn't you have any further movement on that review?

**Comment by sufuf3** [comment]
@maruilian11 sent the issue(sachinchoolur/lg-video#1) try to discuss the author two days ago, after https://github.com/cdnjs/cdnjs/pull/11404#pullrequestreview-45887690.
Waiting for response.

**Comment by extend1994** [comment]
@PeterDaveHello You are right, and I saw your comments in all other sub-library, to avoid bothering you again and again. Just reply you here. It was my negligence, so sorry again... :disappointed:

**Comment by PeterDaveHello** [comment]
@extend1994 no worries, just a reminder, to make sure we can do better next time.

**Comment by extend1994** [comment]
@PeterDaveHello Will be more careful next time!

**Comment by extend1994** [comment]
The license GPLv3 is confirmed according to the author.

**Pull request merged**
