### PR TITLE
Updating ekko-lightbox package.json

### PR DESCRIPTION
**Pull request by ashleydw**
Modified package.json for ekko-lightbox to latest version for autoupdate but left version as 3.0.3a (current is 3.2.2) so that auto-update can do its thing.

This time with correct tab spacing.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hmmmm ... I think you are still touching the indent xDDDD, there should be spaces before values, and I think the homepage url is correct, but you changed to its repo url, in this case, the less diff we have, the better PR it is, so please update it again, thank you.

**Comment by PeterDaveHello** [comment]
Oh, I noticed that you are the author, so that I think you can decide which one is its homepage url, ha.

**Comment by ashleydw** [comment]
Hm. For me, the spacing is spaces? Two spaces per indent (as per github editor). Do you see tabs, or?

And yes, I would prefer the homepage to be the main repo page :)

**Comment by PeterDaveHello** [comment]
Okay, fine, I'll merge it now.

**Comment by PeterDaveHello** [comment]
BTW, you can see the diff in 146b183.

**Comment by ashleydw** [comment]
Oh the spacing after the semi-colons. I see now. Thanks

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by ashleydw** [comment]
I updated my package on npm about 6 hours ago, but the change hasn't been detected from this. Newest version is v3.3.0. Any ideas a why?

https://github.com/ashleydw/lightbox/releases
https://www.npmjs.com/package/ekko-lightbox

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs#enabling-npm-auto-update
> because many libs will change the naming or directory structure during different versions, and we may need to minify the lib without pre-minified dist files, so it'll be reasonable to delay for at most **30** hours, if you think there is a lib didn't been updated, please wait at least **30** hours for the process to audit it.

**Comment by PeterDaveHello** [comment]
* b7cec41 add ekko-lightbox v3.3.0 Peter Dave Hello 47 minutes ago

**Pull request merged**
