### PR TITLE
add currencyformatter.js@1.0.4 w/ npm auto-update

### LINKED ISSUE #9210: [Request] Add currencyformatter.js
**Library name:** currencyformatter.js
**Git repository url:** https://github.com/osrec/currencyFormatter.js
**npm package url(optional):**  currencyformatter.js
**License(s):** MIT
**Official homepage:** https://osrec.github.io/currencyFormatter.js/

### PR DESCRIPTION
**Pull request by nolsherry**
@kennynaoh, please help me review this PR, thanks! 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/osrec/currencyFormatter.js
- Official website (optional, not the repository): https://osrec.github.io/currencyFormatter.js/
- NPM package url (optional): https://www.npmjs.com/package/currencyformatter.js
- GitHub / Bitbucket popularity (required):
  - Count of stars: 289
  - Count of watchers: 13
  - Count of forks: 15
- NPM download stats (optional):
  - Downloads in the last day: 1
  - Downloads in the last week: 14
  - Downloads in the last month: 58
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [X] This lib was not found on cdnjs repo
- [X] No already exist / duplicated issue and PR
- [X] The lib has notable popularity
  - [X] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [X] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [X] Has valid tags for each versions (for git auto-update)
- [X] Auto-update setup
- [X] Auto-update target/source is valid.
- [X] Auto-update filemap is correct.
# Git commit checklist
- [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [X] The parent of the commit(s) in the PR is not old than 3 days.
- [X] Pull request is sending from a non-master branch with meaningful name.
- [X] Separate unrelated changes into different commits.
- [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [X] Close corresponding issue in commit message
- [X] Mention related issue(s), people in commit message, comment.

close #9210, cc @osrec

### CODE REVIEW

**Comment by kennynaoh** [comment]
@nolsherry 
The latest version on git repo is `v1.0.4`.
Please confirm with author whether he/she can published the latest version on npm.
Thanks!

**Comment by nolsherry** [comment]
@kennynaoh, OK, I will confirm with the author.

**Comment by osrec** [comment]
Latest version published to npm :)

**Comment by PeterDaveHello** [comment]
@osrec Thanks

**Comment by nolsherry** [comment]
@kennynaoh , I have updated to the latest version `v1.0.4`, please help me review this PR, thanks!

**Comment by nolsherry** [comment]
@kennynaoh , the author has updated all versions to npm, please try to download the repo from npm, thanks!

**Comment by kennynaoh** [comment]
@nolsherry 
Right, there are just two versions on `npmcdn.com`, but there are all versions on `npmjs.com`.
Sorry about that.

**Comment by kennynaoh** [comment]
LGTM
ping @PeterDaveHello

**Pull request merged**
