### PR TITLE
New version of the Shepherd js library added

### PR DESCRIPTION
**Pull request by cristiancporto**
Added the 2.8.0 version of the Shepherd library

* Git repository (required): https://github.com/shipshapecode/shepherd
* Official website (optional, not the repository): https://shipshapecode.github.io/shepherd/docs/welcome/
* NPM package url (optional): https://www.npmjs.com/package/shepherd.js

### CODE REVIEW

**Comment by cristiancporto** [comment]
I was trying to use the shepherd library but the latest version available on cdnjs is old, so I decided to upload the last version. Shoul I include the intermediate versions too?

**Comment by rwwagner90** [comment]
This is already quite outdated. We just released version 4.1.0 and it would be great to get the modern versions in!

**Comment by rwwagner90** [comment]
@PeterDaveHello could we get this in please and/or update to the latest version, then get it in?

**Comment by PeterDaveHello** [comment]
> I was trying to use the shepherd library but the latest version available on cdnjs is old, so I decided to upload the last version. Shoul I include the intermediate versions too?

I think you can try to update the auto-update config in its `package.json` so they'll be handled, would you?

**Comment by rwwagner90** [comment]
@PeterDaveHello this wasn't my PR, but I am the maintainer of Shepherd. The auto update thing you mentioned sounds great! How can we do that?

**Comment by PeterDaveHello** [comment]
@rwwagner90 I assume the files should be hosted have a pattern in the directory/filename structure?
We have a short doc for auto-update you may want to have a look first: https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

**Comment by rwwagner90** [comment]
@PeterDaveHello yes, it should just be the npm release contents always.

**Comment by rwwagner90** [comment]
@MattIPv4 not sure how to do that. Certainly open to it. We have published versions on npm of course, so please let me know what you need.

**Comment by MattIPv4** [comment]
Ah shoot, I gave you half a macro response.

If you take a look in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents, you'll be able to see more about how auto-update configs work.

Equally, for some live examples, take a look through some of our recently merged PRs: https://github.com/cdnjs/cdnjs/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Amerged

**Comment by rwwagner90** [comment]
@MattIPv4 Is there any chance you could open a PR for me? Happy to provide the necessary info. I cannot even download this repo to contribute because it's like 10 gigs or more and all my git processes use over 100% of my cpu trying to sync it.

**Comment by MattIPv4** [comment]
@rwwagner90 if there isn't already an issue in this repo for updating this lib, please create obe. I'm slowly working through all issues (oldest to newest) and creating PRs for them.

**Comment by rwwagner90** [comment]
@MattIPv4 I created a new issue and I tried to add the package.json too it. Not sure if it is 100% correct or not, but hopefully it helps! https://github.com/cdnjs/cdnjs/issues/13902

**Pull request closed without merging**
