### PR TITLE
add missing license of bean

### PR DESCRIPTION
**Pull request by a1090200**
#6324
[License](https://github.com/fat/bean/blob/master/LICENSE).
Adding missing license of bean.

### CODE REVIEW

**Comment by Amomo** [comment]
Hi @a1090200 , the title of your PR is not clearly.
Could you modify your PR titte?

**Comment by a1090200** [comment]
Sure.Is it ok to change the title to "adding missing license of bean"?

**Comment by Amomo** [comment]
@a1090200 please start with "add".

**Comment by Amomo** [comment]
@a1090200 could you fix your commit message also?  make it start with "add".

**Comment by PeterDaveHello** [comment]
The problem is we can not recognized the lib been updated in the first line of the commit message.

**Pull request closed without merging**
