### PR TITLE
Update es6-tween auto-update config in package.json

### PR DESCRIPTION
**Pull request by dalisoft**
# Pull request template for new library

Pull request for issue: #13359 
Related issue(s): #10998

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

## Profile of the lib

* Git repository (required): https://github.com/tweenjs/es6-tween.git
* Official website (optional, not the repository): https://es6-tween.js.org/
* NPM package url (optional): https://www.npmjs.com/package/es6-tween
* License and its reference: [MIT License](https://github.com/tweenjs/es6-tween/blob/master/LICENSE)
* GitHub / Bitbucket popularity (required): https://github.com/tweenjs/es6-tween
  * Count of watchers: 8
  * Count of stars: 123
  * Count of forks: 26
* NPM download stats (optional):
  * Downloads in the last day: ~350
  * Downloads in the last week: 2 241
  * Downloads in the last month: ~9000

## Essential checklist

* [x] I'm the author of this library
  * [ ] I would like to add link to the page of this library on CDNJS on website / readme
* [ ] This lib was not found on cdnjs repo
* [ ] Doesn't already exist / has duplicate issue and PR
* [ ] The lib has notable popularity
  * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [x] More than 800 downloads stats per month on npm registry
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [x] Has valid tags for each versions (for git auto-update)
* [x] Auto-update setup
* [x] Auto-update target/source is valid.
* [x] Auto-update filemap is correct.

## Git commit checklist

* [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [ ] The parent of the commit(s) in the PR is not older than 3 days.
* [ ] Pull request is sent from a non-master branch with a meaningful name.
* [ ] Separate unrelated changes into different commits.
* [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [x] Close corresponding issue in commit message
* [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by dalisoft** [comment]
@PeterDaveHello Hi!

Is am i should add files manually? CDNJS does not fetches auto from NPM?

**Comment by PeterDaveHello** [comment]
@dalisoft leave the version info alone then you don't need to add the assets ;)

**Comment by dalisoft** [comment]
@PeterDaveHello Now looks OK?

**Comment by PeterDaveHello** [comment]
Thanks for your contribution @dalisoft

**Comment by dalisoft** [comment]
Thank you for your help @PeterDaveHello

**Pull request merged**
