### PR TITLE
add defiant.js v1.3.1 with git autoupdate

### PR DESCRIPTION
**Pull request by maruilian11**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Should not use defiant-latese*.js

**Comment by maruilian11** [comment]
fixed

**Comment by PeterDaveHello** [comment]
Can you update commit message to some kind of this:
`add defiant.js v1.3.1 with git autoupdate, close #5037`

**Comment by maruilian11** [comment]
ok

**Comment by PeterDaveHello** [comment]
** Should not use defiant-latese*.js **

**Comment by maruilian11** [comment]
ok

**Comment by PeterDaveHello** [comment]
Files still there ...

**Comment by maruilian11** [comment]
sorry...
hope this time is right

**Pull request merged**
