### PR TITLE
add rapidoid with git auto-update

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #8398
@pvnr0082t, @x09326 please help me review this pull request, thank you.
Manually add the old versions because there has different folder name format
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/rapidoid/rapidoid
- Official website (optional, not the repository):
- NPM package url (optional):
- GitHub / Bitbucket popularity (required):
  - Count of stars: 764
  - Count of watchers: 63
  - Count of forks: 61
- NPM download stats (optional):
  - Downloads in the last day:
  - Downloads in the last week:
  - Downloads in the last month:
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [x] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [ ] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by nmihajlovski** [comment]
Thanks @kennynaoh!

More accurate description of the Rapidoid's JS and CSS libraries would be:
`A pack of several JQuery and Angular plugins, Rapidoid extras and other JavaScript libraries that work well together, included by default in the Rapidoid web application framework.`

Also, most of the libraries in the pack are MIT-licensed, so I think changing `Apache` to `MIT` would be more appropriate.

**Comment by kennynaoh** [comment]
Thanks @nmihajlovski ,
I will fix it.

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 ,
I have fixed `description` and `license` part.
Please help me review it again.
Thanks!

**Comment by PeterDaveHello** [comment]
@nmihajlovski Thank you.

**Comment by pvnr0082t** [comment]
@kennynaoh Both of `rapidoid.min.js` and `rapidoid.min.css` look like not minified. Please confirm with author if he can provide officially minified files. Thanks.

**Comment by nmihajlovski** [comment]
Sure, I will provide minified files soon...

**Comment by PeterDaveHello** [comment]
@nmihajlovski Thank you!

**Comment by nmihajlovski** [comment]
I minified them, and I just released v5.2.3 with the minified files.

**Comment by kennynaoh** [comment]
@nmihajlovski Thank you!

**Comment by kennynaoh** [comment]
@PeterDaveHello ,
What should I do about `rapidoid.min.js` and `rapidoid.min.css` in the old version?
Because they are src js file, not minified file.
Or I could change the name from `rapidoid.min.js` to `rapidoid.js`, and minified it by myself.
Thanks!

**Comment by PeterDaveHello** [comment]
We can just leave them alone.

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 ,
I have added the latest version `5.2.3` with correct minified file.
Some of old version still remain minified file apparently but actually src file, and I leave them alone.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by x09326** [comment]
@kennynaoh 
Please rebase it.

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 
I have rebased to the latest master branch.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by x09326** [comment]
LGTM

**Comment by kennynaoh** [comment]
@PeterDaveHello 
What you mean is we can't accept this kind of version naming scheme?
Thanks!

**Comment by PeterDaveHello** [comment]
Should be like the others, not leading with a prefix.

**Comment by kennynaoh** [comment]
But this kind of naming scheme are used in some of old versions.
The naming scheme is changed in recent and latest version.
Is that also a problem?
If so, should I recommend author to change it, right?
Thanks!

**Comment by PeterDaveHello** [comment]
Yes, and you say it's only in old versions, so please manually modify them, and update .gitignore to prevent the bot add them again, thanks.

**Comment by kennynaoh** [comment]
What you mean modify them manually is this `rapidoid-4.0.3` --> `4.0.3`?
Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh correct

**Comment by nmihajlovski** [comment]
Regarding the "rapidoid-x.x.x" release tags, feel free to ignore these older versions.

**Comment by PeterDaveHello** [comment]
@kennynaoh why did you add the `wait for response` label? You just need to rename them and add a rule to `.gitignore`

**Comment by kennynaoh** [comment]
Because the main file is not the minified file.
https://github.com/rapidoid/rapidoid/issues/91

**Comment by PeterDaveHello** [comment]
@kennynaoh that's fine, but please just let us know what's going on here, thanks.

**Comment by kennynaoh** [comment]
OK

**Comment by nmihajlovski** [comment]
Hi @kennynaoh, what's the status of this issue? It seems that the progress has stopped.

**Comment by PeterDaveHello** [comment]
@nmihajlovski we'll get this lib hosted on CDNJS soon, sorry for the late reply.

**Comment by kennynaoh** [comment]
@pvnr0082t @x09326 I have updated this PR. Please help me review it again. Thanks!

**Comment by nmihajlovski** [comment]
Thanks!

**Comment by PeterDaveHello** [comment]
@nmihajlovski you're welcome

**Pull request merged**
