### PR TITLE
add parsley.js v2.1.3

### PR DESCRIPTION
**Pull request by maruilian11**
@Piicksarn  could u help me check this PR for #6473 ? thank you!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
You should not close the issue here, but report the problem.

**Comment by maruilian11** [comment]
sorry, report what problem?

**Comment by PeterDaveHello** [comment]
You think you solved #6473? Of course not.

**Comment by maruilian11** [comment]
so, we need to open an issue to remind the author to update version to 2.1.3 on npm package, then we can close the issue?

**Comment by PeterDaveHello** [comment]
"This" issue was closed 2 days ago. What do you mean we can close the issue?

**Comment by maruilian11** [comment]
i mean #6473

**Comment by PeterDaveHello** [comment]
So why don't we move to #6473 ?

**Pull request merged**
