### PR TITLE
[author] GSAP 1.16.0

### PR DESCRIPTION
**Pull request by jackdoyle**
Updating GSAP to 1.16.0 (including both /1.16.0/ and /latest/ directories).

The reason I'm doing a PR is primarily because of the /latest/ directory. Any chance you could help get this merged ASAP? Thanks a bunch!

### CODE REVIEW

**Comment by thomasdavis** [comment]
Pete has been running the show around here lately but GSAP sticks out in my inbox =D

**Comment by jackdoyle** [comment]
Excellent, thanks a bunch. I noticed that the /1.16.0/ directory is live, but the /latest/ directory didn't get updated. Any chance you could merge that in too? 

For example, you should see 1.16.0 at the top of this file, but it still says 1.15.1:
http://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenMax.min.js 

Help?

**Comment by PeterDaveHello** [comment]
That's the reason why we don't want to use the /latest/ directory, I think it's cached on the server, will be renew later.

And bye the way, I'll respectfully ask you to update your local repo with our latest master branch next time before committing and sending PR, the parent of this commit is too old, will make us harder to trace/debug while we got problems, thanks a lot!

**Comment by jackdoyle** [comment]
Ah, sorry about that. I thought I did a pull first, but I must have missed that. Wups. 

As for the /latest/ directory, I know it's not ideal but when we started with you guys we were told it was fine and now we've got a lot of people depending on that. I apologize if that's annoying. 

I'll keep an eye on the /latest/ directory and hopefully it'll get updated in the next 12 hours or so. Let me know if you think it may take longer. And thanks again!

**Comment by PeterDaveHello** [comment]
You don't need to apologize @jackdoyle, once your PR been merged, we also have responsibility on it, wait for at most 12 hours is a good idea, let's see if we'll get new version on it!

**Comment by jackdoyle** [comment]
Hmm...it looks like it has been over 24 hours and the /latest/ directory still hasn't been updated. It seems like something is wrong. Help?

Again, this should say 1.16.0 at the top: http://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenMax.min.js

**Comment by PeterDaveHello** [comment]
mention @thomasdavis & @terinjokes for help, thanks!

**Comment by jackdoyle** [comment]
Bump. Anyone? @thomasdavis? @terinjokes?

**Pull request merged**
