### PR TITLE
Slick Carousel 1.4.0

### PR DESCRIPTION
**Pull request by kenwheeler**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please read our document first for what you need to send a PR, thanks.

**Comment by kenwheeler** [comment]
Yeah? I've followed it to a "t". Whats the  problem?

**Comment by kenwheeler** [comment]
Via https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-updating-an-existing-library

I have met every condition

**Comment by kenwheeler** [comment]
As well as all the common conventions in the a. section

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs#important---no-more-manual-submissions
https://github.com/cdnjs/cdnjs#create-or-update-packagejson
https://github.com/cdnjs/cdnjs#raising-a-pull-request

Please tell me where are these files from, update the version field, and add auto-update config for it.

**Comment by PeterDaveHello** [comment]
No response, and we already have v1.4.0 & 1.4.1, so close this PR.

**Pull request closed without merging**
