### PR TITLE
add chartist-plugin-legend w/ npm autoupdate

### LINKED ISSUE #9183: [Request] Add chartist-plugin-legend
**Library name:** chartist-plugin-legend
**Git repository url:** https://github.com/CodeYellowBV/chartist-plugin-legend
**npm package url(optional):** npm install chartist-plugin-legend
**License(s):** https://github.com/CodeYellowBV/chartist-plugin-legend/blob/master/LICENSE
**Official homepage:** https://github.com/CodeYellowBV/chartist-plugin-legend
**Wanna say something? Leave message here:**

Legend plugin for Chartist.js

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #9183 
@x09326 @kennynaoh Please help me review this pull request, thank you.
Manually add the other versions from git repo because npm auto-update can't get some of the old versions

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/CodeYellowBV/chartist-plugin-legend
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/chartist-plugin-legend
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 35
   - Count of watchers: 8
   - Count of forks: 16
 * NPM download stats (optional):
   - Downloads in the last day: 44
   - Downloads in the last week: 208
   - Downloads in the last month: 1171

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9183, cc @SpaceK33z

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Is there something I should do here (as the author of this package)?

**Comment by x09326** [comment]
LGTM

**Comment by pvnr0082t** [comment]
@x09326 @kennynaoh I have rebased on the latest master branch. Please help me review it again, thank you.

**Comment by kennynaoh** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@SpaceK33z nope, just kindly let you know that what we are doing :smile: 

@pvnr0082t @x09326 @kennynaoh I don't know why you guys should ignored the author's comment, it's very rude and please do not do it again.

**Comment by pvnr0082t** [comment]
@SpaceK33z My apologies. I didn't mean to. :facepunch:

**Comment by SpaceK33z** [comment]
Okay haha it's alright

**Pull request merged**
