### PR TITLE
add avalon.js 1.4.3

### PR DESCRIPTION
**Pull request by zhangchunlin**
avalon.js : https://github.com/RubyLouvre/avalon

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please also add auto-update config for it, thanks.

**Comment by zhangchunlin** [comment]
@PeterDaveHello ,what is "auto-update"? I grep "auto-update" under "cdnjs/ajax/libs/angular.js" found nothing, can you give me an example?

**Comment by PeterDaveHello** [comment]
I think you should read the document first, readme.md or contributing.md, thanks.

**Comment by zhangchunlin** [comment]
@PeterDaveHello , Is my new patch OK?
Thanks.

**Comment by PeterDaveHello** [comment]
I'm afraid it's not.
If the auto-update need to grab minified files from `min`, the path of minified files will be like this `min/a.min.js`, I think you can put the minified files in the same folder, thanks.

**Comment by zhangchunlin** [comment]
@RubyLouvre ,Can you modify the file structure as https://github.com/cdnjs/cdnjs#enabling-gitrecommended-or-npm-auto-update , place avalon.js & avalon.min.js in same folder?
Thanks

**Comment by PeterDaveHello** [comment]
Maybe can add a `dist` folder.

**Comment by zhangchunlin** [comment]
The file structure has been modified already, but the version should be 1.4.4, it will be released in 6-15
I will push new patch after 1.4.4 release.

**Comment by PeterDaveHello** [comment]
Thank you, it'll be great if you could also rebase the branch with our latest master branch!

**Pull request closed without merging**
