### PR TITLE
add jQuery-rwdImageMaps@1.6 w/ git autoupdate

### LINKED ISSUE #9268: [Request] Add rwdImageMaps
**Library name:** rwdImageMaps
**Git repository url:** https://github.com/stowball/jQuery-rwdImageMaps
**npm package url(optional):** 
**License(s):** MIT license
**Official homepage:** http://mattstow.com/experiment/responsive-image-maps/rwd-image-maps.html
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #9268 
@x09326 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/stowball/jQuery-rwdImageMaps
 * Official website (optional, not the repository):
 * NPM package url (optional): 
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 1002
   - Count of watchers: 87
   - Count of forks: 409
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9268, cc @stowball

### CODE REVIEW

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Why don't you use `jQuery-rwdImageMaps` but `rwdImageMaps`?

**Comment by pvnr0082t** [comment]
Because the request title is `rwdImageMaps`, use `jQuery-rwdImageMaps` better?

**Comment by PeterDaveHello** [comment]
@pvnr0082t of course, I didn't see any good reference to ask you change its name'

**Comment by pvnr0082t** [comment]
@x09326 I have changed lib name to `jQuery-rwdImageMaps`. Please help me review it again, thank you.

**Comment by x09326** [comment]
@pvnr0082t 
I think the commit message need to be modified.

**Comment by pvnr0082t** [comment]
@x09326 I have modified commit message. Please help me review it again, thank you.

**Pull request merged**
