### PR TITLE
[new] add jquery.dirtyforms.dialogs.facebox@2.0.0-beta00004 with git auto-update

### PR DESCRIPTION
**Pull request by Amomo**
Hi @Piicksarn 

From #5599, I add jquery.dirtyforms.dialogs.facebox at v2.0.0-beta00004 from its dist repo.
dist repo: https://github.com/NightOwl888/jquery.dirtyforms.dialogs.facebox.dist

But I point the repo field to its main repo.
main repo: https://github.com/snikch/jquery.dirtyforms
I would also do this in other plugins' repo field. 

Would you mind checking this PR for me? Thank you~ :-D

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `14`, Star `133`, Fork `49`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by Piicksarn** [comment]
@Amomo, i willl ping peter after you have it reabased!
thank you! :smiley:

**Comment by Amomo** [comment]
@Piicksarn I have rebased, could take a look? Thank you~

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you have a look at the pr? Thank you!

**Comment by PeterDaveHello** [comment]
Did you really check it again after rebase @Piicksarn ?

**Comment by Piicksarn** [comment]
@PeterDaveHello, i did it!

**Pull request merged**
