### PR TITLE
[New] Add devicon w/ git auto-update

### LINKED ISSUE #11809: [Request] Add devicon
**Library name:** devicon
**Git repository url:** https://github.com/konpa/devicon
**npm package name or url** (if there is one): https://www.npmjs.com/package/devicon
**License (List them all if it's multiple):** [MIT](https://github.com/konpa/devicon/blob/master/LICENSE)
**Official homepage:** https://konpa.github.io/devicon/

### PR DESCRIPTION
**Pull request by sashberd**
close #11809, cc @konpa

Pull request for issue: #11809 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/konpa/devicon
 * Official website (optional, not the repository): http://devicon.fr/
 * NPM package url (optional): https://www.npmjs.com/package/devicon
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 50
   - Count of stars: 1317
   - Count of forks: 129
 * NPM download stats (optional):
   - Downloads in the last day: 7
   - Downloads in the last week: 86
   - Downloads in the last month: 256

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [X ] This lib was not found on cdnjs repo
 * [X ] No already exist / duplicated issue and PR
 * [ X] The lib has notable popularity
   * [X ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [ X] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [X ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [X ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X ] The parent of the commit(s) in the PR is not old than 3 days.
 * [X ] Pull request is sending from a non-master branch with meaningful name.
 * [ X] Separate unrelated changes into different commits.
 * [ X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [X ] Close corresponding issue in commit message
 * [X ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by maruilian11** [comment]
Hi @sashberd, 
Please remember to remove `close # 11809, cc @ konpa` in the init comment, or the authors will keep being bothered by each comment we make. Thanks.

**Comment by maruilian11** [comment]
The best way to test if fetch the wrong files(like `.json` `.md` `.mp3`) is using [`auto-update.js`](https://github.com/cdnjs/cdnjs/blob/master/auto-update.js)(for npm auto-update) and [`autoupdate`](https://github.com/cdnjs/autoupdate)(for git auto-update) to fetch the files yourself. That are also the ways our bot uses. Feel free to ask any question if you have problem using them. Thanks.

**Comment by PeterDaveHello** [comment]
@maruilian11 I won't ask non regular contributor to do that and mention it "the best" since the role is different. It's good to mention it and can give it a try if anyone wants to.

**Comment by sufuf3** [comment]
Update the title because this PR not only add v2.2, but also add v1.0.

**Pull request merged**
