### PR TITLE
adding jquery-domPath files

### PR DESCRIPTION
**Pull request by asatour**

### CODE REVIEW

**Comment by asatour** [comment]
I did one commit and only one for all introduced file.
all is ok now?

**Comment by PeterDaveHello** [comment]
Wold you please add auto-update config for it?

**Comment by asatour** [comment]
Sorry, but i didn't get you

**Comment by PeterDaveHello** [comment]
Yeah I think you didn't read the document first, https://github.com/cdnjs/cdnjs#important---no-more-manual-submissions, we need auto-update for the libs.

**Comment by asatour** [comment]
done

**Comment by PeterDaveHello** [comment]
There is no any tag in your repo, auto-update will need it to recognize different versions, would you please add it?

**Comment by asatour** [comment]
I did, the build is passed, something else still missing Sir?

**Comment by PeterDaveHello** [comment]
Hmmmm ... I didn't see any tag in that repo yet.

**Comment by asatour** [comment]
Sorry, I did now

**Comment by PeterDaveHello** [comment]
Thanks.

**Comment by PeterDaveHello** [comment]
Cause we have a problem on the website, so you won't see this project on it right now, but this url will be available in 30 mins https://cdnjs.cloudflare.com/ajax/libs/jquery-domPath/1.0.0/jquery.domPath.min.js so that you can use it.

**Comment by asatour** [comment]
Thanks a lot
big up

**Comment by PeterDaveHello** [comment]
np

**Comment by PeterDaveHello** [comment]
It's available now, but I noticed that there is no real code in your minified file, I think you should send a PR to fix it!

**Comment by PeterDaveHello** [comment]
Okay I fixed it in 9c38664.

**Pull request merged**
