### PR TITLE
Add Kule Lazy v3.0.1007beta

### PR DESCRIPTION
**Pull request by keicheng**
sorry, i redo all steps.

### CODE REVIEW

**Comment by maruilian11** [comment]
@keicheng the PR looks ok~ next time you can try `git cherry-pick`, so you don't have to redo all steps. just by one command. :smiley: 
also, if you use `git rebase`, you can avoid closing the PR, and open the new one.
but, you have done a great work :+1:  thank you for your contribrtion :smile:

**Comment by keicheng** [comment]
ok, thanks, i`ll try it next time

**Comment by keicheng** [comment]
I need to do something?

**Comment by PeterDaveHello** [comment]
Let's just merge it this time!

**Comment by keicheng** [comment]
thanks!

**Comment by keicheng** [comment]
Hi guys
I have some questions:
if my css has link image, how to i set url? and i need add img files into repo?

**Comment by PeterDaveHello** [comment]
should better also put the image in, for how to set rule, you can jut use relative path.

**Pull request merged**
