### PR TITLE
Add new versions of crypto-js.

### PR DESCRIPTION
**Pull request by evanvosberg**
Issue: #9958 
Related issue(s): https://github.com/brix/crypto-js/issues/75

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 94
   - Count of stars: 1591
   - Count of forks: 273
 * NPM download stats (optional):
   - Downloads in the last day: 16.936
   - Downloads in the last week: 92.935
   - Downloads in the last month: 390.481

# Essential checklist
 * [x] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [-] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [?] Auto-update setup
 * [?] Auto-update target/source is valid.
 * [?] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [-] The parent of the commit(s) in the PR is not old than 3 days.
 * [-] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [-] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [-] Close corresponding issue in commit message
 * [?] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@evanvosberg would you please rebase your branch with our latest master branch as CI mentions: https://ci.cdnjs.com/cdnjs/cdnjs/3160? Thanks.

**Comment by evanvosberg** [comment]
That's what I tried, but I ended up in a broken repo state with unstanged files, there was no way to reset ...

Have to checkout again ... try again ...

**Comment by PeterDaveHello** [comment]
@evanvosberg have you enabled sparseCheckout? We're happy to help to solve the problem if you'll like to.

**Comment by evanvosberg** [comment]
Yes the sparseCheckout is enabled, new checkout is running ... still takes a lot of time, will try to rebase again. @PeterDaveHello anything special I should consider with the rebase?

**Comment by PeterDaveHello** [comment]
@evanvosberg I think you'll only need to make sure you have the latest master branch just like cdnjs/cdnjs, then you can rebase, and after rebase, do a force push to overwrite the PR :+1:

**Comment by evanvosberg** [comment]
Created a new pull request https://github.com/cdnjs/cdnjs/pull/10520 from an non-master branch, base on a pretty master.

**Pull request closed without merging**
