### PR TITLE
[new] [author] added Matreshka.js

### PR DESCRIPTION
**Pull request by finom**
Hey guys. Trying to make pull request again.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
You missed its real files sir

**Comment by finom** [comment]
I'm sorry... Which files?  "matreshka.js", "matreshka.min.js", "matreshka.min.map" exist...

**Comment by PeterDaveHello** [comment]
"matreshka.js", "matreshka.min.js", "matreshka.min.map"
As the first you add a whole new lib, real files will be needed, as you can see, test failed bacause of this reason.

**Comment by finom** [comment]
Have no idea what's going on. Sad :(

**Comment by PeterDaveHello** [comment]
I meant you didn't add any files but package.json, is not enough.

**Comment by finom** [comment]
Ah! You mean add current version manually. I thought it will be pulled automatically.

**Comment by PeterDaveHello** [comment]
Yeah, but you won't pass the test, so you should add it.

**Comment by finom** [comment]
Ok thanks! I'll do this in a while.

**Comment by finom** [comment]
Finally :)

**Comment by finom** [comment]
@PeterDaveHello what is my next step? Should I just wait?

**Comment by PeterDaveHello** [comment]
Will pick it up, be patient please.

**Comment by PeterDaveHello** [comment]
Picked in d4c0e8a

**Comment by finom** [comment]
Awesome! Thanks.

**Comment by PeterDaveHello** [comment]
np

**Pull request closed without merging**
