### PR TITLE
add pangu v3.0.0

### PR DESCRIPTION
**Pull request by vinta**
- auto-update enabled (npm)
- official homepage: https://github.com/vinta/pangu.js
- npm page: https://www.npmjs.com/package/pangu
- version: 3.0.0

The origin of two new files:
https://github.com/vinta/pangu.js/blob/master/dist/browser/pangu.js
https://github.com/vinta/pangu.js/blob/master/dist/browser/pangu.min.js

Ping @PeterDaveHello

- - -

Fixes vinta/pangu.js#46

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@vinta will you not like the map file been hosted on cdn? I think you can add them in, and change the filemap to `"**/*"` instead of `"*.js"`, thanks.

**Comment by vinta** [comment]
@PeterDaveHello Please review it again. I did a git push --force on this branch.

**Comment by PeterDaveHello** [comment]
Looks good my my eyes, will merge if after test passed, thanks @vinta.

**Comment by vinta** [comment]
@PeterDaveHello Thank you!

**Comment by PeterDaveHello** [comment]
@vinta you are welcome.

**Comment by PeterDaveHello** [comment]
Deployed!
http://cdnjs.com/libraries/pangu
https://cdnjs.cloudflare.com/ajax/libs/pangu/3.0.0/pangu.js
https://cdnjs.cloudflare.com/ajax/libs/pangu/3.0.0/pangu.min.js

**Pull request merged**
