### PR TITLE
add plyr@1.8.2 w/ npm autoupdate

### LINKED ISSUE #8027: [Request] Add Plyr
**Library name: Plyr** 
**Git repository url: https://github.com/selz/plyr**
**npm package url: https://www.npmjs.com/package/plyr** 
**License(s): MIT**
**Official homepage: https://plyr.io**
**Wanna say something? Leave message here: A simple, accessible HTML5 media player.**

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8027 
@x09326 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/Selz/plyr
 * Official website (optional, not the repository): https://plyr.io
 * NPM package url (optional): https://www.npmjs.com/package/plyr
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 7737
   - Count of watchers: 266
   - Count of forks: 533
 * NPM download stats (optional):
   - Downloads in the last day: 628
   - Downloads in the last week: 1246
   - Downloads in the last month: 4637

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8027, cc @SamPotts

### CODE REVIEW

**Comment by x09326** [comment]
@pvnr0082t 
I think the origin files have been minified.
You don't have to minify it again.

**Comment by pvnr0082t** [comment]
@x09326 I have fixed it. Please help me review again, thank you.

**Comment by x09326** [comment]
@PeterDaveHello 
I think this PR is okay, please help me review it, thanks.

**Comment by PeterDaveHello** [comment]
> @pvnr0082t 
> I think the origin files have been minified.
> You don't have to minify it again.

@x09326 nice catch!

**Pull request merged**
