### PR TITLE
update postscribe to use npm

### PR DESCRIPTION
**Pull request by jnewman**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars:
   - Count of watchers:
   - Count of forks:
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

This adds the latest version of postscribe, which publishes it's dist
folder to npm.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@jnewman thanks for your PR, I noticed that there are some changes have nothing to do with transfer this lib to use npm auto-update config, would you please leave them alone? Thanks.

**Comment by jnewman** [comment]
Which ones? The homepage?

**Comment by jnewman** [comment]
I'll split them into another pull

**Comment by PeterDaveHello** [comment]
repository, homepage, filename. It's fine to fix them here, I can squash multiple commits.

**Comment by jnewman** [comment]
Sure, I meant I'll split updating them into another pull

**Comment by PeterDaveHello** [comment]
@jnewman I didn't see that they need to be updated, do they?

**Comment by jnewman** [comment]
Yes, we're not maintaining that homepage. I'll not change the repo and filename location. (I'd copied the position from jquery.)

**Comment by PeterDaveHello** [comment]
Okay, thanks, got your point.

**Comment by jnewman** [comment]
Rebased, please let me know if I should make any other changes. Thanks

**Comment by PeterDaveHello** [comment]
Thanks, let's move forward.
I saw `postscribe.js  postscribe.max.js  postscribe.min.js  test-reports/` in the dist of the latest npm package, seems there is no map file there, but it's in the commit, is this correct? Also, I wonder if the test-report files should be kind of distribution file? If it must be there, we should exclude it from the filemap. Thanks.

**Comment by jnewman** [comment]
I'll update the postscribe build to include the map and exclude the test-report. Thanks, for the heads up.

**Comment by PeterDaveHello** [comment]
NP, thanks for prompt reply.

**Comment by jnewman** [comment]
Updated. Now pointing to 2.0.5.

**Pull request merged**
