### PR TITLE
add scrollbear v0.0.3 with npm autoupdate config

### LINKED ISSUE #7732: [Request] Add Scollbear
**Library name:** scrollbear
**Git repository url:**https://github.com/changbenny/scrollbear
**npm package url(optional):** https://www.npmjs.com/package/scrollbear
**License(s):** MIT
**Official homepage:** http://changbenny.github.io/scrollbear/

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/33411213-request-add-scollbear?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by dannyxx001**
PR for #7732 
@kennynaoh please help me review this PR, thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/changbenny/scrollbear
- Official website (optional, not the repository): https://changbenny.github.io/scrollbear/
- NPM package url (optional): https://www.npmjs.com/package/scrollbear
- GitHub / Bitbucket popularity (required):
  - Count of stars: 399
  - Count of watchers: 9
  - Count of forks: 7
- NPM download stats (optional):
  - Downloads in the last day: 5
  - Downloads in the last week: 12
  - Downloads in the last month: 92
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [x] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [ ] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

close #7732, cc @changbenny

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@dannyxx001 don't forget to assign.

**Comment by kennynaoh** [comment]
@dannyxx001 
The latest git tag version: ```v0.1.0``` is not the same as the latest version: ```v0.3.0``` in ```package.json```
Please check this.
Thanks.

**Comment by PeterDaveHello** [comment]
@kennynaoh use `confirm` instead of `check` here.

**Comment by PeterDaveHello** [comment]
Ping.

**Comment by PeterDaveHello** [comment]
Hello, any updates here? Thanks.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@extend1994 I saw you pick up this lib.
If you have time, please work on this, thanks.

**Comment by extend1994** [comment]
@sufuf3 waiting the author's help https://github.com/changbenny/scrollbear/issues/9. I have added the tag of waiting response in the issue https://github.com/cdnjs/cdnjs/issues/7732

**Comment by sufuf3** [comment]
@PeterDaveHello Could we close this one, and wait for response from changbenny/scrollbear#9?
Because there is an issue for adding this lib.
And there is no response from contributor for a while.
Many thanks.

**Comment by PeterDaveHello** [comment]
We can reopen anytime

**Pull request closed without merging**
