### PR TITLE
[new] add angular-leaflet-directive@0.8.6 with git auto-update, close #5193

### LINKED ISSUE #5193: [Request] angular-leaflet-directive
**Library name:** angular-leaflet-directive
**Git repository url:** https://github.com/tombatossals/angular-leaflet-directive
**npm package url(optional):** 
**Official homepage:** http://tombatossals.github.io/angular-leaflet-directive/#!/
**Wanna say something? Leave message here:** Please #)

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 , I add a new lib with git auto-update from the request #5193 
repo: https://github.com/tombatossals/angular-leaflet-directive
I collect files in dist/ not include architecture/, and minify angular-leaflet-directive_dev_mapped.js.
Would you mind checking this PR for me? Thank you~ :-)

### CODE REVIEW

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Comment by PeterDaveHello** [comment]
You sure we don't need `architecture` folder?

**Comment by maruilian11** [comment]
maybe we need <code>.png</code>.

**Comment by Amomo** [comment]
@PeterDaveHello 
According to this, 
https://github.com/tombatossals/angular-leaflet-directive/pull/801
I think `architecture` folder is used for documentation.
And, I didn't see any file reference the files in `architecture`.
For these reason, I think we can ignore it.

**Pull request merged**
