### PR TITLE
add cytoscape 2.0.1 ~ 2.0.5, 2.1.0, 2.1.1

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/cytoscape/cytoscape.js
**Watch 148
  Star 2,167
 Fork 313**
@PeterDaveHello  could u help me check this PR for #6094 ? thank you!
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR 
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update) https://github.com/elevateweb/elevatezoom/issues/120
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Missing map file ?
https://github.com/maruilian11/cdnjs/blob/cytoscape/ajax/libs/cytoscape/2.0.1/cytoscape.min.js#L7

**Comment by maruilian11** [comment]
@PeterDaveHello i removed the map file to keep file structure the same, i have added it back.

**Comment by PeterDaveHello** [comment]
So what's the source of this proble? Where did you get it?

**Comment by maruilian11** [comment]
by your comment
https://github.com/cdnjs/cdnjs/issues/6094#issue-114580079
>https://github.com/cytoscape/cytoscape.js/releases

**Comment by PeterDaveHello** [comment]
You didn't answer the question.

**Comment by maruilian11** [comment]
https://github.com/cytoscape/cytoscape.js/archive/v2.1.1.zip
use the same with v2.0.1 ~ 2.0.5, 2.1.0, 2.1.1

**Comment by PeterDaveHello** [comment]
So where can I see the file with wrong map from source?

**Comment by PeterDaveHello** [comment]
Don't assign to me if there is nothing changed.

**Comment by maruilian11** [comment]
oh i mistook your meaning
the file with wrong map from source isn't from https://github.com/cytoscape/cytoscape.js/archive/v2.0.1.zip
it was made by web-minify-helper
when i built v2.0.1 files, it only built `cytoscape.js`, so i use web-minify-helper to minified the file.

**Comment by PeterDaveHello** [comment]
So what's the source of the minified file? There are so many file, you minify by guessing?

**Comment by maruilian11** [comment]
as i said 2.0.1 only built `cytoscape.js`, that is the source of  the minified file.

**Comment by PeterDaveHello** [comment]
Also so that problem came from your manually minify process, that's the simply answer.

**Pull request merged**
