### PR TITLE
Add waypoints library

### PR DESCRIPTION
**Pull request by githubfantom**
Add waypoints library. Clone https://github.com/githubfantom/jquery.waypoints

### CODE REVIEW

**Comment by githubfantom** [comment]
Change name in package.json

**Comment by drewfreyling** [comment]
Thanks @githubfantom 
Any chance you could squash them into 1 commit?

**Comment by githubfantom** [comment]
I do not know how to do it. Can you help?

**Comment by PeterDaveHello** [comment]
`git rebase`

**Pull request closed without merging**
