### PR TITLE
Pixelcog [**Parallax.js**]

### PR DESCRIPTION
**Pull request by vivekkupadhyay**
**Parallax.js** 
**https://github.com/pixelcog/parallax.js**
**http://pixelcog.com/parallax.js**
Its a really great repository for `parallax` effect, please add this into [**cdn**](https://cdnjs.com).

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
This PR is in a mess, please fix it first, thanks.

**Comment by PeterDaveHello** [comment]
This is a wrong PR, please fix it, or I'll close it in 3 days, thanks.

**Comment by vivekkupadhyay** [comment]
Ok.
My apologies for late reply, yeah please go ahead, it was indeed a mess.

**Comment by PeterDaveHello** [comment]
Thanks.

**Pull request closed without merging**
