### PR TITLE
add Mixitup v2.1.9 and update package.json, close #5320

### LINKED ISSUE #5320: [Request] Add MixItUp
**Library name:** MixItUp 
**Git repository url:** https://github.com/patrickkunka/mixitup
**npm package url(optional):** 
**Official homepage:** https://mixitup.kunkalabs.com/
**Wanna say something? Leave message here:** Actually on cdnjs there is only a very old version. Please, add version 21.8 and 2.1.9. Thank you so much!

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by maruilian11**
@LeaYeh could u plz help me check this PR for #5320, thank you !
**watch : 162**
**star : 2842**
**fork : 425**
**git repo url :** https://github.com/patrickkunka/mixitup

* [ ] Not found on cdnjs repo
* [x] No already exist issue and PR
* [x] Notable popularity
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)
* [x] Has valid tags for each versions (for git auto-update)
* [x] Auto-update setup
* [x] Auto-update target/source is valid.
* [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by maruilian11** [comment]
@Piicksarn could u help me check this PR for #5320, thank you~

**Comment by Piicksarn** [comment]
@maruilian11, i think you should change version number in package.json on a769a2f, and change commit line to "Update mixitup to v2.1.9". 6a7935b just for adding autoupdate config.

Or, the simplest way is to add autoupdate config in mixitup only.

**Comment by maruilian11** [comment]
@Piicksarn i have corrected it, could u help me check it again? thank you very much!

**Comment by Piicksarn** [comment]
@maruilian11, sorry for my delay...
It's fine but need be rebased to master!

**Comment by maruilian11** [comment]
@Piicksarn it's alright~ i often forget to check PRs, too. could u help me check it again? thank you!

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you please have a look at the pr?
thank you!

**Pull request merged**
