### PR TITLE
add git autoupdate config in jquery-sparklines.js

### PR DESCRIPTION
**Pull request by LeaYeh**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please fix the error in build.

**Comment by LeaYeh** [comment]
check this.

**Comment by PeterDaveHello** [comment]
There is no js file under dist.
https://github.com/gwatts/jquery.sparkline/tree/v2.0/dist
https://github.com/gwatts/jquery.sparkline/tree/v2.1/dist
https://github.com/gwatts/jquery.sparkline/tree/v2.1.1/dist
https://github.com/gwatts/jquery.sparkline/tree/v2.1.2/dist

**Comment by LeaYeh** [comment]
這種要自己 make 的是不是就不適用 auto update?

**Comment by drewfreyling** [comment]
@LeaYeh english please?

**Pull request closed without merging**
