### PR TITLE
[new] add react-redux@4.0.0 with npm auto-update

### PR DESCRIPTION
**Pull request by Amomo**
Hi @Piicksarn 

For #5947, I add react-redux at v4.0.0 and add `npm` auto-update config in its package.json.
repo: https://github.com/rackt/react-redux

Would you mind checking this PR for me? Thank you~ :-D

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `98`, Star `932`, Fork `98`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by gaearon** [comment]
Thank you for this. :-)

**Comment by Piicksarn** [comment]
@Amomo, sorry for my delay!
The pr is fine but need rebase to the master!
Thank you :smiley:

**Comment by Amomo** [comment]
@Piicksarn I have rebased it, could you check again? Thanks~

**Comment by Piicksarn** [comment]
It's fine!
@PeterDaveHello, would you mind to have a look at the pr?
thank you!

**Pull request merged**
