### PR TITLE
add license to hiw-api

### PR DESCRIPTION
**Pull request by honestree**
added license to hiw-api
https://github.com/HealthIndicators/js-api/blob/master/LICENSE.md

### CODE REVIEW

**Comment by honestree** [comment]
@x09326 
#5500 license adding of hiw-api
please help me review it ,again!

**Comment by x09326** [comment]
LGTM
ping @cdnjs/intern2

**Comment by honestree** [comment]
@x09326 
#5500 license adding of hiw-api
please help me review it, for the third time!

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
