### PR TITLE
update git auto-update config of vex-js

### LINKED ISSUE #8710: Update vex
v3 beta1 was released : https://github.com/HubSpot/vex/tree/v3.0.0-beta.1

May need to update the auto-update config.

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8710 
@kennynaoh Please help me review this pull request, thank you.

close #8710

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
hmmmm ... this will change the structure, have you discussed with the author? Maybe css can be in the `dist` folder too.

**Comment by geekjuice** [comment]
Since the `files` field still points to the styles in `css`, is there a blocking reason why they should be moved to the `dist` directory?

Having said that, it is fairly common to place distribution files together e.g. `dist/{css,js}`, so if @bbatliner (/cc @adamschwartz) doesn't have a strong preference in keeping the structure as is, we can consider restructuring.

**Comment by bbatliner** [comment]
No reason why the files can't be moved. Looking at the other HubSpot repos, they follow the pattern `dist/css/*.css` and `dist/js/*.js` for built files - would this directory structure work for cdnjs?

**Comment by PeterDaveHello** [comment]
@bbatliner that will work.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by bbatliner** [comment]
Update from [another comment of mine](https://github.com/cdnjs/cdnjs/issues/8710#issuecomment-285747182).

> Hi again,
> 
> We've switched fully to the /dist/{css,js}/*.{css,js} structure in all our releases past 3.0.0. I checked the vex-js folder here in the cdnjs repo and it > seems to be pulling the right files.
> 
> Let me know if anything needs to change.

**Comment by pvnr0082t** [comment]
The auto-update config had already been updated. See 1d6b7e99761fd3d0c9dae3a2724895e408a6079b. And vex-js in cdnjs is the latest version(https://cdnjs.com/libraries/vex-js). I'm going to close this PR.

**Pull request closed without merging**
