### PR TITLE
[New] Add route-recognizer@0.3.3 w/ npm auto-update

### LINKED ISSUE #8410: [Request] Add route-recognizer
**Library name:** route-recognizer
**Git repository url:**https://github.com/tildeio/route-recognizer
**npm package url(optional):** https://www.npmjs.com/package/route-recognizer
**License(s):**MIT
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35660808-request-add-route-recognizer?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sufuf3**
close #8410, close #8444

Pull request for issue: #8410
Related issue(s): #8444 #11170

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/tildeio/route-recognizer
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/route-recognizer
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 32
   - Count of stars: 366
   - Count of forks: 82
 * NPM download stats (optional):
   - Downloads in the last day: 4573
   - Downloads in the last week: 28954
   - Downloads in the last month: 121,916

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@cdnjs/intern3 @dakshshah96 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
I exclude the folder `named-amd`, `es5` and the files `*.amd.js`, `*.cjs.js`, `*.es.js` which use in back-end.
I didn't manually add v0.1.2 ~ v0.1.3 from npm because the `route-recognizer.js` which under `lib` I think it can't use in web front-end. And with `brower.json` said, the `dist/route-recognizer.js` is fine to use in the front-end, but I think the library miss these files from these two versions.

@extend1994 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@dakshshah96 @cdnjs/intern3 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@pvnr0082t @maruilian11 @qwe19272375 @hare1039 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@hare1039 @qwe19272375 @pvnr0082t @maruilian11
Please help me review this PR, Thank you.

**Comment by maruilian11** [comment]
@sufuf3 How do you ensure `*.amd.js`, `*.cjs.js` and  `*.es.js` are for back-end?

**Comment by sufuf3** [comment]
- `*.es.js` learn from https://github.com/cdnjs/cdnjs/pull/11183#issuecomment-300976140
- `*.cjs.js` learn from https://github.com/cdnjs/cdnjs/pull/5823#issuecomment-154659196
And I think maybe I have to add `*.amd.js`, I refer to http://yulin-learn-web-dev.logdown.com/posts/306644-some-terms-on-the-website-front-end-development-requirejs-browserify-amd-commonjs-npm-bower and http://requirejs.org/docs/whyamd.html

Thank you.

**Comment by maruilian11** [comment]
@sufuf3 The first ref shows if there is `import` in es6 file, it won't work, so we don't host it. But there is no `import` in `0.1.0` es file.
The second ref shows we need to confirm with the author if `cjs.js` can be hosted.

@PeterDaveHello Seems like `web-minify-helper` only for ES6+, so we can't use it for `es.js`? If it can't, do we only add it manually without minifying?

**Comment by PeterDaveHello** [comment]
I don't believe @sufuf3 you really learned what they are, let's assign this as your assignment, and give a short presentation about what do you know about those packaging technologies.

Every front-end resource should be optimized/minified for better performance, es6 is not widely supported yet and many of them even not working in browser, maybe we just don't add them(and still, make sure the files we are going to add will work).

**Comment by sufuf3** [comment]
@PeterDaveHello sorry, I'll learn packaging technologies.

**Comment by sufuf3** [comment]
I'll help to fix this PR until I get the reply from the author.
From now, I'll close this PR and wait for the response.
Thanks

**Pull request closed without merging**
