### PR TITLE
add datepick w/ git auto-update config

### LINKED ISSUE #8832: [Request] Add jQuery Datepicker
**Library name:** jQuery Datepicker
**Git repository url:** https://github.com/kbwood/datepick
**npm package url(optional):** -
**License(s):** MIT
**Official homepage:** http://keith-wood.name/datepick.HTML
**Wanna say something? Leave message here:**

Author promotes his own website instead of GitHub repo so it does not have a lot of stars, but:
- this lib has **2nd place in Google** for _jQuery Datepicker_
- it's the most advanced datepicker out there
- you already host another lib of this author: https://cdnjs.com/libraries/jquery-countdown

### PR DESCRIPTION
**Pull request by x09326**
PR for #8832 
@pvnr0082t @kennynaoh  please help me review it, thanks.

Manually add old versions of datepick because the file structure is different from the latest version then git auto-update can't get them.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required):https://github.com/kbwood/datepick
- Official website (optional, not the repository): http://keith-wood.name/datepick.html
- NPM package url (optional):
- GitHub / Bitbucket popularity (required):
  - Count of stars:65
  - Count of watchers:36
  - Count of forks:19
- NPM download stats (optional):
  - Downloads in the last day:
  - Downloads in the last week:
  - Downloads in the last month:
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [x] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

close #8832, cc @kbwood

### CODE REVIEW

**Comment by x09326** [comment]
@pvnr0082t 
I have added it.
I found that the file structure is different from the latest version.
And the version tag is uncommon.
Should I discuss with author?
Or I just modify something?

**Comment by pvnr0082t** [comment]
>the version tag is uncommon.

Have you tried if auto-updater can get all versions from git repo?

**Comment by pvnr0082t** [comment]
>I found that the file structure is different from the latest version

I think you need to manually add them.

**Comment by x09326** [comment]
@kennynaoh @pvnr0082t 
I have added the old version.
Please help me review it, thanks.

**Comment by x09326** [comment]
@pvnr0082t @kennynaoh 
I have fixed the version number and the file structure of 5.0.0.
Please help me review it, thanks.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@x09326 try to not generate the map file ver the old versions next time, since there is no map from official release, we usually just generate the map for the latest release unless there are map files in old releases.

**Comment by x09326** [comment]
@PeterDaveHello 
Okay, I will remember that next time.

**Pull request merged**
