### PR TITLE
Add jquery-awesome-cursor v0.1.4

### PR DESCRIPTION
**Pull request by yumeixxx**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Should add its files in the PR.

**Comment by PeterDaveHello** [comment]
cc @cdnjs/intern

**Comment by maruilian11** [comment]
@yumeixxx please also add a folder named `jquery-awesome-cursor` and put the package.json in it. And create a fold named the version number, then add files under `dist` to `0.1.4`.

**Comment by yumeixxx** [comment]
I'm sorry.
I have changed.

**Comment by maruilian11** [comment]
@yumeixxx all your step is correct! but can you use `git rebase -i HEAD~5` to delete unnecessary commit and squash other into one commit ? :smiley:

**Comment by maruilian11** [comment]
hi @yumeixxx, any update?

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Pull request closed without merging**
