### PR TITLE
Add license of ng-clip, cc #9248

### PR DESCRIPTION
**Pull request by jingwei95**
https://github.com/asafdav/ng-clip/edit/master/LICENSE

### CODE REVIEW

**Comment by kennynaoh** [comment]
LGTM
@cdnjs/intern2

**Comment by x09326** [comment]
LGTM

**Comment by x09326** [comment]
@jingwei95
Your reference is a wrong page. 
https://github.com/asafdav/ng-clip/blob/master/LICENSE
I think this is the right one.
Please find a right reference next time

**Comment by kennynaoh** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
Thanks for your contribution.

**Pull request merged**
