### PR TITLE
Optimize RSS build process, closes #10198

### LINKED ISSUE #10198: Refactor RSS in build process
[Bountysource](https://www.bountysource.com/issues/40687237-refactor-rss-in-build-process?utm_source=40687237&utm_medium=shield&utm_campaign=ISSUE_BADGE)

The RSS generation process currently we are using is really too slow, and also use too much cpu/memory resource.

The root cause seems to be the git command, there are too many git commands involve in, the exec commands, not including the js codes, will use more than 5 minutes on an 8-core 160$/MO DigitalOcean VPS in the whole build process and make the process super slow, should better refactor the process ASAP ...

Ref:
https://github.com/cdnjs/cdnjs/blob/c137f9788ff22251e0059dc5172e93e852a8543e/build/packages.json.js#L26-L90

### PR DESCRIPTION
**Pull request by VPashkov**
Pull request for issue: #10198

As stated in the issue #10198 the main reason of slow RSS build process was this git/bash command:
`git ls-tree -r --name-only HEAD | grep **/package.json | xargs -n 1 -P ' + threads + ' git log -1 --since="2 weeks ago" --name-status --format="blahcrap %ad" --`
I replaced it with the following command:
`git log --since="2 weeks ago" --name-status --format="blahcrap %ad" -- **/package.json`
and RSS build time decreased from 7 minutes to 3 seconds on my machine.
I also adjusted RSS generation code because new command produces slightly different output.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@pvnr0082t I think you can take a first review.

**Comment by PeterDaveHello** [comment]
@pvnr0082t tested yet? I'll like to push this improvement asap.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I'll find the time to test it.

**Comment by pvnr0082t** [comment]
After I ran origin `packages.json.js` and modified `packages.json.js`
- `packages.min.json` under `new-website/public` are the same
```
da55d7218242aa476d4dc4e72906845f  packages.min.json
da55d7218242aa476d4dc4e72906845f  packages.min.json_origin
```
- I used `vimdiff` to test `rss.xml` under `new-website/public` and they are almost the same. They are different at `<lastBuildDate>` only.

**Comment by PeterDaveHello** [comment]
`packages.min.json` is not related with this change so you'll not see any different with it.

**Comment by PeterDaveHello** [comment]
@pvnr0082t did you compare the time spent before and after this PR?

**Comment by pvnr0082t** [comment]
@PeterDaveHello Yes, I did.
Before
```
real    1m7.725s
user    6m2.776s
sys     1m12.288s
```
After
```
real    0m18.334s
user    0m2.604s
sys     0m10.500s
```

**Comment by PeterDaveHello** [comment]
@VPashkov Thanks a lot for your contribution, please claim you bounty here:
https://www.bountysource.com/issues/40687237-refactor-rss-in-build-process

Thank you again!

**Comment by PeterDaveHello** [comment]
Hello @VPashkov ?

**Comment by VPashkov** [comment]
@PeterDaveHello, hi. Sorry I didn't reply earlier. I don't need this bounty. I would be glad if you cancel this bounty and assign it to another issue.

**Comment by PeterDaveHello** [comment]
@VPashkov No worries, thanks for your reply and contribution, I'm not sure if there is option to cancel bounty, though I know the bounty is very low, you can also take it and donate to any project you'd like to help (including CDNJS), but no pressure at all, it's all up to you, thanks again :)

**Comment by PeterDaveHello** [comment]
Since there is no way to cancel the bounty, I just claim the bounty with the reason of why I need to claim it by myself, and'll use that bounty on the other issues, thanks for @VPashkov again!

**Pull request merged**
