### PR TITLE
[New] Add inferno-vnode-flags w/ npm auto-update

### PR DESCRIPTION
**Pull request by sufuf3**
Pull request for issue: #10840
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/infernojs/inferno
 * Official website (optional, not the repository): https://infernojs.org/
 * NPM package url (optional): https://www.npmjs.com/package/inferno-vnode-flags
 * License and its reference: MIT, https://github.com/infernojs/inferno/blob/master/LICENSE.md
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 304
   - Count of stars: 10562
   - Count of forks: 454
 * NPM download stats (optional):
   - Downloads in the last day: 866
   - Downloads in the last week: 4441
   - Downloads in the last month: 26,672

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@extend1994 @cdnjs/intern3  I added v1.0.1 ~ v1.2.2 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@cdnjs/active-contributor @cdnjs/intern3 I updated .gitignore and manually added v1.0.0-beta{10..45}
Please help me review this PR again, Thank you.

**Comment by maruilian11** [comment]
Don't we need `4.0.0-alpha1`?

**Comment by sufuf3** [comment]
I think we can include `4.0.0-alpha1`
I ignore `/ajax/libs/inferno-vnode-flags/*-alpha.*`, `4.0.0-alpha1` can't fit this rule, so `4.0.0-alpha1` will be added via auto-update config.
Thank you.

**Comment by sufuf3** [comment]
@extend1994 @pvnr0082t @mercyg 
Please help me review this PR again, Thank you.

**Comment by sufuf3** [comment]
I updated the commit message
@cdnjs/intern3 @cdnjs/active-contributor @cdnjs/library-reviewer 
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@maruilian11 thank you, I updated the commit message
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@hare1039 @qwe19272375 @pvnr0082t @maruilian11
Please help me review this PR, Thank you.

**Comment by PeterDaveHello** [comment]
Was 1.0.0-beta45 minified by you? Shouldn't you respond to @maruilian11 ?

**Comment by sufuf3** [comment]
No, I copied from https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/inferno/1.0.0-beta45/inferno-vnode-flags.min.js.map.

**Comment by PeterDaveHello** [comment]
You copy a minified file from a map file? Really?

**Comment by sufuf3** [comment]
@PeterDaveHello sorry I mean I copied https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/inferno/1.0.0-beta45/inferno-vnode-flags.min.js.map this file and add this file under `1.0.0-beta45` this folder.

**Comment by PeterDaveHello** [comment]
@sufuf3 I think I'm asking the minify process ...

**Comment by sufuf3** [comment]
This PR's situation as same with this https://github.com/cdnjs/cdnjs/pull/11561#pullrequestreview-56521819

**Comment by sufuf3** [comment]
Reminified 1.0.0-beta45 without map file.
@cdnjs/active-contributor @cdnjs/intern3
Please help me review this PR, Thank you.

**Pull request merged**
