### PR TITLE
Update auto-update config of inferno related libs

### LINKED ISSUE #10840: [Request] Update Inferno libraries
Library name: inferno
Git monorepo root https://github.com/infernojs/inferno   (changed)
packages (GIT):
https://github.com/infernojs/inferno/tree/master/packages/inferno-compat
https://github.com/infernojs/inferno/tree/master/packages/inferno-component
https://github.com/infernojs/inferno/tree/master/packages/inferno-create-class
https://github.com/infernojs/inferno/tree/master/packages/inferno-create-element
https://github.com/infernojs/inferno/tree/master/packages/inferno-devtools
https://github.com/infernojs/inferno/tree/master/packages/inferno-hyperscript
https://github.com/infernojs/inferno/tree/master/packages/inferno-mobx
https://github.com/infernojs/inferno/tree/master/packages/inferno-redux
https://github.com/infernojs/inferno/tree/master/packages/inferno-router
https://github.com/infernojs/inferno/tree/master/packages/inferno-server
https://github.com/infernojs/inferno/tree/master/packages/inferno-shared
https://github.com/infernojs/inferno/tree/master/packages/inferno-test-utils
https://github.com/infernojs/inferno/tree/master/packages/inferno-vnode-flags
https://github.com/infernojs/inferno/tree/master/packages/inferno

npm package url(optional):
- [x] https://www.npmjs.com/package/inferno-compat
- [x] https://www.npmjs.com/package/inferno-component
- [x] https://www.npmjs.com/package/inferno-create-class
- [x] https://www.npmjs.com/package/inferno-create-element
- [x] https://www.npmjs.com/package/inferno-devtools
- [x] https://www.npmjs.com/package/inferno-hyperscript
- [x] https://www.npmjs.com/package/inferno-mobx
- [x] https://www.npmjs.com/package/inferno-redux
- [x] https://www.npmjs.com/package/inferno-router
- [x] https://www.npmjs.com/package/inferno-server
- [x] https://www.npmjs.com/package/inferno-shared
- [x] https://www.npmjs.com/package/inferno-test-utils
- [x] https://www.npmjs.com/package/inferno-vnode-flags
- [x] https://www.npmjs.com/package/inferno

License(s): The MIT license
Official homepage: http://infernojs.org/

### PR DESCRIPTION
**Pull request by extend1994**
Update file pattern to grab files with more possible file types.
According to https://github.com/cdnjs/cdnjs/pull/11621#discussion_r136314498.
And I think we can close #10840 after this pull request is merged because all inferno related lib were added.

### CODE REVIEW

**Comment by extend1994** [comment]
@sufuf3 I updated the commit message, please help review it, thanks.

**Comment by sufuf3** [comment]
Sorry~
Should we use the plural? (libs) add `s`?

**Comment by extend1994** [comment]
Oh yes, update right away.

**Comment by extend1994** [comment]
@sufuf3 Done, please check it. Thx.

**Comment by extend1994** [comment]
@sufuf3 I used `cc` instead of `close` in the commit message.

**Comment by extend1994** [comment]
ping @cdnjs/intern3 @cdnjs/library-reviewer @cdnjs/active-contributor

**Comment by maruilian11** [comment]
@extend1994 Why use `!(*.node)*.!(*ts)` for all inferno case? Do they all exist `node.js` and `*.ts` before
?

**Comment by extend1994** [comment]
@maruilian11 Yes, you can refer the discussions in https://github.com/cdnjs/cdnjs/pull/11621.

**Comment by sufuf3** [comment]
FYI: https://github.com/cdnjs/cdnjs/pull/11621#pullrequestreview-59490800

**Pull request merged**
