### PR TITLE
Add git autoupdate config in superfish

### PR DESCRIPTION
**Pull request by Piicksarn**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I wonder if we need all the files including 3-party libs 'cause they aren't in the old versions on our cdn.

**Comment by Piicksarn** [comment]
i just have a correction to make filemap more precise. is this suitable?

**Comment by PeterDaveHello** [comment]
megafish.css seems to be part of this project?

**Comment by Piicksarn** [comment]
have it corrected and rebased to the master

**Comment by PeterDaveHello** [comment]
No you didn't.

**Comment by Piicksarn** [comment]
is it ok now？～

**Comment by PeterDaveHello** [comment]
Of course, not.

**Comment by Piicksarn** [comment]
megafish.css seems to be part of this project! i check out the old versions of the project and cdn, finding it had been included, so that i added it in autoupdate config.

**Pull request merged**
