### PR TITLE
Add vue-bootstrap-typeahead via single package.json w/ npm auto-update

### PR DESCRIPTION
**Pull request by TheRealChrisS**
# Pull request template for new library

Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

## Profile of the lib

* Git repository (required): https://github.com/alexurquhart/vue-bootstrap-typeahead
* Official website (optional, not the repository): https://alexurquhart.github.io/vue-bootstrap-typeahead/
* NPM package url (optional): https://github.com/alexurquhart/vue-bootstrap-typeahead/blob/master/package.json
* License and its reference: https://github.com/alexurquhart/vue-bootstrap-typeahead/blob/master/LICENSE.txt
* GitHub / Bitbucket popularity (required):
  * Count of watchers: 3
  * Count of stars: 48
  * Count of forks: 33
* NPM download stats (optional):
  * Downloads in the last day: 297
  * Downloads in the last week: 1747
  * Downloads in the last month: 18063

## Essential checklist

* [ ] I'm the author of this library
  * [ ] I would like to add link to the page of this library on CDNJS on website / readme
* [x] This lib was not found on cdnjs repo
* [x] Doesn't already exist / has duplicate issue and PR
* [x] The lib has notable popularity
  * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [x] More than 800 downloads stats per month on npm registry
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [x] Has valid tags for each versions (for git auto-update)
* [x] Auto-update setup
* [x] Auto-update target/source is valid.
* [x] Auto-update filemap is correct.

## Git commit checklist

* [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [x] The parent of the commit(s) in the PR is not older than 3 days.
* [x] Pull request is sent from a non-master branch with a meaningful name.
* [x] Separate unrelated changes into different commits.
* [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [x] Close corresponding issue in commit message
* [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by xtuc** [comment]
Since yesterday no versions were pushed by the bot. But it has 8 versions on npm.

I'm going to move this package to our new bot.

**Comment by xtuc** [comment]
I changed the file map a bit in https://github.com/cdnjs/packages/commit/74aae1675e4e685a996a872ba83163efff23f3ea, which added a few unwanted file but it's not a big deal.

Existing versions were pushed by the new bot https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/vue-bootstrap-typeahead.

**Comment by MattIPv4** [comment]
Why did the filemap get changed? The current in this PR is a valid glob and should pick up all the files that we want to be hosting for this lib?

**Comment by MattIPv4** [comment]
Awesome to see that the bot is working and pushing new versions from the new repo to here. However, it looks like it didn't push a package.json to here with a version populated? https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/vue-bootstrap-typeahead

**Comment by xtuc** [comment]
> Why did the filemap get changed? The current in this PR is a valid glob and should pick up all the files that we want to be hosting for this lib?

That's true. I noticed that we have regressions between the glob implementation in js and the one I found in Golang. I need to rewrite one that is 100% same.

> However, it looks like it didn't push a package.json to here with a version populated? 

Yes, that's true. And since I deleted the package.json here the package will be removed from the website shortly.
For the Algolia index I'm planning to push the new search entry when the package has been updated, so that the version is always the latest without needed it to be commited somewhere. But for the website, I'm not sure yet.

**Comment by MattIPv4** [comment]
Ah yeah, that might be interesting if we have it in Algolia but not in package data for the rest of the site. You'll be able to search on the site and find it but then clicking through will return a 404. (The API will also do the same, where it'll appear in `/libraries` but not `/libraries/<library>`)

**Comment by xtuc** [comment]
@MattIPv4 that's a good point. We will need to think about that and we can follow up on Slack.

> I noticed that we have regressions between the glob implementation in js and the one I found in Golang

I think I was wrong, based on https://github.com/cdnjs/tools/pull/4 the glob patterns are consistent between JS and Go implementation, which is good news.

As shown by https://github.com/cdnjs/tools/pull/4/files#diff-b910bc898c102b4ea1abace39dcecac3R141: `/**/!(*.common.*|*.html)` doesn't match `/a.js` (files in root dir don't match, files in sub dirs match). So my change to the package's pattern still make some sort of sense.

**Comment by MattIPv4** [comment]
The glob should match correctly: https://www.digitalocean.com/community/tools/glob?glob=%2A%2A%2F%21%28%2A.common.%2A%7C%2A.html%29&tests=VueBootstrapTypeahead.umd.min.js&tests=VueBootstrapTypeahead.css&tests=VueBootstrapTypeahead.umd.js.map&tests=VueBootstrapTypeahead.common.js.map&tests=VueBootstrapTypeahead.umd.js&tests=VueBootstrapTypeahead.common.js&tests=VueBootstrapTypeahead.umd.min.js.map&tests=demo.html

**Comment by xtuc** [comment]
Interesting, then there might be a difference between these two implementations

**Pull request merged**
