### PR TITLE
Update tween.js auto-update config

### LINKED ISSUE #11595: [Request][author] Update the auto-update config of tween.js
I want the latest versions of tween.js available on cdnjs. What is the process for adding a new version to cdnjs? Currently the latest version available is 16.7.1, but we now have a 16.10.0 version.

https://cdnjs.com/libraries/tween.js

### PR DESCRIPTION
**Pull request by sufuf3**
close #11595
Pull request for issue: #11595
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/tweenjs/tween.js/
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/@tweenjs/tween.js
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 194
   - Count of stars: 4422
   - Count of forks: 730
 * NPM download stats (optional):
   - Downloads in the last day: 334
   - Downloads in the last week: 991
   - Downloads in the last month: 2,441

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@dakshshah96 @cdnjs/intern3 
Please help me review this PR, Thank you.

**Comment by PeterDaveHello** [comment]
@sufuf3 why did you ignore question from @extend1994 but keep requesting new reviews?

**Comment by sufuf3** [comment]
@extend1994 sorry. I think the missing versions will be automatically added via auto-update config.

@cdnjs/intern3 @cdnjs/active-contributor I updated the commit message.
Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@extend1994 I updated the detailed commit message, many thanks.

A question is the files of v16.12.0 and v17.1.0 seem as same with each other. The different part is the version field of `package.json`.
So we still add v16.12.0?
If the author does not use git tag at v16.12.0, maybe we don't need to host v16.12.0.
What do you think?

Please help me review this PR, Thank you.

**Comment by sufuf3** [comment]
@cdnjs/intern3 @cdnjs/active-contributor I updated the commit message.
Please help me review this PR, Thank you.

**Comment by PeterDaveHello** [comment]
The version `0.0.0-development` on npm should be ignored.

**Pull request merged**
