### PR TITLE
[new] add jquery-lazyload-any@0.2.3 with git auto-update, close #4978

### LINKED ISSUE #4978: [Request] LazyLoad Any
LazyLoad Any
https://github.com/emn178/jquery-lazyload-any

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 , I add a new lib with git auto-update from the request #4978
repo: https://github.com/emn178/jquery-lazyload-any
Would you mind checking this PR for me? Thank you~ :-)

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `18`, Star `155`, Fork `38`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by maruilian11** [comment]
@Amomo i wonder in this case we don't need to keep the file structure?

**Comment by PeterDaveHello** [comment]
Wrong structure, inconsistency problem between real files and the filemap ...

**Comment by Amomo** [comment]
Sorry for my mistake.😰
@maruilian11 I have corrected my commit, could you take a look?
Thank you~ :-D

**Comment by maruilian11** [comment]
@Amomo sorry, i thought we only need to keep the structure when the files are under the `dist`.
@PeterDaveHello i think it's ok.

**Comment by PeterDaveHello** [comment]
I think, we could just add the minified file, as it's not a very popular lib, hosting without src is fine.

**Comment by Amomo** [comment]
Ok~ I have fix it~
Hi @maruilian11 I have modified it and rebased to latest master branch.
Could you take a look again? Thank you~ :-D

**Comment by maruilian11** [comment]
@PeterDaveHello do u mean if lib's popularity is not enough and its min file and `.js` are under the separate file, then we can just take the min file?
btw, i think this PR is ok.

**Pull request merged**
