### PR TITLE
upgrade jqModal with v1.3.0 and add git autoupdate, close #5325

### LINKED ISSUE #5325: [Request] Upgrade jqModal
**Library name:** jqModal
**Git repository url:** https://github.com/briceburg/jqModal
**Official homepage:** http://jquery.iceburg.net/jqModal/
**Wanna say something? Leave message here:** This library is already hosted on cdnjs (https://cdnjs.com/libraries/jqModal, last version from 03/01/2009), but the author changed homepage url and moved to GitHub several years ago. It's still being developed.

### PR DESCRIPTION
**Pull request by maruilian11**
@Piicksarn could u plz help me check this PR for #5325? thank you~

### CODE REVIEW

**Comment by Piicksarn** [comment]
@maruilian11, missing `package.json` in the PR!
I will check again when you add the package.json.:ok_woman:

**Comment by maruilian11** [comment]
@Piicksarn haha i found it after i sent the PR haha
i will correct it later~ sorry~

**Comment by maruilian11** [comment]
@Piicksarn i have corrected the problem, could u help me check it again? thank you very much!

**Comment by Piicksarn** [comment]
@maruilian11, you need to show the library name in the second commit~:)

**Comment by maruilian11** [comment]
@Piicksarn i have modify the commit msg, could u help me check it again? thank u~

**Comment by Piicksarn** [comment]
* [ ] `Not found on cdnjs repo` --> *This PR is not for adding a new lib*
* [x] No already exist issue and PR
* [ ] Notable popularity ---------------> *see #5325*
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)
* [x] Has valid tags for each versions (for git auto-update)
* [x] Auto-update setup
* [x] Auto-update target/source is valid.
* [x] Auto-update filemap is correct.

**Comment by PeterDaveHello** [comment]
What's the reason why to bump version in 3a19ea1 but not in 857a226?

**Comment by maruilian11** [comment]
@Piicksarn could u help me check it again? thank u~

**Comment by Piicksarn** [comment]
I think it's fine!
@PeterDaveHello, would you take a look on the pr?
Thank you!

**Pull request merged**
