### PR TITLE
[new] [author] add FlipDiv

### PR DESCRIPTION
**Pull request by kireerik**
source: https://github.com/kireerik/FlipDiv

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Ha, same issue I think, possible to remove old tags in repo? thanks.

**Comment by kireerik** [comment]
Thank you for your feedback! I removed them. Is it okay that the lib's first release is 1.5.0?

**Comment by PeterDaveHello** [comment]
Sure, I'm going to merge now!

**Comment by kireerik** [comment]
Thank you!

**Comment by PeterDaveHello** [comment]
No problem.

**Comment by kireerik** [comment]
Why [FlipDiv's page](https://cdnjs.com/libraries/FlipDiv) on cdnjs.com not showing details? (The [minimized js file](http://cdnjs.cloudflare.com/ajax/libs/FlipDiv/1.5.0/FlipDiv.min.js) is available.)

**Comment by PeterDaveHello** [comment]
What's detail?

**Comment by kireerik** [comment]
The site was blank without information. Now it is there.

**Comment by PeterDaveHello** [comment]
okay

**Pull request merged**
