### PR TITLE
adding json-schema-faker

### PR DESCRIPTION
**Pull request by ducin**
I would like to ask you to add json-schema-faker to cdnjs. Below are the informations I found in other PRs and issues. Please let me know if I need to do anything more.

PS cloning the repo is quite tough :disappointed: 

*Library name*: json-schema-faker
*Git repository url*: https://github.com/json-schema-faker/json-schema-faker
*npm package url(optional)*: json-schema-faker
*License(s)*: the MIT license
*Official homepage*: json-schema-faker.js.org

*Watch* 11
*Star* 202
*Fork* 20

### CODE REVIEW

**Comment by drewfreyling** [comment]
You are missing `filename` from `package.json`

**Comment by ducin** [comment]
Hi @drewfreyling, sorry for the error. I just included the "filename" attribute. Please let me know if I should do anything further.

**Comment by ducin** [comment]
I'm sorry for so many commits... but it's really difficult to commit anything having 23GB repo locally. I'm waiting several minutes for a `git status` command. I'll do my best to do as little commits as possible... :disappointed:

**Comment by PeterDaveHello** [comment]
Hi @ducin,

Please take a look at this, it'll help:
https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md

**Comment by PeterDaveHello** [comment]
I'll need you to squash/fixup them into only one commit, it'll be great if you would like to use npm auto-update instead of git auto-update, our git auto-updater is slower.

**Comment by ducin** [comment]
@PeterDaveHello thank you so much, I'l do what you suggested and asked me to (both the sparse checkout as well as squashing). I've got 2 questions:
* do you want me to drop this (#6844) pull request and start a new one? I never tried a `squash` and `push --force` into a pull request, don't know what will be the result. If corrupted, as I assume, I might just open a new one.
* I'm trying to work with cdnjs for the first time. And I think it's really frustrating to get over all those things and, you know, it's not about the size itself, but about poor documentation/guides. The main cdnjs readme is missing very important information. You point to an issue with the discussion at first point instead of writing just few sentences for newcomers on what to do (and the discussion might be linked *for your reference*, not as something everybody has to read. Moreover, the content of `package.json` was completely unclear for me until I looked at circleCI test output. And then I got to know that there are some scripts for validation. So what I suggest is that your repo is missing a good readme *very very much*. I think it's not only me having problems, since I spent significant amount of time trying to find relevant information and despite that I fell into many trouble. But that's just my opinion :-) I expect a good readme would generate a lot less repetative problems in future :)

**Comment by PeterDaveHello** [comment]
@ducin 
1. Feel free to reopen or fix this, it's up to you, if you wanna try to fix this one, I'll do my best to help you, maybe you'll learn some skills about git rebase, what do you think?
2. Sorry for the poor documentation, though I'm the main maintainer of cdnjs, I'm also still a full time student with not so good English skills, there are many issues to be solved, to improve the document is still on my TODO list, maybe you can help us improve our document(CONTRIBUTING.md and README.md) be better, I'll really appreciate it.

**Comment by ducin** [comment]
1. Well, I have done `git rebase -i` dozens of times, but never on existing github pull request. Was afraid not to break it. But I can see github is smart enough to notice the changes and overwrite entire PR. Cool. So I've already force-pushed squashed commits. Oh my God, that was a tough one :)

**Comment by PeterDaveHello** [comment]
Thanks @ducin

**Comment by ducin** [comment]
thank you!

**Pull request merged**
