### PR TITLE
Add canvasXpress@13.1 w/ git auto-update

### LINKED ISSUE #9334: [Request] CanvasXpress
**Library name: canvasXpress** 
**Git repository url: https://github.com/neuhausi/canvasXpress**
**npm package url(optional):** 
**License(s): GLP3**
**Official homepage: http://canvasxpress.org/html/index.html**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #9334 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/neuhausi/canvasXpress
 * Official website (optional, not the repository): http://canvasxpress.org/html/index.html
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 14
   - Count of watchers: 142
   - Count of forks: 6
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9334, cc @neuhausi

### CODE REVIEW

**Comment by extend1994** [comment]
@PeterDaveHello please help review this pull request, thank you.

**Comment by PeterDaveHello** [comment]
Looks like there is no valid git tag in the repository which means the git auto-update mechanism will not work on it, @extend1994 would you please confirm with its author?

**Comment by extend1994** [comment]
@PeterDaveHello Do you mean [this](https://github.com/neuhausi/canvasXpress/tags) ?

**Comment by PeterDaveHello** [comment]
Correct 💯

**Comment by extend1994** [comment]
Check the valid tag [here](https://github.com/neuhausi/canvasXpress/issues/8).

**Comment by extend1994** [comment]
According to the latest version, I changed the title of pull request and commit message.
@PeterDaveHello please help me review this pull request, thank you.

**Comment by PeterDaveHello** [comment]
@extend1994 well done.

**Pull request merged**
