### PR TITLE
Add license of dd_belatedpng, cc #5500

### PR DESCRIPTION
**Pull request by NiniHsu**
Reference: http://www.dillerdesign.com/experiment/DD_belatedPNG/

### CODE REVIEW

**Comment by NiniHsu** [comment]
@kennynaoh please help me check this PR.
Thank you!

**Comment by kennynaoh** [comment]
@NiniHsu I think `review` is much better than `check`, you can use it next time. Thanks!

**Comment by kennynaoh** [comment]
LGTM
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
LGTM

**Comment by NiniHsu** [comment]
@kennynaoh I will remember next time. Thanks!

**Pull request merged**
