### PR TITLE
Add license of ext-core, cc #5500

### PR DESCRIPTION
**Pull request by dada0423**
https://github.com/MikhailTatsky/ext-core/blob/ext-core-3.1/src/ext-core.jsb#L2
@pvnr0082t 
Please review this

### CODE REVIEW

**Comment by dada0423** [comment]
@pvnr0082t 
Please review this "add liense work"

**Comment by pvnr0082t** [comment]
@dada0423 If you just add license for a library, you can remove the pull request template. BTW, you should wait for CI test finished first then tag me.

**Comment by pvnr0082t** [comment]
LGTM
@cdnjs/intern2 Please help review this pull request, thank you.

**Comment by x09326** [comment]
LGTM

**Pull request merged**
