### PR TITLE
import ngprogress via git auto-update & update to v1.1.3

### PR DESCRIPTION
**Pull request by x09326**
PR for #9336 
@pvnr0082t @kennynaoh 
Please help me review it, thanks.

Manually add old versions of ngprogress from git repo because auto-update
can't get them, cc #9336

### CODE REVIEW

**Comment by pvnr0082t** [comment]
Test failed.

**Comment by x09326** [comment]
@pvnr0082t 
The test failed due to the filename has changed.
I have modified the filename from `ngProgress.min.js` to `ngprogress.min.js`.
And I delete the part cc to the author.

**Comment by pvnr0082t** [comment]
> - use `import deepstream.io-client-js via npm auto-update` as title would be better. Same as commit message.
> - You can add all missing versions in one commit.

What's your reply about these two? @x09326

**Comment by x09326** [comment]
@pvnr0082t 
I have modified the commit message and title.
Please help me review it, thanks.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by x09326** [comment]
ping @kennynaoh 
Please help me review it.

**Comment by kennynaoh** [comment]
Because `v1.0.6` and `v1.1.0` are exist on cdnjs, do we also need to add these two versions?
Or it doesn't affect.
Thanks!

**Comment by pvnr0082t** [comment]
I think @x09326 didn't commit them. v1.0.6/1.1.0 just exist already. @kennynaoh

**Comment by kennynaoh** [comment]
OK
@x09326 
Please rebase to the latest master br.
Thanks!

**Comment by x09326** [comment]
@kennynaoh @pvnr0082t 
I have rebased to the latest master branch.
Please help me review it, thanks.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
What's the reason why 9dd5694eb497d24e6897274749f794255aa3cb91 only bumped the version without files? We should make every commit pass the test, that is not good at all.

**Comment by x09326** [comment]
@PeterDaveHello 
So I need to add version 1.1.3 in that commit right?

**Comment by PeterDaveHello** [comment]
@x09326 Of course.

**Comment by x09326** [comment]
@kennynaoh @pvnr0082t 
I have moved 1.1.3 version in the added version commit and rebased with the latest master branch.
Please help me review it, thanks.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@cdnjs/intern2 didn't we talk about this before? I remember that we did.

**Comment by pvnr0082t** [comment]
Sorry for didn't review commit by commit.

**Comment by x09326** [comment]
@pvnr0082t @kennynaoh 
I have modified the filename with v1.1.3.
Please help me review it, thanks.

**Comment by PeterDaveHello** [comment]
@x09326 let use an one-line commit message for it:
`add ngprogress v1.1.3 w/ filename update`

**Comment by x09326** [comment]
@kennynaoh @pvnr0082t 
I have modified the commit message.
Please help me review it, thanks.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
where is @kennynaoh ?

**Comment by kennynaoh** [comment]
@x09326 
Sorry for late response.
Please rebase to the latest master br.
Thanks!

**Comment by x09326** [comment]
@kennynaoh 
I have rebased it.
Please help me review it, thanks.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
@x09326 two things need to be done.

1. Transfer to git auto-update config
2. Add symbolic links in v1.1.2/1.1.3 to make sure the filename consistency with the old versions.

Thanks.

**Comment by x09326** [comment]
@PeterDaveHello 
Sorry, I don't understand how to adding symbolic links.
Could you explain it more clearly?
Thanks.

**Comment by PeterDaveHello** [comment]
@x09326 Something like ln -s origin.js new.js, 
Take this as an example:
ls -l documents/CONTRIBUTING.md

**Comment by x09326** [comment]
@kennynaoh @pvnr0082t 
I have changed to git auto-update and added symbolic links for v1.1.2/v1.1.3.
Please help me review it, thanks.

**Pull request merged**
