### PR TITLE
add ngHandsontable v0.7.0

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/handsontable/ngHandsontable
**Watch 45
  Star 282
 Fork 88**
@Amomo could u help me check this PR for #6256 ? thank you!
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
What's the reason why to add such an old version?

**Comment by maruilian11** [comment]
@Piicksarn could u help me check this PR? thank you~

**Comment by PeterDaveHello** [comment]
We have a small problem here, please rebase with our latest master branch, sorry for the inconvenient caused.

**Comment by maruilian11** [comment]
@Piicksarn i have rebased it~

**Pull request merged**
