### PR TITLE
Update auto-update filemap of oojs-ui

### PR DESCRIPTION
**Pull request by sufuf3**
Pull request for issue: #11350
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
**Git repository url:** https://phabricator.wikimedia.org/diffusion/GOJU
**npm:** https://www.npmjs.com/package/oojs-ui
**License (List them all if it's multiple):** MIT
**Official homepage:** https://www.mediawiki.org/wiki/OOjs_UI
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:
   - Count of stars:
   - Count of forks:
 * NPM download stats (optional):
   - Downloads in the last day: 675
   - Downloads in the last week: 1406
   - Downloads in the last month: 3180

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@dakshshah96 @cdnjs/intern3 please help me review this PR, thanks.

**Comment by sufuf3** [comment]
@dakshshah96 You're right.
We don't need to host it.
But with `"**/*.!(txt|md)"` I didn't get the `LICENSE-MIT` file with auto-update. 
I think because `LICENSE-MIT` can't match `.`
Could you test for me? I afraid that I didn't take note it.

**Comment by dakshshah96** [comment]
@sufuf3 You're right, my bad! `LICENSE-MIT` won't be fetched with the file rule you've used.

**Comment by sufuf3** [comment]
Use "Update" instead of "Fix" in commit message.

**Pull request merged**
