### PR TITLE
Adding Sortable v1.0.1

### PR DESCRIPTION
**Pull request by RubaXa**
Sortable
===
Minimalist JavaScript library for reorderable drag-and-drop lists on modern browsers and touch devices. No jQuery. Supports AngularJS, React, Meteor and any CSS library, e.g. Bootstrap.

 - https://github.com/rubaxa/Sortable
 - http://rubaxa.github.io/Sortable

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
We have Sortable already, please update that existing one instead of adding a new folder, thanks.

**Comment by RubaXa** [comment]
But where?

**Comment by RubaXa** [comment]
O! So sorry, i'm find.
https://github.com/cdnjs/cdnjs/blob/5b2dcf5aa6ea14701c3f76aec9784cd1cb5a6012/ajax/libs/Sortable/package.json

**Comment by PeterDaveHello** [comment]
Yeah :)

**Pull request closed without merging**
