### PR TITLE
add: dummyjs

### PR DESCRIPTION
**Pull request by spyshiv**
**Library name: Dummyjs** 
**Git repository url: https://github.com/spyshiv/dummyjs**
**npm package url(optional):** 
**License(s):GNU GENERAL PUBLIC LICENSE Version 2, June 1991**
**Official homepage:http://spyshiv.github.io/dummyjs/**
**Wanna say something? Leave message here:**Dummyjs is js library to generate dummy words, dummy sentences and dummy paragraphs which are very useful while writing a webpage and instead of content you have to write some dummy text like...lorem ipsum dolor sit etc..using dummyjs can save the much time of web developer

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@spyshiv we need a higher popularity to add lib, would you please send this PR later?

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by maruilian11** [comment]
Hi @spyshiv, 
Thanks for suggestion, however, this library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

this issue will be closed if there is no any response in next 7 days, if there is any other good reason to add this lib, we may discuss to add it.

**Comment by spyshiv** [comment]
Closing this.

**Pull request closed without merging**
