### PR TITLE
[new] Add bigSlide.js v0.9.1 with git auto-update, close #5154

### LINKED ISSUE #5154: [Request] Add bigSlide.js
**Library name:** bigSlide.js
**Git repository url:** https://github.com/ascott1/bigSlide.js
**npm package url(optional):** https://www.npmjs.com/package/bigslide
**Official homepage:** http://ascott1.github.io/bigSlide.js/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by Piicksarn**

### CODE REVIEW

**Comment by Piicksarn** [comment]
@Amomo, this pr is for adding a new lib bigSlide.js v0.9.1 with git auto-update.
would you please checking the pr and here is Git repository url: https://github.com/ascott1/bigSlide.js
Thank you!

**Comment by Amomo** [comment]
@PeterDaveHello I think it is fine.

**Comment by PeterDaveHello** [comment]
Seems the author forgot to bump the version number in the comment, would you please manually update 0.9.0 to 0.9.1 in these js files' comment?

**Comment by Piicksarn** [comment]
@Amomo I have it corrected and need your help for check it again~
Thank you!

**Comment by Amomo** [comment]
I think these two commits are good.
@PeterDaveHello could you take a look?

**Comment by PeterDaveHello** [comment]
I think you should explain in detail of the version number, or the easier way, just squash them into one commit.

**Comment by Piicksarn** [comment]
@Amomo would your please help me for check out the pr?
Thank you!

**Comment by Amomo** [comment]
I think it is fine. @PeterDaveHello could you take a look? Thank you~

**Comment by PeterDaveHello** [comment]
I can't recognize the lib you modified in this commit message:
> bump the version number from 0.9.0 to 0.9.1 in js files' comment

Let's just do it in the same commit.

**Comment by Piicksarn** [comment]
@Amomo would you mind to check it again :^P
is the commit line suitable for the PR?
Thank you!!

**Comment by Amomo** [comment]
@Piicksarn Your wording is a little strange(?)
I think "bump version number to 0.9.1 in comment field of bigSlide.js." may be fine.
or... you can just combine the two commits. That also works.
I hope this could be help.

**Comment by Piicksarn** [comment]
@Amomo I decide to squash them into one commit. :^P
Thank you !

**Comment by Piicksarn** [comment]
@Amomo, I have it rebased to master~
would you please check it again?
Thack you ~

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine.
Could you take a look? Thank you~

**Comment by PeterDaveHello** [comment]
Nice.

**Pull request merged**
