### PR TITLE
add markdown-it-footnote@3.0.0 w/ npm autoupdate

### LINKED ISSUE #8588: [Request] Add markdown-it-footnote
**Library name:** markdown-it-footnote
**Git repository url:https://github.com/markdown-it/markdown-it-footnote
**npm package url(optional):** https://www.npmjs.com/package/markdown-it-footnote
**License(s):MIT
**Official homepage:https://github.com/markdown-it/markdown-it-footnote
**Wanna say something? Leave message here:
Markdown-it is already in cdnjs, but many plugins of it are not. 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8588 
@x09326 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/markdown-it/markdown-it-footnote
 * Official website (optional, not the repository): https://markdown-it.github.io/
 * NPM package url (optional): https://www.npmjs.com/package/markdown-it-footnote
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 13
   - Count of watchers: 6
   - Count of forks: 9
 * NPM download stats (optional):
   - Downloads in the last day: 104
   - Downloads in the last week: 898
   - Downloads in the last month: 3207

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8588, cc @puzrin

### CODE REVIEW

**Comment by x09326** [comment]
@pvnr0082t 
I think the ```homepage``` is a demo page.

**Comment by puzrin** [comment]
I'd suggest link to github page as homepage if such link is mandatory. Readme is a good start point, IMHO.

**Comment by puzrin** [comment]
I mean, demo collaborates a lot of extensions, and point to main project. That can be a bit confusing if user expects info about footnotes.

**Comment by PeterDaveHello** [comment]
@puzrin Thanks.

**Comment by pvnr0082t** [comment]
@PeterDaveHello So we use https://github.com/markdown-it/markdown-it-footnote/blob/master/README.md as homepage here?

**Comment by PeterDaveHello** [comment]
@pvnr0082t So there is no need to set homepage.

**Comment by pvnr0082t** [comment]
@x09326 I have remove `homepage`. Please help me review again, thank you.

**Pull request merged**
