### PR TITLE
Update bootstrap-table v1.7.0

### PR DESCRIPTION
**Pull request by wenzhixin**
ref: #4510
ref: https://github.com/wenzhixin/bootstrap-table/issues/730

### CODE REVIEW

**Comment by wenzhixin** [comment]
Source here: https://github.com/wenzhixin/bootstrap-table/tree/master/dist

**Comment by PeterDaveHello** [comment]
Would you please squash them into a commit as our document said? And I think you touched too many files here, Thanks.

**Comment by drewfreyling** [comment]
closing due to no response.

**Comment by PeterDaveHello** [comment]
https://cdnjs.com/libraries/bootstrap-table

**Pull request closed without merging**
