### PR TITLE
[author] [new] adding v0.1.5 highlight-lisp.js and accompanying CSS

### PR DESCRIPTION
**Pull request by orthecreedence**
Origin: https://github.com/orthecreedence/highlight-lisp

Thank you!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hi @orthecreedence,

Would you please setup auto-update config for it and add minified css also?

We currently support npm (in readme) and git auto-update(#3638).

Thanks!

**Comment by int64ago** [comment]
Actually, I'm always confused, how can auto-update work in furture if adding minified file by hand

**Comment by PeterDaveHello** [comment]
It's okay, the source files will be automatically fetched, that's enough.

**Comment by drewfreyling** [comment]
@PeterDaveHello Are you happy if I merge this then?

**Comment by PeterDaveHello** [comment]
hmmmm ... I'll pick it.

**Comment by PeterDaveHello** [comment]
Hi @orthecreedence,

Seems there is no any tag in your git repo, our git auto-update will need, could you set it up?

Thanks and sorry for the late reply.

**Comment by orthecreedence** [comment]
Hello, I'm not well versed on any of this...where do I add the tag?

**Comment by PeterDaveHello** [comment]
It depends on your git client I think, here is the doc:
https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by orthecreedence** [comment]
Ok, added tag v0.1.5 to the base repo (https://github.com/orthecreedence/highlight-lisp).

**Comment by PeterDaveHello** [comment]
Can you squash them into only one commit and rebase with our latest master branch? Thanks.

**Comment by drewfreyling** [comment]
Closing due to no response.

**Pull request closed without merging**
