### PR TITLE
Add hideseek-mod via single package.json w/ npm auto-update

### PR DESCRIPTION
**Pull request by maxwroc**
# Pull request template for new library

Pull request for issue: #13435
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

## Profile of the lib

* Git repository (required): https://github.com/maxwroc/HideSeek-Mod
* Official website (optional, not the repository): http://maxwroc.github.io/HideSeek-Mod/
* NPM package url (optional): https://www.npmjs.com/package/hideseek-mod
* License and its reference: Apache-2.0
* GitHub / Bitbucket popularity (required):
  * Count of watchers: 1
  * Count of stars: 0
  * Count of forks: 80
* NPM download stats (optional):
  * Downloads in the last day: 173
  * Downloads in the last week: 442
  * Downloads in the last month: 1.2K

## Essential checklist

* [x] I'm the author of this library
  * [x] I would like to add link to the page of this library on CDNJS on website / readme
* [x] This lib was not found on cdnjs repo
* [x] Doesn't already exist / has duplicate issue and PR
* [x] The lib has notable popularity
  * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [x] More than 800 downloads stats per month on npm registry
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [x] Has valid tags for each versions (for git auto-update)
* [x] Auto-update setup
* [x] Auto-update target/source is valid.
* [x] Auto-update filemap is correct.

## Git commit checklist

* [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [x] The parent of the commit(s) in the PR is not older than 3 days.
* [x] Pull request is sent from a non-master branch with a meaningful name.
* [ ] Separate unrelated changes into different commits.
* [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [x] Close corresponding issue in commit message
* [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by maxwroc** [comment]
@dakshshah96 May I ask you to review this small change please. Thank you in advance!

**Comment by maxwroc** [comment]
Hi @sufuf3, can you review this change? Please let me know if anything is missing or not right. Thank you in advance!

**Comment by maxwroc** [comment]
@PeterDaveHello can you help review this change - thank you in advance

**Comment by PeterDaveHello** [comment]
@maxwroc I'll take a look when I have time, sorry for the delay

**Comment by maxwroc** [comment]
@PeterDaveHello gentle reminder

**Comment by maxwroc** [comment]
@PeterDaveHello please... :)

**Pull request merged**
