### PR TITLE
add abr4xas-twemoji-awesome v1.0.4

### LINKED ISSUE #7663: [Request] Add twemoji-awesome
**Library name**: twemoji-awesome
**Git repository url**: https://github.com/abr4xas/twemoji-awesome
**npm package url(optional)**: https://www.npmjs.com/package/twemoji-awesome
**License(s)**: MIT
**Official homepage**:

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #7663 
@x09326 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/abr4xas/twemoji-awesome
- Official website (optional, not the repository):
- NPM package url (optional): https://www.npmjs.com/package/twemoji-awesome
- GitHub / Bitbucket popularity (required):
  - Count of stars: 1
  - Count of watchers: 2
  - Count of forks: 48
- NPM download stats (optional):
  - Downloads in the last day: 0
  - Downloads in the last week: 140
  - Downloads in the last month: 140
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [ ] The lib has notable popularity
  - [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [ ] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

with npm autoupdate config, close #7663, cc @abr4xas

### CODE REVIEW

**Comment by x09326** [comment]
It's a little strange.

First, this is forked from https://github.com/ellekasai/twemoji-awesome.
Second, the line 4 of file ```twemoji-awesome.css``` said the version is 2.0.0.

@PeterDaveHello what should we do in this case?

**Comment by PeterDaveHello** [comment]
@x09326 you can for it yourself, you'll get the same result.
The problem here is the popularity ...

**Comment by abr4xas** [comment]
Hello, 

Recently published the v1.0.4
Yes, it is a fork of Ellekasai but now includes all emoji that twitter offers.

**Comment by pvnr0082t** [comment]
@x09326 I have updated version info to v1.0.4. Please help me review again, thank you.

**Comment by x09326** [comment]
You can add ```"http://abr4xas.github.io/twemoji-awesome/"``` as the ```homepage```.

**Comment by PeterDaveHello** [comment]
@pvnr0082t @x09326 as I said, the problem is the popularity ...

**Comment by x09326** [comment]
@PeterDaveHello 
But this project forked from [here](https://github.com/ellekasai/twemoji-awesome).
And it has enough popularity.

**Comment by PeterDaveHello** [comment]
Everybody can fork a popular project, but doesn't been anything, right?

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by abr4xas** [comment]
Hi there,

Need some help with this? :smile:

**Comment by pvnr0082t** [comment]
@abr4xas Thanks for your active, but the problem of this PR is that the library does not achieve the popularity threshold.

**Comment by sufuf3** [comment]
@PeterDaveHello this library doesn't have enough popularity.
What can we do for this PR?
close this PR or wait for this lib has enough popularity? 

Thank you.

**Pull request closed without merging**
