### PR TITLE
[new] add Swiper by iDangero.us

### PR DESCRIPTION
**Pull request by kireerik**
origins:
- https://github.com/nolimits4web/Swiper/blob/master/dist/idangerous.swiper.min.js
- https://github.com/nolimits4web/Swiper/blob/master/package.json

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I found that there are 3 files under `dist` but you only added 1, please add 2 others, thanks.

**Comment by kireerik** [comment]
Okay, I will add them too.

**Comment by PeterDaveHello** [comment]
In fact, you can just use force push to update a PR, instead of keep opening new PRs.

**Comment by kireerik** [comment]
Thank you for mentioning this! I am really sorry for creating multiple pull requests with the same issue. I am a little newbie collaborating on GitHub. Hope everything will fine for this time. ;)

**Pull request closed without merging**
