### PR TITLE
Add license field for crossfilter, #6324

### PR DESCRIPTION
**Pull request by Asu4ni**
source: https://github.com/square/crossfilter/blob/master/LICENSE
#6324

### CODE REVIEW

**Comment by Asu4ni** [comment]
I have also tried to use command line to do this, but it seemed I had to copy the whole directory first. Is it necessary? Or I'm doing it wrong. (The files seemed big and took so long to download, so I cancelled it before it was done.)
BTW, "cookiejar" hasn't been checked but there's been license field in the package file if I didn't get it wrong.

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by Amomo** [comment]
Hi @Asu4ni , thanks for your contribution. :-D

You can try to see our document [sparseCheckout.md](https://github.com/cdnjs/cdnjs/blob/master/sparseCheckout.md), it would help you to pull down part of our repo. 
 It's welcome to send more PR to us. :smile: You can tag me if you met any problems.

And, I have checked the licence field of `"cookiejar"`.
Yes, the license field is realy exist in the package.json, thanks for your report! ^^

**Comment by Asu4ni** [comment]
OK! but you forgot to check the one I have updated. haha

**Comment by Amomo** [comment]
checked, thank you!

**Pull request merged**
