### PR TITLE
Add jsPlumb v2.3.0 thru v2.5.5

### PR DESCRIPTION
**Pull request by sfmskywalker**
Added jsPlumb v2.3.0 thru v2.5.5.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I'll take care of it.

**Comment by PeterDaveHello** [comment]
Done in
f14fde6f72cc0e768abf8e9187cd6da2ae4fbdf9 & 6b109df9752fd753501de0a7655700af0f59ecff

**Comment by sfmskywalker** [comment]
Thank you! It's my first contribution to this project. Next time I'll create a separate branch as instructed.

**Comment by PeterDaveHello** [comment]
@sfmskywalker 👍

**Pull request closed without merging**
