### PR TITLE
Enrich  backbone.layoutmanager's package.json(field: license)

### PR DESCRIPTION
**Pull request by iwdmb**
#5500 
license link: [https://github.com/tbranyen/backbone.layoutmanager/blob/master/LICENSE](https://github.com/tbranyen/backbone.layoutmanager/blob/master/LICENSE)

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I didn't see any sentences talk about MIT, anything wrong?

**Comment by iwdmb** [comment]
about MIT License ...

[https://opensource.org/licenses/MIT](https://opensource.org/licenses/MIT)

Please review, thanks!

**Comment by PeterDaveHello** [comment]
I meant I didn't see "MIT" in that project, though the content is the same as MIT, would you please open an issue ticket to confirm with its author? Thanks!

**Comment by iwdmb** [comment]
[https://github.com/tbranyen/backbone.layoutmanager/search?utf8=%E2%9C%93&q=MIT](https://github.com/tbranyen/backbone.layoutmanager/search?utf8=%E2%9C%93&q=MIT)

**backbone.layoutmanager.js may be freely distributed under the MIT license.**

**Comment by PeterDaveHello** [comment]
Oh, okay, thank you very much!

**Pull request merged**
