### PR TITLE
[new] add wavedrom v1.2.0-1.2.4 w/npm autoupdate

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 this PR is for #6849.
I add `wavedrom` at `v1.2.3` and add `npm` auto-update config in its package.json.

"WaveDrom.js" is minified file.
And, I think "wavedrom.max.js" is its source file, so I didn't minify these two files.

Would you mind checking this PR for me? Thank you~ :-D

# Profile of the lib
 * Git repository (required): https://github.com/drom/wavedrom
 * NPM package url (optional): https://www.npmjs.com/package/wavedrom
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 30
   - Count of watchers: **212**
   - Count of forks: 34

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message.
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
https://github.com/drom/wavedrom#html-pages

**Comment by drom** [comment]
Thank you for the PR @Amomo : yes:
WaveDrom.js =  minified file.
wavedrom.max.js = not minified version of it.

I can generate to more files if you have specific guidelines for the file names. Like:
wavedrom.min.js -- for minified version.
wavedrom.js -- for the not minified version.

WaveDrom also requires one of skins to be available from here: 

https://github.com/drom/wavedrom/tree/master/skins

Two skins available now:

skins/default.js
skins/narrow.js

Can you publish these files together?

**Comment by PeterDaveHello** [comment]
@drom Thanks for your comment, WaveDrom.js + wavedrom.max.js is okay, but more libraries use libname.js + libname.min.js, you can consider to use it in the future.

**Comment by drom** [comment]
@PeterDaveHello I can rename wavedrom.js and wavedrom.min.js but what about skins?
Can you put skins on CDN?

skins/default.js
skins/narrow.js

**Comment by drom** [comment]
I just released v1.2.4 with the following files to share:

wavedrom.js
wavedrom.min.js
skins/default.js
skins/narrow.js

**Comment by PeterDaveHello** [comment]
Thanks @drom. @Amomo so let's add old versions manually, and apply the new auto-update config.

**Comment by Amomo** [comment]
@drom thanks for your advice.

@maruilian11 could you help me checking this PR? Thank you~

**Comment by maruilian11** [comment]
@PeterDaveHello i think this PR is ok.

**Comment by PeterDaveHello** [comment]
LGTM

**Pull request merged**
