### PR TITLE
Add jqGrid version 5.0.1

### PR DESCRIPTION
**Pull request by tonytomov**
The old plugins directory is removed and replaced with the new addons which is subdirectory of css and js .

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Assigned to @Amomo @maruilian11 to review this PR.

**Comment by tonytomov** [comment]
Hello,

Sorry to bother. I'm new to this. I can not see what is the problem. Could you please point me where to see the problem and fix it?

It is better to close the PR and create new?

Thank you

Kind Regards,
Tony

**Comment by PeterDaveHello** [comment]
Seems there was syntax error in package.json

**Comment by maruilian11** [comment]
hi, @tonytomov
when you add version 5.0.1, please also modify version field in package.json in one commit, or the test won't pass.

**Comment by tonytomov** [comment]
Hi @maruilian11 

Thanks. I have done these steps, but it seems there is a problem again

**Comment by PeterDaveHello** [comment]
I think you should rebase your branch with our latest master branch.

**Comment by maruilian11** [comment]
@tonytomov after `git rebase -i HEAD~5`, don't forget to git rebase master first~
hope this will help you :smiley:

**Comment by tonytomov** [comment]
Hello,

I have executed the command you suggested (I hope), but nothing changes.

Can you please instruct me step by step  (including the command ) what to do.
Sorry to to ask this, but I'm not very familiar with GitHub.

Would be better to delete everything and create the PR from the beginning?

Thank you very much for your support 

Kind Regards,
Tony Tomov

**Comment by PeterDaveHello** [comment]
> Would be better to delete everything and create the PR from the beginning?

I think it'll be obviously easier, but I'll be happy to help you "fix" this PR if you wanna learn.

**Comment by tonytomov** [comment]
Hello,

Thanks for the great support.

I do not like easy things. I want to learn.

Kind Regards

**Comment by PeterDaveHello** [comment]
So, can you tell me if you know how to fix the "conflicts" in git?

**Comment by PeterDaveHello** [comment]
because this PR is old and there are conflicts, you will need to sync with our master branch first, if you need instructions, you can take a look at one of my post: https://www.peterdavehello.org/2015/05/how-to-syncupdate-forked-repository-with-upstream/, after that try resolve the conflicts!

**Comment by tonytomov** [comment]
Using rebase upstream/maseter otput this error:
....
warning: squelched 3250 whitespace errors
warning: 3255 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging ajax/libs/jqgrid/package.json
Applying: Fix for package.json
Using index info to reconstruct a base tree...
M	ajax/libs/jqgrid/package.json
Falling back to patching base and 3-way merge...
Auto-merging ajax/libs/jqgrid/package.json
CONFLICT (content): Merge conflict in ajax/libs/jqgrid/package.json
Failed to merge in the changes.
Patch failed at 0002 Fix for package.json
The copy of the patch that failed is found in:
   /home/tony/cdnjs/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort"

**Comment by PeterDaveHello** [comment]
@tonytomov then you should open the file(s) it told about, and decide what's the contain you want, then continuing rebase.

Here are some docs have good explaination, I think I don't need to explane all the things again, but feel free to ask me if you need help!
https://help.github.com/articles/resolving-merge-conflicts-after-a-git-rebase/
https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/
http://githowto.com/resolving_conflicts

Cheers!

**Comment by tonytomov** [comment]
Have run
git rebase --continue
Applying: Fix for package.json
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
The status give me

git status
rebase in progress; onto a2a178f
You are currently rebasing.
  (all conflicts fixed: run "git rebase --continue")

Should I think that it is ok now

**Comment by PeterDaveHello** [comment]
@tonytomov so run git rebase --continue :+1` and push it!

**Comment by tonytomov** [comment]
Hello,

Sorry to ask again (excuse me for this) . Everything seems fine.
What is the next step? I don't see the 5.0.1

Kind Regards,
Tony Tomov

**Comment by PeterDaveHello** [comment]
Nope
> rebase in progress; onto a2a178f
> You are currently rebasing.
> (all conflicts fixed: run "git rebase --continue")

If you are done, please do `git push --force`

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by tonytomov** [comment]
Hello,
Thank you to be back to me.

Obviously, I need to start over. I will need you help at end of week when I'm ready to do this.

Thank you.

Tony

**Comment by tonytomov** [comment]
Hello,

Except [this](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) I couldn't find any other documentation for adding to cdnjs. Can you please point me to more detailed one. I want to start from the beginning.

Thank you for your support.

Kind Regards,
Tony

**Comment by PeterDaveHello** [comment]
@pvnr0082t can you please help @tonytomov here?

**Comment by pvnr0082t** [comment]
@PeterDaveHello Is anything I could help here? Should I directly help rebase it?

**Comment by PeterDaveHello** [comment]
@tonytomov what do you think?

**Comment by tonytomov** [comment]
Hello,
Thank you for the support.
I think it is ok.
Any help with a set of actions (command) I can do is welcome. If possible, please  guide me how to finish this .

Thank you.

Kind Regards,
Tony

**Comment by PeterDaveHello** [comment]
Okay, @pvnr0082t please help rebase with conflicts solving, thanks.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I have fixed in my local but I can't push it because of permission denied.  I think @tonytomov don't choose `Allow edits from maintainers` option at the right side.
By the way, @tonytomov you send this pull request from master branch. It will cause this PR never pass CI test. Please send a new pull request from non-master branch. Thanks.

**Comment by PeterDaveHello** [comment]
@pvnr0082t yes since the PR is old, maybe ask @tonytomov  to check the box first, then you can update it, then @tonytomov can use the old branch to create a new one, then send a new PR!

**Comment by PeterDaveHello** [comment]
I saw the invitation to have write access on https://github.com/tonytomov/cdnjs, @pvnr0082t did you receive that?

**Comment by pvnr0082t** [comment]
@PeterDaveHello Yes, I did.

**Comment by PeterDaveHello** [comment]
@pvnr0082t nice, let's fix it! 👍

**Comment by pvnr0082t** [comment]
@PeterDaveHello @tonytomov Okay, I fixed it. 
By the way, the branch `jqgrid` in your GitHub repo is the something I did wrong. :stuck_out_tongue: You can delete that.

**Comment by tonytomov** [comment]
@pvnr0082t 
Thanks. What I need to do?

**Comment by maruilian11** [comment]
@tonytomov We will wait for the CI test pass, then review the commit in this PR, If there is anything need to be changed, we will let you know, thank!

**Comment by maruilian11** [comment]
@pvnr0082t 
```
==========ERROR==========
Please do not send pull request from master branch!
You should create a new branch with meaningful name for pull request!
'Creating and deleting branches within your repository' Reference:
https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/
For the reason why we need to create a new branch for every pull request,
please refer to the GitHub Flow: https://guides.github.com/introduction/flow/index.html
==========ERROR==========
```

**Comment by PeterDaveHello** [comment]
@maruilian11 I have no reason why you posting this error, we all know about it, why don't you just explain what do you want here?

**Comment by PeterDaveHello** [comment]
Wrong file permission detected! @pvnr0082t I think you can help fix it 👍

**Comment by pvnr0082t** [comment]
File permission fixed.

**Comment by maruilian11** [comment]
@pvnr0082t this commit not just add v5.0.1, could you also help mention other info in commit msg? Thanks.

**Comment by tonytomov** [comment]
Hello,
First of all Thank you for the job you do.
For me now is little difficult to see exactly what is happen, but I hope to understand this later.

Currently we have version 5.2.0 and I hope I can add it without problems later.

Kind Regards,
Tony

**Comment by PeterDaveHello** [comment]
@pvnr0082t  let's fix the commit message and get it merged ASAP, thanks.

**Comment by tonytomov** [comment]
Hello,

I apologize for this, but what should I do po publish the (new) release?

**Comment by PeterDaveHello** [comment]
Hi @tonytomov, I wonder if you would like to send a new pull request or fix this one, with the correct git auto-update config? The npm package seems to be dated. Hope we can get this updated ASAP, Thanks!

**Comment by tonytomov** [comment]
Hello @PeterDaveHello ,

Which is the better one? Maybe to fix this and continue with automatic updates? or...

**Comment by PeterDaveHello** [comment]
@tonytomov I'm both fine :)

**Comment by tonytomov** [comment]
Let fix this one

**Comment by maruilian11** [comment]
Hi @tonytomov , Could you also provide `ui.multiselect.js`minified file in `js/minified` because we don't support partially minify in one directory.

**Comment by maruilian11** [comment]
Hi @tonytomov, 
Could you modify your PR to only change the package.json?
That will help us review fast.
And v5.2.1 will be added to cdnjs after few hours after this PR being merged.
We use `CC-BY-NC-3.0` which is the short identifier of Creative Commons Attribution Non Commercial 3.0.
https://spdx.org/licenses/CC-BY-NC-3.0.html

We won't add `ui.multiselect`, `jqDnR`,  `jqModal`, `jquery.contextmenu`, `jquery.searchFilter` and `jquery.tablednd` because they belong to other libraries, may already be hosted on cdnjs. For which hasn't be hosted, we will host them ASAP. 

Following is my recommended `package.json`:
```
{                                                                                                                                                                                    
  "name": "jqgrid",
  "filename": "js/jquery.jqGrid.min.js",
  "version": "4.6.0",
  "description": "jqGrid is an Ajax-enabled JavaScript control that provides solutions for representing and manipulating tabular data on the web.",
  "homepage": "http://www.trirand.com/blog/",
  "keywords": [
    "jQuery",
    "jqGrid",
    "JavaScript",
    "grid",
    "table",
    "pivot",
    "tree",
    "subgrid",
    "sorting",
    "paging",
    "editing",
    "grouping",
    "searching",
    "ajax"
  ],
  "license": "CC-BY-NC-3.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/tonytomov/jqGrid"
  },
  "author": {
    "name": "Tony Tomov",
    "url": "http://www.guriddo.net",
    "email": "tony@trirand.com"
  },
  "autoupdate": {
    "source": "git",
    "target": "git://github.com/tonytomov/jqGrid.git",
    "fileMap": [
      {
        "basePath": "",
        "files": [
          "css/**/!(ui.multiselect).+(css|map)",
          "js/**/!(jqDnR|jqModal|ui.multiselect).+(js|map)",
          "plugins/**/!(jquery.contextmenu|jquery.searchFilter|jquery.tablednd).+(js|css)"
        ]
      }
    ]
  }
```

**Comment by tonytomov** [comment]
Thank you. Sorry for the stupid question - How to do this change?
Note that I have change my computer and the my local copy is lost.

**Comment by tonytomov** [comment]
If possible, can you please do this on my behalf?

**Comment by maruilian11** [comment]
@tonytomov I have tried to help modify your commit, but seems that I have no permission to do with your master branch. You can use `git reset HEAD^ --soft` to uncommit the last commit. And please remember `git pull` our master branch to keep your commit behind too much commits on our latest master. Or you can consider open another branch to send the PR, then I will be allowed to help you modify your commits. Feel free to ask if you need.

**Comment by tonytomov** [comment]
@maruilian11 

I have added you a  write permissions to my repository

**Comment by PeterDaveHello** [comment]
I don't think we need additional permission to the origin repository here, the key point here is the branch for this PR is `master` branch, so it's better to send it through another branch.

**Comment by maruilian11** [comment]
@tonytomov Would you please open another branch and send the PR? I think it can be easily done by GitHub website GUI. 👍 I will help you modify the commit after the PR being opened.

**Comment by tonytomov** [comment]
I have created new branch and made a new PR. The branch is jqgridjs

**Comment by PeterDaveHello** [comment]
@tonytomov Thanks a lot!

**Comment by sufuf3** [comment]
close and move to #11646

**Pull request closed without merging**
