### PR TITLE
[new] add syn@0.2.0

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 this PR is for #6217.
I add `syn` at `v0.1.4` and add `git` auto-update config in its package.json.

There is a folder **"dist/"** in its GitHub repository, but don't see in npm package.
Files from npm need building, so I choose to add git auto-update.

Would you mind checking this PR for me? Thank you~ :-D

# Profile of the lib
 * Git repository (required): https://github.com/bitovi/syn
 * Official website (optional, not the repository): http://blog.bitovi.com/syn-a-standalone-synthetic-event-library/
 * NPM package url (optional): https://www.npmjs.com/package/syn
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 38
   - Count of watchers: **398**
   - Count of forks: 293

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
What does `[nrw]` mean here?

**Comment by PeterDaveHello** [comment]
oh ... new

**Comment by PeterDaveHello** [comment]
I wonder tag its organization will have notification or not, maybe should use its top 1~3 authors, contributors instead.

https://github.com/bitovi/syn/graphs/contributors

**Comment by Amomo** [comment]
Hi @maruilian11 
I have update this PR to syn v0.2.0, could you help me checking it? thanks

**Pull request merged**
