### PR TITLE
Added npm hook for angular.js to auto-update library

### PR DESCRIPTION
**Pull request by heathergh**
# Pull request template for new library

Pull request for issue: #13719
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

## Profile of the lib

* Git repository (required): git://github.com/angular/angular.js.git
* Official website (optional, not the repository):
* NPM package url (optional): https://www.npmjs.com/package/angular
* License and its reference: MIT
* GitHub / Bitbucket popularity (required):
  * Count of watchers: 4,100
  * Count of stars: 59,600
  * Count of forks: 28,800
* NPM download stats (optional):
  * Downloads in the last day:
  * Downloads in the last week: 493,860
  * Downloads in the last month:

## Essential checklist

* [ ] I'm the author of this library
  * [ ] I would like to add link to the page of this library on CDNJS on website / readme
* [ ] This lib was not found on cdnjs repo
* [ ] Doesn't already exist / has duplicate issue and PR
* [x] The lib has notable popularity
  * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [x] More than 800 downloads stats per month on npm registry
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [ ] Has valid tags for each versions (for git auto-update)
* [x] Auto-update setup
* [ ] Auto-update target/source is valid.
* [ ] Auto-update filemap is correct.

## Git commit checklist

* [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [x] The parent of the commit(s) in the PR is not older than 3 days.
* [x] Pull request is sent from a non-master branch with a meaningful name.
* [x] Separate unrelated changes into different commits.
* [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [ ] Close corresponding issue in commit message
* [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by MattIPv4** [comment]
Whilst this is exactly what we need and the config is correct, the `angular` npm package only contains the core angular files and not all the modules:

https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/angular.js/1.7.8
https://code.angularjs.org/1.7.9

```
tree node_modules/angular

node_modules/angular
├── LICENSE.md
├── README.md
├── angular-csp.css
├── angular.js
├── angular.min.js
├── angular.min.js.gzip
├── angular.min.js.map
├── bower.json
├── index.js
└── package.json
```

I'll create an issue on the Angular repo to see if they have any suggestions for this, but if not then our best bet may be to go with this PR :)

**Comment by heathergh** [comment]
I'm happy to know the package.json was formatted correctly! What if I changed the package.json to have a git hook rather than npm? 

```
"autoupdate": {
    "source": "git",
    "target": "https://github.com/angular/code.angularjs.org",
    "fileMap": [
      {
        "basePath": "1.7.9",
        "files": [
          "**/*",
          "**/!(docs)/*",
          "**/!(test-bundles)/*",
          "**/!(*.+(zip|txt|xml|json))"
        ]
      }
    ]
  }
```

**Comment by MattIPv4** [comment]
git auto-updating requires tags in the repo and a consistent repo format, which that doesn't have.

**Comment by MattIPv4** [comment]
Per the suggestion in https://github.com/angular/angular.js/issues/17007, would be happy in making PRs to add a library to cdnjs for each of the modules listed in https://code.angularjs.org/1.7.9 @heathergh? (Plus this PR for auto-updating the core package)

New libraries just require a single commit with the new package.json file that contains the meta information & auto-update config (not version attribute).

**Comment by heathergh** [comment]
I can definitely do that! For the "related issues" line in the PR template should I include this PR# and/or the issue linked in this one or leave it blank?

**Comment by MattIPv4** [comment]
I would update this one to be `Closes #issue` so that when this gets merged the issue will auto close. For the others, I would just reference this PR :) Thank you!

**Comment by nepa** [comment]
Seems like some AngularJS modules are already listed as individual libraries on cdnjs, while others are not. If that's okay with both of you, I'd check all modules that are listed in the AngularJS 1.7.8 library and create issues for those modules that are not available in version 1.7.9 yet.

If I got you correctly, @heathergh, you'd be willing to provide appropriate pull requests then?

Let me know, if you created any issues already.

**Comment by MattIPv4** [comment]
I'm not aware of any issues created regarding this, but it would be best to search existing open issues before creating each new one.

Creating an issue for each missing module would be great so that we can track what needs to be added :)

**Comment by nepa** [comment]
Sure, I'll check for duplicates. I did not find any recent issues of @heathergh regarding AngularJS modules. Just wanted to make sure that it's the desired workflow to create individual issues where needed. I'll take care of that then.

**Comment by nepa** [comment]
These are the missing AngularJS modules:
- [ ] `angular-animate` -> #13732
- [ ] `angular-route` -> #13733
- [ ] `angular-cookies` (existing lib `angular-cookie` is a different project) -> #13734
- [ ] `angular-aria` -> #13735
- [ ] `angular-loader` -> #13736
- [ ] `angular-message-format` -> #13737
- [ ] `angular-parse-ext` -> #13738

**Comment by MattIPv4** [comment]
Thank you for creating those!

**Comment by heathergh** [comment]
> @MattIPv4: Seems like some AngularJS modules are already listed as individual libraries on cdnjs, while others are not. If that's okay with both of you, I'd check all modules that are listed in the AngularJS 1.7.8 library and create issues for those modules that are not available in version 1.7.9 yet.
> 
> If I got you correctly, @heathergh, you'd be willing to provide appropriate pull requests then?
> 
> Let me know, if you created any issues already.

Hey nepa!

I haven't created the pull requests yet, but I will doing that this afternoon. I'll make sure to reference the issues you've created for the missing modules. Thank you for doing that!

**Comment by nepa** [comment]
@heathergh: Glad to hear that. :) Let me know, if I can do anything else to assist. Thank you!

**Comment by nepa** [comment]
@MattIPv4: Now that all PRs are closed, how long does it take for the CDN to pick up the new auto-updater configurations?

**Comment by MattIPv4** [comment]
@xtuc could we move all the new angular libs that got added to the new bot?

**Comment by nepa** [comment]
From what I can tell, at least, the modules `angular-route`, `angular-cookies` and `angular-aria` are still missing. All other libraries are now available individually in version 1.7.9.

**Comment by xtuc** [comment]
I moved `angular-route`, `angular-cookies` and `angular-aria` to the new bot. They should get updated shortly

**Comment by nepa** [comment]
All right, the AngularJS modules are now available in version 1.7.9.

Thanks to everyone.

**Pull request merged**
