### PR TITLE
[New] Update paho-mqtt auto-update w/ v1.1.0

### PR DESCRIPTION
**Pull request by jpwsutton**
Pull request for issue: #12889
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:
   - Count of stars:
   - Count of forks:
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [] Doesn't already exist / has duplicate issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
 * [x] The parent of the commit(s) in the PR is not older than 3 days.
 * [x] Pull request is sent from a non-master branch with a meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sashberd** [comment]
@jpwsutton Do not change version number in package.json
If you would like to change version number, so please also add this  version folder with files to lib folder

**Comment by jpwsutton** [comment]
Thanks @sashberd, I'll try and do that now. 
It's taking far too long to clone the repository, so I'm going to try and do the commits necessary through the  GitHub UI

**Comment by PeterDaveHello** [comment]
@jpwsutton is it possible to provide officially minified js file in the repository for future versions? Thanks.

**Comment by icraggs** [comment]
@PeterDaveHello yes, we can add a minified version to the repo for future versions.  Do you need anything else right now?

**Comment by avanc** [comment]
Any news here? cdnjs version of paho-mqtt is still 1.0.2 which suffers basic functionality like automatic reconnect.

**Comment by PeterDaveHello** [comment]
Here we go :tada: https://cdnjs.com/libraries/paho-mqtt/1.1.0

**Comment by icraggs** [comment]
Thanks! @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Thank you all :smile:

**Pull request merged**
