### PR TITLE
[New] Add tilt.js /w npm auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
@cdnjs/intern2 Please help me review this PR.
Pull request for issue: #10668 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/gijsroge/tilt.js
 * Official website (optional, not the repository): https://gijsroge.github.io/tilt.js/
 * NPM package url (optional): https://www.npmjs.com/package/tilt.js
 * License and its reference: MIT, https://github.com/gijsroge/tilt.js/blob/master/LICENSE
 * GitHub / Bitbucket popularity (required): 
   Watch 31
   Star 991
   Fork 45
 * NPM download stats (optional):
   70 downloads in the last day
   141 downloads in the last week
   702 downloads in the last month
# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by maruilian11** [comment]
@pvnr0082t I mentioned it.

**Comment by pvnr0082t** [comment]
ping @cdnjs/intern2

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by maruilian11** [comment]
@extend1994 Please help me review this PR. Thanks.

**Comment by PeterDaveHello** [comment]
Not really a big problem. @sufuf3 I'll suggest you not to directly change the form of PR title from your mentor, seniors, the case you can do this is 1) on the contributors' PR which does not belong to our members, 2) your students when you became a mentor/senior.

**Comment by PeterDaveHello** [comment]
Ping @extend1994

**Comment by sufuf3** [comment]
@maruilian11 @PeterDaveHello I really sorry about this, I'll be careful next time.
Should I change this PR title to origin title?

**Comment by PeterDaveHello** [comment]
@sufuf3 no need

**Comment by PeterDaveHello** [comment]
@maruilian11 please mention the reason why we can't fetch the old versions, of course we manually add them because the current config can't fetch them, this explain nothing.

**Comment by maruilian11** [comment]
ok, I will update my word.

**Pull request merged**
