### PR TITLE
[new] add jquery-sortable@0.9.13 with git auto-update, close #5316

### LINKED ISSUE #5316: [Request] Add "jQuery Sortable"
**Library name:** jQuery Sortable
**Git repository url:** https://github.com/johnny/jquery-sortable
**Official homepage:** http://johnny.github.io/jquery-sortable/

### PR DESCRIPTION
**Pull request by Amomo**
Hi @LeaYeh , I add a new lib with git auto-update from the request #5316 
repo: https://github.com/johnny/jquery-sortable
Would you mind checking this PR for me? Thank you~ :-)

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : `888` star
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by Amomo** [comment]
Hi @maruilian11 would you mind checking this PR for me?
Thank you~ :-D

**Comment by maruilian11** [comment]
@Amomo i think we also need `js/vendor`, `source/css` and `source/img`.

**Comment by Amomo** [comment]
@maruilian11 `vendor` means that they are not produced by this lib, so we should add them.

In `css` folder, they only provide an example file `example.css`, build from `jquery-sortable.css.sass`.
Because it is an example file, user need to extend it by himself.
I think we don't need to provide it.
(other files use for building website and examples, they come from other lib)
https://github.com/nostalgiaz/bootstrap-switch
https://github.com/rubychan/coderay

And, icons in `img` are form  [Glyphicons Free](http://glyphicons.com/). They note this on their website.
I think we don't collect them here, too.

Is this explanation okay?

**Comment by maruilian11** [comment]
@Amomo thank you for your explaining, can you show me where  they said the icons are from glyphicons free? thank you very much!
can you rebase this commit and tag me again? thanks~

**Comment by Amomo** [comment]
@maruilian11 I have rebased it!
site: http://johnny.github.io/jquery-sortable/ at the bottom of the page.

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Pull request merged**
