### PR TITLE
add tunajs v0.4.4 with npm autoupdate config

### LINKED ISSUE #7821: [Request] Add tuna.js
**Library name:** tuna.js
**Git repository url:** https://github.com/Theodeus/tuna
**npm package url(optional):** https://www.npmjs.com/package/tunajs
**License(s):** MIT
**Official homepage:**
**Wanna say something? Leave message here:** I'm the maintainer of Tuna, so happy to help if needed. The reason I'm not making a straight up pull request is because Tuna needs to be shipped with a couple of .wav files in order to work, which isn't mentioned as ok.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #7821 
@kennynaoh Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/Theodeus/tuna
 * Official website (optional, not the repository): 
 * NPM package url (optional): https://www.npmjs.com/package/tunajs
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 638
   - Count of watchers: 55
   - Count of forks: 58
 * NPM download stats (optional):
   - Downloads in the last day: 5
   - Downloads in the last week: 34
   - Downloads in the last month: 244

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7821, cc @Theodeus

### CODE REVIEW

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Comment by Theodeus** [comment]
Hey, author of the lib here: would it be possible to include the .wav files in /impulses as well? Those are needed to make all of the audio effects work.

**Comment by PeterDaveHello** [comment]
@Theodeus Sure!

**Comment by pvnr0082t** [comment]
@kennynaoh I have added `.wav* files. Please help me review again, thank you.

**Comment by PeterDaveHello** [comment]
`.wav*` or `*.wav`?

**Comment by kennynaoh** [comment]
@PeterDaveHello 
Maybe it's ```*.wav```.
But I think just wrong typing.
I see the correct pattern in package.json.
Please help me review it again.
Thanks.

**Comment by pvnr0082t** [comment]
Oh, that's messy wirting. It's `*.wav`.

**Comment by PeterDaveHello** [comment]
@terinjokes seems wav files on cdnjs.cloudflare.com are not allowed, I got 403 Forbidden, would you please help us enable it? Thanks.

cc @cdnjs/team-cdnjs

**Pull request merged**
