### PR TITLE
[New] Add signalr with npm auto-update via single package.json

### PR DESCRIPTION
**Pull request by bradygaster**
# Pull request template for new library

Pull request for issue: #
Related issue(s): #13198 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

## Profile of the lib

* Git repository (required):https://github.com/aspnet/AspNetCore/
* Official website (optional, not the repository):http://dot.net
* NPM package url (optional):https://npmjs.com/package/@aspnet/signalr
* License and its reference:Apache-2
* GitHub / Bitbucket popularity (required):
  * Count of watchers:1,278
  * Count of stars:10,744
  * Count of forks:2,569
* NPM download stats (optional):
  * Downloads in the last day: 10,000 (est as npm provides weekly only)
  * Downloads in the last week: 113,000
  * Downloads in the last month: 400,000 (est as npm provides weekly only)

## Essential checklist

* [x] I'm the author of this library
  * [x (if allowed)] I would like to add link to the page of this library on CDNJS on website / readme
* [x] This lib was not found on cdnjs repo
* [x] Doesn't already exist / has duplicate issue and PR
* [x] The lib has notable popularity
  * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [x] More than 800 downloads stats per month on npm registry
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [ ] Has valid tags for each versions (for git auto-update)
* [ ] Auto-update setup
* [ ] Auto-update target/source is valid.
* [ ] Auto-update filemap is correct.

## Git commit checklist

* [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [x] The parent of the commit(s) in the PR is not older than 3 days.
* [x] Pull request is sent from a non-master branch with a meaningful name.
* [x] Separate unrelated changes into different commits.
* [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [x] Close corresponding issue in commit message
* [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by bradygaster** [comment]
at this point i seem to be stuck. The name of our NPM package is `@aspnet/signalr`. I've tried to create this folder structure and coordinating package.json in a multitude of methods but none seem to work. Please advise, @dakshshah96 @sufuf3 @sashberd @extend1994

**Comment by bradygaster** [comment]
closing to try to re-structure incoming repo

**Comment by MattIPv4** [comment]
@bradygaster Hiya, is there a reason this is being put under `@aspnet` and not `signalr` or similar?

**Comment by bradygaster** [comment]
good question @MattIPv4 - i actually tried putting it under `@aspnet/signalr`, then `@aspnet`, and then `signalr` but none worked.

**Comment by MattIPv4** [comment]
Honestly, this bot sometimes is just annoying.

**Comment by bradygaster** [comment]
thanks for the fix @MattIPv4 - would love to know what i'd done incorrectly.

**Comment by MattIPv4** [comment]
@bradygaster Is isn't fixed 😂 I need to go an properly spare checkout this so I can squash it all.

**Comment by MattIPv4** [comment]
@PeterDaveHello Is there no quicker way to deal with this? Even with sparse checkout, it takes about five minutes to simply add the origin...

**Comment by bradygaster** [comment]
@MattIPv4 i had just added the package.json to the branch of my fork thinking that'd be enough.

**Comment by MattIPv4** [comment]
@bradygaster Yeah, in theory, that is all you need to do. Once you go beyond that due to issues such as this, it becomes a huge pain due to the repo size. I will keep you updated on progress once @PeterDaveHello responds with best steps to squash this.

**Comment by bradygaster** [comment]
thanks @PeterBot (who i know is a bot so this is embarrassing) and @MattIPv4 for the assistance!

**Comment by bradygaster** [comment]
no we don't need those.

**Comment by PeterDaveHello** [comment]
@bradygaster So the map file will need to ignore them :)

**Comment by bradygaster** [comment]
@PeterDaveHello that's fine - need me to make any changes?

**Comment by MattIPv4** [comment]
@bradygaster I believe Peter would like you to make changes to the npm file map in package.json so that it doesn't pick up the `esm` & `cjs` directories if you say they aren't needed?

**Comment by PeterDaveHello** [comment]
@MattIPv4 Thanks, you are right.

**Comment by sashberd** [comment]
I think this one is relative #12940

**Comment by bradygaster** [comment]
Thanks for the clarification @MattIPv4 - will do shortly.

**Comment by MattIPv4** [comment]
@PeterDaveHello Is there any reason the bot cannot automatically rebase?

**Comment by bradygaster** [comment]
@MattIPv4 - all i did was edit the file again in the GH UI. Not cloning the whole repo (or even a subset of it) just to change one line. Let me know if there is another course of action I should take.

**Comment by PeterDaveHello** [comment]
@bradygaster I will help rebase it.

**Comment by PeterDaveHello** [comment]
@MattIPv4 There is no this feature yet.

**Comment by MattIPv4** [comment]
@PeterDaveHello Is it a feature that we could add, it seems like something the bot could always automatically do so that it isn't an error given to the author?

**Comment by MattIPv4** [comment]
@PeterDaveHello Is this good to merge now?

**Comment by PeterDaveHello** [comment]
@MattIPv4 I don't have enough time to implement that yet. Contributions to implement this feature would be welcome.

**Comment by bradygaster** [comment]
@MattIPv4 and @PeterDaveHello - does something need to be implemented for this PR to be merged? we'd really like to enable our customers with CDNJS access soon. :)

**Comment by PeterDaveHello** [comment]
@bradygaster coming soon, I'll give it a higher proirity!

**Comment by PeterDaveHello** [comment]
hmmm, as we already have `signalr.js`, to prevent misunderstanding, I'll rename it to `aspnet-signalr`

**Comment by PeterDaveHello** [comment]
The version naming is ... not very easy to understand ...

```
1.0.0/                   1.0.0-preview2-final/  1.0.2/  1.1.0/                 1.1.0-preview3-35497/  3.0.0-preview-18579-0056/  3.0.0-preview4-19216-03/
1.0.0-preview1-final/    1.0.0-rc1-final/       1.0.3/  1.1.0-preview1-35029/  1.1.2/                 3.0.0-preview-19075-0444/
1.0.0-preview1-update1/  1.0.0-rc1-update1/     1.0.4/  1.1.0-preview2-35157/  1.1.4/                 3.0.0-preview3-19153-02/
```

Please allow me to ignore those non stable version

**Comment by bradygaster** [comment]
@PeterDaveHello - Apologies for the significant delay in updating this, I'll facilitate an update to make sure the auto-update is working. Also, we've moved our client into a new organization, specifically from aspnet/signalr to microsoft/signalr. Is it conceivable that we could have the CDNJS  package updated to be `microsoft-signalr` instead of `aspnet-signalr`? 

Finally, our old client is [here](https://cdnjs.com/libraries/signalr.js). We'd like to get this updated to our 2.4.1 release. Is this possible, too?

**Comment by MattIPv4** [comment]
@bradygaster If you can open a PR that updates the packge.json file with the new information we should be able to get it expedited for you :)

**Comment by PeterDaveHello** [comment]
> @PeterDaveHello - Apologies for the significant delay in updating this, I'll facilitate an update to make sure the auto-update is working. Also, we've moved our client into a new organization, specifically from aspnet/signalr to microsoft/signalr. Is it conceivable that we could have the CDNJS package updated to be `microsoft-signalr` instead of `aspnet-signalr`?
> 
> Finally, our old client is [here](https://cdnjs.com/libraries/signalr.js). We'd like to get this updated to our 2.4.1 release. Is this possible, too?

Not very recommend to do the rename, though the assets won't be broken as the symbolic links will work on the CDN origin, however there is no renaming mechanism and won't be an one any sooner, so it will be a period people may thought aspnet-signalr missing on the website.

**Comment by bradygaster** [comment]
@PeterDaveHello well we've already done the rename in NPM. Are you suggesting we don't rename the CDNJS package? As in, leave it as aspnet-signalr even though the new location is at microsoft/signalr?

**Comment by PeterDaveHello** [comment]
@bradygaster Yes if you can accept that. Before we have enough sponsorship I can not guarantee any ETA of when the rename mechanism will be implemented.

**Comment by bradygaster** [comment]
@PeterDaveHello yes, i can accept that. Can i be notified the moment you implement renaming?

**Comment by PeterDaveHello** [comment]
@bradygaster I will try to remember that and maybe search rename related issues to ping authors, but as I mentioned earlier, there is no guarantee right now 🙂

**Pull request merged**
