### PR TITLE
add OverlappingMarkerSpiderfier@0.3.3

### PR DESCRIPTION
**Pull request by maruilian11**
Pull request for issue: #9112 
@Piicksarn @cdnjs/intern2 could you please help me review this PR? Thank you!
the [issue](https://github.com/jawj/OverlappingMarkerSpiderfier/issues/112) about adding source file and git tags doesn't get any response for a while. But it's not the first time that this lib is asked to be added to cdnjs, cc https://github.com/cdnjs/cdnjs/issues/5115.
I think we can at least add the latest version(0.3.3) of this lib and close this issue.
the commited files are from http://jawj.github.io/OverlappingMarkerSpiderfier/bin/oms.js and http://jawj.github.io/OverlappingMarkerSpiderfier/bin/oms.min.js mentioned in [download](https://github.com/jawj/OverlappingMarkerSpiderfier#download).
you can find version number in oms.js.

# Profile of the lib
 * Git repository (required): https://github.com/jawj/OverlappingMarkerSpiderfier
 * Official website (optional, not the repository): 
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   Watch 30
   Star 466
   Fork 145

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
`oms` not `OverlappingMarkerSpiderfier`?

**Comment by maruilian11** [comment]
@PeterDaveHello I updated the lib name field.

**Comment by PeterDaveHello** [comment]
@maruilian11 DON'T YOU NEED TO UPDATE THE PR TITLE?

**Comment by maruilian11** [comment]
@PeterDaveHello yes, sorry..
do I need to rebase the commit with our latest master again?

**Pull request merged**
