### PR TITLE
[new] [author] Added chess.js v0.9.3

### PR DESCRIPTION
**Pull request by jhlywa**
Some of the chess.js users have requested that it be added to cdnjs (jhlywa/chess.js#73)

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hi @jhlywa, thanks for your PR, I wonder if we need the test.js file here?

**Comment by jhlywa** [comment]
The tests were automatically included by cdnjs-importer.  I have removed them.

**Comment by PeterDaveHello** [comment]
Okay, would you please squash/fixup them into only one commit? Thanks.

**Comment by jhlywa** [comment]
Ok, I switched to npm instead of git autoupdate, fixed whitespace issues in package.json, and squashed.

**Pull request merged**
