### PR TITLE
Update knockout-validation to version 2.0.1

### PR DESCRIPTION
**Pull request by crissdev**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
According to #3638, I wanna ask for auto-update config if it's possible, thanks.

**Comment by crissdev** [comment]
I wanted to provide it after NPM package is updated - I'm waiting for publishing permissions on this. Currently the NPM package is published at 2.0.0-pre but this PR adds files for version 2.0.0. So I thought the `autoupdate` configuration might mess up the things. If that's not the case then please let me know and I'll add it. Thanks.

**Comment by crissdev** [comment]
Also the file structure is different - the directories are in lowercase.

**Comment by PeterDaveHello** [comment]
Seems there is no auto deploy on this lib, right? What about git auto-update?

**Comment by crissdev** [comment]
I've added npm auto update. If possible please leave this PR until I sort it out with the owner of the npm package. If needed I can rebase my work and force-push to my fork.

**Comment by PeterDaveHello** [comment]
Okay, it's okay, just ping me when you are ready, thanks!

**Comment by crissdev** [comment]
@PeterDaveHello I've published the npm package.

**Comment by PeterDaveHello** [comment]
Seems there is no min and map file in dist?

**Comment by crissdev** [comment]
:boom: This really puts me in a tough spot. You mentioned earlier git auto-update. Will that fix this problem? Really sorry for this.

**Comment by PeterDaveHello** [comment]
If you have them in your repo, yes.

**Comment by crissdev** [comment]
I do have them. What is required to enable this?

**Comment by crissdev** [comment]
@PeterDaveHello I've added git auto-update in package.json

**Comment by PeterDaveHello** [comment]
Would you please squash/merge these commits into only one commit as our document said.

**Comment by crissdev** [comment]
done

**Comment by PeterDaveHello** [comment]
Oops, we have a problem here, filename should be dist/knockout.validation.min.js with dist prefix due to the auto-update config.

**Comment by crissdev** [comment]
I was inspired by `ajax/libs/aegis/package.json` which seems to have almost the same auto-update config. For npm auto-update I could specify multiple `basePath, files` entries. Can I have the same for git auto-update?

**Comment by PeterDaveHello** [comment]
Currently not, sorry for the inconvenience, to keep the structure (will be better), I'll respectfully suggest you to use npm auto-update or setup another git repo for the dist files, to setup another repo for it is also a common method for this situation.

**Comment by crissdev** [comment]
I will use npm auto-update once I have a 2.x version released. I will just make sure next time I have everything set up correctly. Sorry for this bad PR - I'll make it better next time.

**Comment by PeterDaveHello** [comment]
No need to say sorry @crissdev, it's okay.
I want to confirm that what will you do and what should I do now, will you add other 2 files in npm so that we can keep the structure and use npm auto-update?

**Comment by crissdev** [comment]
Yes, I will add the 2 files to npm and add a new directory `2.0.1`. But one question remains - can I leave the `2.0.0` directory in the structure with wthat's currently in in?
Most probably I can do the update tomorrow. Thanks.

**Comment by PeterDaveHello** [comment]
It's okay, because updated won't grab the exist versions.

**Comment by crissdev** [comment]
@PeterDaveHello Since I didn't get this right last time I haven't yet tagged the latest sources in the repository with `2.0.1`. Can you take a quick look to see if everything's right? Thanks

**Comment by PeterDaveHello** [comment]
It's good, so I need you'll need me merge it now?

**Comment by crissdev** [comment]
It would be great.
By the way, changing the title of this PR to reflect `2.0.1` might be a good idea.

**Comment by PeterDaveHello** [comment]
Thanks.

**Pull request merged**
