### PR TITLE
add ticketbase-js v0.1.13

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/ticketbase/ticketbase-js
**Watch 5
  Star 4
 Fork 0**
@Amomo could u help me check this PR for #6864 ? thank you!
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [ ] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update) 
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
This ticketbase.js seems to be not fully compiled, check the diff with official hosted cdn:
http://cdn.ticketbase.com/widgets/v0.1.13/ticketbase.js

**Comment by maruilian11** [comment]
@Amomo i have changed `ticketbase.js` from master branch to tag v0.1.13.
it should be fully compiled, could you help me check this PR?

**Comment by maruilian11** [comment]
ping @Amomo

**Comment by Amomo** [comment]
@maruilian11 sorry for late. 😣
I think this PR is ok, could you rebase it on latest master branch again?
Thank you very much!!!!!

**Comment by PeterDaveHello** [comment]
As https://github.com/ticketbase/ticketbase-js/issues/111 said, so how can you apply auto-update from git repo?

**Comment by PeterDaveHello** [comment]
> Amomo i have changed ticketbase.js from master branch to tag v0.1.13.

Surprised that you still grabbing files from master branch, that's a very old issue.

**Comment by PeterDaveHello** [comment]
Seems the release commits always contain `petlanthropy.js`, do we need it or not?

**Comment by maruilian11** [comment]
@PeterDaveHello 
https://github.com/ticketbase/ticketbase-js#distribution
due to this, i though we just need ticketbase.js.
do you need me to open an issue?

**Comment by PeterDaveHello** [comment]
@maruilian11 Why not?

**Comment by rstacruz** [comment]
hey, Ticketbase.js maintainer here. You're fine not bundling petlanthropy.js with it :)

**Comment by PeterDaveHello** [comment]
Thanks @rstacruz :+1:

**Comment by PeterDaveHello** [comment]
@maruilian11 let's update the PR with the latest master branch.

**Comment by PeterDaveHello** [comment]
@rstacruz  but is that a part of you lib?

**Comment by maruilian11** [comment]
@PeterDaveHello updated.

**Comment by rstacruz** [comment]
peterdavehello, it's a useless vestige of an old version of ours and we'll be removing it in the next version.

**Comment by PeterDaveHello** [comment]
@rstacruz so will it be needed for old versions? our auto-updater will pick all the versions including the old versions.

**Comment by rstacruz** [comment]
Nah, it's no longer supported and past versions will not work anymore.

**Comment by PeterDaveHello** [comment]
@rstacruz Okay, thanks for your reply.

**Pull request merged**
