### PR TITLE
add bootflat v2.0.4

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/bootflat/bootflat.github.io
**Watch 187
  Star 3,820
 Fork 393**
@Amomo could u help me check this PR for #6843 ? thank you!
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update) 
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Don't you read its document @maruilian11 ? Where is icheck.min.js?


https://github.com/bootflat/bootflat.github.io#quick-start

```html
<!-- Bootflat's JS files.-->
        <script src="https://bootflat.github.io/bootflat/js/icheck.min.js"></script>
```

**Comment by maruilian11** [comment]
＠PeterDaveHello but we already have ichcek on cdnjs.
https://cdnjs.com/libraries/iCheck

**Comment by PeterDaveHello** [comment]
Okay, sorry that's my fault, let's rebase upon latest master branch and merge this PR.

**Comment by maruilian11** [comment]
@PeterDaveHello i have rebase upon latest master branch.

**Pull request merged**
