### PR TITLE
add cPlayer v2.3.0 w/ git auto-update

### PR DESCRIPTION
**Pull request by Copay**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):cPlayer(https://github.com/Copay/cPlayer)
 * Official website (optional, not the repository):http://cplayer.js.org
 * NPM package url (optional):https://www.npmjs.com/package/cPlayer
 * GitHub / Bitbucket popularity (required):
   - Count of stars:101
   - Count of watchers:7
   - Count of forks:15

# Essential checklist
 * [ x ] I'm the author of this library
   * [ x ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ x ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ x ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ x ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ x ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ x ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by Copay** [comment]
i'm sorry that my english is not well.

**Comment by PeterDaveHello** [comment]
@Copay we can help you fix this PR, would you like to give it a try?

**Comment by Copay** [comment]
Thanks!

**Comment by PeterDaveHello** [comment]
@Copay looks like you deleted the forked repo, so please fork a new one and send the PR again, we'll help you pass the tests, thanks!

**Pull request closed without merging**
