### PR TITLE
Add pegasus@0.3.2

### PR DESCRIPTION
**Pull request by Piicksarn**
@maruilian11 , would you mind to have a look at the pr?
The PR is referenced to issue  #5928.
The git repo : https://github.com/typicode/pegasus/tree/v0.3.2

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `30`, Star `555`, Fork `41`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

Thank you!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
No comment?

**Comment by maruilian11** [comment]
@Piicksarn i think we need min file of all `.js`,  and add `requiredFiles`.

**Comment by Piicksarn** [comment]
@maruilian11,i have it corrected! would you please have a look at the PR again?
Thank you!

**Comment by maruilian11** [comment]
@Piicksarn i think this PR is OK. could you rebase it? thank you~

**Comment by Piicksarn** [comment]
@maruilian11, i have it rebased!
Would you please have a look at the pr again?
thank you!

**Comment by PeterDaveHello** [comment]
Don't you need to close a issue in the commit message? 
There is a npm package of this lib, please try to use npm auto-update.

**Comment by Piicksarn** [comment]
@maruilian11, i have it rebased & changed it to nom-autoupdate.
Would you mind to have a look at the pr again?
Thank you!

**Pull request merged**
