### PR TITLE
 Update licenses format of jquery.form

### PR DESCRIPTION
**Pull request by zky524**
Ref:https://github.com/jquery-form/form#license
cc #11931

### CODE REVIEW

**Comment by hare1039** [comment]
@zky524 Hi, I squashed the commits and rebased this branch as you asked. Please tell me anything else you need. Thanks!

**Comment by extend1994** [comment]
@zky524 Thanks for contribution! 😄 
However, the commit is about license info update instead of format. Please note this in the future. 
In addition,when you try to send pull request, it would be better to make sure that no one has opened a same pull request before you. When someone has opened the pull request the same as yours. Please pick another issue, there are a lot of issues you can discover 💪 
cc @cdnjs/intern3

**Comment by PeterDaveHello** [comment]
Isn't this has conflict with #12050? Don't we need to respect the earlier sent PRs? @hare1039 @sufuf3 don't you need to check message on https://github.com/cdnjs/cdnjs/issues/11931#issuecomment-339309717 ?

**Comment by sufuf3** [comment]
I'm really sorry about that.
I should pay more attention before merge the PR.
I'll keep in mind.
Sorry.

**Comment by PeterDaveHello** [comment]
@sufuf3 I think it's not just about merging, it's in the normal review process, isn't it?

**Comment by sufuf3** [comment]
Yes. sorry.

**Pull request merged**
