### PR TITLE
 Manually add bootstrap-timepicker missing versions & update metadata

### PR DESCRIPTION
**Pull request by hare1039**
Pull request for issue: #11043
Related issue(s): # #

@cdnjs/intern3 Please help me review this PR. Thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/jdewit/bootstrap-timepicker
 * Official website (optional, not the repository): https://jdewit.github.io/bootstrap-timepicker/
 * NPM package url (optional): https://www.npmjs.com/package/bootstrap-timepicker
 * License and its reference: MIT, https://github.com/jdewit/bootstrap-timepicker/blob/gh-pages/LICENSE

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by hare1039** [comment]
@extend1994 Good point. I fix the commit message, and remove `0.2.6+1` because it is identical with `0.2.6`. Please review this PR again. Thanks.

**Comment by hare1039** [comment]
@extend1994 I appended the `er`. Please help me review this PR again. Thanks.
@pvnr0082t Please help me review this PR. Thanks.

**Comment by hare1039** [comment]
ping

**Comment by PeterDaveHello** [comment]
@hare1039 shouldn't you request review from me rather than a meaningless ping?

**Comment by sufuf3** [comment]
@hare1039 Would you modify the commit message as this comment https://github.com/cdnjs/cdnjs/pull/11081#pullrequestreview-37739237?
This PR almost finish except for this part.
Thank you.

**Comment by sufuf3** [comment]
@hare1039 Would you modify the commit message as this comment https://github.com/cdnjs/cdnjs/pull/11081#pullrequestreview-37739237 after the final exam?
This PR almost there.
Thank you.

**Comment by sashberd** [comment]
@PeterDaveHello @sufuf3 @extend1994 cannot rebase this one to latest master. Suggest to close.

**Pull request merged**
