### PR TITLE
Add notificon@1.0.4 with git autoupdate.

### PR DESCRIPTION
**Pull request by Piicksarn**
@maruilian11,  would you mind to have a look at the pr?
The PR is referenced to issue  #5928.
Thank you!
The information of the pr:
The git repo : https://github.com/makeable/Notificon/tree/1.0.4

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `15`, Star `950`, Fork `40`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
No license info?

**Comment by Piicksarn** [comment]
@maruilian11, would you like to  checkout the pr again? Thank you~

**Comment by Piicksarn** [comment]
@maruilian11 , @Amomo,
would you like to checkout the pr? Thank you~

**Comment by maruilian11** [comment]
@Piicksarn could you please tell me how you tell its license is `BSD-2-Clause`?
And please open an issue to ask the author to update the tags. Thank you.

**Comment by Piicksarn** [comment]
Author show the license is BSD in README.md
https://github.com/makeable/Notificon/tree/1.0.4

and the BSD format could be found in the link show below:
https://opensource.org/licenses/BSD-2-Clause

**Comment by maruilian11** [comment]
@Piicksarn thank you, i see.
sorry for checking late, could you rebase the commit again?

**Comment by PeterDaveHello** [comment]
@Piicksarn maybe you can sedn a PR to add it into the package.json in origin repository, also help us confirm the license is correct.

**Comment by Piicksarn** [comment]
https://github.com/makeable/Notificon/pull/16

**Comment by Piicksarn** [comment]
@maruilian11 , @PeterDaveHello, I have already done. :smiley:

**Comment by maruilian11** [comment]
@PeterDaveHello so do we need to wait for the PR be merge in origin repository?

**Comment by PeterDaveHello** [comment]
Just confirm.

**Comment by maruilian11** [comment]
@Piicksarn could you change the auto-update config to npm? thank you!

**Comment by Piicksarn** [comment]
@maruilian11, i have it changed!

**Pull request merged**
