### PR TITLE
add cookie-banner@1.0.0 w/ git auto-update

### LINKED ISSUE #9956: [Request] Add Cookie Banner
**Library name: cookie-banner 
**Git repository url: https://github.com/dobarkod/cookie-banner/
**npm package url(optional):** 
**License(s):**
**Official homepage: http://cookiebanner.eu/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by kennynaoh**
close #9956, cc @zytzagoo

Pull request for issue: #9956 
Related issue(s): # #
@x09326 Please help me review this PR, thanks!
I removed the homepage `http://cookiebanner.eu/` because it will link to the git repo.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/dobarkod/cookie-banner
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference: MIT, https://github.com/dobarkod/cookie-banner/blob/master/LICENSE.md
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 144
   - Count of watchers: 18
   - Count of forks: 44
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Looks like there is an official minified file build process in its [Makefile](https://github.com/dobarkod/cookie-banner/blob/1.0.0/Makefile), let's ask for the possibility for officially minified one?

**Comment by zytzagoo** [comment]
Minified file is now in the repo: https://github.com/dobarkod/cookie-banner/commit/2fdca8b768ccac450b5552d2d2fad70502329243

**Comment by PeterDaveHello** [comment]
@zytzagoo thanks a lot, is it possible to re-tag v1.0.0 or tag a new release? Thank you.

**Comment by zytzagoo** [comment]
@PeterDaveHello re-tagged v1.0.0

**Comment by PeterDaveHello** [comment]
@zytzagoo Thanks a lot!

**Comment by kennynaoh** [comment]
@x09326 I have updated the fileMap, please help review it. Thanks!

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Pull request merged**
