### PR TITLE
Update Amchart Libraries to 3.13.0

### PR DESCRIPTION
**Pull request by abishekrsrikaanth**
AmCharts - 3.13.0
AmStockChart - 3.13.0
AmMaps - 3.13.0

Since these libraries are not on GIT, sending a manual PR to be merged.

Ref: http://www.amcharts.com/download/

### CODE REVIEW

**Comment by abishekrsrikaanth** [comment]
@PeterDaveHello the CI check has failed, is there anything that needs to be done?

**Comment by PeterDaveHello** [comment]
I'm going to rebuild the test, because we had a problem on CircleCI and fixed now.

**Comment by abishekrsrikaanth** [comment]
@PeterDaveHello, so is this good to go now?

**Comment by PeterDaveHello** [comment]
Because this PR is a little bit large, would you please give me more time to audit it? thanks :)

**Comment by abishekrsrikaanth** [comment]
Np, Thanks :)

**Comment by PeterDaveHello** [comment]
Looks okay in file structure, but seems you didn't follow our conventions, there are 3 libs in 2 commits, would you please separate them into 3 independent commits? thanks.

**Comment by abishekrsrikaanth** [comment]
Thanks, I will send a new PR. Closing this

**Comment by PeterDaveHello** [comment]
Thank you.

**Pull request closed without merging**
