### PR TITLE
[new] [author] Adding Cesium 1.9.0 library your service.

### PR DESCRIPTION
**Pull request by maikuru**
[Review on Reviewable](https://reviewable.io/reviews/cdnjs/cdnjs/4615)

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
But we didn't support json yet, hi @terinjokes, is json okay to be supported?

**Comment by maikuru** [comment]
@PeterDaveHello Not sure if you meant to comment here.  Otherwise I don't really know what you are referring to.

**Comment by PeterDaveHello** [comment]
There are many json files here, even though I merge this PR, you can not access them :p

**Comment by maikuru** [comment]
that shouldn't inhibit core functionality.  I'll have to run some tests when it's being served via this service.

**Comment by PeterDaveHello** [comment]
So should remove them here.

**Comment by drewfreyling** [comment]
@maikuru any word on removing the json files?

**Comment by Piicksarn** [comment]
@cdnjs/intern @cdnjs/intern2

**Comment by maruilian11** [comment]
@maikuru any update?
the PR will be closed if there is no any response in next 7 days.

**Comment by PeterDaveHello** [comment]
Hello, any updates here? Thanks.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by maruilian11** [comment]
@PeterDaveHello this PR has been no response for a long time, do we close it directly?

**Comment by PeterDaveHello** [comment]
fair enough

**Pull request closed without merging**
