### PR TITLE
update URI.js to use auto update

### PR DESCRIPTION
**Pull request by codylerum**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
What about other js files?

**Comment by codylerum** [comment]
@rodneyrehm which files should be published?

**Comment by rodneyrehm** [comment]
does [package.json's "files"](https://github.com/medialize/URI.js/blob/gh-pages/package.json#L49-L61) answer that?

**Comment by codylerum** [comment]
@rodneyrehm Yes it does. I'll update the PR. Thanks!

**Comment by codylerum** [comment]
updated.

**Pull request merged**
