### PR TITLE
adds comixngn

### LINKED ISSUE #5179: [Request] comix-ngn [author]
Please add [comix-ngn](https://github.com/ogewan/comix-ngn), master branch.

### PR DESCRIPTION
**Pull request by ogewan**
resolves #5179

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@cdnjs/intern please audit this PR.

**Comment by Piicksarn** [comment]
- [x] Not found on cdnjs repo 
- [x] No already exist issue and PR
- [ ] Notable popularity  ***`Watch : 1    Star : 1    Fork : 1`***

The library could not be added, as the popularity isn't reach the standard in [README](https://github.com/cdnjs/cdnjs/blob/master/README.md).
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```

**Comment by Piicksarn** [comment]
@cdnjs/intern

**Comment by maruilian11** [comment]
@ogewan we suggest you resent the PR until the popularity is enough. thank you!

**Pull request closed without merging**
