### PR TITLE
add react-router 1.0.0-rc3

### PR DESCRIPTION
**Pull request by mjackson**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Would you please leave un-related key/value in package.json alone? Thanks.

**Comment by mjackson** [comment]
Nevermind.

**Comment by PeterDaveHello** [comment]
@mjackson sorry for the inconvenience. @Amomo  please help send another PR to add this lib.

**Comment by Deep-Codes** [comment]
And that's how `unpkg` was born [Read more](https://twitter.com/mjackson/status/1455597224151248896?s=20)

**Pull request closed without merging**
