### PR TITLE
Added sanitize.css@3.1.1

### PR DESCRIPTION
**Pull request by jonathantneal**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@jonathantneal would you consider only the add the auto-update section in package.json? Thanks.

**Comment by PeterDaveHello** [comment]
@jonathantneal ZDroid/sanitize.css and 10up/sanitize.css are not the same, you should not modify the origin lib, but add a new 10up-sanitize.css, thanks.

**Comment by jonathantneal** [comment]
To create this pull, I used `cdnjs-importer` with no configuration. This is the commit it produces out of the box. Is there a way to use this tool without it attempting to consume the same namespace?

I’ll hit up ZDroid to see if they are continuing work on that project. This came up in 2014 https://github.com/necolas/normalize.css/issues/287. FWIW, sanitize.css was started in [2012](https://github.com/10up/sanitize.css/commit/b380c3f5890a0f5059044e52b35e8932958274d3).

**Comment by PeterDaveHello** [comment]
> To create this pull, I used cdnjs-importer with no configuration. This is the commit it produces out of the box. Is there a way to use this tool without it attempting to consume the same namespace?

I don't think so.

> I’ll hit up ZDroid to see if they are continuing work on that project. This came up in 2014 necolas/normalize.css#287. FWIW, sanitize.css was started in 2012.

It doesn't matter, you can not overwrite the already exist libs.

**Comment by jonathantneal** [comment]
And that’s namespacing, folks! All right, thanks @PeterDaveHello.

**Comment by PeterDaveHello** [comment]
So are you going to create a new PR?

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@PeterDaveHello I think this PR can close, because we hosted it.
https://github.com/cdnjs/cdnjs/commit/52832b69cf1033550e93b1883ec2cec3549fda7b
https://cdnjs.com/libraries/10up-sanitize.css

**Pull request closed without merging**
