### PR TITLE
Add carbon-components via single package.json w/ npm auto-update

### LINKED ISSUE #11198: [Request] Add Carbon Design Systems
**Library name:** Carbon Design Systems
**Git repository url:** https://github.com/carbon-design-system/carbon-components
**npm package name or url** (if there is one): carbon-components
**License (List them all if it's multiple):** Apache License Version 2.0, January 2004
**Official homepage:** http://carbondesignsystem.com/
**Wanna say something? Leave message here:** Cool CSS framework

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/44931952-request-add-carbon-design-systems?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by MattIPv4**
Resolves #11198

### CODE REVIEW

**Comment by sashberd** [comment]
@MattIPv4 I suggest to ask author about which files should be hosted. IMO umd is not only folder to host

**Comment by MattIPv4** [comment]
What else do you believe needs to be hosted? The es6 versions of everything, in the `es` directory? The source files, in `src`? The HTML demos, in `html`?

**Comment by sashberd** [comment]
@MattIPv4 scripts folder?

**Comment by MattIPv4** [comment]
Updated to include scripts. I've also noticed a set of font files that only appear in the src dir, which seems weird. Will reach out.

**Comment by MattIPv4** [comment]
> Thanks so much for reaching out! For CDN files for `carbon-components`, I think you got basically all of them. For a full list I assume it'd be:
> 
>   * `/css/carbon-components.css`
>   * `/css/carbon-components.css.map`
>   * `/css/carbon-components.min.css`
>   * `/css/carbon-components.min.css.map`
>   * `/scripts/carbon-components.js`
>   * `/scripts/carbon-components.min.js`
>   * `/umd` directory

Sounds like we having everything required, ref: https://github.com/carbon-design-system/carbon/issues/5899

**Pull request merged**
