### PR TITLE
Add knockout-es5@0.4.6 w/ git auto-update

### LINKED ISSUE #7619: [Request] Add knockout-es5
**Library name:**knockout-es5 
**Git repository url:**https://github.com/SteveSanderson/knockout-es5
**npm package url(optional):** knockout-es5
**License(s):**MIT
**Official homepage:**http://blog.stevensanderson.com/2013/05/20/knockout-es5-a-plugin-to-simplify-your-syntax/
**Wanna say something? Leave message here:**
Everyone that uses knockoutjs want use this also. So will be very aprecited if we can have it from here.

### PR DESCRIPTION
**Pull request by dakshshah96**
close #7619

Pull request for issue: #7619

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/SteveSanderson/knockout-es5
 * Official website (optional, not the repository): http://blog.stevensanderson.com/2013/05/20/knockout-es5-a-plugin-to-simplify-your-syntax/
 * NPM package url (optional):
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 13
   - Count of stars: 157
   - Count of forks: 39
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by dakshshah96** [comment]
Hey @sufuf3, thanks for the review. I'd like to point out here that the `close #7628` is a PR and PRs can't be closed through commit messages, only issues can be.

**Comment by PeterDaveHello** [comment]
@dakshshah96 oh really? Didn't know that!

**Comment by sufuf3** [comment]
But my PR's commit can close PR. like this: https://github.com/cdnjs/cdnjs/pull/11302/commits
It's a little bit weird.

**Comment by dakshshah96** [comment]
@sufuf3 @PeterDaveHello Just tested it out. It does work. My bad, sorry! 😅

**Comment by dakshshah96** [comment]
@sufuf3 Modified the commit message 👍

**Pull request merged**
