### PR TITLE
[new] add Furtive@2.2.3 with git auto-update, close #5075

### LINKED ISSUE #5075: [Request] Add Furtive CSS
https://github.com/johnotander/furtive

### PR DESCRIPTION
**Pull request by Amomo**
Hi @LeaYeh  , I add a new lib with git auto-update from the request #5075
repo: https://github.com/johnotander/furtive
Would you mind checking this PR for me?
Thank you~ :-)

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Any updates?

**Comment by LeaYeh** [comment]
sorry for reply late.
in its package.json main field is specified 'gulpfile.js' , so i thought we should also add gulpfile.js and change the basepath.

**Comment by Amomo** [comment]
Hi @LeaYeh 
By reading the content of 'gulpfile.js', I think it is a node program using ”uncss“ module to compress the sass and css files.
Because it need to read package.json and files under other directories, I think 'gulpfile.js' should be used by those who develop this library.
I believe that we should only collect the css files.

**Comment by Amomo** [comment]
@LeaYeh I have rebased it!
Could you come to check it again? Thank you! :-D

**Comment by LeaYeh** [comment]
wow my mistake, you are so attentive.
@PeterDaveHello

**Pull request merged**
