### PR TITLE
Add once@1.4.0 with npm auto-update

### LINKED ISSUE #10212: [Request] once
**Library name:** once
**Git repository url:** https://github.com/zaclummys/once
**npm package url(optional):** 
**License(s):** MIT License

### PR DESCRIPTION
**Pull request by clairetsai818**
close #10212, cc @zaclummys

Pull request for issue: #10212 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/zaclummys/once
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/once
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 1
   - Count of watchers: 1
   - Count of forks: 0
 * NPM download stats (optional):
   - Downloads in the last day: 858,414
   - Downloads in the last week: 4,607,545
   - Downloads in the last month: 17,134,389

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by clairetsai818** [comment]
@PeterDaveHello please help me review this, thanks.

**Comment by clairetsai818** [comment]
@PeterDaveHello I've modified the nom name. Please help me revise this, thanks.

**Comment by PeterDaveHello** [comment]
@clairetsai818 However, the popularity is not enough, you need to confirm that first.

**Comment by clairetsai818** [comment]
@PeterDaveHello Sorry I didn't notice that. Shall we close issue #10212?

**Comment by PeterDaveHello** [comment]
@clairetsai818 Nope, I'll explain the conventions about the popularity to the issuer first. e.g. https://github.com/cdnjs/cdnjs/issues/10216#issuecomment-273477835

**Comment by PeterDaveHello** [comment]
@clairetsai818 Take a look at the example first, it'll show you how to deal with it.

**Comment by PeterDaveHello** [comment]
@clairetsai818 you should not close without giving a reason/note.

**Comment by clairetsai818** [comment]
This PR will be close because issue #10212 closed due to no response.

**Comment by clairetsai818** [comment]
This PR will be close because issue #10212 closed due to no response.

**Pull request closed without merging**
