### PR TITLE
add dom-to-image w/ npm auto-update 

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #8589
@x09326 please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/tsayen/dom-to-image
- Official website (optional, not the repository):
- NPM package url (optional): https://www.npmjs.com/package/dom-to-image
- GitHub / Bitbucket popularity (required):
  - Count of stars: 182
  - Count of watchers: 9
  - Count of forks: 46
- NPM download stats (optional):
  - Downloads in the last day: 11
  - Downloads in the last week: 184
  - Downloads in the last month: 770
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [x] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [x] More than 500 downloads stats per month on npm registry
- [ ] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
Some versions have different naming for the src and dist file, would you please make them the same? Maybe could ask the author for suggestions, thanks.

**Comment by kennynaoh** [comment]
The author said `domvas is a separate project, this lib is originally it's fork`, so I think we don't need to add this file under `src/` in some of old versions.
@pvnr0082t , @x09326 
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by x09326** [comment]
@kennynaoh 
Please rebase with the latest master branch, thanks.

**Comment by kennynaoh** [comment]
@pvnr0082t , @x09326 
I have rebased to the latest master br.
Please help me review it again.
Thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
