### PR TITLE
[new][author] add css-material-colors

### PR DESCRIPTION
**Pull request by sivot**
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/sivot/css-material-colors.git
 * Official website (optional, not the repository): n.a.
 * NPM package url (optional): n.a.
 * GitHub / Bitbucket popularity (required):
   - Count of stars: n.a.
   - Count of watchers: n.a.
   - Count of forks: n.a.
 * NPM download stats (optional):
   - Downloads in the last day: n.a.
   - Downloads in the last week: n.a.
   - Downloads in the last month: n.a.

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sivot** [comment]
**Could somebody please help me?**
 ci/circleci — Your tests failed on CircleCI

> ✗ css-material-colors: useless fields check 
>         » css-material-colors: we don't need bin, jshintConfig, eslintConfig, styles, install, typescript, browserify, browser, jam, jest, scripts, devDependencies, main, peerDependencies, contributors, bugs, gitHEAD, issues, files, ignore, engines, engine, directories and maintainers fields in package.json // valid-packages-test.js:288 
>   ✗ Broken » 32360 honored ∙ 1 broken (8.419s) 
>   npm ERR! Test failed.  See above for more details.

**Comment by PeterDaveHello** [comment]
Hi @sivot ,

Thanks for this PR, however, this library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue and send a PR, I'll respectfully suggest you to send it again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

Best,
Peter

**Comment by sivot** [comment]
@PeterDaveHello Ooookay, thanks. It's my first public project, and first PR. There is too many info for me at first time. Thanks for experience. You can close this issue calmly.

**Comment by PeterDaveHello** [comment]
Thanks.

**Pull request closed without merging**
