### PR TITLE
[new] add react-router-active-component

### PR DESCRIPTION
**Pull request by pcarrier**

### CODE REVIEW

**Comment by maruilian11** [comment]
thank you for your contribution, but you also need to add the files need updated, or it won't pass the test.

**Comment by pcarrier** [comment]
Well, please let me know if there's anything I can do to help :)

**Comment by PeterDaveHello** [comment]
Any updates?

**Comment by maruilian11** [comment]
@pcarrier for this lib, we can only wait until it have enough popularity. of course, if you can still send PRs  to add another lib with enough popularity. before that, please remember to read our document first. thank you!

**Pull request closed without merging**
