### PR TITLE
[Update] startbootstrap-sb-admin-2 to 4.0.6

### PR DESCRIPTION
**Pull request by oliverbooth**
Also add missing versions including 4.0.0 to 4.0.5

## Profile of the lib

* Git repository (required): https://github.com/BlackrockDigital/startbootstrap-sb-admin-2
* Official website (optional, not the repository): https://startbootstrap.com/previews/sb-admin-2/
* NPM package url (optional):
* License and its reference:
* GitHub / Bitbucket popularity (required):
  * Count of watchers: 447
  * Count of stars: 6719
  * Count of forks: 4009
* NPM download stats (optional):
  * Downloads in the last day:
  * Downloads in the last week:
  * Downloads in the last month:

## Essential checklist

* [ ] I'm the author of this library
  * [ ] I would like to add link to the page of this library on CDNJS on website / readme
* [ ] This lib was not found on cdnjs repo
* [ ] Doesn't already exist / has duplicate issue and PR
* [ ] The lib has notable popularity
  * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [ ] More than 800 downloads stats per month on npm registry
* [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [ ] Has valid tags for each versions (for git auto-update)
* [ ] Auto-update setup
* [ ] Auto-update target/source is valid.
* [ ] Auto-update filemap is correct.

## Git commit checklist

* [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [x] The parent of the commit(s) in the PR is not older than 3 days.
* [x] Pull request is sent from a non-master branch with a meaningful name.
* [x] Separate unrelated changes into different commits.
* [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [ ] Close corresponding issue in commit message
* [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by oliverbooth** [comment]
Alright I give up with this one.

> package.json wrong indent, please use 2-spaces as indent, remove trailing spaces

I switched to 2-space indent and it's still throwing the same error. I'll let someone else take over from here

**Comment by oliverbooth** [comment]
Hey how about that, it worked that time.

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting pull requests that manually add versioned files for libraries. Instead, please ensure that the library has an up-to-date auto-update config for either NPM or Git in the cdnjs repository.

**Comment by MattIPv4** [comment]
In this case, the auto-update config in https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/startbootstrap-sb-admin-2/package.json is outdated and needs updating to match the repo structure of recent tags: https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/tree/v4.0.7

**Pull request closed without merging**
