### PR TITLE
[author] [new] add single-spa w/ npm auto-update via single package.json

### PR DESCRIPTION
**Pull request by frehner**
# Pull request template for new library

Pull request for issue: # n/a ?
Related issue(s): # # n/a ?

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

## Profile of the lib

* Git repository (required): https://github.com/CanopyTax/single-spa
* Official website (optional, not the repository): https://single-spa.js.org
* NPM package url (optional): https://www.npmjs.com/package/single-spa
* License and its reference: MIT https://github.com/CanopyTax/single-spa/blob/master/LICENSE
* GitHub / Bitbucket popularity (required):
  * Count of watchers: 100
  * Count of stars: 2065
  * Count of forks: 183
* NPM download stats (optional):
  * Downloads in the last day:
  * Downloads in the last week: 5582
  * Downloads in the last month: 

## Essential checklist

* [x] I'm the author of this library - _I'm a maintainer, does that count?_
  * [x] I would like to add link to the page of this library on CDNJS on website / readme
* [x] This lib was not found on cdnjs repo
* [x] Doesn't already exist / has duplicate issue and PR
* [x] The lib has notable popularity
  * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  * [x] More than 800 downloads stats per month on npm registry
* [x] Project has public repository on famous online hosting platform (or been hosted on npm)

## Auto-update checklist

* [ ] Has valid tags for each versions (for git auto-update)
* [ ] Auto-update setup
* [ ] Auto-update target/source is valid.
* [ ] Auto-update filemap is correct.

## Git commit checklist

* [x] The first line of commit message is less then 50 chars; clean, clear and easy to understand.
* [x] The parent of the commit(s) in the PR is not older than 3 days.
* [x] Pull request is sent from a non-master branch with a meaningful name.
* [x] Separate unrelated changes into different commits.
* [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
* [ ] Close corresponding issue in commit message
* [ ] Mention related issue(s), people in commit message, comment.

Sorry, first time adding a library to cdnjs. I was unclear on some of the checklist items, so please let me know if I need to fix or change something. I tried to follow all the docs and guides that I could, but I probably missed something...

Thank you!

### CODE REVIEW

**Comment by frehner** [comment]
ah looks like I need to remove `main` `module` and `bugs` I think?

**Comment by frehner** [comment]
oh, should I remove `repository` as well? I _think_ that's what it's saying...?

**Comment by frehner** [comment]
hm, ok, I'm kind of stumped. Based off the tarball I download from npmjs, here's my project's folder structure:
```
-lib
--umd
---single-spa.min.js
--esm
---single-spa.min.js
```
and based off the package.json I have, my `basePath` is `lib` so that should be removed from the final directory structure based off the docs here https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md#23-auto-update-example

so my final filename should be `umd/single-spa.min.js` right? But that's not right because the script can't find it. What did I miss? :)

**Comment by frehner** [comment]
Sorry, I'm a little unclear on what happens next -- is there something I need to do, or do I just wait for it to get merged, or is there something else?

**Comment by joeldenning** [comment]
bump

**Comment by PeterDaveHello** [comment]
@frehner can you confirm that the structure in the old versions is also working on CDN / browser client-side? Thanks. We're close to merge it :tada: 

```
   ├── jquery-support.js
   ├── single-spa-child-app-error.js
   ├── single-spa.helpers.js
   └── single-spa.js
```
```
   ├── esm
   │   ├── single-spa.js
   │   └── single-spa.js.map
   └── umd
       ├── single-spa.js
       └── single-spa.js.map
```

**Comment by joeldenning** [comment]
@PeterDaveHello are you looking at single-spa@2.x? The jquery-support.js, single-spa-child-app-error.js, and single-spa.helpers.js files do not work in the browser -- they're in CJS format. The last publish to single-spa@2 was in August 2016. In single-spa@>=3 we cleaned up our build process so that the `lib` directory only had files that work in the browser.

Is having those files in the lib directory in versions 2.x a problem? @frehner and I are both members of the single-spa core team, and we'd be fine with only single-spa@>=3.x (or even 4.x) being put on cdnjs.com.

**Comment by PeterDaveHello** [comment]
@joeldenning The auto-updater will fetch all matched versions and files, so that's why I'd like to confirm, it's fine to host version >= v3.0 only, but i'll also be great to host some old versions if the effort are very small ;) 

So those versions with these 3 files, can I simply remove all the 3 files(some of them has only 2 of these files) and keep the remaining? Or all the versions contain any of these 3 files should be removed as they'll not work?

**Comment by joeldenning** [comment]
I just looked at [the published single-spa.js](https://unpkg.com/single-spa@2.1.8/lib/single-spa.js) for single-spa@2, and it looks like it is also in CJS format and would not actually work in the browser. So actually none of the files for single-spa@2 were ones that work via script tag.

Early on in the development of single-spa, we counted on single-spa being bundled by webpack/browserify/rollup and it wasn't actually useable via script tag. It wasn't until [single-spa@3.0.0](https://unpkg.com/single-spa@3.0.0/lib/single-spa.js) that we actually started publishing a UMD version that works via script tag.

So I think the best option might actually be to exclude single-spa@2 and below from cdnjs.com.

**Comment by PeterDaveHello** [comment]
@joeldenning 👌 thanks

**Comment by joeldenning** [comment]
Any updates on this?

**Comment by frehner** [comment]
Thank you for your work on this :)

**Pull request merged**
