### PR TITLE
Backfill 10up-sanitize.css v11.0.0

### PR DESCRIPTION
**Pull request by kernc**
Backfill 10up-sanitize.css v11.0.0 (the current version).

Ref: https://github.com/cdnjs/cdnjs/pull/13843

The prospect of having to use a different, inferior CDN for this single resource bugs me so. :sweat_smile: 

Files from said git tag, minified via www.cssminifier.com. Hope it's ok. Will [SRIs](https://github.com/cdnjs/SRIs/blob/8abe5e01929157e317400b50d243e99202b7af80/10up-sanitize.css/11.0.0.json) update automatically?

Thanks.

### CODE REVIEW

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting pull requests that manually add versioned files for libraries.

I recommend reaching out to the author of this library and asking them to publish a new patch release, so that the auto-update bot picks it up and pulls in the new files for that version.

**Comment by kernc** [comment]
Thanks, that's reasonable.

Would a patch release be possible, @jonathantneal? :sun_with_face:

**Comment by jonathantneal** [comment]
Yes. Tagging releases is a habit I am long behind on.

**Comment by kernc** [comment]
@jonathantneal Respectful ping on the above issue. Sanitize.css seems to be [gaining tract](https://www.npmjs.com/package/sanitize.css?activeTab=dependencies) — please find time publish a patch release to make the new files (since Sanitize.css 9.x!) available over CDNjs. <3

**Comment by jonathantneal** [comment]
Thank you for your respectful ping, @kernc. I’ve published new tags for versions 9, 10, and then 11 at https://github.com/csstools/sanitize.css/releases

Would you please let me know if there is more that I can do to help?

**Comment by kernc** [comment]
Thank you. Seems like CDNjs is configured to prefer fetching from npm.
https://github.com/cdnjs/cdnjs/blob/d2702897d8121d7d6408d0786e55c060d4125621/ajax/libs/10up-sanitize.css/package.json#L25-L33
I assume as @MattIPv4 indicated, since [versions up to 11.0.0 are already committed](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/10up-sanitize.css), a _new version_ (e.g. 11.0.1) would have to be pushed to _npm_ to have the CDNjs bot pick it up. Slightly awkward, but nobody should mind. :blush:

**Comment by jonathantneal** [comment]
Hey, that helps me understand the desire to bump, and it would help the users, so let me do this. I’ll have a few minutes in about a half hour. Stay tuned.

**Comment by kernc** [comment]
@jonathantneal Any news? :sweat_smile: Releases rarely go according to schedules, more so when we take just minutes to make them.

**Comment by jonathantneal** [comment]
@kernc, would you let me know if 11.0.1 is correctly published for cdnjs?

**Comment by kernc** [comment]
While not yet featured in the [web ui](https://cdnjs.com/libraries/10up-sanitize.css), it's been picked by the bot (https://github.com/cdnjs/cdnjs/commit/96746425b638bb76f4e8956219fc274494be04b9) and is serving.

Thank you! :100:

**Pull request closed without merging**
