### PR TITLE
initial lightservice.js 9.1.0 lib to cdn

### PR DESCRIPTION
**Pull request by contactsamie**
NEW pull request

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

# Profile of the lib
 * Git repository (required):https://github.com/contactsamie/LightService
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/lightservice
 * GitHub / Bitbucket popularity (required):
   - Count of stars:1
   - Count of watchers:1
   - Count of folks:1
 * NPM download stats (optional):
   - Downloads in the last day:18
   - Downloads in the last week:1064
   - Downloads in the last month:1695

# Essential checklist
 * [Y ] I'm the author of this library
   * [Y ] I would like to add link to the page of this library on CDNJS on website / readme
 * [Y ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [Y ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [Y ] Has valid tags for each versions (for git auto-update)
 * [Y ] Auto-update setup
 * [Y ] Auto-update target/source is valid.
 * [ Y] Auto-update filemap is correct.

# Git commit checklist
 * [Y ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [Y ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by contactsamie** [comment]
New pull request

**Comment by PeterDaveHello** [comment]
@contactsamie would you please squash/fixup them into only one commit? THANKS.

**Comment by contactsamie** [comment]
ok

**Comment by PeterDaveHello** [comment]
#7047

**Pull request closed without merging**
