### PR TITLE
[New] Manually add backbone.paginator@2.0.6 & update its homepage

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #11545

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/backbone-paginator/backbone.paginator
 * Official website (optional, not the repository): https://backbone-paginator.github.io/backbone.paginator/api/
 * NPM package url (optional): https://www.npmjs.com/package/backbone.paginator
 * License and its reference: [MIT](https://github.com/backbone-paginator/backbone.paginator/blob/master/LICENSE-MIT)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 59
   - Count of stars: 1,469
   - Count of forks: 281
 * NPM download stats (optional):
   - 2,329 downloads in the last day
   - 11,974 downloads in the last week
   - 49,467 downloads in the last month 

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by extend1994** [comment]
1. Use `https://backbone-paginator.github.io/backbone.paginator/api/` as the homepage instead of `https://backbone-paginator.github.io/backbone.paginator/` because the later one is always redirected to the former one.
2. The files in backbone.paginator@2.0.6 on npm are the same as the the commit tree https://github.com/backbone-paginator/backbone.paginator/tree/d80ca918ef6ca79a022490dbea75b60cd1a5acc6.

**Comment by sufuf3** [comment]
@extend1994 I think we just need to cc author when we add the new library.
But this PR just update the version and package.json, should we cc the author?

**Comment by extend1994** [comment]
@sufuf3 I think we don't need by referring the PRs opened before. So I remove `cc` part. Please help me review it, thanks.

**Comment by maruilian11** [comment]
How about we directly turn to use npm auto-update since it has the latest version, but git repo didn't add a tag.

**Comment by extend1994** [comment]
@maruilian11 v0.15 ~ v0.8 are only on GitHub.

**Comment by maruilian11** [comment]
@extend1994 Yes, but we can manually add them. But keeping updating the latest version is more important, right?

**Comment by extend1994** [comment]
@maruilian11 the current latest version is v2.0.6 which is also what I add in this pull request. The author(s) could release future versions in both platform. So I think it's find to use git auto-update.

**Comment by PeterDaveHello** [comment]
The discussion here looks a little bit strange here.
1. We should update the new version first.
2. The missing versions can be added manually later.
3. The versions on GitHub but not on npm seem already hosted.

**Comment by extend1994** [comment]
@PeterDaveHello 
For the first point, do you mean the order of two commits should be exchanged?
For the third point , I think I forgot that when I replied maruilian11 thought I had known that. Sorry...

**Comment by PeterDaveHello** [comment]
I mean we don't need to wait for the old version discussion here.

BTW, I don't even think we need to manually add the old versions, as you can see in https://github.com/backbone-paginator/backbone.paginator/issues/380, just simply ping the author politely, the problem fixed. No pull request needed, not review waiting needed, because the problem is clear enough.

**Comment by extend1994** [comment]
OK, thank you!

**Pull request merged**
