### PR TITLE
Update balance-text to v3 w/ git auto-update

### PR DESCRIPTION
**Pull request by redmunds**
Update package.json & auto-update config of balance-text. Here's the situation that I am trying to handle:

* Up to and including v2.x, the executable is jquery.balancetext.js/jquery.balancetext.min.js
* Starting with v3.0, the executable is balancetext.js/balancetext.min.js

I would like to post the new executable without removing the old ones, but my settings are not quite right.

Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:
  - Count of stars:
   - Count of forks:
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by redmunds** [comment]
Replacement for PR https://github.com/cdnjs/cdnjs/pull/10691

**Comment by PeterDaveHello** [comment]
@redmunds CI failed, would you like to try to fix it by yourself first?

**Comment by PeterDaveHello** [comment]
hmmm stil failed ...

**Comment by redmunds** [comment]
@PeterDaveHello Here's the situation that I am trying to handle:

* Up to and including v2.x, the executable is jquery.balancetext.js/jquery.balancetext.min.js
* Starting with v3.0, the executable is balancetext.js/balancetext.min.js

I would like to post the new executable without removing the old ones. Do you have any recommendations on how to accomplish that?

**Comment by PeterDaveHello** [comment]
@redmunds No problem, you can do it, or do you want technical help?

**Comment by PeterDaveHello** [comment]
@redmunds BTW,  I'll suggest you to clearify the PR title and commit message first, they are too fuzy that nobody can recognize which library you are working on from them.

**Comment by redmunds** [comment]
@PeterDaveHello 

> No problem, you can do it, or do you want technical help?

I need help

>  I'll suggest you to clearify the PR title and commit message first, they are too fuzy that nobody can recognize which library you are working on from them.

I added repo name to PR Title.

**Comment by PeterDaveHello** [comment]
@sufuf3 please help @redmunds review and fix the errors 😄 

@redmunds if you are interested in free and open source contribution and would like to learn something, I'll respectfully make your request much more clear, like, what kind of help do you need, which error message you cannot understand, etc. So that we can help you efficiently and more accurately, but no worries, we'll be very happy to help you solve the problems 👍

**Comment by redmunds** [comment]
@PeterDaveHello 

> ... what kind of help do you need, which error message you cannot understand ...

My goal is described in [this short comment](https://github.com/cdnjs/cdnjs/pull/10744#issuecomment-282902512). I think this is the main error:

```
./ajax/libs/balance-text/2.0.0/balancetext.min.js does not exist but is referenced in package.json!
```

As I described above, `balancetext.min.js` will only exist for v3 and higher, so my configuration seems to be wrong for what I want to do. I am not sure if what I want is possible (although you said it was) and I don't know how to fix it.

Maybe I need to start a new project for v3 called something like `balance-text-vanilla` ?

**Comment by redmunds** [comment]
Could it be because package.json has `"version": "2.0.0"` ? I was told that would be automatically updated, so I didn't change it to `"3.0.0"`.

**Comment by maruilian11** [comment]
Hi @redmunds, if you modify `filename`, you need to also add the real file(`balancetext.js` and `balancetext.min.js`). Our test will check if the `filename` file exist.

**Comment by sufuf3** [comment]
@redmunds Thank you.
In this commit, please do the following:
1. modifiy the `package.json` : 
1-1. `filename": "balancetext.min.js",` -> `"filename": "jquery.balancetext.min.js",`
1-2.
```
        "files": [
          "*balancetext*.js"
        ]
```
to 
```
        "files": [
          "jquery.balancetext.js",
          "jquery.balancetext.min.js"
        ]

```
3. change the commit message to 
```
Update description and keywords of balance-text

cc #10691
```

then, add another commit with following:
1. Add the folder `3.0.0` and include `balancetext.js` and `balancetext.min.js`.
2. modified `package.json`:
2-1. `"version": "2.0.0",` to `"version": "3.0.0",`
2-2. `"filename": "jquery.balancetext.min.js",` -> `filename": "balancetext.min.js",`
2-3. 
```
        "files": [
          "jquery.balancetext.js",
          "jquery.balancetext.min.js"
        ]

```
to
```
        "files": [
          "balancetext*.js"
        ]
```
3. commit message 
```
Add balance-text@3.0.0 w/ git auto-update 

close #10691
```

**Comment by redmunds** [comment]
@sufuf3 Thanks for the detailed directions.

The first commit you describe is the existing state of balance-text lib, so nothing to do there, correct?

The second commit is what I already have, except for the version number, correct? I just pushed a new commit to my branch for that change.

Yes, I know that commits should be squashed with very clear names, but I'd like to see if this solves the problem first. If so, can squashing and commit renaming be done when merging?

Thanks again.

**Comment by sufuf3** [comment]
@redmunds because your pull requests will run in a CI server.
In order to make them pass, we should split the commit, and do these step.

You could refer to the reference: https://github.com/cdnjs/cdnjs/pull/10386/commits

Thank you.

**Comment by PeterDaveHello** [comment]
@redmunds are you using GitHub gui or git command line on this PR?

**Comment by redmunds** [comment]
@PeterDaveHello 

> are you using GitHub gui or git command line on this PR?

Neither :) I'm using the github web interface. I prefer command line, but the repo takes me hours to clone on a 50MB line.

**Comment by PeterDaveHello** [comment]
@redmunds thanks for reply, would you please add the files for v3? Otherwise you can not directly update version and filename here.

**Comment by PeterDaveHello** [comment]
@redmunds thanks!
@sufuf3 time for you to practice to rebase and squash commits for contributors!

**Comment by sufuf3** [comment]
@redmunds please make sure that you have checked allow edits from maintainers.
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by PeterDaveHello** [comment]
@sufuf3 it should be checked already.

**Comment by PeterDaveHello** [comment]
@hare1039 please don't approve before CI test passed.

**Comment by maruilian11** [comment]
@PeterDaveHello I think `filename` and `autoupdate` should modify in `Add balance-text@3.0.0 w/ git auto-update`, should I help do the modify directly? Or it's fine in this case?

**Comment by maruilian11** [comment]
@sufuf3 `filename` and `autoupdate` should modify with adding `3.0.0`. and we just update `autoupdate`, not add it.

**Comment by sufuf3** [comment]
@maruilian11  I did like to know that you mean as following?
1. In first commit, just update description and keywords.
the commit message as following?
```
Update balance-text package.json info, cc #10691

description and keywords
```
2. update `filename` and `autoupdate` form `package.json`, add `3.0.0/balancetext.js` and `3.0.0/balancetext.min.js`.
the commit message as following?
```
Add balance-text@3.0.0 w/ git auto-update

Update filename, autoupdate, close #10691
```

Is it right?

**Comment by maruilian11** [comment]
should use sentence in commit msg description, and modify version number with adding 3.0.0.

**Comment by redmunds** [comment]
@maruilian11 Is that message for me? Unfortunately, I'm updating with web interface where only 1 file can be added/edited per commit, and commits cannot be edited/squashed. Please use Merge/Squash and commit message can be edited at that time. Thanks! cc: @PeterDaveHello

**Comment by sufuf3** [comment]
@maruilian11  Is it right as below?
1. In the first commit, just update description and keywords of `package.json`.
The commit message as the following:
```
Update balance-text package.json info, cc #10691

Update description and keywords of balance-text package.json info
```
2. Update `filename` and `autoupdate` of `package.json`, add `3.0.0/balancetext.js` and `3.0.0/balancetext.min.js`.
The commit message as the following:
```
Add balance-text@3.0.0 w/ git auto-update

Update filename, git autoupdate of balance-text package.json info.
Add balance-text@3.0.0, close #10691
```

If it is right, I'll revise it.

**Comment by PeterDaveHello** [comment]
@sufuf3 too duplicated ...

**Comment by PeterDaveHello** [comment]
@sufuf3 please just help squash and rebase with commit message:
```
Update balance-text to v3 with git auto-update

 - add balance-text v3.0.0 assets
 - add git auto-update config
 - update description, filename and keywords

Changes are listed as above, close #10691
```

**Comment by sufuf3** [comment]
@pvnr0082t @maruilian11 @extend1994 @hare1039  I modified the commit message.
Please help me review this PR again, thank you.

**Comment by maruilian11** [comment]
@PeterDaveHello I think this PR is fine.

**Comment by PeterDaveHello** [comment]
Well done 👍 !

**Pull request merged**
