### PR TITLE
Add route-recognizer@0.2.0 w/ npm auto-update

### LINKED ISSUE #8410: [Request] Add route-recognizer
**Library name:** route-recognizer
**Git repository url:**https://github.com/tildeio/route-recognizer
**npm package url(optional):** https://www.npmjs.com/package/route-recognizer
**License(s):**MIT
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35660808-request-add-route-recognizer?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by x09326**
PR for #8410 
@pvnr0082t please help me review it, thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required):https://github.com/tildeio/route-recognizer
- Official website (optional, not the repository):
- NPM package url (optional):https://www.npmjs.com/package/route-recognizer
- GitHub / Bitbucket popularity (required):
  - Count of stars:314
  - Count of watchers:33
  - Count of forks:70
- NPM download stats (optional):
  - Downloads in the last day:12
  - Downloads in the last week:828
  - Downloads in the last month:2851
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [x] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [x] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [x] More than 500 downloads stats per month on npm registry
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

close #8410, cc @rwjblue

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@x09326 Please add `keywords` in package.json.

**Comment by pvnr0082t** [comment]
@x09326 Why you minified the files under `dist/es6` without map?

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by PeterDaveHello** [comment]
move to #11497

**Pull request closed without merging**
