### PR TITLE
add ramjet.js 0.5.0

### LINKED ISSUE #7191: [Request] Add ramjet
**Library name:** ramjet
**Git repository url:** https://github.com/Rich-Harris/ramjet
**npm package url(optional):** ramjet

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #7191 
@PeterDaveHello please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/Rich-Harris/ramjet
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 4780
   - Count of watchers: 130
   - Count of forks: 174
 * NPM download stats (optional):
   - Downloads in the last day: 0
   - Downloads in the last week: 31
   - Downloads in the last month: 133

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

autoupdate config added, close #7191, cc @Rich-Harris

### CODE REVIEW

**Comment by kennynaoh** [comment]
I have tagged x09326 to check my pull request.
Thanks

**Comment by PeterDaveHello** [comment]
@kennynaoh You should tag me to review your PR, not to @cdnjs/intern2 until you finished the first training.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
OK!
I already updated the comment about changing the tag to you.
Thanks.

**Comment by PeterDaveHello** [comment]
Please minify ramjet.es6.js

**Comment by kennynaoh** [comment]
When I minify ramjet.es6.js, I met a problem.
Error message:
Parse error at ./ramjet.es6.js:517,7
Unexpected token: keyword (default)
Please help me to check this error.
Thanks.

**Comment by PeterDaveHello** [comment]
@kennynaoh Have you tried other js minifiers?

**Comment by kennynaoh** [comment]
Not yet.
Maybe I can try javascript-/cssminifier.com
Thanks.

**Comment by PeterDaveHello** [comment]
There are maybe minifier that, if more than 3 minifier can not work, we can just leave it.

**Comment by PeterDaveHello** [comment]
Since it's es6, there may not be any of well know minifiers support it, so leave alone.

**Comment by PeterDaveHello** [comment]
So let's rebase this branch with our latest master branch.

**Comment by kennynaoh** [comment]
I have rebased already.
Thanks.

**Comment by PeterDaveHello** [comment]
Thanks.

**Pull request merged**
