### PR TITLE
add bootstrap-sweetalert@1.0.0 w/ npm autoupdate

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #7952 
Add the latest version of bootstrap-sweetalert and use __npm auto-update__ instead of git auto-update

@x09326 Please help me review this pull request, thank you.

### CODE REVIEW

**Comment by x09326** [comment]
@PeterDaveHello 
I think this PR is okay, please help me review it, thanks.

**Comment by PeterDaveHello** [comment]
@pvnr0082t please separate the npm auto-update config and the version 1.0.0 into two commits.

**Comment by pvnr0082t** [comment]
@x09326 I have separated into 3 commit. Please help me review again, thank you.

**Comment by PeterDaveHello** [comment]
The 2nd and 3rd commit, you didn't mention the lib name.

**Comment by pvnr0082t** [comment]
@x09326 I have updated the commit message. Please help me review again, thank you.

**Comment by x09326** [comment]
@PeterDaveHello 
I think this PR is okay, please help me review it, thanks.

**Comment by PeterDaveHello** [comment]
Why don't you update the filename and version in 	ae117b0 but in 47ca308?

**Comment by pvnr0082t** [comment]
I just wanted to make the changes look more clearly.  So is the related changes in the same commit  better? @PeterDaveHello

**Comment by PeterDaveHello** [comment]
They are just the same thing, you should make every commit pass the test.

**Comment by pvnr0082t** [comment]
@x09326 I have updated commits. Please help me review again, thank you.

**Comment by PeterDaveHello** [comment]
Please mention the filename change.

**Comment by pvnr0082t** [comment]
@x09326 I have updated commit message. Please help me review again, thank you.

**Comment by x09326** [comment]
@PeterDaveHello 
I think this PR is okay, please help me review it, thanks.

**Pull request merged**
