### PR TITLE
add wnumb v1.0.2 with npm autoupdate config

### LINKED ISSUE #7607: [Request] Add wNumb
**Library name:** wNumb.js
**Git repository url:** https://github.com/leongersen/wnumb
**License(s):** WTFPL
**Official homepage:** http://refreshless.com/wnumb/

### PR DESCRIPTION
**Pull request by dannyxx001**
PR for #7607 
@pvnr0082t please help me review this PR, thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/leongersen/wnumb
 * Official website (optional, not the repository): http://refreshless.com/wnumb/
 * NPM package url (optional): https://www.npmjs.com/package/wnumb
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 34
   - Count of watchers: 3
   - Count of forks: 13
 * NPM download stats (optional):
   - Downloads in the last day: 146
   - Downloads in the last week: 710
   - Downloads in the last month: 2125

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7607, cc @leongersen

### CODE REVIEW

**Comment by pvnr0082t** [comment]
@dannyxx001 Issue #7579 also related. Please mention it in the commit message.

**Comment by PeterDaveHello** [comment]
@pvnr0082t nice catch!

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this pull request is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
@dannyxx001 should mention another issue in commit message for future trace.

**Comment by dannyxx001** [comment]
OK, I had updated it.

**Comment by dannyxx001** [comment]
OK, I had updated it again. @pvnr0082t Please help me review again.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
Thanks.

**Pull request merged**
