### PR TITLE
Add license of joopl, cc #5500

### PR DESCRIPTION
**Pull request by NiniHsu**
http://matiasfidemraizer.com/joopl/

### CODE REVIEW

**Comment by NiniHsu** [comment]
@kennynaoh
Please help me check this PR.
Thank you!

**Comment by kennynaoh** [comment]
@NiniHsu 
What's the detail of `Apache`?
Please take a look at this https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json.
Thanks!

**Comment by NiniHsu** [comment]
@kennynaoh 
I added the detail.
Please check it.
Thank you!

**Comment by kennynaoh** [comment]
LGTM
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
@NiniHsu You just need  to use `Add license of joopl, cc #5500` as commit message. You don't need to add `v2`.

**Comment by pvnr0082t** [comment]
@NiniHsu You need to give a **meaningful branch name** next time. It's `patch-5` now...

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
