### PR TITLE
Add license of mogl, cc #5500

### PR DESCRIPTION
**Pull request by sufuf3**
Reference: https://github.com/projectBS/MoGL/blob/master/doc/0.2/Matrix_.md

### CODE REVIEW

**Comment by sufuf3** [comment]
@kennynaoh please help me review it, thanks!

**Comment by kennynaoh** [comment]
@sufuf3 Sorry for late response. Please rebase to the latest master branch. Thanks!

**Comment by kennynaoh** [comment]
You can use this https://github.com/projectBS/MoGL/blob/master/doc/0.2/Matrix_.md#constructor next time. It's more clear, thanks!

**Comment by sufuf3** [comment]
@kennynaoh please help me review it again, thanks!

**Pull request merged**
