### PR TITLE
Add terra.js

### PR DESCRIPTION
**Pull request by rileyjshaw**
Source: https://github.com/rileyjshaw/terra.git

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Don't you wanna add it now? @rileyjshaw

**Comment by rileyjshaw** [comment]
@PeterDaveHello I actually realized that it's hosted elsewhere, and since it's not on npm auto-updating would be a bit tricky. Overall I don't think that it's a great fit.

Thanks for checking, though!

**Comment by PeterDaveHello** [comment]
We also support git auto-update, if you want.

**Comment by rileyjshaw** [comment]
@PeterDaveHello that's alright - thanks though!

In the meantime, I think [this](https://github.com/cdnjs/cdnjs/pull/4578) one's ready to go

**Pull request closed without merging**
