### PR TITLE
[author][new] Added react-slick

### PR DESCRIPTION
**Pull request by akiran**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please squash these two commits into only one commit, thank you.

**Comment by akiran** [comment]
Squashed  commits

**Comment by akiran** [comment]
@PeterDaveHello  How long it will take to appear on cdn ?

**Comment by PeterDaveHello** [comment]
About 15 mins, you can use it now, via https://cdnjs.cloudflare.com/ajax/libs/react-slick/0.3.1/react-slick.min.js, though we have problem on website so the index didn't been updated, sorry for the inconvenience.

**Comment by akiran** [comment]
Thanks

On Wed, Feb 11, 2015 at 10:01 PM, Peter Dave Hello <notifications@github.com

**Comment by PeterDaveHello** [comment]
np

**Pull request merged**
