### PR TITLE
update auto-update config of inferno

### LINKED ISSUE #10886: Update inferno auto-update rule for v1.4.1
There seems to be some ts files now 😓

### PR DESCRIPTION
**Pull request by pvnr0082t**
update auto-update config to exclude *.ts files

Pull request for issue: #10886 
@cdnjs/intern2 Please help me review this pull request, thank you.

# Profile of the lib
 * Git repository (required): https://github.com/infernojs/inferno
 * NPM package url (optional):https://www.npmjs.com/package/inferno

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
What about index.js?

**Comment by PeterDaveHello** [comment]
@pvnr0082t would you please also confirm that if we need other js files? thanks

**Comment by PeterDaveHello** [comment]
Any updates?

**Comment by pvnr0082t** [comment]
After discussed in https://github.com/infernojs/inferno/issues/958, we only need `inferno.js` and `inferno.min.js`. I have modified the auto-update config. @cdnjs/intern2 @maruilian11 Please help me review this PR, thank you.

**Pull request merged**
