### PR TITLE
Add vue-toasted@1.1.21 w/ npm auto-update

### LINKED ISSUE #12017: [Request] Add vue-toasted
**Library name:** vue-toasted
**Library description:** Toast for Vuejs apps
**Git repository url:** https://github.com/shakee93/vue-toasted
**npm package name or url** (if there is one): https://www.npmjs.com/package/vue-toasted
**License (List them all if it's multiple):** MIT
**Official homepage:** https://shakee93.github.io/vue-toasted/
**Wanna say something? Leave message here:** Seem promising and very useful, not very popular right now but can be.

### PR DESCRIPTION
**Pull request by venkatramanareddy**
close #12017, cc @paulogdm

Pull request for issue: #12017 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/shakee93/vue-toasted
 * Official website (optional, not the repository): https://shakee93.github.io/vue-toasted/
 * NPM package url (optional): https://www.npmjs.com/package/vue-toasted
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 8
   - Count of stars: 283
   - Count of forks: 37
 * NPM download stats (optional):
   - Downloads in the last day: 208
   - Downloads in the last week: 1232
   - Downloads in the last month: 6482

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by venkatramanareddy** [comment]
@maruilian11 I've updated the homepage

**Comment by maruilian11** [comment]
@venkatramanareddy Any reason to cc `paulogdm` rather than `shakee93`?

**Comment by PeterDaveHello** [comment]
One more review please.

**Comment by shakee93** [comment]
Hello there, i am the author of this plugin.. how can i help this to get merged ?

**Comment by sufuf3** [comment]
@venkatramanareddy Thanks for your contribution.

@shakee93 Thanks for pay attention at this PR.
Let's wait for reviewers review.
I think this PR will be merged soon.

Many thanks.

**Comment by shakee93** [comment]
Thank you @venkatramanareddy , @maruilian11, @sufuf3, @PeterDaveHello !!

and @paulogdm for posting the request !!

**Comment by PeterDaveHello** [comment]
@shakee93 no problems :)

**Pull request merged**
