### PR TITLE
[New] Add image-select@2.0 w/ git auto-update

### LINKED ISSUE #11776: [Request] Add Image-Select
**Library name:** Image-Select
**Library desctiption:** Image Select is an extension of Chosen, a jQuery plugin that makes long, unwieldy select boxes much more user-friendly. It provides image support for Single and Multi select HTML tags. 
**Git repository url:** https://github.com/websemantics/Image-Select
**License (List them all if it's multiple):** The MIT License (MIT)
**Official homepage:** http://websemantics.github.io/Image-Select/

### PR DESCRIPTION
**Pull request by qwe19272375**
close #11776, cc @websemantics

Pull request for issue: #11776  

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/websemantics/Image-Select
 * Official website (optional, not the repository): https://websemantics.github.io/Image-Select/
 * NPM package url (optional):
 * License and its reference: [MIT](https://github.com/websemantics/Image-Select/blob/master/LICENSE)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 11
   - Count of stars: 114
   - Count of forks: 39
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x ] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by qwe19272375** [comment]
@cdnjs/intern3 please help me review this PR, thanks!

**Comment by qwe19272375** [comment]
@cdnjs/intern3 please help me review this PR, thanks!

**Comment by extend1994** [comment]
@PeterDaveHello May I know what's the key point of deciding should we use auto-update config to grab old versions? Because you and some of us use this to grab them before. Is the file structure of this lib changed so many times that we should just manually add them?

**Comment by PeterDaveHello** [comment]
@extend1994 well, it's a good question, and it really depends.
If a few simple adjusts which makes the rules more flexible, this is acceptable, but if we need to write multiple different patterns for only old versions, I'll like to think about it, because it'll cause the maintanance complexity increasing in future, when you need to checkout or update the auto-update config, it may confuse you. That's my opinion.

Discussions are very welcome here.

**Comment by extend1994** [comment]
OK, thanks for quick reply! When I meet any example we can discuss this issue. I will propose it.

**Comment by maruilian11** [comment]
@PeterDaveHello Does it mean we don't need to modify the old version file structure to fit with the current one? If we still need to add symbolic Link for old version, which means we still need to **manually** do it.

**Comment by PeterDaveHello** [comment]
I think I say it, if that pattern can't be simplified easily, it's better to manually add them (of course who fetched the files should use auto-updater in case of manual issues, and should also provide the pattern for reviewer to test it).

cc @cdnjs/intern3

**Comment by maruilian11** [comment]
got it

**Comment by sashberd** [comment]
@sufuf3 @extend1994 What is exact things need to be done in order to fix this PR?

**Comment by sufuf3** [comment]
This PR need to be followed this requirement: https://github.com/cdnjs/cdnjs/pull/11876#pullrequestreview-67333825
Thanks

**Comment by sashberd** [comment]
@PeterDaveHello I updated the PR

As for minified version of files. It is look like lib is not maintained any more, last release before an year ago. I can open an issue, but I think we will never get answer from the authors. Thus, FYR this updated PR and merge if all is OK

**Comment by sashberd** [comment]
@PeterDaveHello Sorry, just forget to add it in the 2.0 version. Updated. FYR

**Pull request merged**
