### PR TITLE
Add git autoupdate config in rangy. close #5342

### LINKED ISSUE #5342: [Request] Update to latest Rangy, version 1.3.0
**Library name:** Rangy
**Git repository url:** https://github.com/timdown/rangy
**npm package url(optional):** 
**Official homepage:** https://github.com/timdown/rangy/releases
**Wanna say something? Leave message here:** Rangy 1.3.0 came out a few months ago and it would be great to have it hosted on the CDN. Would be great to include both core-rangy and the optional modules included with the downloads.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by Piicksarn**
@maruilian11, would you please checkout the pr for me?
The library information is shown below.
Thank you!

**`The git repository url :`** https://github.com/timdown/rangy
 - `watch` :  54
 - `star` : 715
 - `fork`  : 95

### CODE REVIEW

**Comment by maruilian11** [comment]
* [ ] Not found on cdnjs repo
* [ ] No already exist issue and PR
* [ ] Notable popularity
* [ ] Project has public repository on famous online hosting platform (or been hosted on npm)
* [ ] Has valid tags for each versions (for git auto-update)
* [ ] Auto-update setup
* [ ] Auto-update target/source is valid.
* [ ] Auto-update filemap is correct.

**Comment by PeterDaveHello** [comment]
You didn't check `Not found on cdnjs repo` ?

**Comment by Piicksarn** [comment]
@PeterDaveHello , the PR is for adding autoupdate to exit library in cdnjs.
so that the first check box is empty

**Comment by PeterDaveHello** [comment]
Oh, okay, thanks.

**Comment by PeterDaveHello** [comment]
I think we may need other files under the same directory.

**Comment by maruilian11** [comment]
@PeterDaveHello i have checked, it's not a upgrade case, so it's already on cdnjs repo.
i thought if its lib is not on cdnjs repo, then i check it.
or u mean the upgrade content not on cdnjs repo, then check it?

**Comment by Piicksarn** [comment]
@maruilian11, I have added the other files in the same directory, add need your help for checkout the PR.
Thank you!

**Comment by Piicksarn** [comment]
@maruilian11, I have added the other files in the same directory, add need your help for checkout the PR.
Thank you!

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Pull request merged**
