### PR TITLE
[Update] jQuery Countdown 2.0.2

### PR DESCRIPTION
**Pull request by swcheon**
jQuery Countdown 2.0.2
Released date: 2015-01-10
URL: http://keith-wood.name/countdown.html
Comment: jQuery Countdown is maintained this website instead of git repository. (Git repository stored a jQuery Countdown 2.0.1)

Could you please check this? @maruilian11 :)

### CODE REVIEW

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok. could u plz take a look?

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's fine. could u plz take a look?

**Comment by PeterDaveHello** [comment]
@Piicksarn can you check this?

**Comment by Piicksarn** [comment]
**Library name :** ***countdown***
**Git repository url :**https://github.com/kbwood/countdown
 - [ ] **`Not found on cdnjs repo`**----*This commit is for updating the exist lib in cdnjs.*
 - [x] No already exist issue and PR
 - [x] Notable popularity
 `Watch : 15`
 `Star : 212`
 `Fork : 80`
 - [x] Project has public repository on famous online hosting platform (or been hosted on npm)
 - [x] Has valid tags for each versions (for git auto-update)

---------------------------------------------------------------------------------------------------------------------------------------------

**Library name :** ***html5shiv***
**Git repository :** https://github.com/aFarkas/html5shiv.git
- [ ] **`Not found on cdnjs repo`**----*This commit is for updating the exist lib in cdnjs*
- [x] No already exist issue and PR
- [x] Notable popularity
`Watch : 486 `
`Star : 6050`
`Fork : 1478`
- [x] Project has public repository on famous online hosting platform (or been hosted on npm)
- [x] Has valid tags for each versions (for git auto-update)

----------------------------------------------------------------------------------------------------------------------------------------------

@swcheon, 
The PR is fine! :thumbsup:
But the branch is 32 commits behind cdnjs:master. The branch should be rebased to cdnjs:master!
Fighting!!:sparkles:

**Tip :** 
 - **` git remote add [name] [url]`**
  - example : git remote add cdnjsOrigin https://github.com/cdnjs/cdnjs.git
 - **` git pull --rebase cdnjsOrigin master`**
 - **` git push .... --force`**

**Comment by PeterDaveHello** [comment]
Nope, not at all, js files in 0a5c77c contains html in js file, and we should not put several unrelated commits in a same PR.

**Comment by drewfreyling** [comment]
@swcheon any update on this?

**Comment by PeterDaveHello** [comment]
#6526

**Pull request closed without merging**
