### PR TITLE
Add gitgraph.js v1.2.1 with git auto-update

### LINKED ISSUE #7642: [Request] Add gitgraph.js
**Library name:**  gitgraph.js
**Git repository url:** https://github.com/nicoespeon/gitgraph.js
**npm package url(optional):** https://www.npmjs.com/package/gitgraph.js
**License(s):**MIT
**Official homepage:** http://gitgraphjs.com/

### PR DESCRIPTION
**Pull request by x09326**
PR for #7642 
@kennynaoh please help me review it, thanks.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/nicoespeon/gitgraph.js
 * Official website (optional, not the repository): http://gitgraphjs.com/
 * NPM package url (optional): https://www.npmjs.com/package/gitgraph.js
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 380
   - Count of watchers: 33
   - Count of forks: 91
 * NPM download stats (optional):
   - Downloads in the last day: 0
   - Downloads in the last week: 9
   - Downloads in the last month: 35

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #7642, cc @nicoespeon

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@x09326 would you please check if the author forget to publish on npm? We prefer to use npm auto-update. Thanks.

**Comment by x09326** [comment]
Okay, I will open an issue to ask the author.

**Comment by PeterDaveHello** [comment]
@x09326 Thanks.

**Comment by x09326** [comment]
@PeterDaveHello 
The author has published latest versions of the lib on npm.
What is the next step?

**Comment by PeterDaveHello** [comment]
@x09326 I wonder if we can transfer to npm auto-update, could you take a look at the releases on both GitHub and npm, and see if there is any big difference? Like the versions, the structure, etc.

**Comment by x09326** [comment]
@PeterDaveHello 
The npm only has 2 releases, and github has 13 releases.
But the files and the **structure** we need in the ```build``` are same of the latest version v1.2.1.

**Comment by PeterDaveHello** [comment]
hmmmm ... @x09326 can you keep tracking the activity of this lib? If the author didn't forget to put the next release on npm, we can consider to transfer to npm, at least we already added the other old versions.

**Comment by x09326** [comment]
Got it.

**Comment by PeterDaveHello** [comment]
Thanks.

**Comment by x09326** [comment]
@PeterDaveHello 
They update this lib on npm with version v1.2.2.
What's next step?

**Comment by PeterDaveHello** [comment]
If it's added by the bot, that's nothing to do.

**Pull request merged**
