### PR TITLE
Update jsPlumb to version 2.0.7

### PR DESCRIPTION
**Pull request by JustinWingChungHui**
File structure has changed significantly from version 1.4.1.  There are no longer separate vanilla  and jQuery versions

# Profile of the lib
 * Git repository (required):https://github.com/sporritt/jsplumb/
 * Official website (optional, not the repository): https://jsplumbtoolkit.com/
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 2774
   - Count of watchers: 216
   - Count of forks: 725

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
There should not be a merge commit there, would you please remove it.

**Comment by JustinWingChungHui** [comment]
I've removed the merge commit.  Apologies, should have branched it first!  The author includes the version in the the file names.  Is there a way to set up auto update for that?

**Comment by PeterDaveHello** [comment]
> The author includes the version in the the file names. Is there a way to set up auto update for that?

Oops, no.

**Comment by PeterDaveHello** [comment]
I found that there are not only js files in its dist folder, maybe we should add other files in?

**Comment by JustinWingChungHui** [comment]
They aren't required according to the docs. https://jsplumbtoolkit.com/community/doc/home.html#setup
Most of the dist folder seems to be the documentation and examples.  I can put them in as well if you think its a good idea

**Comment by PeterDaveHello** [comment]
Okay, let's try it.

**Comment by JustinWingChungHui** [comment]
Thanks.  I've contacted the author to see if he would like to make newer versions more auto update compatible

**Comment by PeterDaveHello** [comment]
@JustinWingChungHui Oh that's nice, thanks a lot !

**Pull request merged**
