### PR TITLE
Add license of requirejs-plugins, cc #9248

### PR DESCRIPTION
**Pull request by sufuf3**
https://github.com/millermedeiros/requirejs-plugins/blob/master/LICENSE.txt

### CODE REVIEW

**Comment by sufuf3** [comment]
@pvnr0082t

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM

**Comment by pvnr0082t** [comment]
@sufuf3 Please give a meaningful branch name next time. :+1:

**Pull request merged**
