### PR TITLE
[new] add intl-tel-input@6.0.6 wit git auto-update, close #5313

### LINKED ISSUE #5313: [Request] Add International Telephone Input
**Library name:** International Telephone Input
**Git repository url:**https://github.com/Bluefieldscom/intl-tel-input
**npm package url(optional):** 
**Official homepage:** http://jackocnr.com/intl-tel-input.html
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by Amomo**
Hi @Piicksarn ,  I add a new lib with git auto-update from the request #5313 
repo: https://github.com/Bluefieldscom/intl-tel-input
`The library has provided a minified css file, so I didn't add one.`
Would you mind checking this PR for me? Thank you~ :-)

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `68`, Star `1,424`, Fork `235`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by Piicksarn** [comment]
@Amomo, would you mind to discuss the reason for choosing files in `img folder` (in autoupdate file map)?
Thank you!

**Comment by Amomo** [comment]
Um...I just think I should add every release files  (not including dot file, node program) into autoupdate file map.
@Piicksarn Shouldn't I set auto update for img folder?

**Comment by Amomo** [comment]
@Piicksarn I have rebased this PR, could you check it again?
Thank you~ :-D

**Comment by Piicksarn** [comment]
@Amomo, sorry for my delay..QQ..
would you mind to rebase it to master again?

**Comment by Amomo** [comment]
@Piicksarn I have rebased it, could you check it again? Thank you~ :-D

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you please checkout the pr?
And the css file in this lib has already minified. :)

**Comment by PeterDaveHello** [comment]
I think you can use `repository` instead of `repositories` because there is only one repo.

**Comment by Amomo** [comment]
@PeterDaveHello I have modified it~

**Comment by PeterDaveHello** [comment]
But you are still using an array to store it.

**Comment by Amomo** [comment]
oh! I got the point, ok, I will fix it.

**Comment by PeterDaveHello** [comment]
syntax error ... you should use git's hook to prevent this problem ...

**Comment by Amomo** [comment]
@PeterDaveHello Oh~ really useful! Thank you for told me that.😆
I pass the test locally, it would be fine this time!

**Comment by PeterDaveHello** [comment]
And we have hooks examples.
https://github.com/cdnjs/cdnjs/tree/master/hooks

**Comment by Amomo** [comment]
Oh ...I modified that line when I tried to pass the test...Forgot to fix it back...OTZ
I add the wildcard back now.

**Comment by PeterDaveHello** [comment]
Bad quality ...

**Comment by Amomo** [comment]
Sorry for letting you check again and again.
THANK U 😭

**Pull request merged**
