### PR TITLE
Add croppie@2.4.0 w/ git auto-update

### LINKED ISSUE #9577: [Request] Add croppie
**Library name:** Croppie
**Git repository url:** https://github.com/foliotek/croppie
**npm package url(optional):** https://www.npmjs.com/package/croppie
**License(s):** ISC
**Official homepage:** http://foliotek.github.io/Croppie/

### PR DESCRIPTION
**Pull request by x09326**
Pull request for issue: #9577 
Related issue(s): # #
@pvnr0082t 
Please help me review it, thanks.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/Foliotek/Croppie
 * Official website (optional, not the repository):https://foliotek.github.io/Croppie/
 * NPM package url (optional):https://www.npmjs.com/package/croppie
 * GitHub / Bitbucket popularity (required):
   - Count of stars:423
   - Count of watchers:29
   - Count of forks:182
 * NPM download stats (optional):
   - Downloads in the last day:185
   - Downloads in the last week:882
   - Downloads in the last month:3836

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9577, cc @thedustinsmith

### CODE REVIEW

**Comment by x09326** [comment]
@pvnr0082t 
I have rebased to the latest master branch.
And the author said the license is MIT.
Please help me review it, thanks.

**Comment by x09326** [comment]
@pvnr0082t 
The npm just release one more beta version.
Do I need to change to npm auto-update?

**Comment by pvnr0082t** [comment]
@PeterDaveHello The npm release one more beta version. Would it better to use npm auto-update than git auto-update?

**Comment by PeterDaveHello** [comment]
If there is only one version, may not be a problem, both fine.

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
