### PR TITLE
Added webcamjs@1.0.2

### PR DESCRIPTION
**Pull request by Jeni4**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Would you please add git auto-update config? This can be done in a additional commit. Thanks.

**Comment by PeterDaveHello** [comment]
BTW, seems there is no any tags in its repo, which is git auto-update will rely on, would you like to open an issue in its repo?

**Comment by Jeni4** [comment]
Will it be alright to implement git auto-update with my forked repo for now?
Then in the meantime contact @jhuckaby and ask for possible implementation of the package.json file and version tags?

Will this edition of package.json be possible with the above conditions?
```php
{
  "name": "webcamjs",
  "filename": "webcam.min.js",
  "version": "1.0.2",
  "description": "WebcamJS is a small standalone JavaScript library for capturing still images from your computer's camera, and delivering them to you as JPEG or PNG Data URIs. The images can then be displayed in your web page, rendered into a canvas, or submitted to your server. WebcamJS uses HTML5 getUserMedia, but provides an automatic and invisible Adobe Flash fallback.",
  "homepage": "http://pixlcore.com/read/WebcamJS",
  "maintainers": {
    "name": "Joseph Huckaby"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/jhuckaby/webcamjs.git"
  },
  "license": "MIT",
  "author": "Joseph Huckaby (http://pixlcore.com)"
  "autoupdate": {
    "source": "git",
    "target": "git://github.com/Jeni4/webcamjs.git",
    "basePath": "/dist/",
    "files": [
      "webcam.min.js",
      "webcam.js",
      "webcam.swf"
    ]
  }
}
```

**Comment by jhuckaby** [comment]
Hey guys, author of WebcamJS here.  I don't think this is going to work at all.  WebcamJS relies on an Adobe Flash SWF file, which must be hosted on the same domain as the page.  It cannot be requested from a CDN like cdnjs.  Even though people can download and host the SWF manually, this will confuse users, because by default it tries to request the SWF at the location of the JS (which would be on the CDN).  I do not like adding this kind of confusion to my users.

Also, I'd rather submit my library to CDNJS myself, and not have it being pulled from someone's fork which I do not control.

Please give me some time to research the CDNJS submission guidelines, instructions, and then make sure the Adobe Flash SWF thing is even going to work (I don't think it will).  Then I'll come back and submit this myself.

Thanks!

**Comment by Jeni4** [comment]
@jhuckaby Alright. Will respect your wishes.
My original thought came from trying to update an old site i maintain currently using you older jpegcam project, and in the middle thought it would be very nice to be able to load your project from a publicly available CDN.

**Comment by PeterDaveHello** [comment]
Thank you both, you are welcome to submit other libs.

**Comment by jhuckaby** [comment]
Thank you @Jeni4 for your interest in my library (and my old broken JPEGCam thing, hahaha).  I really had no idea CDNJS would accept submissions from smaller libraries like this, so I thank you for bringing this to my attention!  I will try to figure out how to make this work from a CDN host, and submit it soon.

Thanks @PeterDaveHello for the quick responses, and awesome service :)

**Comment by PeterDaveHello** [comment]
np, hope your lib can work with cdn in future.

**Comment by drewfreyling** [comment]
@jhuckaby For what it is worth, we would not pull it from someone's fork.

**Pull request closed without merging**
