### PR TITLE
[new] [author] Add js-cookie (former jquery-cookie)

### PR DESCRIPTION
**Pull request by FagnerMartinsBrack**
jQuery dependency was made optional in the version `1.5.0`. `js-cookie` repository contains [all `jquery-cookie` releases/tags](https://github.com/js-cookie/js-cookie/releases) since v1.

X-Ref: https://github.com/cdnjs/cdnjs/issues/4627

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
> Property is required (true): /properties/filename

It requires the "filename" property right? I see people [use](https://github.com/cdnjs/cdnjs/pull/4701/files#diff-56e8021a2281e45c7dac5f358e79d09eL3) the [filename](https://github.com/cdnjs/cdnjs/pull/4704/files#diff-3e3b074fc16b67765297884fb46029efL5) to specify the minified resource, but js-cookie, as a source repo, doesn't expose the distribution file. In this case, what should I put in that field?

> For those libs can use auto-update, you should add auto-update config for it, but as the first pull request to add a lib, you should still add its real files, or you won't pass the test.

...

> ./ajax/libs/js-cookie/2.0.0-pre/undefined does not exist but is referenced in package.json

Do I have to add all tags minified files? :tired_face:

**Comment by PeterDaveHello** [comment]
I think you should put the real files as the first PR to add a lib.

**Comment by FagnerMartinsBrack** [comment]
Is it ok to add the unminified files?

**Comment by PeterDaveHello** [comment]
It's fine.

**Comment by FagnerMartinsBrack** [comment]
@PeterDaveHello 

I made your work easier and added the minified files directly from the build of each version tag.

I have added only the versions `>= 1.5.0`. Those are the versions available only in the js-cookie project, it didn't make any sense to add the versions that already exist under jquery-cookie name.

It would be very nice to add a notice in [jquery-cookie](cdnjs.com/libraries/jquery-cookie) page on cdnjs to highlight the importance to use the latest supported version under the name js-cookie.

**Pull request merged**
