### PR TITLE
add missing PNG image of jquery.nicescroll

### LINKED ISSUE #4218: Update Nicescroll
Please update Nicescroll to the latest version 3.6.0 which fixes IE Touch Issues.

https://github.com/inuyaksa/jquery.nicescroll

Thanks.

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #4218 
@dannyxx001 Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
# Profile of the lib
- Git repository (required): https://github.com/inuyaksa/jquery.nicescroll
- Official website (optional, not the repository):
- NPM package url (optional):
- GitHub / Bitbucket popularity (required):
  - Count of stars: 2091
  - Count of watchers: 162
  - Count of forks: 813
- NPM download stats (optional):
  - Downloads in the last day:
  - Downloads in the last week:
  - Downloads in the last month:
# Essential checklist
- [ ] I'm the author of this library
  - [ ] I would like to add link to the page of this library on CDNJS on website / readme
- [ ] This lib was not found on cdnjs repo
- [x] No already exist / duplicated issue and PR
- [ ] The lib has notable popularity
  - [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
  - [ ] More than 500 downloads stats per month on npm registry
- [ ] Project has public repository on famous online hosting platform (or been hosted on npm)
# Auto-update checklist
- [ ] Has valid tags for each versions (for git auto-update)
- [ ] Auto-update setup
- [ ] Auto-update target/source is valid.
- [ ] Auto-update filemap is correct.
# Git commit checklist
- [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
- [x] The parent of the commit(s) in the PR is not old than 3 days.
- [x] Pull request is sending from a non-master branch with meaningful name.
- [x] Separate unrelated changes into different commits.
- [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
- [x] Close corresponding issue in commit message
- [x] Mention related issue(s), people in commit message, comment.

close #4218

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@pvnr0082t please tell us the process how did you get and add this files?

**Comment by dannyxx001** [comment]
I don't see the version `3.5.4` and `3.5.1` in repository. Can you explain it? Thanks.

**Comment by pvnr0082t** [comment]
@dannyxx001 @PeterDaveHello I can't not find tagged release for v3.5.1 and v3.5.4. I think the PNG image is the same so I get ```zoomico.png``` from ```v3.6.0``` for each version. I don't know whether it's ok or not.

**Comment by PeterDaveHello** [comment]
@pvnr0082t It's dangerous that you ate just guessing but you didn't tell us, we need to confirm this.

**Comment by pvnr0082t** [comment]
Sorry for that. I'll confirm it.

**Comment by PeterDaveHello** [comment]
Any updates here? Thanks!

**Comment by sufuf3** [comment]
@pvnr0082t 
as the author said https://github.com/inuyaksa/jquery.nicescroll/issues/605#issuecomment-307403953
Would you replace img of v3.5.4 and v3.5.1 from v3.4.0?
the img md5 is `0baba0c525c7c1b9dcc097b932ce033f`

Thank you.

**Comment by sufuf3** [comment]
@PeterDaveHello 
There is no response from the contributor since 12 Sep.
Could I help this and close this PR?

This should be a high priority issue.

Thanks.

**Comment by sufuf3** [comment]
@PeterDaveHello this PR is just replacing img of v3.5.4 and v3.5.1 from v3.4.0.
But I can't help improve this PR.
Also, there is no response from contributor since 15 May 2016.

What should I do for this PR?

Would you mind giving me some advice?
Many thanks.

**Comment by sashberd** [comment]
@PeterDaveHello @sufuf3 @extend1994 Cannot rebase this PR with master. Suggest to close it

**Comment by extend1994** [comment]
Close it due to no progress for long time, will help it with a new PR ASAP, cc @PeterDaveHello

**Pull request closed without merging**
