### PR TITLE
[Update] jQuery Countdown 2.0.2

### PR DESCRIPTION
**Pull request by swcheon**
jQuery Countdown 2.0.2
Released date: 2015-01-10
URL: http://keith-wood.name/countdown.html
Comment: jQuery Countdown is maintained this website instead of git repository. (Git repository stored a jQuery Countdown 2.0.1)

### CODE REVIEW

**Comment by maruilian11** [comment]
could u please also add 'jquery.countdown.min.css'? 
you can use this minify tool https://github.com/PeterDaveHello/web-minify-helper
thank you very much!

**Comment by maruilian11** [comment]
@swcheon i just find out that jQuery Countdown has been updated, please look #5304.
you could still send PR for `htmlshiv`.

**Comment by swcheon** [comment]
@maruilian11 That is different plugins. That is "The Final Countdown (jquery.countdown)" and This is "jQuery Countdown (jquery-countdown)".

**Comment by maruilian11** [comment]
@swcheon sorry, i just saw your reply, so i deleted my comment.

**Pull request closed without merging**
