### PR TITLE
[new] add fetch@0.9.0 with git auto-update, close #5089

### LINKED ISSUE #5089: [Request] Add window.fetch polyfill
>The global fetch function is an easier way to make web requests and handle responses than using an XMLHttpRequest. This polyfill is written as closely as possible to the standard Fetch specification at https://fetch.spec.whatwg.org.

Repository: https://github.com/github/fetch

**Stats:**
Latest commit 4 days ago, 310 commits since Oct 13, 2014
4040 stars
153 forks

Project for being able to use the `fetch` API in as many places as possible. Would be lovely to have in cdnjs.

Was going to add it myself but the size of this repo is too big at 1291 libraries...

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 , I add a new lib with git auto-update from the request #5089
Would you mind checking this PR for me?
Thank you~ :-)

### CODE REVIEW

**Comment by maruilian11** [comment]
can i ask u why u wrote "fetch*.js" not "fetch.js"?
and i think if u can add a new field named "requiredFile" about fetch.min.js, it will help maintainer a lot :)

**Comment by Amomo** [comment]
@maruilian11 , you are right! I should add "requiredFile" field in it.
I have done the correction, could you check it again?
Thank you~ :-)

**Comment by maruilian11** [comment]
i think it's ok. @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@maruilian11 
> can i ask u why u wrote "fetch*.js" not "fetch.js"?

`fetch*.js` is better then `fetch.js`, we don't need to add `fetch.min.js`, `fetch.debug.js` in future, and not dangerous as `*.js`.

So please use `fetch*.js`.

**Comment by Amomo** [comment]
Thanks for the reply from both of you~
I will use `fetch*.js`.
And, I still keep the the "requiredFile" field to remind future maintainer.
@maruilian11 could you check it again? :-)

**Comment by maruilian11** [comment]
thank u a lot, i will use that way next time.
@PeterDaveHello is it ok?

**Comment by PeterDaveHello** [comment]
No need to add `reuiredFiles`, please remove it. The current only min file already been pointed by `filename` field.

**Comment by maruilian11** [comment]
@Amomo sorry it's my mistake, it seems that min files didn't be pointed by filename needs required file, like <code>min.css</code>, i'm sorry :(

**Comment by Amomo** [comment]
@maruilian11, it's ok, we all learned from this case. :)
I have finished the correction in this PR and others.
Could you take a look?
Thank you for checking it again and again. :-D

**Comment by maruilian11** [comment]
@PeterDaveHello is it ok?

**Comment by PeterDaveHello** [comment]
Should rebase with latest master branch.

**Comment by Amomo** [comment]
Hello @PeterDaveHello , It has rebased with latest master branch now.
Thank both of you for checking this PR~

**Comment by PeterDaveHello** [comment]
Should tag another one to check it again next time.

**Comment by Amomo** [comment]
Thank you. I will. :-)

**Pull request merged**
