### PR TITLE
add nivo-lightbox@1.2.0 w/ git auto-update

### LINKED ISSUE #9081: new request Nivo-Lightbox
Library name: Nivo-Lightbox
Git repository url: https://github.com/gilbitron/Nivo-Lightbox
npm package url(optional): N/A
License(s): https://github.com/gilbitron/Nivo-Lightbox/blob/master/license.txt
Official homepage: https://dev7studios.com/products/nivo-lightbox-wordpress-plugin/

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #9081 
@x09326 please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/gilbitron/Nivo-Lightbox
 * Official website (optional, not the repository): https://dev7studios.com/products/nivo-lightbox-wordpress-plugin/
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 141
   - Count of watchers: 18
   - Count of forks: 74
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9081, cc @gilbitron

### CODE REVIEW

**Comment by x09326** [comment]
LGTM

**Comment by kennynaoh** [comment]
@PeterDaveHello 
Because I did the same PR https://github.com/cdnjs/cdnjs/pull/9091 of this library.
Should I close it?

**Comment by PeterDaveHello** [comment]
@kennynaoh you didn't do #9091, as I didn't see a reason need you to take over somebody else's issue, this one should be closed, btw, you can still compare the difference between these two PR, thanks.

**Comment by kennynaoh** [comment]
Sorry about that!

**Pull request closed without merging**
