### PR TITLE
Add license of r2d3, cc #5500

### PR DESCRIPTION
**Pull request by hare1039**
ref: https://github.com/mhemesath/r2d3/blob/master/LICENSE

### CODE REVIEW

**Comment by hare1039** [comment]
@kennynaoh Please check my work. Thanks.

**Comment by hare1039** [comment]
@PeterDaveHello Hi, I have changed the commit message and pushed to my fork, but I don't how to make this pull request relate to the fixed one. Should I make a new pull request?

**Comment by PeterDaveHello** [comment]
Looks like you made two additional commits, try `git reset HEAD^^^` to revert them all.

**Comment by PeterDaveHello** [comment]
Boom 💥

**Comment by hare1039** [comment]
Sorry, I was adjusting my environment. Fix it now.

**Comment by hare1039** [comment]
@PeterDaveHello I fixed it. Please check.

**Comment by PeterDaveHello** [comment]
@hare1039 Call you mentor first

**Comment by PeterDaveHello** [comment]
@hare1039 And you should wait for the CI result before ping somebody to review for you.

**Comment by kennynaoh** [comment]
LGTM
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
