### PR TITLE
[new] hello.js

### PR DESCRIPTION
**Pull request by MrSwitch**
Hi

I hope i'm not making a fudge of this submission. Given a `package.json` file with `autoupdate` will the autoupdate do the rest?

Thanks alot for a fantastic CDN

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please add its real files and add filename to point to its main file, thanks.

**Comment by MrSwitch** [comment]
@PeterDaveHello 

Is it possible to do that without cloning the entire repo? Its huge!

I can submit all the files via the github web interface, but i dont believe i can add multiple files under a single commit, or rebase via the website.

**Comment by PeterDaveHello** [comment]
If you don't mind, I can take this, I don't think we can do it without cloning the repo, however, shallow clone can help you drop old history, make the repo smaller and make the process faster.
Let me know what do you think, thanks.

**Comment by MrSwitch** [comment]
Yeah, if you have the time, please do include HelloJS. Thanks alot.

**Comment by PeterDaveHello** [comment]
Okay, sure.

**Comment by MrSwitch** [comment]
Closed by 9937c85b6a7f11321d5a3b42d6a31acf9dc9b214

Thanks @PeterDaveHello

**Pull request closed without merging**
