### PR TITLE
Add autoupdate section for marked

### PR DESCRIPTION
**Pull request by smarts**
Resolves cdnjs/cdnjs#5527

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
To keep the origin structure on cdnjs, I think you should set `basePath` to `lib` and that the auto-updater grab un-minified source only, the minified file will be added when I commit new updates. Thanks.

**Comment by smarts** [comment]
Can you specify exactly what you want? I'm new to this and I'm not quite sure what you mean. The documentation is much clearer for npm autoupdate sources than it is for a git source…

**Comment by PeterDaveHello** [comment]
As I said:
 * set `basePath` to `lib`
 * only put `marked.js` in the `files` array.
Thanks.

**Comment by smarts** [comment]
Then how will `marked.min.js` make it to the CDN?

**Comment by PeterDaveHello** [comment]
I'll do it.
https://github.com/cdnjs/cdnjs#enabling-gitrecommended-or-npm-auto-update

**Comment by smarts** [comment]
Yeah i already read that. And I maintain that the npm case is better documented. It tells about how it looks in the tarball and what is produced. That info is not detailed for the git case. And you didn't answer the question about how `marked.min.js` would end up as part of what gets CDN-ized.

**Comment by PeterDaveHello** [comment]
I think it said we'll handle the minify works :)
> ... and we may need to minify the lib without pre-minified dist files ...

**Comment by smarts** [comment]
Yikes. OK, that's good to know. That actually makes me want to avoid using cdnjs since it means I would potentially get something different than what the lib author has released on GitHub. Anyway, thanks for volunteering to do this. I'll go ahead and close this pull request.

**Comment by PeterDaveHello** [comment]
We'll support multi-filemap soon, that means the files don't need to be the same basePath, which can include the minified files and src files at the same time from source.

**Pull request closed without merging**
