### PR TITLE
Correct license typo of jquery.tipsy

### PR DESCRIPTION
**Pull request by sajochiu**
cc #9248, cc @x09326

### CODE REVIEW

**Comment by x09326** [comment]
Remember to give a meaningful branch name next time.

LGTM
@cdnjs/intern2

**Comment by pvnr0082t** [comment]
@sajochiu The license of library does not change. I think `Correct license typo of jquery.tipsy` will be better title. @x09326 How do you think.

**Comment by x09326** [comment]
Sounds good.
@sajochiu 
Please modify the commit message like @pvnr0082t said.

**Comment by pvnr0082t** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
Awesome!

**Pull request merged**
