### PR TITLE
Add wavesurfer.js@2.0.4 w/ npm auto-update & update package.json

### PR DESCRIPTION
**Pull request by thijstriemstra**
- Updated the license for wavesurfer.js.
- added missing versions: 2.0.0-beta02, 2.0.1, 2.0.2, 2.0.3, 2.0.4

I am one of the maintainers.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
I'd also like to get the auto-update going (again?) for this repository. Why is it currently not updating?

**Comment by sufuf3** [comment]
Hi @thijstriemstra
Thank you for your contribution.
I found the front-end files now release from npm not release from GitHub repo.
CDNJS can add versions automatically via auto-update config.
Would you remove the versions beta02,  and v2.0.0~v2.0.3 and update the auto-update config?
After this updating auto-update config PR be merged, CDNJS bot could help you add all the versions (include 2.0.0-beta02, v2.0.0 ~ v2.0.3)

### 1. Update the lib's info in the first commit
1. update the author field: from https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/wavesurfer.js/package.json#L10 to [`"katspaugh <katspaugh@gmail.com>"`](https://github.com/katspaugh/wavesurfer.js/blob/2.0.1/bower.json#L6)
2. Update license field: from https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/wavesurfer.js/package.json#L11 to [`BSD-3-Clause`](https://github.com/katspaugh/wavesurfer.js/blob/2.0.1/bower.json#L6)
3. Add homepage info: `"homepage": "https://wavesurfer-js.org/"`

The first commit message is 
```
Update wavesurfer.js package.json info

Update author & license and add homepage info of wavesurfer.js
```

### 2. Add the latest version and update the auto-update config in the second commit
1. Add the files of v2.0.4
2. Update package.json
   A. from https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/wavesurfer.js/package.json#L12-L23 to 
```
  "npmName": "wavesurfer.js",
  "npmFileMap": [
    {
      "basePath": "dist",
      "files": [
        "**/!(*.cjs.*)"
      ]
    }
  ],
```
   B. Update version from https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/wavesurfer.js/package.json#L4 to `2.0.4`

3. The second commit message is 
```
Add wavesurfer.js@2.0.4 w/ npm auto-update
```

This would be a great work and make this PR better to be merged.

Thank you very much.

**Comment by sufuf3** [comment]
Hi @thijstriemstra
Thank you for your contribution.
I found the front-end files now release from npm not release from GitHub repo.
CDNJS can add versions automatically via auto-update config.
Would you remove the versions beta02,  and v2.0.0~v2.0.3 and update the auto-update config?
After this updating auto-update config PR be merged, CDNJS bot could help you add all the versions (include 2.0.0-beta02, v2.0.0 ~ v2.0.3)

### 1. Update the lib's info in the first commit
1. update the author field: from https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/wavesurfer.js/package.json#L10 to [`"katspaugh <katspaugh@gmail.com>"`](https://github.com/katspaugh/wavesurfer.js/blob/2.0.1/bower.json#L6)
2. Update license field: from https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/wavesurfer.js/package.json#L11 to [`BSD-3-Clause`](https://github.com/katspaugh/wavesurfer.js/blob/2.0.1/bower.json#L6)
3. Add homepage info: `"homepage": "https://wavesurfer-js.org/"`

The first commit message is 
```
Update wavesurfer.js package.json info

Update author & license and add homepage info of wavesurfer.js
```

### 2. Add the latest version and update the auto-update config in the second commit
1. Add the files of v2.0.4
2. Update package.json
   A. from https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/wavesurfer.js/package.json#L12-L23 to 
```
  "npmName": "wavesurfer.js",
  "npmFileMap": [
    {
      "basePath": "dist",
      "files": [
        "**/!(*.cjs.*)"
      ]
    }
  ],
```
   B. Update version from https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/wavesurfer.js/package.json#L4 to `2.0.4`

3. The second commit message is 
```
Add wavesurfer.js@2.0.4 w/ npm auto-update
```

This would be a great work and make this PR better to be merged.

Thank you very much.

PS. I can't request a review by myself, so mention in the comment.

**Comment by thijstriemstra** [comment]
@sufuf3 thank you very much for your detailed review! I've opened a new pull request that addresses your review comments: #12532

**Pull request closed without merging**
