### PR TITLE
[new] [author] Added Matreshka.js

### PR DESCRIPTION
**Pull request by finom**
Hey guys. I'm working under website right now and I hope this is not a problem. I hope I've understood cdnjs requirements correctly. Thanks.

### CODE REVIEW

**Comment by finom** [comment]
Just looked at https://circleci.com/gh/cdnjs/cdnjs/1486
How can I fix the issue?

**Comment by PeterDaveHello** [comment]
Please add its real files, and use 2 spaces as indent if possible, thanks!

**Comment by finom** [comment]
Seems files is OK now. Am I wrong?

I'll change indents. Thanks.

**Comment by PeterDaveHello** [comment]
Please squash these commits into only one commit as our document said, thanks!

**Pull request closed without merging**
