### PR TITLE
geojson2svg added

### PR DESCRIPTION
**Pull request by gagan-bansal**
while running ``npm test`` I got the following error:

```SyntaxError: Error parsing /home/gaganb/lib_repo/cdnjs/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map/package.json: Unexpected end of input```

I have not done any changes other than in ``ajax/libs/geojson2svg``

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Would you please merge/squash these commits into only one commit as our document said? thanks.

**Comment by gagan-bansal** [comment]
Thanks for guidance.
I have merged all commits to single commit.

**Comment by PeterDaveHello** [comment]
Okay, one more thing, there are 3 files under dist - geojson2svg.js  geojson2svg.js.map  geojson2svg.min.js

so would you please also add geojson2svg.js as your auto-update config ? thanks.

**Comment by gagan-bansal** [comment]
Thanks for the quick response. cdnjs.com is really wonderful project.

I have added the following keys in [package.json](https://github.com/gagan-bansal/cdnjs/blob/master/ajax/libs/geojson2svg/package.json)
```
  "npmName": "geojson2svg",
  "npmFileMap": [
    {
      "basePath": "/dist",
      "files":["*"]
    }
  ],
  "filename": "geojson2svg.min.js"
```
is there any different config? Or the format is different ?

**Comment by PeterDaveHello** [comment]
Yeah, I know, the config is okay, but it'll include 3 files, but you only add 2 of them in this commit, it'll be better to add them all.

**Comment by gagan-bansal** [comment]
I had deleted the ``geojson2svg.js`` from my commit as it was uncompressed one, so its not required. The main file is ``geojson2svg.min.js`` and source map for the same `` geojson2svg.js.map``.

Please let me know if I am doing something wrong as first time I am adding my lib to cdnjs.com.

**Comment by PeterDaveHello** [comment]
Yeah, but `"files":["*"]` will match all the files under dist, right? so we just keep the structure the same, uncompressed files are okay to be included.

**Comment by gagan-bansal** [comment]
Ok I got your point as I have included ``"basePath": "/dist"`` and in files with * i.e. ``"files":["*"]`` then all three files from ``/dist`` would be uploaded while auto-update. 

I'll commit all three once again and will do the merge/squash again.
Thanks

**Comment by gagan-bansal** [comment]
Hi, I committed now all three files.
Thanks.

**Comment by PeterDaveHello** [comment]
Thank you.

**Comment by gagan-bansal** [comment]
Thanks Peter for adding this lib, now after I update the lib what I have to do to update in cdnjs.com. Few doubts:
- is it auto-updated from github or npm
- do I have to tag the version in github

**Comment by PeterDaveHello** [comment]
No, you are using npm auto-update.

**Comment by gagan-bansal** [comment]
Thanks Peter.

**Comment by PeterDaveHello** [comment]
np

**Comment by PeterDaveHello** [comment]
But I think add tags for them won't bite you, and can make the repo looks even better, users are easier to trace the code between different versions, right?

BTW, would you like to add cdnjs to your project? So users can easily know that they can use cdn instead of hosting by themselves.

**Comment by gagan-bansal** [comment]
Thanks for the suggestion. I'll add tag to github.
Yes, certainly I am going to add cdnjs link of geojson2svg on README of the project.

**Comment by PeterDaveHello** [comment]
:+1:

**Pull request merged**
