### PR TITLE
Add forge v0.7.1 w/ npm auto-update

### PR DESCRIPTION
**Pull request by sufuf3**
Pull request for issue: #11152
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/digitalbazaar/forge
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/node-forge
 * License and its reference: BSD-3-Clause OR GPL-2.0
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 106
   - Count of stars: 1862
   - Count of forks: 302
 * NPM download stats (optional):
   - Downloads in the last day: 40233
   - Downloads in the last week: 218411
   - Downloads in the last month: 898968

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by sufuf3** [comment]
@cdnjs/intern3 please help me review this PR, thanks.

**Comment by sufuf3** [comment]
@hare1039 I modified the commit message, please help me review this PR again, thanks.

**Comment by sufuf3** [comment]
duplicate with #10572, cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
use `forge` instead

**Comment by PeterDaveHello** [comment]
@sufuf3 make sure you followed discussion in #10572

**Comment by davidlehn** [comment]
I'm one of the upstream forge authors.  I was just catching up on progress on this.

For the checkboxes above, I can say we'll add cdnjs info to the project README.

As far as naming, `forge` is good, but note there are many other projects called "forge" or similar out there.  `node-forge` was picked back before npm was larger than just node.  Now that package has built files that can be used in browsers so the naming is a bit off.

Out of curiosity, why is this adding every ancient released version of the project?  There are even a bunch of .map files that I don't think were ever created by the build system.  I can't imagine any reason for using any version other than the latest 0.6.x or 0.7.x releases.  And 0.6.x is only in maintenance mode now.

**Comment by PeterDaveHello** [comment]
@davidlehn serving ancient versions so users won't be force to upgrade the version they are using 😊

**Comment by sufuf3** [comment]
@davidlehn Thank you.
I'd like to know that for <0.7.0 the git source of `forge-dist` is the same as npm package?

Could you give me some suggestions?

because I will manually add v0.2.0 ~ v0.2.13 and v0.2.23 ~ v0.6.49 with a simple shell script to built bundles. 
(run `npm install`, run `npm run minify` and `npm run bundle` to get `forge.min.js` and `forge.bundle.js`.)

Thank you very much.

**Comment by PeterDaveHello** [comment]
@sufuf3 When do we start to build dist files for libs?

**Comment by sufuf3** [comment]
@PeterDaveHello Sorry, I just follow the discussions in #10572 and saw the PR build dist files for libs.
What I need to do is ask the author can provide a single file for <0.7.0 versions, right?
Otherwise, we just host >=0.7.0 versions, which is built and minimized basic forge bundles.

**Comment by PeterDaveHello** [comment]
We don't build the files.

**Comment by sufuf3** [comment]
OK, thanks. I'll discuss with the author that can he provide a single file for <0.7.0 versions.
Otherwise, we just host >=0.7.0 versions.

**Comment by davidlehn** [comment]
@sufuf3 The `forge-dist` repo is a full clone, tags and all, of the main `forge` repo as of the transition from 0.6.x to 0.7.x.  It exists to support bower and similar tools that need usable sources in git.  For 0.6.x this wasn't an issue since you could use the source directly without a build step.  For 0.7.x you need to build the CommonJS code for browsers.  `forge-dist` is used to hold all those huge built files rather than adding them to the main repo.  npm releases of 0.7.x+ include the built sources as well.

When we do a `forge` release we also do a `forge-dist` release.  For 0.7.x it's just adding the built files.  It's a bit more complex for 0.6.x.  We wrote up what we do here: https://github.com/digitalbazaar/forge/blob/master/RELEASE.md.

https://bower.io/ suggests using yarn and webpack so I assume that at some future point we'll give up on `forge-dist` updates and just tell everyone to use npm or build files themselves.  Releases are rare now so it's not a big deal to keep `forge-dist` going.  Our built files are "kitchen sink" style so people using just small parts of forge should build their own files anyway.

Sorry this is all so complex!  It's the best we could come up with to keep supporting bower w/o putting gigantic built files into the main `forge` repo.  If I had to recommend something, I'd say only support >=0.7.0 on cdnjs since that's a simple matter of grabbing the files out of the npm packages and there are very few reasons to use the older releases.  We don't have "single files" available for older releases.  Those were never built since the code could be used directly.

**Comment by sufuf3** [comment]
@davidlehn thank you very much.
I'll fix this PR. 👍

**Comment by sufuf3** [comment]
@cdnjs/intern3 
Please help me review this PR, Thank you.

**Comment by PeterDaveHello** [comment]
Ping @hare1039 @clairetsai818

**Comment by PeterDaveHello** [comment]
@pvnr0082t please help rebase with master branch in this situation that it's a little bit old already.

**Comment by PeterDaveHello** [comment]
@pvnr0082t @hare1039 @extend1994 @sufuf3 title ... again.

**Pull request merged**
