### PR TITLE
[Author] Manually add missing files of mathjax@2.7.2-beta.0

### PR DESCRIPTION
**Pull request by dpvc**
This PR adds files to the MathJax 2.7.2-beta.0 release that were originally missing from the release, but added shortly after the release.  It was retagged, but it appears cdnjs picked up the original version before these were added.

If this PR is unacceptable, I can retag a new 2.7.2-beta.1 release instead.  But it would be great if these missing files could be added to this one.

Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):  https://github.com/mathjax/MathJax
 * Official website (optional, not the repository): https://www.mathjax.org/
 * NPM package url (optional):
 * License and its reference: Apache2
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 189
   - Count of stars: 4286
   - Count of forks: 653
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [x] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by dpvc** [comment]
@sufuf3, thanks for fixing the title, and letting me know how the commit message should have been formatted.  I have amended the commit as you requested, so I hope that everything is ready for you at this point.  Let me know if there is more that I need to do.

Thank you for the quick response, and for the excellent service you provide.

**Comment by PeterDaveHello** [comment]
@dpvc thanks for your prompt response.

**Comment by PeterDaveHello** [comment]
@sufuf3 don't duplicate the first line and its body please, it's no meaning to say it twice. I think we discussed already?

**Comment by PeterDaveHello** [comment]
I updated the commit message here: https://github.com/cdnjs/cdnjs/commit/0b5de65f2fd2d9a0f691efe748a4d22d774819ed, @dpvc thanks for your update!

**Comment by dpvc** [comment]
@PeterDaveHello, thanks for your help!

**Comment by PeterDaveHello** [comment]
@dpvc you're welcome. The updates will be deployed soon.

**Pull request merged**
