### PR TITLE
[New] Add excel-formula w/ npm auto-update

### PR DESCRIPTION
**Pull request by extend1994**
Related pull request: #11767

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/joshbtn/excelFormulaUtilitiesJS
 * Official website (optional, not the repository): http://excelformulabeautifier.com/
 * NPM package url (optional): https://www.npmjs.com/package/excel-formula
 * License and its reference: [MIT](https://github.com/joshbtn/excelFormulaUtilitiesJS/blob/master/license.include)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 12
   - Count of stars: 140
   - Count of forks: 42
 * NPM download stats (optional):
   - Downloads in the last day: 22
   - Downloads in the last week: 67
   - Downloads in the last month: 108

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by extend1994** [comment]
1. Add this lib because another lib jexcel needs it/(discussions are in https://github.com/cdnjs/cdnjs/pull/11767)
2. Didn't add v0.9.42 on npm because it is not packaged. Didn't find distribution on its git repo, either.

**Comment by sufuf3** [comment]
1. use **close** (It's the new lib)
```
Add excel-formula@1.4.2 w/ npm auto-update
cc #11767, cc @joshbtn
```
-->
```
Add excel-formula@1.4.2 w/ npm auto-update
**close** #11767, cc @joshbtn
```
2. we need to avoid the same words in line head, such as **Manually add**
```
Manually add excel-formula v1.0.1/1.0.0 from GitHub
Manually add them because the author didn't package them on npm.
cc #11767
```
-->
```
Manually add excel-formula v1.0.1/1.0.0 from GitHub
Add v1.0.1 & v1.0.0 of lib because they are unavailable from npm, #11767
```

**Comment by extend1994** [comment]
@sufuf3 For the first request, 11767 is not issue but a pull request, I use `cc` here because I said the quote there
> I think we can know that excel-formula.min.js belongs to excelFormulaUtilitiesJS 
I will help add excelFormulaUtilitiesJS.

For the second request, I only removed `manually` part because I think `they are unavailable` is for the situation of that the versions don't exist on the platform. But the situation here is that the versions are there, just were not packaged by the author.

Please help review this, thanks.

**Comment by maruilian11** [comment]
Why don't we directly use `git auto-update`? Then, we won't need the second commit, right?

**Comment by extend1994** [comment]
@maruilian11 v1.1.1/1.1.2 are not on GitHub. So we can consider GitHub and npm to have same number of versions. But we prefer npm, which became the reason I use npm.

**Comment by maruilian11** [comment]
@PeterDaveHello Do we still prefer npm now? I thought we see git repo equally long time ago.

**Comment by PeterDaveHello** [comment]
@maruilian11 both fine.

**Pull request merged**
