### PR TITLE
Add license info of arbor with MIT

### PR DESCRIPTION
**Pull request by Kamigami55**
for #6324
[ref] (https://github.com/samizdatco/arbor/blob/master/README#L75)

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Nice :+1:

**Comment by PeterDaveHello** [comment]
@Kamigami55 thanks for your contribution, however, as you can see on https://github.com/Kamigami55/cdnjs/commit/35bf7c941a2aafd95cbf3c4b886cea76592b9d23, the parent commit of this commit, is https://github.com/Kamigami55/cdnjs/commit/7e3a2578acdb518e5e013841b8a57e2f2ed85ac7, which was made on 29 Nov, is a little bit too old(about a month ago), to have a clean and clear git commit history for easier to trace, we don't merge a PR who's parent was too far away, to fix that, you have 2 method:

- Easier one - Close this PR, deleted your forked cdnjs, and re-fork, redo the PR.
- Harder one (but you can learn something if you want)- Sync your forked repository with our latest[1](https://www.peterdavehello.org/2015/05/how-to-syncupdate-forked-repository-with-upstream/), rebase your branch for this PR(patch-1) onto the latest master branch, and use **force push** to update this PR.
(If you want the second way, don't forget to read about sparse-checkout and shallow clone [here](https://github.com/cdnjs/cdnjs/blob/master/sparseCheckout.md) first, to save your time)

Or, I can also manually cherry-pick your commit, which means you don't need to do any thing.

Wait for your response.

**Comment by Kamigami55** [comment]
@PeterDaveHello thanks for your reply, I'll try the harder one, update this PR later, thank you.

**Comment by PeterDaveHello** [comment]
@Kamigami55 no problem

**Comment by Kamigami55** [comment]
@PeterDaveHello I have updated the PR, rebase to the parent commit Kamigami55@bee1dc8, Is it correct?

**Comment by PeterDaveHello** [comment]
Perfect :sparkles:

**Pull request merged**
