### PR TITLE
[new] add jquery.complexify@0.5.1 with git auto-update

### PR DESCRIPTION
**Pull request by Amomo**
Hi @LeaYeh 

For #5603, I add jquery.complexify at v0.5.1 and add git auto-update config in its package.json.
repo: https://github.com/danpalmer/jquery.complexify.js

As `jquery.complexify.banlist.js` only contain a variable, I didn't minify it.
And, this library don't provide keywords, so I pick some words from README.md.

Would you mind checking this PR for me? Thank you~ :-D

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity : **Watch `51`, Star `599`, Fork `159`**
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct.

### CODE REVIEW

**Comment by LeaYeh** [comment]
@Amomo why dont we need [banlist](https://github.com/danpalmer/jquery.complexify.js/blob/0.5.1/jquery.complexify.banlist.js) ?

**Comment by Amomo** [comment]
@LeaYeh I do add `jquery.complexify.banlist.js` in my PR.
I just said that I didn't minify it.

**Comment by LeaYeh** [comment]
sorry for my misunderstanding...
but `jquery.complexify.banlist.js` also have some command, didnt it effect network traffic and browser overhead?

**Comment by PeterDaveHello** [comment]
So what's going on here? It's been a long time.

**Comment by PeterDaveHello** [comment]
close per #7394

**Pull request closed without merging**
