### PR TITLE
Added alasql lib

### PR DESCRIPTION
**Pull request by mathiasrw**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Don't we need other files under dist?

**Comment by mathiasrw** [comment]
For the moment the abillity to include "plugins" from the other files is considered an experimental feature that is not documented yet - so nope. Only the alasql.js is needed (and the worker version if one wants to use it as a webworker)

**Comment by mathiasrw** [comment]
(but thanks for keeping an eye out)

**Comment by mathiasrw** [comment]
:+1:

**Pull request merged**
