### PR TITLE
Add angular-cookies@1.5.7 w/ npm auto-update

### LINKED ISSUE #8091: [Request] Add angular-cookies
**Library name:** angular-cookies
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by x09326**
PR for #8091 
@pvnr0082t please help me review it, thanks.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required):https://github.com/angular/angular.js
 * Official website (optional, not the repository):https://angularjs.org
 * NPM package url (optional):https://www.npmjs.com/package/angular-cookies
 * GitHub / Bitbucket popularity (required):
   - Count of stars:50011
   - Count of watchers:4302
   - Count of forks:24208
 * NPM download stats (optional):
   - Downloads in the last day:928
   - Downloads in the last week:29755
   - Downloads in the last month:103566

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #8091, cc @gkalpak

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Sorry that I have to close this, see: https://github.com/cdnjs/cdnjs/issues/8091#issuecomment-227086626

**Comment by gkalpak** [comment]
I don't know why (or if it's intentional), but a few other "official" angular modules are missing as well:

- angular-animate
- angular-aria
- angular-message-format
- angular-parse-ext
- angular-route

**Comment by PeterDaveHello** [comment]
@gkalpak they are all here:　https://cdnjs.com/libraries/angular.js/1.5.7

**Comment by gkalpak** [comment]
I just noticed. Curiously enough, some of the modules are also listed separately (e.g. angular-messages, angular-resource, angular-sanitize, angular-touch). This can be confusing.
I guess removing them would break people's apps, so it's out of question, though :smiley:

**Comment by PeterDaveHello** [comment]
@gkalpak Sorry about that, since we maintainers can't be familiar with all the libs, so ... that's very not perfect ... about the duplicated hosting

**Pull request closed without merging**
