### PR TITLE
Add angular-fontselect@0.13.4 w/ git auto-update

### LINKED ISSUE #10140: [Request] Add angular-fontselect
**Library name:** angular-fontselect
**Git repository url:** https://github.com/Jimdo/angular-fontselect
**npm package url(optional):** https://www.npmjs.com/package/angular-fontselect
**License(s):** The MIT License
**Official homepage:** https://github.com/Jimdo/angular-fontselect
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by qwe19272375**
Pull request for issue: #10140 
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/Jimdo/angular-fontselect
 * Official website (optional, not the repository): 
 * NPM package url (optional): https://www.npmjs.com/package/angular-fontselect
 * License and its reference: MIT, [ref](https://github.com/Jimdo/angular-fontselect#license)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 73
   - Count of stars: 25
   - Count of forks: 6
 * NPM download stats (optional):
   - Downloads in the last day: 41
   - Downloads in the last week: 249
   - Downloads in the last month: 1540

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #10140, cc @Xiphe

### CODE REVIEW

**Comment by qwe19272375** [comment]
@pvnr0082t Please help me review this PR, thanks!

**Comment by Xiphe** [comment]
Sweet! But just so you know, I'm not a maintainer anymore. cc @KarstenBuckstegge @christian-meyer-jimdo

**Comment by PeterDaveHello** [comment]
@Xiphe thanks!

**Comment by TobiasBales** [comment]
not sure regarding `I would like to add link to the page of this library on CDNJS on website / readme` does it mean linking from the repo to the cdn or the other way around?
Either way, works for us

(Jimdo Employee/maintainer here)

**Comment by qwe19272375** [comment]
@TobiasBales  I think it means that CDNJS will add a new page with a link to the homepage/repository.
ex. https://cdnjs.com/libraries/jquery

**Comment by TobiasBales** [comment]
Sure, that sounds great, so both points can be checked imo.

**Comment by PeterDaveHello** [comment]
No it means we'll like the document or website can mention its page on cdnjs.

**Comment by PeterDaveHello** [comment]
Ping @maruilian11

**Comment by qwe19272375** [comment]
`libs/webfontloader.js` removed and excluded in `package.json`.

**Comment by PeterDaveHello** [comment]
Can you please change the pattern to only exclude exactly `libs/webfontloader.js`?

**Comment by qwe19272375** [comment]
@pvnr0082t Exclude exactly `libs/webfontloader.js` in `package.json`, please help me review it, thanks!

**Pull request merged**
