### PR TITLE
Add a license of graphael, cc #5500

### PR DESCRIPTION
**Pull request by sufuf3**
https://github.com/DmitryBaranovskiy/g.raphael/blob/b0290afa10307ed79e6fc77a19688557e1978edc/g.bar.js
https://github.com/DmitryBaranovskiy/g.raphael/blob/b0290afa10307ed79e6fc77a19688557e1978edc/g.dot.js
https://github.com/DmitryBaranovskiy/g.raphael/blob/b0290afa10307ed79e6fc77a19688557e1978edc/g.line.js
https://github.com/DmitryBaranovskiy/g.raphael/blob/b0290afa10307ed79e6fc77a19688557e1978edc/g.pie.js

### CODE REVIEW

**Comment by sufuf3** [comment]
@pvnr0082t

**Comment by pvnr0082t** [comment]
@sufuf3 You should tag me and say something like "Please help me review this pull request". Thanks.

**Comment by pvnr0082t** [comment]
You can highlight which line of the file like https://github.com/DmitryBaranovskiy/g.raphael/blob/b0290afa10307ed79e6fc77a19688557e1978edc/g.bar.js#L5.

**Comment by pvnr0082t** [comment]
LGTM
ping @cdnjs/intern2

**Pull request merged**
