### PR TITLE
add anyjs v1.0.2 with npm auto-update config

### LINKED ISSUE #6867: [Request] Add anyjs
Library name: anyjs
Git repository url: https://github.com/any-js/anyjs
npm package url(optional): https://www.npmjs.com/package/anyjs
License(s): MIT
Official homepage: http://any-js.github.io/

### PR DESCRIPTION
**Pull request by kennynaoh**
PR for #6867 
@x09326 please help me review this pull request, thank you.
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/any-js/anyjs
 * Official website (optional, not the repository): https://any-js.github.io/
 * NPM package url (optional): https://www.npmjs.com/package/anyjs
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 1
   - Count of watchers: 1
   - Count of forks: 0
 * NPM download stats (optional):
   - Downloads in the last day: 2
   - Downloads in the last week: 5
   - Downloads in the last month: 74

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #6867, cc @anyjser

### CODE REVIEW

**Comment by x09326** [comment]
@PeterDaveHello 
I think this PR is okay, please help me review it, thanks.

**Comment by PeterDaveHello** [comment]
Please put them in the same folder.

**Comment by kennynaoh** [comment]
@x09326 
I have updated my location of files.
Please help review it again.
Thanks!

**Comment by x09326** [comment]
@kennynaoh 
Do you rebase with the master?

**Comment by kennynaoh** [comment]
@x09326 
I have rebased to the latest master branch.
Please help me review it again.
Thanks.

**Comment by x09326** [comment]
@PeterDaveHello 
I think this PR is okay, please help me review it, thanks.

**Pull request merged**
