### PR TITLE
point angular-i18n's filename field to minified file, and add git auto-update config, #5195

### PR DESCRIPTION
**Pull request by Amomo**
Hi @Piicksarn , I have point the filename field to minified file, and add git auto-update config for this lib.
Would you mind checking this PR  from #5195 for me? Thank you~ :-)

### CODE REVIEW

**Comment by Piicksarn** [comment]
@Amomo, It doesn't pass the online check!
I will checkout the pr after you correct it:^)

**Comment by Amomo** [comment]
Hi @Piicksarn I have fixed it!
Could you take it a look? Thank you~

**Comment by Amomo** [comment]
Sorry, the number of changed files is too many...
You could look first commit and the last one. They are about changes in package.json.

**Comment by Piicksarn** [comment]
mm...@Amomo..I think you need to minified the file which pointed in package.json.
Only angular-locale_en-us.js need to minify in very versions. 
I think this is the good example for you: https://github.com/maruilian11/cdnjs/commit/b8bb01c3b4ee6d5373267aa91cabfa658cf0c3a9

You need to checkout the file map of the autoupdate commit.
I can not find the files in https://github.com/angular/angularjs.org
and it seems that the lib doesn't use tags for the versions.

**Comment by Piicksarn** [comment]
I think this is good example for you! 
https://github.com/cdnjs/cdnjs/pull/5204
The only file need to minified is pointed in package.son

you need to check your file map in autoupdate as i can not find the files in https://github.com/angular/angularjs.org
and the lib seems doesn't use tags for the versions.

**Comment by Amomo** [comment]
@Piicksarn the lib is here https://github.com/angular/angular.js

**Comment by Amomo** [comment]
@Piicksarn I have finished the modification.
Could you take a look again? Thank you~

**Comment by Piicksarn** [comment]
I think it's fine.
@PeterDaveHello, would you please take a look for the pr?
Thank you!

**Comment by PeterDaveHello** [comment]
Bad implement.

* 0c7ffce Will never pass the test before you added the minified files.
* 3d156ed Did a funny thing that you minified the en-us but leave others alone.

Once you want to minified this lib, ab97aa2 should also add `requiredFIles` field.

**Comment by Piicksarn** [comment]
@PeterDaveHello, we need to minified all the files, not only  the file which pointed in package.json, in each version?
sorry,I will be more careful on checking the PR...

**Comment by PeterDaveHello** [comment]
I think you should make sure you know about the difference between angular-locale_en-us.js and others.

**Comment by Amomo** [comment]
Oh, my bad. I should commit them by correct order.
@Piicksarn I have re-add those minified files, and changed the commit's order.
Could you take a look again? Thank you!

**Comment by PeterDaveHello** [comment]
> add minified files in v1.0.7/1.2.0/1.2.3/1.2.5/1.2.15
What's the lib's name?

**Comment by Amomo** [comment]
Thank you for the reminder. I have made a correction. :-D

**Comment by Piicksarn** [comment]
@PeterDaveHello, would your please check out the pr?
Thank you!

**Pull request merged**
