### PR TITLE
add angular-touch v1.4.8

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/angular/bower-angular-touch
**Watch 25
  Star 68
 Fork 96**
@Amomo could you help me check out the PR for #6051 ? thank you~
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity cc #6051
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by Amomo** [comment]
@maruilian11 because you use the files from npm, their version number is 1.4.7.
Could you change your folder name and related message to a right version number?

I think it is good to add/auto-update this library from npm. Thank you! :-D

**Comment by Amomo** [comment]
@LeaYeh I have rebased it, could you come to check this PR? Thank you~

**Comment by maruilian11** [comment]
@Amomo ?

**Comment by PeterDaveHello** [comment]
Don't forget to update the title.

**Comment by maruilian11** [comment]
@Amomo but when i npm install angular-touch, it's `v1.5.0-build.4384+sha.e5e0884` in its package.json.

**Comment by PeterDaveHello** [comment]
@maruilian11 so it's the same problem, maybe we could as the author is there any other source we can use.

**Comment by maruilian11** [comment]
@PeterDaveHello other source means we don't use npm auto-update? other versions?

**Comment by Amomo** [comment]
@maruilian11 
but I get version "1.4.8" in its package.json just now, by `npm install angular-touch`

**Comment by PeterDaveHello** [comment]
I think the versions are good in npm,

$ curl https://registry.npmjs.org/angular-touch | ./jq .time

```js
{
  "modified": "2015-11-20T08:23:23.866Z",
  "created": "2014-10-08T23:08:25.832Z",
  "1.3.0-rc.5": "2014-10-08T23:08:25.832Z",
  "1.3.0": "2014-10-13T22:39:58.203Z",
  "1.3.1": "2014-10-31T17:50:17.565Z",
  "1.3.2": "2014-11-07T19:32:14.427Z",
  "1.3.3": "2014-11-18T08:10:07.435Z",
  "1.3.4-build.3587": "2014-11-20T22:53:44.331Z",
  "1.2.27": "2014-11-21T00:07:33.619Z",
  "1.3.4": "2014-11-24T23:47:11.758Z",
  "1.3.5": "2014-12-02T05:36:28.937Z",
  "1.3.36": "2014-12-09T00:13:27.725Z",
  "1.3.6": "2014-12-09T00:28:57.954Z",
  "1.3.7": "2014-12-15T22:03:02.733Z",
  "1.2.28": "2014-12-15T22:37:19.601Z",
  "1.3.8": "2014-12-19T21:44:16.153Z",
  "1.4.0-beta.0": "2015-01-14T21:26:02.396Z",
  "1.3.9": "2015-01-14T23:23:04.591Z",
  "1.3.10": "2015-01-20T20:40:45.855Z",
  "1.4.0-beta.1": "2015-01-20T20:56:37.598Z",
  "1.4.0-beta.2": "2015-01-26T23:15:29.347Z",
  "1.3.11": "2015-01-26T23:34:56.375Z",
  "1.4.0-beta.3": "2015-02-03T21:37:40.729Z",
  "1.3.12": "2015-02-03T21:52:46.848Z",
  "1.3.13": "2015-02-09T11:11:00.817Z",
  "1.4.0-beta.4": "2015-02-09T11:30:19.138Z",
  "1.3.14": "2015-02-24T19:11:35.278Z",
  "1.4.0-beta.5": "2015-02-24T19:40:26.089Z",
  "1.4.0-beta.6": "2015-03-17T12:18:01.197Z",
  "1.3.15": "2015-03-17T13:16:34.188Z",
  "1.4.0-rc.0": "2015-04-10T18:13:07.112Z",
  "1.4.0-rc.1": "2015-04-24T20:46:41.938Z",
  "1.4.0-rc.2": "2015-05-12T19:26:56.613Z",
  "1.4.0": "2015-05-27T01:50:10.244Z",
  "1.3.16": "2015-06-05T21:22:01.434Z",
  "1.4.1": "2015-06-16T14:13:02.230Z",
  "1.4.2": "2015-07-06T21:32:41.934Z",
  "1.3.17": "2015-07-06T21:54:37.037Z",
  "1.4.3": "2015-07-15T02:03:08.817Z",
  "1.4.4": "2015-08-13T18:57:50.144Z",
  "1.3.18": "2015-08-18T22:41:55.764Z",
  "1.4.5": "2015-08-28T20:00:53.705Z",
  "1.3.19": "2015-09-16T21:24:33.209Z",
  "1.4.6": "2015-09-17T12:30:00.201Z",
  "1.5.0-beta.0": "2015-09-17T14:04:01.240Z",
  "1.2.29": "2015-09-29T22:03:53.625Z",
  "1.3.20": "2015-09-29T22:36:37.925Z",
  "1.4.7": "2015-09-29T23:08:50.869Z",
  "1.5.0-beta.2": "2015-11-18T00:27:03.630Z",
  "1.4.8": "2015-11-20T08:23:23.866Z"
}
```

**Comment by maruilian11** [comment]
@Amomo i have added 1.4.8, could you help me check the PR again?

**Comment by PeterDaveHello** [comment]
@maruilian11 PR title ...

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine, could you take a look? Thank you~

**Pull request merged**
