### PR TITLE
[author] jQuery-Form-Validator - Auto update should include stylsheets

### PR DESCRIPTION
**Pull request by victorjonsson**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I think we should not touch its `version` field here.

**Comment by victorjonsson** [comment]
Oh... Is it okey if I do a new PR that contains both the changes to the file declaration in package.json and the missing CSS-files in the latest version (that were auto-updated)?

**Comment by PeterDaveHello** [comment]
I think you can just update the filemap, and I can take the rest things.

**Comment by victorjonsson** [comment]
Ok, gr8!

**Pull request closed without merging**
