### PR TITLE
[author] Auto update should include stylesheets

### PR DESCRIPTION
**Pull request by victorjonsson**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Can you mention your lib's name in the commit message? Thanks!

**Comment by victorjonsson** [comment]
I have once again made a new PR. 

I'm embarrassed to say that my computer cant bare with the size of the cdnjs-repo. I'm doing this via the browser.

**Comment by PeterDaveHello** [comment]
Have you tried sparse-checkout with shallow clone?

See: https://github.com/cdnjs/cdnjs/blob/master/sparseCheckout.md

**Comment by victorjonsson** [comment]
Will have to check that out next time.

**Pull request closed without merging**
