### PR TITLE
bootbox.js add license field with MIT

### PR DESCRIPTION
**Pull request by LeaYeh**
@Amomo could you plz check this pr for me?
#5500

### CODE REVIEW

**Comment by Amomo** [comment]
@LeaYeh please attach the `lib's GitHub repo` in PR comment in the future～
It would help us to review your PR easier and faster.

And, `starting your commit message with a verb` would help others understand your commits clear and effectively. Would you mind to modify your commit message?

Thank you!

**Comment by LeaYeh** [comment]
so sorry for that.
lib: https://github.com/makeusabrew/bootbox/tree/v4.4.0

**Comment by Amomo** [comment]
@LeaYeh Thank you for attaching lib repo's url.
Could you modify your commit message to `start with a verb`?

**Comment by LeaYeh** [comment]
okay.

**Comment by Amomo** [comment]
@LeaYeh could you make you commit message to start with the key action you done?
And, please also modify the title to make it more readable.

Thank you~

**Comment by Amomo** [comment]
Hi @LeaYeh could you modify your commit message and PR title like...
`add license field in ...` or `Enrich ...'s package.json(field: license) `
to make you message more clear?

And, don't forget to rebase the commit after modifying. Thank you! :-D

**Comment by Amomo** [comment]
@LeaYeh could you please update your PR~?

**Comment by PeterDaveHello** [comment]
Added in d0935dabf7069a8c693c02e99dcbf1f42bbfdd5f

**Pull request closed without merging**
