### PR TITLE
[author] [new]  Added jsnlog@2.12.1

### PR DESCRIPTION
**Pull request by mperdeck**
https://github.com/mperdeck/jsnlog.js
http://jsnlog.com

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@mperdeck Thanks. @maruilian11 please review.

**Comment by maruilian11** [comment]
hi, @mperdeck 
i'm here to help you send the PR
we hope you send just **one** clean and clear commit to add new lib
i suggest you use `git rebase -i HEAD~5` to delete all commits you have sent, then use `git rebase master` to rebase with our latest master.
after all steps, you can resent a new clean commit
thank you for your contribution :smiley: 

p.s. with `git rebase` you don't have to close this PR, and reopen a new one
hope this will help you

**Comment by PeterDaveHello** [comment]
also cc @cdnjs/intern

**Comment by mperdeck** [comment]
@PeterDaveHello I created a new pull request #6234 that replaces this pull request. I think you've already seen that pull request and assigned Amomo.

**Comment by PeterDaveHello** [comment]
So close this.

**Pull request closed without merging**
