### PR TITLE
[NEW][AUTHOR] Add Syncano Library

### PR DESCRIPTION
**Pull request by kellyjandrews**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Would you please provide repository info in the package.json? Thanks.

**Comment by kellyjandrews** [comment]
Done. Let me know if you need anything else.

**Comment by PeterDaveHello** [comment]
Yeah, need to fix indent in package.json and wait for higher population, thanks.

**Comment by kellyjandrews** [comment]
Thanks. I'll just go ahead and close the pull request and locate another cdn.

**Pull request closed without merging**
