### PR TITLE
Add ngclipboard w/ npm auto-update via single package.json

### LINKED ISSUE #11344: [Request] Add ngclipboard
**Library name:** ngclipboard
**Git repository url:** https://github.com/sachinchoolur/ngclipboard
**npm package name or url**: [ngclipboard](https://www.npmjs.com/package/ngclipboard)
**License:** MIT
**Official homepage:** https://sachinchoolur.github.io/ngclipboard/

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

### PR DESCRIPTION
**Pull request by dmr-loggly**
close #11344 
Pull request for issue: #11344
Glue library for employing clipboard.js (already hosted here) in angular.js

# Profile of the lib
 * Git repository (required): https://github.com/sachinchoolur/ngclipboard
 * Official website (optional, not the repository): https://sachinchoolur.github.io/ngclipboard/
 * NPM package url (optional): https://www.npmjs.com/package/ngclipboard
 * License and its reference: MIT https://github.com/sachinchoolur/ngclipboard/blob/master/LICENSE
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 6
   - Count of stars: 309
   - Count of forks: 65
 * NPM download stats (optional):
   - Downloads in the last day: 1051
   - Downloads in the last week: 5723
   - Downloads in the last month: 21624

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by dmr-loggly** [comment]
I'm a bit stumped-- CONTRIBUTING.md said I could add a libary via auto-update with just the package.json, but the CI is complaining that other files don't exist.

**Comment by dmr-loggly** [comment]
OK, figured out my malfunction.

**Comment by maruilian11** [comment]
@cdnjs/library-reviewer Please help me make the double check, thanks!

**Comment by maruilian11** [comment]
@pvnr0082t @extend1994 Just help modify the commit msg, could you please check it again? Thanks!

**Comment by dmr-loggly** [comment]
Thanks for your help, @maruilian11!

**Pull request merged**
