### PR TITLE
[new] bootstrap-notify

### PR DESCRIPTION
**Pull request by lobbin**
Files copied from github repository, https://github.com/goodybag/bootstrap-notify.

Uglified by me.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
syntax error in package.json, and should keep the directory/file structure as the upstream/source.

**Comment by lobbin** [comment]
Yeah, sorry about the syntax error. I've updated the pull request with a proper package.json and moved the files around as they are structured upstream.

**Comment by PeterDaveHello** [comment]
Would you please also setup auto-update config for it?
So that we don't need to manually update it in future, which is slower.

See:https://github.com/cdnjs/cdnjs#enabling-gitrecommended-or-npm-auto-update

Thanks.

**Comment by lobbin** [comment]
Sure thing, just trying to figure out how to test it though. Will the auto-update take care of the minification process?

**Comment by PeterDaveHello** [comment]
auto-update will not take care of the minification process, but  I will, when I auditing/reviewing the updates. The test process may be a little bit complex, should use with [autoupdate](https://github.com/cdnjs/autoupdate) repository, I think you can refer to other libraries and let me help you to audit/review the config.

Here are some examples, hope they'll help:
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/css-social-buttons
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/bootstrap-fileinput
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/Glide.js
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/lazy.js
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/timeline.css

**Comment by lobbin** [comment]
Ah, ok. The setting seems simple enough and I hope this is the last change :)

**Comment by PeterDaveHello** [comment]
@lobbin, we don't use fully-wildcard on non-dist folder which is used to distribute the releases, maybe you can try `css/bootstrap-notify*.css`? Thanks.

**Comment by lobbin** [comment]
This looks better? :)

**Comment by PeterDaveHello** [comment]
Nice, last request, would you please rebase your branch with our latest master branch as our document says? Then I'll merge it, thanks a lot!

**Comment by lobbin** [comment]
Bah, sometimes I truly hate git. Give me a moment and I'll fix it :)

**Comment by PeterDaveHello** [comment]
No problem.

**Pull request closed without merging**
