### PR TITLE
add nes v1.0.0

### LINKED ISSUE #5912: https://github.com/hapijs/nes
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by maruilian11**
close #5912, cc @hueniverse
**git repo url:** https://github.com/hapijs/nes
**Watch 25
  Star 127
 Fork 1**
@LeaYeh could u help me check this PR for #5912 ? thank you!
- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by LeaYeh** [comment]
i think this pr is ok.
@PeterDaveHello

**Comment by PeterDaveHello** [comment]
1. No need cc in the comment next time
2. Should say that it's with auto-update!

**Comment by maruilian11** [comment]
ok

**Comment by hueniverse** [comment]
Minified version is wrong:
https://cdnjs.cloudflare.com/ajax/libs/nes/1.2.0/client.min.js
vs.
https://cdnjs.cloudflare.com/ajax/libs/nes/1.2.0/client.js

Not sure how to go about fixing it.

**Comment by PeterDaveHello** [comment]
@hueniverse thanks! I'll take a look at it.

**Comment by PeterDaveHello** [comment]
@hueniverse We have problem to minify that file, will use src instead, thanks for your report! Feel free to open an issue if you found any other problem.

**Comment by kpdecker** [comment]
Should use dist/client.js and minimize that. The source file is worthless for browsers as is.

**Comment by PeterDaveHello** [comment]
I think there is no dist folder.

**Comment by kpdecker** [comment]
The dist folder is a build artifact. Looks like you want to use the npm update mode:

```
  "npmName": "nes",
  "npmFileMap": [
    {
      "basePath": "dist",
      "files": [
        "*.js"
      ]
    }
  ]
```
https://github.com/cdnjs/cdnjs#enabling-npmrecommended-or-git-auto-update

**Comment by PeterDaveHello** [comment]
@kpdecker Didn't notice that it has npm package, I'll transfer to use npm auto-update for it. #6177

**Pull request merged**
