### PR TITLE
Add license of mycolorway-simple-hotkeys, cc #5500

### PR DESCRIPTION
**Pull request by lcd78706**
https://github.com/mycolorway/simple-hotkeys/blob/master/LICENSE

### CODE REVIEW

**Comment by lcd78706** [comment]
@kennynaoh 
Please review this pull request. Thanks!

**Comment by kennynaoh** [comment]
@lcd78706 
If the PR is for adding license, you just need to add the reference in comment.
Thanks!

**Comment by kennynaoh** [comment]
LGTM
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
