### PR TITLE
 [new] JavaScript InfoVis Toolkit

### PR DESCRIPTION
**Pull request by vozkych**
Add the JavaScript InfoVis Toolkit from http://philogb.github.io/jit/.

### CODE REVIEW

**Comment by drewfreyling** [comment]
@vozkych are you able to add git auto update to the `package.json` for this lib?

**Comment by vozkych** [comment]
I tried to add this, but the author of this library does not compile a minified version. Is there any solution, how to build minified version of this lib during the git auto update process?

Od: Drew Freyling<mailto:notifications@github.com>
Odesl?no: ?pond?l??, ?13?. ?dubna? ?2015 ?3?:?05
Komu: cdnjs/cdnjs<mailto:cdnjs@noreply.github.com>
Kopie: Petr Vozka<mailto:vozkych@vozkych.net>


@vozkych<https://github.com/vozkych> are you able to add git auto update to the package.json for this lib?

-

**Comment by drewfreyling** [comment]
That is fine if they don't have a minified version. I believe @PeterDaveHello will add this manually when the library is updated.

**Comment by PeterDaveHello** [comment]
Sure, I'll audit every updates before commit them, I'll minifiy them then.

**Comment by vozkych** [comment]
That is great! I will update package.json with autoupdate section soon.

Odesláno z mého Windows Phone
________________________________
Od:Peter Dave Hello<mailto:notifications@github.com>
Odesláno:‎13. ‎4. ‎2015 11:47
Komu:cdnjs/cdnjs<mailto:cdnjs@noreply.github.com>
Kopie:Petr Vozka<mailto:vozkych@vozkych.net>
Předmět:Re: [cdnjs]  [new] JavaScript InfoVis Toolkit (#4555)


Sure, I'll audit every updates before commit them, I'll minifiy them then.

**Pull request merged**
