### PR TITLE
add fsvs v1.2.2

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/lukesnowden/FSVS
**Watch 33
  Star 601
 Fork 137 **
@Amomo could u help me check this PR for #7044 ? thank you!

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by Amomo** [comment]
@maruilian11 sorry for late, this PR is fine, could you rebase it on our master branch? thanks~

**Comment by maruilian11** [comment]
@Amomo it's ok~ done.

**Comment by PeterDaveHello** [comment]
Do we need duplicated files here? `assets/js/bundle.js` vs `js/bundle.js`, where is the difference?

**Comment by maruilian11** [comment]
@PeterDaveHello there is only `fsvs.js` in js folder. what do you mean?

**Comment by PeterDaveHello** [comment]
Why did you add duplicated files?

**Comment by maruilian11** [comment]
@PeterDaveHello do you mean we should change `assets/js/bundle.js` structure to `js/bundle.js`?

**Comment by PeterDaveHello** [comment]
I have no idea what's the problem here, why not set `assets` as base path?

**Comment by maruilian11** [comment]
@Amomo i have set basepath to assets, could you help me check this PR again? thank you!
i removed `requiredFiles` because peter said we don't need it anymore.

**Pull request merged**
