### PR TITLE
Adding react-breadcrumbs

### PR DESCRIPTION
**Pull request by svenanders**
Tried adding this a couple of months ago, but forgot to add the initial components. I've added the two latest versions. The 0.13.0 works with React 0.13, and the 0.2.15 works with React 0.12 and below.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please remove the unnecessary files.

**Comment by svenanders** [comment]
Which ones?

**Comment by PeterDaveHello** [comment]
I think we need these files only:
package.json
0.2.15/react-breadcrumbs.min.js
0.13.0/react-breadcrumbs.min.js

**Comment by drewfreyling** [comment]
Closing due to no response and a lack of popularity with repo.

**Pull request closed without merging**
