### PR TITLE
Move mobi.css from personal repo to organization

### PR DESCRIPTION
**Pull request by xcatliu**
We have created a new organization for Mobi.css
The repo url has changed from
`git+https://github.com/xcatliu/mobi.css.git`
 to
`git+https://github.com/mobi-css/mobi.css.git`

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/mobi-css/mobi.css
 * Official website (optional, not the repository): http://getmobicss.com
 * NPM package url (optional): https://www.npmjs.com/package/mobi.css
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 87
   - Count of stars: 2059
   - Count of forks: 160
 * NPM download stats (optional):
   - Downloads in the last day: 0
   - Downloads in the last week: 31
   - Downloads in the last month: 121

# Essential checklist
 * [x] I'm the author of this library
   * [x] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Sorry for the late review, we'll give it review soon.

**Comment by hare1039** [comment]
@PeterDaveHello I try to rebase the branch but `Permission denied`. What can we do now?

**Comment by PeterDaveHello** [comment]
@xcatliu may I know that if you checked `Allow edits from maintainers.` so that we can update your branch? Thanks.
image

**Comment by xcatliu** [comment]
@PeterDaveHello Yes I have checked `Allow edits from maintainers`

image

**Comment by PeterDaveHello** [comment]
hmmmm ... then that's interesting, I'll use "Squash and merge" this time, if you got the problem, I'll report to GitHub.

**Pull request merged**
