### PR TITLE
Holder 2.5.0 update

### PR DESCRIPTION
**Pull request by imsky**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Thanks @imsky

**Comment by imsky** [comment]
I don't see 2.5.0 on https://cdnjs.com/libraries/holder, but I do see it in the repo. Should the version number in `package.json` remain constant?

**Comment by PeterDaveHello** [comment]
https://cdnjs.cloudflare.com/ajax/libs/holder/2.5.0/holder.min.js is already available, I think the web's index just didn't been updated, I'll ask help from @thomasdavis to figure it out.

**Comment by imsky** [comment]
All right. I've reverted the version field, adding only the minified build.

**Comment by PeterDaveHello** [comment]
Would you please squash these 2 commits into only one commit and update its commit log as readme file said? thank you.

**Comment by imsky** [comment]
Done.

**Comment by PeterDaveHello** [comment]
Thanks a lot @imsky, I'm going to merge now!

**Comment by PeterDaveHello** [comment]
Seems I forgot this PR, sorry for that, I'm going to manually merge it later!

**Comment by imsky** [comment]
@PeterDaveHello Thanks.

**Comment by PeterDaveHello** [comment]
:)

**Pull request closed without merging**
