### PR TITLE
Added axe-core@2.0.5

### PR DESCRIPTION
**Pull request by marcysutton**
This is a PR for issue #8556.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/dequelabs/axe-core/
 * Official website (optional, not the repository): http://www.deque.com/products/axe/
 * NPM package url (optional): https://www.npmjs.com/package/axe-core
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 3,758
   - Count of watchers: 172
   - Count of forks: 2,648
 * NPM download stats (optional):
   - Downloads in the last day: 114
   - Downloads in the last week: 803
   - Downloads in the last month: 2,411

# Essential checklist
 * [X] I'm the author of this library
   * [X] I would like to add link to the page of this library on CDNJS on website / readme
 * [X] This lib was not found on cdnjs repo
 * [X] No already exist / duplicated issue and PR
 * [X] The lib has notable popularity
   * [X] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [X] More than 500 downloads stats per month on npm registry
 * [X] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X] The parent of the commit(s) in the PR is not old than 3 days.
 * [X] Pull request is sending from a non-master branch with meaningful name.
 * [X] Separate unrelated changes into different commits.
 * [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [X] Close corresponding issue in commit message
 * [X] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@marcysutton would you please fix the errors first? Thanks

**Comment by maruilian11** [comment]
hi @marcysutton , i'm here to help you send the PR.

1. our `filename` need to point to minified file.
2. please remove `contributors` and `main`
https://github.com/cdnjs/cdnjs/blob/master/tools/fixFormat.js#L29
https://github.com/cdnjs/cdnjs/blob/master/tools/fixFormat.js#L31
3. after seeing the structure of axe.js npm package, the `basePath` should be blank and `files` can be `"axe*"` to catch `axe.js` and `axe.min.js`.
 
PS. you can use `git rebase` to modify this commit without opening a new PR.
if you don't have much time, i'm happy to add this lib for you :smile:

**Comment by marcysutton** [comment]
Thank you! I've pushed an update.

**Comment by PeterDaveHello** [comment]
@marcysutton would you like to add `"homepage": "http://www.deque.com/products/axe/"` in the package.json?

**Comment by marcysutton** [comment]
Oh sure! Would you mind adding it?

**Comment by PeterDaveHello** [comment]
It's good to add it so that there will be a link on the lib page on cdnjs.

**Comment by marcysutton** [comment]
I've added the line you mentioned, should be good to go.

**Comment by PeterDaveHello** [comment]
Thanks @marcysutton

**Pull request merged**
