### PR TITLE
Add dflow@0.18.3 w/ git autoupdate

### LINKED ISSUE #9706: [Request] Add dflow
**Library name:** dflow
**Git repository url:** https://github.com/fibo/dflow.git
**npm package url(optional):** dflow
**License(s):** MIT
**Official homepage:** http://g14n.info/dflow
**Wanna say something? Leave message here:** is a minimal Dataflow programming engine

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by extend1994**
Pull request for issue: #9706 

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/fibo/dflow.git
 * Official website (optional, not the repository): 
 * NPM package url (optional): https://www.npmjs.com/package/dflow
 * License and its reference: MIT
 * GitHub / Bitbucket popularity (required): 
   - Count of stars: 26
   - Count of watchers: 9 
   - Count of forks: 3
 * NPM download stats (optional):
   - Downloads in the last day: 1
   - Downloads in the last week: 60
   - Downloads in the last month: 567

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9706, cc @fibo

### CODE REVIEW

**Comment by extend1994** [comment]
@PeterDaveHello please help me review this pull request, thank you.

**Comment by fibo** [comment]
awesome thanks!

**Comment by PeterDaveHello** [comment]
@fibo feel free to let your users use it on CDNJS :)

**Comment by fibo** [comment]
yeah,  I already updated installation instructions https://github.com/fibo/dflow/commit/521f20923d8c0fa1698083ff4e9613917f9d4d80

**Comment by PeterDaveHello** [comment]
Cool, btw, would you like to have a CDNJS badge just like https://github.com/selectize/selectize.js ?

**Pull request merged**
