### PR TITLE
add mathquill@0.10.1 w/ npm auto-update

### LINKED ISSUE #9938: [Request] Add mathquill
**Library name:** mathquill
**Git repository url:** https://github.com/mathquill/mathquill
**npm package url(optional):** 
**License(s):** Mozilla Public License, v. 2.0: http://mozilla.org/MPL/2.0/
**Official homepage:** http://mathquill.com
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by hare1039**
close #9938, cc @laughinghan

@pvnr0082t Please review this PR, thank you.
Pull request for issue: #9938
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/mathquill/mathquill
 * Official website (optional, not the repository): http://mathquill.com
 * NPM package url (optional): https://www.npmjs.com/package/mathquill
 * License and its reference: MPL2.0, [ref](https://github.com/mathquill/mathquill/blob/master/package.json#L5)
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 80
   - Count of stars: 1009
   - Count of forks: 313
 * NPM download stats (optional):
   - Downloads in the last day: 13
   - Downloads in the last week: 89
   - Downloads in the last month: 278

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@hare1039 you should select your reviewer.

**Comment by hare1039** [comment]
Sorry that I forgot to minify the css. Please review this PR again. Thank you.

**Comment by PeterDaveHello** [comment]
@pvnr0082t LGTM with rejection not approval?

**Comment by hare1039** [comment]
I fixed the permission. Please review this PR again. Thank you.

**Pull request merged**
