### PR TITLE
add flexslider v2.3.0

### PR DESCRIPTION
**Pull request by bdukes**
flexslider 2.2.2 has a [minified version of the CSS file](https://cdnjs.cloudflare.com/ajax/libs/flexslider/2.2.2/flexslider-min.css), but I wasn't sure of the best way to do that minification, so I haven't included it.  Let me know if there's a preferred tool for CSS minification and I can update the PR.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Personally I use this script : https://github.com/PeterDaveHello/web-minify-helper, minified file(s) will be required, so please include it, thanks!

**Comment by PeterDaveHello** [comment]
BTW, is auto-update possible for this lib? According to  #36388, we are transferring libs to use auto-update, thanks!

**Comment by bdukes** [comment]
I've added the minified CSS and added an auto-update configuration

**Comment by PeterDaveHello** [comment]
Thanks a lot, would you please squash these commits into only one commit as our document said? Thank you.

**Comment by bdukes** [comment]
there you go

**Comment by PeterDaveHello** [comment]
Thank you!

**Pull request merged**
