### PR TITLE
[new] Add jquery-serialScroll

### PR DESCRIPTION
**Pull request by bdukes**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Is it possible to add auto-update config for it? thanks.

**Comment by bdukes** [comment]
It isn't on npm (it is on bower, though).  Is there a way to do auto-update for non-npm libraries?

**Comment by PeterDaveHello** [comment]
Yes, and I think we already have it for a while.
Check this out : https://cdnjs.com/libraries/jquery.serialscroll

**Comment by bdukes** [comment]
Ah, you're right!  I both missed finding it in the search somehow and had an out-of-date local copy for the git repo.  Sorry for wasting your time.

**Comment by PeterDaveHello** [comment]
It's okay.

**Pull request closed without merging**
