### PR TITLE
[author][new] Added react-foundation-apps

### PR DESCRIPTION
**Pull request by akiran**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Would you please point filename field in package.json to the minified file and add auto-update config for it? Thanks!

**Comment by akiran** [comment]
Done !

**Comment by PeterDaveHello** [comment]
And please squash these two commits into only one commit, thanks.

**Comment by akiran** [comment]
Squashed commits

**Comment by akiran** [comment]
@PeterDaveHello 
Unminified  version is served even with .min.js extension
https://cdnjs.cloudflare.com/ajax/libs/react-foundation-apps/0.6.0/react-foundation-apps.min.js

**Comment by PeterDaveHello** [comment]
That's because of you commit the same file with different file name ... check your commit please :)

**Comment by akiran** [comment]
Sorry. my mistake.

If I make a new npm release with 0.6.1 version, it will be auto updated to new version right ?

**Comment by PeterDaveHello** [comment]
Yeah, and I fixed this issue in 6f760cb.

**Pull request merged**
