### PR TITLE
Pipes core

### PR DESCRIPTION
**Pull request by creatorrr**
**CLOSED** in favour of cdnjs/cdnjs/pull/11496

> 
> Checklist for **Pull request** or **lib adding request issue** follows the conventions.
> 
> Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.
> 
> # Profile of the lib
>  * Git repository (required): https://github.com/pipesjs/core
>  * Official website (optional, not the repository): http://pipes.js.org/core
>  * NPM package url (optional):
>  * License and its reference: MIT
>  * GitHub / Bitbucket popularity (required):
>    - Count of watchers: 1
>    - Count of stars: 2
>    - Count of forks: 0
>  * NPM download stats (optional):
>    - Downloads in the last day:
>    - Downloads in the last week:
>    - Downloads in the last month:
> 
> # Essential checklist
>  * [x] I'm the author of this library
>    * [ ] I would like to add link to the page of this library on CDNJS on website / readme
>  * [ x] This lib was not found on cdnjs repo
>  * [ x] No already exist / duplicated issue and PR
>  * [ ] The lib has notable popularity
>    * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
>    * [ ] More than 500 downloads stats per month on npm registry
>  * [x ] Project has public repository on famous online hosting platform (or been hosted on npm)
> 
> # Auto-update checklist
>  * [x ] Has valid tags for each versions (for git auto-update)
>  * [ x] Auto-update setup
>  * [ x] Auto-update target/source is valid.
>  * [ x] Auto-update filemap is correct.
> 
> # Git commit checklist
>  * [x ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
>  * [x ] The parent of the commit(s) in the PR is not old than 3 days.
>  * [x ] Pull request is sending from a non-master branch with meaningful name.
>  * [x ] Separate unrelated changes into different commits.
>  * [x ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
>  * [x ] Close corresponding issue in commit message
>  * [x ] Mention related issue(s), people in commit message, comment.
>

### CODE REVIEW

**Comment by dakshshah96** [comment]
@creatorrr The library doesn't meet our minimum requirements. Please wait for it to gain popularity and then we can add it to CDNJS.

cc @PeterDaveHello

**Comment by dakshshah96** [comment]
Hey @creatorrr,

Since your library doesn't meet the minimum popularity requirements, I'm closing this PR right now. Thanks for wanting to be a part of cdnjs but we have limitations on what libraries we can host.

For your reference, the notable popularity criteria is — GitHub (more than 100 stars) and/or npm (more than 500 downloads per month).

Don't forget to ping any one of us once the library has notable popularity. All the best!

**Comment by PeterDaveHello** [comment]
This lib seems to have good documentation and structure, if @creatorrr you'd like to fix the pull request, I can accept it, thanks!

**Comment by dakshshah96** [comment]
@PeterDaveHello Great!

@creatorrr We can reopen this pull request if you'd still like to work on it :)

**Comment by creatorrr** [comment]
@PeterDaveHello Thank you! I really appreciate that you took the time to review the lib. @dakshshah96 yes, please re-open the request. I'll make the required changes and push again.

**Comment by dakshshah96** [comment]
@creatorrr It's all yours :)

**Comment by PeterDaveHello** [comment]
@creatorrr may I know that if you're using GitHub web gui to send this pull request or you're working locally? So that we can know that how can we help you. Thanks.

**Comment by creatorrr** [comment]
Closing in favor of cdnjs/cdnjs/pull/11496 
Cc/ @dakshshah96 @PeterDaveHello

**Pull request closed without merging**
