### PR TITLE
[author] [ajv] updated bundles

### PR DESCRIPTION
**Pull request by epoberezkin**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Thanks @epoberezkin

**Comment by PeterDaveHello** [comment]
BTW I manually added the files in https://github.com/cdnjs/cdnjs/commit/9ba862b90f600012cd27a1520104368eda338e5e

**Comment by epoberezkin** [comment]
Thanks! That was fast :)

**Comment by PeterDaveHello** [comment]
Thank you too @epoberezkin

**Pull request merged**
