### PR TITLE
minified and update benchmark

### PR DESCRIPTION
**Pull request by Amomo**
Hi @maruilian11 , From #5195, I add the minify files to each version of benchmark, and point benchmark.js to benchmark.min.js in package.json.
Additionally, I update the repository field in package.json.
Would you mind checking this PR for me? Thank you~ :-)

### CODE REVIEW

**Comment by maruilian11** [comment]
@Amomo i think it's great, but i think next time your first commit can be "minify benchmark" to aviod too long commit msg, and sorry i'm late can u rebase it and tag me, thank u.

**Comment by Amomo** [comment]
@maruilian11 thanks for your suggestion~
I have modified the commit message and rebased the branch.
Could you check it again? thank you~ :-D

**Comment by maruilian11** [comment]
@PeterDaveHello i think it's ok.

**Comment by Amomo** [comment]
@maruilian11 sorry, I am not sure what is "auther edit" ?
Could you give me a hint?

**Comment by maruilian11** [comment]
@Amomo like this one.
https://github.com/cdnjs/cdnjs/commit/48726834adb8784df98e1820847b2eaf25fb9a32

**Comment by PeterDaveHello** [comment]
What's your minify tool?

**Comment by Amomo** [comment]
When I need to minify over 3 files, I use this.
http://lisperator.net/uglifyjs/

**Pull request merged**
