### PR TITLE
add clockpicker with git auto-update config

### LINKED ISSUE #7997: [Request] Add clockpicker
**Library name:** clockpicker
**Git repository url:** https://github.com/weareoutman/clockpicker
**npm package url(optional):** 
**License(s):** MIT (https://github.com/weareoutman/clockpicker/blob/gh-pages/LICENSE)
**Official homepage:** http://weareoutman.github.io/clockpicker/
**Wanna say something? Leave message here:**
This is a really awesome and useful Bootstrap time picker library, would love to see it included :)

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by nolsherry**
@pvnr0082t, please help me to review this pull request, thanks!

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/weareoutman/clockpicker
 * Official website (optional, not the repository): https://weareoutman.github.io/clockpicker/
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 1496
   - Count of watchers: 77
   - Count of forks: 334
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [X] This lib was not found on cdnjs repo
 * [X] No already exist / duplicated issue and PR
 * [X] The lib has notable popularity
   * [X] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [X] Has valid tags for each versions (for git auto-update)
 * [X] Auto-update setup
 * [X] Auto-update target/source is valid.
 * [X] Auto-update filemap is correct.

# Git commit checklist
 * [X] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [X] The parent of the commit(s) in the PR is not old than 3 days.
 * [X] Pull request is sending from a non-master branch with meaningful name.
 * [X] Separate unrelated changes into different commits.
 * [X] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [X] Close corresponding issue in commit message
 * [X] Mention related issue(s), people in commit message, comment.

close #7997, cc @weareoutman

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@nolsherry don't forget to assign PR.

**Comment by pvnr0082t** [comment]
@nolsherry Please add `keywords` in package.json.

**Comment by nolsherry** [comment]
@pvnr0082t, I have added ```keywords``` in package.json, please help me to review this pull request again, thank you!

**Comment by PeterDaveHello** [comment]
@nolsherry you should assign this PR to him, not just tag him.

**Comment by pvnr0082t** [comment]
@nolsherry There is no license in `package.json`. Please add it.

**Comment by nolsherry** [comment]
@pvnr0082t, I have added the license in```package.json```, please help me to review this pull request, thanks!

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Comment by PeterDaveHello** [comment]
As a practice, @kennynaoh please teach @nolsherry use git auto-update to get all the versions and add them in the same commit.

**Comment by nolsherry** [comment]
@PeterDaveHello, I have use git auto-update to get all the versions and them in the same commit.
Please help me to review the pull request, thanks!

**Comment by PeterDaveHello** [comment]
@nolsherry Call your reviewer first.

**Comment by nolsherry** [comment]
@pvnr0082t, I have use git auto-update to get all the versions and them in the same commit.
Please help me to review the pull request, thanks!

**Comment by pvnr0082t** [comment]
@nolsherry Where? I didn't see the all versions you got except v0.0.7.

**Comment by nolsherry** [comment]
@pvnr0082t, sorry~ I have updated all the versions and them in the same commit.
Please help me to review the pull request, thanks!

**Comment by pvnr0082t** [comment]
@nolsherry Please remove version of commit message.

**Comment by nolsherry** [comment]
@pvnr0082t, I have removed the version of commit message.
Please help me to review this pull request, thanks!

**Comment by pvnr0082t** [comment]
@PeterDaveHello I think this PR is ok. Please review it again, thank you.

**Pull request merged**
