### PR TITLE
Add vectorious w/ npm auto-update

### LINKED ISSUE #10013: [Request] [author] Add vectorious
**Library name:** vectorious
**Git repository url:** https://github.com/mateogianolio/vectorious
**npm package url(optional):** https://npmjs.com/package/vectorious
**License(s):** MIT
**Official homepage:** https://github.com/mateogianolio/vectorious
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by pvnr0082t**
Pull request for issue: #10013
@kennynaoh @x09326 Please help me review this pull request, thank you.
Manually add old versions because the filename with version number and add symbolic link for versions without "vectorious.min.js"

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/mateogianolio/vectorious
 * Official website (optional, not the repository): 
 * NPM package url (optional): https://www.npmjs.com/package/vectorious
 * License and its reference: MIT, https://github.com/mateogianolio/vectorious/blob/master/LICENSE.md
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 372
   - Count of watchers: 14
   - Count of forks: 20
 * NPM download stats (optional):
   - Downloads in the last day: 1
   - Downloads in the last week: 195
   - Downloads in the last month: 648

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #10013, cc @mateogianolio

### CODE REVIEW

**Comment by kennynaoh** [comment]
@PeterDaveHello Should we need to add source file `vectorious.js` in this case? Thanks!

**Comment by PeterDaveHello** [comment]
Of course, why not?

**Comment by pvnr0082t** [comment]
@kennynaoh @x09326 I have added source file and modified filemap. Please help me review it again, thank you.

**Comment by kennynaoh** [comment]
LGTM

**Comment by pvnr0082t** [comment]
@kennynaoh @x09326 I have removed src file and added symbolic link for versions without `vectorious.min.js`. Please help me review it again, thank you.

**Comment by kennynaoh** [comment]
LGTM

**Comment by x09326** [comment]
LGTM
ping @PeterDaveHello

**Comment by mateogianolio** [comment]
Sorry, should have mentioned that the files need to be bundled to work. How do I notify you if I add a source map or an unminified version?

**Comment by pvnr0082t** [comment]
Hi @mateogianolio,
Sorry, I didn't get you. Do you mean maybe you will add source map or unminified file for the future release? Just put the distributed purpose files under `dist` folder, the auto-updater will fetch the files follow auto-update config, in this case, fetch all files under `dist` folder.

**Comment by mateogianolio** [comment]
Yes, awesome! Thank you.

**Comment by PeterDaveHello** [comment]
@mateogianolio thanks for your help!

**Comment by pvnr0082t** [comment]
I have rebased on the latest master branch. Please help me review it, thanks. ping @PeterDaveHello

**Pull request merged**
