### PR TITLE
Update auto-update config of outdated-browser

### PR DESCRIPTION
**Pull request by evromalarkey**
+ Including lang subfolder

Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/burocratik/outdated-browser
 * Official website (optional, not the repository): http://outdatedbrowser.com/en
 * NPM package url (optional):
 * License and its reference:
 * GitHub / Bitbucket popularity (required):
   - Count of watchers:
   - Count of stars:
   - Count of forks:
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by extend1994** [comment]
Hi @evromalarkey Thanks for the request. Unfortunately, cdnjs doesn't serve html files. You can refer https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md#1-policy-rules-and-guidelines. And there is also one case you can see in https://github.com/cdnjs/cdnjs/pull/4435.

**Comment by evromalarkey** [comment]
oh, I didn't know. Well it's a pity, because without the language support it's very limiting use this library from cdnjs

**Comment by sufuf3** [comment]
@PeterDaveHello We can't add *.html
So what can we do for this PR? Close it?
Thank you.

**Comment by evromalarkey** [comment]
I guess you can close it, apparently it wouldn't work as I wanted anyway. IE would not load external html files, so I came up with different way.

**Comment by sufuf3** [comment]
@evromalarkey Great!
Then, I'll close this PR.
Thank you. :)

**Pull request closed without merging**
