### PR TITLE
add x18n@2.0.1 w/ npm autoupdate

### PR DESCRIPTION
**Pull request by pvnr0082t**
PR for #8011 
@kennynaoh Please help me review this pull request, thank you.

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/florian/x18n
 * Official website (optional, not the repository):
 * NPM package url (optional): https://www.npmjs.com/package/x18n
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 313
   - Count of watchers: 17
   - Count of forks: 13
 * NPM download stats (optional):
   - Downloads in the last day: 3
   - Downloads in the last week: 25
   - Downloads in the last month: 105

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

cc #8011

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
The title shouldn't be so long.

**Comment by kennynaoh** [comment]
Should `cc #8011, cc @florian` in commit message need to write in new line?
Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh nope

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I think this PR is correct.
Please help me review it again.
Thanks.

**Pull request merged**
