### PR TITLE
Add flexMenu@1.4.2 w/ git auto-update

### LINKED ISSUE #9740: [Request] Add flexMenu
**Library name:** flexMenu
**Git repository url:** https://github.com/352Media/flexMenu/
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://352media.github.io/flexMenu/
[flexMenu-master.zip](https://github.com/cdnjs/cdnjs/files/612660/flexMenu-master.zip)

**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by NiniHsu**
Pull request for issue: #9740
Related issue(s): #9414
@kennynaoh please help me review this PR, thank you!
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/352Media/flexMenu/
 * Official website (optional, not the repository): http://352media.github.io/flexMenu/
 * NPM package url (optional):
 * GitHub / Bitbucket popularity (required):
   - Count of stars: 75
   - Count of watchers: 18
   - Count of forks: 44
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update)
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

close #9740, cc #9414, @rdebeasi

### CODE REVIEW

**Comment by kennynaoh** [comment]
@NiniHsu Please fill up the detailed information in comment table.

**Comment by NiniHsu** [comment]
@kennynaoh I modified it. Please review the PR.
Thank you!

**Comment by NiniHsu** [comment]
@kennynaoh I added it. Please review the PR.
Thank you!

**Comment by kennynaoh** [comment]
LGTM, ping @cdnjs/intern2

**Comment by PeterDaveHello** [comment]
@pvnr0082t then you should give this to me

**Comment by PeterDaveHello** [comment]
Thanks for all your contribution!

**Pull request merged**
