### PR TITLE
[update] Three.js r70

### PR DESCRIPTION
**Pull request by luigimannoni**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please tell us where did you get these files, thanks.

**Comment by luigimannoni** [comment]
Hello,
sorry I should have included that in the commit description.

It is the new release of threejs, straight from his maintainer github repo: https://github.com/mrdoob/three.js

More precisely:
https://github.com/mrdoob/three.js/blob/master/build/three.js
https://github.com/mrdoob/three.js/blob/master/build/three.min.js

**Comment by PeterDaveHello** [comment]
Okay @luigimannoni, thanks for your explain, and I also found that we already have auto-update config for it, it may be just waiting to be audited, so I may not merge this commit, just let you know, thanks!

**Comment by luigimannoni** [comment]
Oh sorry, thought the autoupdate wasn't working yet for github repositories :)

You can reject this pull request,
Thanks!

**Comment by PeterDaveHello** [comment]
It's okay, I just audit the update result and commit in d822f22 :)

**Pull request closed without merging**
