### PR TITLE
add license of tablesort, cc #9248

### PR DESCRIPTION
**Pull request by honestree**
https://github.com/tristen/tablesort/blob/gh-pages/LICENCE

### CODE REVIEW

**Comment by honestree** [comment]
@x09326 
please help me review it.

**Comment by x09326** [comment]
LGTM
ping @cdnjs/intern2

**Comment by pvnr0082t** [comment]
@honestree It's not easy to know the license is `MIT` in this `License` file. You can also paste https://github.com/tristen/tablesort#licence as reference next time.

**Comment by pvnr0082t** [comment]
LGTM

**Pull request merged**
