### PR TITLE
Update embedly-jquery license identify format

### PR DESCRIPTION
**Pull request by programmiri**
Issue #11931

Pull request for issue: #
Related issue(s): # #

Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Profile of the lib
 * Git repository (required): https://github.com/embedly/embedly-jquery
 * Official website (optional, not the repository):
 * NPM package url (optional):
 * License and its reference: "BSD-3-Clause"
 * GitHub / Bitbucket popularity (required):
   - Count of watchers: 14
   - Count of stars: 309
   - Count of forks: 70
 * NPM download stats (optional):
   - Downloads in the last day:
   - Downloads in the last week:
   - Downloads in the last month:

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [ ] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 200 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 800 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

# Git commit checklist
 * [ ] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [ ] The parent of the commit(s) in the PR is not old than 3 days.
 * [ ] Pull request is sending from a non-master branch with meaningful name.
 * [ ] Separate unrelated changes into different commits.
 * [ ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [ ] Close corresponding issue in commit message
 * [ ] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Squashing into only one commit now.

**Comment by maruilian11** [comment]
@programmiri Please help us fill the lib in in the init comment to help other reviewers review more quickly. Thanks.

**Comment by programmiri** [comment]
@maruilian11 I edited the first comment, I hope that's right now?

**Comment by sufuf3** [comment]
@extend1994 @hare1039 @qwe19272375 @pvnr0082t 
Please help review this PR, Thank you.

**Comment by PeterDaveHello** [comment]
@maruilian11 why would you insert your commit here? I don't get it, shouldn't you ask if the contributor wants to do it or not first?

**Comment by maruilian11** [comment]
@programmiri Sorry for that.
@PeterDaveHello Do I need to remove the commit I made?

**Comment by PeterDaveHello** [comment]
@maruilian11 of course you should remove it and send another PR.

**Comment by maruilian11** [comment]
@PeterDaveHello I remove the commit made by me. Could you please take a look at this PR?

**Pull request merged**
