### PR TITLE
Add license of slidesjs, cc #5500

### PR DESCRIPTION
**Pull request by nolsherry**
Reference: https://github.com/nathansearles/Slides#license

### CODE REVIEW

**Comment by nolsherry** [comment]
@kennynaoh please help me review this PR, thanks!

**Comment by kennynaoh** [comment]
LGTM

**Comment by kennynaoh** [comment]
@pvnr0082t , Please help review this PR, thanks!

**Comment by nolsherry** [comment]
@kennynaoh @pvnr0082t I have modified `lisense` to `license`, please help me review this PR, thanks!

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM

**Pull request merged**
