### PR TITLE
add bootstrap-ui-datetime-picker w/ npm auto-update

### PR DESCRIPTION
**Pull request by maruilian11**
**npm package url:** https://www.npmjs.com/package/bootstrap-ui-datetime-picker
**4,027 downloads in the last month**
@PeterDaveHello  could u help me check this PR for #7673  ? thank you!
Checklist for **Pull request** or **lib adding request issue** follows the conventions.

Note that if you are using a distribution purpose repository/package, please also provide the url and other related info like popularity of the source code repo/package.

# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [x] This lib was not found on cdnjs repo
 * [x] No already exist / duplicated issue and PR
 * [x] The lib has notable popularity
   * [x] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [x] More than 500 downloads stats per month on npm registry
 * [x] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [x] Has valid tags for each versions (for git auto-update) 
 * [x] Auto-update setup
 * [x] Auto-update target/source is valid.
 * [x] Auto-update filemap is correct.

# Git commit checklist
 * [x] The first line of commit message is less then 50 chars, be clean and clear, easy to understand.
 * [x] The parent of the commit(s) in the PR is not old than 3 days.
 * [x] Pull request is sending from a non-master branch with meaningful name.
 * [x] Separate unrelated changes into different commits.
 * [x] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
 * [x] Close corresponding issue in commit message
 * [x] Mention related issue(s), people in commit message, comment.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Review by yourself, too simply mistake here, and please put library name at the head of `package.json`.

**Comment by maruilian11** [comment]
@Piicksarn I have added versions from git repo which are not on npm pacakge. although we don't support partly minified in certain directory, I minified ` bootstrap-ui-datetime-picker.tpls.js` because our minify function won't minify the file which is already minified, so `bootstrap-ui-datetime-picker.min.js` made by the author won't be influence. 

since some version miss on npm package, I will open an issue to ask the author if he can maintain the latest version on npm package.
could you help me check this PR? thanks!

**Comment by Piicksarn** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
What's the reason why `datetime-picker.tpls.js` in some versions been minified but some versions not? @Piicksarn did you really review this PR?

**Comment by PeterDaveHello** [comment]
`datetime-picker.tpls.min.js`s should be removed here, it's small enough.

**Comment by maruilian11** [comment]
@Piicksarn I removed all `tpls.min.js`, please help me check this PR again, thanks!

**Comment by PeterDaveHello** [comment]
If there is no missing version, just say "old versions" instead of listing them all.

**Comment by maruilian11** [comment]
ok.

**Pull request merged**
