### PR TITLE
[new] [author] Initial release of tanner-bootstrap theme - v1.0.0

### PR DESCRIPTION
**Pull request by TheTannerRyan**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Same problem again @TheTannerRyan, there is no `dist` under your project but you refer basePath to it in the config.

**Comment by TheTannerRyan** [comment]
@PeterDaveHello What should I change the basePath to?

**Comment by PeterDaveHello** [comment]
basePath is okay, but you should better use git's tag to recognize different versions, currently, you use the version number as its folder name, it's not a good method, maybe you can change folder 1.0.0 to dist, thanks.

**Comment by TheTannerRyan** [comment]
@PeterDaveHello What would I change the version to because then I get a npm test error?

**Comment by PeterDaveHello** [comment]
Sorry that I didn't get your point here, did you mean it'll may the test failed?

**Comment by TheTannerRyan** [comment]
If I change the folder 1.0.0 to dist and then use the tags, CircleCl will fail saying that it can not find the folder 1.0.0.

**Comment by PeterDaveHello** [comment]
Okay, I think there was a misunderstanding, I meant change the folder in your project's repo, not in cdnjs.

**Comment by TheTannerRyan** [comment]
So do I have the folder 1.0.0 inside the dist folder in my repo, or do I just have the dist folder with the files inside?

**Comment by PeterDaveHello** [comment]
In your repo only. In cdnjs name the folder with its version number.

**Comment by TheTannerRyan** [comment]
With my repo, do I have it like this:   dist -> - 1.0.0 -> (files)
Or just: dist -> (files)

**Comment by PeterDaveHello** [comment]
`dist -> (files)`

**Pull request closed without merging**
