### PR TITLE
Change animejs to use git auto-update, close #9905

### LINKED ISSUE #9905: [Request] updete animejs
**Library name:**  animejs
**Git repository url:** https://github.com/juliangarnier/anime
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://anime-js.com
**Wanna say something? Leave message here:**
Thank you!
=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

### PR DESCRIPTION
**Pull request by maruilian11**
Pull request for issue: #9905
@Piicksarn @cdnjs/intern2 Could you please help me review this PR? Thanks!

### CODE REVIEW

**Comment by pvnr0082t** [comment]
LGTM

**Comment by kennynaoh** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
@kennynaoh you should ping me next time ... let's rebase with the latest master branch then we can merge it.

**Comment by maruilian11** [comment]
@PeterDaveHello  I rebase the branch with the latest master branch, thank you.

**Pull request merged**
