### PR TITLE
Added Cleverbot.io.js v1.0

### PR DESCRIPTION
**Pull request by dtesler**
Cleverbot.io.js standard and minified

Built for [cleverbot.io](https://cleverbot.io)

### CODE REVIEW

**Comment by drewfreyling** [comment]
There are no changes in this commit?

**Comment by dtesler** [comment]
What do you mean?

**Comment by albertyw** [comment]
There are two commits for this pull request and the second one reverts the first one.

**Comment by dtesler** [comment]
The revert commit was accidental

**Comment by dtesler** [comment]
@drewfreyling Sorry, I added a commit that reverts the first accidental revert :/

**Comment by PeterDaveHello** [comment]
Please squash them into only one commit as our document said, thanks!

**Comment by PeterDaveHello** [comment]
And would you please add auto-update for it?

**Comment by dtesler** [comment]
How do I add auto update?

**Comment by PeterDaveHello** [comment]
Use npm package and read readme file, or add tags in git repo and see #3638.

**Comment by dtesler** [comment]
Will do first thing tomorrow morning.  Thanks Pete.

**Comment by PeterDaveHello** [comment]
:+1:

**Pull request closed without merging**
