### PR TITLE
[new] add zoom@1.7.14 with git auto-update, close #5090

### LINKED ISSUE #5090: [Request] https://github.com/jackmoore/zoom/tree/master

### PR DESCRIPTION
**Pull request by Amomo**
Hi @LeaYeh , I add a new lib with git auto-update from the request #5090
Would you mind checking this PR for me?
Thank you~ :-)

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Any updates?

**Comment by LeaYeh** [comment]
i think it's fine.

**Comment by Amomo** [comment]
I have made this branch match to the latest master branch.

**Comment by Amomo** [comment]
@LeaYeh I have rebased it to latest master branch.
If it is ok, could you ping Peter for me? Thank you! :-D

**Comment by LeaYeh** [comment]
sorry for late, plz rebase it again and i will check it ASPS.

**Comment by Amomo** [comment]
@LeaYeh I have rebased it!
Could you come to check it again? Thank you! :-D

**Comment by LeaYeh** [comment]
ok.
@PeterDaveHello

**Comment by PeterDaveHello** [comment]
What's the reason why you used `jquery.zoom` but not `jquery-zoom`?

https://github.com/jackmoore/zoom/blob/master/package.json

**Comment by Amomo** [comment]
oops! I thought project name should be same with filename field at that time.
Now, I understand the reason to name a project's directory.
I will fix it right away~

**Comment by Amomo** [comment]
@LeaYeh I have made a correction.
Could you come to check this PR? Thank you~ :-D

**Comment by Amomo** [comment]
Hi @Piicksarn would you mind checking this PR for me?
Thank you~ :-D

**Comment by Amomo** [comment]
@LeaYeh , @Piicksarn I have rebase this commit to match latest master branch.
Would you mind checking this PR for me? Thank you~ :-D

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you please take a look at the PR?
thank you~

**Comment by PeterDaveHello** [comment]
Don't name it by your self :smiling_imp: you did it several times ...

**Pull request merged**
