### PR TITLE
add git auto-update config of oj.VimeoVideo

### PR DESCRIPTION
**Pull request by maruilian11**
**git repo url:** https://github.com/ojjs/oj.VimeoVideo
**Watch 1
  Star 1
 Fork 0**
@Amomo could you help me check out the PR for #6035 ? thank you~
- [ ] Not found on cdnjs repo
- [x] No already exist issue and PR
- [ ] Notable popularity
- [x] Project has public repository on famous online hosting platform (or been hosted on npm) 
- [x] Has valid tags for each versions (for git auto-update)
- [x] Auto-update setup
- [x] Auto-update target/source is valid.
- [x] Auto-update filemap is correct

### CODE REVIEW

**Comment by Amomo** [comment]
@maruilian11 could you separate it into 2 commit?

**Comment by maruilian11** [comment]
@Amomo but i just did one thing, didn't i? :joy:

**Comment by Amomo** [comment]
OH SORRY! I mistaken that line! 
@maruilian11 This PR is good, could you rebase it? Thank you. 😂

**Comment by PeterDaveHello** [comment]
...

**Comment by maruilian11** [comment]
@Amomo i have rebased it~

**Comment by Amomo** [comment]
@maruilian11 sorry for checking late.
Could you rebase it again? Thank you very much!

**Comment by maruilian11** [comment]
@Amomo i have rebased it~

**Comment by Amomo** [comment]
@PeterDaveHello I think this PR is fine, could you take a look?
Thank you! :-)

**Comment by maruilian11** [comment]
@PeterDaveHello could you take a look on this PR：）

**Pull request merged**
