### PR TITLE
Add Kule Lazy 3.1.160316

### PR DESCRIPTION
**Pull request by keicheng**
https://github.com/keicheng/kule.lazy/tree/v3.1.160316

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@keicheng See
cb443d4: add kule.lazy v3.1.160316 by PeterBot

**Comment by keicheng** [comment]
How fixed it?

**Comment by PeterDaveHello** [comment]
@keicheng No need to fix, bot added it.

**Comment by PeterDaveHello** [comment]
@keicheng The time diff of your PR and our bot's commit isn't so long, since there is auto-update config, you don't need to manually submit it.

**Comment by keicheng** [comment]
ok, thanks!

**Pull request closed without merging**
